### ISSUE TITLE
Few Mermaid diagram rendering issues in Windows High Contrast Black mode

### ISSUE THREAD

**Issue by sulabh-msft** [mermaid-js/mermaid#1003]
**Describe the bug**
Certain part of mermaid diagrams are not visible in Windows High Contrast Black mode Edge

**To Reproduce**
Steps to reproduce the behavior: ( Windows -> High Contrast Black mode and then open edge browser)
1. Go to [Gantt Chart](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbiAgICAgICBkYXRlRm9ybWF0ICBZWVlZLU1NLUREXG4gICAgICAgdGl0bGUgQWRkaW5nIEdBTlRUIGRpYWdyYW0gZnVuY3Rpb25hbGl0eSB0byBtZXJtYWlkXG5cbiAgICAgICBzZWN0aW9uIEEgc2VjdGlvblxuICAgICAgIENvbXBsZXRlZCB0YXNrICAgICAgICAgICAgOmRvbmUsICAgIGRlczEsIDIwMTQtMDEtMDYsMjAxNC0wMS0wOFxuICAgICAgIEFjdGl2ZSB0YXNrICAgICAgICAgICAgICAgOmFjdGl2ZSwgIGRlczIsIDIwMTQtMDEtMDksIDNkXG4gICAgICAgRnV0dXJlIHRhc2sgICAgICAgICAgICAgICA6ICAgICAgICAgZGVzMywgYWZ0ZXIgZGVzMiwgNWRcbiAgICAgICBGdXR1cmUgdGFzazIgICAgICAgICAgICAgIDogICAgICAgICBkZXM0LCBhZnRlciBkZXMzLCA1ZFxuXG4gICAgICAgc2VjdGlvbiBDcml0aWNhbCB0YXNrc1xuICAgICAgIENvbXBsZXRlZCB0YXNrIGluIHRoZSBjcml0aWNhbCBsaW5lIDpjcml0LCBkb25lLCAyMDE0LTAxLTA2LDI0aFxuICAgICAgIEltcGxlbWVudCBwYXJzZXIgYW5kIGppc29uICAgICAgICAgIDpjcml0LCBkb25lLCBhZnRlciBkZXMxLCAyZFxuICAgICAgIENyZWF0ZSB0ZXN0cyBmb3IgcGFyc2VyICAgICAgICAgICAgIDpjcml0LCBhY3RpdmUsIDNkXG4gICAgICAgRnV0dXJlIHRhc2sgaW4gY3JpdGljYWwgbGluZSAgICAgICAgOmNyaXQsIDVkXG4gICAgICAgQ3JlYXRlIHRlc3RzIGZvciByZW5kZXJlciAgICAgICAgICAgOjJkXG4gICAgICAgQWRkIHRvIG1lcm1haWQgICAgICAgICAgICAgICAgICAgICAgOjFkXG5cbiAgICAgICBzZWN0aW9uIERvY3VtZW50YXRpb25cbiAgICAgICBEZXNjcmliZSBnYW50dCBzeW50YXggICAgICAgICAgICAgICA6YWN0aXZlLCBhMSwgYWZ0ZXIgZGVzMSwgM2RcbiAgICAgICBBZGQgZ2FudHQgZGlhZ3JhbSB0byBkZW1vIHBhZ2UgICAgICA6YWZ0ZXIgYTEgICwgMjBoXG4gICAgICAgQWRkIGFub3RoZXIgZGlhZ3JhbSB0byBkZW1vIHBhZ2UgICAgOmRvYzEsIGFmdGVyIGExICAsIDQ4aFxuXG4gICAgICAgc2VjdGlvbiBMYXN0IHNlY3Rpb25cbiAgICAgICBEZXNjcmliZSBnYW50dCBzeW50YXggICAgICAgICAgICAgICA6YWZ0ZXIgZG9jMSwgM2RcbiAgICAgICBBZGQgZ2FudHQgZGlhZ3JhbSB0byBkZW1vIHBhZ2UgICAgICA6MjBoXG4gICAgICAgQWRkIGFub3RoZXIgZGlhZ3JhbSB0byBkZW1vIHBhZ2UgICAgOjQ4aCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19
) in Windows Edge browser and High Contrast black mode

Or 

1. Go to [Sequence Diagram](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgSm9oblxuICAgIHBhcnRpY2lwYW50IEFsaWNlXG4gICAgQWxpY2UtPj5Kb2huOiBIZWxsbyBKb2huLCBob3cgYXJlIHlvdT9cbiAgICBKb2huLS0-PkFsaWNlOiBHcmVhdCFcblxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0) in Windows Edge browser and High Contrast black mode

Or
1.  Go to [FlowChart](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBBW0hhcmQgZWRnZV0gLS0-fExpbmsgdGV4dHwgQihSb3VuZCBlZGdlKVxuICAgIEIgLS0-IEN7RGVjaXNpb259XG4gICAgQyAtLT58T25lfCBEW1Jlc3VsdCBvbmVdXG4gICAgQyAtLT58VHdvfCBFW1Jlc3VsdCB0d29dIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0) in Windows Edge browser and High Contrast black mode

**Expected behavior**
a. Gantt Chart
1.  The color contrast of the text present should be equal or greater than 7:1
2. The heading of the image as well as the text below should be seen in high contrast black theme.

b. Sequence Diagram
1.  Arrows message text/ line should be visible in high contrast black ( contrast ratio > 7:1)

c. FlowChart
1. Arrows should be visible in high contrast black ( contrast ratio > 7:1)

**Actual behavior**
a. Gantt
1: The color contrast of the text in Gantt Chart in high contrast black is below 7:1 
2: The heading of the image as well as the text below cannot be seen in high contrast black theme.

b. Sequence diagram
1. Color contrast ratio for the messageText /line is less than 7:1

FlowChart
1. The color contrast for the arrow in high contrast black is below 7:1

**Screenshots**
Gantt Chart ( High Contrast black -> Edge browser)
![image](https://user-images.githubusercontent.com/13728069/66889946-d0c95600-f001-11e9-8877-1c4f1537401f.png)

Sequence Diagram ( High Contrast black -> Edge browser)
![image](https://user-images.githubusercontent.com/13728069/66890110-85637780-f002-11e9-8167-f28ec5daaec5.png)

FlowChart
![image](https://user-images.githubusercontent.com/13728069/66890229-fe62cf00-f002-11e9-89e5-650b565979cd.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser Versions: Microsoft Edge 44.18362.329.0
 - Windows Version: Windows10​​​

Note: Similar issue is observed in Firefox as well ( in high contrast black mode

Mermaid version: 8.2.3

**Comment by chrismoran-bkt** [comment]
This has been (at least partially) addressed with my directives pr #1458 
With a small change to the dark theme css (see what I did in the sequence diagram section and replicate it for other graph types to fix the colors) the fix can be propagated to other graph types.

**Comment by jgreywolf** [comment]
@sulabh-msft Can you confirm is this is still an issue for you, and if the PR from @chrismoran-bkt addressed this - and if only in part what is still missing. (if there is still a part that is not working quite right, we should open a new issue for that one)

**Comment by jgreywolf** [comment]
I will be closing this issue within 30 days if I do not hear back from anyone that this is still an issue (i.e.: the PR mentioned above did not resolve the issue)
