### ISSUE TITLE
How to prevent edge overlap

### ISSUE THREAD

**Issue by abergmeier** [mermaid-js/mermaid#1006]
As much as I like mermaid - it often really handles edges in an erradic way.
Often I have to go through try and error to find a configuration, where the edges don't overlap.
Maybe I am too dumb but I could not yet make heads or tails for what logic mermaid uses to layout graphs.
Below is an example. Mermaid does a fine job except for overlapping edges (which I almost never want).

```
    graph TD
      linkStyle default interpolate basis
      dpc[DataPipeline Controller]
      pbc[Protobuf Controller]
      psc[Pseudonymization Controller]

      dpr((DataPipeline Resource))
      prrr((ProtobufPublic Resource))
      psr((Pseudonymization Resource))

      preg(Protobuf Registry)
      prbind(Protobuf Bindings)
      pinst(Pseudonymization Service)

      psc-->|spawns|pinst
      psc-->|reads|psr


      pbc-->|reads|prrr
      pbc-->|spawns|preg
      pbc-->|generates|prbind

      dpc-.->|creates|psr
      dpc-.->|creates|prrr
      dpc-->|reads|dpr
```

**Comment by Dunning-Kruger** [comment]
I assume this is what you mean by edge overlap, right?
![image](https://user-images.githubusercontent.com/1564825/66932586-d9bc2680-f005-11e9-96e4-4914163f8093.png)

**Comment by abergmeier** [comment]
> I assume this is what you mean by edge overlap, right? 

Yes.

**Comment by CAFxX** [comment]
Another example of erratic edge behaviors:

- on the left, edge overlaps unrelated node
- on the right, two edges gratuitously cross and overlap

![image](https://user-images.githubusercontent.com/408018/69105662-53d14680-0aaf-11ea-971f-06411dfbe385.png)

```mermaid
graph LR;
subgraph gateway
    gw-dev
    gw-pr1
    gw-pr2
end
subgraph service1
    svc1-dev
    svc1-pr1
end
subgraph service2
    svc2-dev
    svc2-pr2
end
sre --> gw-dev
gw-dev --> svc1-dev
gw-dev --> svc2-dev
svc1-dev --> svc2-dev
svc2-dev --> svc3-dev
qa --> gw-pr1
gw-pr1 --> svc1-pr1
gw-pr1 --> svc2-dev
svc1-pr1 --> svc2-dev
dev --> gw-pr2
gw-pr2 --> svc1-dev
gw-pr2 --> svc2-pr2
svc2-pr2 --> svc3-dev
```

**Comment by knsv** [comment]
If we render using dagre + graphlib but not dagre-js we could expose more options layout to the synax. (https://github.com/dagrejs/dagre/wiki) Like ranker and align for instance.

**Comment by gowrav-scienaptic** [comment]
Any update on this?

**Comment by jgreywolf** [comment]
After discussion we have determined that this will be closed as "wont fix" at this time, due to the fact that the underlying libraries currently used do not support this
