### ISSUE TITLE
auto generate sql scripts

### ISSUE THREAD

**Issue by lastlink** [mermaid-js/mermaid#1016]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be great if following a specific format for database UML diagrams that we could generate sql scripts for a db schema.  

**Describe alternatives you've considered**
LucidCharts does this with their entity context uml diagrams for postgres, sqllite, and mysql

**Comment by Dunning-Kruger** [comment]
I'm not sure this is mermaid's focus. It could be something else built on top of mermaid...

**Comment by jgreywolf** [comment]
Closing this issue as outside the scope of mermaid
