### ISSUE TITLE
State diagram long name renders incorrect as description compared to plantuml

### ISSUE THREAD

**Issue by Pyrolistical** [mermaid-js/mermaid#1022]
Given
```
stateDiagram

[*] --> S1
state "Some long name" as S1
```
renders
![Screen Shot 2019-10-22 at 11 39 11](https://user-images.githubusercontent.com/463642/67318627-9871be00-f4c0-11e9-9c4c-6c19c9c96244.png)

But the equivalent diagram in plantuml is
```
@startuml

[*] --> S1
state "Some long name" as S1

@enduml
```
renders
![SoWkIImgAStDuUAArefLqDMrKmWsv08AbgGgA0NdvwOgvEJdfIla9UQcAYaa5eCakHnIyrA0EW00](https://user-images.githubusercontent.com/463642/67318765-c1924e80-f4c0-11e9-9c75-f0136745be5e.png)

The plantuml way of adding a description is
```
@startuml

[*] --> S1
state "Some long name" as S1: some description

@enduml
```
renders
![SoWkIImgAStDuUAArefLqDMrKmWsv08AbgGgA0NdvwOgvEJdfIla9UQcAYaa5WCbhHIAGS8fgSN9HPa59PdvULnS3gbvAK0p0000](https://user-images.githubusercontent.com/463642/67318842-dff84a00-f4c0-11e9-8672-7c19d668917c.png)

I used https://www.planttext.com to produce the plantuml diagrams

**Comment by Dunning-Kruger** [comment]
Kept as a bug since, I believe, the original intention was to utilize plantuml's syntax.

**Comment by knsv** [comment]
Part of release 8.4.1
