### ISSUE TITLE
State diagram failed to render \n in transition labels compared to plantuml

### ISSUE THREAD

**Issue by Pyrolistical** [mermaid-js/mermaid#1023]
Given
```
stateDiagram

[*] --> S1
S1 --> S2: long line using html<br/>shouldn't work
S1 --> S3: long line using escape\nshould work
```
renders
![Screen Shot 2019-10-22 at 12 09 09](https://user-images.githubusercontent.com/463642/67321735-c527d480-f4c4-11e9-8e59-fb31fd6b427a.png)

but with plantuml given
```
@startuml

[*] --> S1
S1 --> S2: long line using html<br/>shouldn't work
S1 --> S3: long line using escape\nshould work

@enduml
```
renders
![SoWkIImgAStDuUAArefLqDMrKmWsv0esXB2Ch1HoylFI5N8oyr8LIeipWSoCajmScwGYVRlYZFpId9GyzHA5yloYRBWMOqmjgSN9YGMfCNaG7H3bN5mEgNafG7i1](https://user-images.githubusercontent.com/463642/67321789-da9cfe80-f4c4-11e9-9c8e-81f525994354.png)

**Comment by Dunning-Kruger** [comment]
Kept as a bug since, I believe, the original intention was to utilize plantuml's syntax.

**Comment by forivall** [comment]
I found that `<br>` works instead of `<br/>`

**Comment by knsv** [comment]
I will make <br/> and <br> work even though they won't in plantUML. This is they work in sequence diagrams so it will be consistent in that sense.

New lines there are a bit trickier... will need to think about those, they will mess upp the grammar a bit as this:
```

[*] --> S1
S1 --> S2: long line using html<br/>shouldn't work
S1 --> S3: long line using escape\nshould work
```

is really the same as the code below when mermaid receives it. Should work will be poercieved as two new states.
```
[*] --> S1
S1 --> S2: long line using html<br/>shouldn't work
S1 --> S3: long line using escape
should work
```

**Comment by Pyrolistical** [comment]
Then you are missing an encoding step between the raw text and by the time mermaid gets it.

Makes me wonder if there's a security issue if there's a form of automatic interpretation of `\n`. What else is unintentionally interpreted?

**Comment by forivall** [comment]
PlantUML automatically interprets `\n`. (the escape character, not the literal ␤)

**Comment by knsv** [comment]
In this case it will be up to the integrator to handle the escaping but then br, br/ and \n could be supported.

**Comment by knsv** [comment]
Part of release 8.4.1
