### ISSUE TITLE
Some logs are out of logLevel

### ISSUE THREAD

**Issue by liyuanqiu** [mermaid-js/mermaid#1024]
**Describe the bug**
These `console.warn` are not controlled by `logLevel` option:
https://github.com/knsv/mermaid/blob/0157f665a305b0616e7932360a2f9fb2fa154668/src/diagrams/state/stateRenderer.js#L281
https://github.com/knsv/mermaid/blob/2da55993e0e7f5a35c8d2b3132d4588c1189a149/src/diagrams/state/shapes.js#L109
They print logs to browser no matter what `logLevel` is.

**To Reproduce**
1. Open state diagram example page: https://mermaidjs.github.io/#/stateDiagram

2. Open browser console, check the logs at `warn` level.
```
⚠️ Diagram node Active stateRenderer.js:281:10
⚠️ 98.68333435058594 32 shapes.js:109:10
```
Same issue in my own project that uses state diagram.

**Expected behavior**
Remove those warning logs, or make them be controlled by `logLevel`.

**Screenshots**
![image](https://user-images.githubusercontent.com/24999464/67356009-71cc8980-f58b-11e9-9b7b-1d0ef0e06140.png)

![image](https://user-images.githubusercontent.com/24999464/67356003-6a0ce500-f58b-11e9-8bec-a0b6951a338a.png)

**Desktop (please complete the following information):**
 - OS: [macOS catalina]
 - Browser [Firefox]
 - Version [69]

**Comment by knsv** [comment]
Thanks @liyuanqiu, I will remove these.

**Comment by knsv** [comment]
Part of release 8.4.1
