### ISSUE TITLE
Update Pie Charts to render Legends and Percentage for each section

### ISSUE THREAD

**Issue by ashishjain0512** [mermaid-js/mermaid#1027]
**Is your feature request related to a problem? Please describe.**
The current Pie Chart only shows labels but gives no context of the percentage a particular section has.

**Describe the solution you'd like**
Pie Chart must render the percentage each section makes and for better UX and visibility the labels should be rendered separately as legends to accommodate long texts for labels as well.

**Comment by knsv** [comment]
Part of release 8.4.1
