### ISSUE TITLE
IE11 Compatibility: IE throws syntax errors on mermaid.js

### ISSUE THREAD

**Issue by penenkel** [mermaid-js/mermaid#1030]
I'm trying to use mermaid with an IE11 browser. Unfortunately the IE throws syntax errors when importing the mermaid.js script (also happens when importing mermaid.min.js). Apparently it is a lot more picky than modern browsers. I'm hoping that this can be fixed by tweaking the transpilation settings, but im no js expert.

I have haphazardly tried several of the newer mermaid versions 8.1, 8.4 from several CDNs using the following example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <div class="mermaid">
      graph LR; A --- B; B-->C[fa:fa-ban forbidden]; B-->D(fa:fa-spinner);
    </div>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@8.4.0/dist/mermaid.js"></script>
    <script>
      mermaid.initialize({ startOnLoad: true });
    </script>
  </body>
</html>
```
Resulting in:
> Syntaxerror: mermaid.js (9909,59)

> const generateForCustomCharacters = (length, characters) => {

Btw. I would have expected that `=>` would have been transpiled away, as I assume it is a relatively new language feature.

**Comment by GDFaber** [comment]
AFAIK IE11 does not support ECMA 6 nor promises (took the info from caniuse.com). I had to include bluebird and a fetch polyfill for c3.js to work properly in IE11, could there be any polyfills that take care of this for mermaid as well?

**Comment by nothingismagick** [comment]
It seems that https://github.com/knsv/mermaid/blob/master/babel.config.js is just transpiling for node (although I assume thats just for jest). One of the problems with switching e2e to cypress is that chrome is virtually es2018 compliant - and for IE11 arrow functions (among MANY, MANY other things) just don't exist. Although Cypress is awesome for compliance testing and visual diffing it is not ideal for device / os / browser testing.

**Comment by penenkel** [comment]
So, is it feasible to change the transpilation settings? Or do I have to figure out a solution on my end?

I can certainly understand not wanting to support ancient legacy browsers, unfortunately there are still some situations where the IE cannot be avoided :/

**Comment by AshokkumarPesarlanka** [comment]
what is the approach to make it work in IE 11 as well ?
or can you please confirm it will not work in IE 11.
