### ISSUE TITLE
strict mode checks fails with latest version 8.4.0

### ISSUE THREAD

**Issue by rajasekaran2003** [mermaid-js/mermaid#1031]
Error		Strict-mode does not allow duplicate property names: rankdir
Error		Strict-mode does not allow duplicate property names: padding

**Comment by knsv** [comment]
Thanks for reporting this. I will add some more rules to the code standard, for instance the no-dupe-keys.
https://eslint.org/docs/rules/no-dupe-keys

**Comment by knsv** [comment]
@rajasekaran2003 I think this has been fixed. Can you take a look and if it is ok, close the issue?

**Comment by rajasekaran2003** [comment]
Thanks
