### ISSUE TITLE
Letter "s" injected to the node ID

### ISSUE THREAD

**Issue by kickbk** [mermaid-js/mermaid#1038]
This could be my implementation, but has anyone experienced having the letter "s" injected to the node ID starting with version 8.2?

**Comment by dak** [comment]
It looks like this issue was introduced in 8.2.4 with the BREAKING CHANGE (why was this not a minor update?) that IDs could not be numbers. Also, what was the point of that change?

**Comment by Dunning-Kruger** [comment]
> It looks like this issue was introduced in 8.2.4 with the BREAKING CHANGE (why was this not a minor update?) that IDs could not be numbers. Also, what was the point of that change?

It might be a bug, not an intentional change. Could you provide some steps to reproduce the issue on the live editor?

**Comment by dak** [comment]
@Dunning-Kruger we just debugged this and are rushing out a fix, but I'll try to provide a simple test case. From our perspective, we were generating a uuid (at least for nodes), so sometimes, but not always, the id would get prepended with an 's' and subtly break.

**Comment by knsv** [comment]
Is there a fix in the horizon, if not I will look at this. Please let me know.

**Comment by knsv** [comment]
The underlying reason for this issue if that the ids for nodes in the graph is used as element ids in the generated SVG and css selectors is not allowed to start with a number. I don't want to disallow this ids starting with numbers as this would break graphs for end users and potentially break existing documentation out there. 

**I strongly discourage grammar changes that break existing diagrams** as this would interfere with peoples existing documentation.

There are al lot of small things that I would have done differently in the grammar if I knew then what I know now. :)

However I will fix this in a better way then the current way. There will be an id in the graph, lets call it the graph id. Then an internal id used by the dom. This will be documented and called something like mermaid-dom-id-${graphId}

**Comment by knsv** [comment]
Part release 8.4.2, please verify and reopen if problem remains.
