### ISSUE TITLE
Update NPM readme

### ISSUE THREAD

**Issue by klemmchr** [mermaid-js/mermaid#1046]
As the Readme got reworked with #1045 it also needs to be updated on [npm](https://www.npmjs.com/package/mermaid). The images are broken currently because they are referenced by a relative path. They might need to be replaced with an absolute url.

**Comment by chris579** [comment]
Maybe we also should automate that. A little workflow updating the readme on npm when the readme in the repo changes.

**Comment by NeilCuzon** [comment]
hi guys! I've recently contributed to the docs, including some recent edits for the README.md, for mermaid and I would want to help out with this issue as well. 

however, I don't have any real experience with updating the documentation for npm. 
Point me in the right direction and I'll work on it.

**Comment by Dunning-Kruger** [comment]
@NeilCuzon Thank you for the good intentions but the issue is already assigned to someone with permission on NPM.
