### ISSUE TITLE
Add `package` to class diagram

### ISSUE THREAD

**Issue by queses** [mermaid-js/mermaid#1052]
**Is your feature request related to a problem? Please describe.**

Hello! *Иon-native English speaker warning*

I'm relative frequently drawing class diagrams. For now I'm using MagicDraw but I would like to try text-to-scheme solution.

I like your syntax for class diagrams and I would be very happy to use it for my work but I frequently using `packages` in my schemes. Like `class A` goes to `package X` and associated with `class B` that laying in `package Y`. 

**Describe the solution you'd like**

I would like to have a `package` extension for current syntax like:

```
package Sales {
  class Product {
    +int id
  }
  Product o-- Employees.Manager

package Employees {
  class Manager {
    +int id
  }
}
```

**Describe alternatives you've considered**
Do not see any

**Additional context**
None

**Comment by Dunning-Kruger** [comment]
Perhaps namespace instead or package?

**Comment by queses** [comment]
Well, I just sticked to MagicDraw and Java terms. Its absolutely okay if this thing will be called "namespace"

**Comment by chris579** [comment]
How does this look in MagicDraw? Could you provide a screenshot of the resulting diagram?

**Comment by queses** [comment]
Well there is two packages - "Специалист" ("Specialist") и "Ядро" (Core). There are modules in my app.

![image](https://user-images.githubusercontent.com/14962059/68371444-8c445c80-0160-11ea-861a-198e8b6f4b8c.png)

**Comment by chris579** [comment]
Cool, that might be a slightly bigger task, if someone is up to grab it. Should packages be nestable?

**Comment by queses** [comment]
As for my task it's not required, because I use them as modules. Modules in my applications structure shouldn't be nested. However I believe that somebody would be happy with nested packages.

So, answering your question - I think that it depends on how hard it will be to implement nested modules. If it creates significant technical complexity then don't do it :)

**Comment by dchjmichael** [comment]
Desperately need this feature 😂

**Comment by jgreywolf** [comment]
I would like to take this on, if no one is opposed...

**Comment by chris579** [comment]
> I would like to take this on, if no one is opposed...

Great. Love to see how active you are!

**Comment by ismarslomic** [comment]
Would it be possible to re-open this issue? I think this is highly important and required feature when modeling real life information models. Could a quick fix be to enable [Subgraphs] from Flowchart (https://mermaid-js.github.io/mermaid/#/flowchart?id=subgraphs) for Class Diagrams as well?

**Comment by chris579** [comment]
This issue is still open.

**Comment by jgreywolf** [comment]
Due to some issues that I ran into when trying to implement this, I decided to wait until the new rendering engine is ready to continue.  However, Im not sure when that will be, so maybe I should start working on this again :)

**Comment by jannismain** [comment]
👍 would love to see this in mermaid... lack of this feature had me going back to plantuml...

**Comment by dellagustin-sap** [comment]
> Should packages be nestable?
I would like to have nestable packages / namespaces.
My use case is related to representing packages or submodules inside microservices.
I also want to represent microservices as packages / namespaces and annotate them with stereotypes.
I will try to add examples in the future.

**Comment by ricardorauber-poatek** [comment]
Any update on this?

**Comment by jgreywolf** [comment]
Sorry, no - I had put the work on hold until the new version of rendering engine was completed.  Now that this is in place I will get back to this item

**Comment by ricardorauber-poatek** [comment]
Cool, thanks for the reply!

**Comment by bowdi** [comment]
Hi @jgreywolf, have you made any progress on this?

**Comment by HorstBaerbel** [comment]
First things first: Thanks for Mermaid!
Just want to chime in that this would be a great option to have!

**Comment by megretson** [comment]
Would also like to bump this, would love to see this feature.

**Comment by FatsharkGo** [comment]
I need this, please help!

**Comment by ePaul** [comment]
Hi,

I'd like a feature which seems to be related to this, but is likely simpler:
Just group some related classes together, so they keep together when layouting. I don't have a need of actually drawing a package box around them, but I don't want those classes be spread around randomly in my diagram.

Of course, this could also be implemented with the package box, and then just hiding it.

**Comment by ksilverwall** [comment]
to implement this function, need to extend specification of class-diagrams syntax.
who does define specification?

**Comment by czs108** [comment]
Does anyone know latest updates about this feature?

**Comment by sebastianbergt** [comment]
Just to let you know, I really need this feature and have set up a bounty for it here: https://app.bountysource.com/issues/83273957-add-package-to-class-diagram

It would be nice to have it called "namespace" instead of "package".

**Comment by aivanov-oneinc** [comment]
+1

**Comment by parnumeric** [comment]
Hi! I discovered recently this amazing tool to draw diagrams, which I liked very much, and I'm eager to see when the package/namespace feature will be implemented!

**Comment by stevenlafl** [comment]
+1

**Comment by wacaine** [comment]
+1

**Comment by ksilverwall** [comment]
@jgreywolf 
have you already implemented this logic?
if you have not about parser logic and my code is useful, copy from my code plz.

**Comment by jgreywolf** [comment]
@ksilverwall Just did a quick review.  Looks good.  I will most likely not get to applying this to any rendering code until next week. So if you have time to do that also, please feel free ;)

**Comment by ksilverwall** [comment]
@jgreywolf 
Thank you for your review, I will modify my pr.
Note that, you may face out of memory error on lint when you are developing rendering logic.
I think this is another problem then we need to solve this first.

```
<--- Last few GCs --->

[91998:0x7fa870078000]    62592 ms: Scavenge 4045.3 (4122.3) -> 4044.3 (4143.3) MB, 15.6 / 0.0 ms  (average mu = 0.891, current mu = 0.691) allocation failure; 
[91998:0x7fa870078000]    63636 ms: Mark-sweep 4058.7 (4143.7) -> 4054.7 (4159.5) MB, 1003.7 / 0.0 ms  (average mu = 0.733, current mu = 0.133) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10d080dc5 node::Abort() (.cold.1) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 2: 0x10bb041e9 node::Abort() [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 3: 0x10bb043ce node::OOMErrorHandler(char const*, bool) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 4: 0x10bc90f63 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 5: 0x10be59c15 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 6: 0x10be585f2 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 7: 0x10be4a92a v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 8: 0x10be4b2a5 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 9: 0x10be2d71e v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
10: 0x10c26348c v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
11: 0x10c658fb9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/kazuki_tsunemi/.volta/tools/image/node/18.14.2/bin/node]
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by duaneking** [comment]
Any updates? Namespace does not work as expected, as using it breaks diagrams by removing connections between objects that are very clearly defined.

**Comment by EugeneLau0** [comment]
expect update. it's a useful feature

**Comment by Kasimashi** [comment]
Same here ! :)

**Comment by ksilverwall** [comment]
If you find a bug, please create a new issue. Anyone can do it.
This issue is closed.

Additionally, if you have the time, please consider submitting a pull request with a fix.
I have implemented most of the features I need.

**Comment by duaneking** [comment]
> If you find a bug, please create a new issue.

This is a bug.

They did. Its this bug.

**Comment by markus-96** [comment]
The only thing that is not working from my point is nested namespaces, but this was not requested by this *Feature Request*. For some example usage, you could refer to https://github.com/mermaid-js/mermaid/blob/develop/demos/classchart.html and search for the keyword `namespace`.

Before this *Feature Request*, the keyword was not present at all. So, if one finds a bug, a *Bug Report* should be filed.

Thanks to the developers of this really helpful feature!

**Comment by Bazmundi** [comment]
I'm actually keen to have PlantUML style component diagrams, so that is not the C4 implementation at the moment.
