### ISSUE TITLE
Easier and more contextualized documentation

### ISSUE THREAD

**Issue by erelling** [mermaid-js/mermaid#1053]
Not being a frontend developer, I sometimes find the documentation is geared towards a skillset I haven't got.

I find mermaid to be an amazing tool but often find I need a bit more context and getting-started hints.

**Comment by chris579** [comment]
Thanks for your issue. It would be awesome if you could enhance the docs so they provide more value from a beginner aspect. You self assigned this issue, so I assume you want to work it out?

**Comment by erelling** [comment]
Yes, will do!

**Comment by chris579** [comment]
Awesome! Make sure to have a look at our [contributing guidelines](https://github.com/mermaid-js/mermaid/blob/master/CONTRIBUTING.md).
