### ISSUE TITLE
How can I remove the <style> mermaid-svg-internal-css in the svg?

### ISSUE THREAD

**Issue by KeisukeYamashita** [mermaid-js/mermaid#1054]
## What

I want to remove the `<style ... title="mermaid-svg-internal-css />` in the `svg`.

How can I do that?

Thank, you.

**Comment by Braincoke** [comment]
I also looked for this functionality when I was integrating mermaidjs to Gridsome.
I ended up removing the styles manually with unifiedjs.

~~~js
const remove = require('unist-util-remove')
const fromXml = require('xast-util-from-xml')
const toXml = require('xast-util-to-xml')

// ... create your graph
let graph = window.mermaid.render(svgId, definition);
// Remove the style tags
const xmlAST = fromXml(graph)
remove(xmlAST, node => node.name=='style')
graph = toXml(xmlAST)
~~~

**Comment by jgreywolf** [comment]
@KeisukeYamashita Were you able to come up with a solution for this?
