### ISSUE TITLE
Letter "s" injected to the node ID - continued

### ISSUE THREAD

**Issue by kickbk** [mermaid-js/mermaid#1055]
You locked my older post https://github.com/mermaid-js/mermaid/issues/1038#event-2781832932 and only allowed collaborators to reopen. Just letting you know we will not be using the new version, for now. Really appreciate your efforts working on this wonderful lib, but your solution only works partially. You prepended a `mermaid-dom-id`- to the IDs. It's more of a change than a bugfix/solution.

**Comment by knsv** [comment]
Sorry, the locking is done by automation.

It is is your call if you use the latest version or not. The current solution will work fine unless the author of the diagram calls its id "mermaid-dom-id" and happends to have an existing id with the same name as in

```
graph TD
  mermaid-dom-id-123test ---> 123test
```

This diagram would render an arrow to itself...

Good news though as I think I know a way to fix this with better selectors. Let keep this open for now.
