### ISSUE TITLE
Mermaid Sequence Diagram is not rendered in script

### ISSUE THREAD

**Issue by Shanmugapriya001** [mermaid-js/mermaid#1059]
When I try sequence diagram  from function that renders an svg with a graph from a chart definition. Sequence diagram is not rendered.
Here is the sample code:
<script>
mermaid.initialize({
     startOnLoad:true
 });
 $(function(){
     var graphDefinition = 'sequenceDiagram \nparticipant Browser';
     console.log(graphDefinition);
     var cb = function(svgGraph){
         console.log(svgGraph);
     };
     mermaid.render('id1',graphDefinition,cb);
 });
</script>
<body>
  <div id="id1">
</div>
</body>

Diagram is not generated , some problem with svg <g> generation .
I am not getting any sample code for generating dynamic sequence diagram from json in mermaidjs. Thanks if I get the solution. kindly correct me if I am wrong .

![image](https://user-images.githubusercontent.com/27997257/68570970-de022500-0487-11ea-9322-bdfb80db1d7f.png)

Here is the sample image how it should generate 

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtIFxucGFydGljaXBhbnQgQnJvd3NlclxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

**Comment by Yokozuna59** [comment]
Closes this issue since no reply was given.

Feel free to re-open it or create a new one if it's not resolved.
