### ISSUE TITLE
Parallelogram shaped nodes are not in documentation

### ISSUE THREAD

**Issue by Dunning-Kruger** [mermaid-js/mermaid#1062]
Parallelogram nodes are supported but not shown in the documentation.
[Sample here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbL0NocmlzdG1hcy9dXG5cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19).
[Docs here](http://mermaid-js.github.io/mermaid/#/flowchart?id=nodes-amp-shapes).

**Comment by GDFaber** [comment]
I'd like to add this to the docs, should get to it this weekend.

**Comment by GDFaber** [comment]
Done, my PR is in #1070.
