### ISSUE TITLE
Generic type support for class diagrams

### ISSUE THREAD

**Issue by chris579** [mermaid-js/mermaid#1063]
I want to be able to define a generic class in class diagrams. This currently breaks because the parser doesn't allow `<` or `>` in the class name.

```
classDiagram
class Test<T> {
+ test: int
}
```

[Live editor example](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBUZXN0PFQ-IHtcbisgdGVzdDogaW50XG59XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ/error/UGFyc2UgZXJyb3Igb24gbGluZSAyOgouLi5zc0RpYWdyYW1jbGFzcyBUZXN0PFQ-IHsrIHRlc3Q6IGludH0KLS0tLS0tLS0tLS0tLS0tLS0tLS0tLV4KRXhwZWN0aW5nICdORVdMSU5FJywgJ0VPRicsICdTVFJVQ1RfU1RBUlQnLCBnb3QgJ0RFUEVOREVOQ1kn)

If this syntax would break something, there could be an alternative syntax
```
classDiagram
class Test{T} {
+ test: int
}
```
This should render with `<` `>` brackets. Needs more work because this means additional parsing.

**Comment by keenanjt33** [comment]
New contributor here! I'm interested in taking this on. Looks like the grammar in _flow.json_ will need to be added to.

**Comment by Dunning-Kruger** [comment]
@keenanjt33 Don't forget to check the [contribution guide](https://github.com/mermaid-js/mermaid/blob/master/CONTRIBUTING.md) and [join us in slack](https://join.slack.com/t/mermaid-talk/shared_invite/enQtNzc4NDIyNzk4OTAyLWVhYjQxOTI2OTg4YmE1ZmJkY2Y4MTU3ODliYmIwOTY3NDJlYjA0YjIyZTdkMDMyZTUwOGI0NjEzYmEwODcwOTE) if you need any pointers/help. Leave a comment when you're sure you'll work on it and we'd be happy to assign it to you and remove the `help wanted` label.

**Comment by chris579** [comment]
> Looks like the grammar in _flow.jison_ will need to be added to.

This issue is about class diagrams, not flow diagrams.

**Comment by jgreywolf** [comment]
@keenanjt33 Just checking - Are you working on this?

**Comment by jgreywolf** [comment]
I have taken an initial attempt at this one.  Please see forked branch at: https://github.com/jgreywolf/mermaid/tree/1063-GenericTypeSupportInClassDiagrams

Im not 100% happy with it, due to how I am splitting the classname from the type...  but I will continue to refactor and fiddle I am sure :)

**Comment by chris579** [comment]
Great. Please make sure to give a sign you're on working on an issue so we can block it for you and nobody else grabs it.

**Comment by jgreywolf** [comment]
I was holding off on that waiting to see if the original person who said they were going to work on it piped up. And yet still worked on it to get the experience ;)
