### ISSUE TITLE
Click event on a node in a classDiagram

### ISSUE THREAD

**Issue by FransBouma** [mermaid-js/mermaid#1064]
Hi,

(using 8.4.2)

The documentation doesn't mention any 'interaction' section for classDiagram (or I have overlooked it ;) ) and the syntax for flowDiagram nodes on a classDiagram apparently doesn't work:

```html
<div class="mermaid">
classDiagram
	Employee <|-- Clerk
	Employee <|-- Manager
	Manager <|-- BoardMember
	click Employee "../Entities/Employee.htm" "Click to go to definition"
</div>
```

This results in the error:
```
Error: Parse error on line 5:
...ties/Employee.htm" "Click to go to defin...
-----------------------^
Expecting 'AGGREGATION', 'EXTENSION', 'COMPOSITION', 'DEPENDENCY', 'LINE', 'DOTTED_LINE', got 'STR'
```
however I can't find the right syntax, or is this feature not supported on classDiagrams? 

TIA!

**Comment by chris579** [comment]
I'm not aware of any interaction logic for class diagrams. However, if there is some logic for that in flow diagrams, it could be ported over.
