### ISSUE TITLE
Parse method does not return a boolean

### ISSUE THREAD

**Issue by ginger-tek** [mermaid-js/mermaid#1066]
**Describe the bug**
The `mermaid.parse()` method is supposed to return a boolean when passed a string of mermaid markdown, but it is instead returning `undefined` for valid markup, and an `Uncaught` error on invalid markup.

**To Reproduce**
`mermaid.parse('graph TD\n')` = returns `undefined`
`mermaid.parse('graph TD\n{')` = returns `Uncaught {str: "Parse error on line 1...`

**Expected behavior**
Per [this section of the current documentation](http://mermaid-js.github.io/mermaid/#/usage?id=advanced-usage), 

> "The function mermaid.parse(txt) takes a text string as an argument and returns true if the text is syntactically correct and false if it is not."

`mermaid.parse('graph TD\n')` = should return `true`
`mermaid.parse('graph TD\n{')` = should return `false`

**Screenshots**
![image](https://user-images.githubusercontent.com/38133930/68774640-68b76100-05fb-11ea-861e-7dc5b9044c2c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 77.0.3865.120

**Comment by chris579** [comment]
Right, the docs are not matching the [implementation](https://github.com/mermaid-js/mermaid/blob/master/src/mermaidAPI.js#L335). There is no sign of returning a boolean. It would make sense to return a boolean in the first place, however the thrown error contains the information about the parser error. 

If you would change the method in a way that it returns a bool and doesn't throw an exception, this would be a breaking change in the api which should be avoided. Therefore I don't see the point in returning a boolean. This is more like a flaw in the docs.

**Comment by simpltek** [comment]
I see what you mean, but having the ability to return both boolean and error info would be great. Maybe the return value can either be an object instead? That way you can still easily implement simple checking, but still get detailed error info upon invalid markup.

The object would probably be something like this, with a nullable error property :
```
{
    result: [boolean]
    error: [object] or [null]
}
```

For example:
```
var result = mermaid.parse(str);
if(!result.result) { // false
    // invalid markup
    // result object --> { result: false, error: 'Uncaught: ...' }
    var error = result.error;
}

if(result.result) { // true
    // valid markup
    // result object --> { result: true, error: null }
}
```

**Comment by chris579** [comment]
Still the `parse` function would throw an exception (because removing that would be a breaking change). Regarding execution flow, it would stop if you don't catch the exception. And if you catch it, you automatically know that the parser failed. Imo that's a suitable solution that would also fit the code you posted (if you change it a bit).

**Comment by simpltek** [comment]
Hmm, then maybe this method shouldn't really be sold as a validation check, or the docs should say that *you* need to use a try catch to return what you want to return. That, or just make a separate method called `validate()` implementing a try catch around `parse()` specifically for validation checking only, which would return something similar to what I wrote above

**Comment by chris579** [comment]
You're right, I also consider that to be a flaw in the docs. I like the idea of a separate method, that could be handy. Will implement that.

**Comment by jgreywolf** [comment]
@klemmchr Do you have any update on this?  Are you still able to work on a solution?

**Comment by klemmchr** [comment]
Not really, I don't really have the spare time to help out here and I'm heavily out of sync with the codebase.

**Comment by NeilCuzon** [comment]
Will this method be deprecated, until it is fixed? I will be adjusting the docs to reflect this for now.

**Comment by sidharthv96** [comment]
The upcoming parse in v10(#4108) will support both use cases.
```js
/**
 * Parse the text and validate the syntax.
 * @param text - The mermaid diagram definition.
 * @param parseOptions - Options for parsing.
 * @returns true if the diagram is valid, false otherwise if parseOptions.suppressErrors is true.
 * @throws Error if the diagram is invalid and parseOptions.suppressErrors is false.
 */

async function parse(text: string, parseOptions?: ParseOptions): Promise<boolean | void> {
```

**Comment by silverwind** [comment]
I tried using `await mermaid.parse(source)` but it still was not returning a boolean, but `undefined` when diagram was valid.

**Comment by silverwind** [comment]
Actually I think the return value of `parse` doesn't need  to matter because if there is a parse error, I would like to know what it is, so I think it's fine for it to always just throw the actual error and let the return value undefined.
