### ISSUE TITLE
FlowChart: Node text is getting clipped in chrome for browser zoom <100%

### ISSUE THREAD

**Issue by sulabh-msft** [mermaid-js/mermaid#1068]
**Describe the bug**
FlowChart: Node text is getting clipped in chrome for browser zoom <100%

**To Reproduce**
1. In Chrome browser, go to [Flowchart demo live editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)
3. Change the browser zoom level to <100% ( say 80 %)

4. Refresh the browser tab

**Expected behavior**
The whole content (all the letters of the phrase "Let me think" and "Car") of the nodes should be visible

**Screenshots**

![image](https://user-images.githubusercontent.com/13728069/68937901-4b34f380-07c3-11ea-813d-2303d08ef483.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: Google Chrome
 - Version 78.0.3904.97 (Official Build) (64-bit)

**Additional context**
Please note that this issue in not happening in 
- Edge/Firefox browsers at both (<100% and >100%) browser zoom levels
- Chrome, is working fine for  (>=100%) browsers zoom level

**Comment by zhangyoufu** [comment]
I ran into this issue several months ago.
Now with Chrome 88, I cannot reproduce under whatever zoom level.
I think this issue can be closed now.

**Comment by sulabh-msft** [comment]
Verified in the chrome browser at zoom < 100%.
This is fixed now.
