### ISSUE TITLE
Repeatable freeze: adding new class before other class in classDiagram in Live Editor

### ISSUE THREAD

**Issue by lukewlms** [mermaid-js/mermaid#1069]
**Describe the bug**
While adding a new class in the Live Editor, the editor freezes.  Repros on Chrome and Firefox (latest versions).

**To Reproduce**
1. in Live Editor, add this simple classDiagram:

```
classDiagram


class Foo {
  bar
}
```

2. Between classDiagram and class Foo (one newline before and after, if that matters), start typing `class Bar {}`

So, you're trying to achieve:

```
classDiagram

class Bar {}

class Foo {
  bar
}
```

**Screen capture**
Here's a [video of the repro](https://www.dropbox.com/s/2gh575savplckk1/2019-11%20mermaid%20freeze.mov?dl=0).

**Result**

Before the '{' appears, the browser window freezes.  Browser eventually asks if user wants to stop the script.

**Expected behavior**
Live editing continues with an error message.

**Desktop (please complete the following information):**
 - Browser: Firefox and Chrome latest
- Mac OSX 10.14.6

---

Thanks - what a great library!

**Comment by jgreywolf** [comment]
It looks like this issue no longer repros in version 8.6.4.

Please verify/confirm if you still see the problem

https://mermaid-js.github.io/mermaid-live-editor/

**Comment by jgreywolf** [comment]
@lukewlms  Can you please confirm that this no longer repros for you in current version of [live editor](https://mermaid-js.github.io/mermaid-live-editor/)

**Comment by lukewlms** [comment]
This looks good to me now.  Thanks so much!
