### ISSUE TITLE
Dependency on github lib dagrejs/dagre-d3

### ISSUE THREAD

**Issue by damiandennis** [mermaid-js/mermaid#1071]
Hey,

Could we possibly get the dependency changed from a github repo to an rpm lib "dagrejs/dagre-d3".
The main reason I am having issues with this is I am behind a corporate firewall and we have an internal repo for npm but nothing that caters for github dependencies. I hope this is not a big ask.

Thanks

**Comment by chris579** [comment]
Duplicate of #1065
