### ISSUE TITLE
display associated information when the mouse is moved over

### ISSUE THREAD

**Issue by yoyomule** [mermaid-js/mermaid#1072]
I hope it will support the ability to display associated information when the mouse is moved over the flowchart icon.Thanks

**Comment by Dunning-Kruger** [comment]
Which graph are you referring to? 
Also, how do you imagine the syntax to define the "associated information"?

**Comment by GDFaber** [comment]
Hi @yoyomule, you can define tooltips for the flowchart nodes to display additional information. Please refer to [section "Interaction" in the docs](https://mermaid-js.github.io/mermaid/#/flowchart?id=interaction) for more information on how this works.

If that's not what you want to do, please open a new issue and add an example of what should be possible.
