### ISSUE TITLE
Comment syntax is not in documentation

### ISSUE THREAD

**Issue by Dunning-Kruger** [mermaid-js/mermaid#1074]
Original issue with the implementation of comments: [here](https://github.com/mermaid-js/mermaid/issues/47).

`%% Comment`

**Comment by Dunning-Kruger** [comment]
@jgreywolf I would like to assign this issue to you before closing it so it permanently shows you fixed it. Could you leave a comment so you show up as a possible assignee? Thank you!

**Comment by jgreywolf** [comment]
This is a comment :)

**Comment by Dunning-Kruger** [comment]
@jgreywolf I think you mean `%% This is a comment :)`! Just kidding. Thanks for everything!
