### ISSUE TITLE
Is there a way to have LR graph type with TB subgraphs

### ISSUE THREAD

**Issue by bluezald** [mermaid-js/mermaid#1091]
Is there a way to have LR graph type for the main graph and having a different type in its subgraphs?
Like this diagram? (this is photo edited)
![diagram](https://user-images.githubusercontent.com/1034742/69700909-a0a7c380-1126-11ea-80e3-85448f8ec8b8.png)

**Comment by knsv** [comment]
That is currently not possible. The library we are using for layout does not support this so it would also be be difficult to achieve this.

I could see a way to getsub graphs function is their own little graphs with their own directions but then linking to individual nodes from in one subgraph to a node in another subgraph would not be possible. Linking from subgraphs to subgraphs would work though.

**Comment by bluezald** [comment]
thanks @knsv 
you mention linking from subgraphs to subgraphs.
I'm note sure how is this done?

**Comment by GDFaber** [comment]
I'm closing this issue in favour of #1265.
