### ISSUE TITLE
Mangled output with multiple Class Diagrams on the same page

### ISSUE THREAD

**Issue by Gaudeval** [mermaid-js/mermaid#1092]
**Describe the bug**
When inserting multiple class diagrams on the same page, anything but the first one gets mangled and all classes' boxes end up in the top left corner. 

The log seems to indicate the correct position information is available for both diagrams, but it does not appear in the output SVG. 

The issue also occurs when calling `mermaid.render` or `mermaid.init` with the selected elements.

Confirmed on mermaid 8.4.2 (picked from unpkg)

The mermaid website examples (with multiple diagrams) render correctly.

**To Reproduce**
Here is a small example:
```html
<!DOCTYPE html>
<html lang="en">

<body>

<div class="mermaid" id="diag-1">
classDiagram
Class01 <|-- AveryLongClass : Cool
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
</div>

<div class="mermaid" id="diag-2">
classDiagram
Class01 <|-- AveryLongClass : Cool
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
</div>
  
	<script src="mermaid.min.js"></script>
	<script>
		mermaid.initialize({startOnLoad:true, logLevel:0});
	</script>

</body>
</html>
```

**Screenshots**
![mermaid-issue](https://user-images.githubusercontent.com/588283/69722862-0ccafd00-1110-11ea-8a43-511831511b84.PNG)

**Browser:** Chrome Version 77.0.3865.120

**Comment by Gaudeval** [comment]
After a bit of experimentation, it seems the order in which the diagrams appear on the page and the order in which they are processed does matter. With the same html as before, using the following script will result in the correct output:
```javascript
mermaid.initialize({ logLevel:0, startOnLoad: false });
		
var elt_1 = document.querySelector("#diag-1");
var elt_2 = document.querySelector("#diag-2");
		
nodes = [elt_2, elt_1]; // Works, nodes = [elt_1, elt_2] does not
for (let i = 0; i < nodes.length; ++i) {
	const id = `mermaid-${Date.now()}`;	
	const element = nodes[i];
			
	mermaid.render(id, element.textContent.trim(), (svg, bind) => {element.innerHTML = svg;}, element);
}
```

**Comment by jgreywolf** [comment]
So, if I understand correctly - it works correctly if the diagrams are processed in the reverse order?

**Comment by knsv** [comment]
I think this was an issue. Then it was fixed but reappeared in develop after the addition of click functions. 

It was the removed counter that caused the reappearing issue. I have been working with Ashish for a more intuitive handling of ids where the classDb retains two ids one for the DOM and one for the graph.

**Comment by jgreywolf** [comment]
Just looked at the PR referenced here.  I can see where that makes it easier to keep the id consistent between the different sections of code.  I had removed the counter previously because it was not able to identify the correct element since the count part was missing in classRenderer...   :)
