### ISSUE TITLE
State diagrams not showing as expected

### ISSUE THREAD

**Issue by ramstein74** [mermaid-js/mermaid#1094]
Hello i was trying this code from your repo
```
 stateDiagram
        State1: The state with a note
        note right of State1
            Important information! You can write
            notes.
        end note
        State1 --> State2
        note left of State2: This is the note to the left.
```
but the result is note the same , please see attached pic.
State1 does now show in the image !!!!
![image](https://user-images.githubusercontent.com/1210858/69752590-7a474f80-1149-11ea-9c0e-ce0d84a4ad18.png)
can you help ??

**Comment by Dunning-Kruger** [comment]
The result you're showing is consistent to the diagram markdown you added, and matches what the documentation shows: 

![image](https://user-images.githubusercontent.com/1564825/69753118-bd40fd00-1120-11ea-8bee-40bc19fdc51d.png)

"State1" is the state with the text "The state with a note" as description. The relevant part of the doc shows that syntax here:

![image](https://user-images.githubusercontent.com/1564825/69753192-f24d4f80-1120-11ea-8cda-1bee8ab02d5f.png)

Both images were screenshotted from [here](http://mermaid-js.github.io/mermaid/#/stateDiagram).
I might be misunderstanding your issue/question/problem. Please, let me know if that's the case.

**Comment by ramstein74** [comment]
Guess you are right.
I just dont know where i saw it wrong.
Please close the issue.
Regards

Em qua., 27 de nov. de 2019 às 19:20, Nacho <notifications@github.com>
escreveu:

**Comment by Dunning-Kruger** [comment]
@ramstein74 For future reference, you can always close your own issues if you think they are resolved! Thank you!
