### ISSUE TITLE
Markdown files with mermaid as html

### ISSUE THREAD

**Issue by clockbook** [mermaid-js/mermaid#1096]
Hi all,

I have several mermaid sequence diagrams written up in markdown files. I'd like to be able to convert the markdown to html and have the mermaid diagrams render correctly.

I know it's possible to write mermaid syntax inside a div and have the browser render it as a svg. However, is it possible to render from a markdown file directly?

**Comment by asiaon123** [comment]
@clockbook You need to customize your markdown parser to support mermaid rendering
This is what i do for rendering with hacking markdown-it parser
```typescript
const renderedSvg = mermaidAPI.render(needsUniqueId, code, svgCode => {}, mermaidDrawer);
```

**Comment by jgreywolf** [comment]
Closing due to age
