### ISSUE TITLE
unable to create an arrow to subgraph

### ISSUE THREAD

**Issue by 400thecat** [mermaid-js/mermaid#1097]
I have simple graph, and I can create arrows to members of subgraph

graph TB
  router
  subgraph Network
    server1
    server2
  end
router --> server1
router --> server2

However, I cannot create an arrow to the subgraph itself:

graph TB
  router
  subgraph Network
    server1
    server2
  end
router --> Network

[screenshot here](https://ibb.co/DVq3LrJ)

How can I create an arrow to subgraph, instead of its members ?

**Comment by walterheck** [comment]
I would be very happy to see this functionality also, and it would be even better if we could have relations between subgraphs :)

**Comment by scrobbleme** [comment]
+1

**Comment by Dunning-Kruger** [comment]
Duplicate of #644
