### ISSUE TITLE
Class diagram: support for abstract members

### ISSUE THREAD

**Issue by adaJQD** [mermaid-js/mermaid#1104]
How to represent an abstract method in class diagram?

**Comment by chris579** [comment]
In UML it would be written italic, however this case is not supported by mermaid currently.

**Comment by jgreywolf** [comment]
I will go ahead and take this one.  One implementation question: in some cases UML diagram for an abstract class could also include `{abstract}` under the class name.  Should we follow that convention?  Or just the italics

**Comment by chris579** [comment]
This issue is about abstract methods in classes. Classes itself can already be marked as abstract by using annotations. I find that suitable enough.

**Comment by jgreywolf** [comment]
Sorry - yes.
