### ISSUE TITLE
Crash when nested urly braces in class diagram

### ISSUE THREAD

**Issue by abnerlee** [mermaid-js/mermaid#1115]
1. Go to https://mermaidjs.github.io/mermaid-live-editor
2. input 
```
classDiagram

class Person {
  Name {}
}
```
3. The page will be Not Responding

 - OS: macOS 10.15.1
 - Browser Chrome
 - Version 78

**Comment by Dunning-Kruger** [comment]
@abnerlee Thank you for the report! Duplicate of #1069
