### ISSUE TITLE
graph 能支持上下和左右方向嵌套使用吗

### ISSUE THREAD

**Issue by wolfcoming** [mermaid-js/mermaid#1118]
graph 能支持上下和左右方向嵌套使用吗

**Comment by chris579** [comment]
Hi, could you please elaborate your issue in English so everyone understands it? Thanks!

**Comment by EricXing** [comment]
> graph 能支持上下和左右方向嵌套使用吗

In English: Can I mix TD and LR in one graph?

**Comment by chris579** [comment]
I assume that you mean flowcharts, right? That's currently not possible.

**Comment by GDFaber** [comment]
I'm closing this issue in favour of #1265.
