### ISSUE TITLE
Fold out / collapse flowchart

### ISSUE THREAD

**Issue by maxschons** [mermaid-js/mermaid#1123]
**Problem: Complicated flow charts are hard to grasp**
Creating complex flowcharts makes them overwhelming for users. Nevertheless they are sometimes necessary. Users will not use a complicated flow chart or one has to abandon complexity for the sake of users using them.

**Solution: Collapse the flowchart at the beginning and extend branches to the next split**
As a user I would like to see only the start of the flowchart until the first split. I would like to see an indication that something follows below when I click on the boxes. When I click on a box only this branch extends until the next split. Here I can decide again and click. Additionally this should trigger events, that a backend could record.

**Alternatives**
- _render a questionnaire_ from the flowchart on click in a bootstrap module or something like that
- _grey out parts of the flowchart_, that have not been clicked (e.g. I click a box and everything not in the branch will be greyed out). The nice thing here is that users can still see the other parts if they want. The bad thing is that the space for complex flowcharts is limited and collapsing brings space.

**Additional context**
Background: I'd like to generate complex medical flowcharts. Physicians do not use complex flowcharts and reducing complexity is probably harmful due to less specific medication etc.

**Comment by Dunning-Kruger** [comment]
Hello! Thank you for reaching out!

I feel like this is outside of the scope of mermaid. The library goes from markdown-like text to a graph markup/image. 

Some of the mentioned solutions (collapsing, graying out) could be implemented post generation of the graph, and others (questionnaire) don't even require the generation of the graph markup at all.

You could also consider re-generating the markup (and re-rendering the graph) on any action of the user you consider.

**Comment by maxschons** [comment]
Thanks, appreciated!

I agree that this goes beyond the current 'standard' features but wanted to propose it anyway here to get your guys point of view on it. 

In case I want to implement it, any specific pitfalls I should be aware of?

**Comment by jgreywolf** [comment]
Closing this as wont fix since it is outside the scope of mermaid directly
