### ISSUE TITLE
Docs api usage mentions wrong include

### ISSUE THREAD

**Issue by chris579** [mermaid-js/mermaid#1124]
However, [here in the docs](https://mermaid-js.github.io/mermaid/#/usage?id=api-usage) an obscure `mermaidAPI.js` is mentioned I've never seen before. I'm quite sure that the docs are outdated.

_Originally posted by @chris579 in https://github.com/mermaid-js/mermaid/issues/1122#issuecomment-562878314_

The docs are wrong about that. You don't need to include any other file than `mermaid.js`.

**Comment by jdavis61** [comment]
Opened https://github.com/mermaid-js/mermaid/pull/1140 for this ticket. Please review and provide feedback.
