### ISSUE TITLE
How to insert an image in flowchart?

### ISSUE THREAD

**Issue by waterdrop01** [mermaid-js/mermaid#1133]
Hello,

looking at https://github.com/mermaid-js/mermaid/issues/548, I still couldn't figure out how to insert an image in my flowchart. 

I'm using the online editor : https://mermaidjs.github.io/mermaid-live-editor

And here is the code I'm using:
```
graph TD
  DIR((&lt;img src&#61;&#39;https://iconscout.com/ms-icon-310x310.png&#39; width&#61;&#39;30&#39; /&gt;))
```
And here is the error:
![Screenshot from 2019-12-10 13-32-38](https://user-images.githubusercontent.com/47316824/70529747-98ea1500-1b51-11ea-993f-1b283dfe4555.png)

Thank you for your help!

**Comment by Dunning-Kruger** [comment]
[Here's your sample](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgRElSKFwiPGltZyBzcmM9J2h0dHBzOi8vaWNvbnNjb3V0LmNvbS9tcy1pY29uLTMxMHgzMTAucG5nJzsgd2lkdGg9JzMwJyAvPlwiKSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0Iiwic2VjdXJpdHlMZXZlbCI6Imxvb3NlIn19) corrected to render the image.
Note that I had to set `securityLevel` to `loose` in order for mermaid to not escape the html content.

**Comment by waterdrop01** [comment]
@Dunning-Kruger Awesome! That looks great, thanks so much
