### ISSUE TITLE
marker-end remove url (arrowhead dosen't appear)

### ISSUE THREAD

**Issue by hatemjaafar** [mermaid-js/mermaid#1138]
Hello,

I need  to remove  url specified in the  marker-end attribute when generating SVG.

exemple:
marker-end="url(http://some url#arrowhead2)"   => dosen't work.
marker-end="url(#arrowhead2)"   => work.

I make search and i found that it have to be specified in configuration but i don't understand how.

thanks for your help

**Comment by knsv** [comment]
What version of mermaid are you using? There has been a recent bugfix for that in version 8.4.3

**This will give releative path in the marker-end attributes, like you want:**
```
<html>
  <body>
      <div class="mermaid" style="width: 100%; height: 100%">
        graph TB
          a --> b
      </div>
  <script src="./mermaid.js"></script>
    <script>
      mermaid.initialize({
        arrowMarkerAbsolute: false,
      });
    </script>
  </body>
</html>
```
This will give full path is marker-end attributes:
```
<html>
  <body>
      <div class="mermaid" style="width: 100%; height: 100%">
        graph TB
          a --> b
      </div>
  <script src="./mermaid.js"></script>
    <script>
      mermaid.initialize({
        arrowMarkerAbsolute: true,
      });
    </script>
  </body>
</html>
```

**Comment by jgreywolf** [comment]
Closing as this was resolved externally
