### ISSUE TITLE
Is there a way to add notes in flowchart?

### ISSUE THREAD

**Issue by wangdayong228** [mermaid-js/mermaid#1141]
Hi,
I found most of the other diagrams could add notes, but not found in flowchat, could I add notes in mermaid flowchart like this? thank you.

![image](https://user-images.githubusercontent.com/11971608/70786880-8fb6ad80-1dc8-11ea-8c69-bb01a581d424.png)

**Comment by chris579** [comment]
There is no documented way of doing this. You could attempt to create a node at the top of your graph definition that has no connections. However, I would consider this to be more of a hack than a real solution.

**Comment by wangdayong228** [comment]
> There is no documented way of doing this. You could attempt to create a node at the top of your graph definition that has no connections. However, I would consider this to be more of a hack than a real solution. I'm not sure whether this can be realised with current solutions.

thank you for your reply, your solution is work good. It would be better if use syntax like 'Note node "i am the note of node"', hope enhance this feature:)

**Comment by GDFaber** [comment]
I'm closing this issue in favour of #821 which is also about adding notes to flowcharts.
