### ISSUE TITLE
Class: interface realization / lollipop

### ISSUE THREAD

**Issue by mestaritonttu** [mermaid-js/mermaid#1145]
There doesn't seem to be a way to define this currently: https://www.uml-diagrams.org/realization.html

PlantUML calls it lollipop: https://plantuml.com/class-diagram and supports it like this:
```
bar ()- foo
bar ()-- foo
foo -() bar
```

**Comment by jgreywolf** [comment]
I will start work on this after January 6th.  Unless someone else is interested :)

**Comment by ashishjain0512** [comment]
@jgreywolf  I think this will be resolved by PR #1171 as that adds supports for dashed lines. After this PR the following relations will be available.

![image](https://user-images.githubusercontent.com/16836093/71740128-b44bf580-2e5b-11ea-9f27-01e0f837fdb9.png)

**Comment by jgreywolf** [comment]
I think that resolves part of it.  The other part was being able to do something like the following: 

![image](https://user-images.githubusercontent.com/300077/71740387-e8e68f80-2e10-11ea-8d71-c9303a66c94b.png)

**Comment by adamguild** [comment]
@jgreywolf I would be happy to help with that last part, do you have any pointers for me? I am new to the project. Thank you.

**Comment by may4everL** [comment]
@jgreywolf I have made some changes regarding the lollipop interface diagram
I have made an imcomplete PR #3154 : https://github.com/mermaid-js/mermaid/pull/3154
With the current changes, the lollipop diagram would be generated like:
![image](https://user-images.githubusercontent.com/34352226/174515715-1e602c9f-e923-4e3b-b647-75013744cde9.png)

This feature is incomplete, as the classbox surrounding the interface needs to be deleted.

Please let me know if you have any comments, thanks!

**Comment by may4everL** [comment]
I have update the code according to the changes of the code base
Please refer to the PR #3311 
The redundant classbox for this simple interface is not handled yet.

**Comment by jgreywolf** [comment]
Closing this issue as lolipop funcitonality has been merged. If the other item still needs to be addressed please open a new issue
