### ISSUE TITLE
new editor URL: Cannot open Class Diagramm Example page

### ISSUE THREAD

**Issue by NebojsaKrtolica** [mermaid-js/mermaid#1147]
**Describe the bug**
Cannot open Class Diagramm Example page https://mermaid-js.github.io/mermaid/#/classDiagram

**To Reproduce**
Visit https://mermaid-js.github.io/mermaid/#/classDiagram

**Expected behavior**
The page loads and renders successfully 

**Screenshots**

> classDiagram.jison:175 
 Uncaught Error: Parse error on line 7:
...+withdrawl(amount)}```
----------------------^
Expecting 'NEWLINE', 'EOF', got 'PUNCTUATION'
    at E.parseError (classDiagram.jison:175)
    at E.parse (classDiagram.jison:245)
    at Ye (classRenderer.js:415)
    at Object.render (mermaidAPI.js:565)
    at r.code ((index):46)
    at c.tok (docsify.min.js:1)
    at c.tok (docsify.min.js:1)
    at c.tok (docsify.min.js:1)
    at c.parse (docsify.min.js:1)
    at Function.c.parse [as parser] (docsify.min.js:1)

![image](https://user-images.githubusercontent.com/6503280/71018876-96f7f700-20f9-11ea-95ea-15ca6e7a911a.png)

![image](https://user-images.githubusercontent.com/6503280/71018582-0e795680-20f9-11ea-8793-23f7724d76f5.png)

**Desktop**
 - Device: MacBook Pro (15-inch, 2018)
 - OS: macOS 10.15.2 (19C57)
 - Browser Chrome
 - Version Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by Dunning-Kruger** [comment]
Fixed here: https://github.com/mermaid-js/mermaid/commit/d53e00ffe0e9dc12d5d2e47c8f9ccc20ea5c88f4

Thanks for the report!
