### ISSUE TITLE
How to stretch line length 

### ISSUE THREAD

**Issue by wangdayong228** [mermaid-js/mermaid#1152]
This is the graph made by mermaid.
<img width="263" alt="屏幕快照 2019-12-21 下午6 26 46" src="https://user-images.githubusercontent.com/11971608/71306794-046c9600-2420-11ea-8a41-c5a92b7206d8.png">
I want enlarge the link line as follow, could mermaid do this work? Maybe use linkstyle or set a factor for stretch line length?
<img width="468" alt="屏幕快照 2019-12-21 下午6 25 02" src="https://user-images.githubusercontent.com/11971608/71306820-485f9b00-2420-11ea-9f43-747aefe8ac00.png">
except replay, thank you guys.

**Comment by GDFaber** [comment]
AFAIK this cannot be adjusted in mermaid at the moment. According to [this comment](https://github.com/dagrejs/dagre-d3/issues/256#issuecomment-232524943) there are graph settings in dagreD3 which allow to set the distance between nodes. Perhaps these can be added to the flowchart config attributes and applied in the flowchart renderer?

**Comment by GDFaber** [comment]
[dagrejs layout settings](https://github.com/dagrejs/dagre/wiki#configuring-the-layout)

**Comment by GDFaber** [comment]
The settings ```nodesep``` and ```ranksep``` can be used to put more space between the nodes (both 50 by default); as mentioned above, this is applied to all the nodes in the graph.

```nodesep``` is the spacing value for nodes of the same rank, while ```ranksep``` holds the spacing value between ranks. In a top-down graph for example, "nodesep" could be seen as the horizontal spacing while "ranksep" does the vertical spacing.

I'm going to provide a PR to make the settings available in the flowchart configuration.
