### ISSUE TITLE
What is actually a NEWLINE? (Creating Markdown Dynamically With JS)

### ISSUE THREAD

**Issue by jpetro416** [mermaid-js/mermaid#1158]
If I have an error like the one below (because I'm dynamically creating a string in javascript). How do I add a "NEWLINE". I've had some success with "; " and " ". But it's very inconsistent with each graph type. The documentation is not helpful for actual dynamic scenarios.

**TLDR:  How to create a new line for markdown text and not for labels?**

` diagram_txt_tmp +=  node_list[id].getNodeID() + " --> " + desc_node[dn_count] + " \n ";`
I've also tried this, which works on graph TD, but not statediagram:
` diagram_txt_tmp +=  node_list[id].getNodeID() + " --> " + desc_node[dn_count] + "; ";`
```
mermaid.js:90322 Uncaught Error: Parse error on line 1:
...-> store_line_count <br/> will_verify_li
-----------------------^
Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF',
```

**Comment by GDFaber** [comment]
Hi @jpetro416, is it possible that new lines ```\n``` are converted to ```<br/>``` tags in your code before handing over the markdown to mermaid? If not, can you provide a minimal example of your markdown right before it is rendered?

**Comment by jpetro416** [comment]
Yes the output example above is for `\n` being converted into `<br/>`. If mermaid is having this much trouble with a string, why doesn't it have an issue when it's raw text being rendered?  There should be a clear way to tell mermaid that this is a new line.... like "\NEWLINE" or something. 

On a side note, am I missing the part in the documentation where they show actual examples from a dynamic standpoint? It seems crazy to only have documentation on plain text examples...

**Comment by jgreywolf** [comment]
@jpetro416 If this is still an issue for you that should be reviewed, can you please provide an example using [Live Editor](https://mermaid-js.github.io/mermaid-live-editor)

**Comment by jpetro416** [comment]
The markdown was working on the live editor, only when it's interpreted while being generated as a string in JS does it have this issue. The way end of lines are done is obviously not good for data being generated on the fly. Would seriously recommend looking at how it's parsed on the Mermaid.js side. It's not a good setup for the type of dynamic data most people would want loaded/created

**Comment by sidharthv96** [comment]
`\n` is used in many places in our tests.

https://github.com/mermaid-js/mermaid/blob/9a5cae9c6343db61d0479827c52b7ff9978c0eba/packages/mermaid/src/diagrams/class/classDiagram.spec.js#L110-L115

Please reopen with a reproduction repo in case the issue is still present.
