### ISSUE TITLE
Static analysis action fails

### ISSUE THREAD

**Issue by chris579** [mermaid-js/mermaid#1164]
The newly added GitHub Action for static test analysis fails.

https://github.com/mermaid-js/mermaid/commit/6cbbf0af2f7bdbfc6bea4dbdfce64c466408a8f0/checks?check_suite_id=377334155

**Comment by chris579** [comment]
@DavertMik could you have a look into this? Seems like your action fails for no reason.

**Comment by GDFaber** [comment]
Hi @chris579, is this still an issue or can we close here?

**Comment by chris579** [comment]
Looks like it got disabled already. Could be removed completely imo.
