### ISSUE TITLE
Refactoring: Break out getRows 

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#1169]
**Code duplication**
state/stateRenderer.js and state/shapes.js both contain identical implementations of getRows function.

It should be broken out to a common function. It is also similar to the sanitize function in flowDb. A more generic approach could cater all those use cases.

Create a folder called 'common' with common functions that are shared between the diagrams.

**Comment by GDFaber** [comment]
I like the idea of centralizing functionality. Perhaps later on there will be more to put there, like splitting text lines with the line break regex (haven't double-checked that, just came to my mind when I was reading this).

**Comment by jgreywolf** [comment]
We have a utility module, should we add things like this here, or not, as this would be common functionality more diagram specific?
