### ISSUE TITLE
Animation and Arrow sign and CSS in mermaid

### ISSUE THREAD

**Issue by MdMohiuddin** [mermaid-js/mermaid#1173]
1. Actually I want to do some animation on my flowchart . How can I do it?
2. The edge line is colored but the arrow is not.
3. How I can use CSS in mermaid.
![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/13714230/71708345-d3766300-2e1a-11ea-93a5-9246c1b7efc8.jpg)

**Comment by GDFaber** [comment]
Coloring the arrow heads will be done in #1236.

**Comment by jgreywolf** [comment]
@MdMohiuddin please see [documentation](https://mermaid-js.github.io/mermaid/#/flowchart?id=styling-and-classes) for more on how to use CSS for styling diagrams

**Comment by jgreywolf** [comment]
As to animation - this is not supported in Mermaid, and there are no plans to introduce this feature in the near future.

I will be closing this issue in 30 days if there are no other questions.
