### ISSUE TITLE
[Question]how to make programming flowchart?

### ISSUE THREAD

**Issue by retsyo** [mermaid-js/mermaid#1174]
I mean, the flowchart we can find, for example, on http://flowchart.js.org/

I have read that mermaid supports flowchart, but which is not a flowchart for programming. As we have known, there is a special shape for start/end, decision, and so on. And the lines are vertical or horizontal with arrow.

Thanks

**Comment by GDFaber** [comment]
Hi @retsyo,

> As we have known, there is a special shape for start/end, decision, and so on.

The start/end shapes have already been added to mermaid and will be part of an upcoming release. Currently there is no subroutine shape though.

> And the lines are vertical or horizontal with arrow.

Arrows are not a problem, but mermaid uses dagre-d3 to create the flowchart layout. It is very likely that there is no setting in dagre-d3 to draw the lines only vertically/horizontally in a strict way.

You may want to try using the ```curve``` setting in the [flowchart configuration](https://mermaid-js.github.io/mermaid/#/mermaidAPI?id=flowchart) and try if ```step```, ```stepBefore``` or ```stepAfter``` suits you, but it will still differ from the example you linked above.

You can try the live editor if you are interested, follow the link for an example according to the example in the link:
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEJcbkEoU3RhcnQpXG5CW015IE9wZXJhdGlvbl1cbkN7WWVzPGJyPm9yIE5vP31cbkRbY2F0Y2ggc29tZXRoaW5nLi4uXVxuRShFbmQpXG5GW3BhcmFsbGVsIHRhc2tzXVxuR1tNeSBTdWJyb3V0aW5lXVxuQS0tPkJcbkEtLT5GXG5BLS0tR1xuQi0tPkNcbkMtLXllcy0tPkRcbkMtLW5vLS0-RlxuRC0tPkVcbkYtLT5HIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

**Comment by GDFaber** [comment]
Hi @retsyo, feel free to ask if you need further information on this topic.
If you feel like your questions have been answered, would you agree to close this issue?

**Comment by GDFaber** [comment]
I think we can close this issue, feel free to open a new one if you run into problems.
