### ISSUE TITLE
subclassDiagram

### ISSUE THREAD

**Issue by carterbox** [mermaid-js/mermaid#1180]
I would like to be able to use the [`subgraph`](https://mermaid-js.github.io/mermaid/#/flowchart?id=subgraphs) feature from Flowchart in [`classDiagrams`.](https://mermaid-js.github.io/mermaid/#/classDiagram) This is because it would allow me to show in my class diagram how groups of classes are organized into modules or packages.

**Comment by chris579** [comment]
Duplicate of #1052
