### ISSUE TITLE
How to force a specific height of a flowchart node?

### ISSUE THREAD

**Issue by MatinF** [mermaid-js/mermaid#1185]
Hi all,

I'm trying to create a very basic flow chart - but I'd like to force a smaller height on the nodes. I'm using mermaid via [jekyll-mermaid](https://github.com/jasonbellamy/jekyll-mermaid).

While this works on some desktop browsers (e.g. on my own Chrome), it's creating some incorrect displays on some mobile screens and some PC browsers.

Any suggestions as for a more "correct" way of achieving a more slim node height?

```
A(Configure)
  B(Record)
  C(Transfer)
  D(Process)
  E(Display)
  A-->B
  B-->C
  C-->D
  D-->E
  classDef bluenode fill:white,stroke:#3d85c6,stroke-width:1px,height:20px,text-align:center,line-height:8px,y:-10px
  class A,B,C,D,E bluenode;
```

**Comment by jgreywolf** [comment]
@MatinF Do you still have any questions on this?

**Comment by MatinF** [comment]
No, thanks
