### ISSUE TITLE
Dotted Line not clearly visible in High Contrast Black

### ISSUE THREAD

**Issue by shpraka** [mermaid-js/mermaid#1187]
**Describe the bug**
Dotted line is not clearly visible in HCB for default theme. 

**To Reproduce**
Go to [live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFI7XG5BVFtcInh5elwiXSAtLT4gRFRbXCJhYmNcIl07XG5BVCAuLT4gQVtcIkJcIl0iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ==)

**Expected behavior**
It should be visible in default theme as well the way it's visible in dark theme. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46188819/71965655-1cb52100-3226-11ea-85dc-28bd7cb04fe0.png)

**Desktop (please complete the following information):**
- OS: [ Windows etc.]
- Browser [ chrome, Edge etc]

**Comment by Pepper-Wood** [comment]
Hi @shpraka! What tool do you use to enable HCB on websites? I just set up this one provided by Google on the Chrome Extension marketplace. The dotted lines render as white:

<img width="1429" src="https://user-images.githubusercontent.com/7936720/76995429-3b225180-6926-11ea-8300-a11ed9ba85ea.png">

**Comment by Dunning-Kruger** [comment]
Pending of reproduction on the current version.

**Comment by johnverbiest** [comment]
I tried to reproduce in Firefox with Dark Reader plugin, and it worked fine as well.
