### ISSUE TITLE
Class diagram - First character of relation name gets cut off.

### ISSUE THREAD

**Issue by fgrandel** [mermaid-js/mermaid#1192]
**Describe the bug**
When defining a relation without a space between the colon and the relation name, then the first character of the relation is being cut off.

**To Reproduce**
```mermaid
classDiagram
      ClassA --> ClassB:relation
```

**Expected behavior**
The relation name should be displayed as "relation"

**Actual behavior**
The relation name is rendered as "elation"

A PR with a proposed fix follows.

**Comment by Dunning-Kruger** [comment]
Live editor sample [here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gICAgICBDbGFzc0EgLS0-IENsYXNzQjpyZWxhdGlvbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19).
