### ISSUE TITLE
Class Diagram - Multiple relations are discarded.

### ISSUE THREAD

**Issue by fgrandel** [mermaid-js/mermaid#1193]
**Describe the bug**
When two classes are related by multiple distinctly labeled relations then only the last relation will actually be rendered.

**To Reproduce**
```mermaid
classDiagram
      ClassA --> ClassB: rel1
      ClassA --> ClassB: rel2
```

**Expected behavior**
Two relations should be rendered with different names.

**Actual behavior**
Only the last relation will be rendered.

As per UML spec multiple relations between classes are allowed, so mermaid should IMHO support that kind of diagram.

PR follows.

**Comment by Dunning-Kruger** [comment]
Live editor sample [here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gICAgICBDbGFzc0EgLS0-IENsYXNzQjogcmVsMVxuICAgICAgQ2xhc3NBIC0tPiBDbGFzc0I6IHJlbDIiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGFyayJ9fQ).

**Comment by fgrandel** [comment]
No idea why the static test fails - seems to be some unrelated setup problem.

**Comment by callaertanthony** [comment]
Hi !
It seems that the solution provided only resolves Class Diagram, is it possible to also consider State Diagram ?
This would offer the possibility for a state to have multiple transitions for a same sink.

```
stateDiagram
	State1 --> State2 : transition1
	State1 --> State2 : transition2
```
