### ISSUE TITLE
Node ID appears in flowchart node with "empty" label when a style is used

### ISSUE THREAD

**Issue by joebordes** [mermaid-js/mermaid#1196]
Look [at this graph](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggTFJcbkEoKCApKSAtLT58c3RlcCAxfCBCXG5CKCggKSkgLS0-fHN0ZXAgMnwgQygoICkpXG5DKCggKSkgLS0-fHN0ZXAgM3wgRCgoICkpXG5saW5rU3R5bGUgMSBzdHJva2U6Z3JlZW55ZWxsb3csc3Ryb2tlLXdpZHRoOjJweFxuc3R5bGUgQyBmaWxsOmdyZWVueWVsbG93LHN0cm9rZTpncmVlbixzdHJva2Utd2lkdGg6NHB4IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)

```
graph LR
A(( )) -->|step 1| B
B(( )) -->|step 2| C(( ))
C(( )) -->|step 3| D(( ))
linkStyle 1 stroke:greenyellow,stroke-width:2px
style C fill:greenyellow,stroke:green,stroke-width:4px
```

![image](https://user-images.githubusercontent.com/1237191/72100745-751e1880-3323-11ea-8adf-6d5c1523224a.png)

1.- Is there a way to keep the link label (step 2) on top of the link?
2.- Is there a way to not have the ID of the node (C), set into the node? I would like to keep the small size and space the other non-styled nodes have

Thanks

**Comment by GDFaber** [comment]
Hi @joebordes,

> 1.- Is there a way to keep the link label (step 2) on top of the link?

this has already been fixed and will be included in an upcoming release.

> 2.- Is there a way to not have the ID of the node (C), set into the node? I would like to keep the small size and space the other non-styled nodes have

That one is new to me. If the style for node C is removed, it is empty like the others. I would also expect it to be empty if a style is defined.

Thanks for reaching out.

**Comment by joebordes** [comment]
1.- Great!!

2.- do you want me to create a bug report?

**Comment by GDFaber** [comment]
This issue is now marked as a bug report. I think that's ok because you already provided an example showing the problem.

**Comment by Dunning-Kruger** [comment]
We might want to edit the title and opening comment to reflect the bug that still exists only, and exclude the already fixed one.

**Comment by GDFaber** [comment]
PR coming up.
