### ISSUE TITLE
"#id" Syntax Not Working for Flowchart Click Events

### ISSUE THREAD

**Issue by commonsguy** [mermaid-js/mermaid#1218]
#689 suggests that `"#id"` should work in `click` to jump to another portion of the current page. This does not appear to be working.

**To Reproduce**

1. UnZIP [MermaidIdSyntaxIssue.zip](https://github.com/mermaid-js/mermaid/files/4105342/MermaidIdSyntaxIssue.zip), which will give you a `mermaid-test.html` file, pulling in `https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js` for the Mermaid distribution. In the first diagram, it contains:

```
click predstate0 "#state-PromptedForLocationServices"
```

to have a click jump the node with the `id` of `state-PromptedForLocationServices`.

2. Load that in your favorite Web browser (tested on Chromium and Firefox).

3. In the first flowchart diagram, click the "PromptedForLocationServices" bubble (bottom of left-most branch).

**Expected behavior**

To jump to the "2. PromptedForLocationServices" heading, the way that `Test link #2` does at the bottom of the page, as that refers to the same `id`:

```
<a href="#state-PromptedForLocationServices">Test link #2</a>
```

**Actual behavior**

On Chromium, it goes to `about:blank#blocked`. On Firefox, the click seems to be ignored. 

Note that if you replace `"#state-PromptedForLocationServices"` with a regular URL (e.g., `"https://commonsware.com"`), clicking the flowchart node works, so clicking in general is fine. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Chromium 79.0.3945.79, Firefox 72.0.1

**Comment by jgreywolf** [comment]
It looks like this could be due to security settings (see [documentation](https://mermaid-js.github.io/mermaid/#/flowchart?id=interaction)) . Specifically, if securityLevel='strict' then all links will be changed to `about:blank`. 

However, if you changed it to a plain URL and everything worked fine, then I'm a little less sure...

**Comment by commonsguy** [comment]
I have:

```html
<script>mermaid.initialize({startOnLoad:true,securityLevel:'loose'});</script>
```

So, AFAIK, I already have it set to `loose`.

**Comment by GDFaber** [comment]
There seems to be a problem concerning click events via function names as well, I'll open a new issue for that. But since this is issue also about click events in flowcharts, I also assign me here.
