### ISSUE TITLE
Subgraph Coloring

### ISSUE THREAD

**Issue by spbert29** [mermaid-js/mermaid#1224]
I am not sure if this is a feature request but i think so. 
At the moment there is no easy way to color subgraphs - at big processes which i want to visualize, there are a lot of subgraphs and you simply loose the overview if each single subgraph has got the same fill color

![image](https://user-images.githubusercontent.com/42182294/73167788-d0f4e980-40f8-11ea-824e-3526cae894f0.png)

I would like to have the same thing as on nodes on the flowchart

A-->B
B-->C

classdef test color:red
class A test

subgraph test123
C-->D
end

classdef subgraphcolor fill:lightblue
class test123 subgraphcolor 

I tried to "recolor" the cluster class that is working fine as long as you have one subgraph, if you have 2 different Subgraphes I haven't found a way yet, to distinguish or seperate them. 

![image](https://user-images.githubusercontent.com/42182294/73168019-49f44100-40f9-11ea-9eae-097f0789baec.png)

At the code they are seperated:

![image](https://user-images.githubusercontent.com/42182294/73168487-35fd0f00-40fa-11ea-9b97-03797a3afd1d.png)

But with this code it wasnt working
![image](https://user-images.githubusercontent.com/42182294/73168038-56789980-40f9-11ea-92d3-615a510b4b06.png)

**Comment by knsv** [comment]
Good idea. This should be implemented.

**Comment by knsv** [comment]
This fix will make sure the assigned class set in the diagram is applied to the subgraph in the DOM element. This will make it easy to apply external styling to that class as well as setting the background.

It will not however be sufficient to set the text color. The text color in svgs are set by the fill property which would apply to both the rect and and the title label.

My suggested improvement for this is to piggyback on the color attribute. When a color attribute is set on a node or a subgraph it will be applied on the node but a second style will be applied for tspans below the node or subgraph where the color code will be set (using fill).

This will make it possible to set the text color using the color attribute which is probably what most people start with before hitting the docs... :)

**Comment by GDFaber** [comment]
> My suggested improvement for this is to piggyback on the color attribute.

That's what we did to enable coloring the text in nodes and link labels, so it would also be consistent. I have a PR for the link labels which adds the method `stylesFromArray` to utils.js, maybe it qualifies here as well.

**Comment by knsv** [comment]
Great, consistency! Must keep it simple for the diagram authors. Will take a look at stylesFromArray.
