### ISSUE TITLE
Support dashes (-) as part of the actor names in the sequence diagrams

### ISSUE THREAD

**Issue by carlosblanco** [mermaid-js/mermaid#1228]
Support dashes (-) as part of the actor names in the sequence diagrams

Ability to have actors with dash in the names.

`data-client-->data-source: Fetch Data `

**Comment by seangwright** [comment]
I'm guessing that the parser sees the `-` as part of an edge between vertices.

Maybe there could be an escape syntax or enclosing a name in `[]` to provide delimeters...

**Comment by carlosblanco** [comment]
I think changing the RegEx for actors from `[^\+\->:\n,;]+` to `[^\+\->:\n,;]+(-*[^\+\->:\n,;]+)*` will do the trick.
