### ISSUE TITLE
How to add styling for link text?

### ISSUE THREAD

**Issue by Redcxx** [mermaid-js/mermaid#1242]
I am using typora to write notes, but my background is dark and the link text is black which make it hard to read, may I know how to style the link text?
![my problem image](https://i.ibb.co/crYPWyc/image.png)

**Comment by GDFaber** [comment]
Hi @Redcxx, thank you for reaching out.

Styling the text color of nodes and links has just been added lately and will be part of an upcoming release.

For further information you can refer to:
#962 (this is what should solve the problem you stated)
#487 (this is about changing the text color of the nodes)

**Comment by Redcxx** [comment]
I have added the line  `linkStyle default color:#ffffff` and it should work after the release.
Thanks for the quick reply and help!

**Comment by GDFaber** [comment]
> I have added the line linkStyle default color:#ffffff and it should work after the release.

This works in 8.4.7, I just tested in the [live-editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbkEoXCJQZXJjZXB0aW9uXCIpIC0tPiB8Y29udmVydHxCKFwiUmVwcmVzZW50YXRpb25cIilcbkMoXCJQZXJmb3JtIEFsZ29yaXRobXVzIC8gYW5hbHl6ZVwiKSAtLT4gQlxubGlua1N0eWxlIGRlZmF1bHQgY29sb3I6I2YwMFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0) to be sure.
