### ISSUE TITLE
SyntaxError: Malformed arrow function parameter list

### ISSUE THREAD

**Issue by rajasekaran2003** [mermaid-js/mermaid#1243]
Getting this syntax error after updating the package from 8.3.1 to 8.4.x. All the 8.4's are throwing this error.

Did any syntax change or is this an error with the minified js?

**Comment by knsv** [comment]
Thanks for your report, could you please supply a little more info so that we can try to reporoduce the issue?

**Comment by rajasekaran2003** [comment]
I'm using mermaid in a web project and I have bundle and minify turned on - https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.1&tabs=visual-studio

Nothing fancy with minify. just default of what visual studio provides. I tried it with a very basic loading of mermaid and that fails with the above error.

on the same web project, I'm able to load the versions of mermaid < 8.4 but not >= 8.4.

**Comment by rajasekaran2003** [comment]
[sampleApp.zip](https://github.com/mermaid-js/mermaid/files/4162945/sampleApp.zip)

**Comment by rajasekaran2003** [comment]
Is this still something on your radar?

**Comment by jgreywolf** [comment]
@rajasekaran2003 Can you confirm this is still an issue with version 10?
