### ISSUE TITLE
Allow gitGraph commit.id to be set

### ISSUE THREAD

**Issue by jcgleissner** [mermaid-js/mermaid#1244]
**Is your feature request related to a problem? Please describe.**
I am always pushing for people to move from SVN or other types of no-versioning-systems to git. To do this a graphic representation does wonders. Mermaid is in a form that makes lends itself to a somewhat 

**Describe the solution you'd like**
I'd like to be able to set the id for git commits to a given string. This way I could use mermaid to render a git graph for repositories actually in use with the actual commit messages or short-SHA's.

```
gitGraph:
options
{
    "nodeSpacing": 150,
    "nodeRadius": 10
}
end
commit["Initial Commit"]
branch newbranch
checkout newbranch
commit["added things on newbranch"]
commit["could also be an actual commit SHA"]
checkout master
commit
commit
merge newbranch
```

**Describe alternatives you've considered**
GitX and the git cli, which are not integrated with display solutions like Grafana.

**Additional context**
The endgame would be to use a decent git graph and then color it's branches according to it's build/test status to provide a great overview for CI/CD. This would be done in using the [mermaid diagram plugin for Grafana](https://github.com/jdbranham/grafana-diagram) and feeding it a gitGraph generated on changes via hooks.

**Comment by jcgleissner** [comment]
I'm also up to implement it myself, but might need some pointers.

**Comment by knsv** [comment]
Sounds great! Let me/us know how we can help. It might be a good idea to joi our slack forum. Thats a good place to get in touch. If you do that give me a ping.

**Comment by knsv** [comment]
BTW: We looked at the gitGraph recently and concluded that there are some general improvements that need to happen as well. Maybe we can tag team it as in split it up:
* Update grammar for parsing and data gathering
* Update/rewrite rendering

**Comment by nirgn975** [comment]
I would also love a way to set the hashes myself and not let them be randomly generated every refresh.

**Comment by ashishjain0512** [comment]
The newer version of GitGraph solves this
