### ISSUE TITLE
Sequence diagram creation and destruction

### ISSUE THREAD

**Issue by ihabawad** [mermaid-js/mermaid#1246]
Please support the object "creation" and "destruction" visualizations for sequence diagrams. These are super important for representing the lifecycles of objects, and lifecycles are, in turn, very usefully represented in sequence diagrams!

![Example](https://user-images.githubusercontent.com/14828452/73974148-b3820580-48d8-11ea-9ca1-afab008845d0.png)

**Comment by dvetutnev** [comment]
I wish this feature.

**Comment by gaelmotte** [comment]
Duplicated By https://github.com/mermaid-js/mermaid/issues/1838

**Comment by gaelmotte** [comment]
+1 :)

**Comment by gcoderre** [comment]
+1

**Comment by jgreywolf** [comment]
Closing in favor of #1838

**Comment by XorNegative** [comment]
+1
