### ISSUE TITLE
how to add a scrollbar  to gantt diagram in mobile?

### ISSUE THREAD

**Issue by jerryc127** [mermaid-js/mermaid#1256]
## Help us help you!
You want an answer. Here are some ways to get it quicker:
* Use a clear and concise title.
* Try to pose a clear and concise question.
* Include as much, or as little, code as necessary.
* Don't be shy to give us some screenshots, if it helps!

![image](https://user-images.githubusercontent.com/16351105/74593196-a943d200-5063-11ea-87a8-1a3569818987.png)

the date will mix together when visit the website in mobile
i want to add a scrollbar
make the gantt diagram have a enough space to show the date

i trying to add a css
```
.mermaid{
overflow: auto; 
}
```

the graph will have a scrollbar ,the other not

**Comment by mvandermade** [comment]
The live editor doesn't seem to have the same issue:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/33425497/75097497-b30d8e00-55ab-11ea-83bd-f75dabddaaed.png">

You can try to inspect the code and compare it to yours ?

**Comment by osfpu** [comment]
My similar issue example:
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbnRpdGxlIE1hcmNoIFBsYW5cbmRhdGVGb3JtYXQgWVlZWS1NTS1ERFxuc2VjdGlvbiBFbmdsaXNoIFByYWN0aWNlXG7lvoXlrpogOiBhMSwgMjAyMC0wMi0yNCAsIDV3XG5zZWN0aW9uIExvc2UgV2VpZ2h0XG4ya2cgOiBiMSwgMjAyMC0wMi0yNCwgMndcbjFrZyA6IGIyLCBhZnRlciBiMSwgMndcbjAuNWtnIDogYjMsIGFmdGVyIGIyLCAxd1xuc2VjdGlvbiBBSSBMZWFybmluZ1xuU3VtbWFyeSA6IGMxLCAyMDIwLTAyLTI0LCAxd1xuUGxhbiA6IGMyLCBhZnRlciBjMSwgMXdcblRCRCA6IGMzLCBhZnRlciBjMiwgM3dcbnNlY3Rpb24gUGlhbm9cblN1bW1hcnkgOiBkMSwgMjAyMC0wMi0yNCwgMXdcblBsYW4gOiBkMiwgYWZ0ZXIgZDEsIDF3XG5UQkQgOiBkMywgYWZ0ZXIgZDIsIDN3XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

**Comment by mvandermade** [comment]
About the adding a scrollbar, when I change the width manually, the tick text still overflows:
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/33425497/75110669-2efde980-5631-11ea-8944-a0c7e8813af9.png">


And it seems that the ticks behave irregular:
Here with 7d
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/33425497/75110680-5785e380-5631-11ea-875c-8a7b61a8a43a.png">

And here with 8d
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/33425497/75110684-68365980-5631-11ea-90aa-8f9c46e483e0.png">

So my tip for now; try varying the length of the gantt chart to fix the ticks spacing.

**Comment by mvandermade** [comment]
> My similar issue example:
> https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbnRpdGxlIE1hcmNoIFBsYW5cbmRhdGVGb3JtYXQgWVlZWS1NTS1ERFxuc2VjdGlvbiBFbmdsaXNoIFByYWN0aWNlXG7lvoXlrpogOiBhMSwgMjAyMC0wMi0yNCAsIDV3XG5zZWN0aW9uIExvc2UgV2VpZ2h0XG4ya2cgOiBiMSwgMjAyMC0wMi0yNCwgMndcbjFrZyA6IGIyLCBhZnRlciBiMSwgMndcbjAuNWtnIDogYjMsIGFmdGVyIGIyLCAxd1xuc2VjdGlvbiBBSSBMZWFybmluZ1xuU3VtbWFyeSA6IGMxLCAyMDIwLTAyLTI0LCAxd1xuUGxhbiA6IGMyLCBhZnRlciBjMSwgMXdcblRCRCA6IGMzLCBhZnRlciBjMiwgM3dcbnNlY3Rpb24gUGlhbm9cblN1bW1hcnkgOiBkMSwgMjAyMC0wMi0yNCwgMXdcblBsYW4gOiBkMiwgYWZ0ZXIgZDEsIDF3XG5UQkQgOiBkMywgYWZ0ZXIgZDIsIDN3XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

Here I can fix it by extending an item a couple of days:
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbnRpdGxlIE1hcmNoIFBsYW5cbmRhdGVGb3JtYXQgWVlZWS1NTS1ERFxuc2VjdGlvbiBFbmdsaXNoIFByYWN0aWNlXG7lvoXlrpogOiBhMSwgMjAyMC0wMi0yNCAsIDV3XG5zZWN0aW9uIExvc2UgV2VpZ2h0XG4ya2cgOiBiMSwgMjAyMC0wMi0yNCwgMndcbjFrZyA6IGIyLCBhZnRlciBiMSwgMndcbjAuNWtnIDogYjMsIGFmdGVyIGIyLCAxd1xuc2VjdGlvbiBBSSBMZWFybmluZ1xuU3VtbWFyeSA6IGMxLCAyMDIwLTAyLTI0LCAxd1xuUGxhbiA6IGMyLCBhZnRlciBjMSwgMXdcblRCRCA6IGMzLCBhZnRlciBjMiwgNHdcbnNlY3Rpb24gUGlhbm9cblN1bW1hcnkgOiBkMSwgMjAyMC0wMi0yNCwgMXdcblBsYW4gOiBkMiwgYWZ0ZXIgZDEsIDF3XG5UQkQgOiBkMywgYWZ0ZXIgZDIsIDN3XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ

**Comment by jgreywolf** [comment]
@mvandermade As it has been some time since this issue was created, can you verify if this is still an issue?

**Comment by mvandermade** [comment]
If you ask me the issue can be closed. Thanks for asking!
