### ISSUE TITLE
cannot add autonumber in sequence diagrams

### ISSUE THREAD

**Issue by goutham2688** [mermaid-js/mermaid#1257]
cannot add autonumber in sequence diagram's

**Steps to reproduce the behavior:**
1. GoTo Mermaid live editor
2. click on sequence diagrams
3. add "autonumber" tag on top of the sequence 
4. "Syntax error" was shown in the editor

**Expected behavior**
Seems like this feature is already implemented per PR#722

**Screenshots**
![2020-02-16 08_34_59-Mermaid live editor](https://user-images.githubusercontent.com/12175784/74605578-597efe00-5097-11ea-8106-e940b27b820b.png)

**Desktop:**
 - OS: Windows
 - Browser: FireFox 73.0 
 - Mermaid Version: 8.4.6

**Comment by knsv** [comment]
Thanks for this report.

This was not so well documented in the md files and there is no rendering tests for the functionality.

The current approach is to add this configuration sitewide. Like below:
```
      mermaid.initialize({
        logLevel: 0,
        flowchart: { curve: 'linear', "htmlLabels": false },
        sequence: { actorMargin: 50, showSequenceNumber: true },
      });
```
 I like the approach with turning it on/off per diagram with the keyword autonumber better so I will repair the and modify the functionality for 8.4.8
