### ISSUE TITLE
Some annoying console.log in the latest release

### ISSUE THREAD

**Issue by ixdi** [mermaid-js/mermaid#1261]
Hi,
In the latest release 8.4.7 there are some annoying console.log. Is it possible to remove them?
(specially the console.log(style))
Thanks!

**Comment by jerryc127** [comment]
yes. i also find this
![image](https://user-images.githubusercontent.com/16351105/74675968-d329ff80-51ef-11ea-9baf-78bb6c4f3426.png)

**Comment by knsv** [comment]
Sorry about that. There will be an 8.4.7 update fixing that soon.
