### ISSUE TITLE
Need a list of software that can us MermaidJS

### ISSUE THREAD

**Issue by jensenbox** [mermaid-js/mermaid#1264]
I think a portion of the readme should either list or link out to a lost of all software that can use MermaidJS.

The 'how" of integration would be awesome as well.

**Comment by mvandermade** [comment]
Are you looking for something like this? 
https://www.npmjs.com/browse/depended/mermaid

**Comment by jensenbox** [comment]
Not really - something that would list all the software that supports if from the end user side. 

Like (as a starting point):

- https://docs.gitlab.com/ee/user/markdown.html#mermaid
- https://marketplace.atlassian.com/apps/1214124/mermaid-plugin-for-confluence?hosting=server&tab=overview
- https://learn.netlify.com/en/shortcodes/mermaid/

I am hoping this could increase the overall visibility and have a place for software producers to add themselves to the list of software that supports mermaid.

One big one I would like to see support mermaid is GitHub - here is a nice canary page - of this page starts working, we know that GH has started supporting mermaid natively: https://github.com/neenjaw/mermaid-markdown-test/blob/master/test/flow_inline.md

**Comment by mvandermade** [comment]
Yes, for example VScode also has a plugin.

I didn't know gitlab already started using it 2 years ago 👍 
If GitHub would start to use it, it would be awesome.

We can start the list in the Wiki of this Github ?

**Comment by mvandermade** [comment]
https://github.com/mermaidjs/mermaid-gitbook is the source of the website

**Comment by chris579** [comment]
> https://github.com/mermaidjs/mermaid-gitbook is the source of the website

The website is generated with GitHub Pages and is located [right in this repo](https://github.com/mermaid-js/mermaid/tree/develop/docs). The Gitbook repo isn't used any more. Also, the orga `mermaidjs` is not associated with `mermaid-js` in any kind.

**Comment by mvandermade** [comment]
imho this page is a good place to start: https://mermaid-js.github.io/mermaid/#/n00b-gettingStarted?id=mermaid-using-plugins

**Comment by jensenbox** [comment]
That page seems a bit buried. I am thinking of more of a first class citizen so it is really easy just to add yourself to a running list. Nothing fancy, just a bullet list of all in-the-wild implementations.

**Comment by chris579** [comment]
The README would be a good place. Somewhere at the bottom, just a simple bullet list.

**Comment by jgreywolf** [comment]
I have started compiling a list of these.  

Includes plugin/extensions for various apps/tools, as well as other systems (like GitLab) that are using Mermaid directly with their markdown
