### ISSUE TITLE
How to declares the direction of the subgraph layout?

### ISSUE THREAD

**Issue by chen4221** [mermaid-js/mermaid#1265]
Can you help me?
How to declares the direction of the subgraph layout?
```
graph TD
    graph definition
```
```
subgraph title TD
    graph definition
end
```
tks!

**Comment by GDFaber** [comment]
Hi @chen4221, unfortunately this is currently not possible. Flowchart rendering depends on dagre which does not offer the functionality to set different directions in the subgraphs either, so it's rather tricky to get it to work.

But this issue should be left open as many people have requested this feature. If you or someone else reading this can give a pointer, feel free to do so.

**Comment by jcampbell** [comment]
I just found this issue from a naïve search from a linked issue that noted that mermaid relies on dagre. Dagre mentions that graphviz offers more functionality for environments where rendering does not have to be done client-side. Having come to mermaid via a desktop note-taking software, I'm completely unfamiliar with the range of users--is client-side rendering important for mermaid?

**Comment by antoniomolram** [comment]
there is some movement in this feature? I just wanted to use it and... I can't. Thank you for your work!

**Comment by sebhahn** [comment]
same for me

**Comment by vishae** [comment]
I would also love to see support for specifying a different orientation for a subgraph

**Comment by bazomatic** [comment]
I'd also love to see different subgraph orientation support somehow within Mermaid; it's so close to replacing Visio/Cacoo/Gliffy/Mural/etc for my needs, but there are certain things it just can't do yet

**Comment by lterfloth** [comment]
This feature would really be appreciated. Lots of flexibility would be added to use mermaid for even more cases. Currently this limits me quite a bit.
