### ISSUE TITLE
State transition label renders incorrect on safari

### ISSUE THREAD

**Issue by Pyrolistical** [mermaid-js/mermaid#1269]
**To Reproduce**
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5cbkEgLS0-IEIgOiB0aGlzIHRleHQgY2F1c2VzIHRoZSByZW5kZXJpbmcgYnVnXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

This is what it looks like on Safari
![Screen Shot 2020-02-21 at 14 29 38](https://user-images.githubusercontent.com/463642/75077310-2f727500-54b7-11ea-9a8f-f1ac8d0dbabe.png)

**Expected behavior**
This is what it looks like on Chrome and Firefox
<img width="341" alt="Screen Shot 2020-02-21 at 14 29 52" src="https://user-images.githubusercontent.com/463642/75077292-241f4980-54b7-11ea-9ec9-6157cd330e05.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3 
 - Browser Safari
 - Version 13.0.5 (15608.5.11)

**Comment by knsv** [comment]
Thanks for reporting. I will take a look

**Comment by knsv** [comment]
The bounding query of bounding box dimensions in safari isnot returning expeced results. Made a workaround that seems to work. Can reproduce the arrow issue though. I suspect that it has to do with the editor.

**Comment by FranklinYu** [comment]
We have another example which might be affected by the same bug in Safari SVG engine: https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5cbmEgLT4-IGI6YyIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

So it looks like Safari doesn’t support `marker-end`? But the example at [marker-end](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-end) works on Safari for some reason… If this is deemed Safari bug we can consider report them at https://bugs.webkit.org?
