### ISSUE TITLE
sequencenumber is not displayed with the text has a <br> tag

### ISSUE THREAD

**Issue by goutham2688** [mermaid-js/mermaid#1271]
**Describe the bug**
While creating sequence diagrams with autonumber enabled, if i add a <br> tag to the text then the sequence number disappears from the diagram.

**To Reproduce**
1. Go to Mermaid Live Editor
2. Click on Sequence diagrams
3. Create a sequence that has both autonumber enabled and <br> tag in it and is self referencing (eg., John-->John: lorem ipsum <br> dolar)
4. See the sequence number is not displayed anymore in the diagram.

**Expected behavior**
The sequence number should be shown

**Screenshots**
![2020-02-22 16_35_18-Mermaid live editor](https://user-images.githubusercontent.com/12175784/75099600-77fe6100-5591-11ea-9a3f-58eb405c3566.png)

**Desktop (please complete the following information):**
 - Browser Firefox 73.0.1
 - mermaid Version 8.4.8

**Comment by rajasekaran2003** [comment]
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gIGF1dG9udW1iZXJcblx0QWxpY2UtPj4rSm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_XG5cdEFsaWNlLT4-K0pvaG46IEpvaG4sIGNhbjxici8-IHlvdSBoZWFyIG1lP1xuXHRKb2huLS0-Pi1BbGljZTogSGkgQWxpY2UsIEkgY2FuIGhlYXIgeW91IVxuXHRKb2huLS0-Pi1BbGljZTogSSBmZWVsIGdyZWF0IVxuXHRcdFx0XHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

still a problem on 8.5.0 with chrome
