### ISSUE TITLE
download png not working for sequence diagrams

### ISSUE THREAD

**Issue by goutham2688** [mermaid-js/mermaid#1272]
**Describe the bug**
clicking on download png results in an empty png file

**To Reproduce**
1. Go to mermaid live editor
2. Click on sequence diagrams
3. click on download png
4. an empty white png file is downloaded

**Expected behavior**
The image of the sequence diagram created

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Mermaid version 8.4.8

**Comment by ca0v** [comment]
Cannot reproduce.  I was able to view the png file in Firefox and Edge Chromium on Windows 10.  Current version is still 8.4.8.

**Comment by goutham2688** [comment]
Issue is seen only for sequence diagrams, and not for other diagrams (i checked FlowChart and Class Diagrams)

**Comment by knsv** [comment]
Thanks for reporting. This is an issue for the mermaid-live-editor. Please report the issue there instead so you get info about its status when it changes.
https://github.com/mermaid-js/mermaid-live-editor

Thanks
