### ISSUE TITLE
mermaid-js.github.io shows 404

### ISSUE THREAD

**Issue by mvandermade** [mermaid-js/mermaid#1280]
Hi,

I am wondering why https://mermaid-js.github.io isn't being forwarded to https://mermaid-js.github.io/mermaid (shows 404)

My question rises, because https://mermaidjs.github.io currently is forwarded.
It is a little confusing to me, because there also exists a github.com/mermaidjs.

So my question, can mermaid-js.github.io also be forwarded to https://mermaid-js.github.io/mermaid as well ?

Thanks.

**Comment by GDFaber** [comment]
Hi @mvandermade, thank you for mentioning this. We fixed it and both URLs should now take you to the mermaid documentation landing page.
