### ISSUE TITLE
getBBox crashes older Firefox when called on tspan

### ISSUE THREAD

**Issue by GKJCJG** [mermaid-js/mermaid#1283]
**Describe the bug**

Mermaid Version 8.4.6 and 8.4.8.

While rendering a chart with the following specification:
classDiagram
Class01 <|-- AveryLongClass : Cool
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 --> C2 : Where am i?
Class09 --* C3
Class09 --|> Class07
Class07 : equals()
Class07 : Object[] elementData
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
Class08 <--> C2: Cool label

Firefox (version 67.0.4; version 73.0.1 is OK) crashes with an NS_ERROR_NOT_IMPLEMENTED upon reaching the call to `.getBBox()` around line 265 of this file: https://github.com/mermaid-js/mermaid/blob/develop/src/diagrams/class/svgDraw.js

At that point, the 'x' whose `.getBBox()` method is getting called is a `<tspan class="title">` element.

**To Reproduce**
Use Firefox 67.0.4
Go to Live Editor
Paste diagram above.
Watch console for NS_ERROR_NOT_IMPLEMENTED

**Expected behavior**
No crash - diagram renders.

**Desktop (please complete the following information):**
 - OS: [RHEL-7]
 - Browser [Firefox]
 - Version [67.0.4]

**Additional context**
Rendering the same graph with Mermaid 8.0.0 produces no errors.

**Comment by mvandermade** [comment]
I would advise to keep the firefox browser updated. Simply because later versions are working : https://developer.mozilla.org/en-US/docs/Mozilla/Errors

**Comment by jgreywolf** [comment]
@GKJCJG Can you please verify that this is resolved with current version of Mermaid and Firefox?

**Comment by GKJCJG** [comment]
I can't verify that it's solved, but I won't be able to replicate the bug, either, so we can close the issue if there's a reasonable belief that it's been solved.
