### ISSUE TITLE
Composite State diagram doesn't render description 

### ISSUE THREAD

**Issue by llLightTll** [mermaid-js/mermaid#1284]
```
stateDiagram
    state "Test 1" as t1{
        unkn: State 1
        [*] --> unkn
    }
```
renders
<img width="286" alt="Screenshot 2020-02-28 at 10 25 21" src="https://user-images.githubusercontent.com/61580506/75532680-b1612180-5a14-11ea-84b7-15fa719018b0.png">

expected: instead of "t1" we got "Test 1"
<img width="286" alt="Screenshot 2020-02-28 at 10 25 21" src="https://user-images.githubusercontent.com/61580506/75534246-1f0d4d80-5a15-11ea-961c-a51a15e03ab1.png">

**Comment by jgreywolf** [comment]
@llLightTll Closing as this works correctly with current version of mermaid:
https://mermaid.live/edit#pako:eNpFjs_OgjAQxF-lmaMB0wINtQdPvoGetN9hI_VPlGKgTVTCu1tL8jmn3d9MZnfEsWssNAZP3m6udO6pNY5FJcIMdnbwTBgwGpgX42x-FdzNabZNMfHDh8Ufy_N1smc6IUNr-5auTbyUGgz8xbbWQMexsScKd29g3DdKwXfblztCn-g-2Azh0fye-6cPcvuui7vvw7xCj3hCF7xaClUoIaUUtaxVhhd0zpc8Skhe8LLmlSrLlapKNWV4pxoxfQDdsE8G
