### ISSUE TITLE
Azure DevOps Wiki - Flow Diagram node text alignment

### ISSUE THREAD

**Issue by JulianHayward** [mermaid-js/mermaid#1289]
In Azure DevOps Wiki using the Mermaid extension the Flow Diagram node text alignment is aligned left and the node width is doubled. 

**Steps to reproduce the behavior**

In Azure DevOps Wiki create a new page and use code:
![image](https://user-images.githubusercontent.com/45695032/75667090-4cf1cc80-5c77-11ea-945b-a31533f19ae0.png)

```
::: mermaid
 graph TD;
 A[Boss] --> B[L1 Joe];
 A --> G[L1 Bob];
 B --> C[L2 Joe<br> Sue];
 B --> D[L2 Joe<br> Finn];
 B --> E[L2 Joe<br> Jane];
 G --> H[L2 Bob<br> Miguelangelonilo];
 G --> I[L2 Bob<br> Anna];
 I --> J[L3 Anna<br> Me];
:::
```
output looks like this:

![image](https://user-images.githubusercontent.com/45695032/75666400-094a9300-5c76-11ea-8ac9-a28fb269ac94.png)

whilst on the [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor) it looks like this:

```
 graph TD;
 A[Boss] --> B[L1 Joe];
 A --> G[L1 Bob];
 B --> C[L2 Joe<br> Sue];
 B --> D[L2 Joe<br> Finn];
 B --> E[L2 Joe<br> Jane];
 G --> H[L2 Bob<br> Miguelangelonilo];
 G --> I[L2 Bob<br> Anna];
 I --> J[L3 Anna<br> Me];
```

![image](https://user-images.githubusercontent.com/45695032/75666487-2d0dd900-5c76-11ea-8e21-4a62a49b9f4e.png)

**Comment by GDFaber** [comment]
Hi @JulianHayward, thanks for reaching out. The problem you've run into is also decumented in #1177. Do you agree to closing your issue in favor of #1177?

**Comment by JulianHayward** [comment]
hi @GDFaber - sure thing..
