### ISSUE TITLE
Red line in Gantt

### ISSUE THREAD

**Issue by Crowds21** [mermaid-js/mermaid#1290]
**Describe the bug**

When drawing a Gantt chart, a red line appears at the beginning of the month
Does it represent the current date?
And how to get rid of it.

**To Reproduce**

```mermaid
gantt
	title Plan
	dateFormat MM-DD
	axisFormat %d
	
	section Preparation
	first		        :done,a1,02-27,24h
	second		:a2,03-01,5d
	third		:a3,after a2,4d
	fourth		:a4,after a3,12d
	fifth		:03-22,1d
```	
**Expected behavior**
A red line appears in the Gantt

**Screenshots**
![line](https://user-images.githubusercontent.com/48215334/75673899-fc05c680-5cbe-11ea-958d-00ba9bf669a7.png)

**Desktop (please complete the following information):**
 - OS:Win

**Comment by Dunning-Kruger** [comment]
@Crowds21 Hey! There is no markup/configuration way of removing the line but... it is just an HTML element. You could just CSS it away with something like:
```
g.today {
    display: none;
}

**Comment by GDFaber** [comment]
We could add an option in the definition to hide the marker or give it another style as well:

```
gantt
  todaymarker off // does not show line
```

```
gantt
  todaymarker stroke:#080 stroke-width:5px
```

But that's only from top of my head and needs further examination.

**Comment by Crowds21** [comment]
> We could add an option in the definition to hide the marker or give it another style as well:
> 
> ```
> gantt
>   todayMarker off // does not show line
> ```
> 
> ```
> gantt
>   todayMarker stroke:#080,stroke-width:5px
> ```
> 
> But that's only from top of my head and needs further examination.

It is a good idea ,thanks
