### ISSUE TITLE
Support conditions/pseudostates in state diagrams

### ISSUE THREAD

**Issue by SaturnIC** [mermaid-js/mermaid#1292]
**Describe the bug**
The initial state may be dependent on some condition C.
So depending on C the initial state can vary.
The UML state diagram implements this by having a pseudostate/condition (rhombus shape),
so that the initial transition can go to the condition and split from there to two different initial states.

In Mermaid state diagramm (MSG) if two initial transitions are described, two solid circles are drawn, each with their own initial transition, which is very ugly. Also in MSG there is no pseudostate/condition element which could be used to solve this UML style.

**To Reproduce**
```
stateDiagram
  [*] --> Ready: guard1
  [*] --> UpToDate: guard2
```

**Expected behavior**
Provide a way to transition from one solid circle to two initial states.

**Proposed solution**
Either add a pseudostate/condition (rhombus shape) as in the UML state diagram or allow 
two transitions to originate from the solid circle.

**Comment by Dunning-Kruger** [comment]
@SaturnIC Hello! Thank you for the feature suggestion! Any idea on how the syntax for this should look like?

**Comment by Dunning-Kruger** [comment]
This issue is now being tracked in #1304
