### ISSUE TITLE
one arrow is partly off screen

### ISSUE THREAD

**Issue by tessus** [mermaid-js/mermaid#1293]
**Describe the bug**
The following code generates an image where one arrow is partly off screen.

```
graph TD
	a --> c;
	a --> d;
	c --> d;
```
[Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblx0YSAtLT4gYztcblx0YSAtLT4gZDtcblx0YyAtLT4gZDtcblx0XHRcdFx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

**To Reproduce**
1. Render the following code
   ```
   graph TD
	   a --> c;
	   a --> d;
	   c --> d;
   ```
2. Observe the rendered image

**Expected behavior**
The arrow should be properly shown. Please note there must be a few pixels between the left edge and the arrow.

**Screenshots**
<img width="117" alt="image" src="https://user-images.githubusercontent.com/223439/75840262-d220d280-5d98-11ea-9130-70f7e9b8c287.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox, Chrome
 - Version: all

**Smartphone (please complete the following information):**
no using a smartphone

**Additional context**
The desktop environment is irrelevant.

**Comment by GDFaber** [comment]
Hi @tessus, thank you for reporting this. I'm closing your issue in favor of #1288 because it states the same problem.
