### ISSUE TITLE
Azure DevOps Wiki - Unable to use Hexagon and Database Graph Nodes

### ISSUE THREAD

**Issue by hugofragata** [mermaid-js/mermaid#1296]
**Describe the bug**
When using the valid Hexagon or Database Nodes in a graph on the Azure DevOps Wiki, an error appears, thus causing the graph not to render.
The error is the following:
```
Parse error on line 2:
graph LR;rabbit_mq{{RabbitMQ}}
-------------------^
Expecting 'SPACE', 'GRAPH', 'DIR', 'TAGEND', 'TAGSTART', 'UP', 'DOWN', 'subgraph', 'end', 'STR', 'MINUS', '--', '==', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DEFAULT', 'PCT', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', got 'DIAMOND_START' 
```

**To Reproduce**
1. Click in edit on a Azure DevOps Page
2. Input `graph LR;rabbit_mq{{RabbitMQ}}`
3. Click Load Diagram

**Expected behavior**
It should render a simple hexagon diagram.
Using the [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor):
![image](https://user-images.githubusercontent.com/8310907/76074892-f694ce80-5f93-11ea-8481-5f41cbee33c8.png)

**Screenshots**
Here's the screenshot of the error when editing the Azure DevOps Wiki:
![image](https://user-images.githubusercontent.com/8310907/76075008-28a63080-5f94-11ea-8b51-dc863d1229c5.png)

**Comment by Dunning-Kruger** [comment]
From [their docs](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page): 
> Current version of Mermaid used is 8.2.6

Sadly, hexagon shapes are a 8.4.0 feature and of course we have no control over what version azure devops uses so we can't do anything about your issue.

**Comment by hugofragata** [comment]
I see. I was unable to find that information on the changelogs. Thanks for the heads up.
