### ISSUE TITLE
mysterious prefix 'd' appears at the the id attribute

### ISSUE THREAD

**Issue by HerbertHe** [mermaid-js/mermaid#1299]
I tried to use mermaidAPI in React to develop a markdown real-time-render editor, markdown is rendered by marked.js. When I overwrote, here something happened not as I guessed.

```ts
const mermaided = (code: string, name: string): string => {
  let rendered = ''
  try {
    mermaid.mermaidAPI.render(name, code, (html) => {
      rendered = html
    })
  } catch(e) {
    rendered = `<p>${code}</p>`
  }
  return rendered
}
```

When I ran the code, at the browser console, it had added new node `<div id="d" + name></div>` when I update the `code`, and then I tried to value `name` as `""`, and appeared mysterious prefix `d`, but I already provide a node to contain the rendered mermaid code, but I could not solve it by myself!

I push the whole code to my project [link](https://github.com/HerbertHe/for-editor), `git clone` and run `npm run dev` can 
recurrent it!!

**Comment by Dunning-Kruger** [comment]
@HerbertHe Any chance you could reproduce this on the live editor or a live version of your project? Can't recommend to anyone cloning and running an unknown project.

**Comment by HerbertHe** [comment]
@Dunning-Kruger I have uploaded a live version at [Editor](https://server.jieec.cn/editor), not absolute same but the same trouble

**Comment by Dunning-Kruger** [comment]
@HerbertHe And how do you reproduce the issue?

**Comment by HerbertHe** [comment]
@Dunning-Kruger same as what I said above, before html node, the div node would be added.

like when I inputted(not copied)

```mermaid
graph TD
    Start --> Stop
```

the node would be added! And its id would be `dgraph`

**Comment by HerbertHe** [comment]
But the project what I have uploaded to GitHub would show the issue more clearly...

**Comment by HerbertHe** [comment]
Add I recommend to add a new method like `mermaidAPI.render()` with removing required `id` just for returning the rendered DOM to provide us inject them to nodes by ourselves, thanks!

**Comment by elvezpablo** [comment]
I was unable to reproduce the issue. 

I didn't see the SVG out being rendered in the preview portion of the app you are making but I did see SVG output from the `mermaidAPI.render()` request. I was also able to substitute valid markup as a string in the `dangerouslySetInnerHTML`

```javascript 
dangerouslySetInnerHTML={{ __html:  '<h1>1</h1>'' }}
```
The above works. I suspect that you need to stringify the output of `marked(value)` to get someting to render. 

Hope that helps.
