### ISSUE TITLE
How can I draw a system structure diagram like this??

### ISSUE THREAD

**Issue by xyfuestc** [mermaid-js/mermaid#1300]
I really like mermaid for its lightweight, and I want to use it to draw the graphs of my papers. I tried my best to do, only got this:
![image](https://user-images.githubusercontent.com/62041458/76374632-c330b600-637e-11ea-90de-1ed5cc246750.png)
But my purpose is this:
![image](https://user-images.githubusercontent.com/62041458/76374662-d04da500-637e-11ea-8b4b-2cca1d753016.png)

I wanna two-way arrows and make them smoothy. Subgraph System and Subgraph Obervation can align in center and in same size.

if images cannot be seen,
[link](https://github.com/xyfuestc/mermaid/blob/develop/img/question1.md)

 Can anyone do me a favor? Thanks in advance! @watsoncj

**Comment by Dunning-Kruger** [comment]
The short answer is... you can't automatically generate a graph styled as you want.
You can take mermaid's graph and style it using CSS to fit your needs.

**Comment by jgreywolf** [comment]
@xyfuestc Here is more detailed information on [Styling and CSS](https://mermaid-js.github.io/mermaid/#/flowchart?id=styling-and-classes)
Do you have any additional questions?

**Comment by Olshansk** [comment]
I often find myself debating between using a flowchart and a state diagram, but I personally bias towards using a flowchart just because it maintains the optionality of customized CSS styling.

**Comment by jgreywolf** [comment]
Closing as there has been no response from OP, and the only way to support something similar to this would be to use the styling options linked to above

**Comment by kyouheicf** [comment]
@xyfuestc You may be able to use Block diagram (beta)
- [Block Diagram Syntax | Mermaid](https://mermaid.js.org/syntax/block.html)
```
block-beta
columns 5
  space:2 App1:1 App2:1 App3:1
  space:5
  block:System:5
    columns 5
    Observer:1 space:1 SystemCore["System Core"]:3
    space:5
    Reactor:1
  end
  App1 <--> SystemCore
  App2 <--> SystemCore
  App3 <--> SystemCore
  Observer -.- App1
  Observer -.-> Reactor
  Observer --"probe"--> SystemCore
  SystemCore --"report"--> Observer
  Reactor -.-> SystemCore
```
