### ISSUE TITLE
Class diagrams optimization

### ISSUE THREAD

**Issue by Duzx5517** [mermaid-js/mermaid#1306]
Idea  class diagrams is  beautiful ,It can distinguish between interface and abstract class.
mermaid class diagrams can only know it's class .

**Comment by jgreywolf** [comment]
Can you clarify your statement?

This [section](https://mermaid-js.github.io/mermaid/#/classDiagram?id=annotations-on-classes) of the documentation provides examples of how to indicate a class is abstract, or if it implements an interface.  

Is that what you are looking for, or something else?
