### ISSUE TITLE
Consider offering syntax like PlantUML for ER diagrams

### ISSUE THREAD

**Issue by spopida** [mermaid-js/mermaid#1309]
I just added the capability to render entity relationship diagrams to mermaid, and made up a simple syntax, e.g. `PERSON !-?< ACCOUNT : holds` is interpreted as *a person holds zero or more accounts and an account must be held by one and only one person*.

PlantUML has a similar-but-different syntax which is also pretty intuitive (and of course already in use).  For example `PERSON ||..o{ ACCOUNT` means the same thing (although the relationship label `holds` is missing). An additional nuance of PlantUML appears to be that using either dots or dashes in the relationship one can distinguish between identifying and non-identifying relationships.

@Dunning-Kruger has suggested use of PlantUML syntax - seems like a good idea.  What do others think?
- Should we just ditch my syntax in favour of PlantUML style (I have no issue with this at all)
- Should we offer two alternative styles? (Given that ER diagrams are not live yet, I'm not sure it's worth it)
- Any other thoughts? As @knsv pointed out in the original trail of issue #117 it's important to spend time now getting this right, as it will be hard to change later, without screwing existing users 
- Ofc I could extend the PlantUML syntax to include the relationship label as this is a useful (and pretty standard in my experience - in fact it's regarded as mandatory by some)

Comments greatly appreciated. Thx.

**Comment by Dunning-Kruger** [comment]
My vote is (of course) for compatibility with PlantUML, and an optional extension to accommodate labels. Maintaining two parallel syntaxes for the same functional results provides no benefit.

I'm sorry I made the suggestion so late in the process. Should've caught it earlier!

**Comment by spopida** [comment]
No problem - I should've thought of it myself - at least you did!  I'll do some work on it and post here when appropriate.

**Comment by vitonextworld** [comment]
FWIW, I have always liked the way this markup looked: https://github.com/BurntSushi/erd. Not sure how it fits with mermaid syntax/style, but just something for your consideration.

I agree having support for multiple syntaxes is not ideal. But I am most interested in getting this diagram type released.  Excited to take advantage of it. Thanks for your hard work!

**Comment by spopida** [comment]
Hi - sorry for the slight delay...it's been a crazy week here in the UK (and probably wherever you are).  I am still planning on converting the syntax to PlantUML asap, but I may be a little delayed.  Hope you and loved ones are all managing OK.  I will post here with any significant updates.

**Comment by spopida** [comment]
I am actively working on this now...making good progress.  Pls assign to me.

**Comment by GDFaber** [comment]
Thank you for looking into this.
