### ISSUE TITLE
Scaling issue of objects in flowchart

### ISSUE THREAD

**Issue by facelessuser** [mermaid-js/mermaid#1313]
**Describe the bug**
It seems that flowcharts specifically do not scale in a sane manner compared to every other chart time offered in Mermaid. It appears it may be Chrome specific as I cannot reproduce it in Firefox.

**To Reproduce**

This can be illustrated with something as simple as the following in the live editor:

```
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

When initially rendered, it looks fine:

<img width="211" alt="chrome_3chTo9FoHP" src="https://user-images.githubusercontent.com/1055125/77392353-57782100-6d60-11ea-99c3-8e9458c845b7.png">

Now if you Increase the text size in the browser and click the refresh, the proportions will be greatly exaggerated, especially compared to the text size:

<img width="458" alt="chrome_VCmo5u9D0i" src="https://user-images.githubusercontent.com/1055125/77392433-88585600-6d60-11ea-90e4-9c965a15c3f8.png">

This does **not** occur with other chart types, like sequence diagram. It seems to scale quite nicely:

<img width="506" alt="chrome_A4J8n3bd54" src="https://user-images.githubusercontent.com/1055125/77392472-a4f48e00-6d60-11ea-883a-2c20a92a0bfc.png">

<img width="801" alt="chrome_24rTWoPHuV" src="https://user-images.githubusercontent.com/1055125/77392509-bd64a880-6d60-11ea-9f2d-de8f985da365.png">

**Expected behavior**

I would expect flowcharts would nicely scale and keep proper proportions like the other chart types.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by facelessuser** [comment]
This seems to be related to using `htmlLabels` with `flowchart`. When disabling `htmlLables`, I no longer get the problematic scaling. For now, I'll turn off `htmlLabels`.

**Comment by jgreywolf** [comment]
I am going to close this issue for now due to the lack of activity, and since there is a "workaround". Please open a new issue if something still needs to be addressed
