### ISSUE TITLE
Mermaid classDiagram rendering issues in Markdown environment

### ISSUE THREAD

**Issue by Blackclaws** [mermaid-js/mermaid#1316]
**Describe the bug**
This bug is not specifically a bug if using mermaid itself but comes up when used in conjunction with markdown files for which gitlab and other sites have added syntax.

The title field of classes in the class diagram is styled by the markdown style. 

I'm not sure if mermaid is even the right place for the fix though it could certainly be one place to fix this. I just wanted to bring it to your attention that this issue exists. I've made a cross issue on gitlab itself:

https://gitlab.com/gitlab-org/gitlab/-/issues/212464

**To Reproduce**
Look at mermaid class diagrams in gitlab Markdown or in vscode with the markdown preview enhanced plugin

**Expected behavior**
Class diagram shows up as in the mermaid live editor

**Additional context**
This happens as far as I am able to ascertain because mermaid uses the class "title" for class titles. This class is used by the surrounding markdown itself however and styled appropriately with the wrong font size. Resulting in that behavior. 

What could be done to fix this is to rename the class in the mermaid generated svg from "title" to something like "classTitle". That would solve the issue.

This would likely be a breaking change for those already styling classes manually however.

**Comment by jgreywolf** [comment]
I am closing this issue as it appears that it is being addressed on the gitlab side
