### ISSUE TITLE
Draw multiline labels on sequence diagram above the arrow

### ISSUE THREAD

**Issue by sandersaares** [mermaid-js/mermaid#1329]
**Is your feature request related to a problem? Please describe.**
When I create multiline sequence diagram labels on the arrows, they overlap the arrow which looks ugly.

**Describe the solution you'd like**
It would look better if they were above the arrow in their entirety.

**Describe alternatives you've considered**
N/A

**Additional context**
Example:

![mstsc_kdQZcbi00w](https://user-images.githubusercontent.com/9914262/78097535-39a45f00-73e5-11ea-8fd0-53d34952d0ef.png)

```
sequenceDiagram
  participant A
  participant B
  
  A->>B: Lorem ipsum dolor sit amet, consectetur<br/>adipiscing elit. Fusce consectetur.
```

**Comment by GDFaber** [comment]
Hi @sandersaares, in mermaid 8.5.1 this was changed and  the text now appears above the arrow. Here is your example in the 8.5.1 [live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gIHBhcnRpY2lwYW50IEFcbiAgcGFydGljaXBhbnQgQlxuICBcbiAgQS0-PkI6IExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1cjxici8-YWRpcGlzY2luZyBlbGl0LiBGdXNjZSBjb25zZWN0ZXR1ci4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ).

Can you confirm it works in your environment? If so, I think we can close the issue.

**Comment by sandersaares** [comment]
Yep looks fixed! Thanks
