### ISSUE TITLE
Fill gaps in gantt diagram documentation

### ISSUE THREAD

**Issue by GDFaber** [mermaid-js/mermaid#1337]
The documentation for gantt diagrams has some sections which are marked "to be done". The missing parts should be added to the docs.

I also added styling/hiding the "today line" by adding `todayMarker` to the gantt definition in #1336. This feature is also undocumented at the moment and should be added here as well.

**Comment by CollierCZ** [comment]
I can give this a try.

**Comment by GDFaber** [comment]
Hi @CollierCZ, that's great. Our contribution guide can be found [here](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md). Please feel free to ask if you need additional information.
