### ISSUE TITLE
Mindmap support

### ISSUE THREAD

**Issue by slipb** [mermaid-js/mermaid#1339]
**Is your feature request related to a problem? Please describe.**
I would be very appreciative if we could have mindmap support.

**Describe the solution you'd like**
https://plantuml.com/en/mindmap-diagram
I think currently Plantuml did a very good example.

**Describe alternatives you've considered**
We could just enhance the features from the flowchart:

current tree:
A --> B
A --> C
A --> D

Enhanced:
A -->B
    **C
    **B
so we don't need to keep type"A" if ist comes from the same node.

**Comment by AnatolyKulakov** [comment]
It would be great!
See also "Mind maps?" (#448) discussion.

**Comment by knsv** [comment]
You have a syntax for avoiding tying A all the time. Perhaps not so for for mindmaps though.
```
  a --> b & c & d
```

I would rather have something like this:
A {
   B
   C
   D
}

But maybe thats is too developer centric?

**Comment by jgreywolf** [comment]
Closing this in favor of #448 , as there is a lot of discussion in that thread on potential syntax
