### ISSUE TITLE
Add maxTextSize in the documentation.

### ISSUE THREAD

**Issue by MarkOdey** [mermaid-js/mermaid#1341]
**Is your feature request related to a problem? Please describe.**
Hey guys, I spent a while figuring out this maxTextSize limit. I even went beyond the evident and tried cloning the repo so I could modify the maxTextSize limit.

Then I realized that I simply had to override the value in the config object when initializing the mermaid api.

**Describe the solution you'd like**
Add the maxTextSize in the documentation along clear reason why it exists.

**Describe alternatives you've considered**
I don't think there are better alternative since its already possible to override this value.

**Additional context**

Seems this issue was related to my situation : https://gitlab.com/gitlab-org/gitlab-foss/-/issues/58603

**Comment by Akiyamka** [comment]
Agree, in must be in docs.
@MarkOdey can you describe how you change this setting in config?
