### ISSUE TITLE
State diagram : having a space in the state name

### ISSUE THREAD

**Issue by sharkx** [mermaid-js/mermaid#1342]
This is a great library. Thank you for making it available.

The question I have is fairly simple : how to add a space in the state name for the state diagram.

Here's what I've tried, and none gives a proper result :

1, for every state add a line for the 'label' like : <state> : some long text
Kinda works, but it sets the text as title for the state with an empty area below

2. replace all spaces (and other specials) by their escaped counterpart; for example <space> with #32;
Also works, but creates very large nodes; I'm guessing the node width is calculated on the length of the input string, not the actual string.
I'm also thinking that this must be the easiest to fix.

Any help is appreciated.
Thank you.

**Comment by Kochise** [comment]
Yswsii: Your state with spaces in it
[*] --> Yswsii

**Comment by aleneum** [comment]
Hi @Kochise,

> Yswsii: Your state with spaces in it
  [*] --> Yswsii

I think this is what @sharkx referes to with

> 1, for every state add a line for the 'label' like : : some long text
Kinda works, but it sets the text as title for the state with an empty area below

The "empty area below" is probably the added horizontal line and the empty space in the node which you can see here:

![mermaid-diagram-20201112122725](https://user-images.githubusercontent.com/205986/98934768-dcc46780-24e2-11eb-9067-c454adbc5b56.png)

Compare this to a state without a separate label:

![Screenshot 2020-11-12 123138a](https://user-images.githubusercontent.com/205986/98934896-08475200-24e3-11eb-8398-512f35d6ab02.png)

**Comment by Kochise** [comment]
Yeah, ok, now I get it (a picture, 1000 words, ...)

I don't know, I've got the same issue, I used this as a fallback until a proper solution is found.
