### ISSUE TITLE
Subroutine flow chart symbol question

### ISSUE THREAD

**Issue by jdavis61** [mermaid-js/mermaid#1343]
Does mermaid.js have a subroutine flow chart symbol, aka one that displays like the example at https://www.smartdraw.com/flowchart/flowchart-symbols.htm? 

If no, would someone please provide a link on how to create a new symbol?

Thanks in advance,

Sincerely,

James Davis

**Comment by jdavis61** [comment]
Answer to my question no.

https://mermaid-js.github.io/mermaid/#/development?id=how-to-add-a-new-diagram-type to create a new diagram type!

**Comment by GDFaber** [comment]
Hi @jdavis61, you are right, there is no subroutine node shape in mermaid's flowchart implementation at the moment. But we should be able to add one for a future release. I'm reopening the issue for this purpose.
