### ISSUE TITLE
Decide Class Diagram orientation

### ISSUE THREAD

**Issue by henri9813** [mermaid-js/mermaid#1344]
Hello,

I would have the possibility to decide the diagram orientation

Here is my current Mermaid diagram:
```mermaid
classDiagram
class A {
  int id
  String name
}

class B {
  int id
  String name
}

class C {
  int id
  String name
}

A "1" --> "*" B
B "1" --> "*" C
```

Currently, it is TOP to bottom, how can i have a Left to Right diagram ? 

Thanks

**Comment by Chaoses-Ib** [comment]
I don't know when it was supported, but now you just need to add `direction LR`:
```mermaid
classDiagram
direction LR
class A {
  int id
  String name
}

class B {
  int id
  String name
}

class C {
  int id
  String name
}

A "1" --> "*" B
B "1" --> "*" C
```

**Comment by jgreywolf** [comment]
Closing as this was resolved

**Comment by 1chooo** [comment]
Hi @Chaoses-Ib 

How do I arrange this with the above example in horizontal?

```mermaid
---
title: p05 by Hugo
---
classDiagram
    direction LR
    class Movie {
        int priceCode
    }

    class Rental {
        int daysRented
    }

    class Customer {
        statement()
    }

    Movie "1" <-- "*" Rental
    Customer "1" <-- "*" Rental
```

````md
```mermaid
---
title: p05 by Hugo
---
classDiagram
    direction LR
    class Movie {
        int priceCode
    }

    class Rental {
        int daysRented
    }

    class Customer {
        statement()
    }

    Movie "1" <-- "*" Rental
    Customer "1" <-- "*" Rental
```
````

**Comment by 1chooo** [comment]
> Hi @Chaoses-Ib
> 
> How do I arrange this with the above example in horizontal?
> 
> ```mermaid
> ---
> title: p05 by Hugo
> ---
> classDiagram
>     direction LR
>     class Movie {
>         int priceCode
>     }
> 
>     class Rental {
>         int daysRented
>     }
> 
>     class Customer {
>         statement()
>     }
> 
>     Movie "1" <-- "*" Rental
>     Customer "1" --> "*" Rental
> ```
> ```
> ```mermaid
> ---
> title: p05 by Hugo
> ---
> classDiagram
>     direction LR
>     class Movie {
>         int priceCode
>     }
> 
>     class Rental {
>         int daysRented
>     }
> 
>     class Customer {
>         statement()
>     }
> 
>     Movie "1" <-- "*" Rental
>     Customer "1" --> "*" Rental
> ```
> ```

Solved:

```mermaid
---
title: p05 by Hugo
---
classDiagram
    direction LR
    class Movie {
        int priceCode
    }

    class Rental {
        int daysRented
    }

    class Customer {
        statement()
    }

    Customer "1" --> "*" Rental
    Rental "*" --> "1" Movie
```

````md
```mermaid
---
title: p05 by Hugo
---
classDiagram
    direction LR
    class Movie {
        int priceCode
    }

    class Rental {
        int daysRented
    }

    class Customer {
        statement()
    }

    Customer "1" --> "*" Rental
    Rental "*" --> "1" Movie
```
````
