### ISSUE TITLE
Regarding NOT able to increase graph size/width in mermaid is in Grafana.

### ISSUE THREAD

**Issue by RavinderSingh191** [mermaid-js/mermaid#1347]
Hello All,

Greetings!!

I have prepared an architecture diagram layer by layer for our environment servers in Grafana software using graph module.

Its going well and loved the way mermaid works, really awesome. I got stuck into an issue after googling also not able to find this hence posting it here.

Since diagram is big with many servers my graph is getting too smaller, with box size as well as font size. It's getting weired now since we can see status(Thanks to Grafana's color system green or red) but it's not looking good.

Would like to request you if experts could guide me how to deal with this case, I apologise I can't add screen shot of it because it's in my official pc.

Any guidance, help will be greatly appreciated here.

Thanks,
Ravinder

**Comment by cbryant42** [comment]
I am having similar issues. Would love if someone could help.

**Comment by sidharthv96** [comment]
The solution would be in Grafana (or the plugin) to add zoom support for SVG like we have added in live editor, and GitHub has added in their implementation of mermaid. 

```mermaid
flowchart TD
    A[Start] --> B{Is it?}
    B -- Yes --> C[OK]
    C --> D[Rethink]
    D --> B
    B -- No ----> E[End]
```

Out of scope for mermaid project.
