### ISSUE TITLE
Class Diagrams unnecessary wide and with white space to the left and right

### ISSUE THREAD

**Issue by ismarslomic** [mermaid-js/mermaid#1349]
**Describe the bug**
Class diagrams in MermaidJS v8.4.8 and 8.5.0 are unnecessary wide and leaves white space to the left and right of diagram nodes, which force user to scroll unnecessarily. 

**To Reproduce**
1. Go to Mermaid Live Editor [example](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5DbGFzc0EgLi4-IFwiMVwiIENsYXNzQiA6IGZvb1xuQ2xhc3NBIC4uPiBcIjAuLjFcIiBDbGFzc0MgOiBmb29cbkNsYXNzQSAuLj4gXCIwLi4xXCIgQ2xhc3NDIDogZm9vXG5DbGFzc0EgLi4-IFwiMC4uMVwiIENsYXNzRCA6IGZvb1xuY2xhc3MgQ2xhc3NBe1xuICAgIDw8bXkgYW5ub3RhdGlvbiA-PlxuICAgIHN0cmluZ1sxXSBBdHRyQVxuICAgIHN0cmluZ1sxXSBBdHRyQlxuICAgIHN0cmluZ1sxXSBBdHRyQ1xuICAgIHN0cmluZ1sxXSBBdHRyRFxuICAgIHN0cmluZ1sxXSBBdHRyRVxuICAgIHN0cmluZ1sxXSBBdHRyRlxuICAgIGludFsxXSBBdHRyR1xuICAgIC0tIEVudGl0eUF0dHJGIC0tXG4gICAgc3RyaW5nWzFdIEF0dHJIXG59XG5cbkNsYXNzRSAuLj4gXCIxXCIgQ2xhc3NGIDogZm9vXG5DbGFzc0UgLi4-IFwiMC4uMVwiIENsYXNzRyA6IGJhclxuQ2xhc3NFIC4uPiBcIjAuLjFcIiBDbGFzc0MgOiBkYWFyXG5jbGFzcyBDbGFzc0V7XG4gICAgPDxteSBhbm5vdGF0aW9uID4-XG4gICAgc3RyaW5nWzFdIEF0dHJBXG4gICAgc3RyaW5nWzFdIEF0dHJCXG4gICAgc3RyaW5nWzFdIEF0dHJDXG4gICAgc3RyaW5nWzFdIEF0dHJEXG4gICAgc3RyaW5nWzFdIEF0dHJFXG4gICAgc3RyaW5nWzFdIEF0dHJGXG4gICAgaW50WzFdIEF0dHJHXG4gICAgLS0gRW50aXR5QXR0ckYgLS1cbiAgICBzdHJpbmdbMV0gQXR0cmhcbn1cblxuY2xhc3MgQ2xhc3NGe1xuICAgIDw8IG15IGFubm90YXRpb24-PlxuICAgIEFCQ1xuICAgIENERVxufVxuXG5jbGFzcyBDbGFzc0d7XG4gICAgPDwgbXkgYW5ub3RhdGlvbj4-XG4gICAgQUJDXG4gICAgQ0RFXG4gICAgRUZHXG4gICAgR0hJXG59XG5cbkNsYXNzQyAtLT4gQ2xhc3NNVHlwZSA6IGZvb1xuQ2xhc3NDIC4uPiBcIjFcIiBDbGFzc0EgOiBmb29cbkNsYXNzQyAuLj4gXCIwLi4xXCIgQ2xhc3NCIDogZm9vXG5DbGFzc0MgLi4-IFwiMVwiIENsYXNzTSA6IGZvb1xuQ2xhc3NDIC4uPiBcIjFcIiBDbGFzc0QgOiBmb29cbkNsYXNzQyAuLj4gXCIwLi4xXCIgQ2xhc3NMIDogZm9vXG5DbGFzc0MgLi4-IFwiMC4uMVwiIENsYXNzTCA6IGZvb1xuQ2xhc3NDIC4uPiBcIjAuLjFcIiBDbGFzc0MgOiBmb29cbkNsYXNzQyAuLj4gXCIwLi4xXCIgQ2xhc3NDIDogZm9vXG5jbGFzcyBDbGFzc0N7XG4gICAgPDxteSBhbm5vdGF0aW9uID4-XG4gICAgc3RyaW5nWzFdIEF0dHJBXG4gICAgc3RyaW5nWzFdIEF0dHJCXG4gICAgc3RyaW5nWzFdIEF0dHJDXG4gICAgc3RyaW5nWzFdIEF0dHJEXG4gICAgc3RyaW5nWzFdIEF0dHJFXG4gICAgc3RyaW5nWzFdIEF0dHJGXG4gICAgaW50WzFdIEF0dHJHXG4gICAgLS0gRW50aXR5QXR0ckYgLS1cbiAgICBzdHJpbmdbMV0gQXR0ckhcbiAgICBib29sZWFuWzFdIEF0dHJJXG4gICAgYm9vbGVhblsxXSBBdHRySlxuICAgIGludFswLi4xXSBBdHRyS1xufVxuXG5jbGFzcyBDbGFzc01UeXBle1xuICAgIDw8IG15IGFubm90YXRpb24-PlxuICAgIEFCQ1xuICAgIENERVxufVxuXG5BY3R1YWxDbGFzc01TdGF0dXNWMSAuLj4gXCIxXCIgQ2xhc3NIIDogZm9vXG5BY3R1YWxDbGFzc01TdGF0dXNWMSAuLj4gXCIwLi4xXCIgQ2xhc3NJIDogZm9vXG5BY3R1YWxDbGFzc01TdGF0dXNWMSAuLj4gXCIwLi4xXCIgQ2xhc3NDIDogZm9vXG5BY3R1YWxDbGFzc01TdGF0dXNWMSAuLj4gXCIwLi4xXCIgQ2xhc3NMIDogZm9vXG5BY3R1YWxDbGFzc01TdGF0dXNWMSAuLj4gXCIwLi4xXCIgQ2xhc3NMIDogZm9vXG5BY3R1YWxDbGFzc01TdGF0dXNWMSAuLj4gXCIwLi4xXCIgQ2xhc3NMIDogZm9vXG5BY3R1YWxDbGFzc01TdGF0dXNWMSAuLj4gXCIwLi4xXCIgQ2xhc3NKIDogZm9vXG5jbGFzcyBBY3R1YWxDbGFzc01TdGF0dXNWMXtcbiAgICA8PG15IGFubm90YXRpb24gPj5cbiAgICBzdHJpbmdbMV0gQXR0ckFcbiAgICBzdHJpbmdbMV0gQXR0ckJcbiAgICBzdHJpbmdbMV0gQXR0ckNcbiAgICBzdHJpbmdbMV0gQXR0ckRcbiAgICBzdHJpbmdbMV0gQXR0ckVcbiAgICBzdHJpbmdbMV0gQXR0ckZcbiAgICBpbnRbMV0gQXR0ckdcbiAgICAtLSBFbnRpdHlBdHRyRiAtLVxuICAgIHN0cmluZ1sxXSBBdHRySFxufVxuXG5jbGFzcyBDbGFzc0h7XG4gICAgPDwgbXkgYW5ub3RhdGlvbj4-XG4gICAgQUJDXG4gICAgQ0RFXG4gICAgRUZHXG59XG5cbmNsYXNzIENsYXNzSXtcbiAgICA8PCBteSBhbm5vdGF0aW9uPj5cbiAgICBBQkNcbiAgICBDREVcbiAgICBFRkdcbiAgICBHSElcbiAgICBJSktcbn1cblxuQ2xhc3NKIC4uPiBcIjFcIiBDbGFzc0sgOiBDbGFzc0tcbmNsYXNzIENsYXNzSntcbiAgICA8PCBteSBhbm5vdGF0aW9uPj5cbiAgICBpbnRbMV0gQXR0ckFcbiAgICBzdHJpbmdbMC4uMV0gQXR0ckJcbn1cblxuY2xhc3MgQ2xhc3NLe1xuICAgIDw8IG15IGFubm90YXRpb24-PlxuICAgIEFCQ1xuICAgIENERVxuICAgIEVGR1xuICAgIEdISVxufVxuXG5DbGFzc0wgLi4-IFwiMVwiIENsYXNzRCA6IGZvb1xuQ2xhc3NMIC4uPiBcIjAuLjFcIiBDbGFzc0IgOiBmb29cbkNsYXNzTCAuLj4gXCIwLi4xXCIgQ2xhc3NNIDogZm9vXG5DbGFzc0wgLi4-IFwiMC4uMVwiIENsYXNzTiA6IGZvb1xuQ2xhc3NMIC4uPiBcIjAuLjFcIiBDbGFzc0MgOiBmb29cbkNsYXNzTCAuLj4gXCIwLi4xXCIgQ2xhc3NBIDogZm9vXG5DbGFzc0wgLi4-IFwiMC4uMVwiIENsYXNzTCA6IGZvb1xuQ2xhc3NMIC4uPiBcIjAuLjFcIiBDbGFzc0wgOiBmb29cbmNsYXNzIENsYXNzTHtcbiAgICA8PG15IGFubm90YXRpb24gPj5cbiAgICBzdHJpbmdbMV0gQXR0ckFcbiAgICBzdHJpbmdbMV0gQXR0ckJcbiAgICBzdHJpbmdbMV0gQXR0ckNcbiAgICBzdHJpbmdbMV0gQXR0ckRcbiAgICBzdHJpbmdbMV0gQXR0ckVcbiAgICBzdHJpbmdbMV0gQXR0ckZcbiAgICBpbnRbMV0gQXR0ckdcbiAgICAtLSBFbnRpdHlBdHRyRiAtLVxuICAgIHN0cmluZ1sxXSBBdHRySFxuICAgIGludFswLi4xXSBBdHRySVxufVxuXG5jbGFzcyBDbGFzc0R7XG4gICAgPDxteSBhbm5vdGF0aW9uID4-XG59XG5cbmNsYXNzIENsYXNzQntcbiAgICA8PCBteSBhbm5vdGF0aW9uPj5cbn1cblxuY2xhc3MgQ2xhc3NNe1xuICAgIDw8IG15IGFubm90YXRpb24-PlxufVxuXG5jbGFzcyBDYWxsWHtcbiAgICA8PCBteSBhbm5vdGF0aW9uPj5cbn1cblxuY2xhc3MgQ2xhc3NOe1xuICAgIDw8IG15IGFubm90YXRpb24-PlxufSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)
2. Note the white space to the left and to the right of the diagram nodes

**Expected behavior**
Unnecessary white space to the left and right of diagram shall not be there

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Firefox
 - Version: 75.0

**Additional context**
It seems that commit [cda67f8b4454b7448ca75d62c82b2f](https://github.com/jgreywolf/mermaid/commit/f8f52c4587cda67f8b4454b7448ca75d62c82b2f) introduced multiplying the diagram width by 1.5.

**Comment by jgreywolf** [comment]
Yes, This was done to correct an issue where diagrams were being cut off.  I am still working on a better method for this, and hope to have something within a couple of weeks

**Comment by jgreywolf** [comment]
Closing as this is being addressed via #1234
