### ISSUE TITLE
How to make the arrow not change the chart?

### ISSUE THREAD

**Issue by nik0145** [mermaid-js/mermaid#1358]
How do I make that the arrow doesn't change the position of blocks relative to the graph ?
like this:
![4cXgajD](https://user-images.githubusercontent.com/23018061/79565840-27e7da80-80ba-11ea-841c-9859b919725a.png)
But, I got it:
![image1](https://user-images.githubusercontent.com/23018061/79565937-55cd1f00-80ba-11ea-8aa2-3d81136070f3.png)

[Example](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbjVlNGFiODJkYTA0Y2E4NzJhN2VkOTZmMCjQn9GA0LjRkdC8INC30LDQutCw0LfQsCktLT41ZGNkMTI1M2U0YTY2ZjRjOWFhOGExYjIo0JrQvtC90LLQtdC50LXRgCwg0LzQvtC50LrQsCwg0L7RhdC70LDQttC00LXQvdC40LUpXG41ZGNkMTI1M2U0YTY2ZjRjOWFhOGExYjIo0JrQvtC90LLQtdC50LXRgCwg0LzQvtC50LrQsCwg0L7RhdC70LDQttC00LXQvdC40LUpLS0-NWRjZDEyNmZlNGE2NmY0YzlhYThhMWI1KNCh0L7RgNGC0LjRgNC-0LLQutCwKVxuNWRjZDEyNmZlNGE2NmY0YzlhYThhMWI1KNCh0L7RgNGC0LjRgNC-0LLQutCwKS0tPjVkY2QyZjFjMDhlNmY4MWY1NTk4MmRiMSjQntGF0LvQsNC20LTQtdC90LjQtSlcbjVkY2QyZjFjMDhlNmY4MWY1NTk4MmRiMSjQntGF0LvQsNC20LTQtdC90LjQtSktLT41ZGNkMmYyYzA4ZTZmODFmNTU5ODJkYjIo0J3QsNGA0LXQt9C60LApXG41ZGNkMmYyYzA4ZTZmODFmNTU5ODJkYjIo0J3QsNGA0LXQt9C60LApLS0-NWRjZDJmMzYwOGU2ZjgxZjU1OTgyZGIzKNCk0LDRgdC-0LLQutCwKVxuNWRkYjlhNDc0YzFhMTIyMDEwNjU5YWVjKNCd0LDRgNC10LfQutCwINCy0YDRg9GH0L3Rg9GOKS0tPjVkY2QyZjM2MDhlNmY4MWY1NTk4MmRiMyjQpNCw0YHQvtCy0LrQsClcbjVkY2QyZjM2MDhlNmY4MWY1NTk4MmRiMyjQpNCw0YHQvtCy0LrQsCktLT41ZGNkMmY0ZDA4ZTZmODFmNTU5ODJkYjQo0K3QutGB0L_QtdC00LjRhtC40Y8pXG41ZGNkMmY0ZDA4ZTZmODFmNTU5ODJkYjQo0K3QutGB0L_QtdC00LjRhtC40Y8pLS0-NWRjZDJmNjUwOGU2ZjgxZjU1OTgyZGI1KNCe0YLQs9GA0YPQt9C60LApXG41ZGRiYTFmMjAxMWEzMjcyNmNiZWFjOWYo0J_RgNC-0LLQtdGA0LrQsCA2KS0tPjVkY2QyZjY1MDhlNmY4MWY1NTk4MmRiNSjQntGC0LPRgNGD0LfQutCwKVxuNWRjZDJmNjUwOGU2ZjgxZjU1OTgyZGI1KNCe0YLQs9GA0YPQt9C60LApLS0-NWRjZDM3ZjM5MDJmNWUyNmE4NDk5MjlkKNCf0L7RgtGA0LXQsdC40YLQtdC70YwpXG41ZGNkMmYxYzA4ZTZmODFmNTU5ODJkYjEo0J7RhdC70LDQttC00LXQvdC40LUpLS0-NWRkYjlhNDc0YzFhMTIyMDEwNjU5YWVjKNCd0LDRgNC10LfQutCwINCy0YDRg9GH0L3Rg9GOKVxuNWRjZDEyNTNlNGE2NmY0YzlhYThhMWIyKNCa0L7QvdCy0LXQudC10YAsINC80L7QudC60LAsINC-0YXQu9Cw0LbQtNC10L3QuNC1KS0tPjVkZGI5YTZiNGMxYTEyMjAxMDY1OWFlZCjQntC_0LXRgNCw0YbQuNGPIDEpXG41ZGRiOWE2YjRjMWExMjIwMTA2NTlhZWQo0J7Qv9C10YDQsNGG0LjRjyAxKS0tPjVkZGI5Yjg4NGMxYTEyMjAxMDY1OWFlZSjQodC60LvQsNC00LjRgNC-0LLQsNC90LjQtSlcbjVkZGI5Yjg4NGMxYTEyMjAxMDY1OWFlZSjQodC60LvQsNC00LjRgNC-0LLQsNC90LjQtSktLT41ZGRiOWVmZTRjMWExMjIwMTA2NTlhZjAo0J_RgNC-0LLQtdGA0LrQsCA1KVxuNWRkYjllZmU0YzFhMTIyMDEwNjU5YWYwKNCf0YDQvtCy0LXRgNC60LAgNSktLT41ZGRiYTFmMjAxMWEzMjcyNmNiZWFjOWYo0J_RgNC-0LLQtdGA0LrQsCA2KVxuNWRjZDJmMmMwOGU2ZjgxZjU1OTgyZGIyKNCd0LDRgNC10LfQutCwKS0u0KPQstC10LTQvtC80LvQtdC90LjQtSDQviDQs9C-0YLQvtCy0L3QvtGB0YLQuC4tPjVkY2QxMjZmZTRhNjZmNGM5YWE4YTFiNSjQodC-0YDRgtC40YDQvtCy0LrQsClcblxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)
(the last line is the problem arrow)

**Comment by jgreywolf** [comment]
@nik0145 It isnt currently possible to specifically control the lines between nodes.  This is a limitation from dagre3d which handles the rendering

**Comment by nik0145** [comment]
Thank you for the answer
