### ISSUE TITLE
Sample code about styling a node

### ISSUE THREAD

**Issue by wangpin34** [mermaid-js/mermaid#1366]
**Describe the bug**
The sample code about stying a node on [this page](https://mermaid-js.github.io/mermaid/#/flowchart?id=styling-and-classes) does not work as expected.

```mermaid
graph LR
    id1(Start)-->id2(Stop)
    style id1 fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff,stroke-dasharray: 5, 5
```

The above code intends to give a stroke-dasharray to **id2** but the value isn't valid. Check below screen of rendered style details of the  **id2**  which says the second **5** was rendered as a style property not a value. 

![image](https://user-images.githubusercontent.com/12655367/80064304-55c19900-856a-11ea-8199-b6e6ef9eb0b3.png)

Accord to [this doc](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray), the value format of dash array should be a list of number, like **5 5**, which is separated by space or comma.  Since comma here is used as the separator of  style properties. I think the space is the only choice. So the fixed version of the sample code will be:

```mermaid
graph LR
    id1(Start)-->id2(Stop)
    style id1 fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
```

Hope this report could help to improve the doc. 

**To Reproduce**
N/A

**Expected behavior**
N/A
**Screenshots**
![image](https://user-images.githubusercontent.com/12655367/80064304-55c19900-856a-11ea-8199-b6e6ef9eb0b3.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome
 - Version:  81.0.4044.113

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by GDFaber** [comment]
Hi @wangpin34, thank you for reporting this. We should remove the comma for the example code to work properly.
