### ISSUE TITLE
it error after use the gulp-htmlclean

### ISSUE THREAD

**Issue by jerryc127** [mermaid-js/mermaid#1369]
## Help us help you!
You want an answer. Here are some ways to get it quicker:
* Use a clear and concise title.
* Try to pose a clear and concise question.
* Include as much, or as little, code as necessary.
* Don't be shy to give us some screenshots, if it helps!

it error after use the gulp-htmlclean.

![image](https://user-images.githubusercontent.com/16351105/80110302-1c604c00-85b1-11ea-8d6d-d24b4d9d3ae6.png)

https://demo.jerryc.me/posts/2df239ce/#mermaid

**Comment by jgreywolf** [comment]
@jerryc127 Can you please provide more detail as to what your question is?

**Comment by jerryc127** [comment]
Thx for reply.

I write in the markdown

```
pie
    title Key elements in Product X
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5
```

and the theme will generate to html 

```

<div class="mermaid">
pie
  title Key elements in Product X
  &quot;Calcium&quot; : 42.96
  &quot;Potassium&quot; : 50.05
  &quot;Magnesium&quot; : 10.01
  &quot;Iron&quot; :  5</div>
```

when i use some tools to minify html, such as gulp-htmlclean

it will be minify like this

```
<div class="mermaid">pie title Key elements in Product X &quot;Calcium&quot; : 42.96 &quot;Potassium&quot; : 50.05 &quot;Magnesium&quot; : 10.01 &quot;Iron&quot; : 5</div>
```

the website show that
![image](https://user-images.githubusercontent.com/16351105/106563876-6e35f980-6567-11eb-992d-1484689a3c5a.png)

**Comment by jgreywolf** [comment]
This seems to be an issue in how it is minified, since the parser is expecting line breaks between statements

**Comment by sidharthv96** [comment]
Not an issue with mermaid. Please skip minifying `pre` blocks.
