### ISSUE TITLE
sub/superscript in mermaid

### ISSUE THREAD

**Issue by sommmen** [mermaid-js/mermaid#1376]
Hello,

Could i add a sub or superscript to mermaid node?

e.g. 

> Request(myDto<sup>1</sup>)

id like to annotate some text so i can reference it outside the diagram:
> <sup>1</sup> the dto should atleast have a valid id

**Comment by vantoan8x** [comment]
Hi Sommmem!

Let adjust config by adding record:
"htmlLabels": true,

ex:
```
{
   "theme": "default",
    "htmlLabels": true,
    "securityLevel": "loose",
}
```


then in the script; ket use html format <sub></sub> or <sup></sup> to make sub/sup content style.

ex
```
graph LR
A1[("192.168.1.1 <sup>up</sup> <sub>down</sub>")]
```

**Comment by sommmen** [comment]
> Hi Sommmem!
> 
> Let adjust config by adding record:
> "htmlLabels": true,
> "securityLevel": "loose",
> 
> ex:
> 
> ```
> {
>    "theme": "default",
>     "htmlLabels": true,
>     "securityLevel": "loose",
> }
> ```
> 
> then in the script; ket use html format or to make sub/sup content style.
> 
> ex
> 
> ```
> graph LR
> NodeIdName[("It work <sup>up</sup> <sub>down</sub>")]
> ```

Hello and thanks for answering.

This is a great suggestion which should help others. Unfortunately I don't think it will help me. I use mermaid in the [DevOps wiki](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-create-repo?view=azure-devops&tabs=browser) so I don't think i can edit any configuration.

**Comment by vantoan8x** [comment]
ask them to update config just disable script element only, link element disable. other html element should approved to display!

I will help to make pull request for this today with new security level.

**Comment by vantoan8x** [comment]
as promised, the pull request here:
https://github.com/mermaid-js/mermaid/pull/1471

or this on my branch:
https://github.com/vantoan8x/mermaid/tree/securityLevel_antiscript_option

or this commit is:
https://github.com/vantoan8x/mermaid/commit/308498f11b059f527d54b14498307d9318d4aaa9

Regards.

**Comment by GDFaber** [comment]
Hi @vantoan8x, this is much appreciated, see my comments in the PR entry.

**Comment by michaelgreyskull** [comment]
Hi van Toan!

can you please tell me, where I need to make these settings?

> ```
> {
>    "theme": "default",
>     "htmlLabels": true,
>     "securityLevel": "loose",
> }
> ```

This maybe a really stupid question, my apologies!
After hours of trying to insert sub- or sup-chars in a sequence diagram, I am finally happy to find a solution. Thank you!

**Comment by vantoan8x** [comment]
@michaelgreyskull,
Look at: https://mermaid-js.github.io/mermaid/#/usage?id=api-usage

example:

```
mermaidAPI.initialize({
       securityLevel: 'loose'
});
```

**Comment by michaelgreyskull** [comment]
> @michaelgreyskull,
> Look at: https://mermaid-js.github.io/mermaid/#/usage?id=api-usage

Thank you, @vantoan8x !
I found it and it seems to work for most graphs, but not for sequence diagrams. :\
