### ISSUE TITLE
Shortcut for deactivation throws syntax error on initially activated participant.

### ISSUE THREAD

**Issue by samurous** [mermaid-js/mermaid#1380]
**To Reproduce**
[This](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gIGFjdGl2YXRlIEJvYlxuXHRBbGljZS0-PkJvYjogU3RvcCwgQm9iIVxuICBkZWFjdGl2YXRlIEJvYiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19) works:
```
sequenceDiagram
  activate Bob
	Alice->>Bob: Stop, Bob!
  deactivate Bob
```
The [short version](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gIGFjdGl2YXRlIEJvYlxuXHRBbGljZS0-Pi1Cb2I6IFN0b3AsIEJvYiEiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ) does not:
```
sequenceDiagram
  activate Bob
	Alice->>-Bob: Stop, Bob!
```
Throws the error:
> Trying to inactivate an inactive participant (Alice)

**Expected behavior**
Both versions should render to.
![grafik](https://user-images.githubusercontent.com/28673531/80733562-2a145500-8b0e-11ea-8206-dcb373721b7c.png)

**Context:**
 - Version [8.5.0]

**Comment by jgreywolf** [comment]
Resolution to this issue can be found in issue #2168
