### ISSUE TITLE
Remove lodash from mermaid in order to reduce bundle size

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#1389]
lodash is hardly used in mermaid. This functions that are being used could and should be replaced with specific implementations thus reducing the bundle size significantly.

Relates to #1385

**Comment by hikerpig** [comment]
I would like to take a try.

I see most specific implementations can be confined in [gitGraphAst.js](https://github.com/mermaid-js/mermaid/blob/master/src/diagrams/git/gitGraphAst.js).

A quick tweak, can be done today.
