### ISSUE TITLE
Smarter use of d3 in order to utilize tree shaking in webpack

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#1390]
Currently 80% of the bundle size is made up of lodash and d3. lodash is easy to remove (#1389), we should do that, d3 not so easy. But we can minimize d3 use by removing statements like this

```
import * as d3 from 'd3';
```

With better imports webpack don't need to pull in all of d3 into the bundle and significantly reduce the bundle size.

relates to #1385

**Comment by spopida** [comment]
I'll sort out the imports, but I don't have sufficient webpack knowledge to configure / prove optimal tree shaking.
