### ISSUE TITLE
When there are two kind of relationship between two classes

### ISSUE THREAD

**Issue by swithun-liu** [mermaid-js/mermaid#1391]
I want to describe the relationships like this
![image](https://user-images.githubusercontent.com/42160297/81256425-0cda0c00-9063-11ea-8ce0-80194b4d0bbe.png)

so I write 
![image](https://user-images.githubusercontent.com/42160297/81256454-23806300-9063-11ea-8995-d9efcb827993.png)

the  new relationship `--o` will cover the former relationship `<|--` , 
only the latter relationship will be displayed

**Comment by jgreywolf** [comment]
I believe that OP is referring to a setup like this: 

> classDiagram
class A
class B
B <|-- A
A --o B

[Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBBXG5jbGFzcyBCXG5CIDx8LS0gQVxuQSAtLW8gQlxuXHRcdFx0XHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

With the caveat that the second relation is displayed like in the image
