### ISSUE TITLE
The second Gantt example is broken when pasted into the Mermaid Live Editor

### ISSUE THREAD

**Issue by jwatt** [mermaid-js/mermaid#1393]
The second Gantt example is broken when pasted into the Mermaid Live Editor.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 76

**Comment by jwatt** [comment]
More specifically it looks like there shouldn't be a colon used for the `dateFormat`, `title` and `excludes` lines, and that the `excludes` line should really contain just one value and the remaining text and the parenthetical on the following line should be comment lines.

**Comment by sidharthv96** [comment]
Current examples seem to be working properly. 
Please reopen with a live editor link if issue persists. Thanks!
