### ISSUE TITLE
8.5.0 dist/mermaid.js minified

### ISSUE THREAD

**Issue by jackthomasatl** [mermaid-js/mermaid#1394]
In build 8.5.0, the mermaid.js file is minified.

This is caused by the -p flag being set on the webpack call.

**Comment by jackthomasatl** [comment]
Any update on this?

**Comment by GDFaber** [comment]
We'll change it back to normal for mermaid 8.5.2 as 8.5.1 is already out.

**Comment by jackthomasatl** [comment]
Sweet, Thank you
