### ISSUE TITLE
Angular 9 : Mermaid dependencies issue can't resolve crypto

### ISSUE THREAD

**Issue by sudhakar-sekar** [mermaid-js/mermaid#1398]
Hi,
and I cannot compile the project, I got the below error,

> ERROR in ./node_modules/crypto-random-string/index.js
Module not found: Error: Can't resolve 'crypto' in 'my-app\node_modules\crypto-random-string

I am upgrading my angular application from v8 to v9.
Am getting error while compiling in angular application, "Module Not Found : can't resolve 'crypto' in node-modules/crypto-random-string" on angular V9 only.
In angular v8 works fine, after upgrade only this issue am facing.
When am installing mermaid that time only, I am facing these issue. I am using v8.5.0.
If am removing mermaid package, my application works perfect. 

"crypto is a latest Node.Js specific API, but in this case it’s being used in a browser application which is incorrect. One of your dependencies mermaid has a dependency on crypto-random-string. This library is using crypto which does not exist in a browser and as a result is not a browser compatible library."

Node Js : v12.16.3
CLI : v9.1.5.
Typescript: v3.8.3

Anyone help me to resolve this issue ASAP.

Thanks,
Sudhakar Chandrasekaran.

**Comment by knsv** [comment]
I have removed that dependency for size reasons. That might help you as well. Keep an eye out for 8.5.1

**Comment by sudhakar-sekar** [comment]
Thanks @knsv , I will wait for the 8.5.1 npm version release.

**Comment by sudhakar-sekar** [comment]
@knsv the issue was fixed in 8.5.1 Thanks and closing.
