### ISSUE TITLE
Click event in React 

### ISSUE THREAD

**Issue by swetha2** [mermaid-js/mermaid#1402]
Hi @all,
  I am not able to trigger my function on click of node. Can anyone help with this please.

   A-->B
         B-->C
         B-->E
         C-->D
        
         click A callback "Tooltip";

**Comment by lolovassia** [comment]
Could you fix it?

**Comment by shajiya-dev** [comment]
Hi, Did you got any solution @swetha2 ?

**Comment by lolovassia** [comment]
> Hi, Did you got any solution @swetha2 ?

Yes, you need to do:

`
graph TB 
node_1["Question...??"] 
node_1_end_a(["Answer A"]) 
node_1_end_b(["Answer B"])
 
node_1 -->|Yes| node_1_end_a 
node_1 -->|No| node_1_end_b 
 
click node_1 callback
click node_1_end_a callback
click node_1_end_b callback
`

And then:

`
window.callback = async function (e) {
				if (e && e != ''){
					setNodeQuestion(e);
				}
			}
`

**Comment by shajiya-dev** [comment]
Have u used Mermaid API? 
Can we bind the function within react component or do we need to define in window and then we have to do callback. Please help me.

**Comment by lolovassia** [comment]
> Have u used Mermaid API?
> Can we bind the function within react component or do we need to define in window and then we have to do callback. Please help me.

I used Mermaid Api, yes. (npm i mermaid)
I use react with hooks, and I have the following function:

`
import React, { useEffect, useContext, useState } from 'react';
import mermaid from 'mermaid';


export const FlowchartTroubleshooting = (props:any) => {

    const [code, setCode] = useState();
    const [nodeQuestion, setNodeQuestion] = useContext(NodeQuestionProvider); // this is read by a parent component

    const handleParsed = async () =>{
      const codeNew = `
      graph TB
      node_1["Question...??"]
      node_1_end_a(["Answer A"])
      node_1_end_b(["Answer B"])
      
      node_1 -->|Yes| node_1_end_a
      node_1 -->|No| node_1_end_b
      
      click node_1 callback
      click node_1_end_a callback
      click node_1_end_b callback
      `;
      setCode(codeNew);
      document.getElementsByClassName('mermaid')[0].removeAttribute('data-processed');

      var config = {
        startOnLoad:true,
        flowchart:{
            useMaxWidth:true,
            htmlLabels:true,
        },
        securityLevel:'loose',
      };
      
      mermaid.initialize(config);
      
      window.callback = async function (e) {
        if (e && e != ''){
          setNodeQuestion(e);
        }
      }
      mermaid.contentLoaded();	
    }

    return (
      <div>
        {	code &&
          <div className="mermaid">
              { code }
          </div>
        }
      </div>
    );

};
`

**Comment by shajiya-dev** [comment]
Thank you so much, It worked. thanks a lot. 👍
