### ISSUE TITLE
Generic Diagramming

### ISSUE THREAD

**Issue by itdependsnetworks** [mermaid-js/mermaid#1410]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
Looking if there is interest in a generic diagram solution? There is http://go.drawthe.net/ that was formed in that idea, but has lost not been updated in years.

**Describe alternatives you've considered**
The solution from: http://go.drawthe.net/ 

**Additional context**
To further clarify what I mean by generic, is that the developer would have to control all constructs (icon placement on grid, icon choice, metadata, etc..) This works well for the use case of highly repeatable diagrams that have a structured data to show the difference between the many diagrams that are slightly different

**Comment by jgreywolf** [comment]
This is not something that fits the roadmap for mermaid at this time
