### ISSUE TITLE
some fa:icons are not shown

### ISSUE THREAD

**Issue by glomerata** [mermaid-js/mermaid#1412]
**Describe the bug**
While testing the display of fontawesome icons, I have found some of them not shown.

**Steps**
Tested in  https://mermaid-js.github.io/mermaid-live-editor/
source code for flowchart graph with icons:

```
graph TB
top-->ip8([ap ip8])-->ip2([fontawesome icons])
ip2-->n[fa:fa-usb fa:fa-wifi fa:fa-car]
ip2-->v0[fa:fa-arrow-down these are not shown fa:fa-arrow-down]
v0-->v1[network-wired fa:fa-network-wired]
v1-->v2[ethernet fa:fa-ethernet]
v2-->v3[...etc fa:fa-hdd fa:fa-mobile-alt]
```

**Expected behavior**
Some icons to be shown:

- fa:fa-network-wired
- fa:fa-ethernet
- fa:fa-hdd
- fa:fa-mobile-alt

are not visible.

**Comment by richtong** [comment]
Any hope on this one, which icons can be used?

**Comment by matschaffer** [comment]
I don't see any icons on the docs either https://mermaid-js.github.io/mermaid/#/flowchart?id=basic-support-for-fontawesome

And is it expected that any of these would work via github markdown? Seems like they don't at the moment

```mermaid
graph TB
top-->ip8([ap ip8])-->ip2([fontawesome icons])
ip2-->n[fa:fa-usb fa:fa-wifi fa:fa-car]
ip2-->v0[fa:fa-arrow-down these are not shown fa:fa-arrow-down]
v0-->v1[network-wired fa:fa-network-wired]
v1-->v2[ethernet fa:fa-ethernet]
v2-->v3[...etc fa:fa-hdd fa:fa-mobile-alt]
```

@glomerata looks like some of the icons you referenced are working now.

![Screen Shot 2022-03-15 at 13 51 18](https://user-images.githubusercontent.com/690/158308788-b0ece529-f0ad-4e60-bdfc-c9861e438397.png)

**Comment by apeacock1991** [comment]
On this point, and maybe I am just doing it wrong, but is there any plan to add support for all the FontAwesome icons?

e.g. things like brands, such as React and Java, don't currently seem supported, at least in the Mermaid live editor, and it'd be pretty useful to have access to all the brand-related ones.

**Comment by jpl-jengelke** [comment]
What about just adding support for the [free icons](https://fontawesome.com/search?m=free)? 

For instance, `wifi` works in the Live Editor but `swift` does not. [Both icons are listed here.](https://fontawesome.com/search?q=wifi&m=free)

**Comment by ioggstream** [comment]
Note: brand icons are accessible via the `fab:` prefix, as shown in the docs, e.g. `fab:twitter` or `fab:python`

**Comment by richtong** [comment]
Ah genius!

Sent via Superhuman ( ***@***.*** )

**Comment by jgreywolf** [comment]
Closing as this appears to have been resolved on the mermaid/live editor side

**Comment by kaylynn234** [comment]
Icons that are rendered in the live editor don't appear to be present in a PNG exported from the live editor - I'm not sure if this would constitute the same issue, but it's certainly strange.

**Comment by jond01** [comment]
```mermaid
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectiveness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
```
