### ISSUE TITLE
Hello everyone, please help, how to set each discount to become a right angle?

### ISSUE THREAD

**Issue by lymi1022** [mermaid-js/mermaid#1413]
I am a programmer from China with limited technology. When I want to connect the current state to the next state, the polyline is connected at a right angle of 90 degrees. Please tell me, does this plugin support the configuration of connections between right angles? How to configure, thank you very much!    Similar to the picture on the website below，http://wangxen21.lofter.com/tag/%E4%B8%9A%E5%8A%A1%E6%B5%81%E7%A8%8B%E5%9B%BE

**Comment by hikerpig** [comment]
As far as I know, currently there is no config for this.

**Comment by jgreywolf** [comment]
Mermaid does not currently support a feature such as this
