### ISSUE TITLE
erDiagram: empty label not working

### ISSUE THREAD

**Issue by zepatrik** [mermaid-js/mermaid#1415]
**Describe the bug**
Unlike the documentation states it is not possible to have an empty label by setting an empty double quoted string. That will result in a syntax error.
On the other had you can achieve an empty label by having a space in double quotes.

**To Reproduce**
Empty string example: https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZXJEaWFncmFtXG4gICAgICAgIENVU1RPTUVSIHx8LS1veyBPUkRFUiA6IFwiXCJcblx0XHRcdFx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

Space example: https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZXJEaWFncmFtXG4gICAgICAgIENVU1RPTUVSIHx8LS1veyBPUkRFUiA6IFwiIFwiXG5cdFx0XHRcdFx0IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0

**Expected behavior**
As described [in the docs](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram?id=other-things) it should be possible to have an empty string label.

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chromium
 - Version: 81

**Smartphone (please complete the following information):**
not tested

**Comment by spopida** [comment]
Thanks for pointing out this bug @zepatrik. It should be fixed in the next release.
