### ISSUE TITLE
Multiple notes are merged together if one of them is in block syntax

### ISSUE THREAD

**Issue by thomasklein-winemaker** [mermaid-js/mermaid#1416]
**Describe the bug**
With 3 notes it seems that the last 2 notes are somehow merged together and also the subsequent mermaid instructions are taken in.

I managed to bypass the issue by having all of them in single-line syntax. I could still achieve multi-line display by using the HTML linebreak element.

**To Reproduce**
[Link to online editor which produces the above image](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtXG4gICAgbm90ZSBsZWZ0IG9mIFdhaXRpbmdcbiAgICAgICAgQ29tbWVudCAxXG4gICAgZW5kIG5vdGVcbiAgICBcbiAgICBbKl0gLS0-IE9wZW46IE9yZGVyIHJlY2VpdmVkXG4gICAgT3BlbiAtLT4gV2FpdGluZ1xuICAgIFdhaXRpbmcgLS0-IFJlYWR5U1xuICAgIFxuICAgIG5vdGUgbGVmdCBvZiBSZWFkeVNcbiAgICAgICAgQ29tbWVudCAyXG4gICAgZW5kIG5vdGVcblxuICAgIFJlYWR5UyAtLT4gU2hpcHBlZFxuICAgIFxuICAgIFNoaXBwZWQgLS0-IERlbGl2ZXJlZFxuICAgIERlbGl2ZXJlZCAtLT4gWypdXG5cbiAgICBub3RlIGxlZnQgb2YgU2hpcHBlZFxuICAgICAgICBDb21tZW50M1xuICAgIGVuZCBub3RlIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Expected behavior**
Notes a separated.

**Screenshots**
<img width="483" alt="Screenshot 2020-05-17 at 10 54 11" src="https://user-images.githubusercontent.com/64782880/82140014-c9cf2400-982c-11ea-8258-17b20558512d.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox, Chrome
 - Version latest

**Comment by GDFaber** [comment]
Hi @thomasklein-winemaker, thanks for reaching out. It seems the parser is too greedy when looking for `end note`, but that is just a guess and needs further analysis.

In the mean time you could use the one-line variant as a workaround, [here is an example](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtXG4gICAgbm90ZSBsZWZ0IG9mIFdhaXRpbmcgOiBDb21tZW50IDE8YnI-c2Vjb25kIGxpbmVcbiAgICBcbiAgICBbKl0gLS0-IE9wZW46IE9yZGVyIHJlY2VpdmVkXG4gICAgT3BlbiAtLT4gV2FpdGluZ1xuICAgIFdhaXRpbmcgLS0-IFJlYWR5U1xuICAgIFxuICAgIG5vdGUgbGVmdCBvZiBSZWFkeVMgOiBDb21tZW50IDJcblxuICAgIFJlYWR5UyAtLT4gU2hpcHBlZFxuICAgIFxuICAgIFNoaXBwZWQgLS0-IERlbGl2ZXJlZFxuICAgIERlbGl2ZXJlZCAtLT4gWypdXG5cbiAgICBub3RlIGxlZnQgb2YgU2hpcHBlZCA6IENvbW1lbnQzXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ).

**Comment by antoine-fl** [comment]
I got hit by this too.
[Here is another workaround I found.](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtXG4gICAgT3BlbjogT3BlblxuICAgIFdhaXRpbmc6IFdhaXRpbmdcbiAgICBub3RlIGxlZnQgb2YgV2FpdGluZ1xuICAgICAgICBDb21tZW50IDFcbiAgICBlbmQgbm90ZVxuICAgIFJlYWR5UzogUmVhZHlTXG4gICAgbm90ZSBsZWZ0IG9mIFJlYWR5U1xuICAgICAgICBDb21tZW50IDJcbiAgICBlbmQgbm90ZVxuICAgIFNoaXBwZWQ6IFNoaXBwZWRcbiAgICBub3RlIGxlZnQgb2YgU2hpcHBlZFxuICAgICAgICBDb21tZW50M1xuICAgIGVuZCBub3RlXG4gICAgRGVsaXZlcmVkOiBEZWxpdmVyZWRcblxuICAgIFsqXSAtLT4gT3BlbjogT3JkZXIgcmVjZWl2ZWRcbiAgICBPcGVuIC0tPiBXYWl0aW5nXG4gICAgV2FpdGluZyAtLT4gUmVhZHlTXG4gICAgUmVhZHlTIC0tPiBTaGlwcGVkICAgXG4gICAgU2hpcHBlZCAtLT4gRGVsaXZlcmVkXG4gICAgRGVsaXZlcmVkIC0tPiBbKl1cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0IiwidGhlbWVWYXJpYWJsZXMiOnsiYmFja2dyb3VuZCI6IndoaXRlIiwicHJpbWFyeUNvbG9yIjoiI0VDRUNGRiIsInNlY29uZGFyeUNvbG9yIjoiI2ZmZmZkZSIsInRlcnRpYXJ5Q29sb3IiOiJoc2woODAsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsInByaW1hcnlCb3JkZXJDb2xvciI6ImhzbCgyNDAsIDYwJSwgODYuMjc0NTA5ODAzOSUpIiwic2Vjb25kYXJ5Qm9yZGVyQ29sb3IiOiJoc2woNjAsIDYwJSwgODMuNTI5NDExNzY0NyUpIiwidGVydGlhcnlCb3JkZXJDb2xvciI6ImhzbCg4MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJwcmltYXJ5VGV4dENvbG9yIjoiIzEzMTMwMCIsInNlY29uZGFyeVRleHRDb2xvciI6IiMwMDAwMjEiLCJ0ZXJ0aWFyeVRleHRDb2xvciI6InJnYig5LjUwMDAwMDAwMDEsIDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxKSIsImxpbmVDb2xvciI6IiMzMzMzMzMiLCJ0ZXh0Q29sb3IiOiIjMzMzIiwibWFpbkJrZyI6IiNFQ0VDRkYiLCJzZWNvbmRCa2ciOiIjZmZmZmRlIiwiYm9yZGVyMSI6IiM5MzcwREIiLCJib3JkZXIyIjoiI2FhYWEzMyIsImFycm93aGVhZENvbG9yIjoiIzMzMzMzMyIsImZvbnRGYW1pbHkiOiJcInRyZWJ1Y2hldCBtc1wiLCB2ZXJkYW5hLCBhcmlhbCIsImZvbnRTaXplIjoiMTZweCIsImxhYmVsQmFja2dyb3VuZCI6IiNlOGU4ZTgiLCJub2RlQmtnIjoiI0VDRUNGRiIsIm5vZGVCb3JkZXIiOiIjOTM3MERCIiwiY2x1c3RlckJrZyI6IiNmZmZmZGUiLCJjbHVzdGVyQm9yZGVyIjoiI2FhYWEzMyIsImRlZmF1bHRMaW5rQ29sb3IiOiIjMzMzMzMzIiwidGl0bGVDb2xvciI6IiMzMzMiLCJlZGdlTGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsImFjdG9yQm9yZGVyIjoiaHNsKDI1OS42MjYxNjgyMjQzLCA1OS43NzY1MzYzMTI4JSwgODcuOTAxOTYwNzg0MyUpIiwiYWN0b3JCa2ciOiIjRUNFQ0ZGIiwiYWN0b3JUZXh0Q29sb3IiOiJibGFjayIsImFjdG9yTGluZUNvbG9yIjoiZ3JleSIsInNpZ25hbENvbG9yIjoiIzMzMyIsInNpZ25hbFRleHRDb2xvciI6IiMzMzMiLCJsYWJlbEJveEJrZ0NvbG9yIjoiI0VDRUNGRiIsImxhYmVsQm94Qm9yZGVyQ29sb3IiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJsYWJlbFRleHRDb2xvciI6ImJsYWNrIiwibG9vcFRleHRDb2xvciI6ImJsYWNrIiwibm90ZUJvcmRlckNvbG9yIjoiI2FhYWEzMyIsIm5vdGVCa2dDb2xvciI6IiNmZmY1YWQiLCJub3RlVGV4dENvbG9yIjoiYmxhY2siLCJhY3RpdmF0aW9uQm9yZGVyQ29sb3IiOiIjNjY2IiwiYWN0aXZhdGlvbkJrZ0NvbG9yIjoiI2Y0ZjRmNCIsInNlcXVlbmNlTnVtYmVyQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvciI6InJnYmEoMTAyLCAxMDIsIDI1NSwgMC40OSkiLCJhbHRTZWN0aW9uQmtnQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvcjIiOiIjZmZmNDAwIiwidGFza0JvcmRlckNvbG9yIjoiIzUzNGZiYyIsInRhc2tCa2dDb2xvciI6IiM4YTkwZGQiLCJ0YXNrVGV4dExpZ2h0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0RGFya0NvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dE91dHNpZGVDb2xvciI6ImJsYWNrIiwidGFza1RleHRDbGlja2FibGVDb2xvciI6IiMwMDMxNjMiLCJhY3RpdmVUYXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwiYWN0aXZlVGFza0JrZ0NvbG9yIjoiI2JmYzdmZiIsImdyaWRDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQmtnQ29sb3IiOiJsaWdodGdyZXkiLCJkb25lVGFza0JvcmRlckNvbG9yIjoiZ3JleSIsImNyaXRCb3JkZXJDb2xvciI6IiNmZjg4ODgiLCJjcml0QmtnQ29sb3IiOiJyZWQiLCJ0b2RheUxpbmVDb2xvciI6InJlZCIsImxhYmVsQ29sb3IiOiJibGFjayIsImVycm9yQmtnQ29sb3IiOiIjNTUyMjIyIiwiZXJyb3JUZXh0Q29sb3IiOiIjNTUyMjIyIiwiY2xhc3NUZXh0IjoiIzEzMTMwMCIsImZpbGxUeXBlMCI6IiNFQ0VDRkYiLCJmaWxsVHlwZTEiOiIjZmZmZmRlIiwiZmlsbFR5cGUyIjoiaHNsKDMwNCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGUzIjoiaHNsKDEyNCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIiwiZmlsbFR5cGU0IjoiaHNsKDE3NiwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGU1IjoiaHNsKC00LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTYiOiJoc2woOCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGU3IjoiaHNsKDE4OCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIn19LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

**Comment by jgreywolf** [comment]
This has been resolved with current version of mermaid
