### ISSUE TITLE
flowchart rendering and htmlLabels

### ISSUE THREAD

**Issue by nsampangi** [mermaid-js/mermaid#1418]
first of all, let me say that this is an awesome library. great job.

I saw that you now have flowchart rendering. One thing I really like about mermaid is the ability to use html markup as part of the node description. Does that not work in flowchart rendering or am I missing something?

Thanks and great job again,
NS

**Comment by knsv** [comment]
Thanks, thats the kind of input we were hoping for when adding this as beta. The reason we left out the html part of the labels is that it make the generated svgs invalid in many svg editing apps. Styling wise you can style the svg elements BUT if users want to to add additional markup thats a valid excuse too keep the html labels.
