### ISSUE TITLE
The mermaid.parse(txt) function is not working

### ISSUE THREAD

**Issue by AndrewBuntsev** [mermaid-js/mermaid#1421]
According to the documentation  
https://mermaid-js.github.io/mermaid/#/usage?id=advanced-usage
"The function mermaid.parse(txt) takes a text string as an argument and returns true if the text is syntactically correct and false if it is not"
It is not working for me for some reason

Steps to reproduce:
1. install mermaid:  npm install mermaid   
(installed  "mermaid": "^8.5.1")

2. import it
import mermaid, { mermaidAPI } from 'mermaid';

3. calling the parse API function
    const result = mermaid.parse('sequenceDiagram');
    const result1 = mermaidAPI.parse('sequenceDiagram');
    console.log(result);
    console.log(result1);

The result is:
undefined
undefined

![5](https://user-images.githubusercontent.com/44885451/82389323-36d9f800-9a7f-11ea-83e4-ef77ba5d8f19.png)

Please advice what I am doing wrong

**Comment by niravcodes** [comment]
Can reproduce. Here is what seems to happen:
If Mermaid syntax is correct, returns Undefined.
If Mermaid syntax is incorrect, returns an object describing the error

**Comment by AndrewBuntsev** [comment]
Argh, thanks, that makes sense now.
I just have to wrap it with the try-catch now.
Pretty annoying but not critical.
