### ISSUE TITLE
Publish final bundles in the `dist/` folder

### ISSUE THREAD

**Issue by acalvo** [mermaid-js/mermaid#1423]
**Is your feature request related to a problem? Please describe.**
I wanted to set Mermaid as a dependency of a [Hugo](https://gohugo.io/) theme. To do so, Hugo allows adding Hugo Modules that are like Go Modules: you put the repo of the dependency and access its content. The problem is that this repo doesn't provide a copy of `mermaid[.min].js` in its `dist/` folder. That is only available in the npmjs package. That's why it can't be used as a Hugo/Go Module.

**Describe the solution you'd like**
Commit `mermaid[.min].js` in the `dist/` folder. Either everywhere (`master`/`develop`/etc) or just in `release/X` branches.

**Describe alternatives you've considered**
For the time being, I'm forced to copy the JS file by hand to my project, which bypasses all the benefits of a proper dependency version management like Go Modules (same as npm, etc.)

**Comment by GDFaber** [comment]
We should do this. I'd also like to extend `yarn build` so it creates the minifed version as well.

**Comment by knsv** [comment]
Hi!

We are currently having compiled bundles included in git for this very reason. However ... this is causing a fair amount of problems for us in development as this often generates conflicts. So in shot, we want to adjust this to a less error prone approach.

@acalvo Is there a reason you can not use mermaid from a cdn, like the url below for instance?
"//cdn.jsdelivr.net/npm/mermaid@8.6.4/dist/mermaid.min.js"

If not we need to find a way to automate this in our release handling and keep the compiled bundles in the release branches.

I am open for comments, ideas and suggestions.

@acalvo @GDFaber @jgreywolf

**Comment by acalvo** [comment]
Hi! Sorry for the delay in my answer.

> @acalvo Is there a reason you can not use mermaid from a cdn, like the url below for instance?
"//cdn.jsdelivr.net/npm/mermaid@8.6.4/dist/mermaid.min.js"

Unfortunately, the policy in the project I'm working at is that we can not link external CDNs. Everything should be served from our own CDN.

I understand the problems you are facing. As I said in my first message I need this in order to use mermaid as a Go module, which simplifies and unifies the dependency version management of our Hugo theme. But of course there are other alternatives (copy-pasting the mermaid bundle in my project directly) which I'll have to do if you roll back these changes.

A solution in between both of them, like just publish the bundles in the `release/x.x.x` branches, would work great for me too.

Up to you, though. If I'm the only one that has faced this need, I understand if you decide to just roll back the changes completely :).

**Comment by GDFaber** [comment]
The current approach indeed causes trouble, sorry for that. I've been thinking about other ways to deliver the "dists" but did not get far. Should we revert it and take our time to think again?

**Comment by acalvo** [comment]
OK, go ahead :).

We will stick with v8.7.0 for the time being; hope we find a better way to deliver the `dist/` folder again in the future :).

**Comment by GDFaber** [comment]
Alright, then I'll reset the ignore file to stop distributing the build files until we can come up with something better.
