### ISSUE TITLE
Dates off by 1 month

### ISSUE THREAD

**Issue by littlesandra88** [mermaid-js/mermaid#1426]
Copy/paste the following into [mermaid-live-editor](https://mermaid-js.github.io/mermaid-live-editor/)

```
gantt
  dateFormat  : YYYY-MM-DD
  title       MyTitle
  section Developers
  Installer    : d10, 2020-06-01, 30d
  Wait         : d20, after d10,  30d
```

and you will get

![mermaid-diagram-20200524210846](https://user-images.githubusercontent.com/2535545/82762702-cb878180-9e02-11ea-80da-e20dbd2bd4c5.png)

Notice the task `Installer` is suppose to begin `2020-06-01` but it starts around `2020-05-01`.

Mermaid: 8.5.1

**Comment by littlesandra88** [comment]
Found the issue. Colon is not allowed in `dateFormat`.

Leaving the ticket open, as this sort of thing should give a syntax error and not compile the graph.

**Comment by jgreywolf** [comment]
Closing as this now works with current version of mermaidjs
