### ISSUE TITLE
classDiagram "()" or "_" in class name 

### ISSUE THREAD

**Issue by pastorpflores** [mermaid-js/mermaid#1428]
Stupid question, but I need to name a class with special characters such as "()" or "_" but it gives me an error. Is it possible?

classDiagram
cell_name --> charge
---^
Expecting 'NEWLINE', 'EOF', 'LABEL', 'STRUCT_START', 'ANNOTATION_END', 'STR', 'AGGREGATION', 'EXTENSION', 'COMPOSITION', 'DEPENDENCY', 'LINE', 'DOTTED_LINE', 'UNICODE_TEXT', 'NUM', 'ALPHA', got 'PUNCTUATION'

Thanks!!

**Comment by jgreywolf** [comment]
What version are you using?  Here is an example from the live editor:
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jZWxsX25hbWUgLS0-IGNoYXJnZSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

**Comment by pastorpflores** [comment]
> What version are you using? Here is an example from the live editor:
> https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jZWxsX25hbWUgLS0-IGNoYXJnZSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

I'm using Typora 0.9.89 for Windows (not sure which version of Mermaid...) I'll look for updates on Typora. Thank you!

**Comment by jgreywolf** [comment]
No worries, If you have additional questions or need assistance, please open a new issue.
