### ISSUE TITLE
flowchart renders arrow gaps with circle nodes

### ISSUE THREAD

**Issue by zepatrik** [mermaid-js/mermaid#1429]
**Describe the bug**
The new "beta" flowchart type renders arrows to/from circle nodes with a gap around them.

**To Reproduce**
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZmxvd2NoYXJ0IFREXG4gICAgY3IoKENyZWF0ZSBSZXF1ZXN0KSkgLS0-IHNlcnZlcltSRVNUIFNlcnZlcl1cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

**Expected behavior**
Not a gap around the circle node.

**Screenshots**
![Screenshot from 2020-05-27 13-38-55](https://user-images.githubusercontent.com/5354445/83014738-88562a00-a01f-11ea-9a7f-723a3fe1509a.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chromium
 - Version 81

**Comment by knsv** [comment]
Thanks for reporting!

**Comment by zepatrik** [comment]
Guess we can close this issue?
