### ISSUE TITLE
Arrows missing in state diagram lie editor

### ISSUE THREAD

**Issue by aeneasr** [mermaid-js/mermaid#1434]
**Describe the bug**

The state diagram has no arrows in the live editor

**To Reproduce**

Take example from the docs:

```
stateDiagram-v2
    [*] --> Still
    Still --> [*]

    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]
```

**Expected behavior**

See arrows like in the docs.

**Screenshots**

<img width="2672" alt="Bildschirmfoto 2020-05-29 um 13 27 11" src="https://user-images.githubusercontent.com/3372410/83255113-21b44600-a1b0-11ea-911e-38791572c35e.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOS Catalina
 - Browser [e.g. chrome, safari]: All
 - Version [e.g. 22]: Live editor runs 8.5.1

**Comment by GDFaber** [comment]
Hi @aeneasr, can you check if this is still an issue in mermaid 8.6.4? I tried on Windows 10 and the arrows are rendered as expected, but I cannot test on Mac.

**Comment by aeneasr** [comment]
It appears to be fixed for all browsers except Safari!

**Comment by dselman** [comment]
I can confirm that the same bug exists on Safari with the class diagram.

**Comment by knsv** [comment]
I see the issue as well. An observation is that the issue only seems to occur in Safari.

**Comment by knsv** [comment]
Turned out to be an issue in the live-editor triggering a bug in safari.

**Comment by knsv** [comment]
Thanks for reporting this. Closing the issue after fix has been deloyed in the mermaid-live-editor
