### ISSUE TITLE
Circles not connected correclty in flowcharts

### ISSUE THREAD

**Issue by dvarrazzo** [mermaid-js/mermaid#1436]
**Describe the bug**

Arrows pointing to circle don't connected correctly. Tested in mermaid 8.5.1.

The following doesn't render ok:

```
    flowchart TD
        db[(PostgreSQL<br/>database)]
        broker((RabbitMQ<br/>broker))
        db --> broker
```

[![](https://mermaid.ink/img/eyJjb2RlIjoiICAgIGZsb3djaGFydCBURFxuXG4gICAgICAgIGRiWyhQb3N0Z3JlU1FMPGJyLz5kYXRhYmFzZSldXG4gICAgICAgIGJyb2tlcigoUmFiYml0TVE8YnIvPmJyb2tlcikpXG5cdFx0Ym94XG4gICAgICAgIGRiIC0tPiBicm9rZXJcblx0XHRib3ggLS0-IGJyb2tlclxuXHRcdFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiICAgIGZsb3djaGFydCBURFxuXG4gICAgICAgIGRiWyhQb3N0Z3JlU1FMPGJyLz5kYXRhYmFzZSldXG4gICAgICAgIGJyb2tlcigoUmFiYml0TVE8YnIvPmJyb2tlcikpXG5cdFx0Ym94XG4gICAgICAgIGRiIC0tPiBicm9rZXJcblx0XHRib3ggLS0-IGJyb2tlclxuXHRcdFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

compare to graph diagrams:

```
    graph TD
        db[(PostgreSQL<br/>database)]
        broker((RabbitMQ<br/>broker))
        db --> broker
```

[![](https://mermaid.ink/img/eyJjb2RlIjoiICAgIGdyYXBoIFREXG5cbiAgICAgICAgZGJbKFBvc3RncmVTUUw8YnIvPmRhdGFiYXNlKV1cbiAgICAgICAgYnJva2VyKChSYWJiaXRNUTxici8-YnJva2VyKSlcblx0XHRib3hcbiAgICAgICAgZGIgLS0-IGJyb2tlclxuXHRcdGJveCAtLT4gYnJva2VyXG5cdFx0XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiICAgIGdyYXBoIFREXG5cbiAgICAgICAgZGJbKFBvc3RncmVTUUw8YnIvPmRhdGFiYXNlKV1cbiAgICAgICAgYnJva2VyKChSYWJiaXRNUTxici8-YnJva2VyKSlcblx0XHRib3hcbiAgICAgICAgZGIgLS0-IGJyb2tlclxuXHRcdGJveCAtLT4gYnJva2VyXG5cdFx0XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

**Comment by knsv** [comment]
Thanks for reporting! Fix will come in next release.
