### ISSUE TITLE
Labels not aligned correctly in flowcharts

### ISSUE THREAD

**Issue by dvarrazzo** [mermaid-js/mermaid#1437]
**Describe the bug**

In flowcharts, multi-line labels are aligned on the left, which looks poorly compared to graph, where they are aligned centered.

Tested with mermaid 8.5.1.

See #1436 for an example.

**Comment by knsv** [comment]
Thanks for reporting. This will be resolved in 8.5.2

**Comment by jgreywolf** [comment]
@dvarrazzo  Can you please check to confirm that your issue is resolved in current version?
