### ISSUE TITLE
Custom arrowhead?

### ISSUE THREAD

**Issue by cs-prewittridge** [mermaid-js/mermaid#1440]
I'm trying to create a SysML diagram. I'm currently using the `classDiagram` to graph it. I will need the circle-cross icon (I think it's called an anchor?) for the arrowhead. Is there support for this? I couldn't find docs on it. Thanks!

![image](https://user-images.githubusercontent.com/66038715/83430321-756a9d80-a403-11ea-8e85-edc078b8ec37.png)

**Comment by jgreywolf** [comment]
This terminator is not currently available for class diagrams.
