### ISSUE TITLE
Strike trough commit

### ISSUE THREAD

**Issue by Kaligule** [mermaid-js/mermaid#1442]
**Describe the bug**

**To Reproduce**
1. Create a file with the following content (minimal example):
```
gitGraph BT:

commit
branch python3
commit
checkout python3
commit
```

2. render the file with mermaid (I used `~/node_modules/.bin/mmdc -i input.mmd -o output.png`)
3. open the rendered file (`open output.png`)
4. the commit in the middle is striken through by the line for the merge.

![output](https://user-images.githubusercontent.com/3586246/83596533-2472ba80-a565-11ea-8543-a73a66d73f71.png)

**Expected behavior**
The yellow circle for the commit should be on top of the blue line.

**Desktop (please complete the following information):**
 - OS: macos
 - Image viewers: Prieview and feh to open files
 - Mermaid: mmdc Version 8.5.1-2

**Comment by ashishjain0512** [comment]
Newer version of Gitgraph implementation solves this
