### ISSUE TITLE
Semicolon breaks sequence diagram

### ISSUE THREAD

**Issue by italomaia-bk** [mermaid-js/mermaid#1445]
**Describe the bug**
Add a ";" to the text description for a sequenceDiagram and it breaks the diagram.

**To Reproduce**

```mermaid
sequenceDiagram
  x->>y: ;abc
```

**Desktop (please complete the following information):**
 - tested on vscode markdown preview

**Comment by GDFaber** [comment]
Hi @italomaia-bk, semicolons can be used instead of line breaks to define the markup:
```sequenceDiagram; x->>y: abc;```

Your example produces an error because it is treated like this:
```
sequenceDiagram
  x->>y: 
  abc
```
