### ISSUE TITLE
mkdocs: How to signal an incorrect diagram directly into the html page?

### ISSUE THREAD

**Issue by fralau** [mermaid-js/mermaid#1447]
I am the maintainer of [mkdocs-mermaid2](https://github.com/fralau/mkdocs-mermaid2-plugin), a plugin that displays mermaid diagrams for the mkdocs static web generator. It works well.

But there is a **minor inconvenience**: currently, it functions like this: an incorrect diagram causes the plugin to fail silently. The HTML page will be displayed as if the diagram did not exist, and this can be confusing.

It would be preferable that the HTML page displayed an error such as Syntax Error, as is the case with the Mermaid live editor (see example in Mermaid live editor)

The full issue is described her:
https://github.com/fralau/mkdocs-mermaid2-plugin/issues/1#issue-611696830

Is there someone out there who has sufficient experience with the mermaid javascript library (and possibly a passing familiarity with mkdocs), who could orient us toward a simple and reliable situation?

Hint: we are able pass arguments to the javascript library in this way, from our yaml config file:

```yaml
plugins:
  - mermaid2:
      arguments:
        securityLevel: 'loose'
        theme: dark 
```

But I guess we would have to inject some javascript, right?

Thanks a lot!

**Comment by knsv** [comment]
Hi! This is a great idea. Just a generic 'syntax error' svg to be displayed when synax error is thrown. We should definitely do this.

**Comment by fralau** [comment]
I didn't think about that... Yes, if you could do it as a default feature, I would be the happiest person. 👍👍

**Comment by knsv** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/5837277/83941907-47180400-a7ef-11ea-9934-0627008905e3.png)

Only remains to make sure existing error handling is not impacted

**Comment by fralau** [comment]
No problem...  It fills its purpose: it reminds me of the Apple MacIntosh error msg of the late 1980s (there was a joke that a person would jump out of their chair and under the desk).

If one really wanted to make it luxurious, on could use the first lines of the original code as watermark (so as to convey what the graph was about). Since that's an SVG in theory that should be possible. But that's just a fancy nice to have....

**Comment by fralau** [comment]
What is the procedure? The team will accept the pull request and immediately release a new version? Or do we wait for a while?
