### ISSUE TITLE
Rename the logger to log

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#1449]
Use more standardized naming in the log functionality.

```
import { logger } from '../../logger';
...
logger.info('Extracting classes');
```

```
import { log } from '../../logger';
...
log.info('Extracting classes');
```

**Comment by harshilparmar** [comment]
Can I do this?

**Comment by GDFaber** [comment]
Sure thing, it is all yours 👍 
Please refer to the contribution guide and feel free to ask if we can be of help.

**Comment by harshilparmar** [comment]
@GDFaber @knsv  Here I have to change more uniform name for log function, right ? Correct me if I am wrong !!

**Comment by jgreywolf** [comment]
@harshilparmar What is status of this work?

**Comment by harshilparmar** [comment]
@jgreywolf It's done !! I have standardized as `logger` in all files. Is it correct ??
