### ISSUE TITLE
Allow $ in class-names

### ISSUE THREAD

**Issue by ikitommi** [mermaid-js/mermaid#1452]
I would like to use Mermaid Class Diagrams to describe Clojure/Java classes with `$` in class names. Currently Mermaid doesn't support it.

Here's an example example output (with DOT): 

![image](https://user-images.githubusercontent.com/567532/83963649-51e69d80-a8b0-11ea-8014-5cf4ad552d4f.png)

(source: https://github.com/metosin/schema-viz)

Related to #1453 .

**Comment by jgreywolf** [comment]
Closing this in favor of #1506
