### ISSUE TITLE
Font aswesome not rendered upon deployment

### ISSUE THREAD

**Issue by divyabhushan** [mermaid-js/mermaid#1457]
**Describe the bug**
Font awesome icons are not rendered on the deployed site - [Basic support for fontawesome](https://mermaid-js.github.io/mermaid/#/flowchart?id=basic-support-for-fontawesome)

**To Reproduce**
1. Go to 'https://mermaid-js.github.io/mermaid/#/flowchart?id=basic-support-for-fontawesome'
2. Look at the output diagram with missing icons

**Expected behavior**
<img width="350" alt="Screenshot 2020-06-07 at 23 26 44" src="https://user-images.githubusercontent.com/11659160/83980466-62c9fa00-a916-11ea-92dd-8969434f50ee.png">

**Screenshots**
Incorrect output:
<img width="314" alt="Screenshot 2020-06-07 at 23 25 24" src="https://user-images.githubusercontent.com/11659160/83980455-50e85700-a916-11ea-8ae1-07df90cae072.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version 83.0.4103.61
 - Browser: Safari
 - Version 13.0.3

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS13.3.1
 - Browser: Safari

**Additional context**

**Comment by syron** [comment]
Same issue here. we just updated to the latest release and the font awesome icons are no longer loading.

**Comment by divyabhushan** [comment]
True. Static site generators such as Jekyll and Hugo have good plugins that resolve these font awesome rendering problems.

**Comment by sudhakar-sekar** [comment]
Hi,
      How to use  font-awesome PRO icons in mermaid?
      Can anyone suggest me.

**Comment by divyabhushan** [comment]
@sudhakar-sekar, sorry didn't get your query. Did you mean how to display these icons in your code using an embed mermaid class? Like the one shown above?

**Comment by sudhakar-sekar** [comment]
@divyabhushan No, what I mean is I am able to use free font-awesome icons in mermaid. Can I use PRO font-awesome icons instead of free icons?

**Comment by knsv** [comment]
Is this still an issue?

It works fine in the live editor so the issue is not with mermaid. I think there is an issue with the documentation site.

https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBCW1wiZmE6ZmEtdHdpdHRlciBmb3IgcGVhY2VcIl1cbiAgICBCLS0-Q1tmYTpmYS1iYW4gZm9yYmlkZGVuXVxuICAgIEItLT5EKGZhOmZhLXNwaW5uZXIpO1xuICAgIEItLT5FKEEgZmE6ZmEtY2FtZXJhLXJldHJvIHBlcmhhcHM_KTsiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ

**Comment by imfence** [comment]
It works fine in the live editor. But when i use typora, it doesnt work.

**Comment by odebroqueville** [comment]
I believe that Mermaid may require an update to support Font Awesome version 5. Please note that the "fa" prefix on its own has been deprecated:

<img width="1187" alt="Screenshot 2021-09-16 at 14 35 19" src="https://user-images.githubusercontent.com/4818315/133613548-97eb0253-4082-468d-b54c-1c1e705d573f.png">

The above is taken from the [Font Awesome documentation](https://fontawesome.com/v5.15/how-to-use/on-the-web/referencing-icons/basic-use).

Also, below is what the [Mermaid documentation](https://mermaid-js.github.io/mermaid/#/flowchart?id=basic-support-for-fontawesome) currently displays in Safari 14.1.2 on macOS Big Sur 11.5.2. All icons are missing in the documentation.

<img width="404" alt="Screenshot 2021-09-16 at 14 05 06" src="https://user-images.githubusercontent.com/4818315/133613984-2a7ca6b5-4998-48a9-b94d-2c1627617b35.png">

and this is what the Mermaid Live Editor (supporting version 8.12.1) renders when copy-pasting the sample code from the documentation. For some reason, the twitter icon is missing!

<img width="1118" alt="Screenshot 2021-09-16 at 14 57 16" src="https://user-images.githubusercontent.com/4818315/133616382-20f67f12-8662-41ad-b398-38248df426b9.png">

However, the results in the Live Editor are not consistent: clicking on the button in the left pane to download a PNG file will show all icons missing, as in the Mermaid documentation, but clicking on the button to open a PNG in a new tab will show all the icons (with spacing issues for the text).

<img width="345" alt="Screenshot 2021-09-16 at 15 11 09" src="https://user-images.githubusercontent.com/4818315/133618305-138c4522-3492-4532-83eb-48f95535ac30.png">

**Comment by jgreywolf** [comment]
This is now working as expected in mermaidJS.  If there is still an issue in the Live Editor please open a new issue in that repo
