### ISSUE TITLE
configure class y position for each depth

### ISSUE THREAD

**Issue by hyungryuk** [mermaid-js/mermaid#1461]
When using classDiagram, i want to change y position for each depth deeper
for example, 
if the relations between each class looks like this
class_A-->class_B
class_B-->class_C
then 
depth level 1 : class_A
depth level 2 : class_B
depth level 3 : class_C

i want to make more distance between each level.

which configuration do i set?

**Comment by jgreywolf** [comment]
@hyungryuk Do you think you could mock up an image to better show what you are talking about here?

**Comment by jgreywolf** [comment]
Closing as there has been no response
