### ISSUE TITLE
[live editor] flowchart does not apply styles

### ISSUE THREAD

**Issue by polarathene** [mermaid-js/mermaid#1468]
Referencing the [docs for graph/flowchart styling](https://mermaid-js.github.io/mermaid/#/flowchart?id=styling-and-classes), I did not have any luck, aside from setting the `default` style which only applied to one node in my flow chart.

```
graph LR
    A:::someclass --> B
    classDef someclass fill:#f96;
```

This is example renders correctly, unless you change `graph` to `flowchart`.

**Comment by jgreywolf** [comment]
I am going to close this issue for now due to the lack of activity
