### ISSUE TITLE
Sequence diagram activations are misaligned for participants with long labels

### ISSUE THREAD

**Issue by DawMatt** [mermaid-js/mermaid#1480]
**Describe the bug**
Activations display in the wrong location for sequence diagrams with long participant labels.

**To Reproduce**
1. Open the Mermaid Live Editor
2. Paste in the following diagram code:
```
sequenceDiagram
participant Event as Very long name goes here
participant API as Some API
participant API2 as A different API
participant Client as Another very long name goes here

activate Event
Event ->> Event: Something important happens
Note over Event,Client: Some explanation goes here
activate Client
Event --x Client: Publish event
deactivate Event

deactivate Client
```

**Actual behavior**
Activations are misaligned and to the side of the participant's lifeline.

**Expected behavior**
Activations should align with the participant's lifeline.

**Screenshots**
![Activation skewed](https://user-images.githubusercontent.com/476705/84981737-88f26400-b178-11ea-9914-9c2f2fb0436e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

- Placing html breaks (```<br/>```) in the label name can work around the issue, if you are willing to for the participant labels to be two or more lines tall.
- [Joplin](https://joplinapp.org/) is using an older version of Mermaid (8.4.6?) and doesn't display this bug
- If you have trouble reproducing the issue it could be due to multiple monitors, screen resolutions and/or display scaling. I have multiple monitors are attached to my desktop, including a 4k monitor. Each monitor is using different scaling settings.

**Comment by cmmoran** [comment]
This should be addressed in the latest develop branch

**Comment by DawMatt** [comment]
Thanks, I can confirm this has been resolved in the library, and subsequently in both the Mermaid Live Editor and the VS Code plugin where I first noticed the issue.
