### ISSUE TITLE
Sequence diagram: long messages cut by the dragram borders

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#1483]
**Describe the bug**
After introducing a wrapping mechanism messages without wraps are beeing cut by the edges of the diagram.

![image](https://user-images.githubusercontent.com/5837277/85108928-d5897e00-b210-11ea-8682-f1f7fe82b58b.png)

They used to be rendered like below:
![image](https://user-images.githubusercontent.com/5837277/85108836-b12da180-b210-11ea-881a-5be2c7afa036.png)

**To Reproduce**
```
sequenceDiagram
   Alice->>Bob:wrap:Extremely utterly long line of longness which had preivously overflown the actor box as it is much longer than what it should be
   Bob->>Alice: I'm short though
```
**Expected behavior**
Diagrams with long messages withoutwrap info in the diagram code should be readable for a user without updating the diagram.

I see three solutions to this:
* Make wrapping is default behaviour
* Keep the positioning of the participants as the default behaviour and add the option of wrapping

Here is an example of a long message text wrapped:
![image](https://user-images.githubusercontent.com/5837277/85109718-10d87c80-b212-11ea-812d-df231ffc6690.png)

Ideal rendering of this difficult message would actually be a combination of the approaches with the participants separated by some distance and wrapped on two or three lines.

**Comment by knsv** [comment]
I really hope you will take the time and effort to look at the wrapping issue as it would a be a waste not getting these changes in.

I have moved the PR changes to a feature branch. This avoids having the upcoming 8.5.3 release depending on this potential PR.
https://github.com/mermaid-js/mermaid/tree/feature/1483_long_messages

 Last note, if you make a PR  point it to the feature branch.

**Comment by jgreywolf** [comment]
Closed as resolved
