### ISSUE TITLE
Renering of gantt chart is broken

### ISSUE THREAD

**Issue by abhijeet-pathak** [mermaid-js/mermaid#1487]
**Describe the bug**
A recent change has broken the correct rendering of gantt diagrams.

**To Reproduce**
1. Run the code from develop branch locally.
2. Go to http://localhost:9000 .
3. Scroll down to 'Adding GANTT diagram to mermaid'
4. The sections and task rectangles appear in gray and black colors.

**Expected behavior**
Appropriate colors/classes (shades of green) should be used for gantt diagrams.

**Screenshots**
![Screenshot from 2020-06-20 17-16-24](https://user-images.githubusercontent.com/56287990/85201043-d9ed8e00-b319-11ea-9fcd-c98625b67040.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser [Firefox]
 - Version [77.0.1]

**Additional context**
Digging deeper, I found that even though `config.gantt` inside `mermaidAPI.js` contains all the attributes, those do not get passed on to the `ganttRenderer.js` correctly from `mermaidAPI.js -> render() function switch case 'gantt'`. 
Therefore, the correct calculation of CSS class names fails, and class names are generated with names like `textNaN` instead of `text0` etc. Specifically, `numberSectionStyles` is not available inside `conf` in `ganttRenderer.js`.

**Comment by GDFaber** [comment]
This has already been fixed by #1497, so we can close here.
