### ISSUE TITLE
<br> tag is not escaped in mermaid diagram

### ISSUE THREAD

**Issue by tomoyukim** [mermaid-js/mermaid#1504]
**Describe the bug**
HTML tags like <div> or <p> is escaped but `<br>` is not escaped and rendered as line break.

For example, the text in the following diagram
```
graph LR;
    A["a<br>b"]-->D
```
will be rendered like
```
a
b
```
not `a<br>b`.

**To Reproduce**
1. Describe above diagram in `div` tag with `mermaid` class
2. mermaid.initialize(config) as following the guide
3. Rendered line break (not escaped)

**Expected behavior**
`<br>` tag should also be escaped as same as the other html tags.

**Screenshots**
<img width="165" alt="Screen Shot 2020-06-27 at 22 13 47" src="https://user-images.githubusercontent.com/1187581/85923126-7f2cd700-b8c3-11ea-9ee9-9fcc12a0e2f0.png">

**Comment by tomoyukim** [comment]
This is additional information. This seems to be happened in `graph` diagram only. I found`<br>` tag is directly included in `<svg>` tag generated by mermaid. It sometimes break the behavior. Also, the escape for `<br>` tag is ignored in case of rendering with `mermaid.initialize` with `class="mermaid"` tag. Even if I describe the diagram as below, 
```
graph LR;
    A["a&lt;br&gt;b"]-->D
```
it's rendered as line feed. I didn't face to the error when using update the diagram with `mermaid.parse` api.

**Comment by Yash-Singh1** [comment]
Now fixed:

https://mermaid.live/edit#pako:eNo1jkEPgjAMhf8KeQdO8AdGYqLBeDEe9Gg9VDZhkQ0yx8EQ_rtdkB6a5vV7r53RDNpAoQ08dtn5WpHPpPZ3Aud9rJ4hb6UTHmW5q1HAmeDYarHMCSXEzjhDUDJqDm9CseqtjacUmlbzmkoQqz8E9k134c0Vw-QJiVjIL3JiGjVHc9Q2DgHqxf3HFOApDrevb6CENxtUW5bP3Z9afgxVQxk
