### ISSUE TITLE
sequence diagram request: grouping actors in box

### ISSUE THREAD

**Issue by The-Alchemist** [mermaid-js/mermaid#1505]
## Request Description

I'd love to be able to do this:

![sequence diagram screenshot with box](https://chrzaszcz.dev/img/2019-11-kafka-transactions/simple-transaction.png)

More specifically, the "boxes" labeled "Application" and "Kafka".

Source: https://chrzaszcz.dev/2019/12/kafka-transactions/

## Proposed Syntax

I propose using the same syntax as loops:

```
sequenceDiagram
    participant Alice
    participant Bob


    box Alice_and_Bob
    Alice->>Bob: Hello John, how are you?
    Bob->>Alice: Fight against hypochondria
    end
    
```

**Comment by knsv** [comment]
Thats a good idea! We should do this.

**Comment by cmmoran** [comment]
Agreed. I can probably get this implemented.

soon™

**Comment by The-Alchemist** [comment]
> Agreed. I can probably get this implemented.
> 
> soon™

You're awesome, @cmmoran !

**Comment by eclaus** [comment]
If the participants belong to a single box, it could be set when creating the participants.  
For example:  

    sequenceDiagram
        %% Alice and Bob are grouped in "Alice_and_Bob" box
        box Alice_and_Bob
        participant Alice
        participant Bob
        end
        %% Truddy does not belong to a group
        participant Truddy

**Comment by orenyomtov** [comment]
I would appreciate this feature as well :)

**Comment by The-Alchemist** [comment]
I don't mind creating (and funding) a bounty on https://gitcoin.co,  https://www.bountysource.com, or https://gitpay.me  if someone is interested. 😄

**Comment by chrimaho** [comment]
Hi Team, Any progress on this request? I am very interested in this feature.

**Comment by iforwms** [comment]
Also interested in this feature.

**Comment by Zyaen** [comment]
+1

**Comment by niklr** [comment]
+1

**Comment by maikheene** [comment]
+1

**Comment by amitkshirsagar13** [comment]
Let me give it a try 👍 @The-Alchemist

**Comment by The-Alchemist** [comment]
> Let me give it a try 👍 @The-Alchemist

That sounds great!  Bounty is still active 🥇 

https://app.bountysource.com/issues/91876024-sequence-diagram-request-grouping-actors-in-box

**Comment by gayalkuruppu** [comment]
Will this be added anytime soon?

**Comment by oleveau** [comment]
Hi There , since I really wanted this feature too, I have done it 
Hopefully it will be accepted / merged ;)

**Comment by rranjan3** [comment]
Would this support nested boxes as well? Like -

sequenceDiagram
    box Friends
      box Alice_and_Bob
        participant Alice
        participant Bob
      end
      participant Truddy
    end

I see errors trying to do this.
