### ISSUE TITLE
Escaping string in class diagram

### ISSUE THREAD

**Issue by ashwinsajiv** [mermaid-js/mermaid#1506]
**Is your feature request related to a problem? Please describe.**
Not able to escape special characters on class diagram name. 

**Describe the solution you'd like**
	class Duck["sda !@# sd"]{
		+String beakColor
		+swim()
		+quack()
	}
Would be great if I could do this.

**Describe alternatives you've considered**
Using this to generate mermaid code, current work around is to replace unsupported string.

**Comment by jgreywolf** [comment]
This is similar to #999

**Comment by jgreywolf** [comment]
Additional info from #1452 
I would like to use Mermaid Class Diagrams to describe Clojure/Java classes with `$` in class names. Currently Mermaid doesn't support it.

Here's an example example output (with DOT): 

![image](https://user-images.githubusercontent.com/567532/83963649-51e69d80-a8b0-11ea-8014-5cf4ad552d4f.png)

(source: https://github.com/metosin/schema-viz)

**Comment by init-dcat-ap-de** [comment]
Similar to #1635.

**Comment by alexzhaohong** [comment]
In a flowchart diagram, I want to be able to add quotation marks `"` to the label of a node. Is that possible?

**Comment by jgreywolf** [comment]
> In a flowchart diagram, I want to be able to add quotation marks `"` to the label of a node. Is that possible?

I would suggest creating a new issue

**Comment by jgreywolf** [comment]
Closing this item as resolved with merge of PR #1907
Please open a new issue for any similar items
