### ISSUE TITLE
[Website] mermaidjs.github.io Transition is jarring (8.4 website to 8.5 website)

### ISSUE THREAD

**Issue by dmayle** [mermaid-js/mermaid#1508]
**Describe the bug**
When going to the site http://mermaidjs.github.io the documentatin/site for 8.4 is shown for a few seconds before being redirected to http://mermaid-js.github.io/mermaid which shows the documentation for 8.5.  Because the large diagrams at the top of the page (New class diagrams for 8.4) are not the same as on 8.5 (Gantt diagrams featured), the transition is always jarring.

**To Reproduce**
1. Go to http://mermaidjs.github.io
2. Watch 8.4 docs displayed for a few seconds
3. Site auto-redirects to http://mermaid-js.github.io/mermaid
4. Watch diagrams jump

**Expected behavior**
Either an HTTP-level redirect, or at least matching content between the two sites

**Comment by GDFaber** [comment]
Hi @dmayle, thank you for reaching out. We improved redirecting from mermaidjs by removing the delay, content transition should be gone now as well.
