### ISSUE TITLE
diagram without flowdirection 

### ISSUE THREAD

**Issue by FriedrichStein** [mermaid-js/mermaid#1527]
Is it possible to draw diagrams without a "flow" in mermaid?
Just items that form an interdependent network.
I'm looking for s.t. like this: 
![Bildschirmfoto 2020-07-06 um 21 25 03](https://user-images.githubusercontent.com/53973194/86751325-df97e300-c03e-11ea-8b06-c02705c88173.jpg)

I tried it out with flow- and statediagrams, but it seems there is no way without having a hierarchy.
![Bildschirmfoto 2020-07-06 um 21 30 45](https://user-images.githubusercontent.com/53973194/86751434-f1798600-c03e-11ea-9f83-96ce7406c7fa.jpg)
![Bildschirmfoto 2020-07-06 um 21 31 00](https://user-images.githubusercontent.com/53973194/86751454-f5a5a380-c03e-11ea-8117-7666fd3322c8.jpg)

PS: Is GitHub the right place to post such a question? I have no experience so far with GitHub, but couldn't find a place for general questions.

**Comment by ourweakness** [comment]
This! I use mermaid for network diagrams and having non-hierarchical, or more definable hierarchies would be a huge boon. A classic example I run into is where  I have a cross connect in router, and inherently it places one as the "higher" router - see the graph below

![image](https://user-images.githubusercontent.com/2288647/90249313-38aa2200-de08-11ea-8f60-bddeddd95d4a.png)

In my mind, P1 and P2, P3 and P4, and P5 and P6 would all be in the same "level", but adding the cross connect links makes one always a "higher" order than another. I get that the basis of this project was to make things quick and dirty (and always follow the same rules), but that added granularity would be an enormous help in writing documentation and truly the only think that keeps this from solving some major documentation issues for me.  

The way I'd like to see it would be a closer to a classic network layout, much more balanced i.e.


![image](https://user-images.githubusercontent.com/2288647/90250072-81160f80-de09-11ea-93ab-f70e0bf2a0f9.png)

**Comment by jgreywolf** [comment]
This is not possible right now due to the way that rendering/placement is handled with dagre

**Comment by ITJamie** [comment]
sad to see this closed out

**Comment by AartBluestoke** [comment]
> This! I use mermaid for network diagrams and having non-hierarchical, or more definable hierarchies would be a huge boon. A classic example I run into is where I have a cross connect in router, and inherently it places one as the "higher" router - see the graph below
> 
> ![image](https://user-images.githubusercontent.com/2288647/90249313-38aa2200-de08-11ea-8f60-bddeddd95d4a.png)
> 
> In my mind, P1 and P2, P3 and P4, and P5 and P6 would all be in the same "level", but adding the cross connect links makes one always a "higher" order than another. I get that the basis of this project was to make things quick and dirty (and always follow the same rules), but that added granularity would be an enormous help in writing documentation and truly the only think that keeps this from solving some major documentation issues for me.
> 
> The way I'd like to see it would be a closer to a classic network layout, much more balanced i.e.
> 
> ![image](https://user-images.githubusercontent.com/2288647/90250072-81160f80-de09-11ea-93ab-f70e0bf2a0f9.png)

the problem that i can see is that mermaid doesn't have ties in rank with purely left/right arrows (eg, 1-3 and 1-2 can't exist at the same time, left-right rendering mucks one up, top-down the other) - one of those would end up pointing to a "lower" rank, rather than rendering in a square :(
