### ISSUE TITLE
Can you add hollow arrow in UML Sequence diagrams to represent the asynchronous message？

### ISSUE THREAD

**Issue by TonyDandelion** [mermaid-js/mermaid#1528]
Non English native speaker warning!
Actually, the UML standard decide to use hollow arrow represent the asynchronous message in Sequence diagram. 
But you haven't add this kind of arrow in your greate artwork mermaid.
I bring up this little flaw to help you perfect mermaid.
Can you add hollow arrow in UML Sequence diagrams to represent the asynchronous message？
Thank you every much!

**Comment by knsv** [comment]
I will be adding this in version 8.9.0.

The syntax will be --) for a dotter version and -) for a solid arrow.

Example:
```
 sequenceDiagram
	  Actor1 -) Actor2:Async
	  Actor1 --) Actor2:Async dotted
	  Actor1 ->> Actor2:Sync
	  Actor1 -->> Actor2:Sync dotted
```

Renders like this:
![image](https://user-images.githubusercontent.com/5837277/104243709-49b39980-5461-11eb-81ec-3cd5ceac0531.png)
