### ISSUE TITLE
ERD Diagrams?

### ISSUE THREAD

**Issue by thardy** [mermaid-js/mermaid#1531]
I've seen a few conversations about ERD diagrams, but it's very unclear as to the status.  Are we close to being able to create ERD diagrams in mermaid?  I'm looking for tables, columns, types on the columns, and relationships between tables - nothing too fancy.

I saw the basic table relationship example, but I've seen nothing to allow columns to be described.

**Comment by spopida** [comment]
I Tim

I wrote the basic implementation earlier this year, and - aspirationally - I would really like to add the extra features you've mentioned, but right now I'm too busy.  Of course, someone else might be willing to have a go, but in the meantime, I'm afraid it remains on the Wishlist.

Best regards
Adrian

**Comment by thardy** [comment]
Ah, the answer to most open source questions.  I'm very familiar, as I'm the primary contributor of an open source project myself.  There's never a shortage of work to do.

Thanks for the response.  It's good to hear that it's still on the wishlist.

**Comment by abhijeet-pathak** [comment]
@spopida I would like to collaborate on this, may be I can add remaining enhancements etc.

**Comment by spopida** [comment]
@abhijeet-pathak Please feel free! I can try to support you, but I have such limited time right now.  Are you familiar with the product structure and contribution docs?  Suggest you spend a good long time understanding all the code (and running in the debugger).  Also look at other diagram types, especially class diagrams to see how the problem has been solved there.

**Comment by Feofilakt** [comment]
Hello! It is possible to add an entity without relationship?

**Comment by spopida** [comment]
@Feofilakt I'm afraid not.  I'd be interested in an example of where this is useful, but I accept there is no reason why it shouldn't be possible if that's what you want to do.

**Comment by spopida** [comment]
@thardy - FYI, this enhancement is on the way...

### Syntax:

 ```
     erDiagram
        DOG { string name }
        DOG {
          int age
          string breed
          string pedigree
        }
        OWNER ||..|{ DOG : owns
        OWNER {
          string name
          string address
          string homePhoneNumber
          string mobilePhoneNumber
        }
        TRAINER }|..|{ DOG : trains
        PROGRAMME }|--|| TRAINER : "operated by"
        DOG ||--|{ PROGRAMME : attends
        PROGRAMME {
          float costPerSession
        }

```

### Rendered Output:

![image](https://user-images.githubusercontent.com/19526120/97582517-c354f300-19ed-11eb-9e45-26e7110f2d69.png)

Hope it fits the bill?

**Comment by thardy** [comment]
That looks awesome!  Good job.
