### ISSUE TITLE
Beta: Flowchart feature has error with some node types

### ISSUE THREAD

**Issue by nathanielatom** [mermaid-js/mermaid#1532]
**Describe the bug**
With some node shapes, the beta: flowchart feature that allows for edges connecting to subgraphs encounters an error.

```
Uncaught TypeError: e.forEach is not a function
    at Object.ne [as polygon] (intersect-polygon.js:19)
    at Object.e.intersect (nodes.js:97)
    at edges.js:119
    at index.js:127
    at Array.forEach (<anonymous>)
    at t (index.js:123)
    at ye (index.js:145)
    at xe (flowRenderer-v2.js:356)
    at Object.render (mermaidAPI.js:779)
    at a (mermaid.js:101)
```

I'm not too sure, but `intersectPolygon` seems to get `polyPoints = {x: 1634.1822891235352, y: 307}` but expects an array.

**To Reproduce**
```
            flowchart TB
                c1{{chart1}}

                c1-->a2
                subgraph one
                a1-->a2
                end
                subgraph two
                b1-->b2
                end
                subgraph three
                c1-->c2
                end
                one --> two
                three --> two
                two --> c2
```

Seems to occur with hexagons, parallelograms, trapezoids, subroutines, and asymetric shapes.

**Expected behavior**
No error, same rendering as other shapes.

**Screenshots**
The graph does get partially rendered and clipped: https://www.dropbox.com/s/fb6z9gkm2mb9q1x/Screenshot%202020-07-09%2021.37.58.png?dl=0

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome 83
 - Version: 8.5.2

**Comment by knsv** [comment]
Thanks for reporting this. Working on getting the successor up to par before deprecating the old rendering.
