### ISSUE TITLE
How to determine then all diagrams are generated and attached to DOM?

### ISSUE THREAD

**Issue by FirstTimeInForever** [mermaid-js/mermaid#1539]
So, I am looking forward to use your library and implement some kind of caching. To make it work, I need to know, then the library is done with rendering and all SVGs are attached to DOM. Are there any ways to attach some kind of listener to render finished event (if there is such an event)? If there is no such listeners, are there any alternative ways of achieving this goal?

**Comment by jgreywolf** [comment]
Its possible that you might be able to attach a listener on the enclosing container?

**Comment by jgreywolf** [comment]
Closing due to lack of response/activity
