### ISSUE TITLE
how to re-render and how to change theme dynamically ？

### ISSUE THREAD

**Issue by jerryc127** [mermaid-js/mermaid#1544]
## Help us help you!
You want an answer. Here are some ways to get it quicker:
* Use a clear and concise title.
* Try to pose a clear and concise question.
* Include as much, or as little, code as necessary.
* Don't be shy to give us some screenshots, if it helps!

***
1.
some element are hidden, and need to click the button to show this.
the website was load and all the element are render.
The element which are hidden render is not normal， need to re-render, how to solve?

![image](https://user-images.githubusercontent.com/16351105/87538942-a19a5f00-c6cf-11ea-82cd-c27ffcbe0148.png)

2. 
how to change theme dynamically?
when i click the button and the website will switch the dark mode.
i need to change the mermaid to 'dark' theme quickly too.

3. how to detect the js was loaded?

**Comment by jgreywolf** [comment]
Closing due to lack of response/activity
