### ISSUE TITLE
Class diagram candinality misplaced in v8.6.0

### ISSUE THREAD

**Issue by josephzidell** [mermaid-js/mermaid#1552]
**Describe the bug**
In class diagrams, the cardinalities are misplaced in version 8.6.0

**To Reproduce**
1. Create a class diagram with 2 classes along with `"1" <-- "1..*"` cardinality

Example markup:
```mermaid
classDiagram

	abc "1" <-- "1..*" def

	class abc {
		serial id [PK] 🔑
		date date
		varchar<8> mva
		varchar<50> location
		varchar<17> unit_id
		timestamp created_at
		timestamp updated_at
	}

	class def {
		serial id [PK] 🔑
		integer person_id
		text[] types
		text[] conditions
		varchar<36> type
		integer altitude
		text remarks
		timestamp created_at
		timestamp updated_at
	}
```

**Expected behavior**
The cardinality is placed at the intersection of the class and the arrows

**Screenshots**
8.5.3 😄 
![schema](https://user-images.githubusercontent.com/1812443/87717367-45424880-c77e-11ea-8669-48838b21379f.png)

8.6.0 😢 
![schema](https://user-images.githubusercontent.com/1812443/87714935-89cbe500-c77a-11ea-993d-45cca135f4b9.png)

**Desktop (please complete the following information):**
 - OS: Mac Cataline
 - Browser Firefox
 - Version 78.0.2

**Comment by knsv** [comment]
Fixed with release 8.6.2
