### ISSUE TITLE
Breaking big flowchart into smaller chuncks

### ISSUE THREAD

**Issue by EnergeticPixels** [mermaid-js/mermaid#1559]
I have a flowchart that will be huge in nature.  I revolves around the Instructional Design model of [ADDIE](https://en.wikipedia.org/wiki/ADDIE_Model).  My part is WCAG/508, SCORM 2004, and xAPI validation and conformance testing of instructional media/courses. The implementation phase.  A lot of cogs in the wheel to this process.  Is there anyway to display only a portion of the 'flowchart' at the beginnig, then in response to an event (mouse/keyboard) action, display the next node?  Or maybe has anyone heard of using axios to dynamically display portions of a big flowchart/diagram?  Any shove in a direction would be helpful.  I am trying to assist project managers (and possibly my replacement) to understand this process.  I am trying to keep this rendering in SVG so that it will work on mobile media.

**Comment by knsv** [comment]
Hi @EnergeticPixels! That is a common issue, I face it myself from time. I understand, the issue with a large flowchart is that it gets really messy by its nature. What usually en up doing is breaking it up in sections, then if you want you could link a click on a section, to reveal its internals which would in practice be presented by another flowchart.

Sometimes this leads to a less exact representation of the underlying system but it's usually possible to get it exact enough. Those simplifications might not actually be what the project managers need to know anyway as in low level details. 

The overall picture is much easier to explain this way in my experience. With disclaimers that the real world has some additional information thats not presented in the diagram.

I hope that makes sense

**Comment by jgreywolf** [comment]
@EnergeticPixels Do you have any additional questions on this?

**Comment by EnergeticPixels** [comment]
@jgreywolf  no further comments. Apologize for being tardy on the reply.
