### ISSUE TITLE
Add Charts support similar to markviz

### ISSUE THREAD

**Issue by mmc41** [mermaid-js/mermaid#1564]
First of all, thanks for this wonderful project. Very cool! Note, that this feature request for Charts also comes with a constructive suggestion about how to possibly implement it (see end of this request)

**Is your feature request related to a problem? Please describe.**
I would like to be able to construct bar/line charts with mermaid using markdown syntax.

**Describe the solution you'd like**
The open source markvis project (https://github.com/geekplux/markvis) shows how this can be done with both syntax and an implementation. Unfortunately, the markvis appear to be abandoned but the code and markdown format looks like a good starting point.

**Describe alternatives you've considered**

**Additional context**
![markvis](https://user-images.githubusercontent.com/17993/88092433-c2135f00-cb90-11ea-8499-2ad0e6646e38.png)

For more info: https://github.com/geekplux/markvis

**Comment by jgreywolf** [comment]
This would be a new diagram - need someone to step forward and take this on

**Comment by merlinuwe** [comment]
Oh yes ..

A basic feature, which is missing.

**Comment by zm-cttae** [comment]
Noting here that we should be using a YAML style syntax instead of a JSON-like one  
All `- key: value` and never `[{ key: value }]`

**Comment by jgreywolf** [comment]
> Noting here that we should be using a YAML style syntax instead of a JSON-like one All `- key: value` and never `[{ key: value }]`

Can I ask why? Just curious

**Comment by M00TSDNS** [comment]
Doesn't the syntax currently avoid `{}` and `[]` atm?  
The current Mermaid config syntax is much more human-readable than JSON

**Comment by zm-cttae** [comment]
Doesn't the syntax currently avoid `{}` and `[]` atm?
The current Mermaid config syntax is much more human-readable than JSON

**Comment by merlinuwe** [comment]
The integration into Obsidian is my reason for this vote.

https://obsidian.md/

**Comment by jgreywolf** [comment]
> Doesn't the syntax currently avoid `{}` and `[]` atm? The current Mermaid config syntax is much more human-readable than JSON

Not necessarily. I mean, {} are used to define members of a class in class diagrams. Not something I had considered before. Personally, I much prefer the hierarchical aspect of JSON.

Not for this particular case though

**Comment by nirname** [comment]
This is under development https://github.com/mermaid-js/mermaid/pull/4413

**Comment by jgreywolf** [comment]
Closing as dupe

**Comment by nirname** [comment]
This may be kinda unfair to close this as a duplication because this was opened earlier. Nevertheless it is better to have one issue, please refer to a new one
* #4269
