### ISSUE TITLE
Dark theme broken since 8.6.0

### ISSUE THREAD

**Issue by scambier** [mermaid-js/mermaid#1573]
**Describe the bug**
The dark theme is illegible on several types of charts since 8.6.0

**To Reproduce**
The label color is too dark. 

**Expected behavior**
The contrast should be greater between labels and their background

**Screenshots**
Straight from the live editor:
![image](https://user-images.githubusercontent.com/3216752/88320377-ccaf2f00-cd1d-11ea-9c74-1cc02224c581.png)
![image](https://user-images.githubusercontent.com/3216752/88320397-d33da680-cd1d-11ea-8051-3ac4cd031706.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: Chromium 84, Firefox 78

**Comment by scambier** [comment]
Duplicate of #1553

**Comment by knsv** [comment]
The theming engine is getting an overhaul with version 8.7, in that version we are adding additional rendering tests for different themes. Will do a quick fix for dark themes in 8.6.3.
