### ISSUE TITLE
HTML tags are escaped starting from 8.6.0

### ISSUE THREAD

**Issue by igsm** [mermaid-js/mermaid#1578]
**Describe the bug**
HTML tags are escaped after 8.6.0 release. Images are not rendered even in the live editor. I installed 8.5.2 in my projects and tags work as expected.

**To Reproduce**
1. [Live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkEoPGltZyBzY3I9J2h0dHBzOi8vaWNvbnNjb3V0LmNvbS9tcy1pY29uLTMxMHgzMTAucG5nJyB3aWR0aD0nMjAnIGhlaWdodD0nMjAnIC8-KVxuQig8Yj5Cb2xkIHRleHQ8L2I-KSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0Iiwic2VjdXJpdHlMZXZlbCI6Imxvb3NlIiwiZmxvd2NoYXJ0Ijp7Imh0bWxsYWJlbHMiOnRydWUsImN1cnZlIjoiYmFzaXMifX0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

**Expected behavior**
Image should be rendered

**Screenshots**
<img width="819" alt="Screenshot 2020-07-25 at 20 54 15" src="https://user-images.githubusercontent.com/12541683/88464187-09635d80-ceb9-11ea-8cbe-a7aae749256b.png">

**Desktop (please complete the following information):**
 - OS: OS Catalina 10.15.5
 - Browser: Chrome, Brave, Safari
 - 8.6.*

**Comment by knsv** [comment]
Thanks for reporting. This is fixed by version 8.6.4
