### ISSUE TITLE
Comments do not work in class diagram classes

### ISSUE THREAD

**Issue by jacobranson** [mermaid-js/mermaid#1594]
**Describe the bug**
When adding a comment in a class diagram class, it does not remove the line from the render.

**To Reproduce**
```mermaid
classDiagram
  class Test {
    +int one
    %%+int two
  }
```

**Expected behavior**
The comment removes the line from the render.

**Screenshots**
![image](https://user-images.githubusercontent.com/28793608/89087695-18d42200-d363-11ea-91e0-27dda3f4120c.png)

**Comment by jgreywolf** [comment]
@jacobranson  I am not able to repro this in the [live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gIGNsYXNzIFRlc3Qge1xuICAgICtpbnQgb25lXG4gICAgJSUraW50IHR3b1xuICB9IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by jacobranson** [comment]
> @jacobranson  I am not able to repro this in the [live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gIGNsYXNzIFRlc3Qge1xuICAgICtpbnQgb25lXG4gICAgJSUraW50IHR3b1xuICB9IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

I have attached screenshots of the issue being shown in the live editor. If you take my example and paste it in there you should see that the property isn't being removed from the editor.

**Comment by jgreywolf** [comment]
Oh sorry, I did use your example, but since I didnt see the `%%` I assumed it was fine.  So that part is different with my link to live editor.  I am using Chrome. 

I will look into it
