### ISSUE TITLE
Unexpected Behavior connecting subgraphNode-->subgraphShape

### ISSUE THREAD

**Issue by ralfbetazi** [mermaid-js/mermaid#1602]
Thanks to all the folks who made mermaid!  I am a new user but quickly found it very useful and easy to grasp.  Fantastic way to do simple charts very quickly.

That said, I discovered odd and unexpected behavior trying to draw an arrow between one node in one subgraph and the shape of a different subgraph.  To illustrate, I'm trying to represent a system where two containers on an AWS-hosted system interact by having a subprocess in one container (Container_Alpha) uses AWS Batch to launch instances of a second container (Container_Beta).  I wanted to represent this by having an arrow drawn from the initiating subprocess to point at the subgraph shape Container_Beta (not any node within it).

I found that the following did not work:

```
%% this does not produce the desired result
flowchart TB
  subgraph container_Beta
    process_C-->Process_D
  end
  subgraph container_Alpha
    process_A-->process_B
    process_B-->|via_AWSBatch|container_Beta
    process_A-->|messages|process_C
  end
```
 I got the following:
![image](https://user-images.githubusercontent.com/12866082/89437064-ebd59580-d6fb-11ea-8fa8-84f5eef71a18.png)
Evidently `container_Beta` is inferred as a subgraph node notwithstanding the prior declaration as a subgraph ID on the right after the `flowchart TB` line and the subgraph seems to disappear.

Quite by accident, I discovered a definition which DID produce what I wanted, but it seems an odd way to do it, and possibly resulting from a accidental artifact rather than intended behavior.  If I give the following:
```
%% this produces the desired result
flowchart TB
  process_B-->|via_AWSBatch|container_Beta
  subgraph container_Beta
    process_C-->Process_D
  end
  subgraph container_Alpha
    process_A-->process_B
    process_A-->|messages|process_C
  end
```
I get the result I want:
![image](https://user-images.githubusercontent.com/12866082/89437541-90f06e00-d6fc-11ea-9766-ef9b9b35b1ba.png)
But this second version seems at the very least inconsistent because it seems to require the graph author to declare `process_B` and `Container_Beta` twice in two different places in an inconsisten fashion.  First you have to declare `process_B` and `container_Beta` as nodes external to any subgraph, then later you have to re-declare `container_Beta` as a subgraph and re-declare `process_B` as a node in subgraph `container_Alpha`.

Is there a more correct way to implement the behavior of the second graph definition?  Or am I doing it the "right" way?  Will this behavior disappear in a future release?

**Comment by knsv** [comment]
Hi!

I can reproduce the issue simplified. The way it should work is that from nodes should be tagged to subgraphs in order of occurrence where the last occurrence counts. The graph below:
```
subgraph A
a -->b
end
subgraph B
b
end
```

Should render this:
![image](https://user-images.githubusercontent.com/5837277/91653404-db1d0300-eaa0-11ea-82ec-eeefecb16b46.png)

It does not though. I will tag this as a bug.
