### ISSUE TITLE
Page https://mermaid-js.github.io/mermaid/#/stateDiagram is almost blank

### ISSUE THREAD

**Issue by JohnWu-Pro** [mermaid-js/mermaid#1609]
**Describe the bug**
Page https://mermaid-js.github.io/mermaid/#/stateDiagram is almost blank

**To Reproduce**
1. Using Chrome 84.0;
2. Open a new tab, and go to 'https://mermaid-js.github.io/mermaid/#/stateDiagram'
3. The page is almost blank

**Expected behavior**
A page displays content about the State Diagram.

**Screenshots**
Not Provided.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 84.0

**Comment by fitzagard** [comment]
Info from console when going to the page:

```javascript

Uncaught Error: Parse error on line 1:
stateDiagram-v2-v2 
^
Expecting 'SPACE', 'NL', 'SD', 'open_directive', got 'ID'
    at T.parseError (stateDiagram.jison:194)
    at T.parse (stateDiagram.jison:264)
    at Ii (stateRenderer-v2.js:215)
    at Object.render (mermaidAPI.js:374)
    at r.code ((index):47)
    at c.tok (docsify.min.js:1)
    at c.parse (docsify.min.js:1)
    at Function.c.parse [as parser] (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1

```

**Comment by liamjones** [comment]
Also getting this on https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram
