### ISSUE TITLE
SVG + Desctription Texts --> PNG/PDF

### ISSUE THREAD

**Issue by spbert29** [mermaid-js/mermaid#1616]
## Help us help you!
Is there an easy way to generate from the SVG + DIVS (where the node Texts are stored) a PNG/PDF?

Like this:
![image](https://user-images.githubusercontent.com/42182294/90311347-50fa6980-defa-11ea-9a25-137be3a7f677.png)

**Comment by jgreywolf** [comment]
Im not sure I am following - this is available on the live editor.  Are you asking how to achieve this within your own code?

**Comment by spbert29** [comment]
Exactly, i tried it with terminal command  with chromium - there it works but that was more a try out.

**Comment by jgreywolf** [comment]
I would suggest looking at what the live editor does

**Comment by DaveJarvis** [comment]
For exporting as PNG, see #2485.

**Comment by jgreywolf** [comment]
Closing due to lack of response/activity from OP
