### ISSUE TITLE
Gantt diagram repeating tasks

### ISSUE THREAD

**Issue by Alex-0293** [mermaid-js/mermaid#1618]
Good day!
Currently am working on automate powershell scheduler.
My vision include making gantt diagram for my scripts. 
Im doesnt found the way to draw repeating tasks. It can be drawn like different tasks, but it consumes a lot of space. 
Could you add repeating task functional.
![изображение](https://user-images.githubusercontent.com/5895448/90342062-dc185400-e00d-11ea-9d08-821206785a08.png)
For example, task CheckIPCameraRecord must be drawn every hour.

**Comment by kmbenitez** [comment]
Seconding this request.

**Comment by Alex-0293** [comment]
Friend! It`s very important in usual system administration tasks. Please take it in work.

**Comment by Cycadophyta** [comment]
This would be fantastic

**Comment by antonmatsiuk** [comment]
this is highly required for any scheduled cronjob tasks
