### ISSUE TITLE
How to change the color of arrowheads

### ISSUE THREAD

**Issue by LaurentDumont** [mermaid-js/mermaid#1619]
Hi! 

It seems that this : https://github.com/mermaid-js/mermaid/pull/376 was merged a while back. I'm looking at a way to get the arrowheads to change color in a LR graph as I have a dark background and they don't show up very clearly.

![image](https://user-images.githubusercontent.com/8936473/90342204-56c47d80-dfd4-11ea-914d-034a6aefd68c.png)

I've tried using a similar structure as the link style but it doesn't seem to work...

```
graph LR;
  A[Prometheus] --> B[Alertmanager] -->|WEBHOOK| C[Laptop FastAPI] -->|PRINT| D[Okidata 184 Turbo]
  linkStyle default stroke-width:2px,fill:green,stroke:blue;
{{< / mermaid >}}
```

**Comment by GDFaber** [comment]
I'm closing this issue in favour of #1236 which also covers the topic.
