### ISSUE TITLE
Flowchart doesn't show arrow heads for all shapes

### ISSUE THREAD

**Issue by Thomas-Swindells-t** [mermaid-js/mermaid#1620]
**Describe the bug**
Arrows only work with some node shapes

**To Reproduce**

    flowchart LR
    box[box] -->  
    rounded(rounded) -->  
    stadium([stadium]) -->  
    subroutine[[subroutine]] -->  
    cylindrical[(cylindrical)] -->  
    circle((circle))
    box2[box2] -->
    asymetric>asymetric] -->
    rhombus{rhombus} -->
    hexagon{{hexagon}} -->
    parallelogram[/parallelogram/]  -->
    parallelogramAlt[\parallelogramAlt\] 
    box3-->
    trapezoid[/trapezoid\] -->
    trapezoidAlt[\TrapezoidAlt/] -->
    last

**Expected behavior**
All links should have arrow heads, however only some do so (depending on target shape). In MS Edge none of the arrow heads show.

**Screenshots**
![mermaid-diagram-20200817143147](https://user-images.githubusercontent.com/68224654/90401781-5c829780-e096-11ea-9e37-986df3792f01.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, firefox, edge (even worse)
 - Version Mermaid live editor 8.7.0

**Comment by oliv3r** [comment]
@Thomas-Swindells-t I think the title would be 'arrow heads' to be more precise?

**Comment by Thomas-Swindells-t** [comment]
Agreed, I did some more digging and it turns out the arrow heads are being drawn, but appear to be targeting the centre of the shape  rather than the appropriate edge so then get overdrawn by the shape fill.
