### ISSUE TITLE
Mermaid Documentation Page is Broken for the 'stateDiagram' or 'entityRelationshipDiagram' section.

### ISSUE THREAD

**Issue by ksuperman** [mermaid-js/mermaid#1623]
**Describe the bug**
Mermaid Documentation Page is Broken for the 'stateDiagram' or 'entityRelationshipDiagram' section.

**To Reproduce**
1. Go to 'https://mermaid-js.github.io/mermaid/#/'
2. Click on 'stateDiagram' or 'entityRelationshipDiagram' in the side bar
3. See error

**Expected behavior**
The Document page for the 'stateDiagram' or 'entityRelationshipDiagram' should be loaded. 

**Screenshots**
The screenshot show the console error that is thorwn when the 'stateDiagram' or 'entityRelationshipDiagram' side nav link is clicked.
![image](https://user-images.githubusercontent.com/8981248/90556253-703d0500-e14d-11ea-8039-16fb162434f8.png)

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: chrome
 - Version: 84

**Additional context**
From preliminary investigation it looks like syntax error for the stateDiagram

**Comment by GDFaber** [comment]
Hi, this has already been fixed in #1609, it might take some time to put the corrected pages to work though.
