### ISSUE TITLE
Documentation page for State Diagram fails with runtime error

### ISSUE THREAD

**Issue by grancalavera** [mermaid-js/mermaid#1632]
**Describe the bug**

The documentation page for **State Diagrams** fails to load. When accessing the page from the left hand navigation, the previous page stays rendered. When accessing the page from a deep link, the website isn't render and instead a blank page shows.

**To Reproduce**
1. Navigate to this URL https://mermaid-js.github.io/mermaid/#/stateDiagram
2. Open the developer tools, you should see an error similar to this:

```
stateDiagram.jison:194 Uncaught Error: Parse error on line 1:
stateDiagram-v2-v2 
^
Expecting 'SPACE', 'NL', 'SD', 'open_directive', got 'ID'
    at T.parseError (stateDiagram.jison:194)
    at T.parse (stateDiagram.jison:264)
    at Ii (stateRenderer-v2.js:215)
    at Object.render (mermaidAPI.js:374)
    at r.code ((index):47)
    at c.tok (docsify.min.js:1)
    at c.parse (docsify.min.js:1)
    at Function.c.parse [as parser] (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1
```

**Expected behavior**
The documentation for **State Diagram** should render

**Screenshots**

![mermaid-runtime-error](https://user-images.githubusercontent.com/301030/90748378-072ecc00-e2ca-11ea-82f0-71a1cf75b0cd.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by GDFaber** [comment]
Hi @grancalavera, this has already been fixed in #1609 (see issue #1621). But the live docs where still broken, this should also be fixed now. Can you check if the error still shows up?

**Comment by grancalavera** [comment]
Hi @GDFaber , thanks for the speedy reply. Sorry, I didn't check the closed issues, my bad. Yes the page renders correctly now, amanzing 🎉 

![image](https://user-images.githubusercontent.com/301030/90773961-a1a10680-e2ee-11ea-9072-f50cd0a7f05e.png)

**Comment by GDFaber** [comment]
That's alright, the live docs were still broken so it was not entirely solved :-)
But as it is working again, we can close this issue.
