### ISSUE TITLE
`classDiagram` doesn't allow colons in class names

### ISSUE THREAD

**Issue by init-dcat-ap-de** [mermaid-js/mermaid#1635]
I'm trying to use mermaid for creating an class diagram in a semantic web context. There, colons are needed for prefixes:

```
classDiagram
    class dcat:Dataset {
        <<mandatory>>
    }
```

_Also an issue for @persidskiy , see https://github.com/mermaid-js/mermaid/issues/1266#issuecomment-643793801_

**Comment by mmngreco** [comment]
@init-dcat-ap-de and @persidskiy, Did you find any workaround for this ?

**Comment by init-dcat-ap-de** [comment]
@mmngreco 
Unfortunately yes: Switching to PlantUML.

**Comment by jgreywolf** [comment]
I will focus on this issue and see if I can make it work

**Comment by jgreywolf** [comment]
@mmngreco This issue should be resolved after #1877 PR has been merged...

**Comment by jgreywolf** [comment]
@aharth the code that you provided works in mermaid live as of 03/17/2023 - I am not sure when this changed, but it is possible to use : in names for classes as well as relationships

**Comment by aharth** [comment]
Do you have an example for using : in relationships?

The following does not work for me on mermaid live:
````
classDiagram
  `rdfs:Resource` --> `rdfs:Class`:`rdf:type`
````

**Comment by aharth** [comment]
I would need colons also in the labels of the edges.

E.g., Con:tains.

**Comment by andrawaag** [comment]
I found a workaround using #58, e.g., dc#58;isPartOf for dc:isPartOf. It is suboptimal, but it works.
