### ISSUE TITLE
`classDiagram` doesn't allow line breaks in Labels on Relations

### ISSUE THREAD

**Issue by init-dcat-ap-de** [mermaid-js/mermaid#1644]
`classDiagram` doesn't allow line breaks in Labels on Relations.

In Flow Charts it is allowed to use `<br>` and it works as exspected, but that's not the case for Class Diagrams.

**Comment by jgreywolf** [comment]
You can, however, use \n. Example from screenshot below: `Du\nck`

[![](https://mermaid.ink/img/pako:eNptkk1vwjAMhv9K5NOmFdTSD9pql2kMaQdO3KZKw7ShRG0SliZiwPjvSxntGCyX2I_9Wo6dA-SyoJBCXmPTTBiWCnkmiD1PgnGsyePXYEAWE5NlIq8Wt6Epa9a39I0uFf7BKXlgQhMs6TWea8VESUoqCqoug62kmSG35t39VYCjph089U4mJq8OP4D0RZcUq2dZS9UHmi3jndC6HwbzqvOPl_Xah_X1Bm3vDdvTVzGlVPc4R_GC-l_9aQS_DS2lrAlr3resLnqojOi14ACniiMr7DpOugz0mnKaQWrNgq7Q1DqDTLSpaLSc70QOqVaGOmA2hZ3IeYGQrrBuLN2geJOSd0nWhfQAn5COfH8Y-iM_8uPEi1wvjBzYQep78dBL3MQbJ1E8Do8O7E9ydxgFcZB4IzdI4tCNAs8BWjAt1ez8fdrr-A3KtrAu?type=png)](https://mermaid.live/edit#pako:eNptkk1vwjAMhv9K5NOmFdTSD9pql2kMaQdO3KZKw7ShRG0SliZiwPjvSxntGCyX2I_9Wo6dA-SyoJBCXmPTTBiWCnkmiD1PgnGsyePXYEAWE5NlIq8Wt6Epa9a39I0uFf7BKXlgQhMs6TWea8VESUoqCqoug62kmSG35t39VYCjph089U4mJq8OP4D0RZcUq2dZS9UHmi3jndC6HwbzqvOPl_Xah_X1Bm3vDdvTVzGlVPc4R_GC-l_9aQS_DS2lrAlr3resLnqojOi14ACniiMr7DpOugz0mnKaQWrNgq7Q1DqDTLSpaLSc70QOqVaGOmA2hZ3IeYGQrrBuLN2geJOSd0nWhfQAn5COfH8Y-iM_8uPEi1wvjBzYQep78dBL3MQbJ1E8Do8O7E9ydxgFcZB4IzdI4tCNAs8BWjAt1ez8fdrr-A3KtrAu)
