### ISSUE TITLE
Comments in `classDiagram` should be allowed inside of Class definitions

### ISSUE THREAD

**Issue by init-dcat-ap-de** [mermaid-js/mermaid#1645]
Comments in `classDiagram` are very limited.

The `%%` can only be used outside of Class definitions but should also be allowed inside of Class definitions, for example for quickly comment out unneeded properties.

**Comment by jgreywolf** [comment]
I will look into this.  This should be supported - and indeed I thought that we had some tests for this specific scenario

**Comment by jgreywolf** [comment]
Interesting aside here - the comment DOES work if you have something you want to keep after the comment.  as so:

` class Duck{
    %% comment6          +String beakColor
      +swim()
      +quack()
    }`
the comment is not displayed, but +String beakColor is shown.  Go figure

**Comment by jgreywolf** [comment]
Quick update on this item - it appears that comments inside of class definitions are not working due to directive support.  I am continuing to work on this to find a way to work around the conflict.

**Comment by ACMCMC** [comment]
Hi, I believe this is an important feature to have. It's very useful to have inline comments, and they are currently not supported...

**Comment by Yokozuna59** [comment]
Hello there! Are there any updates on this issue? I really think it's an essential feature to have in a mermaid.
So, @jgreywolf has started working on it? or anyone else?

I'm not an expert in javascript or typescript, and I'm not sure that is the best approach for it in terms of efficiency and performance. But maybe I'll come up with a regex for that. If anyone can provide some test cases and edge cases to be aware of.

**Comment by jgreywolf** [comment]
If you look at this example from live editor, you can see that the only place the comment does not work is AFTER a property.  Everything else seems to work fine.
(though interestingly, in the image below it doesnt work)

[![this example in live editor](https://mermaid.ink/img/pako:eNp1kE1vgzAMhv8KslSpFQjxMQLJtb321NuUixfSDkGSLiTaOsR_X6Ctdpjmi-3H7yvZnkCYVgIDMeA4Hjq8WFRcc7320cGLfuI6CrHZRMIoJbUj0Z0sEZ-c7fQlepPY781g7O_oP1M8fnZqu_s7fgoCjT88in67u6MZElDSKuzasOm6Dwf3LpXkwELZyjP6wXHgepGid-Z00wKYs14m4K8tOvm4DdgZhzHQK-pXY9RTFFpgE3wByylJy6asG5qRokrgFlCdpy-E1k1d0ZpUAc8JfK_uLCVlXmSE5k2R0SDJE5Bt54w9Ph67pPkHhjppNA?type=png)](https://mermaid.live/edit#pako:eNp1kE1vgzAMhv8KslSpFQjxMQLJtb321NuUixfSDkGSLiTaOsR_X6Ctdpjmi-3H7yvZnkCYVgIDMeA4Hjq8WFRcc7320cGLfuI6CrHZRMIoJbUj0Z0sEZ-c7fQlepPY781g7O_oP1M8fnZqu_s7fgoCjT88in67u6MZElDSKuzasOm6Dwf3LpXkwELZyjP6wXHgepGid-Z00wKYs14m4K8tOvm4DdgZhzHQK-pXY9RTFFpgE3wByylJy6asG5qRokrgFlCdpy-E1k1d0ZpUAc8JfK_uLCVlXmSE5k2R0SDJE5Bt54w9Ph67pPkHhjppNA)

**Comment by Yokozuna59** [comment]
> Which tells me that the issue has been mostly fixed within current version

Oh my bad, you're right, the live editor excludes those comments:

![image](https://user-images.githubusercontent.com/87622592/236015824-acea9fde-47ec-4167-8726-725fd0d623fd.png)

I'm using the [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) extension in VSCode to preview it. But it still shows that it's not commented.

![image](https://user-images.githubusercontent.com/87622592/236012960-55f840d4-0dd0-41ff-b56e-8c53799903b1.png)

So I assumed it wasn't fixed. When there is a syntax error in the code (although my code isn't, so I comment a line then uncomment it), it shows that the version is 9.4.0.

![image](https://user-images.githubusercontent.com/87622592/236014940-18ef4bba-9442-4866-9e83-9f61afca70de.png)

So, the problem might be in that version for comments in that use case. But the weird part is that the mermaid version they are using is [10.1.0](https://github.com/mjbvz/vscode-markdown-mermaid/blob/master/package.json#L96). I might open an issue there asking about it.

---

What about the other use case, the comments after properties?

**Comment by jgreywolf** [comment]
I am working on that one
