### ISSUE TITLE
Comments in `classDiagram` should be allowed at the end of an line (inline-comments)

### ISSUE THREAD

**Issue by init-dcat-ap-de** [mermaid-js/mermaid#1646]
Comments in `classDiagram` are very limited.

The `%%` can only be used outside of Class definitions but should also be allowed at the end of any line, so that the first part of the line is treaded normally and everything after the `%%` as comment.

I think an example is not needed, since inline-comments are a standard use-case.

**Comment by jgreywolf** [comment]
Like I mentioned in #1645,  This should be supported - and indeed I thought that we had some tests for this specific scenario

**Comment by jgreywolf** [comment]
Closing in favor of #1645
