### ISSUE TITLE
Pie chart (add totals for each item)

### ISSUE THREAD

**Issue by dxcore35** [mermaid-js/mermaid#1648]
Add totals in the right either in first style or second style, or both (with change in argument)

![pie](https://user-images.githubusercontent.com/7279156/91115981-61a49f80-e6b1-11ea-8a5b-9900ee6ada97.jpg)

**Comment by Kristinita** [comment]
**Type: +1** :+1:

### Argumentation

I want to use Mermaid pie charts to show statistics where is such a thing as [**sample size**](https://www.statisticshowto.com/probability-and-statistics/find-sample-size/#what).

For example, the statistics books as “[**How to Lie with Statistics**](https://en.wikipedia.org/wiki/How_to_Lie_with_Statistics)” provide examples, how to manipulate statistics:

![Percent bar chart](https://i.imgur.com/2mVHKG4.png)

![Absolute values](https://i.imgur.com/2mVHKG4.png)

The first graph looks solid. But it’s clear from the second graph that the sample size is small and can’t be used for broad generalizations.

It would be nice to always specify the sample size to let readers know the background data of the research. It would be nice if it would be possible automatically.

Thanks.

**Comment by ashishjain0512** [comment]
@dxcore35  Really good suggestion. I am working on this, and will make it driven by a configurable property **showData**, to render the actual data values after the legend text, so that users who can turn on/off as per their requirement.
