### ISSUE TITLE
Problem applying classes and styles to 'flowchart' elements

### ISSUE THREAD

**Issue by adel-belkhiri** [mermaid-js/mermaid#1657]
Hello guys,

I'm facing issues with modifying nodes and link styles using classes (classDef) and styles in a "flowchart" graph. I know this feature is still in beta version but I'm wondering if those issues will be fixed soon. 

When using "graph" graphs, these issues don't happen.

For example, when I write in the live editor :

flowchart TD

     hello --> world;
     classDef someclass fill:#f96;
     class hello someclass;

**Expected behavior**
The fill color of "hello" node change to Orange.

Any idea how to overcome this issue? Thank you.

**Comment by Kamaradeivanov** [comment]
Same problem for me.

**Comment by jucor** [comment]
Same here. Would be very helpful so we can update our flowcharts as nodes get "done" IRL :) Thanks for looking into it!

**Comment by sidharthv96** [comment]
```mermaid
flowchart TD
 hello --> world;
 classDef someclass fill:#f96;
 class hello someclass;
```

Working now.
