### ISSUE TITLE
Sequence diagram: unable to name participant "activate"

### ISSUE THREAD

**Issue by fulldecent** [mermaid-js/mermaid#1658]
**Describe the bug**
The code will fail to compile if a participant is named starting with "activate". This hurts me because I am diagramming how to interact with our server named activate.mybiz.tld.

**To Reproduce**

1. Create one diagram:

       sequenceDiagram
       A->>xactivate: X

2. Create a second diagram

       sequenceDiagram
       A->>activate: X

**Expected behavior**

Both should load.

**Expected behavior**

First loads, second crashes.

**Screenshots**

<img width="448" alt="Screen Shot 2020-09-01 at 23 43 10" src="https://user-images.githubusercontent.com/382183/91929681-f0ff1380-ecac-11ea-82f2-3f5f47d61016.png">
<img width="446" alt="Screen Shot 2020-09-01 at 23 43 18" src="https://user-images.githubusercontent.com/382183/91929682-f197aa00-ecac-11ea-85b0-525fe5ea95d2.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari 
 - Version 13.1.2 (15609.3.5.1.3)

**Comment by jgreywolf** [comment]
Unless I am missing something, activate cannot be used as the name of a node

**Comment by jgreywolf** [comment]
Closing due to lack of response/activity
