### ISSUE TITLE
Convert Mermaid code block in Markdown file to SVG

### ISSUE THREAD

**Issue by superj80820** [mermaid-js/mermaid#1663]
When Markdown on some platforms like Github does not support Mermaid, the power and convenience of Mermaid cannot be used.

So I often have to convert Mermaid in different tools. Ex. Use [mermaid-live-editor](https://mermaid-js.github.io/mermaid-live-editor/) to export PNG

This makes development a lot more `COPY/PASTE`.

---

So I wrote [mermaid-js-converter](https://github.com/superj80820/mermaid-js-converter), which can use command line to convert Mermaid code block strings in Markdown files to SVG.

![](https://i.imgur.com/Tkf5vim.gif)

[How to use](https://github.com/superj80820/mermaid-js-converter#how-to-use)

---

The code of this tool is very simple. I created this issue because I thought it might help people who have the same problem as me.

If Mermaid Author thinks this is a cool tool, I am very willing to contribute it.

Thank you.

**Comment by chaodaiG** [comment]
GitHub now supports mermaid: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

Note to anyone who is trying to use [mermaid-js-converter](https://github.com/superj80820/mermaid-js-converter), this tool publishes your diagram onto mermaid-live-editor, so use it with caution if your diagram contains info that you don't want to expose to the public yet

**Comment by snomos** [comment]
> GitHub now supports mermaid: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

As far as I have been able to find out, this support does not extend to GitHub Pages. Thus we still need services like the one mentioned in this issue. Or a simple GitHub Action that will do the conversion on the fly, and can be easily included in GH Pages workflows. None of the existing actions I have found fits that bill.

**Comment by msuzoagu** [comment]
As @snomos points out, this 
> GitHub now supports mermaid: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

but it appears that a [related issue from 2018](https://github.com/mermaid-js/mermaid/issues/772) is now on [ someone's radar at Github's parent company](https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/1081) so hopefully this issue can be resolved.

**Comment by jgreywolf** [comment]
Closing as this appears to be an information post
