### ISSUE TITLE
Minor : Typo in docs at assets/developer-docs/configuration

### ISSUE THREAD

**Issue by hareshkh** [mermaid-js/mermaid#1669]
**Describe the bug**
In the `assets/developer-docs/configuration` doc, under `Theme configuration`->`Initialize`, *called* is wrongly spelled as *calloed*. 

**To Reproduce**
Go to [link](https://mermaid-js.github.io/mermaid/assets/developer-docs/configuration.html?highlight=theme).

**Screenshots**
![image](https://user-images.githubusercontent.com/16576273/92585124-2d84cd80-f2b2-11ea-8c95-0339e1116a34.png)

**Comment by Lucurus** [comment]
@hareshkh Just FYI, the bug won't be fixed, as outlined in the pull request https://github.com/mermaid-js/mermaid/pull/1683#issuecomment-695780768 should you want to close the issue.
