### ISSUE TITLE
classDiagram "click" fails to parse

### ISSUE THREAD

**Issue by nclu** [mermaid-js/mermaid#1673]
**Describe the bug**
When creating a class in a classDiagram, the "click" behavior doesn't function

**To Reproduce**
1. Go to 'https://mermaid-js.github.io/mermaid-live-editor'
2. Click on 'classDiagram'
3. add content `click Duck "google.com"`

**Expected behavior**
The "Duck" class box should become a link to google

**Comment by jgreywolf** [comment]
it should be `link Duck "google.com"
