### ISSUE TITLE
Gitgraph cause infinite loop crash

### ISSUE THREAD

**Issue by Yukaii** [mermaid-js/mermaid#1677]
**Describe the bug**

Minimum reproducible snippet:

```
gitGraph:
options
{
    "nodeSpacing": 150,
    "nodeRadius": 10
}
end
commit
branch newbranch
checkout newbranch
commit
```

Adding a new line (Press enter) at the end of content causes the infinite loop.

**Expected behavior**

**Screenshots**

![mermaid-gitgraph](https://user-images.githubusercontent.com/4230968/92891286-6b1c5e80-f44a-11ea-8755-0ad906f5989c.gif)

(The cursor blinked at start, after I hit enter, it froze because of infinite loop)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: New Edge Brwoser
 - Version 58

**Smartphone (please complete the following information):**

**Additional context**

**Comment by knsv** [comment]
Thanks we are looking into gitgraph now. We will fix it up and add proper documentation to it. @ashishjain0512

**Comment by include** [comment]
miss this Gitgraph too.

**Comment by Miracle3310** [comment]
The code below (edited from [Introduction](https://mermaid-js.github.io/mermaid/#/?id=git-graph-exclamation-experimental)) caused CodiMD web page not to response so i had to kill the tab，and i could never open that markdown file again with CodiMD. My friend tested in Typora and got similar trouble.
```
gitGraph:
options
{
    "nodeSpacing": 150,
    "nodeRadius": 10
}
end
commit
branch sp
checkout newbranch
commit
commit
checkout master
commit
commit
merge newbranch
```

**Comment by laurent22** [comment]
Similar code also crashes Joplin - https://github.com/laurent22/joplin/issues/5295

**Comment by tessus** [comment]
@knsv any chance you could add a flag to the options to disable experimental features?

**Comment by ashishjain0512** [comment]
Newer verison of GitGraph solves this.
