### ISSUE TITLE
Run from NodeJS?

### ISSUE THREAD

**Issue by chaeron** [mermaid-js/mermaid#1680]
All the docs seem to imply you can only run mermaid in a browser.

Any way or plans to allow running it directly from NodeJS?

**Comment by chaeron** [comment]
Ping....

**Comment by artragis** [comment]
I'm also interrested by the answer

**Comment by sidharthv96** [comment]
We cannot do "proper" server rendering as our layout engines require a browser. 
However, you can render the diagram in a browser using puppeteer/playwright/etc using node and get the corresponding SVG/PNG. 

Refer to the https://github.com/mermaid-js/mermaid-cli project for examples.
