### ISSUE TITLE
Structurizr-generated mermaid diagram renders in live editor, but generates an error when I try to render it in an HTML file

### ISSUE THREAD

**Issue by malkav30** [mermaid-js/mermaid#1698]
**Describe the bug**
Structurizr-generated mermaid diagram renders in live editor, but generates an error when I try to render it in an HTML file. specifically, Structurizr generates a lot of inner html divs with style attributes, and the mermaid parser does not behave correctly when escaping the style parts. What bugs me is that it works perfectly inside the mermaid live editor, so I assume that it should work correctly when using the js library inside my own page.

**To Reproduce**
1. take a generated Structurizr example in mermaid markup (see [here](https://structurizr.com/dsl?src=https://raw.githubusercontent.com/structurizr/dsl/master/examples/big-bank-plc.dsl))
2. Go to [Live editor](https://mermaid-js.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVEJcbiAgbGlua1N0eWxlIGRlZmF1bHQgZmlsbDojZmZmZmZmXG4gIDE4WyhcIjxkaXYgc3R5bGU9J2ZvbnQtd2VpZ2h0OiBib2xkJz5EYXRhYmFzZTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlOyBtYXJnaW4tdG9wOiAwcHgnPltDb250YWluZXI6IE9yYWNsZSBEYXRhYmFzZSBTY2hlbWFdPC9kaXY-PGRpdiBzdHlsZT0nZm9udC1zaXplOiA4MCU7IG1hcmdpbi10b3A6MTBweCc-U3RvcmVzIHVzZXIgcmVnaXN0cmF0aW9uPGJyIC8-aW5mb3JtYXRpb24sIGhhc2hlZDxiciAvPmF1dGhlbnRpY2F0aW9uIGNyZWRlbnRpYWxzLDxiciAvPmFjY2VzcyBsb2dzLCBldGMuPC9kaXY-XCIpXVxuICBzdHlsZSAxOCBmaWxsOiM0MzhkZDUsc3Ryb2tlOiMyZTYyOTUsY29sb3I6I2ZmZmZmZlxuICA1W1wiPGRpdiBzdHlsZT0nZm9udC13ZWlnaHQ6IGJvbGQnPkUtbWFpbCBTeXN0ZW08L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJTsgbWFyZ2luLXRvcDogMHB4Jz5bU29mdHdhcmUgU3lzdGVtXTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogODAlOyBtYXJnaW4tdG9wOjEwcHgnPlRoZSBpbnRlcm5hbCBNaWNyb3NvZnQ8YnIgLz5FeGNoYW5nZSBlLW1haWwgc3lzdGVtPC9kaXY-XCJdXG4gIHN0eWxlIDUgZmlsbDojOTk5OTk5LHN0cm9rZTojNmI2YjZiLGNvbG9yOiNmZmZmZmZcbiAgNFtcIjxkaXYgc3R5bGU9J2ZvbnQtd2VpZ2h0OiBib2xkJz5NYWluZnJhbWUgQmFua2luZyBTeXN0ZW08L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJTsgbWFyZ2luLXRvcDogMHB4Jz5bU29mdHdhcmUgU3lzdGVtXTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogODAlOyBtYXJnaW4tdG9wOjEwcHgnPlN0b3JlcyBhbGwgb2YgdGhlIGNvcmU8YnIgLz5iYW5raW5nIGluZm9ybWF0aW9uIGFib3V0PGJyIC8-Y3VzdG9tZXJzLCBhY2NvdW50cyw8YnIgLz50cmFuc2FjdGlvbnMsIGV0Yy48L2Rpdj5cIl1cbiAgc3R5bGUgNCBmaWxsOiM5OTk5OTksc3Ryb2tlOiM2YjZiNmIsY29sb3I6I2ZmZmZmZlxuICA5W1wiPGRpdiBzdHlsZT0nZm9udC13ZWlnaHQ6IGJvbGQnPk1vYmlsZSBBcHA8L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJTsgbWFyZ2luLXRvcDogMHB4Jz5bQ29udGFpbmVyOiBYYW1hcmluXTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogODAlOyBtYXJnaW4tdG9wOjEwcHgnPlByb3ZpZGVzIGEgbGltaXRlZCBzdWJzZXQgb2Y8YnIgLz50aGUgSW50ZXJuZXQgYmFua2luZzxiciAvPmZ1bmN0aW9uYWxpdHkgdG8gY3VzdG9tZXJzPGJyIC8-dmlhIHRoZWlyIG1vYmlsZSBkZXZpY2UuPC9kaXY-XCJdXG4gIHN0eWxlIDkgZmlsbDojNDM4ZGQ1LHN0cm9rZTojMmU2Mjk1LGNvbG9yOiNmZmZmZmZcbiAgOFtcIjxkaXYgc3R5bGU9J2ZvbnQtd2VpZ2h0OiBib2xkJz5TaW5nbGUtUGFnZSBBcHBsaWNhdGlvbjwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlOyBtYXJnaW4tdG9wOiAwcHgnPltDb250YWluZXI6IEphdmFTY3JpcHQgYW5kIEFuZ3VsYXJdPC9kaXY-PGRpdiBzdHlsZT0nZm9udC1zaXplOiA4MCU7IG1hcmdpbi10b3A6MTBweCc-UHJvdmlkZXMgYWxsIG9mIHRoZSBJbnRlcm5ldDxiciAvPmJhbmtpbmcgZnVuY3Rpb25hbGl0eSB0bzxiciAvPmN1c3RvbWVycyB2aWEgdGhlaXIgd2ViPGJyIC8-YnJvd3Nlci48L2Rpdj5cIl1cbiAgc3R5bGUgOCBmaWxsOiM0MzhkZDUsc3Ryb2tlOiMyZTYyOTUsY29sb3I6I2ZmZmZmZlxuICBzdWJncmFwaCBib3VuZGFyeSBbQVBJIEFwcGxpY2F0aW9uXVxuICAgIDEzW1wiPGRpdiBzdHlsZT0nZm9udC13ZWlnaHQ6IGJvbGQnPkFjY291bnRzIFN1bW1hcnkgQ29udHJvbGxlcjwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlOyBtYXJnaW4tdG9wOiAwcHgnPltDb21wb25lbnQ6IFNwcmluZyBNVkMgUmVzdCBDb250cm9sbGVyXTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogODAlOyBtYXJnaW4tdG9wOjEwcHgnPlByb3ZpZGVzIGN1c3RvbWVycyB3aXRoIGE8YnIgLz5zdW1tYXJ5IG9mIHRoZWlyIGJhbms8YnIgLz5hY2NvdW50cy48L2Rpdj5cIl1cbiAgICBzdHlsZSAxMyBmaWxsOiM4NWJiZjAsc3Ryb2tlOiM1ZDgyYTgsY29sb3I6IzAwMDAwMFxuICAgIDE3W1wiPGRpdiBzdHlsZT0nZm9udC13ZWlnaHQ6IGJvbGQnPkUtbWFpbCBDb21wb25lbnQ8L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJTsgbWFyZ2luLXRvcDogMHB4Jz5bQ29tcG9uZW50OiBTcHJpbmcgQmVhbl08L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDgwJTsgbWFyZ2luLXRvcDoxMHB4Jz5TZW5kcyBlLW1haWxzIHRvIHVzZXJzLjwvZGl2PlwiXVxuICAgIHN0eWxlIDE3IGZpbGw6Izg1YmJmMCxzdHJva2U6IzVkODJhOCxjb2xvcjojMDAwMDAwXG4gICAgMTZbXCI8ZGl2IHN0eWxlPSdmb250LXdlaWdodDogYm9sZCc-TWFpbmZyYW1lIEJhbmtpbmcgU3lzdGVtIEZhY2FkZTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlOyBtYXJnaW4tdG9wOiAwcHgnPltDb21wb25lbnQ6IFNwcmluZyBCZWFuXTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogODAlOyBtYXJnaW4tdG9wOjEwcHgnPkEgZmFjYWRlIG9udG8gdGhlIG1haW5mcmFtZTxiciAvPmJhbmtpbmcgc3lzdGVtLjwvZGl2PlwiXVxuICAgIHN0eWxlIDE2IGZpbGw6Izg1YmJmMCxzdHJva2U6IzVkODJhOCxjb2xvcjojMDAwMDAwXG4gICAgMTRbXCI8ZGl2IHN0eWxlPSdmb250LXdlaWdodDogYm9sZCc-UmVzZXQgUGFzc3dvcmQgQ29udHJvbGxlcjwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlOyBtYXJnaW4tdG9wOiAwcHgnPltDb21wb25lbnQ6IFNwcmluZyBNVkMgUmVzdCBDb250cm9sbGVyXTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogODAlOyBtYXJnaW4tdG9wOjEwcHgnPkFsbG93cyB1c2VycyB0byByZXNldCB0aGVpcjxiciAvPnBhc3N3b3JkcyB3aXRoIGEgc2luZ2xlIHVzZTxiciAvPlVSTC48L2Rpdj5cIl1cbiAgICBzdHlsZSAxNCBmaWxsOiM4NWJiZjAsc3Ryb2tlOiM1ZDgyYTgsY29sb3I6IzAwMDAwMFxuICAgIDE1W1wiPGRpdiBzdHlsZT0nZm9udC13ZWlnaHQ6IGJvbGQnPlNlY3VyaXR5IENvbXBvbmVudDwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlOyBtYXJnaW4tdG9wOiAwcHgnPltDb21wb25lbnQ6IFNwcmluZyBCZWFuXTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogODAlOyBtYXJnaW4tdG9wOjEwcHgnPlByb3ZpZGVzIGZ1bmN0aW9uYWxpdHk8YnIgLz5yZWxhdGVkIHRvIHNpZ25pbmcgaW4sPGJyIC8-Y2hhbmdpbmcgcGFzc3dvcmRzLCBldGMuPC9kaXY-XCJdXG4gICAgc3R5bGUgMTUgZmlsbDojODViYmYwLHN0cm9rZTojNWQ4MmE4LGNvbG9yOiMwMDAwMDBcbiAgICAxMltcIjxkaXYgc3R5bGU9J2ZvbnQtd2VpZ2h0OiBib2xkJz5TaWduIEluIENvbnRyb2xsZXI8L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJTsgbWFyZ2luLXRvcDogMHB4Jz5bQ29tcG9uZW50OiBTcHJpbmcgTVZDIFJlc3QgQ29udHJvbGxlcl08L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDgwJTsgbWFyZ2luLXRvcDoxMHB4Jz5BbGxvd3MgdXNlcnMgdG8gc2lnbiBpbiB0bzxiciAvPnRoZSBJbnRlcm5ldCBCYW5raW5nIFN5c3RlbS48L2Rpdj5cIl1cbiAgICBzdHlsZSAxMiBmaWxsOiM4NWJiZjAsc3Ryb2tlOiM1ZDgyYTgsY29sb3I6IzAwMDAwMFxuICBlbmRcbiAgc3R5bGUgYm91bmRhcnkgZmlsbDojZmZmZmZmLHN0cm9rZTojMDAwMDAwLGNvbG9yOiMwMDAwMDBcbiAgMTMtLiBcIjxkaXY-VXNlczwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlJz48L2Rpdj5cIiAuLT4xNlxuICAxNy0uIFwiPGRpdj5TZW5kcyBlLW1haWwgdXNpbmc8L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJSc-PC9kaXY-XCIgLi0-NVxuICAxNi0uIFwiPGRpdj5NYWtlcyBBUEkgY2FsbHMgdG88L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJSc-W1hNTC9IVFRQU108L2Rpdj5cIiAuLT40XG4gIDktLiBcIjxkaXY-TWFrZXMgQVBJIGNhbGxzIHRvPC9kaXY-PGRpdiBzdHlsZT0nZm9udC1zaXplOiA3MCUnPltKU09OL0hUVFBTXTwvZGl2PlwiIC4tPjEzXG4gIDktLiBcIjxkaXY-TWFrZXMgQVBJIGNhbGxzIHRvPC9kaXY-PGRpdiBzdHlsZT0nZm9udC1zaXplOiA3MCUnPltKU09OL0hUVFBTXTwvZGl2PlwiIC4tPjE0XG4gIDktLiBcIjxkaXY-TWFrZXMgQVBJIGNhbGxzIHRvPC9kaXY-PGRpdiBzdHlsZT0nZm9udC1zaXplOiA3MCUnPltKU09OL0hUVFBTXTwvZGl2PlwiIC4tPjEyXG4gIDE0LS4gXCI8ZGl2PlVzZXM8L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJSc-PC9kaXY-XCIgLi0-MTdcbiAgMTQtLiBcIjxkaXY-VXNlczwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlJz48L2Rpdj5cIiAuLT4xNVxuICAxNS0uIFwiPGRpdj5SZWFkcyBmcm9tIGFuZCB3cml0ZXMgdG88L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJSc-W0pEQkNdPC9kaXY-XCIgLi0-MThcbiAgMTItLiBcIjxkaXY-VXNlczwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlJz48L2Rpdj5cIiAuLT4xNVxuICA4LS4gXCI8ZGl2Pk1ha2VzIEFQSSBjYWxscyB0bzwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlJz5bSlNPTi9IVFRQU108L2Rpdj5cIiAuLT4xM1xuICA4LS4gXCI8ZGl2Pk1ha2VzIEFQSSBjYWxscyB0bzwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlJz5bSlNPTi9IVFRQU108L2Rpdj5cIiAuLT4xNFxuICA4LS4gXCI8ZGl2Pk1ha2VzIEFQSSBjYWxscyB0bzwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlJz5bSlNPTi9IVFRQU108L2Rpdj5cIiAuLT4xMlxuXG5cdFx0IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQiLCJ0aGVtZVZhcmlhYmxlcyI6eyJiYWNrZ3JvdW5kIjoid2hpdGUiLCJwcmltYXJ5Q29sb3IiOiIjRUNFQ0ZGIiwic2Vjb25kYXJ5Q29sb3IiOiIjZmZmZmRlIiwidGVydGlhcnlDb2xvciI6ImhzbCg4MCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwicHJpbWFyeUJvcmRlckNvbG9yIjoiaHNsKDI0MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJzZWNvbmRhcnlCb3JkZXJDb2xvciI6ImhzbCg2MCwgNjAlLCA4My41Mjk0MTE3NjQ3JSkiLCJ0ZXJ0aWFyeUJvcmRlckNvbG9yIjoiaHNsKDgwLCA2MCUsIDg2LjI3NDUwOTgwMzklKSIsInByaW1hcnlUZXh0Q29sb3IiOiIjMTMxMzAwIiwic2Vjb25kYXJ5VGV4dENvbG9yIjoiIzAwMDAyMSIsInRlcnRpYXJ5VGV4dENvbG9yIjoicmdiKDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxLCA5LjUwMDAwMDAwMDEpIiwibGluZUNvbG9yIjoiIzMzMzMzMyIsInRleHRDb2xvciI6IiMzMzMiLCJtYWluQmtnIjoiI0VDRUNGRiIsInNlY29uZEJrZyI6IiNmZmZmZGUiLCJib3JkZXIxIjoiIzkzNzBEQiIsImJvcmRlcjIiOiIjYWFhYTMzIiwiYXJyb3doZWFkQ29sb3IiOiIjMzMzMzMzIiwiZm9udEZhbWlseSI6IlwidHJlYnVjaGV0IG1zXCIsIHZlcmRhbmEsIGFyaWFsIiwiZm9udFNpemUiOiIxNnB4IiwibGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsIm5vZGVCa2ciOiIjRUNFQ0ZGIiwibm9kZUJvcmRlciI6IiM5MzcwREIiLCJjbHVzdGVyQmtnIjoiI2ZmZmZkZSIsImNsdXN0ZXJCb3JkZXIiOiIjYWFhYTMzIiwiZGVmYXVsdExpbmtDb2xvciI6IiMzMzMzMzMiLCJ0aXRsZUNvbG9yIjoiIzMzMyIsImVkZ2VMYWJlbEJhY2tncm91bmQiOiIjZThlOGU4IiwiYWN0b3JCb3JkZXIiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJhY3RvckJrZyI6IiNFQ0VDRkYiLCJhY3RvclRleHRDb2xvciI6ImJsYWNrIiwiYWN0b3JMaW5lQ29sb3IiOiJncmV5Iiwic2lnbmFsQ29sb3IiOiIjMzMzIiwic2lnbmFsVGV4dENvbG9yIjoiIzMzMyIsImxhYmVsQm94QmtnQ29sb3IiOiIjRUNFQ0ZGIiwibGFiZWxCb3hCb3JkZXJDb2xvciI6ImhzbCgyNTkuNjI2MTY4MjI0MywgNTkuNzc2NTM2MzEyOCUsIDg3LjkwMTk2MDc4NDMlKSIsImxhYmVsVGV4dENvbG9yIjoiYmxhY2siLCJsb29wVGV4dENvbG9yIjoiYmxhY2siLCJub3RlQm9yZGVyQ29sb3IiOiIjYWFhYTMzIiwibm90ZUJrZ0NvbG9yIjoiI2ZmZjVhZCIsIm5vdGVUZXh0Q29sb3IiOiJibGFjayIsImFjdGl2YXRpb25Cb3JkZXJDb2xvciI6IiM2NjYiLCJhY3RpdmF0aW9uQmtnQ29sb3IiOiIjZjRmNGY0Iiwic2VxdWVuY2VOdW1iZXJDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yIjoicmdiYSgxMDIsIDEwMiwgMjU1LCAwLjQ5KSIsImFsdFNlY3Rpb25Ca2dDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yMiI6IiNmZmY0MDAiLCJ0YXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwidGFza0JrZ0NvbG9yIjoiIzhhOTBkZCIsInRhc2tUZXh0TGlnaHRDb2xvciI6IndoaXRlIiwidGFza1RleHRDb2xvciI6IndoaXRlIiwidGFza1RleHREYXJrQ29sb3IiOiJibGFjayIsInRhc2tUZXh0T3V0c2lkZUNvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dENsaWNrYWJsZUNvbG9yIjoiIzAwMzE2MyIsImFjdGl2ZVRhc2tCb3JkZXJDb2xvciI6IiM1MzRmYmMiLCJhY3RpdmVUYXNrQmtnQ29sb3IiOiIjYmZjN2ZmIiwiZ3JpZENvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCa2dDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQm9yZGVyQ29sb3IiOiJncmV5IiwiY3JpdEJvcmRlckNvbG9yIjoiI2ZmODg4OCIsImNyaXRCa2dDb2xvciI6InJlZCIsInRvZGF5TGluZUNvbG9yIjoicmVkIiwibGFiZWxDb2xvciI6ImJsYWNrIiwiZXJyb3JCa2dDb2xvciI6IiM1NTIyMjIiLCJlcnJvclRleHRDb2xvciI6IiM1NTIyMjIiLCJjbGFzc1RleHQiOiIjMTMxMzAwIiwiZmlsbFR5cGUwIjoiI0VDRUNGRiIsImZpbGxUeXBlMSI6IiNmZmZmZGUiLCJmaWxsVHlwZTIiOiJoc2woMzA0LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTMiOiJoc2woMTI0LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTQiOiJoc2woMTc2LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTUiOiJoc2woLTQsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSIsImZpbGxUeXBlNiI6ImhzbCg4LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTciOiJoc2woMTg4LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkifX19)
3. see that it renders correctly
4. put the same content in an html file (see index.zip)
5. an error is generated in console

**Expected behavior**
Same graph is rendered from
[index.zip](https://github.com/mermaid-js/mermaid/files/5274839/index.zip)

**Screenshots**
console error : 
![image](https://user-images.githubusercontent.com/9546533/94126756-4b2c6800-fe58-11ea-95f5-2898be3e4890.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - chrome 85.0.4183.102
 - Version 8.8.0

**Comment by trimmurrti** [comment]
Seems, you are using old mmdc version.

if you run mmdc --version and it shows 0.5.1, then just do npm install -g --force @mermaid-js/mermaid-cli
