### ISSUE TITLE
Node Label text mistaken for Direction

### ISSUE THREAD

**Issue by morganrallen** [mermaid-js/mermaid#17]
```
Uncaught Error: Parse error on line 2:
graph TD;      A[URL]-->|Link text|B(R
------------------^
Expecting 'SPACE', 'SQE', 'PE', 'DIAMOND_STOP', 'TAGEND', 'TAGSTART', 'MINUS',
'ALPHA', 'NUM', 'COLON', 'COMMA', 'PLUS', 'EQUALS',
'MULT', 'DOT', 'BRKT', 'PIPE', got 'DIR'
```

Here is it mistaking `RL` in `URL` as right-left direction.

**Comment by huberta2** [comment]
graph TD
    subgraph Interface Utilisateur
        Teams[**Microsoft Teams**] -->|1. Saisie utilisateur (requête/commande)| Apigee_Teams_API[**Apigee API Proxy for Teams**<br/>(Endpoint d'entrée)]
    end

    subgraph API Management Layer
        Apigee_Teams_API -->|2. Requête proxy<br/>(Sécurité, Quotas)| Apigee[**Google Apigee**<br/>(Passerelle API Principale)]
        Apigee -->|3. Route vers Agent IA<br/>(Policies Appliquées)| Agent_IA_Service[**Agent IA Core Logic**<br/>(NLU, LLM Orchestration, Logique Métier)]
        Agent_IA_Service -->|4. Appels API internes (via Apigee)| Apigee
    end

    subgraph Backend Systems / Data Sources
        Apigee -->|5. Route vers Backend<br/>(Appels API sécurisés)| Backend_CRM[CRM (ex: Salesforce)]
        Apigee -->|5. Route vers Backend<br/>(Appels API sécurisés)| Backend_ERP[ERP (ex: SAP)]
        Apigee -->|5. Route vers Backend<br/>(Appels API sécurisés)| Backend_DB[Bases de Données<br/>(SQL, NoSQL)]
        Apigee -->|5. Route vers Backend<br/>(Appels API sécurisés)| Backend_Microservices[Microservices Internes]
        Apigee -->|5. Route vers Backend<br/>(Appels API sécurisés)| Jira[**Jira**<br/>(Système de suivi des tickets)]
        Apigee -->|5. Route vers Backend<br/>(Appels API sécurisés)| Backend_Other[Autres Systèmes Tiers / Hérités]
    end

    %% Flèches bidirectionnelles pour les réponses
    Backend_CRM -->|6. Réponse Backend| Apigee
    Backend_ERP -->|6. Réponse Backend| Apigee
    Backend_DB -->|6. Réponse Backend| Apigee
    Backend_Microservices -->|6. Réponse Backend| Apigee
    Jira -->|6. Réponse Backend| Apigee
     Backend_Other -->|6. Réponse Backend| Apigee

    Apigee -->|7. Réponse Agent IA<br/>(via proxy interne)| Agent_IA_Service
    Agent_IA_Service -->|8. Réponse Agent IA<br/>(via Apigee)| Apigee_Teams_API
    Apigee_Teams_API -->|9. Afficher la Réponse| Teams

    style Teams fill:#A8C8ED,stroke:#333,stroke-width:2px
    style Apigee_Teams_API fill:#FFD700,stroke:#333,stroke-width:2px
    style Apigee fill:#FFD700,stroke:#333,stroke-width:2px
    style Agent_IA_Service fill:#C7E7C8,stroke:#333,stroke-width:2px
    style Jira fill:#F5D8A8,stroke:#333,stroke-width:2px
    style Backend_CRM fill:#F5D8A8,stroke:#333,stroke-width:2px
    style Backend_ERP fill:#F5D8A8,stroke:#333,stroke-width:2px
    style Backend_DB fill:#F5D8A8,stroke:#333,stroke-width:2px
    style Backend_Microservices fill:#F5D8A8,stroke:#333,stroke-width:2px
    style Backend_Other fill:#F5D8A8,stroke:#333,stroke-width:2p
