### ISSUE TITLE
Is there a way to set the Flowchart aspect ratio?

### ISSUE THREAD

**Issue by mullinmax** [mermaid-js/mermaid#1702]
I'm trying to build a large flowchart and it's getting hard to read. the layout seems to be trying to keep an aspect ratio of 1:1. Is there a way to tell Mermaid I don't mind scrolling? I've attached a censored version (it's for work) of the flow chart for reference. as you can see the sub-graphs near the bottom left could easily be at the bottom and would likely make the chart more sensible anyway.

Here's a censored version of the chart I'm making(it's for my job). Basically I want to be able to tell the layout algorithm that it has as much vertical space as it wants. If I need to do some sort of hack-y CSS trick or something that's fine. 
![image](https://user-images.githubusercontent.com/14000345/94822594-d36aba00-03d0-11eb-826e-1c711f057f1c.png)

**Comment by JMeyer126** [comment]
@mullinmax hi, have you found a way to make your large flowchart scrollable? I have the same issue after upgrading from 8.8.0 to 8.8.2.
The following config entry works in the Mermaid Live Editor, but not in my existing code..
 "flowchart": {
    "useMaxWidth": false
  }

**Comment by mullinmax** [comment]
Hmm i will try that out.

**Comment by jgreywolf** [comment]
@mullinmax Have you been able to follow the suggestion from JMeyer126?
