### ISSUE TITLE
Gantt as event timeline

### ISSUE THREAD

**Issue by Giohn** [mermaid-js/mermaid#1708]
I was trying to use the Gantt diagram to create an event timeline diagram.  I think a few extras would really make this a nice format to do this in. Here are my suggestions that would help me make the diagram I would like:

1.  Relative (to the start) time, instead of an absolute date. 
Here the time formats would be the format of the time units from the start time. I think this CAN be done at the moment but I mention it because I recognize the use case is different.

2. Tasks that can be split along the same row and have sub-task labels. The same event or event type can re-occur drawn on the same row:
Something like: 
```gantt
    title A Gantt Diagram
    dateFormat  ss-SSS
    axisFormat  %S.%L
    section Section
    A task           :a1, 00-000 ...
        subtask1        :s1, 01-000, 00-200
        subtask2        :s2, 01-800, 00-200

    Another task     :after a1  , 03-000
``` 
The times in the subtasks could be time from end of last subtask and duration, or perhaps time and duration the same as the task.

3. Tasks/Events that don't need to have a duration and can be a point in time represented by a dot or a circle or line etc.

Thanks for taking the time to look (I realise this may be a new type of chart but this was my thinking so far) :-)

**Comment by Giohn** [comment]
... Just realized that with relative time an a choice of units that the most significant unit has to keep increasing in the timeline. So for example if the most significant unit was seconds then I should be able to input ad view data at 123 seconds (i.e. > 59)

**Comment by arnoldad** [comment]
I second your suggestion 2 (Subtasks split on a single line) This would make the gantt diagram format much better suited to describing more complex sequences of tasks.

**Comment by sidharthv96** [comment]
Please have a look at the newly introduced Timeline Diagram: https://mermaid.js.org/syntax/timeline.html

---
_This issue was closed by a human, not a bot. Please re-open if necessary._

**Comment by Unknow0059** [comment]
In my opinion, Gantt mode is simply better than the Timeline for displaying events.
If only it supported multiple tasks in the same row, it would be perfect.
There's a Block (Beta) mode which comes pretty close to being perfect, but it doesn't have the timeline/date positioning.

**Comment by lee-treehouse** [comment]
@Unknow0059 you might be interested in the compact mode of a gantt https://mermaid.js.org/syntax/gantt.html#output-in-compact-mode
