### ISSUE TITLE
Allow git graph commit id to be defined by users also, if undefined then default to randon number generator

### ISSUE THREAD

**Issue by ashishjain0512** [mermaid-js/mermaid#1713]
Epic: #1252

**Comment by gjoseph** [comment]
FWIW, I'd love got commit hashes in gitGraph to be _semi-random_: auto-generated, but stable, such that I can re-generate the same graph multiple times and keep the same hashes. I often find myself graphing examples of git interactions, and taking snapshots as I go, while documenting steps of the process. It's not ideal that each step shows completely different hashes, eventhough my example is trying to convey they're the same ;)
That said, if I have to manually type a random 8 chars hex string... I suppose it's not too bad ;) -- while on this though it could be nice to be able to label commits (both to represent git tags _and_ the contents of a commit/message)

**Comment by t0ny-peng** [comment]
@gjoseph I second your proposal. Mermaid could utilize some `Deterministic random bit generator` to achieve the fixed(but still looks random) commit hash by giving a seed before the first commit message. In addition, it'll be super nice if the seed could be reset in the middle of commits to get more flexibility.

**Comment by suy** [comment]
I don't understand why this isn't working, given that `gitGraphParser.spec` has:

```js
  it('should handle commit with args', function() {
    const str = 'gitGraph:\n' + 'commit "a commit"\n';

    parser.parse(str);
    const commits = parser.yy.getCommits();

    expect(Object.keys(commits).length).toBe(1);
    const key = Object.keys(commits)[0];
    expect(commits[key].message).toBe('a commit');
    expect(parser.yy.getCurrentBranch()).toBe('master');
  });
  ```

And `gitGraphRenderer.js` contains:

```js
      if (commit.message !== '' && direction === 'BT') {
        svg
          .select('#node-' + commit.id + ' p')
          .append('xhtml:span')
          .attr('class', 'commit-msg')
          .text(', ' + commit.message);
      }
```

I'm not familiar with the code base at all. I just tried something in the live editor, and I saw it not failing to render, but not showing the message either. So I delved a bit on the code, and I've been surprised by this. I don't get why it doesn't work when it seems implemented (to me as a casual observer nonetheless :) ).

**Comment by Yash-Singh1** [comment]
The newer renderer now supports this: #1252.
