### ISSUE TITLE
Support for Options via directives

### ISSUE THREAD

**Issue by ashishjain0512** [mermaid-js/mermaid#1717]
Support for various options for a git graph via directives as in flowcharts. The options are:

- Boolean to control show/hide commit id's 

- Boolean to control show/hide arrows

- color settings

Epic: #1252

**Comment by jgreywolf** [comment]
@ashishjain0512 Are you working on this issue?  I noticed that you marked it as approved, but it has sat since.  Also, what is this a sub task of?

**Comment by sidharthv96** [comment]
All configs are now supported using the yaml frontmatter using the `config` key. 
Directives are deprecated now.
