### ISSUE TITLE
Font awesome not working anymore in link texts

### ISSUE THREAD

**Issue by giovdi** [mermaid-js/mermaid#1724]
**Describe the bug**
Font awesome glyphs are not shown anymore in link texts

I'm using the min.js script and the current config is:
```
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>
	var config = {
		startOnLoad: true,
		flowchart: {
			diagramPadding: 0,
		},
	};
	mermaid.initialize(config);
</script>
```

but the issue seems not related to a specific platform.

**To Reproduce**
Use the following schema in the live editor:
```
graph LR
  A-->|"fa:fa-envelope"| B
```
Live editor: [link](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgQS0tPnxcImZhOmZhLWVudmVsb3BlXCJ8IEJcblx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

**Expected behavior**
The envelope icon in the link

**Desktop**
 - OS: Win10
 - Browser: Chrome
 - Version: 85.0.4183.121

**Additional context**
Related bug #546

**Comment by knsv** [comment]
Very odd, I cant find any traces of this for edge labels, only for vertices. I have added it (again?) for labels.

In flowchart it works already though.
```
flowchart LR
  A-->|"fa:fa-envelope"| B
```

After next release it will be available in graph also.
