### ISSUE TITLE
Console log in release

### ISSUE THREAD

**Issue by lishid** [mermaid-js/mermaid#1742]
**Describe the bug**

Some console logging seemed to be introduced in the release.
To repro, open developer console on this page: https://mermaid-js.github.io/mermaid/getting-started/theming.html

A quick search seems to indicate this line:
https://github.com/mermaid-js/mermaid/blob/4c849554da8bfed3a3f96c5838da8db30f6f464f/src/diagrams/flowchart/flowDb.js#L456

**Comment by silverwind** [comment]
There s a [eslint rule](https://eslint.org/docs/rules/no-console) for that.

**Comment by GDFaber** [comment]
Thanks @lishid, the logger will take care of it. I'll set the message on "info" logging (will only be logged when setting the log level to 1 or 2).

**Comment by lishid** [comment]
Great, that should work. Thanks! @GDFaber
