### ISSUE TITLE
Support new line or <br> in class diagram

### ISSUE THREAD

**Issue by distkeys** [mermaid-js/mermaid#1745]
Currently when I write method names especially for objective-c methods which could be long in name there is no way to break those in multiple lines

1. Request is to support newline or <br> in classdiagram
2. Is there anyway to align the newline?

**Comment by maksimdrachov** [comment]
```
classDiagram
    DuOamBaseMsgHandler : # uint8_t m_phyId
    DuOamBaseMsgHandler : # string m_moduleName
    DuOamBaseMsgHandler : # weak_ptr m_ptrDuPlaneDataStore
    DuOamBaseMsgHandler : # shared_ptr m_ptrDataTree
    DuOamBaseMsgHandler : # int32_t m_initStatus
    DuOamBaseMsgHandler: + virtual ~DuOamBaseMsgHandler()
    DuOamBaseMsgHandler: + someFunction()
    DuOamBaseMsgHandler: + DuOamBaseMsgHandler(const uint8_t& ccId, \n const string_view moduleName, \n weak_ptr ptrDuMplaneDataStore)
    DuOamBaseMsgHandler: + someFunction()
```

Results in this:

![mermaid-diagram-2022-09-16-125923](https://user-images.githubusercontent.com/39975120/190613707-65ab5624-f34c-4a44-ac7a-5435009a4a95.png)

**Comment by jgreywolf** [comment]
newline (\n) is currently supported for class diagrams
