### ISSUE TITLE
State Diagram how to implements internal conversion? (状态图如何实现内部转换？)

### ISSUE THREAD

**Issue by xixifeng** [mermaid-js/mermaid#1752]
State Diagram how to implements internal conversion? 
状态图如何实现内部转换？

for example：
举例：
![](https://images.cnblogs.com/cnblogs_com/TerryFeng/WindowsLiveWriter/UML_E4FF/image_thumb_2.png)

**Comment by hikerpig** [comment]
Seems like your example link or image is broken ?
