### ISSUE TITLE
Huge white margins on img/png output of large diagrams

### ISSUE THREAD

**Issue by galtenberg** [mermaid-js/mermaid#1758]
PNG output of non-trivial diagrams has huge top/bottom margin

**Screenshots**
<img width="1920" alt="Mermaid img output" src="https://user-images.githubusercontent.com/97950/98422570-dc3e5380-2040-11eb-8cb7-e75a86ee4ac2.png">

**Comment by ambrt** [comment]
I noticed that such margins appear when `.mermaid` element is set to `width:100%`.
When forcing 200% `.mermaid {width:200% !important}`huge top margin goes away.

**Comment by hicksjacobp** [comment]
I found that by setting `useMaxWidth` to `false` also removes the top and bottom margins. By default it is set to `true`. See <https://mermaid-js.github.io/mermaid/#/Setup?id=mermaidapi-configuration-defaults>.

**Comment by jkamenik** [comment]
For me the the CSS trick didn't work.  But the `useMaxWidth` did.  The doc is confusing written so I wasn't sure where I needed to put the config.  But I finally figured out it was in the chart options.

```json
{
    "theme": "default",

    "logLevel": "debug",

    "securityLevel": "loose",

    "flowchart": {
        "htmlLabels": true,
        "curve": "basis",
        "useMaxWidth": false
    }
}
```

**Comment by axilleas** [comment]
Since mermaid 8.6.0, you can use [directives](https://mermaid-js.github.io/mermaid/#/8.6.0_docs?id=init) straight into the diagram. For this particular case, I used:

```mermaid
%%{init: {"flowchart": { "useMaxWidth": false } }}%%
graph LR
...
```

**Comment by jonatanklosko** [comment]
@phoerious solution works for flowcharts, however it doesn't for sequence diagrams, because the first `<g>` element has 0 height. However, what worked for us was removing the height attribute altogether.
