### ISSUE TITLE
Fonts specified in rendered svg are Microsoft-specific with no graceful fallbacks

### ISSUE THREAD

**Issue by frederikfab** [mermaid-js/mermaid#1767]
**Describe the bug**
Fonts specified in rendered svg are Microsoft-specific with no graceful fallbacks. From the svg-the fonts are specified as:
`"trebuchet ms",verdana,arial`, none of which have a graceful fallback if those fonts are missing. E.g. when using librsvg to convert the file, no text is being rendered.

**To Reproduce**
Render a diagram without no style specifications (only default styles then apply). Fonts are specified as `"trebuchet ms",verdana,arial`

**Expected behavior**
A default font of sans-serif should be specified, and also two opinionated choices should be added for other platforms.

**Additional context**
Rendering this in Visual Studio Code mermaid preview for markdown - let me know if it is not caused by this project, but needs to be solved downstream.

**Comment by knsv** [comment]
I am open for better defaults, what would you propose? I though these where websafe as per https://www.w3schools.com/cssref/css_websafe_fonts.asp

But as you have issues with this using librsvg we should get better defaults. Meanwhile if you are intregrating mermaid yourself it is possible to set another font in the initialize call:
```
      mermaid.initialize({
        fontFamily: 'courier'
      });
```

**Comment by frederikfab** [comment]
A default of `"trebuchet ms",verdana,arial,sans-serif` will let whatever platform or library fall back to an available sans-serif font 👍

**Comment by GDFaber** [comment]
Perfect, so we can add `sans-serif` to our standard settings. Thank you for elaborating on this.
