### ISSUE TITLE
Github can't display Class Diagram

### ISSUE THREAD

**Issue by wprzadka** [mermaid-js/mermaid#1770]
**Describe the bug**
Sometimes `Github` can't display `Class Diagram` from url copied to `README.md`

**To Reproduce**
1. Go to [Mermaid Live Editor - with class diagram code](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gIERiQ29ubmVjdG9yIC0tIFN5bmNocm9uaXplclxuICBEYkNvbm5lY3RvciA8fC0tIFJldGhpbmtEYkFkYXB0ZXJcbiAgRGJDb25uZWN0b3IgPHwtLSBTUUxpdGVcbiAgRGJDb25uZWN0b3IgLS0gVGFza1xuICBTeW5jaHJvbml6ZXIgLS0gUGFyc2VyXG4gIFN5bmNocm9uaXplciAtLSBDb25uZWN0aW9uXG4gIFN5bmNocm9uaXplciAtLSBNYW5hZ2VyQXBwXG4gIFZpZXdDb21wb25lbnQgPHwtLSBUYXNrXG4gIFRhc2sgKi0tIFN0YXRlXG4gIFRhc2sgLS0gVGFza0l0ZXJhdG9yXG4gIFRhc2sgPHwtLSBTdWJUYXNrXG4gIFZpZXdDb21wb25lbnRJdGVyYXRvciAtLSBGaWx0ZXJcbiAgVGFza0l0ZXJhdG9yIC0tIFN5bmNocm9uaXplclxuICBGaWx0ZXIgLS0gTWFuYWdlckFwcFxuICBWaWV3Q29tcG9uZW50IC0tIFZpZXdDb21wb25lbnRJdGVyYXRvclxuICBWaWV3Q29tcG9uZW50IDx8LS0gRGVmYXVsdFRhc2tWaWV3RGVjb3JhdG9yXG4gIFZpZXdDb21wb25lbnQgPHwtLSBCb3JkZXJUYXNrVmlld0RlY29yYXRvclxuICBWaWV3Q29tcG9uZW50IDx8LS0gRWRpdG9yVGFza1ZpZXdEZWNvcmF0b3JcbiAgVmlld0NvbXBvbmVudEl0ZXJhdG9yIC0tKiBNYW5hZ2VyQXBwXG4gIE1hbmFnZXJBcHAgPHwtLSBVc2VySW50ZXJmYWNlXG4gIFVzZXJJbnRlcmZhY2UgPHwtLSBUYWJsZVVzZXJJbnRlcmZhY2VcbiAgVXNlckludGVyZmFjZSA8fC0tIEdyYXBoVXNlckludGVyZmFjZVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQiLCJ0aGVtZVZhcmlhYmxlcyI6eyJiYWNrZ3JvdW5kIjoid2hpdGUiLCJwcmltYXJ5Q29sb3IiOiIjRUNFQ0ZGIiwic2Vjb25kYXJ5Q29sb3IiOiIjZmZmZmRlIiwidGVydGlhcnlDb2xvciI6ImhzbCg4MCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwicHJpbWFyeUJvcmRlckNvbG9yIjoiaHNsKDI0MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJzZWNvbmRhcnlCb3JkZXJDb2xvciI6ImhzbCg2MCwgNjAlLCA4My41Mjk0MTE3NjQ3JSkiLCJ0ZXJ0aWFyeUJvcmRlckNvbG9yIjoiaHNsKDgwLCA2MCUsIDg2LjI3NDUwOTgwMzklKSIsInByaW1hcnlUZXh0Q29sb3IiOiIjMTMxMzAwIiwic2Vjb25kYXJ5VGV4dENvbG9yIjoiIzAwMDAyMSIsInRlcnRpYXJ5VGV4dENvbG9yIjoicmdiKDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxLCA5LjUwMDAwMDAwMDEpIiwibGluZUNvbG9yIjoiIzMzMzMzMyIsInRleHRDb2xvciI6IiMzMzMiLCJtYWluQmtnIjoiI0VDRUNGRiIsInNlY29uZEJrZyI6IiNmZmZmZGUiLCJib3JkZXIxIjoiIzkzNzBEQiIsImJvcmRlcjIiOiIjYWFhYTMzIiwiYXJyb3doZWFkQ29sb3IiOiIjMzMzMzMzIiwiZm9udEZhbWlseSI6IlwidHJlYnVjaGV0IG1zXCIsIHZlcmRhbmEsIGFyaWFsIiwiZm9udFNpemUiOiIxNnB4IiwibGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsIm5vZGVCa2ciOiIjRUNFQ0ZGIiwibm9kZUJvcmRlciI6IiM5MzcwREIiLCJjbHVzdGVyQmtnIjoiI2ZmZmZkZSIsImNsdXN0ZXJCb3JkZXIiOiIjYWFhYTMzIiwiZGVmYXVsdExpbmtDb2xvciI6IiMzMzMzMzMiLCJ0aXRsZUNvbG9yIjoiIzMzMyIsImVkZ2VMYWJlbEJhY2tncm91bmQiOiIjZThlOGU4IiwiYWN0b3JCb3JkZXIiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJhY3RvckJrZyI6IiNFQ0VDRkYiLCJhY3RvclRleHRDb2xvciI6ImJsYWNrIiwiYWN0b3JMaW5lQ29sb3IiOiJncmV5Iiwic2lnbmFsQ29sb3IiOiIjMzMzIiwic2lnbmFsVGV4dENvbG9yIjoiIzMzMyIsImxhYmVsQm94QmtnQ29sb3IiOiIjRUNFQ0ZGIiwibGFiZWxCb3hCb3JkZXJDb2xvciI6ImhzbCgyNTkuNjI2MTY4MjI0MywgNTkuNzc2NTM2MzEyOCUsIDg3LjkwMTk2MDc4NDMlKSIsImxhYmVsVGV4dENvbG9yIjoiYmxhY2siLCJsb29wVGV4dENvbG9yIjoiYmxhY2siLCJub3RlQm9yZGVyQ29sb3IiOiIjYWFhYTMzIiwibm90ZUJrZ0NvbG9yIjoiI2ZmZjVhZCIsIm5vdGVUZXh0Q29sb3IiOiJibGFjayIsImFjdGl2YXRpb25Cb3JkZXJDb2xvciI6IiM2NjYiLCJhY3RpdmF0aW9uQmtnQ29sb3IiOiIjZjRmNGY0Iiwic2VxdWVuY2VOdW1iZXJDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yIjoicmdiYSgxMDIsIDEwMiwgMjU1LCAwLjQ5KSIsImFsdFNlY3Rpb25Ca2dDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yMiI6IiNmZmY0MDAiLCJ0YXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwidGFza0JrZ0NvbG9yIjoiIzhhOTBkZCIsInRhc2tUZXh0TGlnaHRDb2xvciI6IndoaXRlIiwidGFza1RleHRDb2xvciI6IndoaXRlIiwidGFza1RleHREYXJrQ29sb3IiOiJibGFjayIsInRhc2tUZXh0T3V0c2lkZUNvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dENsaWNrYWJsZUNvbG9yIjoiIzAwMzE2MyIsImFjdGl2ZVRhc2tCb3JkZXJDb2xvciI6IiM1MzRmYmMiLCJhY3RpdmVUYXNrQmtnQ29sb3IiOiIjYmZjN2ZmIiwiZ3JpZENvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCa2dDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQm9yZGVyQ29sb3IiOiJncmV5IiwiY3JpdEJvcmRlckNvbG9yIjoiI2ZmODg4OCIsImNyaXRCa2dDb2xvciI6InJlZCIsInRvZGF5TGluZUNvbG9yIjoicmVkIiwibGFiZWxDb2xvciI6ImJsYWNrIiwiZXJyb3JCa2dDb2xvciI6IiM1NTIyMjIiLCJlcnJvclRleHRDb2xvciI6IiM1NTIyMjIiLCJjbGFzc1RleHQiOiIjMTMxMzAwIiwiZmlsbFR5cGUwIjoiI0VDRUNGRiIsImZpbGxUeXBlMSI6IiNmZmZmZGUiLCJmaWxsVHlwZTIiOiJoc2woMzA0LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTMiOiJoc2woMTI0LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTQiOiJoc2woMTc2LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTUiOiJoc2woLTQsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSIsImZpbGxUeXBlNiI6ImhzbCg4LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTciOiJoc2woMTg4LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkifX0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)
2. Copy Markdown url from this page
3. Paste it to `README.md` file in any repository

**Expected behavior**
Diagram image will not be shown.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: Mozilla Firefox
 - Version: 82.0.3

**Additional context**
Code from live-editor I have been using:
```
classDiagram
  DbConnector -- Synchronizer
  DbConnector <|-- RethinkDbAdapter
  DbConnector <|-- SQLite
  DbConnector -- Task
  Synchronizer -- Parser
  Synchronizer -- Connection
  Synchronizer -- ManagerApp
  ViewComponent <|-- Task
  Task *-- State
  Task -- TaskIterator
  Task <|-- SubTask
  ViewComponentIterator -- Filter
  TaskIterator -- Synchronizer
  Filter -- ManagerApp
  ViewComponent -- ViewComponentIterator
  ViewComponent <|-- DefaultTaskViewDecorator
  ViewComponent <|-- BorderTaskViewDecorator
  ViewComponent <|-- EditorTaskViewDecorator
  ViewComponentIterator --* ManagerApp
  ManagerApp <|-- UserInterface
  UserInterface <|-- TableUserInterface
  UserInterface <|-- GraphUserInterface
```

**Comment by knsv** [comment]
I don't think github can do this yet. GitLab can though. See the thread below, perhaps they will implement it soon.

https://github.community/t/feature-request-support-mermaid-markdown-graph-diagrams-in-md-files/1922
