### ISSUE TITLE
Dead link in documentation 

### ISSUE THREAD

**Issue by StefanLobbenmeier** [mermaid-js/mermaid#1771]
**Describe the bug**
A link in the documentation takes me to 404

**To Reproduce**
1. https://mermaid-js.github.io/mermaid/#/
2. Click on 'Simple start to write diagrams.'
3. The page https://mermaid-js.github.io/mermaid/#/./n00b-GettingStarted opens which is a 404

**Expected behavior**
No 404 - instead I guess https://mermaid-js.github.io/mermaid/#/n00b-gettingStarted (Note the lowercase g)

**Screenshots**.
![D58E3246-008F-4F6E-ABA9-FE3BC2322BC9](https://user-images.githubusercontent.com/36509607/98962958-6f76fd80-2507-11eb-8e97-7fe0e67d63b9.png)

**Comment by BastianZim** [comment]
It's currently working for me. Would you mind checking if it's still broken on your side?

**Comment by StefanLobbenmeier** [comment]
That url: https://mermaid-js.github.io/mermaid/#/./n00b-GettingStarted is still 404, and still the result of me clicking on it. 

I also just tried with google translate as a proxy and it is also 404:
https://translate.googleusercontent.com/translate_c?depth=1&nv=1&pto=aue&rurl=translate.google.com&sl=en&sp=nmt4&tl=de&u=https://mermaid-js.github.io/mermaid/&usg=ALkJrhjXVBaPaMi6FiO2YraGHrf003I8qA#/./n00b-GettingStarted

**Comment by BastianZim** [comment]
Hmm that's strange. I also tried using Google Translate https://translate.google.de/translate?hl=&sl=en&tl=de&u=https%3A%2F%2Fmermaid-js.github.io%2Fmermaid%2F and then clicking on _Simple start to write diagrams._ and it correctly goes to https://mermaid-js.github.io/mermaid/#/n00b-gettingStarted

https://mermaid-js.github.io/mermaid/#/./n00b-GettingStarted is indeed incorrect but it's not linked anywhere for me.

**Comment by StefanLobbenmeier** [comment]
Just to be sure, I am talking about the link in the text, not in the sidebar. The one on the sidebar also works for me, but this link does not:

![20CBFB2E-3C57-4229-BC7D-E352D9E992E3](https://user-images.githubusercontent.com/36509607/100361605-a4e91400-2ffa-11eb-98b7-1964a808a603.jpeg)

**Comment by BastianZim** [comment]
Ahh, thanks for the clarification, that was it, now I can reproduce it. 
What's strange is that I [searched](https://github.com/mermaid-js/mermaid/search?q=n00b-GettingStarted) the repo and could not find the document containing the mistake. Were you able to find it?

**Comment by knsv** [comment]
Thanks for the clarification. This should be fixed.

**Comment by StefanLobbenmeier** [comment]
I was also unable to find the corresponding markdown, otherwise I would’ve fixed it myself.
