### ISSUE TITLE
Parser error when used with mermaidAPI

### ISSUE THREAD

**Issue by TytiX** [mermaid-js/mermaid#1775]
Hello,

I've try parsing the mermaid format with the mermaidAPI but i got an error and doesn't know if i'm doing something wrong or if i just missed something.
My graph is renderering correctly...

My context : this is in a vuejs application i'm getting a file with my graph in it, then parsing it...

My vue js file : 
```
mermaid.initialize({startOnLoad:true});

axios.get('/mermaid.md').then( res => {
  this.code = res.data;
  console.log(this.code);
  const parser = mermaid.parse(res.data);

  const graph = parser.parse(res.data);
  console.log(graph);
});
```

return an error:
```
{str: "Parse error on line 1:↵graph TD    Q1[Question ↵-----^↵Expecting 'NODIR', 'DIR', got 'SPACE'", hash: {…}}
hash: {text: " ", token: "SPACE", line: 0, loc: {…}, expected: Array(2)}
str: "Parse error on line 1:↵graph TD    Q1[Question ↵-----^↵Expecting 'NODIR', 'DIR', got 'SPACE'"
__proto__: Object
```

the mermaid.md file :
```
graph TD
    Q1[Question 1]
    Q1 -->|oui| Q1.1[Question 1.1]
    Q1 -->|non| Q1.2[Question 1.2]
    Q1.1 -->|oui| Q1.1.1[Question 1.1.1]
    Q1.1 -->|non| Q1.1.2[Question 1.1.2]
    Q1.2 -->|oui| Q1.2.1[Question 1.2.1]
    Q1.2 -->|non| Q1.2.2[Question 1.2.2]
    Q1.2.1 -->|oui| Q1.2.11[Question 1.2.11]
    Q1.2.1 -->|non| Q1.2.21[Question 1.2.21]
    Q1.1.1 -->|signal| R[Result]
    Q1.1.2 -->|signal| R
    Q1.2.11 -->|signal| R
    Q1.2.21 -->|signal| R
    Q1.2.2 -->|signal| R

```

**Comment by knsv** [comment]
Hi! I think there is a lacking new line or ; after the TD (as in the DIR mentioned in the error message). I would suggest you look at what you get back from the rest call and check that nothing has been lost in translation.

**Comment by jgreywolf** [comment]
@TytiX Can you confirm whether or not this is still an issue after following up on what Knut mentioned above?

**Comment by TytiX** [comment]
@jgreywolf and @knsv 
Hi, i've tried changing the md file to match the recommandations but nothing changed.

You can test the code on this page if needed
[stackblitz](https://stackblitz.com/edit/vue-ug8bo1?file=src/App.vue)

**Comment by sidharthv96** [comment]
https://stackblitz.com/edit/vue-t1hfju?file=src/App.vue

@TytiX I've fixed it to render the svg code properly.
Not a Vue expert, so not sure why the SVG is not displaying, but you're getting the SVG code in the variable.
You might have to use some special vue tag to render html.
