### ISSUE TITLE
How to change flowchart orientation?

### ISSUE THREAD

**Issue by yonatanbitton** [mermaid-js/mermaid#1779]
Hello. I'm using the live editor. 

I have the following graph:

```
flowchart TD
fence --> | near | puddle
fence --> | near | zebra
puddle --> | to the right of | zebra
puddle --> | near | fence

```
![image](https://user-images.githubusercontent.com/26148975/99438988-4696a400-291d-11eb-893e-222f1738a891.png)
It is currently up to bottom

How can I do it right to left? Like this: (but with oriented text)
![image](https://user-images.githubusercontent.com/26148975/99439077-67f79000-291d-11eb-8553-e55eb49e366c.png)

 Thanks!

**Comment by ViezeVingertjes** [comment]
```
flowchart **LR**
fence --> | near | puddle
fence --> | near | zebra
puddle --> | to the right of | zebra
puddle --> | near | fence
```

**Comment by yonatanbitton** [comment]
Thanks!
