### ISSUE TITLE
Quotes around font-family in sccs files makes svgs susceptible to line-wrap corruption

### ISSUE THREAD

**Issue by ahl** [mermaid-js/mermaid#1788]
**Is your feature request related to a problem? Please describe.**
When used from https://github.com/asciidoctor/asciidoctor-diagram svgs generated by github.com/mermaid-js/mermaid-cli are line-wrapped which causes them to be corrupted. While clearly asciidoctor-diagram should not be doing this (https://github.com/asciidoctor/asciidoctor-diagram/issues/308) I believe mermaid could make a simple fix to correct this.

**Describe the solution you'd like**
If the font-family were not surrounded by quotes (") line wrapping in the middle of the name of the default font family (trebuchet ms) seems to be processed fine. I'd propose that themes' sccs files drop the quotes.

**Describe alternatives you've considered**
Fix asciidoctor-diagram. In the interim, specifying a mermaid config file like this causes the quotes to be dropped:

```json
{
  "fontFamily": "trebuchet ms"
}
```

**Additional context**
N/A

**Comment by knsv** [comment]
Hi, thanks for reporting! Could you please move this report to https://github.com/mermaid-js/mermaid-cli as there are other people working with the cli.
