### ISSUE TITLE
I made python integration with Mermaid-js

### ISSUE THREAD

**Issue by theroyakash** [mermaid-js/mermaid#1791]
I've made a python integration with mermaid-js which uses the mermaid.ink service. I hope it could be added in the docs tutorial portion here: https://mermaid-js.github.io/mermaid/#/Tutorials.

It's also working with colab and jupyter lab notebooks.

```python
import base64

graphbytes = graph.encode("ascii")

graph = """
graph LR;
    A--> B & C & D;
    B--> A & E;
    C--> A & E;
    D--> A & E;
    E--> B & C & D;
"""

base64_bytes = base64.b64encode(graphbytes)
base64_string = base64_bytes.decode("ascii")

import requests, io
from PIL import Image
import matplotlib.pyplot as plt

img = Image.open(io.BytesIO(requests.get('https://mermaid.ink/img/' + base64_string).content))
plt.imshow(img)
```

![image](https://user-images.githubusercontent.com/43792446/100219062-8a9c3100-2f3b-11eb-9762-9e2182b7c8b6.png)

**Comment by ashishjain0512** [comment]
Thanks @theroyakash , we will add it to the tutorials.

**Comment by ashishjain0512** [comment]
@theroyakash your section is now added to the Tutorials, feel free to updates it & thank you for your contribution.
