### ISSUE TITLE
Notes remain bright yellow in dark theme.

### ISSUE THREAD

**Issue by roblabla** [mermaid-js/mermaid#1802]
**Describe the bug**

In sequence diagrams, Notes aren't themed in the dark theme (e.g. it remains black text on bright yellow background). 

**To Reproduce**

Use the following sequence diagram while using the dark theme:

```
sequenceDiagram
  Note over Client, Server: A
```

**Expected behavior**

I expect the note to use a shade of gray/blue as background with white text.

**Screenshots**

![image](https://user-images.githubusercontent.com/1069318/100767608-422cb980-33fa-11eb-999b-f3acb118b9bb.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 83

**Comment by knsv** [comment]
Good point, we should fix this!
