### ISSUE TITLE
Documentation: be precise on the different packages

### ISSUE THREAD

**Issue by djibe** [mermaid-js/mermaid#1803]
Hi,
I cannot find in the documentation a clear presentation of the packages.

What are the differences between `mermaid.js` and `mermaid.core.js`.

Thanks a lot for your brilliant work.

**Comment by sidharthv96** [comment]
mermaid.js - Non minified UMD bundle  - Deprecated
mermaid.min.js - Minified UMD Bundle (To use in websites) - Deprecated
mermaid.core.mjs - Core build of mermaid without external dependencies (to be used with bundlers like webpack, vite, etc)
mermaid.esm.mjs - Non minified ESM bundle
mermaid.esm.min.mjs - Minified ESM bundle to be used in websites
