### ISSUE TITLE
syntax error for nodes ending with "graph"

### ISSUE THREAD

**Issue by uriva** [mermaid-js/mermaid#1811]
```mermaid
graph TD
    some_node_graph --> some_other_node
```

**Comment by uriva** [comment]
By the way I think I opened it in the past and it got deleted, so if you close/delete this please let me know why.
Thanks

**Comment by uriva** [comment]
duplicated with #1670

**Comment by nirname** [comment]
Closing in favor of https://github.com/mermaid-js/mermaid/issues/2135
