### ISSUE TITLE
Gantt diagram same-line y-axis override (sponsorable)

### ISSUE THREAD

**Issue by SethRobertson** [mermaid-js/mermaid#1813]
I would like to be able to manually specify multiple tasks to appear on the same line, to save vertical space for distinct yet related tasks.  Essentially be able to add a new keyword to indicate which line to use.  The user would be responsible for object location clashes (though bonus points if you can specify that the text should be to the left of the object instead of right).

An ideal diagram description might look something like the one below.  The result would be all five tasks appearing on the same line.

```
gantt
    title Example
    Requirements  :a1, 2021-01-11, 4w
    Design  :a2, after a1, sameline a1, 4w
    Development  :a3, after a2, sameline a1, 4w
    Test  :a4, after a3, sameline a1, 4w
    Demo  :crit, a5, after a4, sameline a1, 1d
```

This is perhaps somewhat related to the second item of #1708. I believe it should be added to ganttDb.js's addtask function (and the parser).

I would be willing to sponsor this feature, nearterm.

**Comment by k-slava** [comment]
I can share some expenses. It would be a convenient feature. It can kill many project management tools in simple projects and some task management tools in complicated usages.

**Comment by SethRobertson** [comment]
No comment/contact from the maintainer, so unclear if this would help or not (but if it ever gets done, it is nice to show your appreciation).

However, I agree that it would be a convenient feature that seems to be missing from many task management tools.  I don't actually want to do project planning, I just want to draw compressed gantt tasks so other people understand what is happening.

**Comment by windmaomao** [comment]
yeah, i can't seem to get this working

```bash
|--x---x---x-x--x--x------> user event
|--a---a---a-a--a--a-----> action
```

**Comment by intersectionsSR** [comment]
Hi guys, is there any person working on ?  
Have a good day !

**Comment by SethRobertson** [comment]
Three years later and I still want this feature.  There appears to be another issue #1996 which is a duplicate of this.

Use cases are many.  One particular gratuitous one is an event which occurs monthly for years.  In this particular case I have 99 lines in my chart just for things I need to produce (22 items are duplicated, 48% of the chart represents dups).

As it is, the output is completely unreadable, the raw output is 1784x2476--which is taller than a 4K display.

**Comment by aniston** [comment]
@SethRobertson , it took a couple of years, but in the current ver 10.2.3 this seems possible with a new mode in Gantt called [compact ](https://mermaid.js.org/syntax/gantt.html#output-in-compact-mode) mode.

I rephrased your example to exclude the `sameline a1`  proposal and preceeding the YAML settings with 
`displayMode: compact`

```
---
displayMode: compact
---
gantt
    dateFormat  YYYY-MM-DD
    axisFormat  %d
    title Example
    Requirements  :a1, 2021-01-11, 4w
    Design  :a2, after a1, 4w
    Development  :a3, after a2, 4w
    Test  :a4, after a3, 4w
    Demo  :crit, a5, after a4, 1d
```

HTH

**Comment by nirname** [comment]
@SethRobertson does this display mode serve your purposes?

**Comment by Yokozuna59** [comment]
> does this display mode serve your purposes?

@nirname I think it should, closing issue as resolve.

You could have that layout using [compact mode](https://mermaid.js.org/syntax/gantt.html#output-in-compact-mode).
