### ISSUE TITLE
Incorrect classes in styling documentation for gantt diagrams

### ISSUE THREAD

**Issue by bartosz-m** [mermaid-js/mermaid#1820]
**Describe the bug** 
Documentation related to gantt diagrams located in `mermaid/docs/gantt.md` in section `Styling > Classes used` contains incorrect classes it looks like it was copy paste from sequence diagram docs.

**Comment by NeilCuzon** [comment]
docs have been updated to reflect proper classes, thank you for bringing it to our attention. I will be closing this issue.
