### ISSUE TITLE
how to render with marked.js

### ISSUE THREAD

**Issue by darkgirl** [mermaid-js/mermaid#1830]
Hi, 
I have tried this [example](http://mermaid-js.github.io/mermaid/#/usage?id=example-of-a-marked-renderer) and [marked](https://cdn.jsdelivr.net/npm/marked/marked.min.js)

but I found the following code just work when the document is loading
`
  var updateText = function(text) {
      var source = document.getElementById('source');
      source.innerHTML = marked(text);
  }
`
but if I use updateText() after document loaded, such as:
`
button1.onclick = function(){
updateText ('graph RL;\n  A-->B;');
}
`
it did not work
please somebody help me, let me know how to make this work, thank you very much!

**Comment by fuzhengyin** [comment]
After updateText, invoke `mermaid.run()`
[Using mermaid.run](http://mermaid.js.org/config/usage.html#using-mermaid-run)

**Comment by sidharthv96** [comment]
@darkgirl please call `await mermaid.run()` after updating the DOM element. 
Make sure the updated text has the correct class (`.mermaid`).

**Comment by jgreywolf** [comment]
Closing due to no response
