### ISSUE TITLE
Render issue on chromium based browsers.

### ISSUE THREAD

**Issue by tokyo786** [mermaid-js/mermaid#1834]
**Describe the bug**
UML Diagrams have text overflow in chromium browsers, rendering fine on Firefox.

**To Reproduce**
1. Open https://mermaid-js.github.io/mermaid-live-editor on chrome
2. Open https://mermaid-js.github.io/mermaid-live-editor on Firefox
3. Works fine on Firefox but text overflows in chrome

**Expected behavior**
Should work similarly on chrome and firefox.

**Screenshots**
Chrome:

![image](https://user-images.githubusercontent.com/19167384/102665590-1e63c480-41ab-11eb-899f-a21b268039f2.png)

Firefox:
![image](https://user-images.githubusercontent.com/19167384/102665685-43583780-41ab-11eb-8f3f-67552c7ce35a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 1080p screen, 15 Inch Laptop (125% UI Scaling)
 - Browser Chrome
 - Version Latest

**Comment by dcrouch79** [comment]
Try using `flowchart` instead of `graph`.

This seems to fix the issue on the latest version of Chrome (v87) and Edge (v87)

**Comment by tokyo786** [comment]
> Try using `flowchart` instead of `graph`.
> 
> This seems to fix the issue on the latest version of Chrome (v87) and Edge (v87)

Yep, it fixes the issue on chrome and edge - What's the difference between `flowchart`  and `graph` which fixes it?

**Comment by singhprabhanshu** [comment]
> > Try using `flowchart` instead of `graph`.
> > This seems to fix the issue on the latest version of Chrome (v87) and Edge (v87)
> 
> Yep, it fixes the issue on chrome and edge - What's the difference between `flowchart` and `graph` which fixes it?

But the edges are rounded, not the sharp one. Is there any configuration parameter for edges curves?

**Comment by majusmisiak** [comment]
I'm seeing exact same issue as of Google Chrome Version 88.0.4324.150

Even in the documentation, text is overflowing from the boxes.
![image](https://user-images.githubusercontent.com/25297445/108057657-32b12a00-7053-11eb-94b4-f1b369cf1d32.png)

**Comment by joeldeteves** [comment]
> Try using `flowchart` instead of `graph`.
> 
> This seems to fix the issue on the latest version of Chrome (v87) and Edge (v87)

This worked for me, except using flowchart also breaks the fill colors in some shapes (circles and diamonds).

So it's a bit of a tradeoff.

Interestingly, horizontal graphs work fine (graph LR).

For my vertical charts I've had to swap them for flowchart and not use non-rectangular shapes if I want the fill colors to work and to have it display properly on Chromium browsers.

**Comment by slokhorst** [comment]
It seems that this issue was fixed in Chrome 89. Can anyone confirm?

**Comment by dcrouch79** [comment]
Works for me now in both Chrome and Edge v89.

**Comment by joeldeteves** [comment]
> It seems that this issue was fixed in Chrome 89. Can anyone confirm?

Yes it appears to be working on the latest version of Edge for me as well.

**Comment by Yokozuna59** [comment]
For this [comment](https://github.com/mermaid-js/mermaid/issues/1834#issuecomment-804796350):

> Works for me now in both Chrome and Edge v89.
