### ISSUE TITLE
unable to customize themes

### ISSUE THREAD

**Issue by objectivephoenix** [mermaid-js/mermaid#1836]
**Describe the bug**
I'm using a hugo blog which uses `mermaid.min.js` and I'm unable to customize themes although I am able to change themes successfully.

**To Reproduce**
1. write the following section

```
{{< mermaid >}}
%%{init: {'securityLevel': 'loose', 'theme':'base', 'themeVariables': { 'primaryColor': '#ff0000', 'background': '#f3f3f3'}}}%%
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
{{< /mermaid >}}
```

I get the following output on dark and light theme respectively.

![2020-12-20T21](https://user-images.githubusercontent.com/67443683/102718488-5a636a80-430e-11eb-8b81-31fba0bf28f4.png)
![2020-12-20T22](https://user-images.githubusercontent.com/67443683/102718491-5d5e5b00-430e-11eb-87c4-9934bb3cf4b4.png)

2. No matter what changes I make to the theme variables, the output stays the same. The only successful change happens if I change the theme from base to forest or dark or default. I'm not sure if I should be able to customize them though but I'm unable to using the above method.

**Expected behavior**
`themeVariables` should be implemented but they have no effect. Only the `theme` variable has any effect.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 84 and Chromium 87

**Additional context**
I'm using the [Hugo Book](https://github.com/alex-shpak/hugo-book) theme. It includes `mermaid.min.js`.

**Comment by knsv** [comment]
You have got the mermaid part exactly right. When trying your code in the live editor it renders the image below:
![image](https://user-images.githubusercontent.com/5837277/105393506-b296d080-5c1c-11eb-937e-d40dcc309442.png)

I wonder what version of mermaid your hugo instance is using. Perhaps it is too old. Improved themeing was release summer 2020.

**Comment by objectivephoenix** [comment]
> I wonder what version of mermaid your hugo instance is using. Perhaps it is too old. Improved themeing was release summer 2020.

According to the commit messages [here](https://github.com/alex-shpak/hugo-book/commits/master/static/mermaid.min.js), it's something after version 8.4.8.

I'll try upgrading to the latest version and then report back if anything changes.

**Comment by objectivephoenix** [comment]
I can confirm that this issue is no longer present after upgrading to the version 8.9.0.

Thanks for the help.
