### ISSUE TITLE
Syntax Error when node ends on "_end"

### ISSUE THREAD

**Issue by evheny0** [mermaid-js/mermaid#1837]
**Describe the bug**
Flow chart doesn't allow nodes to have a name that ends with "*_end" 

**To Reproduce**
Here is the example:
```
graph TD
  A --> B_end
```
Although this example works:
```
graph TD
  A --> B_endd
  A --> Bend
```

**Expected behavior**
Not to fail

**Screenshots**
![image](https://user-images.githubusercontent.com/3540194/102896067-dc6ea300-4476-11eb-86b5-df6028f3ddd8.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 87.0.4280.88

**Comment by jgreywolf** [comment]
Closing issue as this is covered in [documentation](https://mermaid-js.github.io/mermaid/#/flowchart?id=flowcharts)
