### ISSUE TITLE
Sequence diagram render issue on Firefox

### ISSUE THREAD

**Issue by ArtFlag** [mermaid-js/mermaid#1848]
On Firefox 84.0.1 and 84.0.2, I'm getting the follow output on my website:

<img width="370" alt="Screenshot 2021-01-08 at 09 33 58" src="https://user-images.githubusercontent.com/25686502/103992942-2785f700-5195-11eb-8d6e-2efdeeaa9a85.png">

On Chrome, I'm getting:

<img width="429" alt="Screenshot 2021-01-08 at 09 34 35" src="https://user-images.githubusercontent.com/25686502/103992982-2f459b80-5195-11eb-9d12-b6d9c2c447d1.png">

**Expected behavior**

I expect the rendered SVG to be the exact same (line height, fonts, etc) regardless on the browser or my website's CSS (unless the site uses `!important` with unappropriate selectors). 

**Desktop (please complete the following information):**
 - OS: MacOs 10.15.7

**Comment by ashishjain0512** [comment]
@ArtFlag We tried replicating the issue on macOS 10.15.7 and Firefox 84.0.1, and were unable to reproduce it.

You can try it in the Mermaid Live Editor, if you still see the issue, please report back with steps to reproduce: use the link below:
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgQWxpY2UtPj4rSm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_XG4gICAgSm9obi0tPj4tQWxpY2U6IEdyZWF0IVxuICAgICAgICAgICAgIiwibWVybWFpZCI6e30sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

**Comment by ArtFlag** [comment]
It seems the issue was coming from an extension, not from mermaid. I'm still unclear about it but we can close this issue.
Thanks!
