### ISSUE TITLE
Add support for return values in methods for class diagram

### ISSUE THREAD

**Issue by jcubic** [mermaid-js/mermaid#1856]
**Is your feature request related to a problem? Please describe.**
Some UML diagrams show full methods specification, it would be nice to include return value so UML diagram can be more like documentation, and user would not need to go do Reference API to get the method spec.

**Describe the solution you'd like**

Allow this syntax:
```
class LNumber {
  isFloat(): boolean
  add(n: LNumber): LNumber
}
```
And display it on the diagram

**Additional Context**
I can try to help adding this feature, if you think it's good idea and the feature will be merged (after review and necessary fixed to the PR if any of course).

**Comment by h33linL** [comment]
+1  I want to have this feature too.

**Comment by Kaapiii** [comment]
+1

**Comment by jgreywolf** [comment]
This functionality is already in place and is working  - see [Live Editor]([![](https://mermaid.ink/img/pako:eNo9UMtqwzAQ_BWzpwTUYDtWLOtcckp76a3osrE2qUGPIEvQ1PjfK7tJ57IzwzC77AS91wQSeoPj-DrgNaBVrshYneL0nuyZQjEt5jAejce42RZn7w2hW0zUeuOeue2TKDcrBwwsBYuDzhvWBgXxiywpkJlqumAyUUEO5yim6D_urgd5QTMSg3TTGOlx1L97Q_fpfdYxpD8JcoJvkC_lrsyohChbUXW1aFsu9jWDO0h-2PGuavie87puDmXXzAx-1pqKAekh-vD2-MQy5l_iylhr?type=png)](https://mermaid.live/edit#pako:eNo9UMtqwzAQ_BWzpwTUYDtWLOtcckp76a3osrE2qUGPIEvQ1PjfK7tJ57IzwzC77AS91wQSeoPj-DrgNaBVrshYneL0nuyZQjEt5jAejce42RZn7w2hW0zUeuOeue2TKDcrBwwsBYuDzhvWBgXxiywpkJlqumAyUUEO5yim6D_urgd5QTMSg3TTGOlx1L97Q_fpfdYxpD8JcoJvkC_lrsyohChbUXW1aFsu9jWDO0h-2PGuavie87puDmXXzAx-1pqKAekh-vD2-MQy5l_iylhr)

**Comment by jcubic** [comment]
@jgreywolf thanks for the heads up. I will check the diagram in my OSS project and will close it if it works.

**Comment by jcubic** [comment]
Can confirm it works. Closing.
