### ISSUE TITLE
Cannot process input if  there is an item ending with string "_top"

### ISSUE THREAD

**Issue by dirkaudaz** [mermaid-js/mermaid#1876]
**Description**
If a plot's element id or name ends with "_top", Mermaid errors out "Syntax error in graph".
This issue does NOT happens if "_top" if followed with another substring, for example, underscore -> "_top_"

**To Reproduce**
Put the following code in a HTML file and try to load it:
```
<div class="mermaid">
graph LR
    test1{{test1}} --> top{{_top}}
    test2{{test2}} --> _top{{top}}
</div>
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>
```

**Expected behavior**

To be able render diagrams with elements with id and names ending with "_top"

**Desktop :**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version:  84.0.2 (64 bit)

**Comment by nirname** [comment]
I think you can render them using string
This one works just fine
```
graph LR
    test1{{test1}} --> top{{"_top"}}
```

```mermaid
graph LR
    test1{{test1}} --> top{{"_top"}}
```

**Comment by nirname** [comment]
Closing this one in favor of #2135
