### ISSUE TITLE
Add a pre-commit lint hook for staged files.

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#1878]
**Is your feature request related to a problem? Please describe.**
This will ensure that the developer does not have to run lint manually

**Describe the solution you'd like**
Use lint-staged along with husky to lint all modified files before each commit

**Describe alternatives you've considered**
Manual linting / Save automatically via editor. But both are not standard.

**Additional context**
This has already been implemented in [mermaid-live-editor](https://github.com/mermaid-js/mermaid-live-editor/blob/master/package.json)

**Comment by harshilparmar** [comment]
@sidharthv96 I would like to work on this issue.
