### ISSUE TITLE
Doesn't support nested generic types for members

### ISSUE THREAD

**Issue by iamkroot** [mermaid-js/mermaid#1882]
The syntax doesn't allow specifying nested generic types for the members in a class diagram
**Required output example:**
```
vector<unique_ptr<int>> member
```

The use of `~` for marking both the start and end of generic type results in wrong output with nested generics:

**Input:**
```
vector~unique_ptr~int~~ member
```

**Current output:**
```
vector<unique_ptr>int<> member
```

The solution would be to add proper support for the same with 2 characters (to denote begin and end).

**Comment by TorrentialFire** [comment]
I played around with this for my own class diagrams. You can use the `<>` characters inside the `~~` statement, like so:
Input:
```
vector~unique_ptr<int>~ member
```
Output:
```
vector<unique_ptr<int>> member
```

I'm using Mermaid >8.8.4

**Comment by sidharthv96** [comment]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/10703445/220007096-1879a0ea-16a4-490e-8ad3-9f903f217fc0.png">

Nested generics are now supported!
