### ISSUE TITLE
Click interactions with hash href returns about:blank instead of a hash link as the href

### ISSUE THREAD

**Issue by ethanlonge** [mermaid-js/mermaid#1883]
**Describe the bug**
As the title states, when I place a # anchor link for the element to jump down to a section on the page that it is on, it instead fills the a href as "about:blank" instead of the # anchor link I entered in

**To Reproduce**
1. Create a diagram with the following code:
```html
<div id="test"></div>
<div class="mermaid">
graph TD
A(Test Link)
click A "#test"
</div>
```
2. Click on Test Link node
3. See that it redirects to about:blank instead of jumping to the test div element

**Expected behavior**
It should be jumping to the test div element instead of redirecting to about:blank

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 88.0.4324.146

**Smartphone (please complete the following information):**
Not tested on mobile. Expected same result

**Additional context**
N/A

**Comment by Hedroed** [comment]
+1

**Comment by Hedroed** [comment]
fixed in #1218

**Comment by wojtek717** [comment]
@Hedroed Any update on this? The problem still ocours.

**Comment by Hedroed** [comment]
Yo, the problem has been fixed, thanks
