### ISSUE TITLE
Escaping annotations specified outside of class definition does not work for class diagrams

### ISSUE THREAD

**Issue by FirstTimeInForever** [mermaid-js/mermaid#1889]
**Describe the bug**
If you try to escape class annotations outside of class definition, the diagram fails to render. Take a look at the examples below.

Works fine:
```
classDiagram
     class Klass3 {
       #lt;#lt;interface#gt;#gt;
       +String name
     }
```

Doesn't work:
```
classDiagram
     class Klass3 {
       +String name
     }

     #lt;#lt;interface#gt;#gt; Klass3
```

**To Reproduce**
1. Open mermaid live editor and type attached code.
2. See error

**Expected behavior**
Both cases should produce the same result.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: chrome
 - Version 88.0.4324.150 (Official Build) (x86_64)
 - Mermaid version of live editor: 8.8.4

**Comment by jgreywolf** [comment]
@FirstTimeInForever Is there a specific requirement that makes you want to use escaped characters for defining interface?

This works:
`classDiagram
     class Klass3 {
       +String name
     }

     <<interface>> Klass3`

**Comment by jgreywolf** [comment]
Closing due to lack of response/activity
