### ISSUE TITLE
Add underlined text to nodes

### ISSUE THREAD

**Issue by amingilani** [mermaid-js/mermaid#1892]
**Is your feature request related to a problem? Please describe.**

When I'm trying to draw ERD diagrams for a course, using the symbols described in the [Fundamentals of Database System](https://www.amazon.ca/Fundamentals-Database-Systems-Ramez-Elmasri/dp/0133970779). The elements are different from the ERD diagram in mermaid.js, so I revert to using the flowchart.

However, I need an underlined node to denote a primary key, but mermaid.js doesn't support underlined nodes

**Describe the solution you'd like**
Allow underlined nodes

**Describe alternatives you've considered**

1. I tried added `<u></u>` tags. Here's what happened:

```
graph TD
    User[User]
    User --> ID(<u>ID/u>)
    User --> Email(Email)
    User --> Password(Password)
```

<img width="351" alt="Screen Shot 2021-02-12 at 5 24 01 PM" src="https://user-images.githubusercontent.com/1188552/107828571-21b4a000-6d57-11eb-8248-2ea26b408585.png">

2. I've also tried adding styles, as per https://github.com/mermaidjs/mermaidjs.github.io/issues/8

```
graph TD
    User[User]
    User --> ID(ID)
    User --> Email(Email)
    User --> Password(Password)
    style ID  text-decoration: underline
```

The result is the same as the previous image.

**Comment by math-GH** [comment]
>     1. I tried added `<u></u>` tags. Here's what happened:
> 
> 
> ```
> graph TD
>     User[User]
>     User --> ID(<u>ID/u>)
>     User --> Email(Email)
>     User --> Password(Password)
> ```

Could you please try a valid HTML `</u>`?

**Comment by sidharthv96** [comment]
<img width="1512" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/a62ef109-fd2b-4b19-b163-58083a2bd67b">
