### ISSUE TITLE
Data Flow Diagram (a la STRIDE Threat Model)

### ISSUE THREAD

**Issue by pbnj** [mermaid-js/mermaid#1893]
**Is your feature request related to a problem? Please describe.**

I am curious if there is a way to generate a [Data Flow Diagram](https://en.wikipedia.org/wiki/Data-flow_diagram) using Mermaid (see example screenshot below).

Data Flow Diagrams are common in software Threat Modelling, especially the [STRIDE](https://github.com/AzureArchitecture/threat-model-templates) threat model methodology.

**Describe the solution you'd like**

A a flow `graph` or `stateDiagram` are very similar in concept. In fact, if there is a way to use custom shapes and denote the type of node, then it may very well be possible to achieve this today.

For example, the following Mermaid code would generate the screenshot below:

```
graph
    DataStore[|Database|] -->|input| Process((System)) -->|output| Entity[Customer]
```

Where:

- A node surrounded by `[| |]` denotes a Data Store
- A node surrounded by `(( ))` denotes a Process or Function
- A node surrounded by `[ ]` denotes an External Entity
- Arrows, `-->|label|` denotes a Data Flow labeled as `label`

Besides a few shapes that are missing (e.g. Data Store represented by horizontal parallel lines), all shapes would also need to be available in solid lines and dashed/dotted lines, which denotes being out-of-scope.

**Additional context**

Simple Data Flow Diagram:

![data flow diagram example](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Data-flow-diagram-example.svg/956px-Data-flow-diagram-example.svg.png)

**Comment by ahmeddjango** [comment]
flowchart LR
    A[User] -->|Captured Image| B(Image Capture)
    B -->|Captured Image| C(Face Detection)
    C -->|Detected Face| D(Face Recognition)
    D -->|Recognized Face| E(Attendance Marking)
    E -->|Marked Attendance| F(Database)
    F -->|Updated Attendance| G[User]
    B -->|Error| H(Error Handling)
    C -->|Error| H
    D -->|Error| H
    E -->|Error| H
    H -->|Error Report| G

**Comment by fguisso** [comment]
Just one more example if anyone needs.

```mermaid
flowchart LR
    user(user)
    mobile((mobile\napplication))
    proxy((reverse\nproxy))
    api((API))
    db[|borders:tb|database]

    subgraph external [Internet]
        user--personal data-->mobile
        mobile-->proxy
    end
    subgraph dmz [Internal Network]
        proxy-->api
        db-->api
        api-->db
    end
    classDef boundary fill:none,stroke-dasharray: 5 5
    dmz:::boundary
    external:::boundary
```
```mmd
flowchart LR
    user(user)
    mobile((mobile\napplication))
    proxy((reverse\nproxy))
    api((API))
    db[|borders:tb|database]

    subgraph external [Internet]
        user--personal data-->mobile
        mobile-->proxy
    end
    subgraph dmz [Internal Network]
        proxy-->api
        db-->api
        api-->db
    end
    classDef boundary fill:none,stroke-dasharray: 5 5
    dmz:::boundary
    external:::boundary
```

**Comment by chahatm90** [comment]
graph TD;
    A[Job Seekers] -->|Search Jobs| B[Job Portal];
    B -->|View Job Listings| A;
    A -->|Apply for Jobs| C[Job Portal];
    C -->|Submit Application| B;
    B -->|Receive Applications| C;
    C -->|Shortlist Candidates| D[Job Recruiters];
    D -->|Review Applications| B;
    D -->|Schedule Interviews| E[Job Seekers];
    E -->|Receive Interview Invitations| A;
    E -->|Accept/Decline Invitations| D;
    D -->|Conduct Interviews| E;
    E -->|Interview Feedback| D;
    D -->|Select Candidates| F[Job Offers];
    F -->|Offer Letters| A;
    F -->|Accept/Reject Offers| D;
    F -->|Hiring Process| G[Onboarding];
    G -->|New Employees| D;
