### ISSUE TITLE
Interface annotation and cardinality not working in IntelliJ plugin

### ISSUE THREAD

**Issue by jonathanlocke** [mermaid-js/mermaid#1898]
Loving mermaid. Thanks for making it!

These examples don't seem to work in the IntelliJ plugin. Are they expected to? Thanks! -- Jon

`class Resource {`
        `<<interface>>`
`}`

produces

<img width="414" alt="Screen Shot 2021-02-20 at 11 17 21 AM" src="https://user-images.githubusercontent.com/74324/108604799-533bf580-736d-11eb-9c83-b907768a1dad.png">

---

`Graph "1" --> "*" Edge : contains`
`class Graph {`
`}`
`class Edge {`
`}`

 
produces

<img width="81" alt="Screen Shot 2021-02-20 at 11 15 45 AM" src="https://user-images.githubusercontent.com/74324/108604806-5b943080-736d-11eb-8cab-d295bdabe3dd.png">

**Comment by jowilkes** [comment]
Which IntelliJ plugin are you referring to, exactly?

**Comment by jonathanlocke** [comment]
It was a while ago, but I think it was the built-in markdown plugin.

**Comment by jonathanlocke** [comment]
If you can't repro this, you can close it. It's not affecting me as I've found another way.

**Comment by Yokozuna59** [comment]
Hi there, is this still an issue? I assume that the extension you are using was using an older version of mermaid, and I think that they bumped the version.

If it wasn't resolved, contact the extension authors to do, since it's not an issue from our side.
