### ISSUE TITLE
Nodes overflow in official doc

### ISSUE THREAD

**Issue by qortex** [mermaid-js/mermaid#1901]
**Describe the bug**
In the official doc, on page https://mermaid-js.github.io/mermaid/#/flowchart?id=graph, it displays as in the screenshot below, with overflowing nodes.

**Expected behavior**

I expect the text not to overflow

**Screenshots**
![image](https://user-images.githubusercontent.com/37897072/108749525-33106000-7540-11eb-8db4-900e709d7c3f.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version latest 88.0.4324.186

**Comment by Abrosimov-a-a** [comment]
Confirm this issue for Debian Chrome 88.0.4324.*

Chrome update to v89.0.4389.90 solve it.
