### ISSUE TITLE
Sequence Diagram determine actor order

### ISSUE THREAD

**Issue by schicks** [mermaid-js/mermaid#1902]
**Describe the solution you'd like**
Right now actors in a sequence diagram always occur in the order of events. Sometimes a diagram would be more intuitive given a different ordering of actors. It would be nice to be able to specify the name of an actor without any interactions on a line as a way to specify where an actor should appear.

**Additional context**
[plantUML](http://www.plantuml.com/plantuml/uml/RSzH2W91283Xzpc55_024R7R4Rg1RKB2fjFet3-hn_L9n8yVN3nen7pjhUUKJJffmDNkhQsxR0nu-MudM6SyMLDGY2dS-3tPe-KDCCqF5ygxgVCXffPk0DNHFpuZ5hg8BwoF_E03) allows for declaring participants on their own lines, and will render participants in the order in which they are declared. Not all participants need be declared.

**Comment by flummer** [comment]
I pretty sure you can already do that: https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=participants

**Comment by mhnsn** [comment]
A forward declaration of a participant does seem to force the actor order to change.
