### ISSUE TITLE
Why is this called mermaid js?

### ISSUE THREAD

**Issue by victor-vineti** [mermaid-js/mermaid#1904]
Out of curiosity why is this package called mermaid?

**Comment by knsv** [comment]
I started the project when I was in my living room watching TV with my kids. I did not really expect mermaid to kick off in the way it has but rather was planning to use it in my daily job. My kids were watching the little mermaid so I got som inspiration... :)

**Comment by jeremy-ebler-vineti** [comment]
It would be nice to include this fun fact / origin story in the README.

**Comment by jgreywolf** [comment]
Closing as question was answered - will look at adding to readme :)
