### ISSUE TITLE
Labels for arcs with identical source/target overlap

### ISSUE THREAD

**Issue by wouterbeek** [mermaid-js/mermaid#1927]
**Describe the bug**
In the class diagram, when two arcs have the same source and target node, their labels often overlap (see screenshot).

**To Reproduce**

1. Create a class diagram with two arcs with the same source and target, but different labels.
2. Notice that more often than not, these labels overlap are are unreadable.

**Expected behavior**
The arcs to be displayed a little bit more apart (when possible, of course), so that at least in the majority of case the labels remain readable.

**Screenshots**
![Screenshot from 2021-02-25 09-37-04](https://user-images.githubusercontent.com/1685012/110023614-a6c71f80-7d2d-11eb-8091-5896f896ffc0.png)

^ This image contains two pairs of arcs with identical source/target nodes but different labels.  Notice that the four labels involved are difficult to read.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser: Chrome 88
 - Version: Mermaid 8.7.0

**Comment by jgreywolf** [comment]
Can you provide an example in the live editor, so we can better understand where we might need to work on this

https://mermaid-js.github.io/mermaid-live-editor/#

**Comment by wouterbeek** [comment]
@jgreywolf This is an MWE Mermaid string:
