### ISSUE TITLE
Can I specify flowcharts' style like this?

### ISSUE THREAD

**Issue by luooofan** [mermaid-js/mermaid#1941]
I can't describe the question exactly in english, so please look the screenshot. 
![image](https://user-images.githubusercontent.com/46896167/111030295-4fffcb00-843c-11eb-930a-f9e7b0fa94d1.png)

How can I change the lines' style in picture above to this:
![image](https://user-images.githubusercontent.com/46896167/111030370-d0263080-843c-11eb-8d61-d5e89c5bf822.png)

To be honest, the requirement is maybe special. But I still want to know  how to do it. Does it have to modify the source code? I can't find relevant documents.

**Comment by alex-bender** [comment]
@knsv Thanks a lot for great tool!
That feature could be pretty useful for real, to have edgePath with only right angle possible.
Or is there at least any way to do that changing the code if not via changing config parameters?
Thanks

**Comment by jgreywolf** [comment]
This is possible now, to a degree, using the information in documentation here:

http://mermaid.js.org/syntax/flowchart.html#styling-line-curves
