### ISSUE TITLE
Is it possible to reference another diagram within a diagram / magic cross linking?

### ISSUE THREAD

**Issue by wolfspyre** [mermaid-js/mermaid#1944]
I'd like to know if there's a standard / supported / good / way to reference diagrams which reside in another file / repository?

My general use case is a diagram which represents a superset several different services' diagrams represented canonically in their respective repositories.. and was thinking that mermaid may have some metapreprocessing available to link between markdown files which contain mermaid diagrams in a more fluid fashion.... 

prolly several ways to accomplish the goal, but thought there might be one that's more elegant, and if so, was wondering if that was a pattern that aught be reinforced?

**Comment by jgreywolf** [comment]
This is not currently possible, and is not on the roadmap to be done any time soon

**Comment by sumau** [comment]
I raised a feature request with GitHub  https://github.com/orgs/community/discussions/201064  to render Mermaid diagrams referenced from a .mmd or .mermaid file — both same-repo relative paths and cross-repo raw URLs. Please upvote if you think it's a good idea!
