### ISSUE TITLE
How can change flow of graphic from TD to LR for a part of graphic?

### ISSUE THREAD

**Issue by benibilme** [mermaid-js/mermaid#1949]
I am using mermaid 8.8.2. I have not been able to figure out relatively obvious thing. How can change flow of graphic from TD to LR for a part of graphic? I have seen some discussion here. It seems it is implemented via subgraph but it does not work in my setup which is manjaro, npm version 7.6.3

**Comment by jgreywolf** [comment]
This is not really possible at this time, due to constraints within dagre.  We are looking at the idea of being able to change this in subgraph, but that is not being actively worked on right now.

**Comment by Yokozuna59** [comment]
Resolved in #2082
