### ISSUE TITLE
State diagrams inline color

### ISSUE THREAD

**Issue by doodlewhale** [mermaid-js/mermaid#1952]
**Is your feature request related to a problem? Please describe.**
There is no simple way to define a node's color inline

**Describe the solution you'd like**
A simple solution akin to the plantuml solution would be ideal. e.g. specifying hex colour code after state name. See plantuml example: 
![image](https://user-images.githubusercontent.com/600571/112042893-f6845400-8b3f-11eb-93fa-6efd7eb96a4a.png)

**Describe alternatives you've considered**
PlantUML

**Comment by knsv** [comment]
How about something more like the current solution in flowcharts? We are trying to keep the syntax as uniform as possible between the different diagrams

**Comment by doodlewhale** [comment]
> 
> 
> How about something more like the current solution in flowcharts? We are trying to keep the syntax as uniform as possible between the different diagrams

That sounds sensible. My suggestion was to keep the State diagrams as close to the Plantuml format for compatibility which seems to have been a requirement from the developers. It would be good to have both options to be fair. I like the idea of keeping it consistent accross the whole of Mermaid but also see the benefit of sharing state diagrams with Plantuml users.
