### ISSUE TITLE
syntax error was observed if class diagram contains comment syntax with curly bracket like `%%{`

### ISSUE THREAD

**Issue by tomoyukim** [mermaid-js/mermaid#1968]
**Describe the bug**
I found syntax error is occurred if class diagram has comment syntax with curly brace like `%%{`. This was originally reported on https://github.com/tomoyukim/vscode-mermaid-editor/issues/35 and I could reproduced on live editor as well. Please take a look at screenshot.

**To Reproduce**
1. Try to render class diagram including `%%{`

For example,

```
classDiagram
	%%{
	Animal <|-- Duck
	Animal <|-- Fish
	Animal <|-- Zebra
	Animal : +int age
	Animal : +String gender
	Animal : +String sample
	Animal: +isMammal(a)
	Animal: +mate()
	class Duck{
		+String beakColor
		+swim()
		+quack()
	}
	class Fish{
		-int sizeInFeetaaaa
		-canEat()
	}
	class Zebra{
		+bool is_wild
		+run()
	}
```

**Expected behavior**
class diagram should be previewed.

**Screenshots**
<img width="485" alt="Screen Shot 2021-03-28 at 22 16 35" src="https://user-images.githubusercontent.com/1187581/112753985-022abb80-9015-11eb-84b1-3b690b90cd4a.png">

**Additional context**
This was not observed on erDiagram at least.

**Comment by NeilCuzon** [comment]
The syntax resembles that of a directive, which is  method of changing the config. 

Example below changes theme to dark: 
%%{init: { "theme": "dark" }}%%
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }

**Comment by NeilCuzon** [comment]
I have added this to the documentation and will be more visible to users. Thanks for the contribution we really appreciate it, with that I will close this issue. 

https://github.com/mermaid-js/mermaid/blob/master/docs/n00b-syntaxReference.md#diagram-breaking
