### ISSUE TITLE
Migrate flowchart from dagre to elkjs

### ISSUE THREAD

**Issue by redexp** [mermaid-js/mermaid#1969]
Hello, I was playing around with flowchart and really big diagram and find out that `dagre` has a lot issues with blocks positioning (like some blocks that has only one edge to other block in some subgroup unexpectedly far from that group, like across hole diagram) and with edges drawing which goes through other blocks. 

I found good solution - [elkjs](https://www.npmjs.com/package/elkjs) it lot more configurable, smarter and can draw edges around a blocks

**Comment by mestaritonttu** [comment]
Dagre itself was recently declared unmaintained. In its issue tracker, people recommend elkjs or [springy](https://github.com/dhotson/springy) as alternatives.

**Comment by knsv** [comment]
I think we should start with lazy loading in mermaid, this opens up for use of larger libraries

**Comment by richardtallent** [comment]
I'm having an issue with a site built with Vite, looks like it stems from this line in dagre's "greedy-fas" file:

```JS
var Graph = require("./graphlib").Graph;
```

This results in "Uncaught TypeError: Cannot read properties of undefined (reading 'Graph')".

Could be related to this issue. If so, I'd be willing to load the extra 100KB if it means I can keep using Mermaid. For now, I've had to remove it from my build, so my online docs have no fancy diagrams.

**Comment by mestaritonttu** [comment]
In May 2022, a dagre contributor merged a couple of PRs from a new developer (build-related stuff). No announcement or undeprecation notice yet, but at least that is counter to "there won’t be any support or attention to pull requests" :)

elkjs is also still active and releases are being tagged.

**Comment by abitrolly** [comment]
https://github.com/eclipse/sprotty might provide an alternative.

**Comment by EfChouTR** [comment]
We should do this sooner rather than later considering it's a high severity ReDoS

<img width="898" alt="image" src="https://user-images.githubusercontent.com/52469390/193878600-4c20d716-2808-4235-8940-ba65ca651a3f.png">

**Comment by EfChouTR** [comment]
FYI current workaround is to add the following to `package.json`

```
  "resolutions": {
    "d3-color": "^3.1.0"
  }
```

**Comment by KartikSoneji** [comment]
Another issue with depending on dagre-d3 is it needs a browser env to run.
This means a fully headless cli is not possible, and a chrome or chromium instance will always be launched in the background, which is very resource intensive.

Migrating away from dagre might solve this issue.

**Comment by hermanussen** [comment]
It appears elkjs is being used from version 9.4.0 and up. However, since elkjs has an [Eclipse Public License 2.0](https://choosealicense.com/licenses/epl-2.0/) (which is a copyleft license), this forces us (and any commercial closed source users) to use an older version of mermaid-js.

Is there no alternative?

**Comment by abitrolly** [comment]
> Is there no alternative?

The alternative is to fork `dagre` and/or sponsor its development.

**Comment by alinamx** [comment]
> It appears elkjs is being used from version 9.4.0 and up. However, since elkjs has an [Eclipse Public License 2.0](https://choosealicense.com/licenses/epl-2.0/) (which is a copyleft license), this forces us (and any commercial closed source users) to use an older version of mermaid-js.
> 
> Is there no alternative?

 I am facing the same issue right now.

**Comment by hermanussen** [comment]
I'm also not a legal expert. But I think if you put the usage of the Elk library into a separate npm package, that would solve the issue.

In order to avoid the Copyleft license, you would just install the main package. And not the Elk "plugin".

Of course, that would mean that the main package must be usable and useful without the plugin. I'm not familiar enough with mermaid-js to know if that would be possible or not.

**Comment by ted-marozzi** [comment]
> We could move elkjs out to be an external diagram. This would make it possible for a site integrator to add elkjs by registering it when mermaid is initialized.
> 
> I am no legal expert but though, perhaps naively, that the copyleft license only would apply if you go in and make changes in the elkjs code. And that you then need to make those changes available to the original project.

This seems like the consensus [here](https://stackoverflow.com/questions/4925638/can-epl-eclipse-public-licence-be-used-in-commercial-context). I am not a legal expert but from what I can gather we can use elk in commercial software but any modifications to elk must be made public.

**Comment by abitrolly** [comment]
Looks like `dagre` is alive again. https://www.npmjs.com/package/@dagrejs/dagre?activeTab=versions Not sure if the maintainers found the funding.
