### ISSUE TITLE
Line/Bar diargams wanted

### ISSUE THREAD

**Issue by popovoleksandr** [mermaid-js/mermaid#1970]
Thanks for so beautiful project.
Is it possible to add simple diagrams like line or bar? I don't know why it is not here but it would be really helpful.

**Comment by Yokozuna59** [comment]
They're currently working on it here #4269 and discussing the grammar.

You could mark this issue as resolved since it's currently a duplication.

Or if you can @sidharthv96.

**Comment by sidharthv96** [comment]
Thanks @Yokozuna59, closed as duplicate of https://github.com/mermaid-js/mermaid/issues/4269

**Comment by Yokozuna59** [comment]
@sidharthv96 shouldn't be closed as `resolved` with `DUPE` label?
