### ISSUE TITLE
Links in documentation are broken

### ISSUE THREAD

**Issue by shirasal** [mermaid-js/mermaid#1972]
The internal documentation links are broken and lead to an Error 404 page.
**Example:**
[Syntax page](https://mermaid-js.github.io/mermaid/#/./n00b-syntaxReference) has a `Getting started` link in it, but it leads to an error. This happens on other links too.

**Comment by jgreywolf** [comment]
It looks like this may have been resolved.  Can you please check again?

**Comment by shirasal** [comment]
Yes, it works now :)

**Comment by NeilCuzon** [comment]
thanks for the eagle eyed issue. I actually fixed these links quite some time ago. I'll be closing this issue now.
