### ISSUE TITLE
Sequence Diagrams: Message font weight with can only be bolder, not lighter

### ISSUE THREAD

**Issue by beatrizsanchez** [mermaid-js/mermaid#1976]
**Describe the bug**
In sequence diagrams, the font weight of messages has a look that feels bold.
The problem is that we cannot use the configuration to make it normal, but it does respond if we want to make it bolder.

**To Reproduce**
Render an arbitrary sequence diagram such as:
```
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
```
use the following settings to toggle the messageFontWeight value between "normal" and "bold". You can even try with "light", "lighter" and it will remain looking bold (compared for example to the font used in the actors)
```
{
	"sequence": {
		"messageFontFamily": "arial",
		"messageFontWeight": "normal",
		"messageFontSize": 14
	}
}
```

**Expected behavior**
I would expect the text to be by default bold and allow users to set it to normal. But I get the feeling that "normal" has as "bold" feel and we can only make it bolder, not lighter. 

**Screenshots**
Using normal font weight
<img width="467" alt="Screenshot 2021-04-07 at 18 16 42" src="https://user-images.githubusercontent.com/6515216/113907661-8c211400-97cd-11eb-8b67-a757b4dae9c3.png">

Using bold font weight
<img width="492" alt="Screenshot 2021-04-07 at 18 16 15" src="https://user-images.githubusercontent.com/6515216/113907670-8dead780-97cd-11eb-9b05-77e918ea6665.png">

**Desktop (please complete the following information):**
 - OS: MacOS BigSur (mermaid Cli v. 8.9.2)

**Comment by wkotlowski** [comment]
I have the similar problem, but instead of using the words: normal, or bold, I had tried using numbers as the default value is 400. I've set it to 10, 50, 100, 200 and there is no effect.

**Comment by wkotlowski** [comment]
@beatrizsanchez There is a stroke setting that messes up the weight. We solved the issue by adding a css styling to the diagram:

```
.mermaid {
            display: flex;
            justify-content: center;
            margin-bottom: 16px;

            & > svg {
                max-height: 800px !important;
                max-width: 600px !important;

                .messageText {
                    stroke: none !important;
                }
            }
        }
```

**Comment by dverbru** [comment]
Reproducible in the online live editor as well.

**Comment by dverbru** [comment]
@knsv does the workaround from @wkotlowski make sense? Does it help to identify the cause of the issue?

**Comment by FabAlchemy** [comment]
For now, the solution is indeed to reset the `stroke` attribute to `none` for `.messageText`:

```css
.messageText {
    stroke: none !important;
}
```

In fact, I think the bug is at the following line. In the same file, the other text-related classes set `stroke: none`.

https://github.com/mermaid-js/mermaid/blob/1c3f94c9ec66e5e61752a75361019336edb975af/src/diagrams/sequence/styles.js#L48
