### ISSUE TITLE
Unable to use # or ; in gantt diagram

### ISSUE THREAD

**Issue by huineng** [mermaid-js/mermaid#1981]
this doesn't work 

```
gantt
    title HASHTEST
THIS#HASH  :2021-04-03 11:06:07, 2sec
```
escaping is also not possible not quoting the text

Just put a # or ; in the THISHASH and you can see the parsing error

https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbiAgICB0aXRsZSBIQVNIVEVTVFxuVEhJU0hBU0ggIDoyMDIxLTA0LTAzIDExOjA2OjA3LCAyc2VjIiwibWVybWFpZCI6e30sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

thanks

**Comment by olekhov** [comment]
Hi! I've just bumped into the same problem. Luckiliy, the solution is described [here](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=entity-codes-to-escape-characters)
You can just use `#35;` for # sign and `#59;` for `;`

**Comment by huineng** [comment]
any update on this ?

**Comment by huineng** [comment]
technically this should be an easy fix , but getting close to a year . 
Thanks to check if this is possible

**Comment by huineng** [comment]
any update ?

**Comment by maximal** [comment]
Alongside with `#` in titles, task headers cannot have `#`, `%`, `;`, or `:`.

I think we need to have an escaping syntax for them. Like:

```
gantt
    title "project title with \", #, and other special characters"
    "task title with \", #, and other special characters"  :2021-04-03 11:06:07, 2sec
```

**Comment by pcolby** [comment]
In my testing, against the current Live Editor (v10.3.0), these are the ones that currently don't work:

* `;` can't be used in any of the `title`, `section` or task names
* `:` can't be used in `section` or task names, but can be used in `title`
* `#` can't be used in task names, and while it won't crash in `title` and `section` it will cause those to be truncated that the first `#`

Would love to know if anyone finds any other chars that need special handling while we wait for a fix 😄 

Thanks.

**Comment by FutzMonitor** [comment]
This seems to be a duplicate/connected with issue #1817. Should these two be connected or should a greater issue be generated to encompass all characters that cannot be used in Gantt labels?

**Comment by FutzMonitor** [comment]
I would like to try tackling this issue.

**Comment by FutzMonitor** [comment]
Is there any reason why on [line 89](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/diagrams/gantt/parser/gantt.jison#L89) the parser excludes semicolons and hash symbols? I'm trying to better understand the Jison parser responsible for parsing through the Gantt syntax.
