### ISSUE TITLE
Randomly missing arrow heads

### ISSUE THREAD

**Issue by sadata7** [mermaid-js/mermaid#1985]
**Describe the bug**
Arrows are missing on the rendered output where a --> relationship is specified. Changing the length of the arrow (e.g. ---> or ------>) makes no difference. It's seemingly unpredictable where the problem will occurs.  The screenshot below is a small corner of a 400-element family tree diagram and shows 4 spots where the arrows are missing.  I counted about 15 missing overall.  I should also point out that the problem seems even worse when 'graph' (straight connectors) is used instead of 'flowchart' (curved connectors). No idea why this would be the case.

**To Reproduce**
The only way to reproduce the behavior is to create a very large graph (about 400 elements) that are fairly evenly distributed.  I can't post the family tree as it contains personal data, but I am willing to help debug the issue.

**Expected behavior**
Arrows should be present wherever the --> relationships are shown in the mermaid markup.

**Screenshots**
The red circles below show where arrows are missing where an arrow relationship is specified in the markup:
 
![Selection_040](https://user-images.githubusercontent.com/80186985/114660219-ebe25800-9cc2-11eb-8212-924be700a57d.png)

**Desktop (please complete the following information):**
 - any
 
**Smartphone (please complete the following information):**
 - any
 
**Additional context**

**Comment by sidharthv96** [comment]
Can you try to reproduce the issue in https://beta.mermaid.live ?
We have released a fix for marker ends recently. 

Also, please provide a sample data without the personal details for us to recreate the issue.

**Comment by sidharthv96** [comment]
I used ChatGPT to draw this, and all the arrows are present. 

[Live Editor Link](https://mermaid.live/edit#pako:eNptmF1T4koQhv-KlWvXXUDU5eJU9SRRQfELRGU8FwMZIWdDYoWwZ7Nb_vfT0z2R1Jnxyn5oMjPd_ead4k-wLBIdDIJVqd7XB9PoNQc5Ktb53wdfvvx1IOj_g1F59Dd-QCiUI5VrDCM5VmVt8ujvr4OYgE2OKPlcjtMfJllQeMGPGw6Hn-hSjtIswzCkcCjDdVboz3iEcZluMY4pvsI1VqtUf4Jrs2iV5gjOCYxxyeVaZ5n-RDcm5weGFxTeSlGmKrex3fydFJlKS4SXlHQvL1Weq7UFNusBaVlkCdIhpU3kRG0-oylGeVIqBCMCj3K02_LuGMzkLF1WBa6P6IrQk7zaldVn-CyvVGX2fk3hi7zWeV5_xnM5V7TAmEIACRtcs0WEBNyjWfKGQShv0lzt40je6NSU_JbjWN5m6U9d7sk5EdrjHZMLeadpVza-lHeqKtMl5dwzG8r7XZrnezCS97zXB46v5ENNdbfxtXzQC71cmpQJo7GcVPqn3oMbOVnb40yZ3MpputmHd3JaqqUp0CODe_mY1dut3u7Rg3zcmEVmHE6wCflS78FUzjRt9InjR_mkylLnezJDwlV-ZvAknxFQ0Sx5ls86p3q8MHiRLzhC6fLHHs3li97arDkrDLChpCcbCznXGa0ELDgRSsiobA2IENB5gDUkYgQLTUPUoHNE6ZbqBiwlcSEhT-oWuERAgwGsVjGUkCa8lCUjCTyrwHITVwhyVkCDriVs15mmJ7PgxFjCL521wI2E95KGDliE4lZCQtJpwB1O8oIKCixBcY9rVetdGz2YY1HrgCUnJkj0sgWmEnCYaTesOfFoDl7qFpmZk9NbBFh14skcgle35FnCDr9FD2LtiRdEVs4NmiOqdhtCLMAQJZlXBWm2QajJfKUzKiSrMAxZpt0WijgrJUEAazHE3ib2ddUg7O0qp_kGlmOIrV1wvS24NNU1MUsxHJrjVTwOFmFrtyhh6iQLMsTmZm-lbqNrU3AeElZkOLbDVrQYtjcr7JsPWJghNnhRqjX32DLscWLLwNIM76VAqdUt8iAFHpdrwPoMJ1Lo3A6zRVNE9AaiJrJKw0d82K-Ku2jRDPPYC4B1Gj7h61_ndswtezZvf7smSzV8MYi8qyFz9g1KYrFGQM-qWkQgUSwzwXKNQilqfoM1JMKkmt6UguUaxeZrCYuoYedmvWSlzeMFSza6MJVIqfYNujQnTPnlJFi20ZCqqquqxUaYt8vI0QQrN7qSoqiTFrjGQ6dbM1mChRuNcRMFvcIacsNOaQZXsHSjW9r9W1EmLYiOqqu1Ih0Ilm-E3f6nKPMWMd3OMpKiYAFHE3PuZZtMTb1YUYIVHGGry11etMjM9IK-xQKOqNFcAkuezZOriirF-o1eDFrxlDaMGm2XYwHH2GiVJf-S9BtmWp1uNd1OBEs4Dqnw3GyLIkqrCiNPwQqOsd1qm7YJNlttFqkhLOGYWq0TvC604CUP6prOyUKOsdkox5KPYJlpdpnbKrKU4yublycteG1gTTthLcdjK7Zui93wXBBiKce35qTLTNUtZi5RdcWbYzXHpO-c59qiB3OG35TEYo4n1Mx1SrbSQGy6qhWPFIs5fjRb47dYg2a2CTz-LOf4iRZVi7rFbO8NYT3H2HrNk23B3GqXjsl6Pgd-FG_DMmr8yg6SNWVwbBocnwaPUYPHqcGxanC8GlyzBsetwWPX4PFrcAwbXMcGx7LB9WzwmDa4rg2ObYPr2-AaN7jODa51g8e7wWPe4HFv8Ng3ePwbPAYOXgcHj4WD6-HgmDj838XBY-Pg8XHwGDm4Tg4-Kwefl4PPzMF1c3DtHDx-Dh5DB6-jg8fSwfV08Jk6eFwdXFsHj6-Da-zgcXZwrR1cbwefuYPP3cFj7-Dzd_AZPHgcHhyLB9fjwTV58Lg8eG0efD4PrtGDx-nBtXrweD24Zg-O24Nr9-Dxe_AZPngcH3yWDz7PB4_pg8_1wbV9cH0fvMYPPucHn_WDz_vBa_7guj_47B88_g--CwB4bgDguQKAewcA7yUAPLcA8FwDwHsPAN9FANybADhXAfDdBcB3GYD2bSA4DDa63Kg0CQbBn9f84OA1wGJs9GswwH8T_aZ2WfUavOYfmLp7T1Sl4wT1XgaDN5Vt9WGgdlUxqfNlMKjKnW6SolStsMufWe8qnxfFpknCMBj8CX4Fgy_9_vej49N-p3928r1z_O2kexjUwaDT7x91-qenx_3eSafXPet0Pw6D3_SE3tFx71un_w0_wi_1zjqHgaYtjfmHQfp98DDICpXo0qxS1e_0gyFON_Jlkb-lK8N3ZYZ4XVXv28HXr-bjI6zKerc4Whabr9s0WSu8GPz8fvL1pHtypro9fXLaU_1eL1kuOt_P3rrHnbfk9Funq4KPj4__AIoXRaU)

```mermaid
graph TD
A[John] --> B[John Jr.]
A --> C[Jane]
D[Mary] -------> E[Mary Jr.]
D --> F[Mike]
B --> G[John III]
B --> H[Jill]
C --> I[Chloe]
C --> J[Chris]
E --> K[Maggie]
E --> L[Martin]
F --> M[Michelle]
F --> N[Mark]
G --> O[Brian]
G -------> P[Blair]
H --> Q[Hannah]
H -------> R[Harold]
I --> S[Sam]
I --> T[Sandra]
J --> U[Justin]
J --> V[Victoria]
K --> W[Kurt]
K --> X[Kate]
L --> Y[Lenny]
L --> Z[Zara]
M --> AA[Amanda]
M --> AB[Aaron]
N --> AC[Nina]
N --> AD[Neil]
O --> AE[Oliver]
O --> AF[Olivia]
P --> AG[Pete]
P --> AH[Patricia]
Q --> AI[Quinn]
Q --> AJ[Qara]
R --> AK[Ryan]
R --> AL[Rebecca]
S --> AM[Steve]
S --> AN[Sharon]
T --> AO[Tim]
T --> AP[Tracy]
U --> AQ[Ulysses]
U --> AR[Uma]
V --> AS[Vince]
V --> AT[Vera]
W --> AU[Warren]
W --> AV[Wanda]
X --> AW[Xander]
X --> AX[Xenia]
Y --> AY[Yannick]
Y --> AZ[Yesenia]
Z --> BA[Zane]
Z --> BB[Zelda]
AA --> BC[Alan]
AA --> BD[Alma]
AB --> BE[Albert]
AB --> BF[Alison]
AC --> BG[Andy]
AC --> BH[Anna]
AD --> BI[Aidan]
AD --> BJ[Aria]
AE --> BK[Arnold]
AE --> BL[Ashley]
AF --> BM[Axel]
AF --> BN[April]
AG --> BO[Adam]
AG --> BP[Amber]
AH --> BQ[Arthur]
AH --> BR[Alice]
AI --> BS[Alec]
AI --> BT[Avery]
AJ --> BU[Andre]
AJ --> BV[Annie]
AK --> BW[Asher]
AK --> BX[Audrey]
AL --> BY[Austin]
AL --> BZ[Autumn]
AM --> CA[Antony]
AM --> CB[Angela]
AN --> CC[Aaron2]
AN --> CD[Angelica]
AO --> CE[Adrian]
AO --> CF[Agnes]
AP --> CG[Abel]
AP --> CH[Ada]
AQ --> CI[Ashton]
AQ --> CJ[Astrid]
AR --> CK[Alfred]
AR --> CL[Alina]
AS --> CM[Alberto]
AS --> CN[Alondra]
AT --> CO[Abraham]
AT --> CP[Adela]
AU --> CQ[Barry]
AU --> CR[Bianca]
AV --> CS[Benson]
AV --> CT[Beatrice]
AW --> CU[Baxter]
AW --> CV[Belle]
AX --> CW[Brendan]
AX --> CX[Blanca]
AY --> CY[Blake]
AY --> CZ[Briana]
AZ --> DA[Brent]
AZ --> DB[Brandy]
BA --> DC[Byron]
BA --> DD[Brynn]
BB --> DE[Bradley]
BB --> DF[Bridget]
BC --> DG[Benito]
BC --> DH[Belinda]
BD --> DI[Barrett]
BD --> DJ[Beulah]
BE --> DK[Boyd]
BE --> DL[Bliss]
BF --> DM[Brock]
BF --> DN[Blair2]
BG --> DO[Bradford]
BG --> DP[Bethany]
BH --> DQ[Bjorn]
BH --> DR[Billie]
BI --> DS[Brice]
BI --> DT[Bryony]
BJ --> DU[Bruno]
BJ --> DV[Bree]
BK --> DW[Brett]
BK --> DX[Britta]
BL --> DY[Brigham]
BL --> DZ[Briony]
BM --> EA[Baldwin]
BM --> EB[Briseis]
BN --> EC[Barron]
BN --> ED[Bristol]
BO --> EE[Basil]
BO --> EF[Bambi]
BP --> EG[Benedict]
BP --> EH[Blanche]
BQ --> EI[Bertram]
BQ --> EJ[Bernice]
BR --> EK[Bertrand]
BR --> EL[Beryl]
BS --> EM[Benson2]
BS --> EN[Bliss2]
BT --> EO[Barclay]
BT --> EP[Blythe]
BU --> EQ[Barney]
BU --> ER[Blaze]
BV --> ES[Brunhild]
BV --> ET[Bayard]
BW --> EU[Benton]
BW --> EV[Briseida]
BX --> EW[Barnaby]
BX --> EX[Britt]
BY --> EY[Beck]
BY --> EZ[Brandy2]
BZ --> FA[Barnard]
BZ --> FB[Brigitta]
AA --> ABC[Alan]
AA --> ABD[Alma]
AB --> ABE[Albert]
AB --> ABF[Alison]
AC --> ABG[Andy]
AC --> ABH[Anna]
AD --> ABI[Aidan]
AD --> ABJ[Aria]
AE --> ABK[Arnold]
AE --> ABL[Ashley]
AF --> ABM[Axel]
AF --> ABN[April]
AG --> ABO[Adam]
AG --> ABP[Amber]
AH --> ABQ[Arthur]
AH --> ABR[Alice]
AI --> ABS[Alec]
AI --> ABT[Avery]
AJ --> ABU[Andre]
AJ --> ABV[Annie]
AK --> ABW[Asher]
AK --> ABX[Audrey]
AL --> ABY[Austin]
AL --> ABZ[Autumn]
AM --> ACA[Antony]
AM --> ACB[Angela]
AN --> ACC[Aaron2]
AN --> ACD[Angelica]
AO --> ACE[Adrian]
AO --> ACF[Agnes]
AP --> ACG[Abel]
AP --> ACH[Ada]
AQ --> ACI[Ashton]
AQ --> ACJ[Astrid]
AR --> ACK[Alfred]
AR --> ACL[Alina]
AS --> ACM[Alberto]
AS --> ACN[Alondra]
AT --> ACO[Abraham]
AT --> ACP[Adela]
AU --> ACQ[Barry]
AU --> ACR[Bianca]
AV --> ACS[Benson]
AV --> ACT[Beatrice]
AW --> ACU[Baxter]
AW --> ACV[Belle]
AX --> ACW[Brendan]
AX --> ACX[Blanca]
AY --> ACY[Blake]
AY --> ACZ[Briana]
AZ --> ADA[Brent]
AZ --> ADB[Brandy]
BA --> ADC[Byron]
BA --> ADD[Brynn]
BB --> ADE[Bradley]
BB --> ADF[Bridget]
BC --> ADG[Benito]
BC --> ADH[Belinda]
BD --> ADI[Barrett]
BD --> ADJ[Beulah]
BE --> ADK[Boyd]
BE --> ADL[Bliss]
BF --> ADM[Brock]
BF --> ADN[Blair2]
BG --> ADO[Bradford]
BG --> ADP[Bethany]
BH --> ADQ[Bjorn]
BH --> ADR[Billie]
BI --> ADS[Brice]
BI --> ADT[Bryony]
BJ --> ADU[Bruno]
BJ --> ADV[Bree]
BK --> ADW[Brett]
BK --> ADX[Britta]
BL --> ADY[Brigham]
BL --> ADZ[Briony]
BM --> AEA[Baldwin]
BM --> AEB[Briseis]
BN --> AEC[Barron]
BN --> AED[Bristol]
BO --> AEE[Basil]
BO --> AEF[Bambi]
BP --> AEG[Benedict]
BP --> AEH[Blanche]
BQ --> AEI[Bertram]
BQ --> AEJ[Bernice]
BR --> AEK[Bertrand]
BR --> AEL[Beryl]
BS --> AEM[Benson2]
BS --> AEN[Bliss2]
BT --> AEO[Barclay]
BT --> AEP[Blythe]
BU --> AEQ[Barney]
BU --> AER[Blaze]
BV --> AES[Brunhild]
BV --> AET[Bayard]
BW --> AEU[Benton]
BW --> AEV[Briseida]
BX --> AEW[Barnaby]
BX --> AEX[Britt]
BY --> AEY[Beck]
BY --> AEZ[Brandy2]
BZ --> AFA[Barnard]
BZ --> AFB[Brigitta]
```

**Comment by anlai46** [comment]
This issue is labeled "Close after 30 days" but it is still open. Does this issue still persist?
