### ISSUE TITLE
Links Now Using Curved Instead of Straight Since 8.9.2.

### ISSUE THREAD

**Issue by geoffblandrbs** [mermaid-js/mermaid#1994]
We have upgraded from mermaid.js 8.9.1 to 8.9.2 and noticed that many links instead of being displayed with straight lines now show with curved lines. The curved lines do not look very good as they curve back on themselves too far and too close to the arrowheads on the ends of lines.

I will attach screenshots for an example.

**Comment by geoffblandrbs** [comment]
![mermaid 8 9 1  version](https://user-images.githubusercontent.com/6451079/115555394-5c7f0b00-a2a7-11eb-8e8d-836d68aaa723.PNG)

As it was in 8.9.1.

**Comment by geoffblandrbs** [comment]
![mermaid 8 9 2  version](https://user-images.githubusercontent.com/6451079/115555444-6acd2700-a2a7-11eb-9fff-378c9b316589.PNG)

As it is now in 8.9.2.

**Comment by sadata7** [comment]
It looks like "flowchart" uses curves now, but I think you can set it to "graph" to get the original straight lines.

**Comment by geoffblandrbs** [comment]
_It looks like "flowchart" uses curves now, but I think you can set it to "graph" to get the original straight lines._

I'm not sure what you mean by that, as far as I know I am using "graph". At least that is the keyword I am using at the start of the mermaid code.

For reference here is the full mermaid code for our diagram.

`graph TD
  classDef ok color:black,fill:lightgreen,stroke:darkgreen,stroke-width:4px,text-align:left,font-size:100%,font-weight:normal,line-height:unset
  classDef error color:lightyellow,fill:red,stroke:darkred,stroke-width:4px,text-align:left,font-size:100%,font-weight:normal,line-height:unset
  classDef error_text color:black,fill:#ffd800,stroke:darkred,stroke-width:4px,text-align:left,font-size:100%,font-weight:normal,line-height:unset
  classDef info text-align:left,font-size:100%,font-weight:normal,line-height:unset
  
  NODE_0(Xxxxxx: X<br/> XXXXXX XXX XXXXXX: XXXXXX_X<br/> XXXX XXX Xxxxxx: XXXXXXX_X)
  class NODE_0 info

  NODE_1("<strong>Xxxxxxx Xxxxxxx Xxxxx (XXX)</strong><br/>xxxxxxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxx.xxxxxxx")
  click NODE_1 nodeCallback
  class NODE_1 ok

  NODE_2("<strong>Xxxxxxxxxxxxxx Xxxxx</strong><br/>xxxxx.xxx.xx.xxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx")
  click NODE_2 nodeCallback
  class NODE_2 ok

  NODE_3("<strong>Xxxxxx Xxxxx to Xxxxxx Xxxxxxxx (XXXX) Xxxxxx</strong><br/>xxxxx.xxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.x<br/>  --->xxxxx.xxxx.xx.xxxxxx.xxxxxx.xxxxxxxxxxxxxxx.xxxxxxx")
  click NODE_3 nodeCallback
  class NODE_3 ok

  NODE_4("<strong>Xxxxxx Xxxxxxx</strong><br/>xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxxxxx")
  click NODE_4 nodeCallback
  class NODE_4 ok

  NODE_5("<strong>Xxxxxx Xxxxxxxxxx (XXXX) Xxxxx</strong><br/>xxxxx.xxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxxx")
  click NODE_5 nodeCallback
  class NODE_5 ok

  NODE_6("<strong>Xxxxxxxxxxxxxxxx Xxxxx xx Xxxxx Xxxxxxxxx (XXXX) Xxxxxx</strong><br/>xxxxx.xxxx.xx.xxxxx.xxxxx.xxxxxxxxxxxxxx.xxxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxx<br/>  --->xxxxx.xxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxx")
  click NODE_6 nodeCallback
  class NODE_6 ok

  NODE_7("<strong>Xxxx Xxxxxx</strong><br/>xx.xxxxxx.xxxxx.xxxxxxxxxxx")
  click NODE_7 nodeCallback
  class NODE_7 ok

  NODE_8("<strong>Xxxxxx Xxxxx xx Xxxxx Xxxxx Bridge</strong><br/>xxxxx.xxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.x<br/>  --->xxxxx.xxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxx.x")
  click NODE_8 nodeCallback
  class NODE_8 ok

  NODE_9("<strong>Xxxx Xxxxxx</strong><br/>Xx xxx xxxxxx xxxxxx")
  click NODE_9 nodeCallback
  class NODE_9 ok

  NODE_10("<strong>Xxxxxx Xxxxx</strong><br/>xxxxx.xxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.x")
  click NODE_10 nodeCallback
  class NODE_10 ok

  NODE_11("<strong>Xxxxx Xxxxx</strong><br/>xxxxx.xxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxx.x")
  click NODE_11 nodeCallback
  class NODE_11 ok

  NODE_12("<strong>Xxxxxx Xxxx Xxxxx (XXX) Xxxxx</strong><br/>xxxxx.xxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.x")
  click NODE_12 nodeCallback
  class NODE_12 ok

  NODE_13("<strong>Xxxxxx Xxxxx to Xxxxxx Xxxx Xxxxx (XXX) Xxxxx Xxxxxxx</strong><br/>xxxxx.xxxxxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.x<br/>  --->xxxxx.xxx.xx.xxxxxx.xxxxx.xxxxxxxxxxxxxxx.xxxxxxx.x")
  click NODE_13 nodeCallback
  class NODE_13 ok

      NODE_14[Xxxxxx Xxxxxx<br/>XXXXXXXX_XXX]
      NODE_15[Xxxxxxxx Xxxxxx<br/>XXXXXXX_XXX]
      NODE_16[Xxxxxxxxxxxxxxx Xxxxxx<br/>XXXXXXXXXXXXXXXX_XXX]
      class NODE_14 info
      class NODE_15 info
      class NODE_16 info

  NODE_4  -.-> NODE_10
  NODE_10 -.-> NODE_9
  NODE_9 -.-> NODE_8
  NODE_8 ==> NODE_11
  NODE_10 ==> NODE_3
  NODE_3 ==> NODE_1
  NODE_10 ==> NODE_13
  NODE_13 ==> NODE_12

  NODE_12 ==> NODE_14
  NODE_12==> NODE_15

  NODE_11 -.-> NODE_7

  NODE_7 -.-> NODE_2
  NODE_2 ==> NODE_6
  NODE_6 ==> NODE_5
  NODE_2 ==> NODE_16
`

**Comment by geoffblandrbs** [comment]
Here's the full diagram, this used to look fine until 8.9.1 but with 8.9.2 there are many curved links that curve back on themselves the arrow heads are no longer aligned correct. Some of the arrow heads are rotated so far they almost look like they are pointed the wrong way.

![full_mermaid 8 9 2 version](https://user-images.githubusercontent.com/6451079/116044327-af224380-a668-11eb-9ec3-63930caa4c0f.PNG)

**Comment by geoffblandrbs** [comment]
A workaround is to change back the curve setting from 'natural' to 'linear' (line 52218) in the 8.9.2 code.

I think if curved links are to be used then they needs to be some work done to make the curved lines and arrows display in a better way.

It may also be nice to have an option to turn on/off curved lines for links.

**Comment by sadata7** [comment]
> I'm not sure what you mean by that, as far as I know I am using "graph". At least that is the keyword I am using at the start of the mermaid code.

Here's what I get and what I was referring to:

![Selection_053](https://user-images.githubusercontent.com/80186985/116095241-3de98d00-a676-11eb-9a75-91c35c9210c8.png)

**Comment by geoffblandrbs** [comment]
> > I'm not sure what you mean by that, as far as I know I am using "graph". At least that is the keyword I am using at the start of the mermaid code.
> 
> Here's what I get and what I was referring to:
> 
> ![Selection_053](https://user-images.githubusercontent.com/80186985/116095241-3de98d00-a676-11eb-9a75-91c35c9210c8.png)

As seen in my reply above I am using 'graph'.

However checking the mermaid code there is no difference between 'flowchart' and 'graph'. With the above code even with setting the chart type to 'graph' the `flowchart` configuration starting at line 52169 is still used. Line 52219 sets the lines to curved. Patching this line to set the lines to linear is works as a temporary fix for the problem. In the detectType(text) function there is no defined `graph` type - setting `graph` as the chart type will default to ` flowchart'. 

Are you sure you are using version 8.9.2 in your example, the issue only shows up in the latest release?

**Comment by geoffblandrbs** [comment]
Upgraded to Mermaid 9.1.1 and this issue now appears to be fixed.
