### ISSUE TITLE
classDiagram, additonal qualifier in class data member name 

### ISSUE THREAD

**Issue by whuji** [mermaid-js/mermaid#2010]
Hello, 

I would like to know how (if possible) to specify some qualifers (as const or static for class static members, etc.) in a class diagram : 

For example : 
```
classDiagram
class ContextManager {
	-static log_handler_pt *log_handler
	-const char *name
}
```

![2021-04-25-181444_197x108_scrot](https://user-images.githubusercontent.com/2234501/116000849-28328400-a5f2-11eb-88da-4420940997d6.png)

For both those members, the name is hidden. Is there any possibility to have more than 1 word for the type ?

Thanks

**Comment by jgreywolf** [comment]
Looking into this

**Comment by Polirecyliente** [comment]
My 'poor man's' workaround, is to do:

``` mermaid
classDiagram
  class class1 {
  +static_const__Variable1
  }
```

So the double underscore `__` separates the modifiers like static and const, from the name of the variable, in this case `Variable1`.

**Comment by manisai216** [comment]
Hi, 

I want to take this up. Is it still available? I am new to open source contribution. Any help is appreciated.

**Comment by whuji** [comment]
Hello @manisai216 , it is still available.
I *think* (but I don't develop on mermaid) that some solutions could be :

1. to extend the type directive,
2. to handle annotations for class members (with << >> but not very elegant),
3. to create a new directive (maybe type specifiers ?),
4. to allow spaces in type directive,

I imagine that the magic takes place in src/diagrams/class/parser/classDiagram.jison.

Thanks !

**Comment by RonaldZielaznicki** [comment]
I'd just like to state that I'm for this as well.

My use case is not quite the same. I am setting up an Entity Relationship diagram, and I wanted to show the type as the same as what it would be in mariaDB. Which would be something like... varchar(36). But, it seems that mermaid only support alpha-numerics.

**Comment by VladimirAlexiev** [comment]
Note that `$` is used as Static annotation on a method, e.g. `someStaticMethod()$`.
I think the right way would be to use the same `$` to annotate a static member.
Try this:
```
classDiagram
    class Foo {
      noStaticMember$
      normalMethod()
      abstractMethod()*
      staticMethod()$
    }
```
![image](https://user-images.githubusercontent.com/536250/159650895-1af0c54b-7133-40f8-87a7-8a40eebdfa5d.png)

**Comment by jgreywolf** [comment]
Im thinking that I did not read/understand the original issue at all.  In regards to marking a member (attribute or method/function) as static or abstract, the syntax mentioned by @VladimirAlexiev is the correct path.  This will underline or italicize the text as appropriate.

I am going to close this as complete, since the work to recognize statics for attributes has already been completed
