### ISSUE TITLE
Has gitGraph feature/documentation been removed?

### ISSUE THREAD

**Issue by AllanXu49** [mermaid-js/mermaid#2011]
I found that memaid includes gitgraph diagram here:

https://wraith13.github.io/writing/?%40demo%2Fmermaid.md#git-graph-source

However, I am not able to find any trace of gitgraph diagram feature anywhere on mermaid documentation here: https://mermaid-js.github.io/mermaid 

Has gitGraph feature been removed or deprecated?

**Comment by knsv** [comment]
It is currently dormant as it is not robust enough. We are about to rework it but as the syntax might change slightly we don't want to push the graph right now.

I hope that will not cause any inconveniences.

**Comment by AllanXu49** [comment]
Thank you for the update.
