### ISSUE TITLE
Integration documentation shouldn't endorse Chrome (misses other browsers)

### ISSUE THREAD

**Issue by toastal** [mermaid-js/mermaid#2019]
**Describe the bug**
The `docs/integrations.md`only lists Chrome and endorses Chrome. I don't think this is the correct approach.

**To Reproduce**
1. visit https://mermaid-js.github.io/mermaid/#/integrations?id=chrome-extensions

**Expected behavior**
I would expect to see the heading "Browser Extensions" and list or table of something like

#### Brower Extensions
| Name | Chrome Web Store | Firefox Add-ons | Safari App Store | etc. | Source/Repository | 
| -- | -- | -- | -- | -- | -- |
| GitHub + Mermaid | [🎡🔗](https://chrome.google.com/webstore/detail/github-%20-mermaid/goiiopgdnkogdbjmncgedmgpoajilohe) | [🦊🔗](https://addons.mozilla.org/firefox/addon/github-mermaid/) | - | - |  [🐙🔗](https://github.com/BackMarket/github-mermaid-extension)
| etc. | etc. | etc. | etc. | etc. | etc. |

a list with links for supported stores is also be acceptable, but I don't think it's okay to say anything except "Browser Extensions" just like above it is a section "Text Editors" and not "Emacs" and perhaps the stores are a better listing than any browser in particular.

**Comment by NeilCuzon** [comment]
This is a very good suggestion. Thank you.

**Comment by NeilCuzon** [comment]
I think the solution fixes this issue adequately, as such I will be closing this now.
