### ISSUE TITLE
Classes with links do not use bold font style

### ISSUE THREAD

**Issue by wouterbeek** [mermaid-js/mermaid#2023]
**Describe the bug**

When classes are specified to have a link, their font style becomes regular i.o. bold.

When some classes have a link and some other classes do not, the overall class diagram looks strange because some classes have bold font style while others have regular font style.

Readers of the Mermaid diagram may interpret the fact that some classes have bold font style as signifying that these classes are more important or are otherwise significantly different from classes that have regular font style.  But this is not the case, the only difference is that some classes have links.  (And the fact that a class has a link does not decrease its importance for the overall visualizations.)

**To Reproduce**

1. Visualize the following Mermaid string.  Notice that the two class have a different font style.

```mermaid
classDiagram
  class Person
  class Monkey
  link Monkey "https://aap.nl" "tooltip"
```

**Expected behavior**

I expect classes without a link to not look "more important" or "more visible" than classes with a link.

Specifically, I expect all classes to have bold font style, regardless of whether they have a link or not.

If the fact that a class has a link must somehow be visually communicated, then there are other ways of doing so that are more common and more appropriate than changing the font style.  For example, classes with a link could have bold font style and be underlined, or they could have a link icon displayed next to their bold name.  (Both approaches are common in web browsers.)

**Screenshots**

Readers of the following diagram interpret "Person" to be somehow more important than "Monkey", but this is not necessarily the intent of the creator of the diagram.  The only difference is that the monkey class can be clicked since a link has been specified for it.

![Screenshot from 2021-04-30 01-53-06](https://user-images.githubusercontent.com/1685012/116632239-f81f1400-a956-11eb-8a48-f41aec2e07f1.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 2021.4
 - Browser: Chrome 90.0.4430.93 (Official Build) (64-bit
 - Version: 8.9.0

**Comment by jgreywolf** [comment]
Closing as this no longer reproduces
