### ISSUE TITLE
Syntax Error, when using common legal symbol: §

### ISSUE THREAD

**Issue by mkschulze** [mermaid-js/mermaid#2033]
**Describe the bug**
A syntax error is thrown as soon as I use a common symbol for legal paragraphs: §

**To Reproduce**
``` 
graph TD
    B["test"]
    B-->C(test 1: gem. § 10 UStG)
    B-->D(test);
    B-->E(test);
```

**Expected behavior**
It should not throw a syntax error.

**Screenshots**

![Bildschirmfoto 2021-05-01 um 18 10 03](https://user-images.githubusercontent.com/3390820/116788163-750dd300-aaa8-11eb-874d-f0e1a1d1b327.png)
em.

**Code Sample**
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBCW1widGVzdFwiXVxuICAgIEItLT5DKHRlc3QgMTogZ2VtLiAgMTAgVVN0RylcbiAgICBCLS0-RCh0ZXN0KTtcbiAgICBCLS0-RSh0ZXN0KTsiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ

**Additional context**
Maybe it could be solved with Unicode support? #1995

**Comment by Yokozuna59** [comment]
You could just wrap it between doable quotes.

```
graph TD
    B["test"]
    B-->C("test 1: gem. § 10 UStG")
    B-->D(test);
    B-->E(test);
```

```mermaid
graph TD
    B["test"]
    B-->C("test 1: gem. § 10 UStG")
    B-->D(test);
    B-->E(test);
```
