### ISSUE TITLE
Can change wiring to horizontal and vertical?

### ISSUE THREAD

**Issue by Ikki-Dai** [mermaid-js/mermaid#2050]
**Is your feature request related to a problem? Please describe.**
it looks a little messy when a flowchart or graph have too many nodes.

**Describe the solution you'd like**
if the wiring aways be horizontal or vertical, it looks much better

**Describe alternatives you've considered**

**Additional context**

**Comment by knsv** [comment]
There will be an update so that it is possible to select rendering direction for some subgraphs.

**Comment by jgreywolf** [comment]
Closing this as it is "resolved" with the feature to set direction in subgraphs. Also, there is an open issue in linked item #2410
