### ISSUE TITLE
Support more columns in Entity Relationship Diagrams

### ISSUE THREAD

**Issue by eeriksp** [mermaid-js/mermaid#2070]
**Is your feature request related to a problem? Please describe.**
I use Mermaid entity relationship diagrams to model my relational database. Right now the diagram supports only two columns: one for the datatype and another for the field name. However, I would often need to include more information: for instance constraints such as `PK`, `U` `N` for primary key, unique and nullable, respectively. In some cases it would also be good to include a free-form comment as a separate column.

**Describe the solution you'd like**

Given an example diagram

```
erDiagram
    CreativeWork {
      TEXT name 
      TEXT description
      TEXT reference
    }
```

I would like the following syntax to be permitted:

```
erDiagram
    CreativeWork {
      TEXT name PK
      TEXT description
      TEXT reference N
    }
```
So I would like to remove the constraint than there can be only two columns on a diagram. Instead a new column could start whenever a space character is detected. If some rows have fewer columns (like `TEXT description` having only two columns whereas other rows have three), the missing columns in the end could simply be considered to be empty.

If I want to mark an empty column which would not be the last one in the row, I could use an empty string. For instance, if I want the different constraint markers to be in their respective columns, the following syntax could be used:
```
erDiagram
    CreativeWork {
      TEXT name PK
      TEXT description
      TEXT reference "" N
    }
```
Now the `N` marker has been shifted to the next column and no longer shares the same column with the `PK` marker.

**Describe alternatives you've considered**
Right now as only two columns can be used, I attache the additional info to one of the columns using underscores as separators:
```
erDiagram
    CreativeWork {
      TEXT name_PK
      TEXT description
      TEXT reference_N
    }
```
This is not very readable nor good-looking, but it is the best way I have discovered using the current feature set.

**Comment by RonaldZielaznicki** [comment]
I'll add in my support for this feature. I've a use case that matches with eeriksp's, and if someone is willing to point me in the right direction I'd be willing to take a crack add making the required changes.

I would even go a step further to say that with primary keys and foreign keys I'd like the diagram to have its lines pointing at the values within the table.

Similar to this: 
![image](https://user-images.githubusercontent.com/58531251/128381953-4b3602f7-cc68-458b-b370-46a94a0ed0aa.png)

**Comment by RonaldZielaznicki** [comment]
Looking around a bit more, this could be related to #1930
