### ISSUE TITLE
SequenceDiagram: floating notes / notes on the same line

### ISSUE THREAD

**Issue by AlexanderWillner** [mermaid-js/mermaid#2087]
**Is your feature request related to a problem? Please describe.**
I like to add notes to participants, however, dislike that each note introduces a new line.

**Describe the solution you'd like**
I want all notes to be horizontally on the same line.

**Describe alternatives you've considered**
There is probably no workaround right now.

**Additional context**

Input:
```mermaid
sequenceDiagram

Participant A
Note right of A: Text
Participant B
Note right of B: Text
Participant C
Note right of C: Text
```

Now:
<img width="693" alt="before" src="https://user-images.githubusercontent.com/307605/119119823-de3f9100-ba2b-11eb-85a8-6e3bf43483e7.png">

Expected:
<img width="693" alt="after" src="https://user-images.githubusercontent.com/307605/119119833-e26bae80-ba2b-11eb-9b3d-ffad7ebc2015.png">

**Comment by twpol** [comment]
I've had a go at implementing this in PR #2746; it wasn't too hard to make it work, but I'm not sure if I've chosen the best way of marking it up, etc., so I'd appreciate some design feedback!

This is what the new diagram on the demo page looks like:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1017843/154585088-ed07245b-21c7-4456-a4f0-1ba39ae6d305.png">

**Comment by Lockszmith-GH** [comment]
I came here asking for the same feature.

**Comment by alexanderankin** [comment]
what's the syntax for this?

**Comment by Lockszmith-GH** [comment]
So.... this was never resolved? right?

What OP described is about the horizontal alignment of notes, and the solution merged in May with #4370 allows `par_over`, but does not solve the horizontal positioning issue originally described.

@jgreywolf ?

**Comment by AlexanderWillner** [comment]
> So.... this was never resolved? right?

I guess not. Assuming this is the correct syntax...

```
sequenceDiagram
    par_over A, B, C
      Note over A: Foo
      Note over B: Bar
      Note over C: Baz
    end
```

...the result doesn't look right:
 
![image](https://github.com/mermaid-js/mermaid/assets/307605/f5e2da38-b7eb-4b88-bcd7-498d1fa7e725)

**Comment by issouza** [comment]
Any expectation to reopen this issue, a more recent issue, or solution to this?

**Comment by Berghopper** [comment]
Not quite the same, but works for my usecase. I wanted to have a note for e.g. A/B on their own. You can achieve it like this:

```mermaid
%%{init: {
  "theme": "",
  "themeCSS": [
    "rect { stroke: transparent; }" 
  ]
}}%%
sequenceDiagram
    box (Here's a note) <!-- Transparent box, just text -->
    participant A
    end
    box (Here's another, on the same line!)
    participant B
    end
    
      A->>B: Message 1
      B->>A: Message 2
```

![Image](https://github.com/user-attachments/assets/af1b6ae8-fac0-44af-8bdb-09e9541ac73b)

**Comment by ryanwwest** [comment]
Does a new duplicated issue need to be recreated for this to be considered again?
