### ISSUE TITLE
Link node to subgraph

### ISSUE THREAD

**Issue by ZeroRadius** [mermaid-js/mermaid#2090]
Hello, I would like to link a Node to a sub graph so that I can use nodes inside the subgraph to represent buttons in a process and link them to other nodes. When I try this in the live editor I get "Syntax error in graph
mermaid version 8.10.1"   

My graph : (Trying to link A -->Logic)
graph 
    A[Hello]
    B[World]
    subgraph  Logic [TestGraph]
        op1[Hellow world]
        op2[Hellow world]
        op3[Hellow world]
    end
    D[Option 1]
    E[Option2]
    F[Option3]
    G[Hello]
    
    A --> Logic
    op1 --> D
    op2 -->E
    op3 --> F
    F --> A
    F -->B
    E --> B
    D --> B
    E -->A

**Comment by knsv** [comment]
Hi!

Replace `graph` with `flowchart`. This makes Mermaid use the new improved renderer that is replacing the original one.

I hope this solves your problem,
Knut

https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZmxvd2NoYXJ0XG5BW0hlbGxvXVxuQltXb3JsZF1cbnN1YmdyYXBoIExvZ2ljIFtUZXN0R3JhcGhdXG5vcDFbSGVsbG93IHdvcmxkXVxub3AyW0hlbGxvdyB3b3JsZF1cbm9wM1tIZWxsb3cgd29ybGRdXG5lbmRcbkRbT3B0aW9uIDFdXG5FW09wdGlvbjJdXG5GW09wdGlvbjNdXG5HW0hlbGxvXVxuXG5BIC0tPiBMb2dpY1xub3AxIC0tPiBEXG5vcDIgLS0-RVxub3AzIC0tPiBGXG5GIC0tPiBBXG5GIC0tPkJcbkUgLS0-IEJcbkQgLS0-IEJcbkUgLS0-QSIsIm1lcm1haWQiOnt9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ

**Comment by ZeroRadius** [comment]
Thank you! Just what I needed
