### ISSUE TITLE
Is it possible to link from a state inside a composite state to one outside?

### ISSUE THREAD

**Issue by iamrecursion** [mermaid-js/mermaid#2092]
I have a state diagram that uses composite states akin to the following:

```mermaid
stateDiagram-v2
  state A
  state B {
    [*] --> C
    C --> D
    C --> A
    D --> [*]
  }
  
  A --> B
```

I'm wondering if there is any way to have the `C --> A` link inside the composite state B link to the state `A` defined in the outer scope. As is, this seems to create a new state `A` inside the compositte state `B`.

**Comment by knsv** [comment]
Yes you can!
```
stateDiagram-v2
  state A
  state B {
    [*] --> C
 }
 C --> D
```
You just need so make sure the id of the outside node does not appear inside the composite state.

**Comment by iamrecursion** [comment]
Oh this is exactly what I needed! Thank you so much!
