### ISSUE TITLE
Feature request: Call back function for Blazor (.net core 5)

### ISSUE THREAD

**Issue by ZeroRadius** [mermaid-js/mermaid#2093]
**Is your feature request related to a problem? Please describe.**
After a bit of playing around we got Mermaid working in Blazor but the call back function when using click does not work (see interaction section int he following link if I did not explain well: https://mermaid-js.github.io/mermaid/#/flowchart).  I assume this is because you can't use the razor syntax for calling a c# method in an @onClick and then of course you can't call JS without JS Interop which of course needs to be called from the c# method that I am unable to call.

**Describe the solution you'd like**
I would like to be able to call a c# method as a call back function in Blazor.net Core 5

**Describe alternatives you've considered**
Opening in a new tab to show the details of the clicked node. The issue was I did not see a way to name the window / tab and my users will 100% get upset if more then one window /tab opens (learned that the hard way).  For the time being we are moving to a pure HTML and JS page inside of the blazor project but it takes it out of the main workflow and takes away a lot of the convenience of blazor

Thank you all for the amazing work you do!

**Comment by DotJoshJohnson** [comment]
Hi, @ZeroRadius! I stumbled upon this issue while searching for existing Mermaid Blazor components. I couldn't find any existing packages, so I created one for use in the app I'm working on. I was able to implement click handling using JavaScript interop.

There is a [preview package on NuGet](https://www.nuget.org/packages/MermaidJS.Blazor) and a [GitHub repo](https://github.com/TrueCommerce/MermaidJS.Blazor) if you just want to see how to implement the callback.

**Comment by dsu0629** [comment]
Hi, @DotJoshJohnson! 
I try to use your package to test the callback (using the provided example), but can't get the node ID successfully

**Comment by dsu0629** [comment]
Here is the code:
@page "/"
@using MermaidJS.Blazor


<MermaidDiagram Definition="@diagramDefinition" OnClick="OnClickNode" />

<p>Last Click Node: @lastClickNode</p>

@code
{
    string diagramDefinition = "graph TB\nA-->B\nclick A onClickMermaidNode;";
    string lastClickNode=string.Empty;
    void OnClickNode(string nodeId)
    {
        lastClickNode=nodeId;
    }
}

**Comment by jgreywolf** [comment]
@ZeroRadius Does the information from @DotJoshJohnson resolve this?
