### ISSUE TITLE
GITHUB REAME.MD SUPPORT

### ISSUE THREAD

**Issue by akiraplusplus** [mermaid-js/mermaid#2108]
Hey Guys, I tried to make the diagram on readme.md in github repo, but it looks github don't support with mermaid syntax.

Is there any way to show them up on github repo readme.md?

**Comment by knsv** [comment]
There is a github feature request active regarding this:
https://github.community/t/feature-request-support-mermaid-markdown-graph-diagrams-in-md-files/1922/153

**Comment by akiraplusplus** [comment]
Ok, There was a way to add an image, and it worked. Thanks for your reply!
