### ISSUE TITLE
How do I make a "circular" graph or flowchart?

### ISSUE THREAD

**Issue by ReaderGuy42** [mermaid-js/mermaid#2130]
I'd like to be able to make a circular graph, by which I mean something along the lines of the recycling icon, where each shape is organized along one circle. 
So far I've only been able to make something where the second element is between the other two (see screenshot 1)
![Screenshot from 2021-06-11 21-04-47](https://user-images.githubusercontent.com/71895400/121737193-d8a00d00-caf8-11eb-87f0-8fd8fcd8ab3d.png)

I would be ok with something that looks like this 
![Screenshot from 2021-06-11 21-05-18](https://user-images.githubusercontent.com/71895400/121737224-e35aa200-caf8-11eb-9b8f-e30e3904028a.png) 
but I'd like to put arrows between the bottom elements.
Any ideas?
Thanks :)

**Comment by patrickbrett** [comment]
This works for me:

```
flowchart LR
    x <--> y
    y <--> z
    x <--> z
```

<img width="212" alt="Screen Shot 2021-06-27 at 3 19 32 pm" src="https://user-images.githubusercontent.com/6735055/123533714-1472dd80-d75b-11eb-92b8-7fd5a3f55e51.png">

**Comment by jgreywolf** [comment]
@ReaderGuy42 Does what @chloebrett showed work for you?

**Comment by nirname** [comment]
There is another more detailed discussion about circular flows https://github.com/mermaid-js/mermaid/issues/3228 @ReaderGuy42 please refer to the new one, or ask to reopen this, if needed
