### ISSUE TITLE
Fails to render nodes with ending with _self _blank _parent _top

### ISSUE THREAD

**Issue by thewhiteboxguy** [mermaid-js/mermaid#2135]
**Describe the bug**
Mermaid fails to render graph nodes with names ending with "_parent".

**To Reproduce**
1. Open the online mermaid editor at https://mermaid-js.github.io/mermaid-live-editor/
2. Enter the code:  
```mermaid
graph
    my_child --> my_parent
```
4. The diagram fails to render...
5. Console output displays:
```
Parse error on line 2:
...    my_child --> my_parent
----------------------^
Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF', 'SQS', 'AMP', 'STYLE_SEPARATOR', 'PS', '(-', 'STADIUMSTART', 'SUBROUTINESTART', 'CYLINDERSTART', 'DIAMOND_START', 'TAGEND', 'TRAPSTART', 'INVTRAPSTART', 'START_LINK', 'LINK', 'DOWN', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'MINUS', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'LINK_TARGET'
```

Notice that any node name ending with "_parent" will fail to render.

**Expected behavior**
It was expected that a graph with the two nodes "my_child" and "my_parent" was rendered.
![mermaid-expected](https://user-images.githubusercontent.com/83271564/122193513-d7723580-ce94-11eb-93be-43477c14a5f2.png)

**Code Sample**
This very simple graph will fail to render:

```mermaid
graph
    my_child --> my_parent
```

**Desktop:**
 - OS: Ubuntu 21.04
 - Browser: Chrome
 - Version 91.0.4472.106 (Official Build) (64-bit)

**Additional context**
An obvious workaround is to not create nodes that end with "_parent". For example:

```mermaid
graph
    A["my_child"] --> B["my_parent"]
```

Notice that the display name for the "my_parent" node must be in quotes.

**Comment by nirname** [comment]
Any link target option will cause this error
```
_self _blank _parent _top
```

**Comment by nirname** [comment]
@ibrahimWassouf you did great job with the previous PR, I think this very similar. If you have time it would be great if you would take a look at it

**Comment by ibrahimWassouf** [comment]
Thanks! I'll take a look at it

**Comment by nirname** [comment]
This issue is related #2495 too

**Comment by nirname** [comment]
The nodes ending with  _self _blank _parent _top and containing some other keywords like call will cause syntax error

**Comment by nirname** [comment]
I was trying to edit this issue, but decided to close it and create a new one, because it is better to leave it as a history there, and make a new and clean one instead. Please refer to #4645
