### ISSUE TITLE
Mermaid License Violation?

### ISSUE THREAD

**Issue by tleish** [mermaid-js/mermaid#2146]
I came across a desktop software which includes the MermaidJS library in the distribution,

1. On the one hand, their website clearly attributes MermaidJS
2. On the other hand, the Mermaid code is distributed inside a `diagram.min.js` file without license documentation. 

Is this a violation of the license, or is the attribution on their website sufficient?  If so, which of the Mermaid authors can I pass this info along to so they can reach out and request a correction?

**Comment by patrickbrett** [comment]
`The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.`

I'd say this violates the license condition.

**Comment by tleish** [comment]
I looked at this again today.  It appears the vendor split the `diagram.min.js` code into 2 files:

- `diagram.min.js`
- `mermaid.min.js`

I believe the `diagram.min.js` is now just additional code for displaying the mermaid diagrams in their desktop app.
