### ISSUE TITLE
Svg fixed height causes gaps when fitting smaller window

### ISSUE THREAD

**Issue by badbort** [mermaid-js/mermaid#2160]
**Describe the bug**
Large-ish sequence diagram gets resized as you'd expect when the window is made smaller, but the fixed height of the svg adds large gaps of whitespace above and below as the diagram is reduced in size to fit the constrained horizontal width.

![image](https://user-images.githubusercontent.com/4551792/123739887-f5e72080-d8d9-11eb-80c3-f2fcf205e013.png)

**To Reproduce**

Use this diagram:

```
sequenceDiagram
	participant User
	participant GitRepo
	participant Server
	participant ResourceA
	participant ResourceB
	participant ResourceC
	
	User->>GitRepo: Commit changes
	loop
		Server->>GitRepo: Check for changes
	end
	User->>Server: Manually Trigger
	note right of Server: Something pipeline scheduled
	
	rect rgba(0,255,0,.1)
		note over Server,ResourceB: Blah blah blah
		activate ResourceA
		GitRepo->>ResourceA: Blah blah blah
		note right of ResourceA: Blah blah blah:<br/>Blah blah blah
		ResourceA->>Server: Blah blah blah
		deactivate ResourceA	
		
		Server->>ResourceB: something something something
		activate ResourceB
		note left of ResourceB: something:<br/>- something something something<br/>- Adds/generates stuff<br/>-Does things<br/>-Does more things<br/>-Hey, more things
		ResourceB->>Server: something something something something
		deactivate ResourceB	
	end
	
	note right of Server: Something something something<br/>Something something something
	
	rect rgba(0,255,0,.1)
		note over Server,ResourceB: something something
		Server->>ResourceB: Does something
		activate ResourceB
		note left of ResourceB: Something something something
		note left of ResourceB: Something something something
		
		ResourceB->>Server: Something something something
		deactivate ResourceB	
	end
	
	note right of Server: something something completed<br/>Schedule something something
	
	rect rgba(0,255,0,.1)
		note over Server,ResourceC: Blah something more
		Server->>ResourceC: Downloads something artifacts
		activate ResourceC
		note left of ResourceC: Blah blah blahBlah blah blah<br/>produces something something
		ResourceC->>Server: Blah blah blahBlah blah blah
		deactivate ResourceC	
	end
	
	note over User,Server: Blah blah bla<br/>Blah blah blah
```

Removing the height attribute changes it to how i'd expect:

![image](https://user-images.githubusercontent.com/4551792/123740192-9d645300-d8da-11eb-944e-ff6a1d0fc169.png)

**Comment by badbort** [comment]
This can also be reproduced easily in the live editor:

![image](https://user-images.githubusercontent.com/4551792/123740118-76a61c80-d8da-11eb-9977-ba884bb4a985.png)

**Comment by GanZhiXiong** [comment]
I ran into the same problem and you can repeat it at the link below.
https://ganzhixiong.com/p/8d969531/
![image](https://user-images.githubusercontent.com/27394631/125319282-32e8f380-e36d-11eb-8599-e77c14c10266.png)

**Comment by cm-wada-yusuke** [comment]
I have a same problem. I created a PR for 100% height when `useMaxWidth` is true.

https://github.com/mermaid-js/mermaid/pull/2312
