### ISSUE TITLE
Svelte - how to update the graph on changes

### ISSUE THREAD

**Issue by MarcGodard** [mermaid-js/mermaid#2165]
Hi I am using svelte and starting simple:

```
<script>
  import mermaid from 'mermaid'
  import { onMount } from 'svelte'

  export let value

  let element = null
  mermaid.initialize({ startOnLoad: false })

  onMount(() => {
    mermaid.init([ element ])
  })
</script>

{#if value}
  <pre bind:this={element}>
    {value}
  </pre>
{/if}
```

But when value is changed, the chart doesn't update. I am very n00b with svelte and mermaid, so please be easy on me.

**Comment by sidharthv96** [comment]
https://github.com/mermaid-js/mermaid-live-editor/blob/649bfee23caeb6cdfaa5702422420b8ab16c9b10/src/lib/components/view.svelte#L31-L34

This might help.
