### ISSUE TITLE
sequence diagram activation not behaved as expected

### ISSUE THREAD

**Issue by zsynacl** [mermaid-js/mermaid#2168]
**Describe the bug**
sequenceDiagram reported error: ERROR: [Mermaid] Trying to inactivate an inactive participant (PCC)

**To Reproduce**
use typora 0.9.96 and type scripts in `Code Sample`

**Expected behavior**
expected diagram shown below (with older version: in typora 0.9.83)
![image](https://user-images.githubusercontent.com/4392800/124245235-613b2780-db52-11eb-9b8e-ea6d48eaf316.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/4392800/124244847-f5f15580-db51-11eb-8eeb-f1cac8b7208b.png)

**Code Sample**
```mermaid
sequenceDiagram
participant PCC
participant SCC
participant UE
PCC->>+UE: DL DCI(PCC)
note right of UE: wait k1(PCC) slots
PCC->>-UE: PDSCH(PCC)
SCC->>+UE: DL DCI(SCC)
note right of UE: wait k1(SCC) slots
SCC->>-UE: PDSCH(SCC)
note left of PCC: wait K2(PCC/SCC)
UE-->>PCC: ACK/NACK(PCC/SCC)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Typora
 - Version: 0.10

**Additional context**
found similar problem #1380

**Comment by zsynacl** [comment]
tried script like this and succeed:
```mermaid
sequenceDiagram
participant PCC
participant SCC
participant UE
PCC->>UE: DL DCI(PCC)
activate UE
note right of UE: wait k1(PCC) slots
PCC->>UE: PDSCH(PCC)
deactivate UE

SCC->>UE: DL DCI(SCC)
activate UE
note right of UE: wait k1(SCC) slots
SCC->>UE: PDSCH(SCC)
deactivate UE
note left of PCC: wait K2(PCC/SCC)
UE-->>PCC: ACK/NACK(PCC/SCC)
```
I suppose the shortcut of activation/deactivation (+/-) should be equal to single activate/deactivate instruction.

**Comment by vassudanagunta** [comment]
seems like this can be closed

**Comment by jgreywolf** [comment]
Closing: suggested resolution
