### ISSUE TITLE
Edge from node to subgraph fails with: 

### ISSUE THREAD

**Issue by thegoatherder** [mermaid-js/mermaid#2179]
**Describe the bug**
Creating an edge from a node to a subgraph fails with `TypeError: Cannot set property 'rank' of undefined`

**To Reproduce**

Create a mermaid diagram with:

```text
graph TD
    A
    subgraph S1
        B
    end
    A-->S1
```

**Expected behavior**

In the documentation, the [Direction in subgraphs](https://mermaid-js.github.io/mermaid/#/flowchart?id=direction-in-subgraphs) section demonstrates node `A` connected to subgraph `TOP`. I'm expecting my node `A` to connect to subgraph `S1`

Similar to:
![image](https://user-images.githubusercontent.com/389668/124924699-9ed8fe00-dff3-11eb-9df5-b3d0781efbc5.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/389668/124924786-b3b59180-dff3-11eb-9559-a03a0397ab04.png)

**Code Sample**

See mermaid live preview editor [here](https://mermaid-js.github.io/mermaid-live-editor/view/#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBXG4gICAgc3ViZ3JhcGggUzFcbiAgICAgICAgQlxuICAgIGVuZFxuICAgIEEtLT5TMVxuICAgICIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOnRydWUsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjp0cnVlfQ)

**Desktop (please complete the following information):**
```text
Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by knsv** [comment]
Hello. Fortunately there is a simple solution for this. Use flowchart instead of graph which will trigger use of the new rendering engine. Very soon the new engine will will be the default one and will be triggered by both graph and flowchart.

```
flowchart TD
    A
    subgraph S1
        B
    end
    A-->S1

```

**Comment by duaneking** [comment]
I'm getting this issue in a state diagram, too.  This fits my error perfectly.

**Comment by nirname** [comment]
Currently it works with `graph` as well, in live editor and latest version of mermaid. Is this one still a problem?

**Comment by jgreywolf** [comment]
Closing due to lack of response/activity
