### ISSUE TITLE
Bug when using mermaid with docsify

### ISSUE THREAD

**Issue by nkavian** [mermaid-js/mermaid#2183]
**Describe the bug**
docsify and mermaid work great together, except the moment I use a `--)` arrow with a sequence diagram.

The same diagram works if I use the online mermaid.

```
mermaid.min.js:1 Uncaught Error: Parse error on line 2:
...Diagram    A --) B : Hello
----------------------^
Expecting 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', got 'TXT'
    at O.parseError (mermaid.min.js:1)
    at O.parse (mermaid.min.js:1)
    at Object.draw (mermaid.min.js:24)
    at Object.render (mermaid.min.js:24)
    at e.code ((index):37)
    at n.parse (docsify.js:1)
    at Function.n.parse [as parser] (docsify.js:1)
    at docsify.js:1
    at docsify.js:1
    at En.compile (docsify.js:1)
```

**To Reproduce**
Use the following within docsify and view the browser console.

`````
```mermaid
sequenceDiagram
    A --) B : Hello
```
`````

**Expected behavior**
Expect the diagram to work in docsify.

**Comment by Yokozuna59** [comment]
I'm assuming that they didn't update the mermaid version, please contact them to update the version, if it was still an issue.
