### ISSUE TITLE
Class diagram incorrectly rendered if there are two backtick-escaped class names with dots (.)

### ISSUE THREAD

**Issue by dgazzoni** [mermaid-js/mermaid#2226]
**Describe the bug**
Class diagram incorrectly rendered if there are two backtick-escaped class names with dots (.) 

**To Reproduce**
1. Run the code sample below

**Expected behavior**
There should be two boxes, one for `a.h` and another for `b.h`. However, a single box for `b.h` is shown.

**Code Sample**
```
classDiagram
    class `a.h` {
    }

    class `b.h` {
    }
```

[Link to live editor](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gICAgY2xhc3MgYGEuaGAge1xuICAgIH1cblxuICAgIGNsYXNzIGBiLmhgIHtcbiAgICB9XG4iLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Browser: Safari, Chrome
 - Version: 14.0.3, 92.0.4515.131

**Comment by jgreywolf** [comment]
As of 10.1 this is no longer reproducible. I am closing as resolved
