### ISSUE TITLE
Class diagrams, relations, how to specify inheritance?

### ISSUE THREAD

**Issue by upyesp** [mermaid-js/mermaid#2238]
Hi,

I'm fairly new to Mermaid and absolutely loving it.  Thanks to all involved.

In Class diagrams, when showing relationships, there are many options available.  I need to show inheritance in my diagram, but haven't found how to specify that in Mermaid.  I see there is:
Animal <|-- Duck
Which results in a solid triangle.  I understand this means, "Directed Association". 
What is the syntax to generate an outline triangle, for, "Inheritance"?
Thanks.

**Comment by plamf** [comment]
The `<|--` you are using is in fact the right syntax for inheritance. It is mentioned here: https://mermaid-js.github.io/mermaid/#/./classDiagram?id=two-way-relations

But I do agree that this is kinda weird and not what one would expect after reading the UML Standard.

**Comment by upyesp** [comment]
Hi Planf,

Thanks for your comment.  My concern is (and I may very well be incorrect), that Mermaid shows this as a solid/filled triangle.  However, in UML, a solid triangle does not represent Inheritance, it represents Directed Association. 

Inheritance should be represented by an outline triangle, one that is not filled.

In which case, Mermaid is rendering class diagrams incorrectly.  The filled triangle should be replaced by an outline triangle, for Inheritance.

I politely request the maintainers of Mermaid to change this.

**Comment by das-g** [comment]
See #1687

**Comment by michalspano** [comment]
Please _fix_ this, I nearly **failed** my assignment because of the issue; the **solid triangle** represents a **directed association**, not **inheritance**.

**Comment by jgreywolf** [comment]
Closing this in favor of #1687
