### ISSUE TITLE
I have probelm to use Annotations on Class When integrating mermaid into markdown document

### ISSUE THREAD

**Issue by lxzhu** [mermaid-js/mermaid#2248]
Hi
First of all, thank you for making this amazing project!

I have a C# project which host markdown files. I use [Markdig](https://github.com/xoofx/markdig) to convert markdown to html and then insert into a page.  Now I am integrating Mermaid to support diagram in the markdown. 

The problem i have now is the Annotation on class.  They are handled as an Html tag. For example, <<interface>> become <> and <interface>. I need to escape the < in document to make it work.

Example One:  *This does not work*
&lt;div class="mermaid">
class Animal {
        &lt;&lt;interface>> 
        +age int
        +dog Dog
 }
&lt;/div>

Example Two:  *This works*
&lt;div class="mermaid">
class Animal {
        &lt;&amp;lt;interface>> 
        +age int
        +dog Dog
 }
&lt;/div>

Here comes my question. Is it possible to apply annotation in another way instead of using this < html entity?

**Comment by jgreywolf** [comment]
At this point this is the only way to add an annotation.  The issues with using < in html is why we used `~~` for defining generics
