### ISSUE TITLE
Add support of "LaTeX" in the form of MathJax

### ISSUE THREAD

**Issue by Minderer** [mermaid-js/mermaid#2267]
Hello
Mermaid have incredible potential for STEM – not super useful for diagrams with mathematical symbolism.
If you add LaTeX support, then a significant amount of this potential is released on the STEM community.
Mermaid will get immortalised if this happens.
Best regards

**Comment by Elaws** [comment]
This is a great idea. Any news for that FR ?

**Comment by sunt05** [comment]
related #2776

**Comment by DaveJarvis** [comment]
This can probably be closed as a duplicate of #2776

**Comment by Yokozuna59** [comment]
duplicate of #2776
