### ISSUE TITLE
Subgraph direction is not consistent

### ISSUE THREAD

**Issue by vangoz** [mermaid-js/mermaid#2286]
Nodes in subgraph does not follow consistent direction in some cases.
For example this flowchart
```
flowchart LR
  subgraph TOP
    direction TB
    subgraph B1
        direction RL
        i1 -->f1
    end
    subgraph B2
        direction BT
        i2 -->f2
    end
    B1 --> B2
  end
  A --> B1 --> B
```

![github-mermaid](https://user-images.githubusercontent.com/2033121/131525217-d2c05f7c-9885-4643-8b88-db35e413b434.PNG)

I believe B1 should be on top of B2, but it's on the left side.

Mermaid version: 8.12.0

**Comment by knsv** [comment]
Ideally it would be but as you have links in to the subgraph and out of it the direction is tainted by the direction outside of the subgraph "LR".

**Comment by knsv** [comment]
I guess this should be described better in the docs.
