### ISSUE TITLE
Class diagram can not be generated when there is a space after the ending curly bracket for a class definition

### ISSUE THREAD

**Issue by TomasJohansson** [mermaid-js/mermaid#2292]
**Describe the bug**
A picture showing "Syntax error in graph" is displayed (when using the mermaidCLI version 8.12.1) when trying to generate a class diagram when there is a space after the ending curly bracket for a class definition.
When using the live-editor (currently showing the version 8.11.4) then you do not see the error in the same way but the right side of the page is grayed, and in the editor the ending curly bracket is red as indicating an error.

**To Reproduce**
1. Go to https://mermaid-js.github.io/mermaid-live-editor/
2. Paste this code into the editor:
```
classDiagram
      class Duck{
      }
      class Fish{
      }
```
3. Now you should be able to see that it works when you have no space after the ending curly bracket for the class Duck but if you add a space you should see that the editor seem to complain about the ending curly bracket.
```
classDiagram
      class Duck{
      }[THIS_IS_THE_PLACE_WHERE_IT_SHOULD_BE_POSSIBLE_TO_ADD_A_SPACE]
      class Fish{
      }
```
If you use the cli (version 8.12.1) and paste the above code into a file "mydiagram.mmd" and use the following command:
`mmdc -i mydiagram.mmd -o mydiagram.png`
then you should see the error "Syntax error in graph" in the generated png file if you have a space at the place mentioned above.

**Expected behavior**
No error should occur. White space should be okay.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - mermaidCLI version 8.12.1 (but as mentioned above, you can also see the problem in the live-editor)

**Comment by jgreywolf** [comment]
@ashishjain0512 Any update?

**Comment by jgreywolf** [comment]
In the live editor this can no longer be reproduced. Is this still an issue?

**Comment by jgreywolf** [comment]
Closing as this issue appears to be resolved
