### ISSUE TITLE
Generic classes drawn once instead of multiple times

### ISSUE THREAD

**Issue by lonix1** [mermaid-js/mermaid#2301]
**Describe the bug**
When using generic classes, similarly-named classes are drawn as a single class instead of multiple classes.

**To Reproduce**
See code below

**Expected behavior**
- two base classes: `Vehicle<Land>` and `Vehicle<Sea>`
- the `Prototype` class should appear twice

**Screenshots**

**Code Sample**
Live sample [here](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gIFZlaGljbGV-TGFuZH4gPHwtLSBQcm90b3R5cGVcbiAgVmVoaWNsZX5MYW5kfiA8fC0tIENhclxuICBWZWhpY2xlfkxhbmR-IDx8LS0gVHJ1Y2tcbiAgVmVoaWNsZX5TZWF-IDx8LS0gUHJvdG90eXBlXG4gIFZlaGljbGV-U2VhfiA8fC0tIEJvYXRcbiAgVmVoaWNsZX5TZWF-IDx8LS0gU2hpcFxuIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0).
Another live sample [here](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gIFZlaGljbGV-TGFuZH4gPHwtLSBQcm90b3R5cGVcbiAgVmVoaWNsZX5MYW5kfiA8fC0tIENhclxuICBWZWhpY2xlfkxhbmR-IDx8LS0gVHJ1Y2tcblxuICBWZWhpY2xlX35TZWF-IDx8LS0gUHJvdG90eXBlX1xuICBWZWhpY2xlX35TZWF-IDx8LS0gQm9hdFxuICBWZWhpY2xlX35TZWF-IDx8LS0gU2hpcFxuIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0) which shows how it should look. I added `Foo_` to trick the editor, ignore those underscores.

````
classDiagram
  Vehicle~Land~ <|-- Prototype
  Vehicle~Land~ <|-- Car
  Vehicle~Land~ <|-- Truck
  Vehicle~Sea~ <|-- Prototype
  Vehicle~Sea~ <|-- Boat
  Vehicle~Sea~ <|-- Ship
````

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser [extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) in vscode
 - Version 8.9.0

**Additional context**
n/a

**Comment by jgreywolf** [comment]
Can you explain this a little more?  What language allows you to have two classes with the same name, but different "interfaces".

Maybe I am just confused as to how that naming convention works

**Comment by jgreywolf** [comment]
If you are not sure what you are asking for here, then I am going to go ahead and close this issue
