### ISSUE TITLE
Buggy generic extension methods in class diagrams

### ISSUE THREAD

**Issue by lonix1** [mermaid-js/mermaid#2302]
## Is your feature request related to a problem? Please describe.

In class diagrams, it's not possible to use generic extension methods (e.g. for c#).

C#, notice the `<T>` and `this`:
````cs
public int Foo<T>(this T value, int maximum, string message) { /* ... */}
````

Mermaid, notice the `~T~` and `this`:
````
classDiagram
  class Foo {
    +Foo~T~(this T, int, string)$ int
  }
````

It incorrectly renders as `this T`. A live sample [is here](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gIGNsYXNzIEZvbyB7XG4gICAgK0Zvb35Ufih0aGlzIFQsIGludCwgc3RyaW5nKSQgaW50XG4gICAgK0Zvb1dvcmthcm91bmRfVCh0aGlzIFQsIGludCwgc3RyaW5nKSQgaW50XG4gIH1cbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9).

## Describe the solution you'd like
To be able to specify the generic `~T~` and the `this` for the same method signature.

## Describe alternatives you've considered
A dirty workaround:
````
classDiagram
  class Foo {
    +Foo_T(this T, int, string)$ int
  }
````

## Additional context
n/a

**Comment by jgreywolf** [comment]
@lonix1 this will be resolved with PR #4534
