### ISSUE TITLE
How to annotate the relation from a class member to another class or another class member

### ISSUE THREAD

**Issue by AmrIKhudair** [mermaid-js/mermaid#2341]
I would like to make an arrow from a class member to another class or one of its members, this feature exists in PlantUML by using `::` operator for example `Class1::member1 --> Class2::member2`. I tried to use this operator in Mermaid but it gave me a syntax error. Please help!

**Comment by mebibou** [comment]
Any idea when this would be implemented? classes are always linked together via member, so its a bit odd this is no supported (makes the whole Class diagram a bit pointless imo)

**Comment by Yokozuna59** [comment]
duplicate of #2341
