### ISSUE TITLE
Do we need a Chinese documentation in readme？

### ISSUE THREAD

**Issue by lexmin0412** [mermaid-js/mermaid#2343]
## Do we need Chinese documentation in readme？
I want to contribute to this project with Chinese documentation。

**Comment by knsv** [comment]
That sounds like an excellent idea! I guess the markdown files in the docs folder is a good place to start. I think we should also consider the process of syncing the english and Chinese docs folders.

**Comment by lexmin0412** [comment]
> That sounds like an excellent idea! I guess the markdown files in the docs folder is a good place to start. I think we should also consider the process of syncing the english and Chinese docs folders.

Another question: how should I arrange the structure of the docs? for example, when I trying to translate the [SUMMARY.md](https://github.com/mermaid-js/mermaid/blob/develop/docs/SUMMARY.md), should I create a file named  _**SUMMARY.zh-CN.md**_ like ant-design or in another way?

**Comment by jgreywolf** [comment]
@lexmin0412 status?

**Comment by lexmin0412** [comment]
> @lexmin0412 status?

The Chinese README has been included now at [README.zh-CN.md](https://github.com/mermaid-js/mermaid/blob/develop/README.zh-CN.md), and I'm going to close this issue.
