### ISSUE TITLE
No actor in sequence diagram in live editor

### ISSUE THREAD

**Issue by AdoHaha** [mermaid-js/mermaid#2344]
Hi the code from tutorial (https://mermaid-js.github.io/mermaid/#/sequenceDiagram ) regarding actor is not working (editor is grayed out)

1. Go to 'https://mermaid-js.github.io/mermaid-live-editor'
2. Copy
`sequenceDiagram
    actor Alice
    actor Bob
    Alice->>Bob: Hi Bob
    Bob->>Alice: Hi Alice`

3. Code grayed out

**Expected behavior**
produce correct sequence graph

**Screenshots**
![2021-09-23-201900_1280x1000_scrot](https://user-images.githubusercontent.com/2242877/134562170-53b381c1-a5bf-4770-a64c-778c3c687831.png)

**Comment by sidharthv96** [comment]
We are lagging one version behind in Live Editor due to a build issue.
The feature will be available once https://github.com/mermaid-js/mermaid-live-editor/pull/385 is merged.
