### ISSUE TITLE
ER-attribute comments not work

### ISSUE THREAD

**Issue by zhengwh** [mermaid-js/mermaid#2346]
**Describe the bug**

https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram?id=attribute-keys-and-comments

Attribute Keys and Comments
Attributes may also have a key or comment defined. Keys can be "PK" or "FK", for Primary Key or Foreign Key. And a comment is defined by quotes at the end of an attribute. Comments themselves cannot have quote characters in them.

but actually it is not work. when i add comments ,the  attribute  will be hidden in the render graph

**Comment by linde12** [comment]
Can confirm. No way to comment and no other way to mark a field as optional/nullable.

As a side note the use of the "PK" or "FK" keys have the same problem as comments!

**Comment by mi-kra** [comment]
Column name can't start with "pk", for example:

    CUSTOMER {
        string name
        string pkcustNumber
        string sector 
    }

it seems to be related problem to above.
