### ISSUE TITLE
Can we have some other charts, not only Pie type charts

### ISSUE THREAD

**Issue by Ikki-Dai** [mermaid-js/mermaid#2352]
**Is your feature request related to a problem? Please describe.**
while use mermaid with markdown, only have Pie type chart to use

**Describe the solution you'd like**
hope have some other type to use, such as bar chart, line chart

**Describe alternatives you've considered**
More and more people use markdown and mermaid in modern editor,  I think rich chart type will support people to use markdown better. 
And it will be easier to obtain a bar chart or line chart in markdown than in Word or Excel. even, it can be a revolution against MS Office Word

**Additional context**
maybe chart grammar like below

```
chart
  type: bar
  xAxis: [2019，2020，2021]，
  yAxis: [150,   220,    300]
```

and I found something interesting called Vega https://vega.github.io , maybe we can learn from that.

**Comment by wuzhefang** [comment]
want it

**Comment by kenorb** [comment]
+1 for column and line charts

**Comment by fenixnet-net** [comment]
I need this for a presentation I'm working on, and I am dismayed to find that there is no other graph type than a pie chart.

**Comment by jacob-shuman** [comment]
I love sequence, pie, git charts etc, but it would open up so many possibilities for me to be able to generate a simple bar chart with mermaid!

**Comment by akutz** [comment]
Is there by chance a branch with this work in-progress we could use if we just needed something simple?

**Comment by meche-gh** [comment]
My open source stuff in the last year has mostly been optimization and performance testing. I'd really like to be able to present profile data for algorithms in a scatter or line graph format. C.f. bar charts used by a MSFT dev: [/microsoft/vscode/pull/161479](https://github.com//microsoft/vscode/pull/161479)

**Comment by yunying61** [comment]
I also want these chart.

**Comment by jgreywolf** [comment]
@ashishjain0512 are you actively working on this?

**Comment by meche-gh** [comment]
Right.. ^ was asking as a contributor to the repo

**Comment by karistom** [comment]
+1
I also want these chart.

**Comment by zm-cttae** [comment]
This feature request would allow all of us to use bar line & scatter charts etc on Github.

**Comment by karistom** [comment]
Bar chart - workaround will be provided in README.md "Bar chart (using gantt chart)" section.
PR - https://github.com/mermaid-js/mermaid/pull/4261

**Comment by karistom** [comment]
Bar Chart - https://github.com/mermaid-js/mermaid#bar-chart-using-gantt-chart-docs---live-editor

**Comment by zm-cttae** [comment]
Related - #4269
