### ISSUE TITLE
Sequence Diagram | Double-digit sequence numbers are weirdly spaced

### ISSUE THREAD

**Issue by ghtyrant** [mermaid-js/mermaid#2390]
**Describe the bug**
As you can see below, double-digit sequence numbers are weirdly spaced. For me, this is most notable when rendering locally:
![image](https://user-images.githubusercontent.com/51596/136698114-bad0066a-5677-45a5-a98f-d77d38c7ec20.png)

If I comment out the `textLength` attribute of the sequence number in sequenceRenderer.js, the numbers are rendered just fine:
![image](https://user-images.githubusercontent.com/51596/136698135-0a1de6f8-679e-4ae7-bfce-c4fc178327eb.png)

MWE:
```
sequenceDiagram
    autonumber
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
```

**To Reproduce**
Render the above MWE to a PDF. You can see the effect in [mermaid.live](https://mermaid.live/edit#eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgYXV0b251bWJlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlclxuICAgIEEtPj5COiBQbGFjZWhvbGRlciIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9) as well, but not as strong.

**Comment by Yokozuna59** [comment]
```mermaid
sequenceDiagram
    autonumber
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
    A->>B: Placeholder
```
