### ISSUE TITLE
Support the style keyword for class diagrams

### ISSUE THREAD

**Issue by kad-beekw** [mermaid-js/mermaid#2408]
**Is your feature request related to a problem? Please describe.**

It is possible to style nodes in `graph` diagrams with a `style` declaration.  The same feature is not available for `classDiagram` diagrams.

Adding support for the `style` keyword will allow non-technical users to configure the color of nodes and other styling properties.  Current solutions rely on changing the CSS context, but this requires deep access to the web page in which the Mermaid diagram is integrated.  Regular users cannot make such changes when they are working within a pre-configured web service.

**Describe the solution you'd like**

Support for the `style` keyword in `classDiagram` diagrams.

**Describe alternatives you've considered**

The alternative is that a separate CSS context is created where the styling is applied.  But such CSS contexts cannot be integrated in most existing Markdown environments.  They require changes to the overall web page.  Most users of existing services do not have the ability to change this.

**Additional context**

The following works and makes the node yellow:

```mermaid
graph
  style Monkey fill: yellow
```

The following does not work and does not generate a diagram:

```mermaid
classDiagram
  style Monkey fill: yellow
```

**Comment by ludoo** [comment]
This would make it possible to style class diagrams in GitHub READMEs.
