### ISSUE TITLE
Unable to render labels containing  U+3001(、)

### ISSUE THREAD

**Issue by ch1y0q** [mermaid-js/mermaid#2412]
**Describe the bug**
Any label containing U+3001（、） will cause a failure in rendering the diagram. The character is often used in CJK context to separate words.

**To Reproduce**
1. visit 
2. type in `graph LR; foo-->b、a、r`
3. unable to render correctly on the right side

It is often reproducible in the mermaid integration of Typora 0.11.13, where a message "Syntax Error in graph mermaid version 8.8.3" is shown.

**Expected behavior**
Label containing "、".

**Screenshots**
Repro on mermaid-js:
![image](https://user-images.githubusercontent.com/16000946/137619644-05dcc882-65c7-4ce4-bd09-b8fb7d3e7ca3.png)

In Typora:

![image](https://user-images.githubusercontent.com/16000946/137619638-816c34ab-9cbc-49be-86d4-723bf9b351f8.png)

**Code Sample**
```
graph LR; 
foo-->b、a、r
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eternalphane** [comment]
You should quote special characters, see [document](https://mermaid.js.org/syntax/flowchart.html#special-characters-that-break-syntax)

**Comment by Yokozuna59** [comment]
As @eternalphane has already outlined, use doable quotes:

```
flowchart LR
foo--> bar["b、a、r"]
```

```mermaid
flowchart LR
foo--> bar["b、a、r"]
```
