### ISSUE TITLE
classDiagram not rendering

### ISSUE THREAD

**Issue by naimdjon** [mermaid-js/mermaid#2422]
Installed [Github+Mermaid](https://chrome.google.com/webstore/detail/github-%20-mermaid/goiiopgdnkogdbjmncgedmgpoajilohe) and wrote a simple `Readme.md` with a classDiagram mermaid block. Followed all examples on the website, but none of the class diagrams are rendering. Even a simple one like this:

      ```mermaid
          classDiagram
            class Animal
      ```
When I tried in the live editor, it is rendering. Anything wrong with the `Github+Mermaid` extension?

**Comment by jgreywolf** [comment]
Unfortunately this is not something that we can address, not being aware of how github has implemented mermaid support
