### ISSUE TITLE
A link between a node and a nested subgraph does not work

### ISSUE THREAD

**Issue by ridanuk** [mermaid-js/mermaid#2429]
**Describe the bug**

In a flowchart, a link between a node and a nested subgraph does not work

**To Reproduce**

Using the example from the [flowchart documentation](https://mermaid-js.github.io/mermaid/#/flowchart?id=direction-in-subgraphs)

flowchart LR
  subgraph TOP
    direction TB
    subgraph B1
        direction RL
        i1 -->f1
    end
    subgraph B2
        direction BT
        i2 -->f2
    end
  end
  A --> TOP --> B
  B1 --> B2

add a link from a new node to one of the existing subgraphs:

C --> B1

and the graph will no longer render.

**Expected behavior**

A link to be added from the new node to the subgraph's rectangle.

**Code Sample**

[This graph will fail in the live editor](https://mermaid.live/edit#eyJjb2RlIjoiZmxvd2NoYXJ0IExSXG4gIHN1YmdyYXBoIFRPUFxuICAgIGRpcmVjdGlvbiBUQlxuICAgIHN1YmdyYXBoIEIxXG4gICAgICAgIGRpcmVjdGlvbiBSTFxuICAgICAgICBpMSAtLT5mMVxuICAgIGVuZFxuICAgIHN1YmdyYXBoIEIyXG4gICAgICAgIGRpcmVjdGlvbiBCVFxuICAgICAgICBpMiAtLT5mMlxuICAgIGVuZFxuICBlbmRcbiAgQSAtLT4gVE9QIC0tPiBCXG4gIEIxIC0tPiBCMlxuICBDIC0tPiBCMSIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9) because of the last line.

flowchart LR
  subgraph TOP
    direction TB
    subgraph B1
        direction RL
        i1 -->f1
    end
    subgraph B2
        direction BT
        i2 -->f2
    end
  end
  A --> TOP --> B
  B1 --> B2
  C --> B1

The webpage shows "Syntax error in graph mermaid version 8.13.3"

**Desktop (please complete the following information):**
 - OS: Windows + Linux
 - Browser Chrome
 - Version 95.0.4638.54

**Comment by knsv** [comment]
Thanks for reporting

**Comment by dinofx** [comment]
I just started using Mermaid and came across this bug within the first few minutes of using subgraphs in a flowchart.  Here is a much simpler graph that might help identify the problem in the original:

```
flowchart LR
subgraph B1
    i1
end
subgraph B2
    i2
    C --> B1
end
```

B1 and B2 should be siblings, but somehow declaring the edge from `C --> B1` causes B1 to end up inside B2.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/7581987/192787829-3c2eb397-0779-4158-b4d2-6399fb7a2277.png">

For this specific graph, one workaround is to move the edge declaration outside of the subgraph:

```
flowchart LR
subgraph B1
    i1
end
subgraph B2
    i2
    C
end
C --> B1
```

**Comment by nirname** [comment]
Closing this in favor of https://github.com/mermaid-js/mermaid/issues/4644, please refer to the new issue. It is a error that comes across different issues.
