### ISSUE TITLE
Is there any animation support for mermaid.js ?

### ISSUE THREAD

**Issue by sr13579** [mermaid-js/mermaid#2461]
Is there any way I can use animation functionality in mermaid.js? Does mermaid.js has any onclick event support?

**Comment by Yash-Singh1** [comment]
> Does mermaid.js has any onclick event support?

Yes, a few diagrams have interaction support:

https://mermaid-js.github.io/mermaid/#/flowchart?id=interaction
https://mermaid-js.github.io/mermaid/#/classDiagram?id=interaction
https://mermaid-js.github.io/mermaid/#/gantt?id=interaction

**Comment by sr13579** [comment]
> > Does mermaid.js has any onclick event support?
> 
> Yes, a few diagrams have interaction support:
> 
> https://mermaid-js.github.io/mermaid/#/flowchart?id=interaction https://mermaid-js.github.io/mermaid/#/classDiagram?id=interaction https://mermaid-js.github.io/mermaid/#/gantt?id=interaction

Thank you for the reply. It was very helpful. Could you please show me a way so that I can work with animations?

**Comment by Yash-Singh1** [comment]
What type of animation are you looking for? E.g. pie chart wiping by category, fade in, etc.

**Comment by sr13579** [comment]
> What type of animation are you looking for? E.g. pie chart wiping by category, fade in, etc.

Collapse or Expand. For example when I click on a node it expands into two or three other nodes. Something like this.

**Comment by Yash-Singh1** [comment]
The solution for that could be to write a callback that toggles whether or not the nodes (and their links) are set to `display: none;` when the `click` event is fired.

**Comment by sr13579** [comment]
> The solution for that could be to write a callback that toggles whether or not the nodes (and their links) are set to `display: none;` when the `click` event is fired.

So there is no in-built feature like that? I have to do something from my own.

**Comment by sr13579** [comment]
> The solution for that could be to write a callback that toggles whether or not the nodes (and their links) are set to `display: none;` when the `click` event is fired.

But how do I write the code? Could you please give me a simple example?

**Comment by Yash-Singh1** [comment]
Here is a JSFiddle of how you can do this: https://jsfiddle.net/7taz82uy/1/.

Code:

```html
<script src="https://unpkg.com/mermaid@8.13.3/dist/mermaid.js"></script>
<div class="mermaid">
flowchart
A --> B
click A callback
</div>
```

```js
function callback() {
  // See below for more info on the IDs in these selectors
  document.querySelector("#flowchart-B-3").style.display =
    document.querySelector("#flowchart-B-3").style.display === "block"
      ? "none"
      : "block";
  document.querySelector("#L-A-B-0").style.display =
    document.querySelector("#L-A-B-0").style.display === "block"
      ? "none"
      : "block";
}

// Need security level loose for this to work
mermaid.initialize({ securityLevel: "loose" });

setTimeout(() => {

// The format for the ID is flowchart-{NODE_ID}-{INDEX}
// where NODE_ID is the ID of the node
// INDEX is the number of links plus a 1-based index of the node
// e.g. this is flowchart-B-3
// the node is B
// The INDEX is 1 (link) + 2 (index) = 3
document.querySelector("#flowchart-B-3").style.display = "none";

// The format for the ID is L-{STARTING}-{ENDING}-{INDEX}
// where STARTING is the node the link is coming from
// END is the node the link is going to
// INDEX is a 0-based (starting from 0) number on what number link it is
// E.g. this is L-A-B-0
// Starts from A, goes to B, the first link
document.querySelector("#L-A-B-0").style.display = "none";

}, 10)
```

**Comment by sr13579** [comment]
> Here is a JSFiddle of how you can do this: https://jsfiddle.net/7taz82uy/1/.
> 
> Code:
> 
> ```
> <script src="https://unpkg.com/mermaid@8.13.3/dist/mermaid.js"></script>
> <div class="mermaid">
> flowchart
> A --> B
> click A callback
> </div>
> ```
> 
> ```js
> function callback() {
>   // See below for more info on the IDs in these selectors
>   document.querySelector("#flowchart-B-3").style.display =
>     document.querySelector("#flowchart-B-3").style.display === "block"
>       ? "none"
>       : "block";
>   document.querySelector("#L-A-B-0").style.display =
>     document.querySelector("#L-A-B-0").style.display === "block"
>       ? "none"
>       : "block";
> }
> 
> // Need security level loose for this to work
> mermaid.initialize({ securityLevel: "loose" });
> 
> setTimeout(() => {
> 
> // The format for the ID is flowchart-{NODE_ID}-{INDEX}
> // where NODE_ID is the ID of the node
> // INDEX is the number of links plus a 1-based index of the node
> // e.g. this is flowchart-B-3
> // the node is B
> // The INDEX is 1 (link) + 2 (index) = 3
> document.querySelector("#flowchart-B-3").style.display = "none";
> 
> // The format for the ID is L-{STARTING}-{ENDING}-{INDEX}
> // where STARTING is the node the link is coming from
> // END is the node the link is going to
> // INDEX is a 0-based (starting from 0) number on what number link it is
> // E.g. this is L-A-B-0
> // Starts from A, goes to B, the first link
> document.querySelector("#L-A-B-0").style.display = "none";
> 
> }, 10)
> ```
