### ISSUE TITLE
Links to Live Editor (Live-Editor.md) result in 404

### ISSUE THREAD

**Issue by bartek** [mermaid-js/mermaid#2463]
**Describe the bug**

There are two files inside `docs/`, `n00b-syntaxReference.md` and `Configuration.md` which link to `Live-Editor.md`. This file does not exist in the `docs/` folder.

**To Reproduce**
1. The resulting 404 can be obseved here: https://mermaid-js.github.io/mermaid/#/./n00b-syntaxReference
2. We can also confirm the file does not exist inside docs, `find ./docs -iname live-editor.md`

**Expected behavior**

It's not clear if this should link to the [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor) or if this live-editor.md page is one that is yet to be worked on.

Happy to clean up once context is provided.

Thanks!

**Comment by sidharthv96** [comment]
Looks like that can be linked to live editor.
