### ISSUE TITLE
Sequence Diagram throwing issue while using de-activation for same participant in 8.12.0 but not in 8.2.6 

### ISSUE THREAD

**Issue by MayurMundekar** [mermaid-js/mermaid#2479]
**Describe the bug**
We migrated from mermaid version from 8.2.6 to 8.12.0. but in that one of our existing sequence diagram which was rendered in 8.2.6 is not rendering in 8.12.0.

**To Reproduce**
Copy the following code and paste in live editor. It will not render

 sequenceDiagram
    participant P1
    participant P2
    participant P3
    participant P4
    participant P5
    P1->>+P2: issue command
    P2->>+P4:  details payload
    P4->>+P5: userId, AppId
    P5->>-P4: document or null
    alt: is mapping absent
       P4->>-P2: Sign-in card
    else is mapping present
       P4->>-P2: response of user command
    end
    P1->>P2: Clicks on sign
    P2->>+P3: Pop Browser with consent url
        

**Expected behavior**
Sequence diagram should render without issues.

**Screenshots**
1.Following screenshot showed using mermaid 8.2.6
![image](https://user-images.githubusercontent.com/83640993/141286696-c2faa902-99cd-4bac-ae12-b437b1e704fc.png)

2.Following screenshot we are getting error where we used mermaid 8.12.0 version.
![image](https://user-images.githubusercontent.com/83640993/141286841-f15f5dd6-82f3-404f-91e0-9e550d3d6237.png)

**Code Sample**
sequenceDiagram
    participant P1
    participant P2
    participant P3
    participant P4
    participant P5
    P1->>+P2: issue command
    P2->>+P4:  details payload
    P4->>+P5: userId, AppId
    P5->>-P4: document or null
    alt: is mapping absent
       P4->>-P2: Sign-in card
    else is mapping present
       P4->>-P2: response of user command
    end
    P1->>P2: Clicks on sign
    P2->>+P3: Pop Browser with consent url

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  chrome
 - Version 95.0

**Additional context**
Following piece of code is giving the problem. but as per mermaid document [link ](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=activations) we can **stack Activations for same actor**:
**alt: is mapping absent
       P4->>-P2: Sign-in card
    else is mapping present
       P4->>-P2: response of user command
    end**

**Comment by MayurMundekar** [comment]
Hi Team, Any update on this

**Comment by MayurMundekar** [comment]
Hi Team, Any update on this

**Comment by jgreywolf** [comment]
@MayurMundekar I know that it has been a couple of years - but can you check to see if this is still an issue with v10.x?

**Comment by jgreywolf** [comment]
Closing due to no response
