### ISSUE TITLE
Write subgraph title in corners 

### ISSUE THREAD

**Issue by ClementDecaux** [mermaid-js/mermaid#2480]
With Flowcharts subgraph titles are centered and can overlap TB arrows which can reduce lisibility of the graph

It would be cleaner to have the possibility to put titles elsewhere (in one of the four corners or vertically in one side or rotated 90° in one side)

![image](https://user-images.githubusercontent.com/41199145/141292105-31975005-c20b-426d-80e1-d613a36db981.png)

**Comment by hersberger** [comment]
I'd like to take a crack at this

**Comment by jgreywolf** [comment]
Closing this in favor of #2977 - I know it was created after this one, but has additional useful info
