### ISSUE TITLE
Flowchart doesn't allow "call" in node text

### ISSUE THREAD

**Issue by Duberry** [mermaid-js/mermaid#2495]
**Describe the bug**

This works:

```
graph TD
testthing[this is a <br>thing]

    A[Christmas] -->|Get money| B(Go shopping)
    B --> testthing
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

This doesn't:

```
graph TD
testthing[this is a call <br>thing]

    A[Christmas] -->|Get money| B(Go shopping)
    B --> testthing
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

Bug initially confirmed in mmdc. Confirmed on mermaid.live

**To Reproduce**
1. Write diagram
2. include the word 'call' in a named object
3. Experience syntax error

**Expected behavior**
Any text should be rendered,

**Screenshots**

**Code Sample**

```
graph TD
testthing[this is a call <br>thing]

    A[Christmas] -->|Get money| B(Go shopping)
    B --> testthing
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

**Desktop (please complete the following information):**
- Version
- 8.13.3

**Comment by Ar-Kareem** [comment]
Is there still no fix for this? 

This #2388 seems to be fixed by putting the reserved word inside a name for that node. i.e. `id[foo_default]` instead of `foo_default`

But for `call` this doesn't seem to work. i.e. `id[call api]` and `call api` both break

**Comment by MisterScott** [comment]
Seeing in a flowchart LR:

1. "calls" (append a letter) works
2. "call" at the END is OK, e.g. `pA-->|correct call|M`
3. "call " (append a space) fails, e.g. `pA-->|correct call |M`
4. "call;" (append a semicolon) fails, e.g. `pA-->|correct call;|M`
5. "call:" (append a colon) works, e.g. `pA-->|correct call:|M`
6. "call<br>" (append an HTML tag, at least for `<br>`) works, e.g. `pA-->|correct call<br>x|M`

**Comment by RSBat** [comment]
In case anybody is looking for a workaround, putting text in quotes works:
```
flowchart TD
   aaa["quoted text can contain call without any problems"]
```

**Comment by nirname** [comment]
Please refer to this one #2135, I am closing it, because they share similar problem
