### ISSUE TITLE
Fork state of state diagram does not work in the live editor

### ISSUE THREAD

**Issue by sgkoishi** [mermaid-js/mermaid#2508]
**Describe the bug**
Fork state of state diagram does not work in the live editor.
[Sample from the documentation](https://mermaid-js.github.io/mermaid/#/stateDiagram?id=forks) and [live editor](
https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiICAgc3RhdGVEaWFncmFtLXYyXG4gICAgc3RhdGUgZm9ya19zdGF0ZSA8PlxuICAgICAgWypdIC0tPiBmb3JrX3N0YXRlXG4gICAgICBmb3JrX3N0YXRlIC0tPiBTdGF0ZTJcbiAgICAgIGZvcmtfc3RhdGUgLS0-IFN0YXRlM1xuXG4gICAgICBzdGF0ZSBqb2luX3N0YXRlIDw-XG4gICAgICBTdGF0ZTIgLS0-IGpvaW5fc3RhdGVcbiAgICAgIFN0YXRlMyAtLT4gam9pbl9zdGF0ZVxuICAgICAgam9pbl9zdGF0ZSAtLT4gU3RhdGU0XG4gICAgICBTdGF0ZTQgLS0-IFsqXSIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0)

**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/9637711/143159382-0c597430-56b9-4001-a2fa-edc6d6d34a5b.png)
Actual:
[![](https://mermaid.ink/img/eyJjb2RlIjoiICAgc3RhdGVEaWFncmFtLXYyXG4gICAgc3RhdGUgZm9ya19zdGF0ZSA8PlxuICAgICAgWypdIC0tPiBmb3JrX3N0YXRlXG4gICAgICBmb3JrX3N0YXRlIC0tPiBTdGF0ZTJcbiAgICAgIGZvcmtfc3RhdGUgLS0-IFN0YXRlM1xuXG4gICAgICBzdGF0ZSBqb2luX3N0YXRlIDw-XG4gICAgICBTdGF0ZTIgLS0-IGpvaW5fc3RhdGVcbiAgICAgIFN0YXRlMyAtLT4gam9pbl9zdGF0ZVxuICAgICAgam9pbl9zdGF0ZSAtLT4gU3RhdGU0XG4gICAgICBTdGF0ZTQgLS0-IFsqXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6dHJ1ZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOnRydWV9)](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiICAgc3RhdGVEaWFncmFtLXYyXG4gICAgc3RhdGUgZm9ya19zdGF0ZSA8PlxuICAgICAgWypdIC0tPiBmb3JrX3N0YXRlXG4gICAgICBmb3JrX3N0YXRlIC0tPiBTdGF0ZTJcbiAgICAgIGZvcmtfc3RhdGUgLS0-IFN0YXRlM1xuXG4gICAgICBzdGF0ZSBqb2luX3N0YXRlIDw-XG4gICAgICBTdGF0ZTIgLS0-IGpvaW5fc3RhdGVcbiAgICAgIFN0YXRlMyAtLT4gam9pbl9zdGF0ZVxuICAgICAgam9pbl9zdGF0ZSAtLT4gU3RhdGU0XG4gICAgICBTdGF0ZTQgLS0-IFsqXSIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOnRydWUsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjp0cnVlfQ)

**Code Sample**
```
   stateDiagram-v2
    state fork_state <>
      [*] --> fork_state
      fork_state --> State2
      fork_state --> State3

      state join_state <>
      State2 --> join_state
      State3 --> join_state
      join_state --> State4
      State4 --> [*]
```

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Firefox Nightly 96.0a1 (2021-11-23) (64-bit), Edge (chromium) 96.0.1054.29 (Official build) (64-bit)

**Comment by Yash-Singh1** [comment]
It turns out that the code that is provided and the code that is rendered in the documentation are different, so

```
   stateDiagram-v2
    state fork_state <>
      [*] --> fork_state
      fork_state --> State2
      fork_state --> State3

      state join_state <>
      State2 --> join_state
      State3 --> join_state
      join_state --> State4
      State4 --> [*]
```

Isn’t the correct code for forks in state diagrams. Related #2507. Replace `<>` with `<<fork>>`.
