### ISSUE TITLE
flowchart subgraph connection

### ISSUE THREAD

**Issue by martinkyrc** [mermaid-js/mermaid#2524]
Hello,
I'd like to 'render' this flowchart:
```mermaid
flowchart TB
A --> B --> C
subgraph B
  direction LR
  B1 --> B2
end
```
other example: https://mermaid-js.github.io/mermaid/#/flowchart?id=direction-in-subgraphs

It is working for version **8.13.3** (vscode [mermaid extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)), but it is not working for mermaid **8.9.2** (GitLab CE 13.12.2 - [latest on Synology](https://archive.synology.com/download/Package/Docker-GitLab)). 

The problem (with version 8.9.2) is, that "B" is subgraph and mermaid distributed with Gitlab 13.12.2 can't render it. It crash with error message: syntax error in graph.

I have two questions:
1. Starting which version is possible to render above mermaid flowchart correctly? (is there any live tool in which I can test it with different mermaid versions?)
2. I'm limited by synology GitLab package version - I can't upgrade it to the latest GitLab (and maybe mermaid distributed with will be latest/newer). The question is, if somebody know, is it possible upgrade only mermaid inside existing Gitlab 13.12.2 running on synology?

Thanks,
martin

**Comment by Yash-Singh1** [comment]
> Starting which version is possible to render above mermaid flowchart correctly? (is there any live tool in which I can test it with different mermaid versions?)

We have a live tool that gives the preview of the up to date version of `mermaid`, at `mermaid.live`, but it doesn't yet support multiple versions of `mermaid`. Doing a search on the repository, it seems this was introduced in PR #2082 (ff7512209555c61e13ef59a4fc7794e99924c902) which was released in `mermaid` 8.11.0.

> I'm limited by synology GitLab package version - I can't upgrade it to the latest GitLab (and maybe mermaid distributed with will be latest/newer). The question is, if somebody know, is it possible upgrade only mermaid inside existing Gitlab 13.12.2 running on synology?

That would be an issue to open up in GitLab. However, the only alternative I could think of would be to use the [live editor](https://mermaid.live/) and copy the markdown output over there.

**Comment by martinkyrc** [comment]
@Yash-Singh1 thank you for reply. I know `mermaid.live` - there is rendering of above mermaid flowchart working (I don't know which version is used there). Also in vscode with mermaid extension (it uses v8.13.3).

I will try to ask on GitLab.

**Comment by Yash-Singh1** [comment]
> I don't know which version is used there

You can find the version in the top left corner in the navigation bar.
![81B7D730-E8B3-430C-8C55-BCEEFB0FDBE5](https://user-images.githubusercontent.com/53054099/144264815-f299ed8c-d9e6-4c02-b332-3d520720d683.jpeg)
