### ISSUE TITLE
sequenceDiagram messages appear with line through them

### ISSUE THREAD

**Issue by ericis** [mermaid-js/mermaid#2525]
**Describe the bug**

It seems that any version of MermaidJS >8.5.2 renders the sequence diagram messages with the line through them.

![mermaid-sequence-messages](https://user-images.githubusercontent.com/974919/144333425-2382c9b1-3d4b-48c0-90e5-6b1dc94f23c1.gif)

Once the version is downgraded to 8.5.2, the message labels appear correctly over the lines:

![image](https://user-images.githubusercontent.com/974919/144333555-78d0fba9-f15d-4ad7-be40-0331090c66d3.png)

**To Reproduce**

_(updated 2021-12-02)_

1. `git clone https://github.com/ourchitecture/hello-cloud/`
2. Run `make start-docs` (requires GNU Make and `docker`). This will build and start a MkDocs Material site using "./mkdocs.yml" and "./src/docs".
3. Visit http://localhost:8000/hello-cloud/contribute/ to see the diagrams in action
4. Edit the file "./mkdocs.yml" and upgrade the MermaidJS script:
    ```yaml
    extra_javascript:
      - "https://unpkg.com/mermaid@8.13.4/dist/mermaid.min.js"
    ```
5. Hopefully, you also see the labels "pushed down" with the lines crossing through them ....

**Expected behavior**

Message labels appear above the lines.

**Screenshots**

See above.

**Code Sample**

```
sequenceDiagram
    participant C as Contributor
    participant M as Maintainer
    participant R as Repository

    C->>R: Check roadmap
    R->>C: tada
    C->>R: Check roadmap
    R->>C: teedee
```

**Desktop (please complete the following information):**
 - OS: Windows Pro 11
 - Browser: Firefox
 - Version: 94.0.2

**Smartphone (please complete the following information):**

n/a

**Additional context**

n/a

**Comment by Yash-Singh1** [comment]
Can't reproduce on `mermaid.live`: https://mermaid.live/edit/#eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgQyBhcyBDb250cmlidXRvclxuICAgIHBhcnRpY2lwYW50IE0gYXMgTWFpbnRhaW5lclxuICAgIHBhcnRpY2lwYW50IFIgYXMgUmVwb3NpdG9yeVxuXG4gICAgQy0-PlI6IENoZWNrIHJvYWRtYXBcbiAgICBSLT4-QzogdGFkYVxuICAgIEMtPj5SOiBDaGVjayByb2FkbWFwXG4gICAgUi0-PkM6IHRlZWRlZSIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9

**Comment by ericis** [comment]
Thanks @Yash-Singh1. So, there must be a layout conflict that older versions of Mermaid avoided / handled somehow, but newer versions have.

Using Mermaid v8.5.2, here is a working example of the proper label layout:
https://www.ourchitecture.io/hello-cloud/contribute/#a-working-program

![image](https://user-images.githubusercontent.com/974919/144414209-025cc2cd-6c7a-49c4-8e43-28e269ebb332.png)

When I upgrade this same page to use the latest version 8.13.4, it looks like the below with the labels "pushed down":

![image](https://user-images.githubusercontent.com/974919/144414255-d63f6f86-b8c7-4de3-bd6a-f78c363a313d.png)

While other scripts and styles could absolutely effect the MermaidJS layout, it's interesting that the older version works properly.

I'll keep investigating! Please share your thoughts / ideas everyone.

👇🏾🤝🏾 I'd appreciate anyone's help in trying this out below...

## To reproduce the page under test:

1. `git clone https://github.com/ourchitecture/hello-cloud/`
2. Run `make start-docs` (requires GNU Make and `docker`). This will build and start a MkDocs Material site using "./mkdocs.yml" and "./src/docs".
3. Visit http://localhost:8000/hello-cloud/contribute/ to see the diagrams in action
4. Edit the file "./mkdocs.yml" and upgrade the MermaidJS script:
    ```yaml
    extra_javascript:
      - "https://unpkg.com/mermaid@8.13.4/dist/mermaid.min.js"
    ```
5. Hopefully, you also see the labels "pushed down" with the lines crossing through them ....

**Comment by ericis** [comment]
@Yash-Singh1 I've also updated the original "Steps to reproduce" with the lessons from above.

**Comment by Yash-Singh1** [comment]
Thanks for the clear writeup! I just hosted the site locally and found out that this bug is Firefox-specific.

![Screenshot from 2021-12-02 17-05-07](https://user-images.githubusercontent.com/53054099/144527209-7ee3fe48-5b56-4a84-a782-e0ccace53452.png)

I actually don't know SVG, but I did find a temporary CSS solution:

```css
.messageText {
    dominant-baseline: middle;
}
```

**Comment by ericis** [comment]
Thanks @Yash-Singh1. I'll test out the work-around and see if I can upgrade to latest!

**Comment by ericis** [comment]
Closing as stale
