### ISSUE TITLE
Requiring from CommonJS is broken

### ISSUE THREAD

**Issue by sdegutis** [mermaid-js/mermaid#2559]
**Describe the bug**
**To Reproduce**
**Expected behavior**
**Code Sample**

When you install this from a Node app and `require('mermaid')`, it fails with this error:

```
module.exports = require("d3");
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules\d3\src\index.js
  from node_modules\mermaid\dist\mermaid.core.js not supported.
Instead change the require of index.js in node_modules\mermaid\dist\mermaid.core.js
  to a dynamic import() which is available in all CommonJS modules.
```

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**
**Additional context**

n/a

**Comment by sidharthv96** [comment]
This might have been fixed in 8.13.3
Ref: https://github.com/mermaid-js/mermaid/issues/2677#issuecomment-1029266586

**Comment by kilgarenone** [comment]
I'm facing this issue in 8.14.0 
```
Eleventy:EleventyErrorHandler     at internal/main/run_main_module.js:17:47 +0ms
[11ty] Must use import to load ES Module: /mnt/c/Users/kwei8/knowledge-base1/node_modules/d3/src/index.js
require() of ES modules is not supported.
require() of /mnt/c/Users/kwei8/knowledge-base1/node_modules/d3/src/index.js from /mnt/c/Users/kwei8/knowledge-base1/node_modules/mermaid/dist/mermaid.core.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /mnt/c/Users/kwei8/knowledge-base1/node_modules/d3/package.json.
```

**Comment by sidharthv96** [comment]
@kilgarenone can you share a repro?

**Comment by kilgarenone** [comment]
Hi @sidharthv96 here you go https://github.com/kilgarenone/mermaidcjs :pray:

**Comment by sidharthv96** [comment]
https://github.com/mermaid-js/mermaid-live-editor/blob/278982c2465c9197114b9f49e2340c23d3f26684/src/lib/components/view.svelte#L6

Can you check this project and use the build settings we use there?
Your issue might be solved by that.

**Comment by kilgarenone** [comment]
I believe that works because it imports the esm version of mermaid.

Issue at hand arises when you `const Mermaid = require('mermaid')`.

**Comment by alexn-s** [comment]
@kilgarenone  sadly your link can no longer be found. Does the repo still exist?

**Comment by jgreywolf** [comment]
The simple answer is that we will not be supporting "require" from cjs
