### ISSUE TITLE
GitGraph: How to change the orientation? Vertical branches support

### ISSUE THREAD

**Issue by FengZhiheng** [mermaid-js/mermaid#2585]
As title describe. Are there any ways to change the orientation of gitGraph.

I want to use gitGraph in my summay report.

**Comment by bjarnesvanberg** [comment]
First of all... Great project! Really great!

I was just about to ask the same. Is it possible to have a **vertical gitGraph**? And if so, can I change the direction (top down vs bottom up)?

Best regards
-B

**Comment by lschierer** [comment]
This would be really useful for longer graphs.

**Comment by amolshinde2010** [comment]
Idea [#3772](https://github.com/mermaid-js/mermaid/discussions/3772) has been added by DamienCassou in discussion section for gitGraph vertical rendering enhancement, you may vote.

**Comment by sjackson0109** [comment]
+1 vote

**Comment by bjarnesvanberg** [comment]
@sjackson0109 I think you should use one of the emoticons (or whatever it's called) as a reaction on the original post to upvote.

**Comment by sjackson0109** [comment]
@bjarnesvanberg - yeah upvoting is probably better. DONE. Thanks for the suggestion.

**Comment by nirname** [comment]
### Discussed in https://github.com/orgs/mermaid-js/discussions/3772

<div type='discussions-op-text'>

<sup>Originally posted by **DamienCassou** November  8, 2022</sup>
Currently, Gitgraph always represents branches horizontally:
![Screenshot 2022-11-07 at 21-05-52 Gitgraph (Git) Diagram 🔥](https://user-images.githubusercontent.com/217543/200404409-7ef13c18-5645-4258-bddb-21eee81168bd.png)

It would be nice to be able to render them vertically as well such as in this mockup:
![Screenshot 2022-11-07 at 21-00-30 Gitgraph (Git) Diagram 🔥](https://user-images.githubusercontent.com/217543/200404397-32f5373a-03f2-4fda-a74f-fd8334279f0b.png)

</div>
