### ISSUE TITLE
Is there any way to make the mermaid display code?

### ISSUE THREAD

**Issue by ghuserac** [mermaid-js/mermaid#2595]
```mermaid
graph TD;  
 (){}-->B;  
 A-->C;  
 B-->D;  
 C-->D;
```

mermaid don't allow to input code, such as `(){}`.
is there  kind of `` markdown syntax that is used to wrap code?

just discovered the ralated document https://mermaid-js.github.io/mermaid/#/flowchart  
please delete this issues. sorry.

**Comment by ibrahimWassouf** [comment]
@nirname seems the user has solved this issue and flagged it to be deleted

**Comment by ibrahimWassouf** [comment]
Thanks @Yokozuna59  ! didn't know maintainers can get notifications without mentions (that must get noisy)
