### ISSUE TITLE
Abstract classifier not respected if return type is also present

### ISSUE THREAD

**Issue by mapio** [mermaid-js/mermaid#2600]
In a class diagram, specifying both the abstract classifier (the `*`) at the end of a method with an explicit return type does not change the appearance of the method itself in the rendering.

In any class diagram add

```
int error()*
correct()*
int concrete()
```

and render it. The `correct` method will appear in italics, while the `error` one not, it will appear identical to the `concrete` method.

**Comment by ristomatti** [comment]
It seems to depend on the used syntax. On class members the symbol seems to have a similar issue.

```groovy
classDiagram
  class AsteriskSymbol {
    int italic*
    *plain: int
    plain*: int
    plain: *int
    plain: int*

    italic()* int
    int plain()*
  }
```

Another possibly related issue is that the package/internal visibility symbol `~` renders as `<` on class members. Methods render fine:

```groovy
classDiagram
  class TildeSymbol {
    ~int tilde
    ~bracket
    ~bracket: int
    bracket~: int
    bracket: ~int
    bracket: int~

    ~tilde()
    ~tilde() int
    ~int tilde()
  }
```

I'm not 100% if the TypeScript (or C#) style type syntax should be supported but it seems to be used for class members at least in [this example](https://mermaid-js.github.io/mermaid/#/classDiagram?id=setting-the-direction-of-the-diagram)..

At the time of writing, both issues seem to occur here as well:

```mermaid
classDiagram
  class AsteriskSymbol {
    int italic*
    *plain: int
    plain*: int
    plain: *int
    plain: int*

    italic()* int
    int plain()*
  }
```

```mermaid
classDiagram
  class TildeSymbol {
    ~int tilde
    ~bracket
    ~bracket: int
    bracket~: int
    bracket: ~int
    bracket: int~

    ~tilde()
    ~tilde() int
    ~int tilde()
  }
```
