### ISSUE TITLE
Two versions of d3 are in the dependency tree

### ISSUE THREAD

**Issue by LucianBuzzo** [mermaid-js/mermaid#2626]
`mermaid` requires `d3` v7 and `dagre-d3` requires `d3` v5, resulting in two separate versions of d3 being installed when using the `mermaid` package. 
See https://npmgraph.js.org/?q=mermaid for a clear visualisation

**Comment by sidharthv96** [comment]
Also, dagre-d3 has been deprecated. https://github.com/dagrejs/dagre-d3

**Comment by huyz** [comment]
What does that dagre-d3's deprecation imply? Could https://github.com/magjac/d3-graphviz be a viable long-term solution?

**Comment by Mizux** [comment]
seems related to:
* #1969
