### ISSUE TITLE
Backward arrows

### ISSUE THREAD

**Issue by SaschaWeisenberger** [mermaid-js/mermaid#2629]
Sometimes when I create a flowchart, I want arrows to go backwards, like `A<--B` instead of `B-->A`. 

The following diagram works well:
```txt
flowchart LR
    subgraph A
        1
        2
    end
    subgraph B
        3
        4
    end
    1-->3
    4-->2
    2-->4
```
```mermaid
flowchart LR
    subgraph A
        1
        2
    end
    subgraph B
        3
        4
    end
    1-->3
    4-->2
    2-->4
```
![image](https://user-images.githubusercontent.com/21291058/149625114-e8e852d8-97e9-41c3-8eb9-af9fdd831f4d.png)

But when I remove `2-->4` die diagram looks completely different
```txt
flowchart LR
    subgraph A
        1
        2
    end
    subgraph B
        3
        4
    end
    1-->3
    4-->2
```
```mermaid
flowchart LR
    subgraph A
        1
        2
    end
    subgraph B
        3
        4
    end
    1-->3
    4-->2
```
![image](https://user-images.githubusercontent.com/21291058/149625192-cfdd192f-bf2f-4193-a704-ece6ca33cbfb.png)

If possible, it would be great to have something like 
```txt
flowchart LR
    subgraph A
        1
        2
    end
    subgraph B
        3
        4
    end
    1-->3
    4<--2
```
which produces
![image](https://user-images.githubusercontent.com/21291058/149625333-d9d082d1-616b-439d-87dc-57db3f832813.png)

Despite this: Awesome tool! Love it ❤️

**Comment by BubbaJoe** [comment]
Bump

**Comment by jerzydziewierz** [comment]
bump

**Comment by ManuelRauber** [comment]
Same here, would be awesome :)

**Comment by xavier-rodet** [comment]
Yep I would need that too :+1:

**Comment by marc-guenther** [comment]
Any news on this? Sounds like a very easy change. `---`, `-->` and `<-->` already exist, why not `<--`?

Unfortunately, one cannot simply reverse the nodes, as that completely destroys the layout, eg. when I want `4<--2`, I cannot simply write `2-->4`.

**Comment by NorthernScott** [comment]
bump

**Comment by ekaterina-o** [comment]
I use this.

```
flowchart LR

A --- B --> A
B --- A

linkStyle 0,2 stroke:none
```

```mermaid
flowchart LR

A --- B --> A
B --- A

linkStyle 0,2 stroke:none
```

**Comment by shaunc** [comment]
@ekaterina-o Do you have a version of your workaround that works in more general situations? That trick is neat but seems to break if A, B are in subgraphs. E.g.:
```mermaid
graph TD

subgraph X
A
end
subgraph Y
B
end

A --- B --> A
B --- A

linkStyle 0,2 stroke:none
```

Even if I put links between subgraphs they reverse order:

```mermaid
graph TD

subgraph X
A
end
subgraph Y
B
end

A --- B --> A
B --- A

X --> Y
linkStyle 0,2 stroke:none

```

**Comment by ekaterina-o** [comment]
@shaunc It works, if I change subgraphs order in the code.

```mermaid
flowchart TD

subgraph Y
B
end

subgraph X
A
end

A --- B --> A
B --- A

linkStyle 0,2 stroke:none
```

**Comment by shaunc** [comment]
Ah nice

**Comment by jgreywolf** [comment]
Closing in favor of #3208, since there is a PR associated

**Comment by flurin137** [comment]
> I use this.
> 
> ```
> flowchart LR
> 
> A --- B --> A
> B --- A
> 
> linkStyle 0,2 stroke:none
> ```
> 
> ```mermaid
> flowchart LR
> 
> A --- B --> A
> B --- A
> 
> linkStyle 0,2 stroke:none
> ```


Just as addition to the workaround: If you want to avoid having the arrow heads you can use invisible links:

```
flowchart LR
  A ~~~ B --> A
  B ~~~ A
```

**Comment by mb111280** [comment]
```
flowchart LR
    subgraph A
        1
        2
    end
    subgraph B
        3
        4
    end
    1-->3
    3~~~1
    4-->2
    2~~~4
```
