### ISSUE TITLE
Format flowchart like a sitemap

### ISSUE THREAD

**Issue by whoacowboy** [mermaid-js/mermaid#2634]
I am using the following [Mermaid][1] MD to create a sitemap.

``` lang-html
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js">
      </script>
    <script>mermaid.initialize({startOnLoad:true});</script>
  </head>
  <body>
    <h1>Example</h1>
    <div class="mermaid">
      flowchart TD
        A(Home)-->B(Col 1 - Level 1)
        A-->C(Col 2 - Level 1)
        C-->F(Col 2 - Level 2)
        A-->G(Col 3 - Level 1)
        G-->H(Col 3 - Level 2)
        H-->I(Col 3 - Level 3)
        A-->J(Col 4 - Level 1)
        J-->K(Col 4 - Level 2)
        A-->L(Col 5 - Level 1)
        B-->E(End)
        F-->E
        I-->E
        K-->E
   </div>
  </body>
</html>
```

Which renders like the image below. See the [Codepen][2].

[![enter image description here][3]][3]

I would like it to respect the column order and align it more like an old school sitemap. 

Does anybody know if this is possible?

[![enter image description here][4]][4]

  [1]: https://mermaid-js.github.io/mermaid/#/
  [2]: https://codepen.io/whoacowboy/pen/yLzwezo
  [3]: https://i.stack.imgur.com/1PUNR.png
  [4]: https://i.stack.imgur.com/L2UFV.png

**Comment by Coloby** [comment]
Already answered [here](https://stackoverflow.com/questions/70733419/format-sitemap-style-memaid-js):

      flowchart TD
      subgraph one
        A(Home)-->B(Col 1 - Level 1)
        A-->C(Col 2 - Level 1)
        A-->G(Col 3 - Level 1)
        A-->J(Col 4 - Level 1)
        A-->L(Col 5 - Level 1)
      end
      subgraph two
        C-->F(Col 2 - Level 2)
        J-->K(Col 4 - Level 2)
        G-->H(Col 3 - Level 2)
      end
        H-->I(Col 3 - Level 3)
        B-->E(End)
        F-->E
        I-->E
        K-->E

**Comment by whoacowboy** [comment]
@Coloby Yep that was my post on SO, forgot to close this out.
