### ISSUE TITLE
RESULT_CODE_HUNG has found on github page #directives

### ISSUE THREAD

**Issue by ShortArrow** [mermaid-js/mermaid#2643]
**Describe the bug**
found error code RESULT_CODE_HUNG on [/#directives](https://mermaid-js.github.io/mermaid/#/directives)

**To Reproduce**
1. Go to [github page of mermaid](https://mermaid-js.github.io/mermaid/)
2. Search into "⚙️ Deployment and Configuration"
3. Click on [Directives](https://mermaid-js.github.io/mermaid/#/directives)
4. Browser's tab will hung

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/16986253/149783745-906f7ed4-c225-46d7-87d8-9b17c0904637.png)

Click "Exit Button" ↓

![image](https://user-images.githubusercontent.com/16986253/149784487-9108a074-d59f-4078-8ae1-7acafd9d50d8.png)

**Happen environment**
 - OS: Windows 11
 - Browser : Chrome 97.0.4692.71 (Official Build) (64bit)
 - Browser : Chrome 98.0.4758.11 (Official Build) dev (64-bit)
 - Browser : Opera 82.0.4227.58

**Additional context**
This issue has not happen on firefox 96.0.1 (64bit).
Probably only in Blink, not in Gecko.

**Comment by knsv** [comment]
Thanks for reporting. It seems t be in the syntax highlighting in one of the code examples. Fixing
