### ISSUE TITLE
classdiagram: method parameter type follow identifier?

### ISSUE THREAD

**Issue by hcientist** [mermaid-js/mermaid#2652]
Is it possible to have method parameter types follow the identifier in class diagrams as in https://cdn-images.visual-paradigm.com/guide/uml/what-is-class-diagram/12-uml-class-diagram-example.png (the `Circle` class's `area` function has a parameter identified as `radius` of type `float`).

[In this example](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBTb2NpYWxcbjw8dXRpbGl0eT4-IFNvY2lhbFxuU29jaWFsOiArZGlzdGFuY2UocyAgaW50W10sIHQgaW50W10pJCBkb3VibGUiLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGFya1wiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ), I'd like to see a colon separating `s` and `t` from their type, but a space doesn't produce one, and adding a colon seems to violate the grammar

(the below is invalid, but maybe there's a different way to specify this?)
```
classDiagram
class Social
<<utility>> Social
Social: +distance(s : int[], t : int[])$ double
```

**Comment by hcientist** [comment]
hmmm, likewise for fields. The [following example](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBQb3NzZVxuUG9zc2U6IC1ERUZBVUxUX1NJWkUgaW50JCIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkYXJrXCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9) almost works, but is missing a colon delimiter that I'd expect between identifier and type

```
classDiagram
class Posse
Posse: -DEFAULT_SIZE int$
```

**Comment by FelixSelter** [comment]
Hi, I noticed a workaround but I agree. THIS FEATURE IS ESSENTIAL  

This fails:
````mermaid
classDiagram:
    class A
        A: method(arg: int)
```

But this works
```mermaid
classDiagram
class A{
    method(arg: int): boolean
}
