### ISSUE TITLE
Using `constructor` as a node name/id causes syntax error

### ISSUE THREAD

**Issue by ssmooncoder** [mermaid-js/mermaid#2672]
Example:

```
flowchart TB
    A-->constructor
    constructor-->B
```

This will break the render engine

**Comment by kirilligum** [comment]
i get this one too. a bit hard to make diagrams of solidity objects

**Comment by nirname** [comment]
`constructor` is a keyword. It is arguable if a node name could coincide with a keyword.
Please, use this
```
flowchart
    A-->B[constructor]
```

```mermaid
flowchart
    A-->B[constructor]
```

Any other combination for constructor works
```
flowchart
A --> constructor-B
```

```mermaid
flowchart
A --> constructor-B
```

**Comment by jgreywolf** [comment]
For now I am closing this based on comment from @nirname 
Use aliasing for "protected" names
