### ISSUE TITLE
Configuration of Rendering Flow Chart

### ISSUE THREAD

**Issue by ricenoddle** [mermaid-js/mermaid#2723]
Hello guys, I'm now rendering a flow chart as following:
```
```mermaid
graph TD

 User-->something

something --> somePoint

somePoint --> balblabla & lalalala

somePoint -- <<dfdfdfd>> --- jajajajaj

jajajajaj --> dfdfdfdf
```

And I got the result:
![image](https://user-images.githubusercontent.com/13479751/153834656-97cbbde8-6555-4ae5-a523-13eb21c993d9.png)

Through the screen shot you can see that `<<dfdfdfd>>` is not rendered correctly. **(What I'm looking for is this can be rendered.)**

In the end I found that I need to add spaces as `<< dfdfdfd >>` so it can be rendered correctly.
![image](https://user-images.githubusercontent.com/13479751/153835056-4fe777e3-ecdf-4e25-9d61-b3ee3d0a0c12.png)

So is it possible to config something to make it work ? I have tried my best to find but unfortunatelly failed.

**Comment by KSR-Yasuda** [comment]
This may work:

* Use HTML entity references for `<` -> `#lt;` and `>` -> `#gt;`
* Quote the string by `"`

```text
graph TD

 User-->something

something --> somePoint

somePoint --> balblabla & lalalala

somePoint -- "#lt;#lt;dfdfdfd#gt;#gt;" --- jajajajaj
%%           ^^^^^^^^^       ^^^^^^^^^

jajajajaj --> dfdfdfdf
```

```mermaid
graph TD

 User-->something

something --> somePoint

somePoint --> balblabla & lalalala

somePoint -- "#lt;#lt;dfdfdfd#gt;#gt;" --- jajajajaj
%%           ^^^^^^^^^       ^^^^^^^^^

jajajajaj --> dfdfdfdf
```

**Comment by ricenoddle** [comment]
> This may work:
> 
> * Use HTML entity references for `<` -> `#lt;` and `>` -> `#gt;`
> * Quote the string by `"`
> 
> ```
> graph TD
> 
>  User-->something
> 
> something --> somePoint
> 
> somePoint --> balblabla & lalalala
> 
> somePoint -- "#lt;#lt;dfdfdfd#gt;#gt;" --- jajajajaj
> %%           ^^^^^^^^^       ^^^^^^^^^
> 
> jajajajaj --> dfdfdfdf
> ```

Yes, this do work, but it's not that convenient for an user. For now I can only add spaces in `<< dfdfd >>`.

BTW, I also tried this in `vscode` and it works fine, so I guess there may be a config to make this work ?
![image](https://user-images.githubusercontent.com/13479751/153838632-954f34d7-0c77-4595-a0a7-51d67dfdaf4e.png)

**Comment by KSR-Yasuda** [comment]
Probably it would misunderstood as an HTML tag.

As there it allows HTML tag use (such as `<strong>`, etc.),
I think you should escape such special characters for safe conversion.

Also, it would depend on *viewer / editor* you use:
it breaks if only the viewer you use converts such `<html_tag_like_text>` unexpectedly
(I mean, Markdown editors, for example, may touch such expressions).
Badly converted graph code being passed, it is not Mermaid lib's business.

I think you should not stick with such sensitive expressions.

**Comment by ricenoddle** [comment]
Yes, I agree. It depends on different renderer.
