### ISSUE TITLE
Request feature for sequence diagram to start arrow from right to left

### ISSUE THREAD

**Issue by zulfadlizainal** [mermaid-js/mermaid#2724]
In telecom network theres many occasion where the right side of the node are sending the signal first to the left side of the node.

For example below, 'UE' node should always be in the left and 'Network' should always be on the right side. But Network should be able to send the signal first.

Currently:
Network->>UE: ...... (This can solve the issue, but in this case Network node already be on the left side. In telecom standard UE should always be on left side)

Request:
UE<<-Network....... (**'<<-' Currently opposite direction arrow not supported based on docs**)

![image](https://user-images.githubusercontent.com/50709439/153873443-44a9040b-47b3-4195-813d-f9dd4886fe5e.png)

Example picture source: [Sharetechnote](https://www.sharetechnote.com/)

**Comment by adam-hotait** [comment]
You can force the order of the participants by declaring them beforehand, like so:

```
sequenceDiagram
  participant UE
  participant Network
 
  Network ->> UE: right to left
```
which gives out:
```mermaid
sequenceDiagram
  participant UE
  participant Network

  Network ->> UE: right to left
```
