### ISSUE TITLE
Consider calling gitGraph a railroad diagram

### ISSUE THREAD

**Issue by dbc60** [mermaid-js/mermaid#2734]
There's no problem. I just came across mermaid and am very excited about the project. When I saw what the experimental `gitGraph` produced, it struck me as a [railroad diagram](https://en.wikipedia.org/wiki/Syntax_diagram), so I thought I'd mention that a name change or allowing for an alternative name, like "railroad" might be nice.

**Comment by bolshoytoster** [comment]
@dbc60 maybe we could have it as an alias.

It could be implemented like `requirementDiagram` and `requirement`:
https://github.com/mermaid-js/mermaid/blob/9110bdfb5d7a205fa1dc5dc8d747ae98503620d2/src/utils.js#L233-L235
https://github.com/mermaid-js/mermaid/blob/1baca16a51e939bbbc27a9b541a858d4430fefda/src/mermaidAPI.js#L138-L141

I'm happy to open a PR for this if you want.
