### ISSUE TITLE
erDiagram comments not rendering properly

### ISSUE THREAD

**Issue by imaginedbyme** [mermaid-js/mermaid#2738]
**Describe the bug**
It looks like the comment column is rendering as the second column, overlapping the attribute name and whether it's a FK/PK etc. Happens on the documentation and on GitHub, but not on the live editor

I thought it was only happening on my local copy/on GitHub, but it's happening on the documentation as well (see here: https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram?id=attribute-keys-and-comments but not on the live editor https://mermaid.live/edit#pako:eNp1kU1OxDAMha9ihe30At2NaJEQUEYdxKob07jFIj8oSUGo07uTIRGIFryx8_wpek-eRW8liVKQqxhHh7ozEOty38LpVBR2hmZ_V1dF1V4_1i2UgErZd_9DzWk8lw-OzZgIkpXjN3JwdQOdeHgmUNyT8QR2gBCfmQL5hXVi842jkeOIga1pJv0UoTWi8YW2Ygykkrqkdqjb433zTx72v6BtnGTQ32b7h3Weiz-8D-x8aFBv3SlcL9gEwDELi9gJTU4jy3iUaOYsTK8SA9WSg3WiHFB52gmcgj1-mP5bSFS-YlaXT7RPlq0)

**To Reproduce**
1. Write a comment on an erDiagram attribute

**Expected behavior**
The comment should appear as the final column.

**Screenshots**
Documentation:
![image](https://user-images.githubusercontent.com/38689429/154358194-43b8a02c-dd34-4038-8cd6-fb5eff4c8cfb.png)

Live Editor:
![image](https://user-images.githubusercontent.com/38689429/154358506-6ea92896-3e8b-4f32-9465-687864248b94.png)

**Code Sample**
Live Editor link above

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 98.0.4758.102

**Additional context**
I couldn't find an open issue about this, so my apologies if there is one already

**Comment by RonaldZielaznicki** [comment]
Likely a known issue #2346, #2548 that was fixed in 8.13.9, #2598.

I would guess that github is using a version earlier than 8.13.9

**Comment by Yash-Singh1** [comment]
Closing as issue is now resolved.
