### ISSUE TITLE
Documentation should give a list of built-in themes

### ISSUE THREAD

**Issue by joachim-n** [mermaid-js/mermaid#2757]
**Describe the bug**

The docs mention themes on passing (default, dark, forest) but I can't find a simple list of all the themes that are built-in.

**Expected behavior**

Docs should have a list of themes.

**Comment by NeilCuzon** [comment]
Thanks for bringing it to our attention. I've made the appropriate changes to the documentation in branch. It should be available in the GitHub pages site after it is committed to Master.

**Comment by sidharthv96** [comment]
Fixed in https://github.com/mermaid-js/mermaid/commit/321c2a73dd132e841180802cb16b06a8ba5258a8 
Available at https://mermaid-js.github.io/mermaid/#/theming?id=deployable-themes

Thanks for the suggestion @joachim-n :)
