### ISSUE TITLE
Convert Diagram such that they can be put in comments

### ISSUE THREAD

**Issue by panwarab** [mermaid-js/mermaid#2759]
**Is your feature request related to a problem? Please describe.**
I like when the design of an algo is presented along with the code rather than in some far fetched documentation. If using mermaid, we can convert the diagram such that we can simply put it as comments in the code, I think that would be really cool. I am working myself on a similar vscode extension. would love to work on this if required.

**Describe the solution you'd like**
Diagrams should be commentable such that they can be put in code

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by jgreywolf** [comment]
Personally I question this as I find most comments in code to be abhorrent :)  As a general rule, a comment is an apology or a lie. If you have to add comments to explain what the code is doing, than it is possible that the code should be re-written so it is more clear ;)

Having said that - What are you working on regarding the vscode plugin?

Also, what would this look like if it was a large mermaid diagram?

Finally - does the language you are using support multiline comments, such as /# #1944

**Comment by sidharthv96** [comment]
This is out of scope for the mermaid project. 
Whichever plugin/extension that reads the comment should extract the mermaid code from the comments and pass it to `mermaid.render`. 

You can also check out Mermaid Chart VSCode plugin 
https://www.mermaidchart.com/blog/posts/mermaid-chart-announces-visual-studio-code-plugin
