### ISSUE TITLE
Add v prefix to release tags

### ISSUE THREAD

**Issue by aohorodnyk** [mermaid-js/mermaid#2771]
**Is your feature request related to a problem? Please describe.**
Hello,

I'm using mermaid as a dependency for [Hugo](https://gohugo.io). This project uses go.mod dependency mechanism.
Hugo requires to have `v` prefix for all release tags, like `v8.14.0` or `v1.0.0`.

I see that mermaid already contains tags with releases. However, all these tags do not contain v prefix.

Is it possible to ask to add v prefix to release tags or create two separate release tags (with prefix and without prefix)?

Thanks a lot

**Describe the solution you'd like**
I'd like to see v prefix in release tags.

**Describe alternatives you've considered**
I believe that v prefix for release tags is kinda standard for now. It will be good to have this prefix.

**Additional context**
None

**Comment by Ash-KODES** [comment]
Please assign this issue to me!
Thankyou

**Comment by aohorodnyk** [comment]
Is is possible to manually add at least for the latest release and following releases, until the issue will be solved?

**Comment by knsv** [comment]
We will add this to out release process
