### ISSUE TITLE
double arrow is not being supported in mermaid.live site even though the documentation states so

### ISSUE THREAD

**Issue by benibilme** [mermaid-js/mermaid#2772]
Hello,

Following gives compile error at  mermaid.live online site even though it stated in the documentation. Is it really supported or is the site using an older version? 

````
graph LR;
A -- B
````

Following compiles but does not generate the double headed arrow. 
````
graph LR;
A <--> B
````

How can I create a simple link between two nodes without arrow head? 
How can I create a link between two nodes with double arrow head on both sides? 
Thanks in advance.

**Comment by EstebanDalelR** [comment]
Try with flowchart
```
flowchart LR
   A <--> B
```
```mermaid
flowchart LR
   A <--> B
```

**Comment by sidharthv96** [comment]
It's working now.
https://mermaid.live/edit#pako:eNpFjstOwzAQRX_FmnXakATSNkVIrWAHG9ghb6bxJLYU25EzRqqi_DtuELCb-9CdM0PrFUEDfcBRi9f3o3Qn8bjZPIkzZGApWDQq5bN0QkhgTZYkNOlU1GEcWIJ0S6rGUSHTizLsAzQdDhNlgJH9x9W10HCI9Ft6Npje2b_WiO7T-39N68jbD9jKl8HgUVEanoGv4wpsJk5-611n-psfw5BszTxOTZ7f4m1vWMfLtvU2n4zSGFh_Heq8Lus9lhXVuwofqkq1l-Kw78r7olO7u6JEWJblG91NXDQ
