### ISSUE TITLE
Allow characters other than [A-z] to be used in class diagrams

### ISSUE THREAD

**Issue by aliyome** [mermaid-js/mermaid#2779]
**Is your feature request related to a problem? Please describe.**

In the class diagram, I tried to put the field and method names in Japanese but I couldn't do it.
For Japanese, the use of Japanese in class diagrams is very descriptive and valuable.
In the current specification, field and method names are specified as `\w+` in regular expressions, so only [A-z] can be set.

**Describe the solution you'd like**

I want to change the regular expression to `.+`, and I want to allow characters other than [A-z].

**Describe alternatives you've considered**
None

**Additional context**
Please see the following figure for the current behavior.
If the field and method names are specified in [A-z], they work correctly.
However, if the field name and method name are specified with characters other than [A-z], such as Japanese, part of the method name will be missing, "*" and "$" will not work, and the return type will not be drawn.

![image](https://user-images.githubusercontent.com/843286/155865033-4b949e71-166a-4907-a598-5e493cbba3c7.png)

If this is unexpected behavior, would it have been better to create an issue as a bug report?

**Comment by jgreywolf** [comment]
We are no longer using the `fieldRegEx` and `methodRegEx` in order to determine how to organize members.  After the release of #4534 this issue may be resolved

**Comment by aliyome** [comment]
Thank you for your support. I apologize for my delayed response. I have checked the current release and confirmed that the issue has been resolved. Thank you!!
