### ISSUE TITLE
Doc improvements for sequence diagram examples

### ISSUE THREAD

**Issue by riaanduplessis** [mermaid-js/mermaid#2795]
## The issue

In a lot of cases, sequence diagrams would be beneficial for making documentation around systems more clear, in which case, the 'Actors' or 'Participants' would be presented as components of an application, system, module or even network. Showing the interaction between these various components.

The current documentation around sequence diagrams builds upon the premise of 'Actors' and 'Participants' by using examples where they are represented as people and the interactions are simple communications. 

This fails to provide a clear and deeper technical understanding to the reader as to the true use-cases of these diagrams.

## The Question

I'd like to add more technical diagrams to the [sequenceDiagram.md](https://github.com/mermaid-js/mermaid/blob/develop/docs/sequenceDiagram.md) page that give examples more orientated towards software, such as inner workings of classes in OOP, or instance communication in a cloud network.

Are there be any suggestions, or objections, to this before I submit work on this?

**Comment by chrismetz09** [comment]
More examples of sequence diagrams would be great!
