### ISSUE TITLE
Mermaid Mindmapping 

### ISSUE THREAD

**Issue by ghost** [mermaid-js/mermaid#2806]
I like to use mermaid as my mindmapping and flowchart tool but I am missing some necessary options to use it with no issues.

1. I did not find a way to insert a quad arrow
2. I did not find a way to create tree diagrams
3. I did not find a way to create a circular diagram
4. I did not find a way to make the nodes foldable
5. etc..

I would appreciate if someone can help me to use mermaid with these features.

Thanks.

**Comment by edgriebel** [comment]
See #448 for a lot of existing commentary on this

**Comment by knsv** [comment]
It is in the works.
