### ISSUE TITLE
#664 not solved?

### ISSUE THREAD

**Issue by hoclun-rigsep** [mermaid-js/mermaid#2828]
Hi!

This should be possible now, see the attached example.

https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZmxvd2NoYXJ0IExSXG4gICAgQSAtLT4gQlxuICAgIFxuc3ViZ3JhcGggQlxuICAgQ1tJbiB0aGUgc3ViZ3JhcGdoXVxuZW5kIiwibWVybWFpZCI6e30sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

Will close this for now.

_Originally posted by @knsv in https://github.com/mermaid-js/mermaid/issues/644#issuecomment-771053466_

I don't see any edge at all when I click on that link.

**Comment by anotherglitchinthematrix** [comment]
Maybe because of the poor styling in the dark theme?
```mermaid
flowchart LR
    A --> B
    
subgraph B
   C[In the subgrapgh]
end
```

**Comment by hoclun-rigsep** [comment]
Maybe, I mean it looks all right now. If nobody else can confirm I would not object to closing this issue.

**Comment by Yash-Singh1** [comment]
@hoclun-rigsep By default, the `mermaid-live-editor` won't override the configuration when you're in dark mode to set `theme` to `"dark"`, so the edge would render colored as if it were in light mode. Setting:

```json
{
  "theme": "dark"
}
```

Gives you the expected result:

![Screenshot from 2022-05-10 18-45-20](https://user-images.githubusercontent.com/53054099/167752166-4a09f2b8-0bc0-434a-a8ef-ae825164ec36.png)
