### ISSUE TITLE
Syntax Error with nested subgraphs

### ISSUE THREAD

**Issue by hwsoderlund** [mermaid-js/mermaid#2829]
**Describe the bug**

When one node is pointing at a subgraph at the root level, and another node is pointing at a nested subgraph inside the root subgraph, mermaid reports a Syntax Error.

**Code Sample**

### This works, when both senders are pointing at the main subgraph (system)

```mermaid

flowchart TD

sender-1 --> system --> receiver-1
sender-2 --> system --> receiver-2

subgraph system
  subgraph sub-system
    service-1
    service-2
  end
end
```

### This also works, when sender-2 is pointing at service-2 _inside_ the nested subgraph (sub-system)

```mermaid

flowchart TD

sender-1 --> system --> receiver-1
sender-2 --> service-2 --> receiver-2

subgraph system
  subgraph sub-system
    service-1
    service-2
  end
end
```

### This, however does not work (Syntax Error), when sender-2 is pointing at the nested subgraph (sub-system)

````
```mermaid

flowchart TD

sender-1 --> system --> receiver-1
sender-2 --> sub-system --> receiver-2

subgraph system
  subgraph sub-system
    service-1
    service-2
  end
end
```
````

Notes:

- If I remove sender-1, it works. So it's the combo of sender-1 pointing at the main subgraph _and_ sender-2 pointing at the nested subgraph, that causes the crash.
- I am mainly using the VS Code extension, running mermaid 8.13.10. Error message: Syntax error in graph.
- I have also tested in the live editor, with version 8.14.0, using latest Chrome on MacOS and it breaks there too, but the page is empty, with no visible error message.
- I have also tried in FireFox using the live editor, with the same result.

Link to live editor:

https://mermaid.live/edit?gist=#pako:eNptjj0SgjAQha-S2ZoUUlJY4Qm03CYkq2Q0gVkSHIbh7iagaGGzs--9b39m0J0hqOD66J66VRzEpUaPfiBviOVBSHkUwzQEcmvLpMmOOdmZcmNiI_9x5botNjdWffvehF6Ir7UPZjsFxKPVlA_8yjLLdBB9KlCAI3bKmvT6nBOE0JIjhCq1RvEdAf2SuNgbFehkbOgYqsCRClAxdOfJ64_emNqq9JHbzOUF-otgnw

**Expected behavior**

It should not crash.

**Comment by nirname** [comment]
Closing this in favor of #4644, please refer to the new issue. It is a error that comes across different issues.
