### ISSUE TITLE
@braintree/sanitize-url is used in this project whhile it has security problems

### ISSUE THREAD

**Issue by Mister-Hope** [mermaid-js/mermaid#2845]
Maybe trying to upgrade to v6?

**Comment by eyllanesc** [comment]
It seems that the package has already been updated (See https://github.com/mermaid-js/mermaid/commit/7b0c3c3cd50a1cc9bae5fb721dd1679db2537920) but the release has not been created yet

**Comment by huineng** [comment]
any outlook when it will be published ?

**Comment by Mister-Hope** [comment]
Any release schedule?

**Comment by valmoz** [comment]
Any news?

**Comment by IdiosApps** [comment]
Any update? As others say, the [mermaid repo has up-to-date dependencies that are safe for @braintree/sanitize-url](https://github.com/mermaid-js/mermaid/blob/develop/package.json#L60) - but there's no release. 

My `npm` is very confused with `npm audit`/`npm audit fix`/`npm audit fix --force`:

```
# npm audit report

@braintree/sanitize-url  <6.0.0
Severity: moderate
Cross-site Scripting in sanitize-url - https://github.com/advisories/GHSA-hqq7-2q2v-82xq
fix available via `npm audit fix --force`
Will install mermaid@8.2.2, which is a breaking change
node_modules/@braintree/sanitize-url
  mermaid  >=8.2.3
  Depends on vulnerable versions of @braintree/sanitize-url
  node_modules/mermaid

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

I'm on latest mermaid (8.14.0) - not sure why npm wants to downgrade to 8.2.2. [Both mermaid 8.2.2 and 8.14.0 are on braintree `^3.1.0`](https://github.com/mermaid-js/mermaid/compare/8.2.2...8.14.0)
