### ISSUE TITLE
Generic type information not used as part of class name

### ISSUE THREAD

**Issue by Andras-Csanyi** [mermaid-js/mermaid#2856]
Hi All,

I'd like to display the case when a non-generic interface is implemented by a generic interface. A good example for this comes from `C#` where the `IEnumerable<out T> : IEnumerable` [like so](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1?view=net-6.0). 

The following code creates a self reference which is not true.

It seems for mermaid  `IEnumerable~out T~` and `IEnumerable` are the same, however they aren't.

```mermaid
classDiagram

    IEnumerable~T~ <|-- IEnumerable : implements

    class IEnumerable~out T~
    <<interface>> IEnumerable~out T~
    class IEnumerable
    <<interface>> IEnumerable

```

**Comment by jgreywolf** [comment]
@Andras-Csanyi This is because the generic type definition is not used as part of the class box id/name. I am looking into some other ways we could possibly handle something like what you are asking though

**Comment by jgreywolf** [comment]
Closing in favor of #4762 which has more discussion
