### ISSUE TITLE
Can my tool get added e.g. to the Use-Cases and Integration section?

### ISSUE THREAD

**Issue by KarnerTh** [mermaid-js/mermaid#2859]
I created a small cli called [mermerd](https://github.com/KarnerTh/mermerd) that lets you generate mermaid-js ERDs from your existing database. Maybe the tool will help others too - could it be added e.g. in the "Use-Case and Integrations" section of your website?

**Comment by knsv** [comment]
Sorry for the late response. I have avoided the issues during the spring as it would eat all of the available time for the project. As for your question, I think it is a good idea. You can easily create a PR for this that would be approved and merged.
