### ISSUE TITLE
Allow users to configure fontsize in flowchart

### ISSUE THREAD

**Issue by Mister-Hope** [mermaid-js/mermaid#2896]
Just like the other digrams.

**Comment by PaulRBerg** [comment]
any updates on this?

Is there really no way to customize the styles for flowchart labels?

related: https://github.com/mermaid-js/mermaid/issues/3324

**Comment by huynhicode** [comment]
> Just like the other digrams.

Hi @Mister-Hope 

@PaulRBerg posted a [discussion](https://github.com/orgs/mermaid-js/discussions/4244) related to your issue -  configuring the font size of flowcharts. 

I have copy pasted my response from the [discussion](https://github.com/orgs/mermaid-js/discussions/4244) below.

----

"Hi @PaulRBerg 

There are two ways of customizing themes: site-wide and to individual diagrams.

To set the font size to an individual diagram, modify the `themeVariable`by setting `fontSize` to the desired size.  The default is 16px.

Here is a link to our documentation on [Theme Configuration](https://mermaid.js.org/config/theming.html#theme-configuration).

![Screenshot 2023-03-24 at 10 13 34 AM](https://user-images.githubusercontent.com/35910788/227594957-8c7c9580-8f0c-4743-aac1-2d7d76ed5a65.png)

Here is an example from [Mermaid.Live](https://mermaid.live/edit#pako:eNpVkMFOhEAMhl9l0pMmkOjBCwcTF3QvazTZjQeBQ4UOMxGmk2HIugLv7iCa7PbU9vv_tukIFdcECciWj5VC58UhK4wI8ZCnyuned9iXIo7vpy150bGh0yQ2V1sWvWJrtWmuV_1mEYl03C0yEl5p8zmvKP31vxiaRJbv0Hq25Tk5HHkSj7l-VWH8JVGOguspl5hIjCt0IkVXQgQduQ51HU4fF0MBXlFHBSQhrUni0PoCojP0hk7jR0v9ohnXJQVINn6vv_-Mt3c39quABYbT57AGB8_7k6kg8W6gCAZbo6dMY-Ow-29aNO_MoZTY9qGmWnt2z-tnKzZSNzD_AAX_dVA)( (screenshot below) where I have set the `fontSize` of my `flowchart` to `150px`.

![screencapture-mermaid-live-edit-2023-03-24-10_01_17](https://user-images.githubusercontent.com/35910788/227592487-59e9f718-1d92-4751-b468-1da8e6d7bb4c.png)

Also, if you haven't joined already, there is a [Slack workspace](https://mermaid-talk.slack.com/) where you can post questions or see if someone else has posted a similar question for a quicker resolution."

**Comment by AmulyaParitosh** [comment]
@huynhicode I did find this solution in the documentation but it does not work for Gantt charts.
![Screenshot_20240331_023540](https://github.com/mermaid-js/mermaid/assets/76733670/316008ac-431f-44fa-9e62-ee7048881b55)

In gantt charts texts tends to get very small. Is there any solution for this?

**Comment by Mister-Hope** [comment]
> @huynhicode I did find this solution in the documentation but it does not work for Gantt charts.
> ![Screenshot_20240331_023540](https://github.com/mermaid-js/mermaid/assets/76733670/316008ac-431f-44fa-9e62-ee7048881b55)
> 
> In gantt charts texts tends to get very small. Is there any solution for this?
> 

I have that issue too,  But it is better for you to open it in a new issue
