### ISSUE TITLE
Add accessibility docs for title and description elements

### ISSUE THREAD

**Issue by lindseywild** [mermaid-js/mermaid#2905]
**Is your feature request related to a problem? Please describe.**
The work that is being done in https://github.com/mermaid-js/mermaid/issues/2732 would be great to add to the docs about how to use the `title` and `description` elements to create more accessible charts.

**Describe the solution you'd like**
Documentation explaining the updates, why they're important, and how to use them.

**Describe alternatives you've considered**

**Additional context**
This is dependent on https://github.com/mermaid-js/mermaid/issues/2732 and which chart types have implemented the new fields. I think it should wait until that issue is complete before doing this.

**Comment by knsv** [comment]
There are some info about this in the docs:
https://mermaid-js.github.io/mermaid/#/accessibility?id=defining-accessibility-options

Can we close this issue?

**Comment by lindseywild** [comment]
@knsv Yep - thank you! If there are follow up suggestions I can open a new story 😄
