### ISSUE TITLE
Can this diagram be converted to Mermaid Syntax? If so, How?

### ISSUE THREAD

**Issue by kingram6865** [mermaid-js/mermaid#2909]
I don't have any code for this yet. I'm just getting started with MermaidJS.
This is the file:

![DiagramSample](https://user-images.githubusercontent.com/13263318/162089416-5c3cf803-575a-4b37-8a00-6bdf75b49e6f.png)

**Comment by DanielOaks** [comment]
Hey there! There are a couple of ways I'd go about showing this.

-----

You could use a flowchart with subgraphs, though you might need to fill it out a bit more to see it fully working:

```
flowchart LR
    subgraph one[Context 1]
    action1[Action 1]
    end
    subgraph two[Context 2]
    action3[Action 3]
    end
    subgraph three[Context 3]
    end
    subgraph four[Context 4]
    action2[Action 2]
    end

    action1 --> action2 --> action3
```

```mermaid
flowchart LR
    subgraph one[Context 1]
    action1[Action 1]
    end
    subgraph two[Context 2]
    action3[Action 3]
    end
    subgraph three[Context 3]
    end
    subgraph four[Context 4]
    action2[Action 2]
    end

    action1 --> action2 --> action3
```

-----

Or as a sequence diagram (which will preserve the order of contexts better):

```
sequenceDiagram
    participant Context 1
    participant Context 2
    participant Context 3
    participant Context 4
    Context 1->>Context 4: Action 1
    Context 4->>Context 2: Action 2
    Context 2->>Context 1: Action 3
```

```mermaid
sequenceDiagram
    participant Context 1
    participant Context 2
    participant Context 3
    participant Context 4
    Context 1->>Context 4: Action 1
    Context 4->>Context 2: Action 2
    Context 2->>Context 1: Action 3
```

-----

I'd recommend playing around with the example diagrams on [the live editor](https://mermaid.live/), and if you haven't already you can take a look at the Diagram Syntax pages on the sidebar here: https://mermaid-js.github.io/mermaid/#/README?id=diagram-types

Hope this helps!

**Comment by kingram6865** [comment]
Thanks Daniel. This is helpful.

I think I was assuming an exact replication would be necessary, but I can see the idea
is still conveyed.

**Comment by knsv** [comment]
The sequence diagram was spot on I think!
