### ISSUE TITLE
GitGraph: commit options for merge commits e.g. tags

### ISSUE THREAD

**Issue by from-nibly** [mermaid-js/mermaid#2934]
**Is your feature request related to a problem? Please describe.**
Merge commits should be treated like ordinary commits, in that they should be customize-able with the same syntax. e.g.

```
commit tag: "vx.x.1" type: HIGHLIGHT id: "1"
merge develop tag: "vx.x.1" type: HIGHLIGHT id: "2"
```

**Describe the solution you'd like**
The syntax tree for `merge` should probably just be exactly the same as the `commit` tree after the branch name.

**Describe alternatives you've considered**
Alternatively merge could be a special case I guess, but git is going to have largely the same information in a merge commit as a normal commit, except for the fact that it will have two parents, which would be described by the graph itself.

**Additional context**
Right now I need to add a fake commit after a merge to express that I would like to add a tag to a merge commit.

**Comment by theory** [comment]
I had exactly the same thought just now as I tried to make a tag on a merge commit. Thanks!
