### ISSUE TITLE
GitGraph: Arbitrary vertical ordering of branches

### ISSUE THREAD

**Issue by from-nibly** [mermaid-js/mermaid#2937]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to order branches arbitrarily i.e. not according to their checkout "time".  Especially in git flow diagrams sometimes you want put some branches in-between two old branches. It would be awesome to be able to arbitrarily order the branches vertically

**Describe the solution you'd like**
A really basic one would be to add a "branchOrder" option to the gitGraph options e.g.

```js
init: {
  gitGraph: {
    branchOrder: [ "master", "version_1.1.1", "develop"]
  }
}
```

but ideally the syntax would allow you to order them, maybe in relation to each other?

something like
```
commit
branch develop
checkout develop
commit
commit
branch release_1.0.0 after main <--- new syntax
checkout release_1.0.0
commit
checkout develop
merge release_1.0.0
checkout main
merge release_1.0.0
```

**Describe alternatives you've considered**
Right now I can't order them at all.

**Additional context**
see also Release Branches
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by husa** [comment]
Alternatively syntax could look like 
```
gitGraph
      commit
      commit
      branch two order: 2
      commit
      checkout main
      commit
      branch three order: 3
      checkout three
      commit
      checkout main
      commit
      commit
      branch one order: 1
      checkout one
      commit
      checkout two
      commit
      checkout main
      merge two
      commit
``` 
to result in 
<img width="705" alt="mermaid-gitgraph-branch-order" src="https://user-images.githubusercontent.com/1536549/164054656-14b3bb5a-c550-4d16-aff3-56ff866ee07d.png">

That can be achieved relatively easy.

With a few caveats:
1. "main" branch is always first
2. therefore only positive `order` is accepted
3. all branches without explicit order will fit between 0 and 1

**Comment by from-nibly** [comment]
Love it. Would it then just fill in gaps if any with un ordered branches?

**Comment by husa** [comment]
It'll place them first(after `main`)
For example:
```
branch one order: 1
branch two order: 2
branch unordered1
branch three order: 100 // order doesn't have to be sequential
branch unordered2
```
would result in

1. main
2. unordered1
3. unordered2
4. one
5. two
6. three
