### ISSUE TITLE
Search results in documentation cannot be clicked

### ISSUE THREAD

**Issue by mootari** [mermaid-js/mermaid#2939]
**Describe the bug**

The search on https://mermaid-js.github.io/mermaid/ is essentially broken, as clicking any result has no effect if it doesn't point to the current page.

**To Reproduce**
1. Go to https://mermaid-js.github.io/mermaid/#/
2. Type "render" in the search field
3. Click the second result, "defaultRenderer"

The click has no effect, and the console displays the following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at e.code ((index):99:24)
    at n.parse (docsify.min.js:1:61215)
    at Function.n.parse [as parser] (docsify.min.js:1:60771)
    at docsify.min.js:1:85819
    at docsify.min.js:1:122
    at On.compile (docsify.min.js:1:86111)
    at docsify.min.js:1:102643
    at docsify.min.js:1:93367
    at docsify.min.js:1:92131
    at Nn (docsify.min.js:1:93099)
```

**Comment by Yash-Singh1** [comment]
It turns out that page itself doesn't work because the code blocks there don't have any language ID.

**Comment by Yash-Singh1** [comment]
Tested and working with #2942.
