### ISSUE TITLE
Inconsistent diagram rendering at Kubernetes docs website 

### ISSUE THREAD

**Issue by chrismetz09** [mermaid-js/mermaid#2941]
**Describe the bug**
Accessing [k8s.io](https://kubernetes.io/) website with Firefox and Chrome browsers displays inconsistent diagram rendering characterized by correct diagram, syntax error message or blank rectangle.

[K8s docs repo](https://github.com/kubernetes/website)

---
 
**To Reproduce**
Using Mermaid 8.13.0:

1. Go to [K8s Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/)
2. scroll down to Ingress diagram
3. On initial page load or reload using Firefox or Chrome, you will see correct rendering, a syntax error or blank rectangle. A page reload may or may not clear the error. Behavior is unpredictable.
4. You can observe similar behavior for the diagrams located at https://kubernetes.io/docs/contribute/style/diagram-guide/

Mermaid 8.14.0 and 9.0.0 exhibit similar behavior.

---

**Expected behavior**
Mermaid diagrams should load and render properly on initial page load and reload.

---

**Screenshots**

Shows the blank rectangle: 
![Screen Shot 2022-04-14 at 3 33 44 PM](https://user-images.githubusercontent.com/5543858/163490316-e938a0b5-eccc-4a71-8fb7-f967c8c0947b.png)

Shows the syntax error: 

![Screen Shot 2022-04-14 at 3 36 32 PM](https://user-images.githubusercontent.com/5543858/163490385-d319c26f-508b-4757-8940-af0f71ce5b0d.png)

---

**Code Sample**
1. Goto https://kubernetes.io/docs/contribute/style/diagram-guide/ 
2. Click on the diagram to take you to live editor.

**Desktop (please complete the following information):**
 - Mac OS 10.15.7,  Ubuntu 20.0.4.
 - Browsers - Firefox 99.0.1 (64-bit); Firefox 97 for Ubuntu; Chrome 100.0.4896.88 and 
 - Mermaid 8.14.0 and 9.0.0

Website uses Hugo 0.87.0 and [Docsy theme](https://www.docsy.dev/) theme.

---

**Additional context**

1. [Issue #31960](https://github.com/kubernetes/website/issues/31960) provides more details on the problem.

2. We use a Hugo shortcode to wrap mermaid code: 

```
<figure>
<div class="mermaid">
    {{.Inner}}
</div>
</figure>
<!-- Hide content and error if JS is disabled. -->
<noscript>
  <div class="alert alert-secondary callout" role="alert">
    <em class="javascript-required">{{ T "javascript_required" | markdownify }}</em>
  </div>
</noscript>
```

BTW, we love Mermaid and created Diagram Guide encouraging docs contributors to use it.

**Comment by sftim** [comment]
FWIW, I _always_ see the “Syntax error in graph” error on initial load. Firefox 99.0 on amd64 Linux.

**Comment by chrismetz09** [comment]
For the blank rectangle diagram rendering, I observed height="16", style="max-width: 16px" and viewBox="0 0 16 16" in the svg element. Running chrome with Mermaid 9.0.0. Hard refresh (shift + command R) seems to clear the problem.

**Comment by knsv** [comment]
Is this still an issue?

**Comment by jgreywolf** [comment]
Closing due to lack of response/activity
