### ISSUE TITLE
flowchart linkStyle color not work anymore ?

### ISSUE THREAD

**Issue by yurenchen000** [mermaid-js/mermaid#2951]
**Describe the bug**

https://mermaid-js.github.io/mermaid/#/flowchart?id=styling-and-classes

```
linkStyle 3 stroke:#ff3,stroke-width:4px,color:red;
```
the `color` property no effect.
I remember it still working last month.

mermaid 8.13.4 in hedgeDoc also no effect.
mermaid.live seems v9.0.0 current

**To Reproduce**

```
graph TD
    A -->|000| B
    B -->|111| C

    linkStyle 1 stroke:#ff3,stroke-width:4px,color:red;
```

**Expected behavior**

**Screenshots**
// broken
![mermaind_linkstyle_err](https://user-images.githubusercontent.com/8458213/163781312-a03622aa-06bc-4937-8ee7-c9cfc3c3576e.png)

// old version effect (in hedgedoc, can't known js version)
![mermaid_linkstyle_ok](https://user-images.githubusercontent.com/8458213/163783180-bc67bdad-685c-467d-8167-dfb76b7f65ce.png)

**Desktop:**

- OS: ubuntu 20.04
- Browser: chrome 99, firefox 98

**Comment by knsv** [comment]
Thanks for reporting. A fix for this will be included in the 9.1.0 release.
