### ISSUE TITLE
 Flowchart subgraph independent layout support

### ISSUE THREAD

**Issue by lugtec** [mermaid-js/mermaid#2980]
The current flowchart can add sub-diagrams, which is great, but the sub-flowchart must keep the same layout as the overall flowchart, which makes me feel inconvenient;
If the sub-flow chart can support a different layout from the parent flow chart, for example, the overall flow chart is TB, and the sub-flow chart is LR, which will greatly facilitate the drawing of complex graphics.

**Comment by knsv** [comment]
This is possible using the direction statement:
https://mermaid-js.github.io/mermaid/#/flowchart?id=direction-in-subgraphs

**Comment by vassudanagunta** [comment]
It is supported:

```
flowchart LR
A --> B --> subgraph_X
subgraph subgraph_X
  direction TB
  C --> D
end
```

``` mermaid
flowchart LR
A --> B --> subgraph_X
subgraph subgraph_X
  direction TB
  C --> D
end
```

But it appears directions can't change if a node in the subgraph has a direct connection to a graph with a different direction declaration. `B --> C` below vs `B --> subgraph_X` above. 

```
flowchart LR
A --> B --> C
subgraph subgraph_X
  direction TB
  C --> D
end
```

``` mermaid
flowchart LR
A --> B --> C
subgraph subgraph_X
  direction TB
  C --> D
end
```

**Comment by vassudanagunta** [comment]
This can probably be closed since it is supported and the limitation I describe is already covered by #2410.

**Comment by knsv** [comment]
Close but not dropping the core issue. direction should work.
