### ISSUE TITLE
Support subgraph without title in flowchart

### ISSUE THREAD

**Issue by copperybean** [mermaid-js/mermaid#3000]
**Is your feature request related to a problem? Please describe.**
Sometimes I use subgraph to group a batch of nodes, I do not want to give it a title.

**Describe the solution you'd like**
Currently, I can write a subgraph as following
`    subgraph id [title]`
So is it possible to set empty title by empty brackets?

**Describe alternatives you've considered**
None

**Additional context**

**Comment by alfursan** [comment]
As far I know, this should work ... try

```mermaid
subgraph identifier[" "]
   a -->
end
```

**Comment by copperybean** [comment]
It works, tks

**Comment by flywire** [comment]
@copperybean close issue #3000

**Comment by omartrigui** [comment]
> As far I know, this should work ... try
> 
> ```
> subgraph identifier[" "]
>    a --> b
> end
> ```
> 
> ```mermaid
> flowchart TB
> a --> b
> subgraph id[" "]
>   b --> c & d & e
> end
> ```

Doesn't work for multiple subgraphs

**Comment by omartrigui** [comment]
> As far I know, this should work ... try
> 
> ```
> subgraph identifier[" "]
>    a --> b
> end
> ```
> 
> ```mermaid
> flowchart TB
> a --> b
> subgraph id[" "]
>   b --> c & d & e
> end
> ```

Doesn't work for multiple subgraphs. Alternatively, you can use `&nbsp` instead of `identifier[" "]`, but neither option supports multiple subgraphs.
