### ISSUE TITLE
Class diagram: method return value must not contain a colon

### ISSUE THREAD

**Issue by luusl** [mermaid-js/mermaid#3003]
When a method return value contains a colon the whole string is not shown. Is this not allowed?
[Sample](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNpNjt0KwjAMRl-l5EphT9BrfQLFq4KEJduK_ZE2RWT03S3bCn5X4XyHJCuMkRg0jA5zvlicE3oTVMtG1J2zrDtQyrMskU5nlVge6DoOMTw_Mb1smFuXhbT-F2r39sAAnpNHS-3sttqALOzZgG4j8YTFiQETalPLm1D4SlZiAj2hyzwAFom3bxhBSyrcpeP7w6o_qfZGuQ)

**Comment by jgreywolf** [comment]
Can you clarify what you are expecting to see?  It looks correct when I open your link

**Comment by luusl** [comment]
Yes, that's right. Now it's correct. When I entered the bug, the return value of the second method was not displayed.
