### ISSUE TITLE
What is the map file for?

### ISSUE THREAD

**Issue by theory** [mermaid-js/mermaid#3006]
I followed [some instructions](http://blog.lindenliu.com/2020/01/07/use-mermaid-jekyll.html) to add Mermaid to a company-private blog by adding [`mermaid.min.js`](https://unpkg.com/mermaid@9.0.1/dist/mermaid.min.js) to the blog repo and a `<script>` element to load it. It works great with no issues I can see except for this error in my browser:

```
[Error] Failed to load resource: the server responded with a status of 404 () (mermaid.min.js.map, line 0)
https://xxxxxx.pages.github.io/assets/js/mermaid.min.js.map
```

It makes sense it didn't find `mermaid.min.js.map` since I didn't copy it to the repository, though I see it [on the CDN](https://unpkg.com/mermaid@9.0.1/dist/mermaid.min.js.map). But since everything seems to be working for my simple flow diagrams, and the map file is huge, I'm curious what it's for. I failed to find information in the documentation; should it be mentioned there? Is it optional? For specific diagram types, perhaps?

TIA!

**Comment by sidharthv96** [comment]
Those are source map files, it has nothing to do with mermaid functionality. 
It is used to map the minified (min.js) code to the original source code to help facilitate debugging.

https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

**Comment by theory** [comment]
Ah, interesting. Is there a way to prevent the minified code from trying to load it?

**Comment by sidharthv96** [comment]
That's a browser feature. 
https://blog.praveen.science/avoiding-http-404-for-map-files-when-using-minified-css/

If you're copying the file to the repo, you could remove the `//# sourceMappingURL=` line.

**Comment by theory** [comment]
Ahh, good to know, thanks. I downloaded the file from https://unpkg.com/mermaid@9.0.1/dist/mermaid.min.js, so presumably every site using the CDN URL will be downloading it all the time. Maybe the line should be removed for the CDN distribution?

Would be nice if the browser only downloaded it if it was needed for debugging…

**Comment by sidharthv96** [comment]
> Would be nice if the browser only downloaded it if it was needed for debugging…

Seems like the browser only downloads it if you have devtools open. 
https://stackoverflow.com/questions/44315460/when-do-browsers-download-sourcemaps

**Comment by theory** [comment]
OH, LOL, which is naturally what I do when I then notice it doesn't load. Got it. A little magical but makes sense.
