### ISSUE TITLE
package.json main setting change enables svelte-kit / vite support

### ISSUE THREAD

**Issue by netfl0** [mermaid-js/mermaid#3009]
I was unable to get mermaid imports working in a svelte/kit webapp until I changed `main` in `package.json` to point to `dist/mermaid.js` instead of the current default of `dist/mermaid.core.js`

This change set on develop is working for me: https://github.com/d3fend/mermaid/commit/426d9f3baa745458a95e97cbd4f75af6c22f595d

I am sure you point main to `dist/mermaid.core.js` for a reason, but, probably due to my ignorance, it was not obvious to me. Hopefully this helps someone else who might run into this issue. 

I am using all the latest version of svelte-kit, vite, and mermaid (develop branch as of today).
```
"@sveltejs/kit": "next",
"vite": "^2.9.0"
```
(I am a bit new to the javascript packaging ecosystem)

**Comment by sidharthv96** [comment]
We're using latest sveltekit in live editor. You could take a look at the config there.
It was indeed a bit tricky to get things to work. 

https://github.com/mermaid-js/mermaid-live-editor

**Comment by netfl0** [comment]
Thank you. To clarify, I was able to get it to work with simple change I linked to, I was just wondering why this change was not already present in mermaid.
