### ISSUE TITLE
Sequence Diagrams with messageAlign smash text with `<br>`

### ISSUE THREAD

**Issue by kevinawoo** [mermaid-js/mermaid#3011]
**Describe the bug**
When create a sequence diagram with `messageAlign: left` config and the text contains `<br>` line breaks, all the lines gets smashed into the first line.

**To Reproduce**
1. Set the config to `{ "sequence": { "messageAlign": "left"} }`
2. Create a sequence diagram using `<br>` in the message

**Expected behavior**
The diagram to have left aligned text with line breaks, as in https://github.com/mermaid-js/mermaid/pull/1315
![image](https://user-images.githubusercontent.com/3469532/167208473-c8599c07-75d6-40df-9155-bbf4599016ee.png)

**Screenshots**
<kbd><img width="687" alt="image" src="https://user-images.githubusercontent.com/3469532/167208707-b659d643-daad-49e6-8511-7cd42488c597.png"></kbd>

You can see in the screenshot everything is smashed into the first line.

**Code Sample**
[Live Editor example](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNpVkEFrwzAMhf-KMIRc2qYtO5lR6LqxwgYbNLv54jlqYmbLmaNsLSH_fd7aQneT3vf0JDQIEyoUUmTZYMmyhAHyDj97JIN56nKPXadrXDtbUxJyh3vORxjHLFN0cd5bXUftFb11GKer1V0M36mSsHHWfECDzgVFZzXxHcavX_yIDMUfhW1ZvhaL2QJu3-MKtqFLt-BB-9bhzAR_ktfGYJsA44GLhr1TdIq63nlJKmA5n8PL02l0E4iReFoeW7wK-A-fkWpuJNwsFYmJ8Bi9tlV6z6AIQAlu0KMSMpUV7nXvWAlFY7L2baUZHyrLIQq5167DidA9h92RjJAce7yYzs86u8YfFrWDDA)

````md
```mermaid
%%{init: { 'sequence': {'messageAlign': 'left'} }}%%
sequenceDiagram
User->>Browser: Click hello
Browser->>Server: Get /hello HTTP/1.1 <br> Host: example.com <br> Accept: text/html
Server->>Browser: HTTP/1.1/ 200 OK <br> Content-Type: text/html <br> Content-Length: 42
```
````

Github Render:
```mermaid
%%{init: { 'sequence': {'messageAlign': 'left'} }}%%
sequenceDiagram
User->>Browser: Click hello
Browser->>Server: Get /hello HTTP/1.1 <br> Host: example.com <br> Accept: text/html
Server->>Browser: HTTP/1.1/ 200 OK <br> Content-Type: text/html <br> Content-Length: 42
```

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser: Chrome
 - Version: 101.0.4951.54

**Comment by PackElend** [comment]
> * Set the config to `{ "sequence": { "messageAlign": "left"} }`

where is that documented, even google does not find it.

that happens in my case
![image](https://user-images.githubusercontent.com/3542031/191356702-4e40bc9f-1162-4272-9ce7-9b3843599380.png)


https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNqNkt1rwyAQwP8V8amDFPb5kodCtnQfsHYjXVsYwhBzSYV4ZkYfRsj_vishT0WIIOjvfienZ8-VLYGnvIPfAKgg17J20ghkNFrpvFa6lejZ0-f-Ej4Wb_nL-mex-3j-OmbF-iqmsMVrVuQRBfwJ3HWE30T4bYTfRfh9hD8IFDhWsFytLqpN2eE927KNRm2CmWFuLS73HbgZKs256nFyecINOCN1SU3rz3cSnJINCJ7SsoRKhsYLnoyhqa3naE97A10na8gaXeOY4XR9In9gAgc6XAZvd3-oeOpdgISHtpR--hU8rWTTEYVSe-s249dRFitdUy496re1kzX8A9ybxBA

**Comment by kevinawoo** [comment]
@PackElend I found it from https://github.com/mermaid-js/mermaid/blob/37eb0454fd2698b5bf6083bc6c75b179761a2b7a/src/docs/Setup.md#messagealign

as well as going through the source https://github.com/mermaid-js/mermaid/blob/f63acea34af95dbf76992506361f25def54df1d7/src/config.type.ts#L274

**Comment by PackElend** [comment]
> https://github.com/mermaid-js/mermaid/blob/37eb0454fd2698b5bf6083bc6c75b179761a2b7a/src/docs/Setup.md#messagealign
that is very well hidden :)

I asked to update the docs: https://github.com/mermaid-js/mermaid/issues/3500

by the way, what does your alignment looks like?
Should it only be aligned on the arrow itself?
![image](https://user-images.githubusercontent.com/3542031/191436507-b2cf2c10-2a04-4035-bb6c-864e5fe0eafc.png)

**Comment by kevinawoo** [comment]
You're right, it does look a little weird.

Seems like `messageAlign` moved the message left, center, or right of the connection line. 

Maybe we should open a new issue to maybe introduce `messageAlign: centerLeft`?

**Comment by PackElend** [comment]
If you could do it today, it would be great otherwise I'll do it tomorrow
(late)

Le mer. 21 sept. 2022 à 19:20, Kevin Woo ***@***.***> a
écrit :

**Comment by PackElend** [comment]
eventually it is done https://github.com/mermaid-js/mermaid/issues/3594
