### ISSUE TITLE
Edge text background color as transparent

### ISSUE THREAD

**Issue by brunolnetto** [mermaid-js/mermaid#3021]
Hi

I try to highlight some main features on given graph. For that, I require coloring and bold-facing of some contours. I am able to do it well for nodes and edges. So far, so good. There is still a thing that grinds my gears: edge text background. I am not able to make it transparent, no matter how hard I look for it. I hoped the theme URL (https://mermaid-js.github.io/mermaid/#/theming) would provide me some good hints on how to perform it. The diagram I wish to work on is below.

https://bit.ly/3LX8tje

Best regargs

**Comment by Yash-Singh1** [comment]
@brunolnetto, Does this work?:

```
%%{init: {'themeVariables': { 'edgeLabelBackground': 'transparent'}}}%%
```

However, when the edge label background is transparent, the text will intersect with the arrows.

**Comment by brunolnetto** [comment]
It works just before the page stop responding. Do you know the reason for it?

**Comment by Yash-Singh1** [comment]
Could you send the console logs that you get when the page stops responding?

**Comment by brunolnetto** [comment]
I pressed button F12: it opened a right tab, where I can click console tab. After that, I pasted the snippet below somewhere below the class definitions. The page just stop responding and there is no console log message. It is very weird.

``` %%{init: {'themeVariables': { 'edgeLabelBackground': 'transparent'}}}%% ```

**Comment by Yash-Singh1** [comment]
Currently, I don't think we support putting directives underneath diagrams, but only at the top like this:

```
%%{init: {'themeVariables': { 'edgeLabelBackground': 'transparent'}}}%%
graph TD
    A([Start]):::start_node ==> B(Step 1)
    B:::active_node ==> C{Flow}:::active_node
    C:::active_node -- Choice 1.1 --> D[Step 2.1]
    C == Choice 1.2 ==> E[Step 2.2]:::active_node
    D --> F{Flow 2}:::active_node
    E ==> F{Flow 2}
    F{Flow 2} == Choice 2.1 ==> H(Feedback node):::active_node
    H(Feedback node) ==> B(Step 1)
    F{Flow 2} == Choice 2.2 ==> G((Finish)):::finish_node
    
    classDef start_node fill:#00a000,stroke:#333,stroke-width:7px
    classDef active_node fill:#FFAE42,stroke:#333,stroke-width:3px
    classDef finish_node fill:#0EBFE9,stroke:#333,stroke-width:7px
```

**Comment by brunolnetto** [comment]
It explains much! Since you are around, may you answer [how do I add color to arrow heads](https://github.com/mermaid-js/mermaid/issues/3026)?

**Comment by Yash-Singh1** [comment]
Closing this for now as question is answered.

**Comment by brunolnetto** [comment]
Is big is the effort to add this feature?

**Comment by Yash-Singh1** [comment]
For arrow head coloring or directive placement in diagram?

**Comment by brunolnetto** [comment]
Arrowhead coloring.

**Comment by Yash-Singh1** [comment]
It shouldn't be hard, but I can look into it later when I have time.

**Comment by brunolnetto** [comment]
Outstanding. May you make me aware as soon as you are ready?

**Comment by paypuce-xsa** [comment]
when using your code, i have this result, with transparent, i have this kind of "grayish" background.
it works good with "white" but is ugly in dark mode then.
Actually, when pasting the mermaid here, it also has the grayish backgound..

<img width="707" height="275" alt="Image" src="https://github.com/user-attachments/assets/3e6c70e0-3e84-45c4-a399-a32982d4bf6f" />

```` text
%%{ init: {  'themeVariables': { 'edgeLabelBackground': 'transparent'} } }%%

graph LR
A("Perception") --> |convert|B("Representation")
C("Perform Algorithmus / analyze") --> B

linkStyle default background:transparent
````

```` mermaid
%%{ init: {  'themeVariables': { 'edgeLabelBackground': 'transparent'} } }%%

graph LR
A("Perception") --> |convert|B("Representation")
C("Perform Algorithmus / analyze") --> B

linkStyle default background:transparent
````
