### ISSUE TITLE
Class Diagram correct UML notation - extend

### ISSUE THREAD

**Issue by olono1** [mermaid-js/mermaid#3024]
**Is your feature request related to a problem? Please describe.**
The notation used for the extends relation ship is wrong. This might seem as a minor mistake, but the arrow is currently filled, but the correct notation has the arrow unfilled.

**Describe the solution you'd like**
It would be great if this could be corrected, so the correct notation is spread. Or in my case I would like to know, where could I make modifications in svg or css to change the arrow fill?

**Additional context**
Mermaid extends 
<img width="156" alt="Snímka obrazovky 2022-05-11 o 7 37 19" src="https://user-images.githubusercontent.com/11738619/167776370-0559c271-ec47-40d6-aa34-346c99c517ce.png">

UML notation extends
![image](https://user-images.githubusercontent.com/11738619/167776476-9f16fa88-3041-4986-947d-84306ef0c123.png)

**Comment by phiat** [comment]
Also, maybe only related to the mermaid docs, but most UML is reversed for the member var name and type like:
```
className
    +<var name> :  <type>  
```
...
compared to the [mermaid docs](https://mermaid-js.github.io/mermaid/#/classDiagram?id=defining-members-of-a-class) 
```
className
    +<type> : <var name>

```
example in docs:
```
BankAccount
+String owner
+BigDecimal balance
+deposit(amount)
+withdrawal(amount
```

I can open another issue if this is unrelated.  Cheers,

**Comment by jgreywolf** [comment]
> Also, maybe only related to the mermaid docs, but most UML is reversed for the member var name and type like:

Being handled as part of this fix

**Comment by jgreywolf** [comment]
@olono1 (or anyone) what is the markup you are using to denote "extends"?

**Comment by jgreywolf** [comment]
Closing this in favor of #1687
