### ISSUE TITLE
Gantt Chart - possibility to use milliseconds or decimal values for seconds

### ISSUE THREAD

**Issue by snoerenberg** [mermaid-js/mermaid#3028]
Is it possible to use milliseconds in a Gantt chart?
Currently I cannot get it to work, only full seconds are working like expected.

working:
```
gantt
	dateFormat x
	axisFormat %H:%M:%S
    title Timeline
    
FirstItem: 1652187038860, 19s
SecondItem: 1652187052444, 5s
ThirdItem: 1652187052977, 1s
```

![grafik](https://user-images.githubusercontent.com/4847454/167930201-91553bee-5ba7-4b1a-80e6-bb195c64c2ec.png)

not working but would be great:
```
gantt
	dateFormat x
	axisFormat %H:%M:%S
    title Timeline
    
FirstItem: 1652187038860, 19000ms
SecondItem: 1652187052444, 5110ms
ThirdItem: 1652187052977, 500ms   
```

![grafik](https://user-images.githubusercontent.com/4847454/167930302-c5f9008b-0b55-4ede-a654-3055c508579d.png)

decimal values are not possible as well as it seems:
```
gantt
	dateFormat x
	axisFormat %H:%M:%S
    title Timeline
    
FirstItem: 1652187038860, 19.0s
SecondItem: 1652187052444, 5.1s
ThirdItem: 1652187052977, 0.500s 
```

![grafik](https://user-images.githubusercontent.com/4847454/167930578-027c1c1c-78d1-48a7-a14f-342674d18dc1.png)

Any help or idea would be appreciated.

Stephan

**Comment by serkan-ozal** [comment]
Seems that the required contribution is straightforward and needs to be handled at 
- here https://github.com/mermaid-js/mermaid/blob/develop/src/diagrams/gantt/ganttDb.js#L231
- and here https://github.com/mermaid-js/mermaid/blob/develop/src/diagrams/gantt/ganttDb.js#L268

**Comment by serkan-ozal** [comment]
Hi, is there any update on this?

**Comment by snoerenberg** [comment]
Hi, I‘ll check back on the suggested changes after I‘m back from parental leave in 3 weeks.

**Comment by serkan-ozal** [comment]
Hi there, were you able to check suggested changes?
