### ISSUE TITLE
link targets (e.g. _blank, _parent) don't work

### ISSUE THREAD

**Issue by danturn** [mermaid-js/mermaid#3077]
**Describe the bug**
Adding a target suffix to a link doesn't change the behaviour. Links always seem to be opened in the current tab

**To Reproduce**
you can run this on your example page for flowcharts here: https://mermaid-js.github.io/mermaid/#/flowchart

or use this:
https://mermaid.live/edit#pako:eNp9zjtrAzEQBOC_smztR6_CYJN0gUDcLpg9ac8S1uPQrRDG-L_7jBNwlamm-BjmhrY4QYNjLN16rgpfP5RhyX693h1e1cZgL7AHQq86me229745B_Vt2NiSCOE0RM6Xd334RxN-T5JBfZghZGDI0kF5eBuijCtMUhMHt9y7PacJ1UsSQrNUJyO3qISU7wttk2OVTxe0VDQjx1lWyE3L8ZotGq1N_tBH4HPl9KvuD28VViQ

**Expected behavior**
with _blank as a target suffix, the link should open in a new tab

**Desktop (please complete the following information):**
- MacOS (m1)
- Chrome & Firefox & Safari

**Comment by abitrolly** [comment]
Same here. Fedora 36 + Firefox 100.

**Comment by abitrolly** [comment]
Doesn't work in GitHub either.
```
flowchart TD
    A["Application.Run()"] 
    click A "https://google.com" _blank
```
```mermaid
flowchart TD
    A["Application.Run()"] 
    click A "https://google.com" _blank
```

**Comment by sidharthv96** [comment]
@danturn link targets seem to work only if the `securityLevel` config is set to `loose`.

Hit `Cancel` after opening this link.
https://mermaid.live/edit#pako:eNp9jsFqwzAMhl_F6JymbeIkrg-Dlu1WGGy3YRiuozamjh0SZVkX-u7LFja6y3T69evjQyOYUCJIOLowmEq3xPZPyrNptovF3W6OxllzZlumoCJq5HI5DEN8slT1h9iEWgF7PTjtz7f07h9awWODnlFlO2Y908zjwEgfbkTKQwQ1trW25fTe-KVWQBXWqEBOscSj7h0piOZTh6ZvLV32-IZuRlwI3UQrf51cfVNqwofSUmhBHrXrMALdU3i-eAOS2h5_oHurT62uf6lG-5cQ_uwgR3gHmaR5LIokTzhPBC-KIoLL1PKYi026FjzLeJ6LjF8j-Pg2rGKRrdebNONFwoXgq_T6Cd4neRc

**Comment by juanrgon** [comment]
Out of curiosity, why does this require the security level to be set to `loose`. What's dangerous about adding a target to a link?

**Comment by nirname** [comment]
https://github.com/mermaid-js/mermaid/issues/2135

**Comment by nirname** [comment]
Please refer to this one #2135, I am closing it, because they share similar problem

**Comment by tommcdo** [comment]
@nirname I don't think this is related to #4645. That issue is about nodes that incidentally have keywords in their names. This is about actually using targets in links.

**Comment by deseven** [comment]
Still doesn't work, still no mention about it in the docs.
