### ISSUE TITLE
Dashes not supported in sequence diagram participant definitions

### ISSUE THREAD

**Issue by willbicks** [mermaid-js/mermaid#3078]
**Describe the bug**

According to #1228 and #1574, dashes / hyphens (-) should be supported in sequence diagrams. And indeed, if actors are only implicitly defined, they can be used when specifying relationships. 

However, if actors are explicitly defined using `participant` tags (as [described in the docs](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequencenumbers)), the diagram fails to render. If escape characters are used, duplicate actors are created.

As software components often contain dashes in their names, it would be helpful to be able to represent those as accurately as possible.

**To Reproduce**

Attempt to render any of the following diagrams:

```
sequenceDiagram
    participant jelly-bean
    participant chocolate-chip

    jelly-bean->chocolate-chip: applies heat
    chocolate-chip->jelly-bean: reports melting condition
```

```
sequenceDiagram
    participant jelly#45;bean
    participant chocolate#45;chip

    jelly-bean->chocolate-chip: applies heat
    chocolate-chip->jelly-bean: reports melting condition
```

```
sequenceDiagram
    participant jelly#45;bean
    participant chocolate#45;chip

    jelly#45bean->chocolate#45chip: applies heat
    chocolate#45chip->jelly#45bean: reports melting condition
```

**Expected behavior**

That the above samples render as below:

```mermaid
sequenceDiagram
    jelly-bean->>chocolate-chip: applies heat
    chocolate-chip->>jelly-bean: reports melting condition
```

The expected behavior would be that there would be a way to include dashes in actor names, both when declaring participants, and describing messages.

The most convenient way to allow this would be to support directly typing dashes in both `participant` and message descriptions, or allow quotation marks to describe literal names in both, escaping the interpretation of any special characters. 

**Additional context**

#1228
#1574

**Comment by financelurker** [comment]
You can try to use an alias for the participants, using "as":
```
sequenceDiagram
    participant JB as jelly-bean
    participant CC as chocolate-chip

    JB->CC: applies heat
    CC->JB: reports melting condition
```

That would render the expected diagram.

**Comment by ashleybartlett** [comment]
I ran into this one yesterday, and I think I found a fix for it and have put up a PR
