### ISSUE TITLE
Subgraph direction not always respected

### ISSUE THREAD

**Issue by SandroK** [mermaid-js/mermaid#3096]
**Describe the bug**
The direction statement of a subgraph is not respected, when pointing at a node within the subgraph

**To Reproduce**
Compare the following charts, the subgraph direction is different, but shouldn't be

Pointing at the subchart as a whole, subchart direction is top to bottom
```
flowchart LR;
	subgraph c
		direction TB
		c1 --> c2
	end
	b --> c
```
[![](https://mermaid.ink/img/pako:eNo1jjELwjAQhf9KuLkddIzgILo5qeMt1-RiA01S0gsipf_dQOz23scH761gkmXQgOKm9DEjZVH3xwkjCspShnemeVSmdRTrMxvxKarXZWfmoPr-rMyxAY62haFh6CBwDuRtnVkxKoUgIwdG0DVadlQmQcC4VbXMloRv1kvKoB1NC3dARdLzGw1oyYV36eqpvgt_a_sBWhNG9Q)](https://mermaid.live/edit#pako:eNo1jjELwjAQhf9KuLkddIzgILo5qeMt1-RiA01S0gsipf_dQOz23scH761gkmXQgOKm9DEjZVH3xwkjCspShnemeVSmdRTrMxvxKarXZWfmoPr-rMyxAY62haFh6CBwDuRtnVkxKoUgIwdG0DVadlQmQcC4VbXMloRv1kvKoB1NC3dARdLzGw1oyYV36eqpvgt_a_sBWhNG9Q)

Pointing at a node within the subchart, subchart direction is left to right (as the entire chart)
```
flowchart LR;
	subgraph c
		direction TB
		c1 --> c2
	end
	b --> c1
```
[![](https://mermaid.ink/img/pako:eNo1jjELwjAQhf9KuLkd6hjBQXRz0o63XJOrDTRJSS-IlP53A7Hbex8fvLeBiZZBA8o4x4-ZKIl6PM8YUFDWPLwTLZMytaNYl9iIi0H114OZTrXtRZlTBRxsDUPFHTTgOXlytuxsGJRCkIk9I-gSLY-UZ0HAsBc1L5aE79ZJTKBHmldugLLE1zcY0JIyH9LNUbnn_9b-A5FTRyY)](https://mermaid.live/edit#pako:eNo1jjELwjAQhf9KuLkd6hjBQXRz0o63XJOrDTRJSS-IlP53A7Hbex8fvLeBiZZBA8o4x4-ZKIl6PM8YUFDWPLwTLZMytaNYl9iIi0H114OZTrXtRZlTBRxsDUPFHTTgOXlytuxsGJRCkIk9I-gSLY-UZ0HAsBc1L5aE79ZJTKBHmldugLLE1zcY0JIyH9LNUbnn_9b-A5FTRyY)

**Expected behavior**
Subgraph direction should be respected, independent of other nodes and connections

**System info**
I have tried on mermaid.live
I believe my system info sn't relevant

**Comment by Zingam** [comment]
```mermaid
flowchart LR
  start(START) --> user
  user(User UI) --> R_Server(Server) 

  subgraph R Server
    direction TB

    R_Server --> RMCE_Database[(Database)]
  end

  R_Server -->|Request| R_Agent(Agent)

  subgraph RMCE Agent
    direction TB

    R_Agent --> DataCollect(((Data Collection)))
  end

  R_Agent -->|Response| R_Server
```
Not respected: `direction TB` for subgraphs.

**Comment by taranlu-houzz** [comment]
@SandroK I think this is a duplicate of #2509. I just ran into this recently as well.

**Comment by SandroK** [comment]
I'll accept that as a duplicate
