### ISSUE TITLE
Export and import JSON

### ISSUE THREAD

**Issue by fasteddys** [mermaid-js/mermaid#3100]
Hello please consider export and import from JSON

**Comment by rlindsgaard** [comment]
I understand the need for making graphs based on e.g json, but I have difficulty imagining how that would work in practice from a mermaid point of concern/view. Perhaps it  would be a better fit to simply wrap that in code that generates the graph markup (ort translates it into json). Personally, I imagine it is going to be somewhat specialised (although maybe template-able) every time.

One tool, one job I suppose.

Can you give an example of what/how you would expect import/export of json to work?

**Comment by jgreywolf** [comment]
While I think that such a thing would be cool to have, I believe it is out of scope for mermaidJs.
