### ISSUE TITLE
Bug: falling on parsing

### ISSUE THREAD

**Issue by grishy** [mermaid-js/mermaid#3123]
**Describe the bug**
When I enter the code, the application crashes and does not display any errors

**To Reproduce**
1. Go to [online](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNo1T7FOAkEQ_ZXNVJBAoeWZWOEXaOdarOwgl3B75NgtDCExaKCwsDwLCitqGpJLEEz8grd_5CxCNfNm3nvzZkr90jJl9FSZ8VDd9a60034SHo_49wufWKl7rLCNcxziPL4r_OCAXXyNS2yxRxM_FBrs45vsX_CNTVwIbh6SkVLmotu9NpdKJcjOpoK6hVqkm395WxhYt7AWvx2a9jFCOpzmtSDqUMFVYXIrQafaiRn5IResKZPW8sCEkdek3UyoYWyN5xub-7KibGBGE-6QCb68fXZ9ynwV-Ezq5Ub-LE6s2R-mpXtW)

**Screenshots**
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/13949080/173221577-32d1c7a5-035e-41b9-8df0-653da8849b8f.png">

**Code Sample**
[live editor](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNo1T7FOAkEQ_ZXNVJBAoeWZWOEXaOdarOwgl3B75NgtDCExaKCwsDwLCitqGpJLEEz8grd_5CxCNfNm3nvzZkr90jJl9FSZ8VDd9a60034SHo_49wufWKl7rLCNcxziPL4r_OCAXXyNS2yxRxM_FBrs45vsX_CNTVwIbh6SkVLmotu9NpdKJcjOpoK6hVqkm395WxhYt7AWvx2a9jFCOpzmtSDqUMFVYXIrQafaiRn5IResKZPW8sCEkdek3UyoYWyN5xub-7KibGBGE-6QCb68fXZ9ynwV-Ezq5Ub-LE6s2R-mpXtW)

**Additional context**
```
view fail TypeError: A is undefined
    Immutable 27
    invoke event.ts:554
    fire event.ts:721
    _attachModel codeEditorWidget.ts:1472
    onDidChangeContent textModel.ts:201
    invoke event.ts:554
    fire event.ts:721
    endDeferredEmit textModel.ts:2591
    _applyUndoRedoEdits textModel.ts:1355
    _applyUndo textModel.ts:1328
    undo editStack.ts:218
    _resourceUndo undoRedoService.ts:977
    _safeInvokeWithLocks undoRedoService.ts:705
    _resourceUndo undoRedoService.ts:977
    _invokeResourcePrepare undoRedoService.ts:748
    _resourceUndo undoRedoService.ts:975
    _undo undoRedoService.ts:1058
    undo undoRedoService.ts:1025
    undo textModel.ts:1503
    runEditorCommand coreCommands.ts:1850
    _runEditorCommand coreCommands.ts:317
    f coreCommands.ts:288
    runCommand editorExtensions.ts:185
    handler editorExtensions.ts:120
    invokeFunction instantiationService.ts:61
    executeCommand standaloneServices.ts:240
    _doDispatch abstractKeybindingService.ts:253
    _dispatch abstractKeybindingService.ts:144
    Xe standaloneServices.ts:275
util-afcbbd18.js:1231:57283

```

**Comment by knsv** [comment]
In your mermaid code. Use flowchart instead of the legacy graph. Then it works.
