### ISSUE TITLE
Remove Members & Methods Box On Class Diagram, If They Are Not Set

### ISSUE THREAD

**Issue by apeacock1991** [mermaid-js/mermaid#3139]
**Is your feature request related to a problem? Please describe.**

I am using the class diagram for a domain model, as after all, in a domain model, they are ultimately going to be classes in the codebase. However, they do not have members nor methods defined.

**Describe the solution you'd like**

It works pretty well, but it would be much prettier if the members & methods boxes were not rendered on the diagram (nor the dividers) if there are none.

Then there would just be a node with a title. I did try using a flowchart, but for a domain model, you really need the UML-style arrows for composition, aggregation etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by knsv** [comment]
Thanks for the suggestion. We are adding this to the backlog

**Comment by jdauvill** [comment]
We have the same need:  UML-style arrows and display of cardinalities, but would like to avoid displaying empty members & methods boxes.

**Comment by jgreywolf** [comment]
I am actively working on this one now, finally :)

**Comment by jdauvill** [comment]
Thanks, Justin !

From: Justin Greywolf ***@***.***>
Date: Wednesday, 17 May 2023 at 15:44
To: mermaid-js/mermaid ***@***.***>
Cc: Jerome Dauvillier ***@***.***>, Comment ***@***.***>
Subject: Re: [mermaid-js/mermaid] Remove Members & Methods Box On Class Diagram, If They Are Not Set (Issue #3139)

I am actively working on this one now, finally :)

**Comment by pauliev** [comment]
Hey, just want to thumbs up this again... would be nice to have...

**Comment by delepster** [comment]
Any news on this?

**Comment by pindab0ter** [comment]
Would like to know if this is being looked at soon or not.

**Comment by jgreywolf** [comment]
This will be resolved with #5880

**Comment by ParanoidUser** [comment]
Kudos to @knsv, @jgreywolf, and @yari-dewalt for the heavy lifting on the update to the new renderer👏

Since this feature has attracted a lot of interest, here’s how to configure the class diagram to hide those empty member boxes (more in [documentation](https://mermaid.js.org/syntax/classDiagram.html#members-box)). You can play around with it in the [preview build](https://deploy-preview-5880--mermaid-js.netlify.app/edit#pako:eNotjTsOwyAQRK-CtjYXoIycMlVamg0sBoWPxUeKZfnuBsfdG-3bmR1U0gQCOOcyMqZSNG4RA3vwWMrNjFmn6RnWur0ofCiXR_oJVnMjGa_ny54dLhnDVTUym5v6wgSBckCn-9A-bhKqpUASREdNBpuvEmQ8uoqtpvcWFYhRPkFObbEgDPrSU1s1Vrpn_spxAtj-Qj4).

```
---
  config:
    class:
      hideEmptyMembersBox: true
---
classDiagram
  class Duck
```
```mermaid
---
  config:
    class:
      hideEmptyMembersBox: true
---
classDiagram
  note for Duck "This will be rendered without empty boxes 
  once GitHub updates to the latest release ."
  class Duck
```

**Comment by devgony** [comment]
@ParanoidUser How do we adjust hideEmptyMembersBox? Does it need special mermaid engine? Even your example looks like it still has member fields on github previewer
![image](https://github.com/user-attachments/assets/0513366d-3380-4815-ae5a-14192ad0a2f3)

**Comment by jgreywolf** [comment]
FYI - This is only available in v11.4 and up. GitHub has not updated the version they are using

**Comment by robross0606** [comment]
IMO this logic is still semi-faulty.  It only works if the class has _zero_ members.  However, if it has attributes but no operations or operations but no attributes , it still displays the empty box for whatever is missing.
```
---
  config:
    class:
      hideEmptyMembersBox: true
---
classDiagram
  class Duck {
    myProperty
  }

  class Goose {
    squawk()
  }
```

![Image](https://github.com/user-attachments/assets/f63eebb8-0879-474f-8f66-51e3ad93bcda)

**Comment by jgreywolf** [comment]
If you have not already, please create a new issue for this so it is seen
