### ISSUE TITLE
Flowchart breaks with more than one link (click event)

### ISSUE THREAD

**Issue by nataliebivens** [mermaid-js/mermaid#3141]
With this general flowchart graph layout, a gap appears when there is more than one link (click event). I have only seen this bug in the Mermaid demo (https://mermaid100-sandbox.mxapps.io/) and in Mendix applications using the Mermaid widget. The graph does not break in the Mermaid live editor. The graph does not break when I remove the double quotes around the links - this makes the nodes clickable, but then the links do not work. Is there a way to fix this? 

flowchart LR
left.1
middle.1
right.1
subgraph Subgraph_1
left.1
end
subgraph Subgraph_2
middle.1
end
subgraph Subgraph_3
right.1
end
Subgraph_1 --- Subgraph_2 --- Subgraph_3
click left.1 "https://www.google.com"
click middle.1 "https://www.google.com"
click right.1 "https://www.google.com"

What the flowchart looks like in the demo / Mendix app:
![Mermaid Demo](https://user-images.githubusercontent.com/97262181/173710063-1a55f39c-9595-4bd6-855d-967707502450.png)

What the flowchart looks like in the live editor (how it should look):
![Mermaid Live Editor](https://user-images.githubusercontent.com/97262181/173710115-727746b0-aedd-4b52-b4b8-438b935772f0.png)

**Comment by sidharthv96** [comment]
As the graph is working in live editor properly. The issue seems to be with how Mendix implements Mermaid.

Maybe setting `securityLevel: loose` could help. 
Also, check which version of mermaid is being used.

**Comment by jgreywolf** [comment]
Closing due to no response
