### ISSUE TITLE
Gitgraph Diagram: rotateCommitLabel

### ISSUE THREAD

**Issue by teacher-svb** [mermaid-js/mermaid#3142]
**Describe the bug**
The option `rotateCommitLabel: true` does not work. In the documentation it says this is the default behaviour, but right now it defaults to a horizontal commit label.

**To Reproduce**
1. Go to the mermaid live editor
2. enter the gitgraph from the code sample below
3. See error: The commit message is displayed horizontally
4. Go to Config
5. Add the option:  `"gitGraph": {"rotateCommitLabel": true}`
6. See error: The commit message is still displayed horizontally

**Expected behavior**
The commit message is shown at a 45° angle

**Screenshots**
What is shown in the documentation:
![afbeelding](https://user-images.githubusercontent.com/39157063/173834771-0820a6fc-8a9f-4258-8189-e2810c91243f.png)

What acutally happens:
![afbeelding](https://user-images.githubusercontent.com/39157063/173834682-829ed30a-f80d-4546-b7b7-fe5b8b2f7376.png)

**Code Sample**
```
    gitGraph
      commit
      commit
      branch develop
      checkout develop
      commit
      commit
      checkout main
      merge develop
      commit
      commit
```

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser: Firefox, Chrome
 - Version: firefox v101.0.1, chrome v102.0.5005.115

**Comment by ashishjain0512** [comment]
@teacher-svb the latest mermaid version 9.1.2 is yet not updated on the live editor. This will be upgraded soon.

FYI  @sidharthv96

**Comment by sidharthv96** [comment]
v9.1.2 released!
- https://github.com/mermaid-js/mermaid-live-editor/pull/840

@ashishjain0512 we should think of setting up an auto release pipeline apart from dependabot just for mermaid which could take around a week.

**Comment by sidharthv96** [comment]
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/10703445/174000831-47a7695e-e663-4abb-a45e-2ef5ae4c4788.png">

Closing as fix is live.

**Comment by teacher-svb** [comment]
what version is used on Github? I still see the same bug over there

**Comment by sidharthv96** [comment]
GitHub will be using an older version for sure as 9.1.2 was only released 2 days back.
