### ISSUE TITLE
ERD diagram doesn't support fields with prefix FK.

### ISSUE THREAD

**Issue by pocelka** [mermaid-js/mermaid#3146]
**Describe the bug**
ERD diagram doesn't parse foreign key column with prefix fk in the name.

**Expected behavior**
Column with prefix fk_ should be properly parsed.

**Screenshots**

**Code Sample**
```
erDiagram
    table1 ||--o{ table2 : has
    table1 {
        int id PK
        int fk_district_id FK
    }
    table2 {
        int id
    }
```

**Additional context**
Due to some historical precedent we have FK columns prefixed with "fk_". Somebody got a "great" idea about this and set some stupid precedent although in database world you can clearly see if field is FK or not by looking on his definition. Unfortunately can't be easily changed, therefore it would help if mermaid could display correctly such field names.

**Comment by sidharthv96** [comment]
- Duplicate: https://github.com/mermaid-js/mermaid/issues/3019

**Comment by pocelka** [comment]
Didn't see that one. Thanks for linking it.
