### ISSUE TITLE
Add Option `until` / `before` to Gantt Diagram

### ISSUE THREAD

**Issue by RoyiAvital** [mermaid-js/mermaid#3173]
**Is your feature request related to a problem? Please describe.**
I'd like to set the end of a task by another task / milestone.

**Describe the solution you'd like**
Just like one could set the beginning of a task by `after <taskName>` I want to be able to end it by `before <taskName>` or `until <taskName>`.
It should also support milestones.

**Describe alternatives you've considered**
Specify the date explicitly.

**Comment by RoyiAvital** [comment]
@RufusJWB , I am not a developer. I am just a user suggesting a feature I'd love to have and use.

**Comment by RufusJWB** [comment]
> @RufusJWB , I am not a developer. I am just a user suggesting a feature I'd love to have and use.

I assumed you to be the maintainer :-)

**Comment by stko** [comment]
@RufusJWB I just discovered the "until" feature, but... would there be any chance to extend the function in that way that the task is been calculated backwards from the "until" date with a given duration like
: a1, 3d, until milestone1

The reason why I'm asking is that I'm trying to generate a gantt chart which calculate backwards from a given finish date (milestone) with given tasks durations to show the necessary start dates to meet the milestone, and after some tryouts I now realized that the todays syntax doesn't allow that.

So I just wanted to ask, if maybe.. 😃

**Comment by pbrolin47** [comment]
Hi @stko,
Thanks for additional input to Gantt Diagram. May I ask you to raise a new ticket with the proposed feature with backwards calculation, since this ticket is closed. Best regards.
