### ISSUE TITLE
BUG: Click events don't work when rendered using mermaid.render

### ISSUE THREAD

**Issue by theOofDoctor** [mermaid-js/mermaid#3181]
**Describe the bug**
If I render a graph using a div with the class mermaid and then just insert the graph into the div, the click events work fine. But if I render the graph using the mermaid.render function, everything but the click events work fine (Including tooltips) which has left me quite confused.

**To Reproduce**
1. Create a graph
2. Render it using the render function
3. Insert the svgcode into a div
4. Try to click on a node that has a click event.

**Expected behavior**
The click event triggers a callback

**Screenshots**
As you can see, the tooltip displays fine (Bottom left, I know it's ugly rn lol) but clicking doesn't cause anything to happen
![image](https://user-images.githubusercontent.com/58712803/176093386-df7449a5-2500-4d7b-903d-444a357857a1.png)

**Code Sample**
```ts
mermaid.render('graph', graph, (svgCode, bindFunctions) => {
      var element = document.getElementById('graph-svg');
      element.innerHTML = svgCode;
      bindFunctions(element);
    });
```
```html
<div id="graph-svg"></div>
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome

**Comment by theOofDoctor** [comment]
Note: after investigating this further, it appears to only happen when running the debug build. If this is in an environment, or built for production and then served locally it works fine. So this might actually just be a weird quirk with Angular/webpack

**Comment by knsv** [comment]
OK, are you OK with closing this issue?

**Comment by theOofDoctor** [comment]
Yeah for sure
