### ISSUE TITLE
The line between subgraph

### ISSUE THREAD

**Issue by R1ckyH** [mermaid-js/mermaid#3187]
![image](https://user-images.githubusercontent.com/24563814/176325126-38182ca8-c99d-41c3-a85a-1b2b9534eea1.png)
Hello, I am going to ask if this part of the graph goes normal? seems the line have cover the charactor.
Graph here
```mermaid
flowchart LR
  subgraph aa
    a((a))
    a<---->b([b])
  end
  subgraph acccccccccccccccccccc
    a<---->c([c])
    c<-->e(e)
  end
  subgraph bd
    b<-->d(d)<-->f((f))
  end
```
source code here
```
flowchart LR
  subgraph aa
    a((a))
    a<---->b([b])
  end
  subgraph acccccccccccccccccccc
    a<---->c([c])
    c<-->e(e)
  end
  subgraph bd
    b<-->d(d)<-->f((f))
  end
```

**Comment by knsv** [comment]
Hi and thanks for reaching out.

Yes it is normal but it is also somewhat unintuitive. 
We are looking at updating/changing/replacing the layout algorithm.

Will close this one. Let us know if there are reasons to keep the issue open. (We are also trying to get a handle on the issues)
