### ISSUE TITLE
Fontawesome example is broken in docs

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#3190]
**Describe the bug**
No icons are rendered in FA example in docs

**To Reproduce**
1. Go to https://mermaid-js.github.io/mermaid/#/flowchart?id=basic-support-for-fontawesome

**Expected behavior**
FA icon is rendered

**Screenshots**
<img width="389" alt="image" src="https://user-images.githubusercontent.com/10703445/176536943-12ff4257-271a-443c-91a9-8470daf42a5e.png">

**Comment by heyfirst** [comment]
Hey @sidharthv96, I have opened #3271, Would you care to review the PR?
