### ISSUE TITLE
max-width calculated too narrow

### ISSUE THREAD

**Issue by amra** [mermaid-js/mermaid#3207]
**Describe the bug**
`max-width` parameter is wrongly calculated in svg, it's too narrow and causes a partly missing arrow.

**To Reproduce**
Link to Live Editor: https://mermaid.live/edit#pako:eNp9k8FOhDAQhl-l6VlegIMHF6Px4EHXg1k8DO0AdUshbVndbPbdbYsQYIEDCf37_TPtTOdCWc2RxjSX9Q8rQVuyT1KVKkI0SgSDUaZBsfKw0wgWyVunkoegfsVx7LidBGO8h-MJZd30no-Ge0_SqSueQtiyzaI-HdeQ28OTsM9tNmRLvDg3Wi2KAnXUiAalUHjYdwJ5QXUUypB-wxtz8buScZbLw01t7ED7L2uF5M4A_Eyi6H5WmyViWonbegbouzvocPcQxLOLG8GyVK1th1MtSNnveHgmBeyEWuTnMbUeEpSqW8VwrX0LJ_XoNMU4KyuRHUdIWDuAfKLZDjaQr_WkM67f46K75ULjokZvhOKOtRi5mRA5MGtum-j8gZy_xG4Upu5VcK5tvYxU0Ttaoa5AcDe0l_A-qS2xwpTG7pdjDq20KU3V1aFtGMBHLmytaZyDNHhHobX1-1mxQeioREChofpXr38Zq3Kw

Just display it.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/174620/176703484-d95fd183-5bd4-4947-ab3d-2957279b263a.png)

**Desktop (please complete the following information):**

- OS: win 10
- Browser firefox 101.0.1, chrome 103.0.5060.53

**Comment by knsv** [comment]
We should fix this

**Comment by knsv** [comment]
This one was resolved with #2824 and the fix will be released in version v9.1.7.
