### ISSUE TITLE
How to dynamically update graph？

### ISSUE THREAD

**Issue by hanxiaohuivc** [mermaid-js/mermaid#3209]
Hello everyone. I want to implement some functions based on mermaid, such as adding new nodes. These functions are implemented directly in the flowRenderer-v2.js file. The approximate code is as follows:
     let vertex = newaddnode;
      g.setNode(vertex.id,
     {
     labelStyle: styles.labelStyle,
     shape: "rect",
     labelText: vertexText,
     rx: radious,
     ry: radious,
     ......
   });
    const element = root.select('#' + svgId + 'g');
   render(element, g, ['point', 'circle', 'cross'], 'flowchart', svgId);

However, when executing the function, an error will be reported: Uncaught Error: Setting two as parent of two would create a cycle

Excuse me, what is the correct way to update the graph? thanks.

**Comment by sidharthv96** [comment]
Can you give some specific code samples?

If you want to re render a graph after changing the source diagram code, you can use the [`mermaid.render` function](https://mermaid.js.org/config/usage.html#api-usage).

**Comment by jgreywolf** [comment]
Closing due to no response
