### ISSUE TITLE
[Bug] Crash when using `*end` as label name

### ISSUE THREAD

**Issue by OxNinja** [mermaid-js/mermaid#3211]
**Describe the bug**
When I use the word `end` in a label, I get a syntax error, see screenshots.

**To Reproduce**
See the code sample below.

**Expected behavior**
The code does not crash and displays the label with the `end` word in it, see screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/57400445/177744387-3710a6e1-047b-4be4-81ec-f4f8ce7be28b.png)

My workaround:
![image](https://user-images.githubusercontent.com/57400445/177745056-7c540770-ca55-41c6-b991-617d44aa16b1.png)

The expected behavior:
![image](https://user-images.githubusercontent.com/57400445/177744925-a503b46a-f780-4de0-8d19-06df742307f1.png)

**Code Sample**
Link to the [live editor](https://mermaid.live/edit#pako:eNptkcFqwzAQRH9F7DEkxm4bCD7Ul_bWU3M1hI20rkUiyUgyTRvy713HCrahcxrmza6QdAXpFEEJzdl9yxZ9FB-ftRUi9Mcvj10r9hHlaUiEUNqTjNrZ1Jm1VmGq_V8dlF_yXGw2r2y226YpWAu4m8En1hwW88ln1gLOJ19YE8yyLDF2U2zwcgj6l-6sqqqRkFWjWY0XOnRO20g-bSh2iY7wiIESyfMF4T138DhlgJzBGgx5g1rxi1-HsIbYkqEaSrYK_amG2t6413cKI70rHZ2HssFzoDVgH93-x0ooo-_pUXrTyJ9gUuv2B44IhlA).

Or code:

```
flowchart LR
  subgraph Stack
    direction LR
    subgraph *stack
        direction LR
        0x00 --> 0x55ff1111
        0x08 --> 0x55ff2222
        0x10 --> 0x55ff3333
        0x18 --> 0x55ff4444
        ... --> 0x...
        max_size --> ???
    end
    **stack_pointer --> 0x18
    *stack_base --> 0x00
    *stack_end --> max_size
  end
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 102.0

**Comment by knsv** [comment]
This can be solved with:
```
flowchart LR
  subgraph Stack
    direction LR
    subgraph *stack
        direction LR
        0x00 --> 0x55ff1111
        0x08 --> 0x55ff2222
        0x10 --> 0x55ff3333
        0x18 --> 0x55ff4444
        ... --> 0x...
        max_size --> ???
    end
    **stack_pointer --> 0x18
    *stack_base --> 0x00
    se[*stack_end] --> max_size
  end
```

If you want to use any char you can also put the label within quotes:
```
se["*stack_end[]"] --> max_size
```
