### ISSUE TITLE
Unicode character set not supported?

### ISSUE THREAD

**Issue by huyz** [mermaid-js/mermaid#3213]
**Describe the bug**
Some Unicode characters don't seem to be supported, in particular emojis.

**To Reproduce**
Link to Live Editor: https://mermaid.live/edit#pako:eNpVkE1Ow0AMha9ieQVSc4EskGhSuqkEEt1lurASpzOi86OJI1QlOQRnYMeKPUsQ9-AmTFqQwCvL73vPsgesfcOY4z5S0LAtlYNU11Who-nEUreDLLsa1yxgvePjCMuLtYdO-xCM21-e-eUMQTG8v8DH0-fr19tzDbCZPQyijXuYzlxxCrt1PEJZbSiID7u_yvbRj7CqzJ1Ou_4rOnJy3VQt5S1lNUUoKJ4QXKDlaMk06Y5hnigUzZYV5qltuKX-IAqVmxLah4aEV40RHzFFHTpeIPXi74-uxlxiz79QaSi9xf5Q0zcyL2QX

1. Go to https://mermaid.live/edit
2. Click on text editor where it says "Let me think"
3. Add emojis like: 🛫 ✅
4. Notice that the rendering has stopped updating and the emojis don't show up

**Expected behavior**
I would expect emojis to be rendered.

**Screenshots**
![screenshot 2022-06-13T083313Z](https://user-images.githubusercontent.com/128394/173313572-87bdbf4b-d4da-4735-85b6-2e2ad982b294.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Brave
- Version: 1.39.111
The same issue affects words containing arabic diacritics such as: عَرَبِي

**Comment by sidharthv96** [comment]
<img width="887" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/43e8c270-6555-4876-8730-b62e9eb70de4">

<img width="994" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/cf292f72-6e54-48c0-b3f5-0feb4df494c8">

Both examples are working now. 
Please use double quotes `"Label 🛫 ✅"` to support unicode and emojis.
