### ISSUE TITLE
Documentation missing versions of supported Font Awesome icons

### ISSUE THREAD

**Issue by jpl-jengelke** [mermaid-js/mermaid#3214]
**Describe the bug**
There's no list of which Font Awesome icons are supported. So Mermaid does not appear to display certain icons in [current documentation](https://fontawesome.com/v6/icons) (as of today's date, 18,000+ icons). 

Mermaid actually supports an [older version of FA with roughly 675 icons](https://fontawesome.com/v4/icons/). To complicate the issue, FA appears to have deprecated its font codes in favor of a simpler syntax, e.g. getting rid of `fa-` prefixes. To further complicate the issue, Mermaid may be supporting an earlier release of version 4 since even some of those don't display.

The version of FA (version 4?) supported by Mermaid should be documented to reduce confusion and allow users to have a baseline on what they can use in their charts. 

**Expected behavior**
Documentation where the version of Font Awesome supported should be listed is currently at https://mermaid-js.github.io/mermaid/#/flowchart?id=basic-support-for-fontawesome .

**Additional context**
There appears to be a lot of confusion about FA support. This documentation update may help clear up any questions and potentially reduce the number of tickets coming in about FA.

**Comment by knsv** [comment]
I agree that this should be clarified. Perhaps as a part of a bigger icon overhaul. The tricky bit is backwards compatability. We cant break old working diagrams ...

**Comment by walterrowe** [comment]
Can we get some traction on this?

**Comment by walterrowe** [comment]
the mermaid docs reference v5 icons. i'm using gitlab 15.8 and it only supports v4 icons. is that a gitlab or mermaid issue?

**Comment by jgreywolf** [comment]
Closing as documentation does state what icons are supported (http://mermaid.js.org/syntax/flowchart.html#basic-support-for-fontawesome)

**Comment by jpl-jengelke** [comment]
Actually, what was meant is the issue was fixed sometime after [the ticket was created](https://github.com/mermaid-js/mermaid/blob/ef5c753e325a478a161f27e629fdd13d01cad47b/docs/flowchart.md) but the ticket wasn't closed. 

BTW, there's a spelling error in `verion` which should be `version`.
