### ISSUE TITLE
`<ul>` works in Mermaid Live editor but fails in production

### ISSUE THREAD

**Issue by wehub** [mermaid-js/mermaid#3215]
This is my mermaid code:
```
flowchart
  subgraph "Setup"
    id1("A merchant currently has the following as their balances <ul><li>One</li><li>Two</li><li>Three</li><li>Four</li></ul><br>A payment is then made for $50.00<br>(denominated as 5000)<br> and goes through the following flow:")
  end
```

The Live Editor produces the desired output:
![image](https://user-images.githubusercontent.com/22106535/178076260-0f6a6e62-a2ec-47e5-8fb8-93958e900c9c.png)

But in production the output is not correct:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/22106535/178078733-ac2f20bc-907c-4653-b6f2-45ad0878c70b.png">

**Comment by knsv** [comment]
Try using hrmlLabels. That could be it.

**Comment by jgreywolf** [comment]
Closing due to no response
