### ISSUE TITLE
Mermaid support on C4

### ISSUE THREAD

**Issue by SrinivasaMeenavalli** [mermaid-js/mermaid#3217]
C4Context changes are working as expected in Live editor but not in Github . Please confirm version compatability.

Source : https://github.com/mermaid-js/mermaid 

<img width="678" alt="image" src="https://user-images.githubusercontent.com/70197032/178202640-b38f9183-de52-4aaa-bf9d-e3dd00665161.png">

**Comment by jwyza-pi** [comment]
Guessing that the issue is GH hasn't pulled in the latest version.  Is there a mechanism or standard timeframe in which they usually do so?

**Comment by knsv** [comment]
Not sure how often they will update. No mechanism in place. This is out of control of the mermaid project.

**Comment by jwyza-pi** [comment]
I Had kind of assumed that there was some "inside" line of communication between the maintainers of MJS and GH.  One of those thing where when one of the worlds largest websites adopts your stuff you have more communication with them :D.  Might have been a naïve assumption though.

**Comment by marchmallow** [comment]
Maybe @el-mapache who wrote the blog page announcing the availability of this on github would know?

Ref. https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by nie7321** [comment]
It looks like they've updated. The example C4 diagram from the docs is [rendering on gist](https://gist.github.com/nie7321/90b3a1039b9b8c06b9e43fd5e40af898).
