### ISSUE TITLE
if there is graph in the name of the node it fails

### ISSUE THREAD

**Issue by ishay320** [mermaid-js/mermaid#3223]
**Describe the bug**
if there is graph in the name of the node it fails.
for example:
```
graph TD
         bitmaps.cpp --> |local| mask_stats_throttle_graph.lbm
```
fails because of the `_graph` part

**To Reproduce**
make graph with `_graph` in one of the nodes

**Expected behavior**
to make node with the name graph

**Desktop (please complete the following information):**
 - OS: cli version and web version
 - Browser chrome
 - Version 103.0.5060.114

**Additional context**
it can be anywhere:
```
graph TD
         graph -->  graph
```

**Comment by knsv** [comment]
Use quotes to fix this:
```
graph TD
         bitmaps.cpp --> |local| theId[mask_stats_throttle_graph.lbm]
```

```mermaid
graph TD
         bitmaps.cpp --> |local| theId[mask_stats_throttle_graph.lbm]
```
