### ISSUE TITLE
Commits in gitgraph are rendered incorrectly with more than 8 branches

### ISSUE THREAD

**Issue by baflo** [mermaid-js/mermaid#3224]
**Describe the bug**
As soon as there are more than 8 branches, the 9th and above are rendered incorrectly. The commits stop to be connected, merges are not displayed and everything is black.

**To Reproduce**
```
  gitGraph
    checkout main
    commit
    branch develop order: 1
    commit
    branch branch1
    commit
    branch branch2
    commit
    branch branch3
    commit
    branch branch4
    commit
    branch branch5
    commit
    branch branch6
    commit
    branch branch7
    commit
    branch branch8
    commit
    merge develop
```
![image](https://user-images.githubusercontent.com/834350/178964218-36e430b7-6b5a-4f46-8887-d5222b6d81b0.png)

**Expected behavior**
If you remove two branches, everything is correctly rendered. This is how it should work with any number of branches:

```
  gitGraph
    checkout main
    commit
    branch develop order: 1
    commit
    branch branch1
    commit
    branch branch2
    commit
    branch branch3
    commit
    %% branch branch4
    %% commit
    %% branch branch5
    %% commit
    branch branch6
    commit
    branch branch7
    commit
    branch branch8
    commit
    merge develop
```
![image](https://user-images.githubusercontent.com/834350/178964476-1b6a810d-77c6-42cb-aebd-90c4ddc5ee3a.png)

**Link**
 https://mermaid.live/edit#pako:eNqFkMsKwjAQRX8lDLjrxrdkrfgBbrMZk7ENNkmJE0HEfzfSKpSqnc08zlkM9w46GAIJQpSW9xGbSnmRS1ekzyGxcGh9dwrOWW7nY0SvK2HoSnVoRIiGohTTn2LbxvhshM-HfDLpK4vP-Z-1_Gr1lNXIL-sRvhlyR7Gkd2ZQQN5zuianf38JCrgiRwpkHg2dMNWsQPlHVlNjkGlnLIcI8oT1hQrAxOFw8xokx0RvaWuxjOg66_EE-1ecEQ

**Comment by knsv** [comment]
A clear bug! We will fix it!

**Comment by ashishjain0512** [comment]
This should be fixed in the latest release. Verified at my end. Closing this now. If issue is still reproducible, reopen as fresh issue
