### ISSUE TITLE
GitGraph: commit options for merge commits

### ISSUE THREAD

**Issue by WeeBull** [mermaid-js/mermaid#3238]
This is really a reopening of #2934 as the original request was for `merge` to support all fields that `commit` does, but the change only added support for tags.

**Is your feature request related to a problem? Please describe.**
Merge commits should be treated like ordinary commits, in that they should be customize-able with the same syntax. e.g.

    commit tag: "vx.x.1" type: HIGHLIGHT id: "1"
    merge develop tag: "vx.x.1" type: HIGHLIGHT id: "2"

**Describe the solution you'd like**
The syntax tree for merge should probably just be exactly the same as the commit tree after the branch name.

**Additional context**
Right now it is impossible to refer to a merge commit. The case I'm struggling with is cherry-picking a merge. Adding an extra commit afterwards isn't the same thing.

**Comment by marijadjukic** [comment]
I was just writting a documentation with Git diagram and naturally added id option to a merge commit to be able to cherry-pick it and was disappointed when I realized it is not supported. Cherry-picking of merged requests is verry common in development so not being able to visualize it is a big gap. It would be really nice if this can be supported.

**Comment by amyq** [comment]
I can confirm the lack of the `id:` parameter on merge commits is a problem. The only option I've found so far is a hacky misuse of the `tag:` parameter to add words to a merge commit.

(In my case, I need to note that something is a squash merge commit.)
