### ISSUE TITLE
debugging log location?

### ISSUE THREAD

**Issue by vigilancetech-com** [mermaid-js/mermaid#3245]
I've been digging thru the documentation and doing searches on my system but I've not been able to figure out where mermaid's debugging log would go.

I'm using spacemacs with code blocks and I have the following at the beginning of them:

`%%{init: {"theme": "default", "logLevel": 1 }}%%`

Also, what is the name of a config file I can put something like that into so I don't have to keep including it in each block?

And when I saw some interesting stuff that looks like javascript (I can't recall where right now) and I have no idea where that would go

**Comment by knsv** [comment]
If you dont want to changer it in every diagram you need to configure it using the initialise call which starts mermaid. The logs never end up in any file but is always to the javascript console.
