### ISSUE TITLE
[ER Diagram] Use readable syntax instead of pictogram

### ISSUE THREAD

**Issue by 838239178** [mermaid-js/mermaid#3247]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when writing er diagram using '||--o{'

**Describe the solution you'd like**
Using 'one to one'/'one to many(1)'/'many(0) to many(0)' instead of `'||--||'`/`'||-|{'`/`'}o--o{'` or something better.

**Describe alternatives you've considered**
I just want a readable syntax

**Additional context**
I love all diagram except er. Thanks all contributors.

**Comment by knsv** [comment]
We cant change the existing syntax but it could be possible to add this as an alternate syntax.

**Comment by DKurilo** [comment]
I created (PR)[https://github.com/mermaid-js/mermaid/pull/3649] and added aliases, so:
```
erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER }|..|{ DELIVERY-ADDRESS : uses
    ADDRESS many to many CUSTOMER : have
    ZIP one or zero to many ADDRESS : have
    T1 one or zero to one or more T2 : test
    T2 one or many optionally to zero or one T3 : test
    T3 zero or more to zero or many T4 : test
    T4 many(0) to many(1) T5 : test
    T5 many optionally to one T6 : test
    T6 only one optionally to only one T1 : test
```
generates:
![mermaid-er-diagram](https://user-images.githubusercontent.com/5169106/195214903-9bcccd0c-1924-48fa-b09c-6a78fa20e65e.svg)

Is it okay or do you want me to change something?

**Comment by 838239178** [comment]
Using 0+ or 1+ instead of zero or more maybe more concise. Whatever, thank you for your contribution.

**Comment by DKurilo** [comment]
> Using 0+ or 1+ instead of zero or more maybe more concise. Whatever, thank you for your contribution.

okay, I added these aliases too.
```
    T4 0+ to 1+ T6 : test
    T1 1 to 1 T3 : test
```

**Comment by 838239178** [comment]
lgtm
