### ISSUE TITLE
Ignore duplicates between subgraphs

### ISSUE THREAD

**Issue by jakesiewer** [mermaid-js/mermaid#3248]
flowchart TB
A[Object] --> B[Watch]
  subgraph Watch [1]
    Glass
    Hands
    Strap
    Battery
  end
  B --> Watch
A --> C[Phone]
  subgraph Phone [2]
    Glass
    Microphone
    Speaker
    Battery
  end
C --> Phone
![mermaid-diagram-2022-07-21-163328](https://user-images.githubusercontent.com/73181878/180253996-90fd7dab-3622-4dd4-b58d-13ecc3ddbc87.svg)

As you can see in the diagram, items that are included in subgraph 1 aren't included in subgraph 2. Is there any way to ignore duplicates between subgraphs?

**Comment by knsv** [comment]
A node can only exist in one place. If you need to create a second one with a different id but with the same title:
```mermaid
flowchart TB
A[Object] --> B[Watch]
subgraph Watch [1]
Glass
Hands
Strap
Battery
end
B --> Watch
A --> C[Phone]
subgraph Phone [2]
Glass
Microphone
Speaker
battery2[Battery]
end
C --> Phone
```
