### ISSUE TITLE
Bug: `linkStyle` can't specify IDs that don't exist at the point in the diagram

### ISSUE THREAD

**Issue by Yash-Singh1** [mermaid-js/mermaid#3251]
**Describe the bug**

If I try to specify a linkstyle with a id that exists after the current `linkStyle`, Mermaid.js throws an error.

**To Reproduce**
1. Go to https://mermaid.live/edit#pako:eNo1js0KwjAQhF8l7Lk9eI1QUPQJ6jGXpbu1wfyUdHMIpe_uijqnge9jmB2mTAwWngXXxTyuLhlN8Ok1SgtsTob8tgZsNuXE5y--mL4fjLrQQeQS0ZNO7B_oQBaO7MBqJZ6xBnHg0qFqXQmF7-QlF7Azho07wCp5bGkCK6XyX7p51EfxZx1vfqY3UQ
2. Notice error

**Expected behavior**

`linkStyles` are applied after.

**Screenshots**

**Code Sample**
If applicable, add the code sample or a link to the [live editor](https://mermaid.live).

https://mermaid.live/edit#pako:eNo1js0KwjAQhF8l7Lk9eI1QUPQJ6jGXpbu1wfyUdHMIpe_uijqnge9jmB2mTAwWngXXxTyuLhlN8Ok1SgtsTob8tgZsNuXE5y--mL4fjLrQQeQS0ZNO7B_oQBaO7MBqJZ6xBnHg0qFqXQmF7-QlF7Azho07wCp5bGkCK6XyX7p51EfxZx1vfqY3UQ

Versions: mermaid.live v9.1.3

**Additional context**

N/a

**Comment by RounakJoshi09** [comment]
Hi @Yash-Singh1 ,

I hope all is well. While investigating a particular bug, I noticed an issue with how `linkStyle` functions when applied to non-existent links. after reading the documentation , I found out that linkStyles applies on links in 0-indexed fashion. So, in this code 
`linkStyle 1 display:none; 
    A --> B`
we are applying linkStyle to the second link (according to 0-indexed) which doesnot even exists.  This results in an unclear error message: **TypeError: Cannot set properties of undefined (setting 'style')**. 

The error message doesn't effectively communicate the underlying issue to the user.
Could you please assign this issue to me? Additionally, would it be possible to generate a more descriptive error message for such cases to enhance user experience?

Thank you for your time and consideration. I'm looking forward to your response.

Best regards,
Rounak

**Comment by Yash-Singh1** [comment]
> Could you please assign this issue to me?

Done


> Additionally, would it be possible to generate a more descriptive error message for such cases to enhance user experience?

Yes, that would be possible by throwing a parse error. Here is an example

https://github.com/mermaid-js/mermaid/blob/12a47076cf47aa3876285016d1182d48443afc93/packages/mermaid/src/diagrams/git/gitGraphAst.js#L158-L166
