### ISSUE TITLE
White space at the end of subgraph names are not filtered out

### ISSUE THREAD

**Issue by coffeegist** [mermaid-js/mermaid#3252]
**Describe the bug**
Comparing the output from mermaid.live to the example found at https://mermaid-js.github.io/mermaid/#/flowchart?id=direction-in-subgraphs, it seems as if the connections between subgraphs are broken. 

**To Reproduce**

Use the code below to generate the following graph 

```mermaid
flowchart LR  
  subgraph TOP  
    direction TB  
    subgraph B1  
        direction RL  
        i1 -->f1  
    end  
    subgraph B2  
        direction BT  
        i2 -->f2  
    end  
  end  
  A --> TOP --> B  
  B1 --> B2
```

**Expected behavior**
The output from above matches the image from the example

**Code Sample**

```
flowchart LR  
  subgraph TOP  
    direction TB  
    subgraph B1  
        direction RL  
        i1 -->f1  
    end  
    subgraph B2  
        direction BT  
        i2 -->f2  
    end  
  end  
  A --> TOP --> B  
  B1 --> B2
```

**Comment by knsv** [comment]
That looks wrong. We will add fixing this to the plan.

**Comment by knsv** [comment]
This is reproducible in the live editor but not when using a simple html file. This is strange.

**Comment by sidharthv96** [comment]
```mermaid
flowchart LR
  subgraph TOP
    direction TB
    subgraph B1
        direction RL
        i1 -->f1
    end
    subgraph B2
        direction BT
        i2 -->f2
    end
  end
  A --> TOP --> B
  B1 --> B2
```

Copied directly from docs. It renders correctly. 
Seems to be caused by whitespace issues. 

```
flowchart LR
  subgraph TOP
    direction TB
    subgraph B1
        direction RL
        i1 -->f1
    end
    subgraph B2
        direction BT
        i2 -->f2
    end
  end
  A --> TOP --> B
  B1 --> B2
```

**Comment by knsv** [comment]
Something must have gone wrong when copying this from the docs. The culprit is whitespaces after the subgraph names. This breaks the rendering as flowcharts currently will ot allow this.

I will rephrase the bug and fix the root cause

**Comment by tomperr** [comment]
Should we close this issue?

**Comment by coffeegist** [comment]
Sorry for the delay, thanks for taking a look! Closing the issue as of 9.2.0
