### ISSUE TITLE
Graphs – how do you configure the ordering of nodes?

### ISSUE THREAD

**Issue by shadowlift** [mermaid-js/mermaid#3253]
Here is my code:
```
graph BT

a(Derivations) -------> b(Mathematics)
a ----> g(Economics)
a -------> c(Physics)
a ----> i(Technology)
a -------> d(Biology)
a ----> f(Human body)
a -------> e(Chemistry)
a ----> h(Anthropology)
```

Here is the result:
[
![cappa](https://user-images.githubusercontent.com/19328386/180616905-62f460f2-9956-4e6e-a9d9-4402dcd2f9ec.PNG)
](url)

I would like my nodes to be listed in the order I put them in, i.e.:
Mathematics first (with a long arrow), Economics second (with a shorter arrow), Physics third (with again the long arrow), (...) etc.

Hopefully there is a simple way to do this – sorry if this is basic, I am quite new to mermaid!

**Comment by knsv** [comment]
The reason for the grouping has to do with the length of the arrows and this is how the layout algoritms deals with it. Perhaps you could group them via subgraphs like this:
```
flowchart BT
    a(Derivations) 
    a ----> b(Mathematics) 
    a ----> c(Physics)
    a ----> d(Biology)
    a ----> e(Chemistry)
    a ----> g(Economics)
    a ----> i(Technology)
    a ----> h(Anthropology)
    a ----> f(Human body)

    subgraph " "
    g 
    h 
    i 
    f
    end
    subgraph " "
    b
    c
    d
    e
    end
```

```mermaid
flowchart BT
    a(Derivations) 
    a ----> b(Mathematics) 
    a ----> c(Physics)
    a ----> d(Biology)
    a ----> e(Chemistry)
    a ----> g(Economics)
    a ----> i(Technology)
    a ----> h(Anthropology)
    a ----> f(Human body)

    subgraph " "
    g 
    h 
    i 
    f
    end
    subgraph " "
    b
    c
    d
    e
    end
```

There are other work ongoing with the layout algorithm that could affect this but that is in another issue. I am closing this one. Re-open or create another issue if you still are having issues.
