### ISSUE TITLE
Border attribute does not work in a certain writing style

### ISSUE THREAD

**Issue by yaeda** [mermaid-js/mermaid#3263]
**Describe the bug**
Border attribute does not work in a certain writing style.

**To Reproduce**

Here are the samples. Please see `borders:tb`.

**OK pattern**

```
flowchart LR
  datastore[|borders:tb|Datastore] -->|input| process((System)) -->|output| entity[Customer]
```

shows

```mermaid
flowchart LR
  datastore[|borders:tb|Datastore] -->|input| process((System)) -->|output| entity[Customer]
```

**NG pattern**

```
flowchart LR
  datastore[|borders:tb|Datastore]
  process((System))
  entity[Customer]

  datastore -->|input| process -->|output| entity
```

shows 

```mermaid
flowchart LR
  datastore[|borders:tb|Datastore]
  process((System))
  entity[Customer]

  datastore -->|input| process -->|output| entity
```

**Expected behavior**
The same rendering results are obtained with the above two styles.

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Chrome
 - Version  103.0.5060.134

**Comment by StevenIsaacs** [comment]
Another example:

flowchart LR
  p((process))
  ds[|borders:tb|ds] --> p
  ds2[|borders:tb|ds2] --> p
  p --> ds2

Renders as:
```mermaid
flowchart LR
  p((process))
  ds[|borders:tb|ds] --> p
  ds2[|borders:tb|ds2] --> p
  p --> ds2
```
Borders has no effect when ds2 is referenced.

**Comment by maiermic** [comment]
I'm looking into this right now. In the example,

> ```
> flowchart LR
>   datastore[|borders:tb|Datastore]
>   process((System))
>   entity[Customer]
> 
>   datastore -->|input| process -->|output| entity
> ```

`node.props.borders` is not defined in [src/dagre-wrapper/nodes.js](https://github.com/mermaid-js/mermaid/pull/2389/files#diff-92908043cabd4ab72980ff47f8c8edcf7d50fefc4d8126f49fbf3a64572de1e7R330). I still have to figure out why.

**Comment by litlighilit** [comment]
This bug seems to occur again...  

In fact border attribute seems to not work in any writing style
