### ISSUE TITLE
Moderate Security Alert!

### ISSUE THREAD

**Issue by botteroxom** [mermaid-js/mermaid#3265]
I can`t send email but I`m receiving an security alert

Possible inject arbitrary `CSS` into the generated graph affecting the container HTML (Moderate)
#27 opened 22 days ago • Detected in mermaid (npm) • package-lock.json

**Comment by knsv** [comment]
It would be great if you could send more information to security@mermaid.live or are you saying that this address does not work?

**Comment by sidharthv96** [comment]
This seems to be in response to [this advisory](https://github.com/mermaid-js/mermaid/security/advisories/GHSA-x3vm-38hw-55wf), and not a new vulnerability.
