### ISSUE TITLE
open source business vision

### ISSUE THREAD

**Issue by ghost** [mermaid-js/mermaid#3273]
Hi all!

#### 1. feature-name
open source business vision

#### 2. feature-description
I would like to contribute to the community through 13 ideas on how to make the mermaid open source project more profitable, when I say profitable, I mean economically viable. Most open source projects work on the subscription model, donation model (monthly/yearly) or premium service model (open core: part open source, part closed source - which is different from the freepremium model, there are people that confuse the freepremium model with the opencore model. I'll say briefly, the freepremium model doesn't exist part of open source and part of closed source. What exists is a proprietary code software with a free part and a paid part, when I say it is free - I don't mean freedom, I mean financially, it's free because you don't pay.  The idea is to give the user a taste of how the software is, so if the user is interested, he (user) pays for the software he wants to use. opencore business model, part of the code is open, that is, the user does not pay for the software and can still see its source code. If he wants to support the project, he can pay a monthly/annual subscription service. This is the main difference between opencore and freepremium.)

#### 2.1. Open source business vision
1. Direct sale of diagram templates in mermaid: *The idea is that it would be a single sale per person, in which case it would be a service to be done and paid for. The person can make the diagram template available to someone else for free or not.*
3. Consultancy on creating diagram templates in mermaid: *Anyone who is a developer or someone who has knowledge of the mermaid language can create unique diagram models for individuals and companies. These people can make these unique diagram templates available to other people or companies if they express an interest in doing so for free or not.*
4. Indirect sale of diagram models in mermaid: *the idea would be something monthly from developers to users for free or not*
5. Storage of diagram templates in mermaid: *Companies interested in the mermaid community may have the mermaid diagram template storage service - companies may charge a monthly or annual fee to provide access to or storage of mermaid diagram templates for free or not.*
6. Monthly or annual donation from people to the mermaid community: *This allows for an interest in individuals or corporations to support the mermaid project. Which can be good to hire more developers and provide more premium services in order to make mermaid openly available.* - ***This is an example of what I call a collective investment fund or crowdfunding.***
7. Extensibility is a key point, as an open source project we can provide other plugins and integrations with mermaid. - *"Get Paid To Build Open Source Extensions for Existing Products"*
8. Sponsorship: *Is different from donation, generally those who are part of the sponsorship can be companies or individuals. But most of the cases are usually companies. There can be sponsorship with monthly/annual donation or without donation - there are cases where the donation would be servers, maintenance and equipment.*
9. Paid Feature Requests
10. Software as a Service
11. Paid Support or Courses: *Red Hat’s model of open source software financed by paid support contracts and on-premise configuration takes more human hours, but it allows them to improve the user experience dramatically. When companies look at the cost to troubleshoot open source software, it’s usually a better deal to sign up with the people who made the software rather than learn it themselves.*
12. Paid certification: *If software is popular enough, companies can offer certification opportunities for specialists who want to validate their knowledge and skills. Getting certified, as a developer, is quite useful for a number of reasons. First, it’s a great opportunity to differentiate yourself among other specialists with the same skills. Second, developers realize the importance of networking with mentors and groupmates. Finally, a developer’s certification leads lends them additional professional credibility and even promotions, and can boost a company’s image.*
13. Advertising tech events or mermaid talks: There are things like ruby-conf, python-conf which are paid community talks for people or companies. This is usually done with sponsorship or with a monthly/annual donation from the community itself.
14. Own hosting, self-hosting: The company or person can use mermaid in their own hosting or in the hosting of the mermaid community.

#### 2.2 Why? *notes*
1. In indirect or direct selling, the community can earn money through sales commission, which is a fee you receive for the sale. This cash receipt rate per sale can be somewhere around 15% or 10% - usually the sales rate around 15% or 10% is done on things like Workana, Freelancer.com etc. It's a sales rate that I put here as a reference.
2. It might be of interest to the mermaid community if there is collective interest in providing a consulting platform for creating mermaid diagram models - this allows business analysts like me to make their services available to the community and thus sell their service - with this, I earn money for the work service I do, which would be the consultancy for creating mermaid diagram models, as well as the exclusive sale of diagram models, either indirectly or directly. The main advantage of this type of business here would be the return of the fee charged for the service provided by consultants to individuals/legal entities.
3. It's a way to make money like Wordpress.

#### 2.3 references
- https://cult.honeypot.io/reads/6-ways-you-make-money-as-an-open-source-business/
- https://www.karllhughes.com/posts/open-source-companies
- https://rubygarage.org/blog/how-make-money-with-open-source-projects
- https://www.timescale.com/blog/how-open-source-software-makes-money-time-series-database-f3e4be409467/
- https://thenextweb.com/news/6-ways-open-source-devs-can-make-money-syndication
- https://vitto.cc/how-to-make-money-with-open-source-as-a-developer/
- https://medium.com/@next_shore/simple-ways-to-make-money-with-open-source-projects-97597dd85ceb

**Comment by knsv** [comment]
Thanks! This is very welcome.

I will look at this closely!
