### ISSUE TITLE
incorrect code of double cycle in the document 

### ISSUE THREAD

**Issue by Issam-seghir** [mermaid-js/mermaid#3301]
**Describe the bug**
I just wanted to point out that there is an error in the [document website ](https://mermaid-js.github.io/mermaid/#/flowchart?id=node-shapes:~:text=flowchart%C2%A0TD%0A%C2%A0%C2%A0%C2%A0%C2%A0id1(((This%C2%A0is%C2%A0the%C2%A0text%C2%A0in%C2%A0the%C2%A0circle))))

**The Double circle** code should be content only **two parentheses** and not three 

![image](https://user-images.githubusercontent.com/74573675/183391241-fb0486d9-16ab-4a78-b966-d74bfacd0ce6.png)

**Comment by ashishjain0512** [comment]
Hey @Issam-seghir 

Thanks for taking the time and reporting this.  Unfortunately, the documentation is correct (however, I do understand the confusion it might create).

Initially, the first set of parenthesis `(text)` was reserved for a node with a rounded edge.

After some time, the requirements were to support a circle, and double parenthesis `((text))` was reserved for that.

Now, we have a lot of users, and to support backward compatibility, when we needed to add support for double circles, we used the triple parenthesis `(((text)))` syntax, so the previous build diagrams are not affected.
