### ISSUE TITLE
classDiagram: return value "std::unique_ptr" does not display

### ISSUE THREAD

**Issue by sebastianbergt** [mermaid-js/mermaid#3303]
**Describe the bug**
The return value of makeToy does not display correctly with `std::` or likely any other namespace prefix.

**To Reproduce**
Just try to render the example below.
If `std::` is omitted, it works again.

**Expected behavior**
Display the makeToy line as `+makeToy() std::unique_ptr<Toy>`

**Screenshots**
Wrong display:
![image](https://user-images.githubusercontent.com/2187920/183409267-3a896e8a-e49f-4735-af9d-8e6aa6d657ba.png)

**Code Sample**
```mermaid 
classDiagram
    class ToyFactory {
        <<factory>>
        +makeToy() std::unique_ptr~Toy~ 
    }
```
[live editor](https://mermaid.live/edit#pako:eNpFjk0KwjAQha8SZqXYE4TSlXoBXQZkSKYabJKaTBaltGc3_RHfavj4eG9G0MEQSNAdpnS2-IzolBclKxH3MFxRc4iDGDe-pK7bDTbNH54cvqn4h6NIbKTM3n4yPXqOc6Gz2MwJKnAUHVpTZtdOBfwiRwpkOT1ljtgpUH5Rc2-Q6WJsWQPZYpeoAswcboPXIDlm-kn797s1fQFmUUi1)

**Desktop (please complete the following information):**
Tried on
 - OS: Ubuntu 20.04 x86_64
 - Browser Chrome
 - Version 103.0.5060.134

**Smartphone (please complete the following information):**
Did not test it on a smartphone.

**Comment by matthew-limbinar** [comment]
Probably this is an instance of https://github.com/mermaid-js/mermaid/issues/1635.

**Comment by jgreywolf** [comment]
Closing in favor of #1635
