### ISSUE TITLE
subsequent sequence diagrams contain previous diagrams (new to 9.1.4)

### ISSUE THREAD

**Issue by messham** [mermaid-js/mermaid#3305]
(Let me know if this issue should be opened more upstream from mermaid)

Since 9.1.4, documents generated with mkdocs (https://github.com/mkdocs/mkdocs) using the mermaid2 plugin (https://github.com/fralau/mkdocs-mermaid2-plugin) that contains more than 1 sequence diagram have not been displaying the diagrams correctly. The first diagram (from top of the doc to bottom) will display correctly, the second will include the first and itself, the third both previous two and itself, etc.

To reproduce, configure the plugin to use mermaid version 9.1.3 as documented here https://github.com/fralau/mkdocs-mermaid2-plugin#explicit-declaration-of-the-mermaid-library. Load a document with multiple sequence diagrams and observe normal behavior. Next, either remove the version or explicitly set it to 9.1.4 and reload the document.

**Comment by hrgui** [comment]
I have the same issue also. 

Here's a codesandbox reproduction of this:
https://codesandbox.io/s/musing-panini-7bz08x?file=/index.html

https://github.com/mermaid-js/mermaid/issues/3292 is a similar issue but it was closed.

**Comment by B-Alica** [comment]
I have the same issue with gantt diagrams.
I display a gantt for the current month, then update it to show another month when user chooses a month. With 9.1.3, no problem, the gantt shows the new data. Since 9.1.4, it shows the new data but still the old ones too. If user chooses several times the same month, it displays several time the data.

**Comment by hrgui** [comment]
I also noticed this problem doesn't show up on the documentation since it's fixed to v9.1.3. When that's updated to v9.1.4, the duplication issue shows up.

**Comment by B-Alica** [comment]
The problem still exists for gantt diagramm.

**Comment by hrgui** [comment]
@B-Alica , I was wondering if you could provide a reproduction in a codesandbox using v9.1.5? If it is still reproducible, I believe it warrants a new bug.

I wasn't able to reproduce but I noticed my setup is just 6 different Gantt charts. Before the fix all subsequent Gantt charts will merge. (e.g. 2nd Gantt chart will also contain the first, 3rd will contain the 2nd and first) After the fix doesn't do that.

However, I believe in the scenario you have described it's different and it involves a month selector? Also not sure if it's reusing the same div.

**Comment by knsv** [comment]
There was a fix for an issue with properly clearing the state between renderings in 9.1.5. Is this still reproducible with 9.1.5 if so I agree that there should new issue.

**Comment by B-Alica** [comment]
@hrgui @knsv It's ok, it's working with 9.1.5 !
