### ISSUE TITLE
Issues with Tooltip

### ISSUE THREAD

**Issue by jpadfield** [mermaid-js/mermaid#3308]
I am working with version 9.1.4

I am following the instructions to add tooltips to nodes as part of interactions (https://mermaid-js.github.io/mermaid/#/flowchart?id=interaction), which works well, thanks, but when I had new line tags "< b r / >" into the tooltip they are just rendered as text: https://jsfiddle.net/4wxyv73h/3/

I am initiating the diagram with loose security as required.

The process does work with older versions of Mermaid, such as the 8.4.8, which is used in the instructions demo: https://jsfiddle.net/4wxyv73h/4/

I could not see anything which indicated new settings that needed to be used with the new version of Mermaid, but perhaps I have missed something.

Was this deliberate for some reason or is this a bug?

In general it would be great to have some better examples of CSS to control tool tips, and it might be useful to have an option to add a tooltip without adding a click, or implying a click by adding an empty callback. 

Thanks

Joe

**Comment by knsv** [comment]
There seems to be something wrong! Thanks for reporting.

**Comment by knsv** [comment]
A more thorough investigation show that the ability to add tags in tooltips were removed to avoid a few vulnerabilities. BR tags should have an exception though. Will reintroduce the ability to use them.
