### ISSUE TITLE
For-profit business with full time developers

### ISSUE THREAD

**Issue by aadamsx** [mermaid-js/mermaid#3309]
Observation: @knsv this library has so much potential. I see so many good ideas and updates just go down the memory hole with no one to work on it.  Issues/Improvements just closed because of the lack of development.  It's obvious you don't have enough time to get any traction on things and you don't have enough contributors to make a real difference.  Yet the use of this tool continues to grow, with even Github integration now an option.

Suggestion: This project needs to be spun off into a for-profit business with many full time developers.  Have you done anything to make this happen?  Do you plan on spinning this off into a paid product (just look at Font Awesome as one example)?  Or maybe a base version and a subscription version with enhanced features.

**Comment by knsv** [comment]
Yes, I am trying to make this happen.

**Comment by knsv** [comment]
Thanks for your suggestion it was well received.
