### ISSUE TITLE
Rendering of Sequence Diagram incorrect

### ISSUE THREAD

**Issue by Zumbala** [mermaid-js/mermaid#3323]
**Describe the bug**
Sequence Diagram rendering incorrect

**To Reproduce**
1. Go to Live Editor
2. Select Sample Sequence Diagram

**Expected behavior**
Rendered diagram should be completely visible

**Screenshots**
![image](https://user-images.githubusercontent.com/7052083/184609418-982c4952-f9ce-4f31-80cd-ec3f03bdb56b.png)

**Comment by jgreywolf** [comment]
@Zumbala I am not able to reproduce this error in live editor.  Can you please validate if this is still an issue?
