### ISSUE TITLE
Are there more styling options for flowchart labels?

### ISSUE THREAD

**Issue by becca-tiessen** [mermaid-js/mermaid#3324]
Hey! I'm having some issues making the labels on a flowchart look acceptable, and I'm not finding much in the way of configuration options. My questions are:
1. Is there a way to add padding around the label text so it doesn't look so squished? and
2. Is there an option to change the label text colour? There's currently not enough contrast.

I have looked through the documentation and https://github.com/mermaid-js/mermaid/blob/develop/src/defaultConfig.js but there's not a ton of customizability for flowcharts that I can tell.

Here's a screenshot of what it looks like currently:
<img width="556" alt="Screen Shot 2022-08-16 at 10 43 01 AM" src="https://user-images.githubusercontent.com/23246768/184921801-286b2ad5-774c-4738-98c5-495d870ffafc.png">

And here's the `docusaurus.config.js` with my current flowchart configuration:
```
 mermaid: {
              theme: "base",
              themeVariables: {
                fontFamily: "proxima-nova",
                fontSize: "16px",
                primaryColor: "#095889",
                primaryTextColor: "white",
                secondaryColor: "#7590A3",
                tertiaryColor: "#f4f4f4",
                signalColor: "#23455C",
                signalTextColor: "#525252",
                noteBkgColor: "#7590A3",
                noteTextColor: "black",
              },
              flowchart: {
                rankSpacing: 100,
                padding: 8,
              }
            }
```

Any help would be appreciated, thanks!

**Comment by PaulRBerg** [comment]
@becca-tiessen passing `themeVariables` to the `mermaid` theme object is not currently supported by Docusaurus (v2.4.0 at the time of writing this):

> [ERROR] ValidationError: "mermaid.themeVariables" is not allowed

Could this be the explanation for the issue you were encountering?

**Comment by PaulRBerg** [comment]
Update: while you can't pass it directly to `mermaid`, you can pass it to the `options` object, like this:

```js
themeConfig:
  mermaid: {
    options: {
      fontFamily: "Roboto",
      themeVariables: {
          // ...
      }
    },
  },
}
```
```

**Comment by jgreywolf** [comment]
@becca-tiessen Have you looked at this? And does it provide what you are looking for?
https://mermaid.js.org/syntax/flowchart.html#styling-and-classes

**Comment by becca-tiessen** [comment]
@PaulRBerg I was using the older way of including mermaid, before Docusaurus made the change to support it so yeah, the config looks a bit different. I think both ways should work the same, but we're upgrading soon so maybe that'll solve some issues.

@jgreywolf thanks for the link! I could probably wrestle it into doing what I want, though it would get a bit tedious to apply the styling to each node individually. Is there a way to apply styling to an entire graph type? If not thanks, and I'll do what I can with what's available 👍

**Comment by sidharthv96** [comment]
@becca-tiessen with the latest mermaid, we support the entire config object inside the diagram's frontmatter. 

https://mermaid.js.org/config/configuration.html#frontmatter-config
