### ISSUE TITLE
`htmlLabels` should be moved up from flowchart to config.

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#3337]
`htmlLabels` should be moved up from flowchart to config.
Will make this a separate issue and handle it there.

_Originally posted by @sidharthv96 in https://github.com/mermaid-js/mermaid/pull/3336#discussion_r950798906_

**Comment by knsv** [comment]
We should make an overhaul of several configuration. options that is/can be shard by multiple diagrams and use a consistent way of handling them.

**Comment by sidharthv96** [comment]
Closing #3397
