### ISSUE TITLE
Remove rogue console.log

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#3339]
**Describe the bug**
There are rogue `console.log`s which pollute the console of sites that embed mermaid. 

**To Reproduce**
- Open https://github.com/mermaid-js/mermaid
- Open console

**Expected behavior**
No logs unless loglevel is set.

**Screenshots**
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/10703445/185790329-791d127e-e42d-49c4-89b3-7777a12edf86.png">

**Comment by knsv** [comment]
Lets remove them all and create a cypress test for it!

**Comment by sidharthv96** [comment]
Maybe eslint might be able to help.
