### ISSUE TITLE
Allow tags and IDs on merge commits in gitgraph diagrams

### ISSUE THREAD

**Issue by bitbonk** [mermaid-js/mermaid#3356]
As of now, it seems that it is not possible to give a merge commit an ID and/or a tag. But git allows is and it sometime is important to do this in a gitgraph diagram to explain or demonstrate stuff.

**Comment by aloisklink** [comment]
Thanks for making the issue :) I actually experienced the exact same thing 2 days ago!

As a side-note, it is possible to give a merge commit a tag (see below).

```mermaid
%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'rotateCommitLabel': false}} }%%
gitGraph
    commit id: "1"
    commit id: "2"
    branch my-pr
    branch other-branch
    checkout main
    commit id: "3"
    checkout my-pr
    commit id: "0"
    commit id: "pull_request-HEAD"
    checkout main
    commit id: "pull_request_target"
    merge my-pr tag: "pull_request"
    checkout other-branch
    commit id: "other_commit"
```
