### ISSUE TITLE
Feature request: Class diagram display regions

### ISSUE THREAD

**Issue by ArnaudB88** [mermaid-js/mermaid#3384]
We use the mermaid class diagram to design database schemes since that's easy for developers and a visual representation can be auto generated through the live editor. But when the diagram becomes bigger (+30 classes), the visual representation becomes complicated because relations will cross other relations. This is because we can't choose which classes are visualized from left-to-right (because of the relationships). The result is a visual scheme in which many relationships cross each other and classes which belong together are scattered from left to right.

I would like to suggest a feature of something like 'display regions'.
- Display regions are squares which group classes together and are always displayed from left to right
- You can declare display regions in the mermaid file
- You can add classes (of a class diagram) to display regions
- (optional) you can set a background color for each display region
- (optional) give a title to a region, which is displayed at the top of the region
- Display regions can be applied to the class diagram and entity relationship diagrams

The alternative I try to do now, is to reorder the class relations, but at this point (+30 classes) it's pointless because some classes jump visually from left to right because of the may relationships between the classes.

Note: this feature request is similar to the existing [subgraph functionality of a flowchart diagram](https://mermaid-js.github.io/mermaid/#/flowchart?id=subgraphs).

Example of a scheme without display regions (as-is):
![image](https://user-images.githubusercontent.com/29403668/187685429-f1bb6d4f-2623-46cc-a547-c152ddccf970.png)

Example of a scheme with display regions (to-be):
(Note: the scheme should be cleaner and relationships should cross less)
![Capture2](https://user-images.githubusercontent.com/29403668/187686656-7c3ec30a-2fae-4f12-ab60-8904e4ba88a2.jpg)

**Comment by knsv** [comment]
We could use subgrapgs/clusters for this. It is possible. @ashishjain0512 What do you think? What should the syntax look like?

**Comment by IceflowRE** [comment]
Pretty sure this is a feature like namespaces or packages.
Also discussed here #4618 .

**Comment by ArnaudB88** [comment]
@IceflowRE Indeed, namespaces is almost exactly what I proposed.
Could it be possible to add styling to namespaces?

**Comment by mihaivader** [comment]
Any ETA for nested namespaces and/or packages for class diagrams ?

**Comment by skillmaker-dev** [comment]
#5487

**Comment by erickalmeidaptc** [comment]
Can we have this feature also added to the ERD diagrams?

**Comment by jgreywolf** [comment]
I am closing this issue, as the original request can be handled by using namespaces
