### ISSUE TITLE
Add ZenUML Support

### ISSUE THREAD

**Issue by MrCoder** [mermaid-js/mermaid#3435]
Hey, author of ZenUML here.

**Is your feature request related to a problem? Please describe.**
ZenUML (ZenUML.com) is a diagram-as-code solution that convert text to sequence diagrams. ZenUML has a Confluence add-on, in which we integrated with Mermaid to extend the capability to more diagrams (many thanks). Many of our clients have asked us to unify the editing experience.

<img width="1195" alt="Screen Shot 2022-09-10 at 9 45 52 am" src="https://user-images.githubusercontent.com/169417/189459737-c55f0af8-dea7-484f-a5f3-3c7886c35729.png">

<img width="1197" alt="Screen Shot 2022-09-10 at 9 48 11 am" src="https://user-images.githubusercontent.com/169417/189459754-1f3e93aa-72f4-48ba-a447-d2dc5241b60b.png">

More introduction of ZenUML can be found here: https://modeling-languages.com/zenuml-drawing-sequence-diagram-easier-faster/

**Describe the solution you'd like**
I would like to integrate ZenUML into mermaid so that users can use ZenUML flavour DSL inside mermaid. ZenUML renderer is an open-source library (under MIT license). I am happy to implement the integration and pull-request.

**Describe alternatives you've considered**

- Confluence users use the ZenUML add-on - https://marketplace.atlassian.com/apps/1218380/zenuml-sequence-diagram?tab=overview&hosting=cloud
- JetBrains users use the ZenUML plugin - https://plugins.jetbrains.com/plugin/12437-zenuml-support
- Desktop users use our desktop applications - https://zenuml.com
- Some enterprise users integrate with our renderer library directly - https://www.npmjs.com/package/vue-sequence
- Most other users use the online editor - https://app.zenuml.com/ or https://zenuml.cn

Should you need more information, please let me know. Send me an email at peng(AT)zenuml.com or DM @PenngXiao on Twitter. Thanks.

**Comment by knsv** [comment]
This is interesting! Lets discuss, contact me on slack (knsv)! @MrCoder

**Comment by jgreywolf** [comment]
@MrCoder What is the current status on this?
