### ISSUE TITLE
Add my plugin to the documentation... 

### ISSUE THREAD

**Issue by emersonbottero** [mermaid-js/mermaid#3465]
**Is your feature request related to a problem? Please describe.**
Update the docs with a link to my vitepress plugin.. 

**Describe the solution you'd like**
https://emersonbottero.github.io/vitepress-plugin-mermaid/guide/more-examples.html

**Describe alternatives you've considered**
Just a doc update, no alternatives

**Additional context**
I didn't see other places with examples working with images like mine. 😎

**Comment by sidharthv96** [comment]
@emersonbottero please raise a PR for this, you can edit the doc file in `src/docs`.
