### ISSUE TITLE
Documentation: Flowcharts styling not fully documented 

### ISSUE THREAD

**Issue by PackElend** [mermaid-js/mermaid#3500]
[see ](https://github.com/mermaid-js/mermaid/issues/3011) mentions the option `messageAlign: left ` but that cannot be found in https://github.com/mermaid-js/mermaid/blob/develop/src/docs/flowchart.md#styling-and-classes.
Could anyone, who knows the options update the documentation 

MERCI :)

**Comment by sidharthv96** [comment]
This problem is bigger than flowcharts and affects almost all types.
We're planning on tackling it from the root, trying to generate documentation from the code.

https://github.com/mermaid-js/mermaid/discussions/3416

**Comment by jgreywolf** [comment]
Closing in favor of #3416
