### ISSUE TITLE
UML inheritence look

### ISSUE THREAD

**Issue by vallsv** [mermaid-js/mermaid#3527]
**Describe the bug**

Hi,

I have noticed that the merrmaid documentation and github integration are not using the right arrow for inheritance.

An UML inhertence arrow is supposed to be an empty triangle.

Mermaid displays it with a filled triangle.

```mermaid
classDiagram
classA <|-- classB : Inheritance
```

Do you think that's something which could be fixed?
With the actual `--|>` syntax? Or optional another one?
I maybe could take a look at it.

**Expected behavior**

![image](https://user-images.githubusercontent.com/7579321/192800029-2dbbd857-5c7d-4b2b-8726-90a1e805cb0e.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/7579321/192799262-124f2a75-d45d-4c13-93d0-e342035ced06.png)

**Code Sample**

```
classDiagram
classA <|-- classB : Inheritance
```

**Comment by michalspano** [comment]
+1; please revisit this issue and the **PR** associated.
