### ISSUE TITLE
Hyperlink doesn't work inside subplot?

### ISSUE THREAD

**Issue by bwheelz36** [mermaid-js/mermaid#3529]
Hi all

Thanks for this great tool. Below is my plot. It's working perfectly, except:
- when I click on the subplot `Phantom Design` the hyperlink isn't working. I've tried putting this click command in various place but can't get it to work?
- The `Automated reporting` block isn't registering as clickable, despite having a click command associated with it?
- While I am asking for help - is it possible to make the subplot go above instead of below the main plot?
Thanks!

```mermaid

flowchart LR
subgraph AA[Phantom Design]
end
    A[Marker <br>Extraction]--->B[Marker <br>Matching]
    B[Marker <br>Matching]--->C[Field <br> Calculation] & E[Automated <br>reporting]
    C[Field <br> Calculation]-->D[Spherical Harmonic <br>Analysis]
    D[Spherical Harmonic <br>Analysis]-->E[Automated <br>reporting];
    D[Spherical Harmonic <br>Analysis]-->F[Distortion Correction]
	

    click AA "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/phantom_notes.html"
    click A "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/marker_extraction.html"
    click B "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/marker_matching.html"
    click C "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/field_calculation.html"
    click D "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/fit_spherical_harmonics.html"
    click E "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/reporting.html"
```

**Comment by bwheelz36** [comment]
Anyone have any ideas on this? otherwise we can just close the issue I guess...

**Comment by mathomp4** [comment]
@bwheelz36 Wait, do the other links work for you? When I try to click on, say "Marker Matching" I just get this:
![Screen Shot 2022-12-06 at 2 20 15 PM](https://user-images.githubusercontent.com/2982494/206002560-ad603226-e410-4ade-bc7f-7b4d19169d62.png)

**Comment by mathomp4** [comment]
I was in Chrome for my thing.

Though now I wonder if my issue is a "GitHub implementation of Mermaid" issue rather than a "Mermaid itself" issue.

Then the next question is: where does one make an issue/question for "GitHub implementation of Mermaid"? 😕

**Comment by 7yl4r** [comment]
Can you include the mermaid source code used to create this plot?

**Comment by bwheelz36** [comment]
Hi @7yl4r see below:

flowchart LR
subgraph AA[Phantom Design]
end
    A[Marker <br>Extraction]--->B[Marker <br>Matching]
    B[Marker <br>Matching]--->C[Field <br> Calculation] & E[Automated <br>reporting]
    C[Field <br> Calculation]-->D[Spherical Harmonic <br>Analysis]
    D[Spherical Harmonic <br>Analysis]-->E[Automated <br>reporting];
    D[Spherical Harmonic <br>Analysis]-->F[Distortion Correction]
	

    click AA "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/phantom_notes.html"
    click A "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/marker_extraction.html"
    click B "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/marker_matching.html"
    click C "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/field_calculation.html"
    click D "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/fit_spherical_harmonics.html"
    click E "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/reporting.html"

**Comment by 7yl4r** [comment]
Why are you defining AA as a subgraph?

The graph you show works well if the "Phantom Design" component is declared as a node instead of as an empty subgraph:

```
flowchart LR

AA[Phantom Design]

A[Marker <br>Extraction]--->B[Marker <br>Matching]
B[Marker <br>Matching]--->C[Field <br> Calculation] & E[Automated <br>reporting]
C[Field <br> Calculation]-->D[Spherical Harmonic <br>Analysis]
D[Spherical Harmonic <br>Analysis]-->E[Automated <br>reporting];
D[Spherical Harmonic <br>Analysis]-->F[Distortion Correction]

click AA "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/phantom_notes.html"
click A "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/marker_extraction.html"
click B "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/marker_matching.html"
click C "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/field_calculation.html"
click D "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/fit_spherical_harmonics.html"
click E "https://acrf-image-x-institute.github.io/mri_distortion_toolkit/reporting.html"
```

The way an empty subgraph *should* behave is not intuitive to me.

A a link for a whole subgraph also brings up a lot of edge cases where it is not clear to me what behavior would be intuitive. A subgraph is just a highlighted (and named) area of a graph.

Your code creates an empty subgraph and then assigns a link to it; this is two layers of I am not sure what *should* be happening.

**Comment by bwheelz36** [comment]
I'm honestly not sure I considered having AA as an unlinked node, I don't think I'd realized I could do this. You're right that does work better! 
Thanks, I'll close this issue now!
