### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by Aniket1026** [mermaid-js/mermaid#3581]
In the contribution guidelines documentation . As for some beginners can we add some more steps that may help them setting the project locally on their system ? I'm attaching a screenshort regarding adding some documentation updates.

<img width="447" alt="mermaid js readme" src="https://user-images.githubusercontent.com/92184189/194143897-2ba4bb08-3466-4aa0-bf8e-9bcdeca46923.PNG">

If it looks helping you can assign me . So i can raise a PR

Also in the contributing.md it is stated that Documentation source files are in /src/docs directory . I'm just not able to find that directory too . My doubt here is did the directory name needs to update or am i making a mistake regarding the path directory.

<img width="841" alt="mermaid js" src="https://user-images.githubusercontent.com/92184189/194145188-3c3f99b7-2f10-4c01-9b07-a3dfc0dad881.PNG">

**Comment by sidharthv96** [comment]
`/src/docs` directory has moved to `packages/mermaid/src/docs`.

**Comment by Aniket1026** [comment]
Created the PR for the Steps i added.

But what for the updated path ? Should i also change the path in the documentation from /src/docs to packages/mermaid/src/docs ?

**Comment by sidharthv96** [comment]
You can update the path

**Comment by Aniket1026** [comment]
@sidharthv96 can I raise another issue for automating the linting as you mentioned earlier?

**Comment by weedySeaDragon** [comment]
@Aniket1026 - I just submitted  PR #3814 that revises the instructions for contributing/developing.
Can you please review it? I'd love your feedback.

Hopefully I can incorporate your feedback and address your issue with it.

**Comment by Aniket1026** [comment]
@weedySeaDragon I apologize for replying so late as I was just busy in other things . And for the review you asked for it's upto maintainers what they want in the project but personally i liked how you described your changes while raising the issue.
keep it up and contribute to open source projects 😄 .
