### ISSUE TITLE
Changing pie chart order

### ISSUE THREAD

**Issue by blakegearin** [mermaid-js/mermaid#3593]
Is it possible pass a flag to change the order of the slices in a pie chart to match the label order instead of biggest to smallest value?

These look the same even though the labels are in a different order.

```mermaid
pie title Pets adopted by volunteers
    "Dogs" : 386
    "Cats" : 85
    "Rats" : 15
```

```md
pie title Pets adopted by volunteers
    "Dogs" : 386
    "Cats" : 85
    "Rats" : 15
```

```mermaid
pie title Pets adopted by volunteers
    "Dogs" : 386
    "Cats" : 85
    "Rats" : 15
```

```md
pie title Pets adopted by volunteers
    "Cats" : 85
    "Rats" : 15
    "Dogs" : 386
```

Docs: https://mermaid-js.github.io/mermaid/#/pie

**Comment by ArsalanAli915** [comment]
Hi, my name is arslalan ali. I would like solve this problem and want to contribute to open source in the month October. please assign me.

**Comment by DIvkov575** [comment]
Could I please be assigned to this issue? I have experience with full-stack JS.

**Comment by utsavs22** [comment]
Hello, I am **Utsav Sinha**. I can solve this issue by allowing **custom labelling** which will result in the flexibility for the user to select the order according to their need.

**Comment by Manishgupta200** [comment]
Assign it to me. I would like to work on this issue.

**Comment by Abhishekjoshi7** [comment]
Please assign this to me, will solve it within 48 hours.
