### ISSUE TITLE
Idea: Add eslint cSpell plugin

### ISSUE THREAD

**Issue by SeanKilleen** [mermaid-js/mermaid#3601]
A follow-up to #3600.

Per @sidharthv96, an ESLint plugin exists for working with cSpell: https://www.npmjs.com/package/@cspell/eslint-plugin

As a follow-up to the work to automate spellcheck, making it a part of ESLint might be a nice thing too.

**Comment by Satyabrat-Ojha** [comment]
@sidharthv96 can you please assign this issue to me?
I would love to learn and contribute here.

**Comment by sidharthv96** [comment]
Just FYI, you don't have to ask for issues to be assigned. 
All issues without Open PRs are up for everyone.
