### ISSUE TITLE
`docs:build` doesn't work in windows

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#3603]
**Describe the bug**
It is an issue with globby and windows path separators.

**To Reproduce**

1. Change any md file in `packages/mermaid/src/docs`
2. Run `pnpm docs:build` in windows
3. Files in `/docs` aren't built properly

**Expected behavior**
Files in `/docs` are built.

I have a partial fix in https://github.com/mermaid-js/mermaid/commit/6f05d4b05afd5cee36f8a685e05982de315e735d, so you can fork the `sidv/fixWindowsPath` branch and continue.

Reported by @SeanKilleen in https://github.com/mermaid-js/mermaid/pull/3600

**Comment by deveshchatuphale7** [comment]
Hey @sidharthv96 I would like to work on this issue

**Comment by sidharthv96** [comment]
Hi @deveshchatuphale7, you don't have to ask for issues to be assigned. 

All issues without Open PRs are up for everyone. :)

**Comment by SiddheshKukade** [comment]
@sidharthv96  Sir I working fine for me as you can I've done the changes and still the build is successful.
![image](https://user-images.githubusercontent.com/65951872/194711450-ad30914a-acc8-4669-9e1d-be52ced1ba17.png)

**Comment by SeanKilleen** [comment]
@SiddheshKukade what version of windows are you on?

**Comment by SiddheshKukade** [comment]
@SeanKilleen Actually I'm doing it on a `gitpod.io` instance

**Comment by SeanKilleen** [comment]
> @SeanKilleen Actually I'm doing it on a `gitpod.io` instance. I uses Ubuntu I think

If it is not a windows gitpod instance, then you will not be able to reproduce the issue. The title of the issue states the process is broken on Windows machines.

**Comment by SiddheshKukade** [comment]
@SeanKilleen Sorry I missed that 👍🏻

**Comment by harshlancer** [comment]
I've tried to reproduce this issue but surprisingly this shows up
![Screenshot 2022-10-10 07 10 50](https://user-images.githubusercontent.com/91771779/194789439-9d05b031-0573-4b01-80c8-40dd0c21744c.png)

**Comment by SeanKilleen** [comment]
@harshlancer are you on Windows? Unclear from the screenshot. This issue only applies to Windows machines.

**Comment by harshlancer** [comment]
Yes I'm on windows 10

**Comment by Aliksarkar18** [comment]
I want to contribute.

**Comment by bismuth42** [comment]
i would like to contribute
