### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by PritamSarbajna** [mermaid-js/mermaid#3610]
Add a favicon to the website

I'd love to work on it if assigned

**Comment by sidharthv96** [comment]
![MermaidOpenSource_IconContained_Pink](https://user-images.githubusercontent.com/10703445/194756606-e4152fac-db50-4df2-b4f0-21e27080d560.svg)

You can use this logo.

**Comment by PritamSarbajna** [comment]
@sidharthv96 thanks

**Comment by PritamSarbajna** [comment]
Hi @sidharthv96 can you tell me where to put my favicon files ?? also where to add the links ?? ....in this broad codebase I'm not understanding.

**Comment by sidharthv96** [comment]
You can refer [here](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md#committing-documentation) to see how documentation is generated. 

The index.html there is where you need to add the favicon tag. 
You can place the favicon in the folder where `header.png` file is located.

**Comment by emersonbottero** [comment]
I can also add it to the nem docs version.
should this color be the primary color used in the docs? links tab group depends on main color..
![image](https://user-images.githubusercontent.com/12377432/196065694-3b9673dc-e1f6-400c-9a56-0f458c841d40.png)
![image](https://user-images.githubusercontent.com/12377432/196065723-9e2bcecd-47a6-4492-aba5-d0104619e43e.png)
![image](https://user-images.githubusercontent.com/12377432/196065741-81375917-df0a-4c4f-9059-80287387fa56.png)

**Comment by AbhayKatoch** [comment]
Could you assign me to this please.

**Comment by emersonbottero** [comment]
It Is already done. The way we add It is different in vitepress since we dont have an HTML file to edit.
