### ISSUE TITLE
Need aria-roledescription on each data view

### ISSUE THREAD

**Issue by brennanyoung** [mermaid-js/mermaid#3626]
The next important step in making mermaid accessible is to insert some basic ARIA roles to help manage expectations.

First thing: Mermaid generates a chart or data view. Currently there is no semantic role provided for the view, which is unhelpful for users of assistive tech. Most ARIA attributes do very little unless you provide an appropriate role (or if the HTML element has an implicit role, such as `<img>` or `<h1>`). `<svg>` elements are **not** automatically mapped to `img` on all platforms, so the aria attributes currently added are likely to be ignored, at least on some configurations.

In particular, HTML `<div>` and `<span>` and SVG `<g>` are mapped to [the "generic" role](https://www.w3.org/TR/wai-aria-1.2/#generic) by default, which does not support naming. Mermaid data views are presented as a `<div>` with a `<svg>` inside. 

(Edit - correction) SVG maps to the "graphics-document" role by default.

Other choices might have been

- [role="img"](https://www.w3.org/TR/wai-aria-1.2/#img) 
- [role="figure"](https://www.w3.org/TR/wai-aria-1.2/#figure)
- [role="graphics-document"](https://www.w3.org/TR/graphics-aria-1.0/#graphics-document)

By my reading of these specs, "graphics-document" indeed appears to be the best fit for a data view today. 

A graphics document:

- Conveys meaning through visual appearance or layout.
- Is structured. (unlike img)
- Is self-contained (i.e. meaning is retained when separated from the surrounding content, unlike figure, which requires a context).

Note: Some critical comments have been raised about imagining accessible data representations as "graphics" or "visualisations". To encourage a presentation-independent mindset for representing data, future versions of ARIA may introduce nomenclature for data that have less of a visual bias, such as "projection" or "DX" (for 'data experience'). My point here is that while "graphics-document" is the best fitting role available today, this may change. 

But ARIA already offers a way to announce an alternative name for any given role: [aria-roledescription](https://www.w3.org/TR/wai-aria-1.2/#aria-roledescription), which may be used to **distinguish one kind of chart/diagram/dataview from another**.

Mention of `aria-roledescription` is typically accompanied by warnings of the "with great power comes great responsibility" type, because misuse of this attribute can be very disorientating. Even so, there is a strong case for it here.

So, back to our mermaid view. Is it a flow chart? a sequence diagram? There are a fixed set of chart types available. We know what they are called. Let's provide a text cue to assistive tech, so that people have an idea what kind of data view they've encountered.

Suggestions (assuming a pie chart, but could be any of the standard set of views):
`<div class="mermaid" role="graphics-document" aria-roledescription="pie chart" aria-labelledby="idOfSVGTitleElement">`
...or...
`<div class="mermaid"><svg id="diagram" role="graphics-document" aria-roledescription="pie chart">`

So, for a pie chart that shows browser statistics, instead of the AT announcing "graphics-document browser statistics" you'll get "pie chart browser statistics". 

I don't know enough to express a preference about where best to put these attributes; on the div or on the svg. Either way, the element that gets the role will become a node in the accessibility tree, and it is **this** node that needs a name. 

For interactive views, you would typically put a tab stop on that element, so that it can be focused, and become a target for general keyboard input (so this is where you'd add any fancy keyboard handlers too). I don't think we are ready for that yet.

If it is the SVG then the title element in the SVG is "automagically" used as the accessible name. This is probably what we want. Otherwise the div can point to the id of the title inside the SVG with `aria-labelledby`. Some testing will confirm which (if any) is better.

Last point: `aria-roledescription` should be a translatable, human-readable name. I haven't looked at mermaid's i18n features (if any) but the case of other language versions of this string should not be overlooked for non-English content.

**Comment by weedySeaDragon** [comment]
Fantastic!  I am very interested in helping to make mermaid more accessible. 
This seems like it will be straightforward to implement.
My opinion is that we should put the tags in the `svg` element.  But others may differ.

I don't believe there is any i18n in mermaid. (I haven't seen any in the code, but I'm newish.) Really good point to make sure that i18n will be easy to apply to `aria-roledescription` .

**Comment by brennanyoung** [comment]
Splendid. Looking at this a bit more, I am inclined to agree that the SVG should be the node that represents the 'root' of the view, rather than the DIV. 

Nice to know the DIV is there, of course (a 'clean' semantics-free block element for various layout affordances).

Also, I have a small correction (OP already edited): SVG maps to the "graphics-document" role by default, so (in theory at least) we do not need to add `role="graphics-document"` to the SVG. All good.

The svg title element is already in place and working fine "in the wild", and there's the first rule of ARIA ("don't use ARIA if you can achieve the same results with the host language"). Relying on svg title helps avoid superfluous ARIA.

**Comment by weedySeaDragon** [comment]
@brennanyoung FYI I've looked at the code and this will be a really easy thing to implement.  (It's just a few lines in mermaidAPI.ts.) I'm going to first do #3648 and then I'll do this.

**Comment by brennanyoung** [comment]
Great work guys! Sorry I have been away from this for a while. 

Just a tiny fly in the ointment - apparently even though the spec says that SVG **should** map to `graphics-document`, I don't think this actually happens on all browsers. I'm informed that in practice it maps to `group`. (Facepalm).

https://www.w3.org/TR/svg-aam-1.0/#mapping_role says SVG maps to `graphics-document`
https://www.w3.org/TR/graphics-aam-1.0/#mapping_role_table does not mention a WAI-ARIA mapping for SVG
https://www.w3.org/TR/html-aam-1.0/ refers to both of the above
[This discussion](https://github.com/w3c/html-aam/issues/43) indicates that the ARIA mapping was changed from `group` to `graphics-document` in the spec at some point. Apparently the browser vendors have not followed through.

This will probably not be a problem as long as there is an accessible name included. If we discover odd behavior we can add the `graphics-document` role as suggested (and retracted) by me above). 

I'm posting this here after the merge with my fingers crossed, in case anyone is hunting an odd symptom. Apologies for any confusion over this rather subtle issue.

**Comment by sidharthv96** [comment]
If it's a small fix, we can try to get it in before the 9.3.0 release. 
We have branched off and released an RC, but might be able to squeeze in small fixes.
