### ISSUE TITLE
2 gantt demo diagrams fail in Firefox 105.0.3 (64-bit)

### ISSUE THREAD

**Issue by weedySeaDragon** [mermaid-js/mermaid#3655]
**Describe the bug**
2 of the diagrams in `demos/gantt.html` are now throwing Syntax errors when running using a local dev server (e.g. `pnpm dev`) and Firefox 105.0.3 (64-bit) [macOs] (just released Oct 7).

The diagrams work fine in Chrome and on the Mermaid live editor. 

**To Reproduce**

1. Run a dev server (e.g. `pnpm dev`)
1. Open  the gantt demo page (`http://localhost:9000/gantt.html`) in that version of Firefox.

The charts titled "Hide today marker" and "Style today marker" are throwing the errors.

**Expected behavior**
These worked before in prior versions of Firefox.

**Desktop (please complete the following information):**

- OS: macOS 
- Browser Firefox
- Version  105.0.3 (64-bit) 

Mermaid develop branch v. 9.2.0-rc2

**Additional context**

This version of Firefox was released on Oct 7th, which explains why the diagrams worked up until recently.  This is the first time I've viewed them since I updated to this version.

**Comment by amritavpr** [comment]
Can I contribute to this one?

**Comment by isinek** [comment]
It seems that this can be solved by using dateFormat Z and value like -01:00.
