### ISSUE TITLE
Support dash in class diagrams

### ISSUE THREAD

**Issue by martinbonnin** [mermaid-js/mermaid#3663]
The following [![test](https://mermaid.ink/img/pako:eNo1zTsOAjEQA9CrRK43F0hBBSegnWbIDBCRD8qnQMvenRShs6VneYcvonDwkVs7B35UTpRTkRHVsrH2ezKr3ShjQ9KaOMic7JSNIfSnJiW4GYXri0D5mG68hbteJPRS4e4cm27g0cv1kz1cr0P_aN0udfwAqi0zHg)](https://mermaid.live/edit#pako:eNo1zTsOAjEQA9CrRK43F0hBBSegnWbIDBCRD8qnQMvenRShs6VneYcvonDwkVs7B35UTpRTkRHVsrH2ezKr3ShjQ9KaOMic7JSNIfSnJiW4GYXri0D5mG68hbteJPRS4e4cm27g0cv1kz1cr0P_aN0udfwAqi0zHg) gives a parse error:

![Screenshot 2022-10-13 at 13 32 24](https://user-images.githubusercontent.com/3974977/195585404-2e26c653-6e85-44bb-98f8-fe6f07f81221.png)

It would be nice to have that supported. This issue looks similar to https://github.com/mermaid-js/mermaid/issues/1228 but for class diagrams.

**Comment by mishugana** [comment]
Would love to take this on

**Comment by jgreywolf** [comment]
@mishugana If you are still up for this, please, jump in

**Comment by jgreywolf** [comment]
Closing as this was resolved in an earlier PR
