### ISSUE TITLE
Add OpenGraph meta tags

### ISSUE THREAD

**Issue by danangtomo** [mermaid-js/mermaid#3675]
**Is your feature request related to a problem? Please describe.**

Not a problem. Just add Open Graph meta tags for title, URL, image, decs, and type to the website.

*The Goals*
- Make the content more eye-catching in social media feeds.
- Tell people what the content is about at a glance.
- Sharing via social media helps this project grow bigger

**Comment by danangtomo** [comment]
I'd love to work on it if assigned

**Comment by knsv** [comment]
Much appreciated, assigned you are!
