### ISSUE TITLE
(docs)  duplicated info in Contributing.md and docs/development.md

### ISSUE THREAD

**Issue by weedySeaDragon** [mermaid-js/mermaid#3682]
**Describe the bug**
Developer documentation:
Confusingly, there are 2 write-ups about how to contribute to the project: `CONTRIBUTING.md` 
and `docs/development.md`.  

There should be only 1 document that explains how to contribute to the project.

`CONTRIBUTING.md` is the established, typical file that explains how to contribute to a project.  If all of the documentation is going to live under a documentation folder (and be  generated with some process), then `CONTRIBUTING.md` should simply contain a note that tells potential contributors where to find the information.  Ex: "Read how to contribute to this project on our documentation site in the [whatever] file. "   -- and then link the text "our documentation site in the [whatever] file." should link to that file on the documentation site.

It's not clear to me if the contributing information on the documentation site is supposed to be the canonical information or not, else I'd do a PR to update `CONTRIBUTING.md`.

**Comment by sidharthv96** [comment]
@weedySeaDragon, yes, we should only have one document.
Can you check https://github.com/mermaid-js/mermaid/pull/3678 and suggest the necessary changes?

I believe it would be better to have contribution guideline inside the main docs site as most people would be referring to that. A link should suffice in contributing.md.

**Comment by weedySeaDragon** [comment]
@sidharthv96  I don't want to hold up #3678.  (I'm looking forward to seeing it merged!)
I'll merge the two documents into a document that lives in the main docs site (where-ever that is after #3678 is merged) and would like to improve it some.
(Maybe that's what you meant, anyway)

And I'll just put a sentence into CONTRIBUTING.md that points people to the right place in the documentation site.
