### ISSUE TITLE
Gantt , boxes of the tasks disappear

### ISSUE THREAD

**Issue by igorpereirabr1** [mermaid-js/mermaid#3692]
Hello Community,

I've been using the Gantt for a while, but for some reason, it's not working as expected, the boxes around the tasks just disappeared.

```
gantt
dateFormat YYYY-MM-DD HH:mm
axisFormat %Hhrs
title Agenda
todayMarker stroke-width:2px,stroke:#0f0,opacity:0.5

section meetings
Focus time :crit, 2022-10-18 08:00, 120mm
Standup :, 2022-10-18 11:00, 30mm
Buscar Valentina :, 2022-10-18 11:30, 30mm
Catch up with Igor and Vis :, 2022-10-18 12:00, 60mm
Almoco :, 2022-10-18 13:00, 60mm
Weekly touch base with Care team :, 2022-10-18 15:00, 90mm
Focus time :, 2022-10-18 16:30, 90mm
section Breaks
```
[![](https://mermaid.ink/img/pako:eNplUk1v2zAM_SuCht3sxB-Lm-jWNiuyQ04FOgzwhZEYW4glGRK91gjy36c4W5BmPEmP7z0SJI9cOoVc8AYsUW0VEL44b4DYrxjpdpuu12yzEcbUFj50-Jv8uml9qC1p6pA9NhiF8ecUjFvwB_QskHcHTN-1olYU_UdyAcSXbJ8lrgepaRTZbFHb2gaUpJ1lBpG0baLvi5NDYKQNMiG9poQVWVGkeZbmS5YtRZYlLC-yc1OvBFYNPROfOHk-ccqJ8jQECZ69QYexYwv_c8sr9xlItiz6vWtq2Y_GeRb92ZsO96piqlBNqsfOOOnuGeUN4yfioRsZuSHa7yDgpcAzeGSEYO61i0m7mrS30_jMqqbOL6x_U3zyCIc4Q3YTPOEG4-K0iqs-nnM1pxYN1lzEp4o7q3ltT5EHA7nX0UouyA-Y8KE_38RaQ-PBcLGHLlzR70qT81ewc6Awfo-cxn46Kh0oWkpn97o544PvItwS9UHM5-f0rIljGHYz6cw8aNWCp_b3qppXRbWEosTqoYRFWSq5y1fLffEt36uHLC-An04Jx6n-9nLB0yGf_gAUFN94?type=png)](https://mermaid.live/edit#pako:eNplUk1v2zAM_SuCht3sxB-Lm-jWNiuyQ04FOgzwhZEYW4glGRK91gjy36c4W5BmPEmP7z0SJI9cOoVc8AYsUW0VEL44b4DYrxjpdpuu12yzEcbUFj50-Jv8uml9qC1p6pA9NhiF8ecUjFvwB_QskHcHTN-1olYU_UdyAcSXbJ8lrgepaRTZbFHb2gaUpJ1lBpG0baLvi5NDYKQNMiG9poQVWVGkeZbmS5YtRZYlLC-yc1OvBFYNPROfOHk-ccqJ8jQECZ69QYexYwv_c8sr9xlItiz6vWtq2Y_GeRb92ZsO96piqlBNqsfOOOnuGeUN4yfioRsZuSHa7yDgpcAzeGSEYO61i0m7mrS30_jMqqbOL6x_U3zyCIc4Q3YTPOEG4-K0iqs-nnM1pxYN1lzEp4o7q3ltT5EHA7nX0UouyA-Y8KE_38RaQ-PBcLGHLlzR70qT81ewc6Awfo-cxn46Kh0oWkpn97o544PvItwS9UHM5-f0rIljGHYz6cw8aNWCp_b3qppXRbWEosTqoYRFWSq5y1fLffEt36uHLC-An04Jx6n-9nLB0yGf_gAUFN94)

Is anyone have any idea about what is wrong here?

Thanks and regards,

**Comment by weedySeaDragon** [comment]
You have the duration times set using `mm` Ex: 
```
Focus time :crit, 2022-10-18 08:00, 120mm
```

If I change them to just "m"
```
Focus time :crit, 2022-10-18 08:00, 120m
```

It works.  
Have you been using "mm" previously?

(The documentation is not clear on this at all.)

**Comment by igorpereirabr1** [comment]
Thanks for helping! Now it's working! Yeah, before this "mm" works without issues...
