### ISSUE TITLE
Add 'curly' eslint rule.

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#3697]
- [ ] Add the "curly" rule into eslintrc.
- [ ] Auto fix all corresponding errors

**Comment by jeroenekkelkamp** [comment]
Can i work on this one? :)

**Comment by sidharthv96** [comment]
Hi,
 
You don't have to ask for issues to be assigned 😄
All issues without Active PRs are open for everyone.

**Comment by jeroenekkelkamp** [comment]
Ah ok, got it ;)
