### ISSUE TITLE
UML comments (notes)

### ISSUE THREAD

**Issue by xenoterracide** [mermaid-js/mermaid#3699]
UML prescribes a [standard](https://www.omg.org/spec/UML/2.5.1/PDF) (sorry only available in PDF), comments, or notes. See section 7.2.3.2. This should be available on all UML Diagrams.

I noticed the absence in class diagrams, but this is not a feature specific to those.

Related (sub issue) #821 

suggestion for syntax.

```
classDiagram
   class Clazz
   
   note -- Clazz
   some fully
   commented
   text
   end note
```

an alternative I like better

```
classDiagram
   class Clazz
   
  Clazz -- [
   some fully
   commented
   text
 ]
```

I think this is problematic for a state diagram, but perhaps that could have a new version, which makes more sense because it's a circle

```
stateDiagram-v3
    O--> Still
    Still -->O
```

I think that mermaid should be able to dynamically resize the note text instead of having it manually sized, although this should have it of a reasonable size.

**Comment by jgreywolf** [comment]
@xenoterracide how is this different from the ability to add notes available right now?

```
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    note for Maple "this is not an animal"
    class Maple

```

https://mermaid.ink/img/pako:eNplUE1rwzAM_StGZ7fUyRxvZpdB2a2n3UYuIlFWM38E24F1Wf77nKTsMiGQeHrvSWiGLvQEGjqLKZ0NfkR0rWclXrxxaNnzz-HAzlP3-R99Nem6oz5kYkOI7IKjJdZCvprESpYBQ19yVbWws7ddO7X1wMFRdGj6csW8ElY1OWpBl7anASebV-lSqDjl8HbzHegBbSIO09hjpvvhf-iIHvQMX6BPx1OJSkgllVCVlA-qFrXicAMtmvr41KjqUQrZVHLh8B1CMREcqDc5xMv9N2vZTN-3eY4TLb8X9mF9?type=png

**Comment by xenoterracide** [comment]
Was that there a year ago? Does it work on GitHub? Sometimes when it takes a year or more for someone to respond it's hard for me to remember if the reason that it's no longer an issue is because something has changed or if I was an idiot or if I forgot to leave a detail. 

Although, at a glance it looks like I'm trying to write the comment itself as multi-line text instead of possibly having to have one really long line in the code. I also mentioned state diagrams. 

Realistically at this point all I remember is that I decided Mermaid had insufficient features and too many bugs for my purposes at that time.

**Comment by jgreywolf** [comment]
Fair enough.  I am going to go ahead and close this one - and if you, or someone, feels it is needed to be looked at, please open a new issue
