### ISSUE TITLE
Docs: Broken links about `defaultConfig.js`

### ISSUE THREAD

**Issue by YDX-2147483647** [mermaid-js/mermaid#3703]
Years passed. `src/defaultConfig.js` becomes `packages/mermaid/src/defaultConfig.ts`, but the doc doesn't.

## Problem

There are 3 links from [_Directives_](https://mermaid-js.github.io/mermaid/#/./directives) to the old `defaultConfig.js`.

1. The note in [_Types of Directives options_](https://mermaid-js.github.io/mermaid/#/./directives?id=types-of-directives-options).

https://github.com/mermaid-js/mermaid/blob/f2279d48d84921d64463bac4cefc14c96ef6dd58/packages/mermaid/src/docs/directives.md?plain=1#L27

2. [_Changing flowchart config via directive_](https://mermaid-js.github.io/mermaid/#/./directives?id=changing-flowchart-config-via-directive), after the `<ul>`.

https://github.com/mermaid-js/mermaid/blob/f2279d48d84921d64463bac4cefc14c96ef6dd58/packages/mermaid/src/docs/directives.md?plain=1#L191

3. [_Changing Sequence diagram config via directive_](https://mermaid-js.github.io/mermaid/#/./directives?id=changing-sequence-diagram-config-via-directive), after the `<ul>`.

https://github.com/mermaid-js/mermaid/blob/f2279d48d84921d64463bac4cefc14c96ef6dd58/packages/mermaid/src/docs/directives.md?plain=1#L224

## Possible Solution

- `defaultConfig.js` → `defaultConfig.ts`

- `https://github.com/mermaid-js/mermaid/blob/develop/src/defaultConfig.js` → `https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/defaultConfig.ts`

---

I think I can make a PR … However, I guess there might be a better way (some macro?) to fix it.

(Sorry I am new to docsify. I've searched their doc but I still have no idea.)

**Comment by callmetushar123** [comment]
Assign me, I will do it

**Comment by aloisklink** [comment]
Fixed by https://github.com/mermaid-js/mermaid/pull/3738

Thanks for reporting this issue :)

We now have a GitHub Action that automatically checks for broken links, so we should hopefully avoid future errors like this!
