### ISSUE TITLE
Multiple npm security warnings

### ISSUE THREAD

**Issue by rbirkgit** [mermaid-js/mermaid#3705]
**Describe the bug**
When running npm audit you get multiple high security warnings.

**To Reproduce**
Run npm /yarn audit.

**Expected behavior**
No security warnings

**Additional context**
This comes from dagre-d3 that uses a very old d3 version and where the security issues are coming from.

**Comment by CalebUsadi** [comment]
I submitted my first pull request. I've never done this before, so let me know if I've done anything wrong. Tests all run fine and I don't appear to have broken anything.
