### ISSUE TITLE
(chore) cSpell: How should it be used? what to ignore, what to add?

### ISSUE THREAD

**Issue by weedySeaDragon** [mermaid-js/mermaid#3749]
### Description

What are the guidelines for using cSpell?  
When should  terms should be added, and when should they be ignored?

What's the intention for adding cSpell?  A sentence or two as a comment at the top of the cSpell.json file would be helpful.

Every time someone adds new jsdoc parameters, won't the parameter names need to be added to cSpell.json?  (This may be OK.  If so, should they be added to the ignore list?)

I'd also suggest that both the `words` and `ignoreWords` lists be kept in alphabetic order so that the lists remain usable -- devleopers will quickly see exactly what words (including parameter names) have already been added that are spelled close to what they are adding. (Otherwise developers/contributer will have to read each and every entry.)

### Steps to reproduce

1. add new methods or constants and/or block documentation
2. note failures flagged by cSpell during linting
3. guess about which new terms should go into the `words` vs the `ignore` list

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by sidharthv96** [comment]
I had done a pass at formatting & sorting it. 

https://github.com/mermaid-js/mermaid/pull/3684/commits/3e76edcbac7659181a66be1a4a537a5d076dc5e7

I'm going through https://cspell.org/configuration/ and seems like ignoreWords shouldn't be used in our case.
Everything should be in words?

Raising a PR.
