### ISSUE TITLE
[Blocker v10] Redirect old doc links

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#3764]
### Description

There will be tons of links to mermaid docs across various sites. 
We should figure out a way to redirect the old URL's to new ones.

### Steps to reproduce

eg: https://github.com/mermaid-js/mermaid-live-editor/pull/1076

Although this is a different issue, it's still relevant. 

PS @emersonbottero

**Comment by fkohrt** [comment]
Just stumbled over the following broken link and thought it might be relevant for this issue:

https://github.com/mermaid-js/mermaid/blob/c8b377bf74a55b8fdfa3ed2af25987d6301346f9/packages/mermaid/src/docs/community/development.md#L9

The rendered documentation page containing the broken link is [here](https://mermaid-js.github.io/mermaid/#/development).

**Comment by spier** [comment]
It doesn't solve the issue of possibly having to redirect old URLs so that inbound links keep working.

However I have fixed some of the broken links, including the example provided by @fkohrt, as part of https://github.com/mermaid-js/mermaid/pull/3765.

**Comment by sidharthv96** [comment]
```
8.6.0_docs
Setup
Tutorials
accessibility
breakingChanges
c4c
classDiagram
configuration
cover
custom-navbar
demos
development
directives
entityRelationshipDiagram
examples
faq
flowchart
gantt
gitgraph
https://mermaid-js.github.io/mermaid/#/./Tutorials
https://mermaid-js.github.io/mermaid/#/./integrations
https://mermaid-js.github.io/mermaid/#/flowchart?id=special-characters-that-break-syntax
https://mermaid-js.github.io/mermaid/#/n00b-gettingStarted?id=_3-calling-the-javascript-api
https://mermaid-js.github.io/mermaid/landing/
integrations
language-highlight
markdown
mermaidAPI
mermaidCLI
mindmap
more-pages
n00b-advanced
n00b-gettingStarted
n00b-overview
n00b-syntaxReference
newDiagram
pie
plugins
quickstart
requirementDiagram
security
sequenceDiagram
stateDiagram
themes
theming
upgrading
usage
user-journey
```

These seem to be the possible links. I extracted it out from the markdown files.

`flowchart` would link to `https://mermaid-js.github.io/mermaid/#/flowchart` with possibility of id links like `https://mermaid-js.github.io/mermaid/#/flowchart?id=links-between-nodes`
