### ISSUE TITLE
ER diagram : add string length

### ISSUE THREAD

**Issue by yannmiquel** [mermaid-js/mermaid#3771]
### Proposal

It is useful to see the string length for the table definition. But one cannot use the parenthesis in the erDiagram yet. Could the use of the parenthesis be added ?

**Comment by mahomedalid** [comment]
I am not familiar with the code, but is not a matter to change [this line](https://github.com/mermaid-js/mermaid/blob/f4bb978a8742f7ffca1bd7e65b4ad5ea1825ba4b/packages/mermaid/src/diagrams/er/parser/erDiagram.jison#L34)? 

from:

`<block>[A-Za-z][A-Za-z0-9\-_\[\]]*  return 'ATTRIBUTE_WORD'`

to:

`<block>[A-Za-z][A-Za-z0-9\-_\[\]\(\)]*  return 'ATTRIBUTE_WORD'`
