### ISSUE TITLE
Typescript compile error in mermaid.d.ts for import { type DetailedError } from './utils';

### ISSUE THREAD

**Issue by roharrin** [mermaid-js/mermaid#3776]
### Description

Trying to compile after importing mermaid into a component fails with 

```
Error: node_modules/mermaid/dist/mermaid.d.ts:7:10 - error TS2614: Module '"./utils"' has no exported member 'type'. Did you mean to use 'import type from "./utils"' instead?

7 import { type DetailedError } from './utils';
           ~~~~


Error: node_modules/mermaid/dist/mermaid.d.ts:7:15 - error TS1005: ',' expected.

7 import { type DetailedError } from './utils';
```

If I manually change this from
import { type DetailedError } from './utils';
to
import type { DetailedError } from './utils';
it works.  But it's an npm package so I need it updated in the repo.

### Steps to reproduce

Install angular
ng new mermaid-test
yes to routing

npm i mermaid

in app.component.ts add 
import mermaid from 'mermaid';

ng serve

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by sidharthv96** [comment]
Which Typescript version are you using?

**Comment by roharrin** [comment]
Installed 4.8.4
In angular dev dependencies ~4.3.5

That was it.  I've updated to 
"typescript": "~4.6.4"
and build passes now.

Thanks.
