### ISSUE TITLE
Flowchart cannot display the string "\n"

### ISSUE THREAD

**Issue by mnlin0905** [mermaid-js/mermaid#3786]
### Description

Due to actual needs, the flowchart needs to display the string "\n";
But no matter what way I do it, "\\" and "n" don't show up together；

### Steps to reproduce

I've tried various combinations and I can't find it to display correctly：

```html
  <div class="mermaid">
    flowchart TB
    1-2(["Start\n"])
    2-3(["Start\\n"])
    3-4(["Start\\\n"])
    4-5(["Start\\nn"])
    5-6(["Start\\\nn"])
    6-7(["Start&#92;&#110;"])
    7-8(["Start&#92;&#92;&#110;"])
    8-9(["Start&#92;&#110;&#110;"])
  </div>
```

### Screenshots

This is the result of the page rendering：
![image](https://user-images.githubusercontent.com/17874282/201306668-ec9a9898-cc5a-4a8b-a35c-f2a90efe60ea.png)

This is the result of live-editor rendering：
![image](https://user-images.githubusercontent.com/17874282/201306995-736fd590-6c58-4f95-a427-efd67b61545c.png)

### Setup

**Desktop**

- OS and Version: Windows
- Browser and Version: Chrome  105.0.5195.102 （64）

**Comment by jgreywolf** [comment]
If you surround the text with backticks (`) instead of double quotes, it works as expected.
