### ISSUE TITLE
Tilde for internal visibility gets turned into an angle bracket

### ISSUE THREAD

**Issue by MelGrubb** [mermaid-js/mermaid#3795]
### Description

Since the introduction of using the tilde to mark generic parameters, I can no longer use it to mark internal (assembly) visibility for methods and parameters. "~InternalProperty" gets displayed as "<InternalProperty". I understand why generics couldn't simply use the regular angle brackets, but why was the tilde chosen as the delimiter when it already had a meaning? 

According to the docs, the tilde is supposed to be used to mark members with internal visibility. If generics can be made to use some other format (perhaps curly braces? e.g. List{int}), then we need a way to either escape or replace the tilde as the marker for internal visibility.

### Steps to reproduce

View this snippet in Mermaid. Sorry, I can't get it to NOT show the diagram, even if I block quote it, so I've removed the "mermaid" from the opening of the code block, but this snippet generates the following screenshot.

```
classDiagram
	class Person {
		+Id : Guid
		+FirstName : string
		+LastName : string
		-privateProperty : string
		#ProtectedProperty : string
		~InternalProperty : string
	}
```

### Screenshots

![image](https://user-images.githubusercontent.com/1153287/201678229-251b0be9-ad69-4f09-89de-21c4473fc619.png)

### Setup

**Desktop**

- OS and Version: Windows 11
- Browser and Version: Microsoft Edge, although I noticed the problem win Obsidian markdown editor as well as in the Visual Studio extension "Markdown Editor v2" by Mads Kristensen.

**Comment by sidharthv96** [comment]
Generics should only work when added in pairs. This is a bug.
