### ISSUE TITLE
mindmap: configuration directive breaks rendering

### ISSUE THREAD

**Issue by McShelby** [mermaid-js/mermaid#3815]
### Description

If a mindmap is preceeded with a configuration directive, the graph will not be rendered.

As a minor thing, even if no configuration directive is given, leading line breaks will also cause the graph not to be rendered.

This can also be seen in the live editor.

### Steps to reproduce

Create a mindmap with configuration directive.

### Code Sample

```text
%%{init: {"theme":"forest"}}%%
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectivness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
```

### Setup

- Windows 11
- Any evergreen browser (FF, Chrome, Edge)

### Additional Context

Even if configuration directives are currently not supported for mindmaps, I'ld expect them to be silently ignored instead of not rendering the graph at all.

**Comment by oglops** [comment]
configuration directive stopped working for all the other graph types for me, is that happening for everyone ? I tried latest 033201ff1fd90b7049ddd14f2f12b61cb108173e still the same

**Comment by jgreywolf** [comment]
It looks like this is working in current version of mermaidJs (try live editor again)
