### ISSUE TITLE
Generalization relationship should be represented by a hollow triangle, not a solid one.

### ISSUE THREAD

**Issue by hsolbrig** [mermaid-js/mermaid#3816]
### Description

According to section **9.2.4.2 Other elements** in [the UML 2.5.1 Specificatiion](https://www.omg.org/spec/UML/2.5.1/PDF), 
A Generalization is shown as a line with a **hollow triangle as an arrowhead** between the symbols representing the involved Classifiers. The arrowhead points to the symbol representing the general Classifier. 

The models on the [Mermaid webpage](https://mermaid.live/edit#pako:eNptkc9OwzAMxl8l8omJ9QWqXRBjEgdOu6FIyE1MFzVxIH80wdi7k3Y0jI2c7J_zWZ_tAyivCVpQFmNcG-wDOsmivDs2Dq1YfTWNWGc1XNONibtr-kxdwD-4FbeGk8CeLvE2BcO96Ik1hfPiKIlP6Ep4s7goOEw0w8n2ZO9wAqI27QiHe299qIW4N24WlvQ9oxrm_Hjebxys9mtG79F80iNviFLFCvkB07_6aQW_hjrvrTDxZW-srjBkrlpYgqPg0OhyiUknIe3IkYS2hJpeMdskQfL4FXPy2w9W0KaQaQn5TZeN_NzuBI_fJHSQVA) are drawing them as solid.

### Steps to reproduce

Draw any subclass relationship.

### Screenshots

![image](https://user-images.githubusercontent.com/415926/202822434-627be01a-8e07-4a8a-b387-1ebc97b1bdb5.png)

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by tushar-c23** [comment]
Hi, I'm Tushar Choudhary, a computer science undergrad from India. I would like to contribute to the project and solve this issue. The codebase of the project and the issue seems to be in the purview of my knowledge.
How should i get started?

**Comment by tushar-c23** [comment]
@jgreywolf Sure! I am still interested in taking this. Please guide me how to get started with this and i'll be on my way
