### ISSUE TITLE
broken output in docs for class diagram

### ISSUE THREAD

**Issue by maliberty** [mermaid-js/mermaid#3824]
### Description

When visiting https://mermaid-js.github.io/mermaid/#/classDiagram I see errors like:
![image](https://user-images.githubusercontent.com/761514/202912742-737b40fc-be6f-44f6-bbee-6385ea8db459.png)

### Steps to reproduce

As above

### Screenshots

As above

### Setup

**Desktop**

- OS and Version: Windows
- Browser and Version: Chrome Version 107.0.5304.107 (Official Build) (64-bit)

**Comment by weedySeaDragon** [comment]
Whomever works on this:  I suggest that you put the failing diagrams (the diagram text) into a test so it doesn't happen again.  :-)

**Comment by jgreywolf** [comment]
Closing as this appears to have been resolved when looking at documentation today
