### ISSUE TITLE
Refactor duplicated code diagram svgDraw files

### ISSUE THREAD

**Issue by weedySeaDragon** [mermaid-js/mermaid#3826]
### Description
There are many versions of `svgDraw` in the individual `diagrams/`

Refactor code common to all diagrams into a separate .js file in `diagrams/common/svgDraw`.

This will help reduce the overall package size (in addition to all the benefits of DRY).

### Steps to reproduce

compare the files (esp `diagrams/c4/svgDraw` and `diagrams/sequence/svgDraw`

**Comment by sidharthv96** [comment]
SvgDraw does take up significant portions of our bundle. jison files are the biggest overall, I think.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/10703445/202926064-61e20108-0faf-40e3-8694-39e54fe9ffcd.png">

**Comment by weedySeaDragon** [comment]
The jison files are definitely biggest, but this would be really easy first step. :-)

**Comment by sidharthv96** [comment]
Yes, replacing/optimizing jison is not at all an easy task.

**Comment by jgreywolf** [comment]
Investigating
