### ISSUE TITLE
Activation not working in sequence diagrams

### ISSUE THREAD

**Issue by jfontsaballs** [mermaid-js/mermaid#3849]
### Description

Activation does not show. Arrow does offset to make room for activation lane.

### Steps to reproduce

See code sample and screenshots

### Screenshots

![imagen](https://mermaid.ink/img/pako:eNpNjjEKwzAQBL8iro3zARWGmLSp0qo5pI0tsKREOhXG-O-RYwy5arlZllnJJgfSVPCpiBZ3z2PmYKJqd1PXvr-oQWlVUoBMPo4HGXbS-B9QmAuoo4Ac2Lu2ue5dQzIhwJBu0eHFdRZDJm6tylXSc4mWtOSKjurbsZwK5xPOS8qPQ_Nnu30Bh5U7Lg?type=png)

https://mermaid.ink/svg/pako:eNpNjjEKwzAQBL8iro3zARWGmLSp0qo5pI0tsKREOhXG-O-RYwy5arlZllnJJgfSVPCpiBZ3z2PmYKJqd1PXvr-oQWlVUoBMPo4HGXbS-B9QmAuoo4Ac2Lu2ue5dQzIhwJBu0eHFdRZDJm6tylXSc4mWtOSKjurbsZwK5xPOS8qPQ_Nnu30Bh5U7Lg

### Code Sample

```text
sequenceDiagram
    A ->>+ B : something
    B ->> A : something else
```

### Setup

Mermaid live 9.2.2 and also on Obsidian 1.0.3

**Comment by jfontsaballs** [comment]
It renders when you deactivate it. This works:

```
sequenceDiagram
    A ->>+ B : something
    B ->>- A : something else
```

**Comment by ultimate-deej** [comment]
I faced the same issue. Is it the intended behavior?
I need to create a diagram where some actors do not deactivate. I'd expect the bar to be visible and continue all the way to the bottom.

**Comment by ckhiu** [comment]
I would also like to see that the actors remain activated until the bottom without the need to deactivate it.
