### ISSUE TITLE
Change direction of erDiagram

### ISSUE THREAD

**Issue by domeniczz** [mermaid-js/mermaid#3851]
### Proposal

We can't change the direction of ER Diagram now, the default direction is Top to Bottom

For example the following code

Using keyword "direction" to adjust the direction

### Example

```
erDiagram
  direction LR
  USER {
    int id PK
    string nicname
    int age
  }
  DESC {
    int id PK
    string city
  }
  USER ||--|| DESC : "1-1"
```

**Comment by hunsnowboarder** [comment]
Still no change for this basic feature requirement? :(

**Comment by domeniczz** [comment]
> Still no change for this basic feature requirement? :(

Absolutely, seems nobody is caring about this issue.

**Comment by fedegonzal** [comment]
Some update here?

**Comment by yari-dewalt** [comment]
> Some update here?

The direction statement is being supported for ER diagrams in the new update, as well as other anticipated features! #5965

**Comment by christopher-merry** [comment]
@yari-dewalt That's awesome!  Any idea on timeline?  Looks like it's close?
