### ISSUE TITLE
Syntax Error in Rendering Class Diagrams

### ISSUE THREAD

**Issue by MateiMitran** [mermaid-js/mermaid#3867]
### Description

I have created a NextJS app with a markdown textbox that on pressing the button, it would render MermaidJS syntax into a diagram using the Mermaid renderer on a card. Some diagrams I have created work and some do not. There is no syntax error and the diagrams do render in the top left of the card. This environment works perfectly locally but behaves like this in production.
I'm running Mermaid version 9.0.0 .

### Steps to reproduce

1. Create NextJS app with markdown textbox that renders mermaid ( mermaid version 9.0.0 )
2. Run npm build and npm start to test it in production
3. Input different class diagrams with at least one relation and try to render. Some work some do not

### Screenshots

![image](https://user-images.githubusercontent.com/92087351/204543234-c2064a3e-98eb-466f-bdd8-aa13e0767e67.png)
![image](https://user-images.githubusercontent.com/92087351/204544315-050a3e7f-00ec-421a-a836-fcf59821e20d.png)

### Code Sample

```text
// Mermaid renderer component
export interface MermaidViewerProps {
    chart: string;
}
export default function MermaidViewer(props: MermaidViewerProps) {
    useEffect(() => mermaid.contentLoaded(), []);
    mermaid.initialize({
        startOnLoad: true,
    });
    return <div className="mermaid">{props.chart}</div>;
}
```

### Setup

**Desktop**

- OS and Version: [Windows 10]
- Browser and Version: [All]

### Additional Context

Running mermaid 9.0.0

**Comment by MateiMitran** [comment]
nump

**Comment by jgreywolf** [comment]
@MateiMitran Have you tried this with version 10.x?
