### ISSUE TITLE
Github mermaid support vs Mermaid Live Editor

### ISSUE THREAD

**Issue by ShahOdin** [mermaid-js/mermaid#3879]
### Description

The following diagrams

```
erDiagram
    CUSTOMER {
        Array[string] name
    }
```
or 

```
erDiagram
    CUSTOMER {
        string[] name
    }
```

both display fine on Markdown live but fail to render on github.

### Steps to reproduce

try to embed the above code examples on github.

### Code Sample

```text
erDiagram
    CUSTOMER {
        Array[string] name
    }
```

### Setup

N/A

**Comment by jgreywolf** [comment]
We do not have any control over what version of mermaid github is using. So there will be, most likely, differences between versions
