### ISSUE TITLE
network diagrams, recommended way?

### ISSUE THREAD

**Issue by ds2345** [mermaid-js/mermaid#3885]
### Proposal

it would be useful to have a dedicated type of diagrams for network / cloud design / architecture 

in the meantime, what would be recommended type existing diagrams to use 

in addition, how to correctly utilize existing icons, i.e. in form of SVG images, on mermaid.js diagrams?

there are examples for using font-awesome icons, but there are many more network specific svg and png images available.
[aws architecture icons](https://aws.amazon.com/architecture/icons/)

### Use Cases

here is one example of network diagram
[AWS ECS](https://aws.amazon.com/blogs/containers/developing-twelve-factor-apps-using-amazon-ecs-and-aws-fargate/)

### Screenshots

![aws ecs](https://d2908q01vomqb2.cloudfront.net/fe2ef495a1152561572949784c16bf23abb28057/2021/04/28/Blog-Architecture-Page-1.png)

**Comment by jgreywolf** [comment]
Closing in favor of #1227
