### ISSUE TITLE
Neural Networks

### ISSUE THREAD

**Issue by ccorcos** [mermaid-js/mermaid#39]
YES! this is amazing. I've been thinking about this for a while. Any thoughts one how to make neural network pictograms? 

For example

![](http://colah.github.io/posts/2014-03-NN-Manifolds-Topology/img/example_network.svg)

**Comment by FavorMylikes** [comment]
does not work @vijay40 , @knsv

**Comment by gnzlbg** [comment]
I disagree, the lines aren't currently straight as in the picture that @ccorcos showed. One can try to use: `linkStyle default interpolate basis` to improve things a bit, but it still looks quite bad.

**Comment by gnzlbg** [comment]
Without inline math, and without straight lines, this is kind of the best that I'm able to make a neural network look like:

![Screen Shot 2020-06-21 at 12 32 41](https://user-images.githubusercontent.com/904614/85222452-5d12f080-b3bb-11ea-9a7e-45ec3c70e4a3.png)

but they should look more like this: 

![Screen Shot 2020-06-21 at 12 33 48](https://user-images.githubusercontent.com/904614/85222465-7ddb4600-b3bb-11ea-924d-13c558c6e1b1.png)
