### ISSUE TITLE
GitHub Pages documentation 404ing 

### ISSUE THREAD

**Issue by JohnPaton** [mermaid-js/mermaid#3912]
### Description

When I try to navigate to the [documentation](http://mermaid-js.github.io/mermaid/) linked in the sidebar, I get a 404

### Steps to reproduce

1. [Click here](http://mermaid-js.github.io/mermaid/)
2. That's it

### Screenshots

<img width="700" alt="image" src="https://user-images.githubusercontent.com/18459252/207838875-1e82ca7f-48e1-4e43-a35a-745beeb99396.png">

### Setup

**Desktop**

- OS and Version: Mac 12.6
- Browser and Version: Chrome

**Comment by sidharthv96** [comment]
Aware of the issue. We're looking into the root cause.
The page loads randomly when refreshing firefox & chrome for me, but not in safari. 

Meanwhile, https://mermaid-js.github.io/mermaid/intro/ works.

**Comment by sidharthv96** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/10703445/207843828-f7197c3e-0de1-4d5e-b9b7-a5cf08345c10.png">

Loads after few refreshes. 
Maybe a caching issue?

**Comment by sidharthv96** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/10703445/207845262-c9515f31-c51c-4555-96a7-19118c64d843.png">

Loads every time with caching disabled.

even `curl https://mermaid-js.github.io/mermaid/` works.

**Comment by sidharthv96** [comment]
Redeployed. Working now.
Thanks for reporting :)

**Comment by JohnPaton** [comment]
Thanks for checking it out!
