### ISSUE TITLE
A required parameter cannot follow an optional parameter.

### ISSUE THREAD

**Issue by andreage** [mermaid-js/mermaid#3913]
### Description

`export function interpolateToCurve(interpolate?: string, defaultCurve: CurveFactory): CurveFactory {`

this gives me:

error TS1016: A required parameter cannot follow an optional parameter.

Is it something that can be changed or should I try to suppress error TS1016 somehow?

Thank you.

### Steps to reproduce

`export function interpolateToCurve(interpolate?: string, defaultCurve: CurveFactory): CurveFactory {`

this gives me:

error TS1016: A required parameter cannot follow an optional parameter.

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by sidharthv96** [comment]
We have a `// @ts-nocheck : TODO Fix ts errors` in src/utils.ts which is suppressing this error for us.

You can use the  `"skipLibCheck": true /* Skip type checking all .d.ts files. */` compileroptions in your tsconfig to skip type checking of your dependencies until the issue is resolved.
