### ISSUE TITLE
Maybe erDiagram entities cannot have spaces in their names?

### ISSUE THREAD

**Issue by aj-stein-nist** [mermaid-js/mermaid#3931]
### Description

I have found a workaround, and I am not very confident but this seems generally similar to mermaid-js/mermaid#1895, but when I have an erDiagram like the one below I get syntax errors with an oldish 8.x version of the library.

```mermaid
erDiagram
  "metaschema definition" }|..|{ "instance" : "must specify model of"
  "metaschema tool" }|..|{ "metaschema definition" : "must parse"
  "metaschema tool" }|..|{ "instance" : "can parse"
  "metaschema tool" }|..|{ "schema" : "can generate"
  "schema" }|..|{ "instance" : "must validate"
```

Not exactly the "right" answer, but oddly when I add another space to between the `erDiagram` declaration and the diagram content, this issue goes away with 9.3.0 release on Cloudflare.

```
erDiagram

  "metaschema definition" }|..|{ "instance" : "must specify model of"
  "metaschema tool" }|..|{ "metaschema definition" : "must parse"
  "metaschema tool" }|..|{ "instance" : "can parse"
  "metaschema tool" }|..|{ "schema" : "can generate"
  "schema" }|..|{ "instance" : "must validate"
```

This workaround I assume is not correct. Is this a bug, am I missing something? It works [in the original way](https://mermaid.live/edit#pako:eNqNkc8KgzAMh1-l5Dx8gJ73Brt6CW10hf6RNh2I-u6Lc4hsbHhNvt-XpJ3AJEuggfLVYZ8xtFGpFgIxFnOngMpS56Jjl2ILapmbZp4EcLEwRkNS0ytfC6sykHHdqIIovUpdC18yTskfNb_m7M4Bc6EToo99DMbT0a18CPYUKSPv2R34e_0DvbOvFFxkXA7orDzstDlYFNJaaTkUq-fVvgiKldNtjAY050oXqMNqef8G6A59oeUJa1OQTg) and [the workaround way](https://mermaid.live/edit#pako:eNqNkcEKwjAMhl-l5Cw-wM6-gddeQpfNQpuONhVk27ubOhmiKF6T7_-StDO41BN0QPnkccwYLVs2xkIkweIuFNH0NHj24hNbMOtyPC6zAp6LIDvSWtf4WsSUiZwfbiaqNJg0WPiQSUrhVfNtzu6cMBf6Q_S2j0P-O7qVX4IjMWWUPbsDP6-_YvD9IwUHHZcj-l6fdt4cogptNVoPxRqk2VdFsUo639hBJ7nSAerULM__gG7AUGi9A7lqkRg) so I am somewhat confused and not sure my bug analysis or the fact it is a bug is correct.

### Steps to reproduce

See above, if a simple repro is needed let me know. Originally reported to usnistgov/hugo-uswds#25 and copy-pasted here to collab more easily.

### Screenshots

If applicable, I can screenshot the hugo theme and the context of the fix, but that likely is much larger than you all would want.

### Code Sample

```text
erDiagram
  "metaschema definition" }|..|{ "instance" : "must specify model of"
  "metaschema tool" }|..|{ "metaschema definition" : "must parse"
  "metaschema tool" }|..|{ "instance" : "can parse"
  "metaschema tool" }|..|{ "schema" : "can generate"
  "schema" }|..|{ "instance" : "must validate"
```

### Setup

**Desktop**

- OS and Version: Ubuntu 22.04 LTS
- Browser and Version: 108.0.1 (64-bit)

**Comment by aj-stein-nist** [comment]
Is there anything I can do to help troubleshoot this, confirm the bug, and propose a possible code change? Thanks!

**Comment by weedySeaDragon** [comment]
@aj-stein-nist Is this still a problem in the current version?  
I can't reproduce the error.

**Comment by aj-stein-nist** [comment]
You are right, I just tested on mermaid.live many moons later and it looks like this not an issue anymore. Thanks for your due diligence!
