### ISSUE TITLE
Using MermaidAPI.parse() method in the backend

### ISSUE THREAD

**Issue by MateiMitran** [mermaid-js/mermaid#3934]
### Description

When I import mermaid and try to use the parse() method from mermaid.mermaidAPI.parse() in the backend, I get an error that the DOM is not sanitized. Is there a way to use this method or the parser.yy property in the backend? I am using mermaid 9.0.0 in typescript.

### Steps to reproduce

1. Use mermaid.mermaidAPI.parse().parser.yy in the backend of a project

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by sidharthv96** [comment]
We do not support Server-side rendering yet.

Duplicate of https://github.com/mermaid-js/mermaid/issues/3650

**Comment by matthewhausman** [comment]
Don't worry - I patched the mermaid package to enable parse to work on the server side. Not all of the validation logic is in the parse function so this won't even be a functional solution. We must call parse and render to fully validate the diagram

**Comment by sidharthv96** [comment]
@matthewhausman would be happy to have a look at implementing at least parsing via grammar in server side without the full validations, if you can raise a PR from your patch.
