### ISSUE TITLE
How to add newline in the text in classDiagram mode

### ISSUE THREAD

**Issue by daichenghe** [mermaid-js/mermaid#3958]
### Description

The #384 issue suggest use <br/>
but it does not work in classDiagram mode

### Steps to reproduce

my code:
rtk Engine: static void copy_ins_sol <br/>(const insaid_solution_t* ins_data, gnss_insaid_sol_t* insaidsol)

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by jgreywolf** [comment]
In class diagram you can use \n where needed (surround the name in backticks``)

classDiagram
    Animal <|-- `Du\nck`
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class `Du\nck`{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }
