### ISSUE TITLE
Mindmap not rendering in Github

### ISSUE THREAD

**Issue by jintolonappan** [mermaid-js/mermaid#3963]
### Description

Mindmap is failing to render at github with error message:

```
Unable to render rich display

Parse error on line 1:
mindmap root((mind
^
Expecting 'open_directive', 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'

For more information, see https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
```

I tried all the sample code from Mermaid Live Editor and the issue is appears to be only with Mindmap. All other type of diagrams are working/ rendering

### Steps to reproduce

1. Create a markdown file in github
2. Add mindmap sample code from live editor to the md with `mermaid` syntax
3. Commit code
4. Error is displayed in github/ browser

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by sidharthv96** [comment]
Mindmap is an external experimental diagram for now. So, GitHub might not have added it into their build. 
There's not much we can do here.
