### ISSUE TITLE
Render fails with this flowchart

### ISSUE THREAD

**Issue by mmenzyns** [mermaid-js/mermaid#3981]
### Description

This graph makes the rendering fail (in live editor, the preview goes blank). I simplified the graph, to the point when you try to change almost anything in the graph, it will appear again.

Such as:
- switch starting node from `start-->A` to `start-->AA`
- switch from `AA-->AB3` to `AA1-->AB3`

Doesn't seem that direction matters.

### Steps to reproduce

1. Try to render provided code on mermaid live editor or vscode with mermaid addon
2. Bug

### Code Sample

```text
https://mermaid.live/edit#pako:eNplUE1vhCAQ_Stmzq5BsKgcmmD2uqf21HChgtVEwbCYdmv87wVNs_2Yy8x78_LmZVZordLAoBvte9tL55PnRpgk1HV5fXNy7hN-4N_cDzIW5_md0EYdYB_-uDV3HW_If52PGU6nx--znB8oaiGFSbtJDiokXuNegO_1pAWwMCrdyWX0AoTZglQu3j7dTAvMu0WnsMxKen0eZAgyAevkeA3sLA2wFT6A5YhmiOKyKPIi9IcUbpHMM1xThKuclBiViGwpfFobDFBGES2rqsKkritSl3R3e9mXx0mtBm_d5Xjx_untC2uCaNM

flowchart TB
    subgraph A
        subgraph AA
            AA1
        end
    end
    subgraph B
        AB3
    end
    start --> A
    AA --> AB3
```

### Setup

**Desktop**

- OS and Version: macOS 13.1
- Browser and Version: Firefox 108.0.2

### Additional Context

I believe anyone should be able to reproduce this issue anywhere.

**Comment by jgreywolf** [comment]
It looks like it is the nested subgraph AA that is causing the problem

**Comment by nirname** [comment]
Closing this in favor of #4644, please refer to the new issue. It is a error that comes across different issues.
