### ISSUE TITLE
Is there markdown-it support for mermaid?

### ISSUE THREAD

**Issue by IdeoG** [mermaid-js/mermaid#3998]
**Is your feature request related to a problem? Please describe.**
As a user I want to render mermaid code to image in markdown.

**Describe the solution you'd like**
I have a link to a repository with markdown-it-mermaid code. So, I can install it and use it in my project:
`npm i markdown-it-mermaid`

**Describe alternatives you've considered**

**Additional context**

**Comment by sidharthv96** [comment]
Currently we need a browser environment to render charts.
Maybe once we have [node rendering support](https://github.com/mermaid-js/mermaid/issues/3650), we could release a plugin.

**Comment by IdeoG** [comment]
Thank you!
