### ISSUE TITLE
Provide parser as separate module

### ISSUE THREAD

**Issue by RangerMauve** [mermaid-js/mermaid#4]
I really like the syntax you've made, and I think it could have applications outside the graph rendering stuff. It'd be nice if you provided a parser for the graph itself as a separate module.

**Comment by KarolisKaj** [comment]
Sorry for bringing it up after such a long time but I believe answer is a bit outdated. Would it be possible to provide an up to date example of extracting object graph of mermaid code, as it was originally requested in this post?

**Comment by tylerlong** [comment]
The code is till pretty correct except you need to adjust the require statements because files has been moved.

**Comment by KarolisKaj** [comment]
@tylerlong Thanks for you reply. I have managed to make it work :)

**Comment by Sigfried** [comment]
I had to change 

    import graph from 'mermaid/src/diagrams/flowchart/graphDb'

to

    import graph from 'mermaid/src/diagrams/flowchart/flowDb'

**Comment by SuperCuber** [comment]
@knsv I'm also interested in this. How would I import this from a yarn project?
