### ISSUE TITLE
Entity Relationship: new syntax to allow attribute to be PK and FK at the same time

### ISSUE THREAD

**Issue by RamanDamayeu** [mermaid-js/mermaid#4009]
### Proposal

According to the documentation for Entity Relationship Diagrams we could add a `key` property to attributes and keys can be "PK" or "FK", for Primary Key or Foreign Key. 

I would propose to add "PK/FK" or "PK,FK" to the chose as there is no restriction from modeling point of view that I know about for an attribute to play role of Primary Key **and** Foreign Key at the same time.

### Example

In the following example CUSTOMER_STATUS.customer_number is a part of Primary Key for CUSTOMER_STATUS and also points to CUSTOMER.customer_number so plays the role of Foreign Key.

```
CUSTOMER {
		int customer_number PK
		string first_name
		string last_name
}

CUSTOMER ||--|{ CUSTOMER_STATUS : has_status
CUSTOMER_STATUS {
		int customer_number PK/FK
		datetime customer_status_start_datetime PK
		datetime customer_status_end_datetime
		string customer_status
}


### Screenshots

_No response_

**Comment by tomperr** [comment]
Good idea, I will take a look
