### ISSUE TITLE
Mindmap: Differentiate the color between the root node and the level 1 node

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#4016]
### Description

The the root node and the first section shares the same color. This is confusing, the colors of these levels should be different.

### Steps to reproduce

```
mindmap
  A
     B
```

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by Yokozuna59** [comment]
it's have been resolved in #4018, not really sure why github didn't resolved the issues when pr was merged.
