### ISSUE TITLE
Mermaid diagrams on GitHub should be zoomable and scrollable.

### ISSUE THREAD

**Issue by polina-c** [mermaid-js/mermaid#4022]
### Description

This is example of diagram that would be much easier to read, if it was zoomable and scrollable:
https://github.com/polina-c/flutter/blob/diagrams/packages/flutter/lib/src/foundation/DEPENDENCIES.md

### Steps to reproduce

![Screenshot 2023-01-21 at 6 59 07 PM](https://user-images.githubusercontent.com/12115586/213894713-56197c0a-341e-44b4-943e-4351f4aa7585.png)

**Comment by polina-c** [comment]
I like it! Thank you.

**Comment by polina-c** [comment]
I do not see scroll bars on the image. Will they show up if diagram stops fitting the screen?

**Comment by jgreywolf** [comment]
This is not something that is currently able to be done via mermaid, and would need to be done outside of the library, such as how the live editor is working now

https://mermaid.live/
