### ISSUE TITLE
Image stop rendering after 9.1

### ISSUE THREAD

**Issue by emersonbottero** [mermaid-js/mermaid#4023]
### Description

When using only an img tag the img is not rendered
It used to work before.

### Steps to reproduce

https://mermaid.live/edit#pako:eNpNUU1TpDAQ_StUX9QqYIYA4WNXLXfHoyc9KXvoIQGyQkIlYXbHKf67YcZRc-r0637vdfcBasU4lND06l_dobbe06aSnnu_Xn6KofWMrq8vOmtHU65WA9cDChb-NaHS7fkb9KpVodm1Fzee5oPa8WDgfz5YguDm90uDZYPBFqXXKL0VjHH5Dd9cnnAzCim5vvrxBd1f3nknsEanhoHmVitv5LrD0dxegQ8fJtwMh6WvAtvxgVdQupChfq2gkrOrm0aGlt8zYZUGx9gb7gNOVj3uZQ2l1RM_F20EthqHzyp-bHo4beq4MB9GlFAe4D-UNA5JmkQkoSnNSJbnPuyhJHEaFkVCSLGOoiglSTL78KaUY12HeU6SNKckIyQuaJ760CtkXC-Mdj8uMq0w1snUSjaiXfKT7l36fIkFDlthu2kb1mpYGcGW63W7gq4ooTmSmNMsxjSOWb2NirwhSdSwbB0RhHk--n8-ulkGn98BKuijPQ

### Screenshots

![image](https://user-images.githubusercontent.com/12377432/213905624-5953764e-30ae-491b-a677-e6b9bd0f0e56.png)

with some text together... 
![image](https://user-images.githubusercontent.com/12377432/213905634-b2c7600d-fee4-4706-8fd1-a01ea7cf6233.png)

this broke my vitepress plugin.. 
from mermaid.render
![image](https://user-images.githubusercontent.com/12377432/213905664-f9fb30e1-2013-46a6-913a-8f688fa5510e.png)
to mermaid.renderAsync
![image](https://user-images.githubusercontent.com/12377432/213905700-27d39da2-224e-43ba-803d-9e51bf21ae8d.png)

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by Valentine14th** [comment]
@sidharthv96 @knsv Hello, I'm an enthusiastic user of mermaid and I would love to start contributing to this project by looking into this bug first!

**Comment by streepvaren** [comment]
Dear all,

As @emersonbottero does, I'm also encountering problems with rendering nodes containing images. 

I noticed two things:

**1. Mermaid Live Editor renders image containing nodes randomly**
This code:
```
flowchart TB 
SPECIES1("<img src='https://waarnemingen.be/media/photo/38346151.jpg' /> Drosera rotundifolia")
SPECIES2("<img src='https://waarnemingen.be/media/photo/38346124.jpg' /> Drosera intermedia")
HAIRS(Petiole hairy?)
HAIRS--Yes-->SPECIES1
HAIRS--No-->SPECIES2
```
Sometimes renders correctly (images & node text visible):
![LiveEditor_OK](https://user-images.githubusercontent.com/63158718/224810759-53515dbe-c28e-4aa1-a805-afb9c8ff2561.jpg)

But can looks like this after refreshing the Mermaid Live Editor:
![Live_Editor_WRONG](https://user-images.githubusercontent.com/63158718/224810798-f9a5e198-f03d-408a-8aa1-eb988699ffb5.jpg)

**2. Nodes containing images stopped working recently in Quarto (R)**
Images are not visible in Quarto's HTML output:
![QuatroHTML](https://user-images.githubusercontent.com/63158718/224810774-20f10dce-bfb1-4f32-a6dc-bf9391c8f547.jpg)

This is also the case when rendering to PDF:
![QuatroPDF](https://user-images.githubusercontent.com/63158718/224810789-fcefb6dc-62e7-4fd5-9788-9bff705c174f.jpg)



**It would be really great for biologists to be able to use Mermaid for easily creating flexible identification tools like these:**

![VB1](https://user-images.githubusercontent.com/63158718/224814501-47e678da-88ce-41bb-a022-1cb3016cf66e.png)
_(From: Moisan, J. (2010). Guide d'identification des principaux macroinvertébrés benthiques d'eau douce du Québec, 2010: surveillance volontaire des cours d'eau peu profonds. Développement durable, environnement et parcs Québec.)_


![VB2](https://user-images.githubusercontent.com/63158718/224816706-acbd0e45-f6a8-46ff-bcc1-1f78b38e4b52.jpg)
_(From: Köhler, G. (Ed.). (2014). Müller/Bährmann Bestimmung wirbelloser Tiere: Bildtafeln für zoologische Bestimmungsübungen und Exkursionen. Springer-Verlag.)_


Keep up the good work!

Best regards,
Streepvaren

**Comment by jgreywolf** [comment]
@Valentine14th Please confirm that you are still interested in working on this, and I will assign to you!

**Comment by jgreywolf** [comment]
I totally missed that.  I just went through and reviewed

**Comment by emersonbottero** [comment]
hi all, this is not fixed.. should I open another Issue?

**Comment by streepvaren** [comment]
Indeed, it is only partly fixed.

When using:
- Windows 11
- R 4.3.1 (latest)
- R studio Version: 2023.06.1+524 (latest)
- Quarto CLI 1.4.226 (pre-release)


Example:
```
{mermaid}
flowchart LR
test_node_with_image("<img src='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'> Google Logo")
test_node_with_image--->test_node_without_image
```

Rendering this containing Mermaid scripts **as HTML works perfectly** and gives this output:
![image](https://github.com/mermaid-js/mermaid/assets/63158718/7a0e3de4-c880-494d-a664-956928d0e05a)


Rendering **as PDF gives this error**:

```
ERROR: Mermaid generated an SVG without a viewbox attribute. Without knowing the diagram dimensions, quarto cannot convert it to a PNG

Stack trace:
    at resolveSize (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:63711:19)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async makePng (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64033:57)
    at async makeDefault (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64085:24)
    at async Object.cell (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64108:20)
    at async Promise.all (index 0)
    at async Object.document (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:39841:25)
    at async handleLanguageCells (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:39812:42)
    at async file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:69487:53
    at async withTimingAsync (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:19401:25)
```

Best regards,
Streepvaren

**Comment by emersonbottero** [comment]
> Indeed, it is only partly fixed.
> 
> When using:
> 
> * Windows 11
> * R 4.3.1 (latest)
> * R studio Version: 2023.06.1+524 (latest)
> * Quarto CLI 1.4.226 (pre-release)
> 
> Example:
> 
> ```
> {mermaid}
> flowchart LR
> test_node_with_image("<img src='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'> Google Logo")
> test_node_with_image--->test_node_without_image
> ```
> 
> Rendering this containing Mermaid script **as HTML works perfectly** and gives this output: ![image](https://user-images.githubusercontent.com/63158718/253405054-7a0e3de4-c880-494d-a664-956928d0e05a.png)
> 
> Rendering **as PDF gives this error**:
> 
> ```
> ERROR: Mermaid generated an SVG without a viewbox attribute. Without knowing the diagram dimensions, quarto cannot convert it to a PNG
> 
> Stack trace:
>     at resolveSize (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:63711:19)
>     at eventLoopTick (ext:core/01_core.js:181:11)
>     at async makePng (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64033:57)
>     at async makeDefault (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64085:24)
>     at async Object.cell (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64108:20)
>     at async Promise.all (index 0)
>     at async Object.document (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:39841:25)
>     at async handleLanguageCells (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:39812:42)
>     at async file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:69487:53
>     at async withTimingAsync (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:19401:25)
> ```
> 
> Best regards, Streepvaren

Remove "Google Logo" Text on the left side and see if the image still shows.

**Comment by streepvaren** [comment]
Hi,

Indeed, also HTML-export is corrupt after adding an image containing node without text:

When using:

Windows 11
R 4.3.1 (latest)
R studio Version: 2023.06.1+524 (latest)
Quarto CLI 1.4.226 (pre-release) - 

Example:
```{mermaid}
flowchart LR

test_node_with_image_and_text("<img src='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'> Google Logo")

test_node_with_image_and_without_text("<img src='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'")

test_node_with_image_and_text--->test_node_with_image_and_without_text--->test_node_without_image

```

Rendering this Mermaid script **as HTML** gives this incomplete output:
![image](https://github.com/mermaid-js/mermaid/assets/63158718/4516c32a-e779-4cc3-b3d8-7a26c5bdcc85)


Rendering **as PDF** gives this error:

```
ERROR: Mermaid generated an SVG without a viewbox attribute. Without knowing the diagram dimensions, quarto cannot convert it to a PNG

Stack trace:
    at resolveSize (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:63711:19)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async makePng (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64033:57)
    at async makeDefault (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64085:24)
    at async Object.cell (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:64108:20)
    at async Promise.all (index 0)
    at async Object.document (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:39841:25)
    at async handleLanguageCells (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:39812:42)
    at async file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:69487:53
    at async withTimingAsync (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:19401:25)
```



Best regards,
Streepvaren

**Comment by emersonbottero** [comment]
should we open another Issue?

**Comment by streepvaren** [comment]
That would be great!
