### ISSUE TITLE
syntax error hiding nodes

### ISSUE THREAD

**Issue by kofifus** [mermaid-js/mermaid#4025]
### Description

My older flowchart which used styling for hiding nodes no longer works.

### Steps to reproduce

This 
```
graph TD
   
    A --- |"text"|h[ ]
    h --> B
 
    style h height:0px;
```

Fails with syntax error.
<br/>

Note that this:
```
graph TD
    
    A --- h[ ]
    h --> B
 
    style h height:0px;
```
works!

I know the first flowchart used to work in previous versions. What is wrong ? is there a better way to hide nodes ?

Thanks

### Setup

Tested in github and mermaid live editor

**Comment by nirname** [comment]
@kofifus Thanks for reaching out!

This works just fine in Github, in the latest (development) version of Mermaid and in the live editor as well.
Please, provide more details to reproduce the error.

**Comment by jgreywolf** [comment]
Closing due to lack of response/activity
