### ISSUE TITLE
underscore in class names not supported

### ISSUE THREAD

**Issue by mpusz** [mermaid-js/mermaid#403]
It seems that providing '_' sign in the class name (e.g. 'unique_ptr') causes class diagram parsing error or is not supported.

**Comment by ruipires** [comment]
I have also found the same issue. Could not find an alternative to specify the class name that would accept the underscore (tried specifying the class name in single and double quotes)

**Comment by J-Setzer** [comment]
As a workaround: Replace '`_`' (Underscore) by '` `' (Blank). 
This works for me. At least it does not break the class diagram.

**Comment by g3o2** [comment]
`'  '` (Blank) does not work for me.

Is there a syntax related reason that `_` is not supported ?

**Comment by depfryer** [comment]
hi 
any update please ?

**Comment by chris579** [comment]
@depfryer  Hi, you're commenting on an issue that has been closed because it went stale. Does this issue still exist? If so, please be so kind to reproduce it in our [live editor](https://mermaidjs.github.io/mermaid-live-editor) and provide the link to your repro. Thanks!

**Comment by jgreywolf** [comment]
This should be supported at least as of 8.4.2.  See link:  https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBDbGFzc18wMVxuQ2xhc3NfMDEgOiBpbnQgc29tZV9Qcm9wZXJ0eVxuQ2xhc3NfMDEgOiBTb21lX01ldGhvZCgpXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ
