### ISSUE TITLE
Remove redundant surrounding classbox from lollipop

### ISSUE THREAD

**Issue by mestaritonttu** [mermaid-js/mermaid#4037]
### Description

This is a continuation of #1145. As mentioned in #3311 there is still a classbox to be removed.

### Steps to reproduce

Check the class diagram demos, syntax is `Interface1 ()-- Interface1Impl`

**Comment by tomperr** [comment]
I am a little confused as to what is expected, as I don't really understand what has been done and what is yet to be implemented. Can you please give some explanations? Sorry if I am missing something obvious

**Comment by mestaritonttu** [comment]
> I am a little confused as to what is expected, as I don't really understand what has been done and what is yet to be implemented. Can you please give some explanations? Sorry if I am missing something obvious

See these examples of how it should look like:

https://www.uml-diagrams.org/realization.html

https://plantuml.com/class-diagram#8b64d7547fa4f699

At the head of the lollipop, there is only text, not a box. So in the Mermaid class diagram section in the demo page, Interface1, Animal and Fruit should not be inside a box.
