### ISSUE TITLE
Reference table for theme variables not working

### ISSUE THREAD

**Issue by acastro2** [mermaid-js/mermaid#4041]
### Description

This link points to a place that doesn't exist:

https://github.com/mermaid-js/mermaid/blob/60175cd84f986537cb187a84d2da203a5675cb8a/packages/mermaid/src/docs/config/theming.md?plain=1#L60

### Steps to reproduce

Go to https://mermaid.js.org/config/theming.html#theme-variables-reference-table

Click the link in the table.

### Screenshots

<img width="744" alt="image" src="https://user-images.githubusercontent.com/5918765/215250932-159b9a85-cadc-4edd-a000-d0b5ccaa4c74.png">

### Setup

**Desktop**

- OS and Version: [ Mac]
- Browser and Version: [Brave]

**Comment by theVJagrawal** [comment]
Can I work on this issue?

**Comment by huynhicode** [comment]
Thanks for reporting, @acastro2 !

Thanks for offering to work on the fix, @theVJagrawal ! 

The "see full list" text should route here: https://mermaid.js.org/config/theming.html#theme-variables

![Screen Shot 2023-01-30 at 10 54 24 AM](https://user-images.githubusercontent.com/35910788/215569000-16d33068-2d17-43f6-8ea6-8a50991ae5f2.png)

**Comment by jgreywolf** [comment]
> Can I work on this issue?

Go for it!

**Comment by ibrahimWassouf** [comment]
Hello, this is my first ever contribution to an open source project. Let me know if there is more I should do to ensure that this is merged, thanks!
