### ISSUE TITLE
Multi directional arrow support in sequence diagrams

### ISSUE THREAD

**Issue by pitecantropo** [mermaid-js/mermaid#4051]
### Proposal

I think a good addition to mermaid sequence diagrams would be Multi directional arrows, such as exist in mermaid's own  flowchart. This would allow illustration of to and from communication (sync between to elements).

### Example

<-->

### Screenshots

Found this example, this would currently not be possible to draw with mermaid because there are no Multi directional arrows
![image](https://user-images.githubusercontent.com/4513487/216280434-0784a39f-7ab9-4154-b4c8-50d8c2e738f6.png)

**Comment by Ronid1** [comment]
@jgreywolf Can you please assign me? would like to work on this

**Comment by nirname** [comment]
@Ronid1 no need to assign, welcome! Start the development, and open PR as soon as you can, make it draft if it is still in progress. But this will be attached to the issue and thus you share it with the community
