### ISSUE TITLE
Overlapping nodes in stateDiagram-v2

### ISSUE THREAD

**Issue by marcosh** [mermaid-js/mermaid#4053]
### Description

When I try to draw this diagram

```
stateDiagram-v2
state show {
    a
}
state length {
    c
}
show --> length
```

the `length` state completely overlaps the `show` one, as you can see in the [live editor](https://mermaid.live/edit#pako:eNpVjsFugzAQRH8FzRkQEBOwDzm1X9Bb5csKOwEF7MiYtCni3-uQECl72p15M9oZjVUaAqMnrz86OjkakmshzSpEY2t_olmaKAxJs2x6r83Jt5vTPJw7mySHp4kYg3YDdSrUr6CEb_WgJURYFbmzRAgGbrqoUPqpOm8dxJH6Ucegyduvm2kgvJv0Bj1ffFEXMt_Wvt0QM34hWFam-7rme1azXVXGuEEUeZUyznnNKpYXecbZEuNvzWdpufwDUfZWpg)

One weird behaviour is that the diagram is rendered correctly as soon as I change the `length` name

### Steps to reproduce

1. Use the following diagram

```
stateDiagram-v2
state show {
    a
}
state length {
    c
}
show --> length
```

2. observe

### Code Sample

```text
https://mermaid.live/edit#pako:eNpVjsFugzAQRH8FzRkQEBOwDzm1X9Bb5csKOwEF7MiYtCni3-uQECl72p15M9oZjVUaAqMnrz86OjkakmshzSpEY2t_olmaKAxJs2x6r83Jt5vTPJw7mySHp4kYg3YDdSrUr6CEb_WgJURYFbmzRAgGbrqoUPqpOm8dxJH6Ucegyduvm2kgvJv0Bj1ffFEXMt_Wvt0QM34hWFam-7rme1azXVXGuEEUeZUyznnNKpYXecbZEuNvzWdpufwDUfZWpg
```

**Comment by jgreywolf** [comment]
See comment in linked issue above - assume same/similar fix

**Comment by Pr0dt0s** [comment]
@jgreywolf this is not related to the other issue, i followed the traces and found the problem in the package dagre-d3-es.

dagre-d3-es is using _.forEach to iterate over an object with the stateIds as properties here:

https://github.com/tbo47/dagre-es/blob/761b78f220466cda021ae2af81a788bf38b5e185/src/dagre/position/index.js#LL7-L14

The problem arises when using a state named _length_ that messes with the forEach funtion as mentioned in this jsDocs:
https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/forEach.js#L5-L11

> **Note:** As with other "Collections" methods, objects with a "length" property are iterated like arrays. To avoid this behavior use `forIn` or `forOwn` for object iteration.

I already sent a pull request to dagre-es that should fix this issue.

@marcosh you could use a workaround like this in the meantime: 
```
stateDiagram-v2
state show {
    a
}
len : length
state len {
    c
}
show --> len
```
Notice that the problem occurs only when the ID of the state is length.

**Comment by Pr0dt0s** [comment]
Version 7.0.10 of dagre-d3-es has been released with the solution to the problem. Updating to this version will resolve the issue .

![image](https://user-images.githubusercontent.com/24417072/224490243-e5fa5d5f-0150-441a-9d53-e314ab36a616.png)

Class and flow diagrams, have the same problem as they utilize the same renderer, Examples [here](https://mermaid.live/edit#pako:eNpNjz0OgzAMha-CPMMFoo7t2KlblcVKDETKD0ocVRVw90JCab3Y_t6zbM-ggiYQoCymdDU4RHTSN1tY8gOPzWXpuiaN4VVp8ZV-rmD953Xmq0ALjqJDo7cFBUrgkRxJEFupqcdsWYL0uxUzh8fbKxAcM7WQJ41Mx0kgerTppDdtOMQTTuifIfxMVOT78dme1g8ILU4k) and [here](https://mermaid.live/edit#pako:eNpFjjEOwyAQBL-CrrY_QJEqKVOli2hOcBgk4Cx8yIos_93EkZytVrtTzAaWHYEGn3i1AauYonqWwKsax5tKVCYJpsAAmWrG6Dq8fSEDEiiTAd2rI48tiQFT9o5iE359igUttdEAbXYodI84VcygPablWh8uCtdrnLG8mf8QnffzZ3nK7geIBz2s).

I'm uncertain about the protocol for contributing updates to libraries. Would it be appropriate to submit a pull request with just the updated package.json (and pnpm-lock?

**Comment by marcosh** [comment]
thanks a lot @Pr0dt0s!

**Comment by aryzing** [comment]
Seems to be working now, let's close?


![mermaid-diagram-2023-05-15-193512](https://github.com/mermaid-js/mermaid/assets/4924405/85c1cdb3-0f4d-478a-bac5-553d234ace26)

**Comment by Pr0dt0s** [comment]
I agree, this issue should be closed already.
