### ISSUE TITLE
`length` node does not work

### ISSUE THREAD

**Issue by mpusz** [mermaid-js/mermaid#4078]
### Description

I need to use `length` as a node name. Unfortunately, it does not work in some cases. For now, I found two scenarios:

1. If I have only two blocks and one of them has the name `length`, the nodes overlap.
2. I cannot attach a callback to a node called `length`

### Steps to reproduce

Check both code samples

### Code Sample

```text
https://mermaid.live/edit#pako:eNplTzEOwjAM_ErkmcKeuRITE0woi0lMHdEklXEVIdS_k4IQA5YH--50unuCL4HAgsvXsVTPKGpOvcumzUh5UDZd15kag_IfyhQHVpc_hB-jv31pB6w63e1uV2vdDlF5vmx9SQ4atS9G2wqR4UiC4vnhWgTYQCJJGENL9FxdHShTIge2nQHltsqWpsNZy_GRPViVmTYwTwGV-oiDYAJ7xfHe0AnzuZTfTyFqkcOn8rv58gIEX1ZQ

https://mermaid.live/edit#pako:eNpFTrsOwjAQ-5Xo5uYHMndlggllOeWuTUQeVbioQlX_nQMGPNmWbfmA0IjBga9LbnuI2MXcZl-NInNdJRprrdkTSVQXJijcCybSzvGJeZDIhT04pYT94XXr1BwOaddXDeCkD55gbITCc8K1YwG3YH6qu2G9t_bXTElav_xOfb-db04SNro
```

### Setup

Live editor

**Comment by Yokozuna59** [comment]
Hi @mpusz, thanks for reporting the issue.
It appears to be an older issue that has been resolve in the latest version. Please confirm that.

- GitHub:
	
	![image](https://github.com/mermaid-js/mermaid/assets/87622592/94fd9769-8e97-4a4e-9e55-339aa350704d)

	![image](https://github.com/mermaid-js/mermaid/assets/87622592/fa8702b4-81a4-4641-830e-c8ada28b590d)

- Live Editor:
		
	![image](https://github.com/mermaid-js/mermaid/assets/87622592/8e977066-f32c-406d-837a-41656d565830)

	![image](https://github.com/mermaid-js/mermaid/assets/87622592/1650c377-944c-4a04-b082-2bd279868b4a)
