### ISSUE TITLE
Pie Chart gets cut off

### ISSUE THREAD

**Issue by adarsh-sgh** [mermaid-js/mermaid#4082]
### Description

[This Pie Diagram](https://mermaid.live/view#pako:eNpNjrEOgkAQRH9lszUFjQ2NhWhHLKg022y4VS5yd-RuL8QQ_l2QmNi-eTOZGbtgBCscrUDqw1SzMpAnVauDgE3QSHRsDfAkKTiB45YS3s4tYQWHsix3cL2c4A9igW5vruszeQBC7cXJJhAaji9C8svqcdbQvn2HlcYsBebRsEpt-RnZ_aAYqyE2-9vv6QJH9vcQVuXBQ5LlA-mYQ4o) when opened in window of width < 600px gets trimmed .

<pre>
mermaid
pie showData 
  title is Mermaid awesome ?
  "YES": 5000
  "OFC YES": 5000
</pre>

### Steps to reproduce

1. Open the [Live Editor link](https://mermaid.live/view#pako:eNpNjrEOgkAQRH9lszUFjQ2NhWhHLKg022y4VS5yd-RuL8QQ_l2QmNi-eTOZGbtgBCscrUDqw1SzMpAnVauDgE3QSHRsDfAkKTiB45YS3s4tYQWHsix3cL2c4A9igW5vruszeQBC7cXJJhAaji9C8svqcdbQvn2HlcYsBebRsEpt-RnZ_aAYqyE2-9vv6QJH9vcQVuXBQ5LlA-mYQ4o) in a seperate window.
2. resize it using dev tools to size <= 600px
3. refresh the page
4. it should show portions of diagram trimmed off as shown in screenshot below

### Screenshots

<img width="689" alt="image" src="https://user-images.githubusercontent.com/63918341/218274556-d19340f9-3390-4486-a3c3-664233e45349.png">

### Code Sample

```text
https://mermaid.live/view#pako:eNpNjrEOgkAQRH9lszUFjQ2NhWhHLKg022y4VS5yd-RuL8QQ_l2QmNi-eTOZGbtgBCscrUDqw1SzMpAnVauDgE3QSHRsDfAkKTiB45YS3s4tYQWHsix3cL2c4A9igW5vruszeQBC7cXJJhAaji9C8svqcdbQvn2HlcYsBebRsEpt-RnZ_aAYqyE2-9vv6QJH9vcQVuXBQ5LlA-mYQ4o

mermaid
pie showData 
  title is Mermaid awesome ?
  "YES": 5000
  "OFC YES": 5000
```

### Setup

**Desktop**

- OS and Version: Macos Ventura
- Browser and Version: Chrome 109.0

**Comment by Gardezi1** [comment]
@sidharthv96 can I take up this issue. And what is the expected behaviour? Like should I graph size become smaller or should the text be moved to the bottom?
