### ISSUE TITLE
Labels are trimmed in class diagrams

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#4083]
### Description

The number values, `1` is trimmed in class diagram. 

### Steps to reproduce

Open https://mermaid.js.org/syntax/classDiagram.html#setting-the-direction-of-the-diagram

### Screenshots

<img width="391" alt="image" src="https://user-images.githubusercontent.com/10703445/218384789-2ab1abeb-5cb3-484d-91f8-e2a6686625a7.png">

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by amsubhash** [comment]
@sidharthv96 I think the bug is in the website not in the SVG as it is working fine in the live editor.
Changing the `line-height: 24px;` to `line-height: inherit;` in the body of the website will fix the issue, don't know if it will affect any other part of the website.
