### ISSUE TITLE
[Bug] Can not use `render` method with mindmap and timeline

### ISSUE THREAD

**Issue by Mister-Hope** [mermaid-js/mermaid#4089]
## Description

Error diagram will be shown if rendering mindmap and timeline diagrams with `mermaid.render()` as they seems to be async. (Also they are also not working as expected with `renderAsync`)

Also, since mermaid:

- does not provide a api to detect whether a diagram has been registered
- will throw if registing a diagram that already registered before

The 3rd and 4th errors are triggered.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/33315834/219099074-127a6fd7-9e51-4903-bc3c-fab351e06c98.png">

### Step to reproduce:

use `mermaid.render` to render any content with timeline or mindmap

### Related code:

Here diagrams are added during render:

https://github.com/mermaid-js/mermaid/blob/b5a4cc0e17168c257a3b0d40a068e3addfc9c40a/packages/mermaid/src/mermaidAPI.ts#L383

However they are async:

https://github.com/mermaid-js/mermaid/blob/25da0c6c8e7d24ee984b050114002978ddf1070a/packages/mermaid/src/diagram-api/diagram-orchestration.ts#L111

## Breaking changes unlisted

mermaid 9.3 use `@mermaid-js/mermaid-mindmap` for mindmap, however it's removed in repo and seems to be deprecated, this is NOT listed in changelog!

**Comment by knsv** [comment]
Thanks for pointing this out. We will add that.

Mind maps has been included in the package so that users don't have to anything to have it available. We have added another diagram, **timeline**, that likely will suffer from the same problem. We hoped to avoid breaking changes but missed this. 

We were/are planning an api update to make all rendering sync, that will be v10. I guess this accelerates that plan.

**Comment by Mister-Hope** [comment]
> We were/are planning an api update to make all rendering async, that will be v10. I guess this accelerates that plan.

Then maybe jsdocs is wrong?

This is not marked as deprecated:

https://github.com/mermaid-js/mermaid/blob/fec193ebaf85403e3bc8031d79b4f593a5db1c31/packages/mermaid/src/mermaidAPI.ts#L351-L377

However this is:

https://github.com/mermaid-js/mermaid/blob/fec193ebaf85403e3bc8031d79b4f593a5db1c31/packages/mermaid/src/mermaidAPI.ts#L580-L584

**Comment by sidharthv96** [comment]
https://github.com/mermaid-js/mermaid/discussions/4091#discussioncomment-5021986

**Comment by sidharthv96** [comment]
Fixed in v10.
