### ISSUE TITLE
[Bug] Sizing in pie chart

### ISSUE THREAD

**Issue by Mister-Hope** [mermaid-js/mermaid#4097]
### Description

There will be huge padding in pie chart, it should be a bug (it exisits a long time)

### Steps to reproduce

See https://mermaid.js.org/syntax/pie.html

**Comment by Harsha-10** [comment]
can you please elaborate more....like the pie chart size need to be increased?

**Comment by Vsoni27** [comment]
Can you please add any related screenshots or code, it would be helpful to understand this issue.

**Comment by Mister-Hope** [comment]
Hi, the gap in official docs already disappeared, I will post later to find out whether this issue is already resovled.

**Comment by Mister-Hope** [comment]
Yes, I think the issue has been solved, there was a huge horizontal gap with pie chart in the previous versions, they disappeared just by upgrading to latest version.
