### ISSUE TITLE
Mindmaps do not work: "No diagram type detected for text: mindmap"

### ISSUE THREAD

**Issue by nicklasb** [mermaid-js/mermaid#4102]
### Description

When I try to create a mind map, I get an error 
`No diagram type detected for text: mindmap`

I get the same error when:
* I preview it in the VS Code editor with "Markdown Preview Mermaid Support" - plugin
* I upload a .md-file on github.
* Add it here, in the "Steps to reproduce". 

Other types, for example Sequence diagrams, seem to work. 

### Steps to reproduce

```mermaid
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectiveness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
```

### Code Sample

The code sample is here in the issue above.

### Setup

**Desktop**

- OS and Version: [Mac]
- Browser and Version: [Chrome]

**Comment by sidharthv96** [comment]
Please refer to https://mermaid.js.org/syntax/mindmap.html#integrating-with-your-library-website

The plugin might not have added support for mindmaps yet. So please raise an issue in their repo. Thank you!

**Comment by nicklasb** [comment]
Correct, there is even an open issue on it on the plugin site:
https://github.com/mjbvz/vscode-markdown-mermaid/issues/153

Did not realize it was that new.

**Comment by pro-gra-001** [comment]
I also get a similar question like that. When I try to make a flowchat, I get a error `UnknownDiagramError: No diagram type detected matching given configuration for text: flowchat
`
 I download the same plugin but it doesn't work
