### ISSUE TITLE
Mermaid v10

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#4103]
Breaking changes planned in v10

- https://github.com/mermaid-js/mermaid/issues/3590
- https://github.com/mermaid-js/mermaid/issues/3577
- https://github.com/mermaid-js/mermaid/issues/3394
- https://github.com/mermaid-js/mermaid/issues/3406
- https://github.com/mermaid-js/mermaid/issues/3055
- https://github.com/mermaid-js/mermaid/issues/3397

---
PS @aloisklink, we have blank issues now.

**Comment by aloisklink** [comment]
Do we know when v10 is expected?

On my side, I have a WIP that slightly updates the types of `MermaidConfig`

<details>
  <summary> Main differences to the types of MermaidConfig: </summary>

Main differences to the types of [`MermaidConfig`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/config.type.ts) in my WIP:
  - A bunch of types for variables like `securityLevel` are changed from a `string`/`number` to an enum. (e.g. `securityLevel` type is `"strict" | "loose" | "antiscript" | "sandbox"`).
  - A bunch of options marked as `Required` in the docs are now made required in the type.
    (this will involve changing functions like `setConfig()` to accept a `Partial<MeramidConfig>`)
</details>

---

We may also want to remove `@deprecated` options: https://github.com/mermaid-js/mermaid/blob/0c18c0309bfdf40eab4e0cbfef9cbaacf8466a61/packages/mermaid/src/config.type.ts#L6-L9

> PS @aloisklink, we have blank issues now.

Awesome, that makes life a bit easier for Mermaid experts!

**Comment by sidharthv96** [comment]
Can you make a PR with your changes?, I'll publish the `release/10.0.0` branch soon with an RC.
Regarding timeline, the plan is to release v10 with _only_ the breaking changes ASAP (No new features), so as soon as the linked issues are resolved. 

https://github.com/mermaid-js/mermaid/issues/3397 is a major one to configs that might need some discussions on.

**Comment by aloisklink** [comment]
> Can you make a PR with your changes?

My PR is at #4112. However, I made that PR **without any breaking changes**, so it can wait until a `v10.0.1`.

It should be pretty easy to add a config validator too using [ajv](https://github.com/ajv-validator/ajv) too if #4112 gets merged (I believe this is the package that ESLint plugins use), in order to implement https://github.com/mermaid-js/mermaid/issues/3397. We can even add it to a `v10.x` release, if we make the config validator print warnings, then make it print errors in v11.

**Comment by Mister-Hope** [comment]
As mermaid v10 provide a async render function, can we expect a recent v11 that split mermaid to `@mermaid-js/core` and `mermaid-js/xxx` (xxx is diagrams)? This can make mermaid tree-shakable.

**Comment by sidharthv96** [comment]
Please open a new issue/discussion. 

I was pondering an idea to split all the new diagrams like mindmap and flowchart-elk into a separate _single_ package (having individual packages for each diagram will affect adoption significantly).

The size difference is significant, but as all diagrams are lazy loaded now, it won't impact most users as only diagrams they use are downloaded. 

Only the people who bundle without splitting will be affected. 

But let's discuss this in a new thread. Thanks!

**Comment by Mister-Hope** [comment]
> The size difference is significant, but as all diagrams are lazy loaded now, it won't impact most users as only diagrams they use are downloaded.

Why are you saying this, as long as the input is made by user (not me), it means I have to pack all mermaid code for them. But with sperate packages, I can pack them each **much more easily** and do a pre-check about users input and register new diagram for them by downloading new chunks containing the diagram, but for making a whole package, it will probably pack into a single chunk by webpack and vite **without advanced code splitting configuration** and users do need to download them all before using anyone.
