### ISSUE TITLE
Documentation website is no longer showing example diagrams

### ISSUE THREAD

**Issue by dextermb** [mermaid-js/mermaid#4117]
### Description

When attempting to view the documentation for any of the diagram types shows `[object Object]` underneath each code example instead of a diagram

### Steps to reproduce

1. Go to docs website
2. View example code for a diagram type (e.g [_here_](https://mermaid.js.org/syntax/flowchart.html#graph))
3. See `[object Object]` instead of diagram

### Screenshots

<img width="743" alt="image" src="https://user-images.githubusercontent.com/6137789/220117523-e69f0765-94ab-4a55-bc47-b45fcdcd96a4.png">

**Comment by mig8447** [comment]
I'm also experiencing this issue on both mobile and desktop browsers. I believe you may be concatenating an object without converting it to a string first

**Comment by sidharthv96** [comment]
Thanks for bringing it up!

Have rebuilt in https://github.com/mermaid-js/mermaid/commit/4bc997cb8faa3d9f317b6f9752e3366d133b4851.
We had an accidental merge of an new release, which was reverted. But the docs site wasn't rebuilt. 

Please do a Ctrl + Shift + R to clear the cache if the issue persists.

**Comment by marcaurele** [comment]
The issue is still present now while having used Ctrl+Shift+R, or another browser which I never used to access mermaid documentation website. How long is it suppose to take to deploy the new artifacts?

**Comment by sidharthv96** [comment]
@marcaurele after my rollback, the v10 branch was again merged before the docs were fixed. 
I have pushed the fix now, please verify if it's working now.

**Comment by dextermb** [comment]
> @marcaurele after my rollback, the v10 branch was again merged before the docs were fixed.
> I have pushed the fix now, please verify if it's working now.

I'm able to see the example. Thanks
