### ISSUE TITLE
Editor hangs and emits "InternalError: too much recursion"

### ISSUE THREAD

**Issue by dyc3** [mermaid-js/mermaid#4129]
**Describe the bug**
The editor hangs and emits "InternalError: too much recursion" when trying to render a specific `erDiagram`.

**To Reproduce**
Link to Live Editor: https://mermaid.live/edit#pako:eNptjjEOwjAQBL9ibe0XuEOkTUWH3JziC0Rgn2XsAiLn7XES6NhqtRqtZsYgjmHAqZvolsjboFpOaj7Klp7ictaqW9Qooiw-f2Jx8NUGaHhOnibXfvcbi3xnzxamVUfpsdG1cVSyXN5hgMmpsEaJjjJ_TWBGer7aym7KkvpDdPfViBSuIj-mrpvIQtM

1. Attempt to render this diagram
```mermaid
erDiagram
    A {
        Map~C, D~ foo "zzzzzzzzzzzzzzzzzzzz"
    }
```

Raw code
```
erDiagram
    A {
        Map~C, D~ foo "zzzzzzzzzzzzzzzzzzzz"
    }
```

**Expected behavior**
Should compile and render the graph

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Firefox
- Version 109.0

**Additional context**

**Comment by sidharthv96** [comment]
Seems like an issue with mermaid. Even github's native renderer doesn't work.
