### ISSUE TITLE
Is `mermaid@10.0.0/dist/mermaid.js` missing from unpkg?

### ISSUE THREAD

**Issue by a114383** [mermaid-js/mermaid#4132]
### Description

Hey - I've had this in my app for a few months, but it's stopped rendering (todays the first day I noticed):

```javascript
  <script src="https://unpkg.com/mermaid/dist/mermaid.js"></script>
  <script src="https://unpkg.com/docsify-mermaid@latest/dist/docsify-mermaid.js"></script>
  <script>mermaid.initialize({ startOnLoad: true, flowchart: { useMaxWidth: false } });</script>
```

Upon some inspection I don't think that first file exists anymore?

https://unpkg.com/browse/mermaid@10.0.0/dist/mermaid.js

### Steps to reproduce

1. Import mermaid: `<script src="https://unpkg.com/mermaid/dist/mermaid.js"></script>`
2. Get 404 error

### Setup

**Desktop**

- OS and Version: Mac
- Browser and Version: Chrome, Version 110.0.5481.100 (Official Build) (x86_64)

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by RyoJerryYu** [comment]
Maybe same issue:

I use mermaid in playwright as follow:

```typescript
const browser = await playwright.chromium.launch(settings.launchOptions);
const context = await browser.newContext({
  viewport: { width: 1000, height: 3000 },
});
const page = await context.newPage();
...
await page.addScriptTag({
  url: "https://unpkg.com/mermaid/dist/mermaid.min.js",
  type: "module",
});
```

And it throw an error today:

```
page.addScriptTag: Error: Failed to load script at https://unpkg.com/mermaid/dist/mermaid.min.js
    at script.onerror (eval at evaluate (:197:30), <anonymous>:7:74)
```

**Comment by Mister-Hope** [comment]
Try not to be so noob, as described in v10 release note, mermaid is ESM only, so the default entry file is `mermaid.core.esm.js`.

If you want to use CDN links, you'd better add `@9` to ensure you are using 9.x to avoid v10 breaking changes break your app/site.

**Comment by sidharthv96** [comment]
@a114383 thanks for pointing it out, I've added an extra section in Changelog and release notes so point this out and how to fix it. 

https://github.com/mermaid-js/mermaid/blob/develop/CHANGELOG.md#mermaid-is-esm-only

---

@Mister-Hope please don't resort to name-calling people reporting genuine issues.

**Comment by Mister-Hope** [comment]
I  DO think that:

1. It's a basic that packages are allowed to make breaking changes while raising major versions(and you should expect this)

2. People should try to read release notes when upgrading to new versions.

Also, this is how I behave on my open source projects too. As a open source author, I have no duty to pay for others careless or ignorant which they should not have. However, this is actually not my project, so I may stop using the word "Noob" if you do think that I am "name-calling people" at this situation, then I can stop it as you wish, though you are still not changing my minds.

**Comment by krisztianpinter** [comment]
question: a few minutes of googling revealed that unpkg hosts mermaid autonomously. you don't have control over it, or manually register anything, right?

so it seems more an unpkg issue, namely they see the version, but can't locate the main file to host. still point to the new version, which is missing.

**Comment by a114383** [comment]
Thanks @sidharthv96!

And while I completely agree with your points @Mister-Hope your presentation doesn't help.  This is used in a static site so despite a lot of usage of Mermaid, I have absolutely no javascript ecosystem experience.  When I checked the release notes, the meaning of "switched to ESM" flew right over my head.  

I pinned this back to v9.4.0 and am back in action - Thanks again.

**Comment by sidharthv96** [comment]
@Mister-Hope, thank you for understanding. I don't disagree with _what_ you said, the _how_ felt a little harsh.

---

@krisztianpinter 
v10 ESM: https://unpkg.com/mermaid@10/dist/mermaid.esm.min.mjs
v9 ESM: https://unpkg.com/mermaid@9/dist/mermaid.esm.min.mjs
v9 CJS: https://unpkg.com/mermaid@9/dist/mermaid.min.js

**Comment by krisztianpinter** [comment]
@sidharthv96 it doesn't explain to me why

https://unpkg.com/mermaid/dist/mermaid.min.js  -> 302 https://unpkg.com/mermaid@10.0.0/dist/mermaid.min.js

it should redirect to 9.4.0. still seems like an unpkg issue to me.

**Comment by Mister-Hope** [comment]
> And while I completely agree with your points @Mister-Hope your presentation doesn't help. This is used in a static site so despite a lot of usage of Mermaid, I have absolutely no javascript ecosystem experience. When I checked the release notes, the meaning of "switched to ESM" flew right over my head.

It's not what ecosystem you are in, even if you are not familar with javascript, you  should know that breaking changes probably exisits across versions and you just ran into one. So obviously this is not the question. I would not call you a noob if you represents  "V9 usage is not working with V10, how I can work with V10”  in discussion. That is a great difference.

**Comment by Mister-Hope** [comment]
> it should redirect to 9.4.0. still seems like an unpkg issue to me.

It makes no sence that it should redirect to 9.4.0, absent of version range of version number means you want the LATEST version, and in this case V10 is, while v10 doesnot have the old file, the cdn link became invalid by the moment mermaid v10 lands, that's why a lot of guides recommend and even force you to include a major version number in your link. REMIND THAT

**Comment by Mister-Hope** [comment]
@sidharthv96 I may remind you that codepen links in docs as example are still using v6... The docs definitely need an update. And these links are better created by active maintainer so that they can get a chance to update overtime. Though I can definitely open a pr with links I created, I can not promise I can keep update that in time with mermaid.

**Comment by sidharthv96** [comment]
> > it should redirect to 9.4.0. still seems like an unpkg issue to me.
> 
> It makes no sense that it should redirect to 9.4.0, absent of version range or version number means you want the LATEST version, and in this case V10 is, while v10 does not have the old file, the cdn link became invalid by the moment mermaid v10 lands, that's why a lot of guides recommend and even force you to include a major version number in your link. REMIND THAT

Yup, this was a problem with mermaid docs too until @aloisklink pointed out we should have major version pinned.

---
> @sidharthv96 I may remind you that codepen links in docs as example are still using v6... The docs definitely need an update. And these links are better created by active maintainer so that they can get a chance to update overtime. Though I can definitely open a pr with links I created, I can not promise I can keep update that in time with mermaid.

I believe it would be much easier to maintain if we had an examples folder and have a button to open in stackblitz.

https://developer.stackblitz.com/guides/integration/open-from-github

**Comment by Mister-Hope** [comment]
Yes, but if the stackblitz project is created by me, then I shall maintain these to keep it update, and I can't give a promise that I can be an active maintainer. I just think it's better for core team member to maintain this
