### ISSUE TITLE
flowchart doesn't support double percetage (%%) comment syntax between attribute blocks

### ISSUE THREAD

**Issue by alexeyval** [mermaid-js/mermaid#4137]
### Description

When attempting to use the double percentage sign comment syntax (%%) between attribute blocks of flowchart, the following error is thrown:

Error: Parse error on line 3:
... A --> %%B --> C --> .[ en
----------------------^
Expecting 'AMP', 'ALPHA', 'COLON', 'PIPE', 'TESTSTR', 'DOWN', 'DEFAULT', 'NUM', 'COMMA', 'MINUS', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'NEWLINE'

### Steps to reproduce

1. Create a new flowchart mermaid document.
2. Use double percentage comment syntax between attribute blocks.
3. Owl done.

### Screenshots

![Screenshot from 2023-02-23 17-51-46](https://user-images.githubusercontent.com/34779096/220911998-3619bf6e-7f03-47c9-bd3a-4bbcb8c21859.png)
![Screenshot from 2023-02-23 17-54-10](https://user-images.githubusercontent.com/34779096/220912226-1bbd83ea-ce17-4f4f-adcc-fbc63e2cfa8f.png)
![Screenshot from 2023-02-23 17-55-26](https://user-images.githubusercontent.com/34779096/220912414-8db0ea4b-00e0-4aaa-b5df-90c3b62d141d.png)

### Code Sample

```text
OK:
flowchart LR
    %%B -->
    A --> 
    C -->
    .[ end ]

FAIL:
flowchart LR
    A --> 
    %%B -->
    C -->
    .[ end ]
```

### Setup

**Desktop**

- OS and Version: Linux
- Browser and Version: Chrome

### Additional Context

The error doesn't occur when commenting at the beginning and at the end.
I have to move comments to the beginning or to the end each time for this to work.
Is there a way to ignore comments in the middle?

**Comment by sidharthv96** [comment]
Related https://github.com/mermaid-js/mermaid/pull/4128
