### ISSUE TITLE
support not english symbol

### ISSUE THREAD

**Issue by LinWanCen** [mermaid-js/mermaid#4138]
### Description

support like chinese symbol "！"

If support in github mermaid.js this not error:
```mermaid
graph LR
A[a！]
```

### Steps to reproduce

add not English symbol in src.

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

**Comment by shtratos** [comment]
Just put it in quotes:

```
graph LR
    A["a！"]
```

```mermaid
graph LR
    A["a！"]
```
