### ISSUE TITLE
Create a common template for different graphs using front matter

### ISSUE THREAD

**Issue by Wonderer11** [mermaid-js/mermaid#4150]
### Proposal

As there are many common elements shared in different graphs (eg. title), Mermaid may create a common template for different graphs.

Using title as an example, it has different code for Gantt Diagrams, Pie Chart, User Journey etc. and I think it will be better to put the title element in the front matter like how it was code in Flowcharts.

### Example

# Gantt diagrams
```
Gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    Task 1    :a1, 2014-01-01, 30d
    Task 2    :after a1, 20d
```
# Pie Chart
```
pie title Pets adopted by volunteers
    "Dogs" : 386
    "Cats" : 85
    "Rats" : 15
```
# User Journey
```
journey
    title My working day
    section Go to work
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Go home
      Go downstairs: 5: Me
      Sit down: 5: Me
```
# Flowcharts
```
---
title: Node
---
flowchart LR
    id
```

**Comment by sidharthv96** [comment]
Frontmatter does work on all diagrams. 
We cannot remove the existing methods as we have to be backwards compatible. 

![image](https://user-images.githubusercontent.com/10703445/221860536-8e86d83e-01c7-4f1f-9bf7-5709f183e26f.png)
