### ISSUE TITLE
Couldn't figure out how to add clickable hyperlinks into the mindmap sample.

### ISSUE THREAD

**Issue by IbrahimHindawi** [mermaid-js/mermaid#4152]

**Comment by jgreywolf** [comment]
This is not currently possible
See issue #4099

**Comment by DmitryGalyuk** [comment]
This is my workaround (I add the class with the nodeID to each node like n123, but it is not mandatory, mm is the div with the mindmap)

        document.addEventListener('click', function (event) {
            if( event.target.tagName === "tspan") {
                let mindmapdiv = document.getElementById("mm");
                if (!mindmapdiv.contains(event.srcElement) ){
                    return;
                }
                let elem = event.srcElement;
                while (elem && mindmapdiv.contains(elem)) {
                    if (elem.classList.contains("mindmap-node")) {
                        let id;
                        for (let c of elem.classList) {
                            if( c.startsWith("n")) {
                                id = c.substring(1);
                                break;
                            }
                        }
                        event.preventDefault();
                        location.hash = "#"+id;
                        renderData(root.findChild(id));
                        return;
                    }
                    elem = elem.parentElement;
                }
            }

**Comment by vMamr** [comment]
I've come up with the perfect solution.

You need to add this JS code after loading Mermaid:
```
        window.addEventListener('load', () => {
            // Ищем все элементы с классом, начинающимся на 'link:'
            document.querySelectorAll('*[class*="link:"]').forEach(node => {
                node.classList.forEach(className => {
                    if (className.startsWith('link:')) {
                        const url = className.split(':')[1]; // Извлекаем URL из класса

                        // Добавляем обработчик события для клика
                        node.addEventListener('click', () => {
                            window.open(`https://${url}`, '_blank'); // Открываем ссылку в новой вкладке
                        });
                    }
                });
            });
        });
```

Use this structure:
```
        mindmap
            root((Главная тема))
                Важная тема
                :::link:example1.com
                Вторая важная тема
                    :::link:example2.com
									важная тема 2.1
											:::link:example2.1.com
                Третья важная тема
                    :::link:example3.com
```

If you want a click icon instead of an arrow, then add this CSS code:
```
[class*="link:"] {
	cursor: pointer; /* Курсор-рука при наведении */
}
```
