### ISSUE TITLE
Support more unicode languages.

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#4155]
### Discussed in https://github.com/orgs/mermaid-js/discussions/4149

<div type='discussions-op-text'>

<sup>Originally posted by **bipul-mohanto** February 26, 2023</sup>
Hi!
I was trying to write something with language Bengali and Hindi. But unfortunately, the compilation failed. Is it possible `mermaid` support for such U+0981 languages?</div>

**Comment by sidharthv96** [comment]
Currently, class & flow diagram parsers seems to have partial unicode support.
We could add more ranges in the jison files and also add the UNICODE_TEXT lexer to all other jison files. 

Wonder if we could add emoji support in this way.

**Comment by bipul-mohanto** [comment]
Thank you very much for the consideration.

**Comment by aswindevsp** [comment]
Hi, I want to work on this, but I don't exactly where to start. Would adding the unicode to jison files would work? Also is there a guide on how can locally install the libary and check if it work. Sorry if made any mistakes in the question.

**Comment by sidharthv96** [comment]
@aswindevsp, you can follow [this guide](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md#development-installation) to setup locally.

Then run `pnpm dev` and you'll be able to get the local mermaid up. 
Opening https://localhost:9000 should take you to the demos page. 

Adding more unicode ranges to JISON should work for flow and class. You can try starting with that for now.

**Comment by aswindevsp** [comment]
I added this range [\u0980-\u09FF] to the flow and classDiagram jison files. And now it's able to dispaly  U+0981 mentioned above.

**Comment by sidharthv96** [comment]
Awesome work @aswindevsp!
Can you mention from where you got the unicode range?
We might be able to add more depending on the need.

**Comment by aswindevsp** [comment]
> Awesome work @aswindevsp! Can you mention from where you got the unicode range? We might be able to add more depending on the need.

https://en.wikipedia.org/wiki/Bengali_(Unicode_block)

**Comment by bipul-mohanto** [comment]
Thanks, @aswindevsp for your effort. Now the Bengali letters are working. But whenever adding `কাকা`, it is not working.  

```
```mermaid
flowchart TB
কক-->খখ;
```

```
// this is not working
কাকা --> धन्यवाद
```

**Comment by sidharthv96** [comment]
As we're already making the change, we should try to support as much unicode ranges as we need to cover Indian languages.

**Comment by bipul-mohanto** [comment]
I sincerely appreciate your efforts. Unfortunately I do not know Javascript, otherwish I could also join in this.

**Comment by aswindevsp** [comment]
Some of the uncode of Bengali and Devanagari are present in the jison files 
[\u08A2-\u08AC\u0904-\u0939\u093D\u0950\u0958-\u0961\u0971-\u0977]|
[\u0979-\u097F\u0985-\u098C\u098F\u0990\u0993-\u09A8\u09AA-\u09B0\u09B2]|
[\u09B6-\u09B9\u09BD\u09CE\u09DC\u09DD\u09DF-\u09E1\u09F0\u09F1\u0A05-\u0A0A]|


Also adding the ranges that are already also seems to break the rendering.

**Comment by aswindevsp** [comment]
Can you assign me to this issues? I could add the unicodes the source.

**Comment by sidharthv96** [comment]
You can open a PR linked to this issue. You don't have to wait for issues to be assigned. Issues without PRs are open for everyone.

**Comment by aswindevsp** [comment]
@sidharthv96 Lot of other ranges are also missing. Should i add them too?

**Comment by sidharthv96** [comment]
Yes please.

**Comment by knsv** [comment]
There is a simple workaround that can be used, when having the unicode characters in a string it works. This will not handle ids though but strings can be handled this way:
```
   id["কাকা"] --> id2["धन्यवाद"]
```
```mermaid
flowchart LR
   id["কাকা"] --> id2["धन्यवाद 👍"]
```

**Comment by Ashinjl** [comment]
hai @aswindevsp can you tell which file you edited for bengali language I will try tamil , malayalam languages

**Comment by sidharthv96** [comment]
As unicode is supported with double quotes, there is no need to pollute the grammar with extra unicode just to support IDs.
