### ISSUE TITLE
mermaid module not found when running tests

### ISSUE THREAD

**Issue by lceconi** [mermaid-js/mermaid#4161]
### Description

Hello, I just updated Mermaid to version 10.0.0 and now the tests in my app stopped working with the error `Cannot find module 'mermaid' from './file.ts'`. This was not occurring in previous versions (> 9.4.0). Everything works fine when running the app, this error is only happening on tests.

I did some investigation and found out that Jest actual error message is `Error: No known conditions for "." entry in "mermaid" package`. Adding the `require` entry, pointing to `"./dist/mermaid.esm.mjs"` in `package.json` solved the issue :)

Any specific reason to remove the `require` entry? Anyhow, I'm opening a PR adding it to `package.json`

### Steps to reproduce

1. Install `mermaid` in a React app
2. Create a file importing `mermaid` as follows: `import mermaid from 'mermaid'`
3. Create a `test` file for the previous created file
4. Run tests
5. See the error `Cannot find module 'mermaid' from './file.ts'`

### Setup

**Desktop**

- OS and Version: Mac
- Browser and Version: Chrome

**Comment by fdemello** [comment]
I updated to 10.1.0 and ran into this. I had to downgrade to 9.4.3 to avoid test errors.

**Comment by fabiradi** [comment]
We use Jest v26 and it still fails for us. Any idea, how to tackle it?

**Comment by StationSoen** [comment]
@fabiradi 
Create empty mock js for mermaid and add its path to `moduleNameMapper` in jest config file.
It works for me.
```javascript
// mermaid-mock.js

// eslint-disable-next-line @typescript-eslint/no-unused-vars
module.exports = (...args) => {
  //
};

```
```javascript

// jest.config.js
module.exports = {
  ...
  moduleNameMapper: {
    ...
    mermaid: "<rootDir>/path_to_mock/mermaid-mock.js",
  }
}
```

**Comment by zongqichen** [comment]
Hi, is there any solution? I'm still facing module not found issue when running jest framework. Thanks
