### ISSUE TITLE
In 10.0.0, you can no longer `try catch` mermaid.parse errors

### ISSUE THREAD

**Issue by AlbinoGeek** [mermaid-js/mermaid#4166]
### Description

When I attempt to parse bad graph syntax, an error is thrown.

When I try to try/catch this error in 10.0.0, it is **still thrown.**

### Steps to reproduce

1. Use broken graph code (such as rendering the graph while the user is typing)
2. Attempt to catch and silently throw away errors by try/catching mermaid.parse
3. Get a huge exception thrown, regardless of the try/catch which should silence it.

### Screenshots

![image](https://user-images.githubusercontent.com/1910461/221992482-e3e960cf-1406-4463-9b89-6b439325a71c.png)

### Code Sample

```text
graph TD

A --> B
A -->
```

### Setup

**Desktop**

- OS and Version:
  - Windows 10
  - Fedora 33 Workstation
  - Ubuntu 20.04
- Browser and Version:
  - Brave [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)]
  - Opera [Version 96.0.4693.20 Chromium: 110.0.5481.100 (Official Build) (64-bit)]

### Additional Context

**This is new behaviour in 10.0.0**

**Comment by AlbinoGeek** [comment]
### Also Note

I am aware that one can `suppressErrors` -- however, this was not required in 9.3.0 -- and a thrown error escaping a `try`/`catch` should always be seen as a bug (abuse of language) in my mind, regardless of configuration.

**Comment by sidharthv96** [comment]
Try adding an `await` before the parse?

mermaid.parse is async, so that must be why it's escaping the try/catch.

From the changelog: https://github.com/mermaid-js/mermaid/blob/develop/CHANGELOG.md#mermaidparse-is-async-and-parseerror-is-removed 

```js
// < v10
mermaid.parse(text, parseError);

//>= v10
await mermaid.parse(text).catch(parseError);
// or
try {
  await mermaid.parse(text);
} catch (err) {
  parseError(err);
}
```

**Comment by sidharthv96** [comment]
I'm closing this now as your issue should be fixed. Please reopen if it isn't. Thank you.

**Comment by MarketingPip** [comment]
@sidharthv96 -  is this documented somewhere or do search indexes just suck? lol

**Comment by AlbinoGeek** [comment]
I, too, could not find this documented at the time.
However, this issue was helpful in guiding me to a solution :)
