### ISSUE TITLE
Unable to escape `:` in timeline

### ISSUE THREAD

**Issue by ckipp01** [mermaid-js/mermaid#4175]
### Description

Given a minimal timeline diagram it seems impossible to be able to escape `:`.  However when you try to for example wrap it in quotes you get a failure without much description or help.

```
Error: Evaluation failed: Error: Diagram error not found.
    at pptr://__puppeteer_evaluation_script__:24:17
    at ExecutionContext._ExecutionContext_evaluate (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:251:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:140:16)
    at async CDPElementHandle.$eval (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:116:24)
    at async renderMermaid (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:216:22)
    at async parseMMD (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:188:20)
    at async run (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:438:20)
    at async cli (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:154:3)
```

### Steps to reproduce

You can reproduce this by creating a minimal file with the following in it:
```
timeline
    title An example
    section Day 1
        "Some event at 9:00"
```

### Setup

This is done using mermaid CLI.

```
❯ mmdc --version
10.0.0
```
Also trying this on the online editor fails

**Comment by af4jm** [comment]
I'm seeing this, as well... if I remove the `:` the quotes display in the diagram... with the `:` I get the following (using [mermaid.live/edit](https://mermaid.live/edit#pako:eNqFkbtuwzAMRX9F4JLFDtJu9VbAS4d08aqFtuiUqEQFEl3UCPzvVeIk8FYuBHgP3xcYoiNoQDmQZyErppiyejLvYugXw9nfo5kG5Simxdm8rKGrWehiIEM_JGpQzVtzOFiACgKlgOxK9ctKW3CYvutQWlpojKaJqqdCWnAWzsrDh8v_AG1H5K6MBdF972PoKZ32r6XzM2OMovWIgf28krvPqNF0KHlXmVxcnSnxuEnRLwp0L0uTJvRb8XGjol-2-zvO2Hs6Tr6MFn1Mj-FXaLGylHPgpLGbZYDmthdMZ4dKLeMpYYBmRJ9LlBxrTMf1K7fnLH8u64Zw))

```
Error: Parse error on line 4:
...    "Some event at 9:00"
-----------------------^
Expecting 'EOF', 'SPACE', 'NEWLINE', 'title', 'acc_title', 'acc_descr', 'acc_descr_multiline_value', 'section', 'period', 'event', 'open_directive', got 'INVALID'
```

on a related note, the documentation does not mention any way of escaping `:` and shows no example of wrapping in `"` or anything else (which implies that this behavior is expected)... so I would say that in addition to the behavior bug described by the original poster, there's also a docs bug for missing a section on how to escape

**Comment by pil0t** [comment]
Just in case, I found a possible workaround - using other unicode symbols that looks similar to `:`
`∶` U+2236 RATIO
`ː` U+02D0 MODIFIER LETTER TRIANGULAR COLON

**Comment by ashantyk** [comment]
having the same problem.

**Comment by FutzMonitor** [comment]
During my testing, there are some other symbols that do not work. 

### Title
1. Using a hashtag symbol `#` will result in the text following the hashtag to not render (e.g. "Hist#ory of Social Media" will just render as "Hist"). This behavior is also the same for newlines `\n`. 
2. The semicolon causes a syntax error and nothing is rendered as a consequence. 
### Section
1. Using the hashtag symbol `#` will result in the text following the hashtag to not render (e.g. "Hist#ory of Social Media" will just render as "Hist"). This behavior is also the same for newlines `\n`. 
2. Colons and semicolons causes a syntax error and nothing is rendered as a consequence.
### Time Period
1. Using the hashtag symbol `#` will result in the remaining text for the time period and even the event proceeding it to not render (e.g. "Ind#ustry 2.0 : Electricity, Internal combustion engine, Mass production" will only render the time period "Ind" and the event will not render below it). This behavior is also the same for newlines `\n`. 
2. Colons and semicolons causes a syntax error and nothing is rendered as a consequence. 
### Events
1. Using the hashtag symbol `#` will result in the remaining text for the event to not render (e.g. "Inter#net, Robotics, Internet of Things" will only render to "Inter"). Interestingly, if there's a newline below it with a new event that event will render just fine.  
2. Newlines  `\n` cause the event to render only up to the text before the newline (e.g. "Inter\nnet, Robotics, Internet of Things" will only render to "Inter") and then the remaining text will be pushed into a section (e.g. the remaining text "net, Robotics, Internet of Things" becomes its own section). 
3. Using a colon or a semicolon causes a syntax error and nothing is rendered as a consequence.

**Comment by FutzMonitor** [comment]
Currently, users are permitted to define `event` elements in the same line by using the colon character `:` as a delimiter. 

![image](https://github.com/mermaid-js/mermaid/assets/31524934/056f168f-6819-4e8a-ad74-289570f82e43)

When defining a workaround to allow colons for this, I find it difficult to include this case. What would be some way of tackling same-line event definitions?
