### ISSUE TITLE
Class Diagram Qualified Associations

### ISSUE THREAD

**Issue by ecorm** [mermaid-js/mermaid#4189]
### Proposal

Please add qualified associations to class diagrams. See this [StackExchange Q&A](https://softwareengineering.stackexchange.com/questions/404403/what-is-the-difference-between-a-qualified-association-and-an-association-class) for a description and example of a qualified association.

This is somewhat related to the feature request #1604 for association classes.

### Example

`Student [courseId: string] --> Course`

**Comment by jgreywolf** [comment]
Closing this as a "duplicate", and moving your comment to that issue
