### ISSUE TITLE
Multi directional arrows have heads of different sizes

### ISSUE THREAD

**Issue by Zannick** [mermaid-js/mermaid#4195]
### Description

In a simple flowchart with multi-directional (bidirectional) arrows, the left arrow head is about 2x the width and height each of the right head.

### Steps to reproduce

Create a graph or flowchart with a double-ended arrow:
```mmd
graph LR
C <--> F[fa:fa-car Car]
```
like so
```mermaid
graph LR
C <--> F[fa:fa-car Car]
```

but on the live demo or using the cli

### Screenshots

[![](https://mermaid.ink/img/pako:eNoVjDEOwjAQBL9iXR1_wEI0QVRUUGKKlX0mEbGNLmchFOXvmKm2mJ2NQo1MjtJSP2GCqLlcfTGd0RysPZ7vCS7BBogZIQ8aKLNkzLGftr_pSSfO7Mn1GSEvT77s3UPTevuWQE6l8UDtHaF8mvEUZOrRZeX9B0bPKgs?type=png)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNoVjDEOwjAQBL9iXR1_wEI0QVRUUGKKlX0mEbGNLmchFOXvmKm2mJ2NQo1MjtJSP2GCqLlcfTGd0RysPZ7vCS7BBogZIQ8aKLNkzLGftr_pSSfO7Mn1GSEvT77s3UPTevuWQE6l8UDtHaF8mvEUZOrRZeX9B0bPKgs)

renders like this for me: ![Screenshot 2023-03-06 204954](https://user-images.githubusercontent.com/518709/223323631-9e0292d7-9d4f-4016-8573-717865174c7c.jpg)

Using the linux CLI on my real graph:
![Screenshot from 2023-03-06 20-54-26](https://user-images.githubusercontent.com/518709/223324773-4c027f6e-693d-4637-b1ef-0e863c247081.png)

### Code Sample

```mmd
graph LR
A <--> B
```

### Setup

CLI:
mmdc version: 10.0.0

Live demo:
Mermaid version: 10.0.0
Browser and Version: Chrome Version 110.0.5481.178 (Official Build) (64-bit)

### Additional Context

generated svg taken from the live demo. Notice the viewBoxes are different sizes. Changing the `pointEnd` viewBox in developer tools to `0 0 10 10` results in an arrow of the same size as the large left arrow. Similarly, changing the `pointStart` to `0 0 12 20` results in the arrow shrinking to the same size as the right arrow.
```svg
<marker orient="auto" markerHeight="12" markerWidth="12" markerUnits="userSpaceOnUse" refY="5" refX="10" viewBox="0 0 12 20" class="marker flowchart" id="flowchart-pointEnd"><path style="stroke-width: 1; stroke-dasharray: 1, 0;" class="arrowMarkerPath" d="M 0 0 L 10 5 L 0 10 z"></path></marker>
<marker orient="auto" markerHeight="12" markerWidth="12" markerUnits="userSpaceOnUse" refY="5" refX="0" viewBox="0 0 10 10" class="marker flowchart" id="flowchart-pointStart"><path style="stroke-width: 1; stroke-dasharray: 1, 0;" class="arrowMarkerPath" d="M 0 5 L 10 10 L 10 0 z"></path></marker>
```

**Comment by bhearsum** [comment]
I'm hitting this as well. The problem appears to worse the deeper the graph is. Here's [an example on the live editor](https://mermaid.live/edit#pako:eNo9j8EKgzAQRH8l7Nn8gJRCi9CTtFCPuSxm1VCTDWukFPHfm1Zb9jJvZ2CYBVq2BCV0Iz_bASWppjJBqVOMI6mD1vqozhjy7XAVDP3mZLoRyk_X2eA9dRGMNO3QsMfEUIAn8ehsrls-HQbSQJ4MlFlalIcBE9acwznx_RVaKDscJypgjhYTVQ57Qf__knWJpd4GfHesb31HQM4):
![image](https://user-images.githubusercontent.com/49649/224707230-72f60c58-b621-4f83-aac7-fbed7b73f2c8.png)

(And when you go deep enough, one side of the arrowheads end up becoming almost entirely invisible.)

**Comment by nekr0z** [comment]
Still an issue in 10.0.2: live editor and Mermaid documentation website, Firefox.
