### ISSUE TITLE
"Upgrade" from 10.0.2 to 9.4.2 ?

### ISSUE THREAD

**Issue by AlbinoGeek** [mermaid-js/mermaid#4200]
### Description

When I run `yarn upgrade-interactive`, `9.4.2` shows as an update from `10.0.2`.

### Steps to reproduce

1. `yarn install mermaid@^10.0.2`
2. `yarn upgrade-interactive`

### Screenshots

![image](https://user-images.githubusercontent.com/1910461/223509428-d11e13e7-6f25-4033-ab1f-8c347c0c3ebf.png)

### Setup

N/A

### Additional Context

This is the first package I've seen a lower version as an upgrade for (outside of maybe CentOS, where it was pretty frequent that they'd iterate the EPOCH value of a package, rather than its version, to force you to `upgrade` to an older version.)

**Comment by sidharthv96** [comment]
@AlbinoGeek thanks for pointing this out. It's the first time we've released older versions. 

Can you check if it's fixed now?

**Comment by sidharthv96** [comment]
Seems like a footgun that's been around for a while. 
https://github.com/npm/npm/issues/6778

**Comment by sidharthv96** [comment]
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/10703445/223521640-ce099bc5-c765-48d5-adf2-4373bfea75b4.png">

Fixed with
```bash
❯ npm dist-tag add mermaid@10.0.2 latest                                                          
```

**Comment by AlbinoGeek** [comment]
Sweet :)  That solves dependabot screaming at me in 100-licate.
