### ISSUE TITLE
32MB in mermaid@10.0.2/dist/ with duplicate files? 

### ISSUE THREAD

**Issue by frehberg** [mermaid-js/mermaid#4203]
### Description

When I port  Rust-aquamarine from mermaid 9.2 to to mermaid 10.0.2 (https://github.com/mersinvald/aquamarine/issues/35), it seems the JS footprint has grown from 900KB to 32MB. I hope this can be reduced to smaller bytesize, picking the essential files from folder https://unpkg.com/browse/mermaid@10.0.2/dist/ 

As stated by release notes, the mermaid package mermaid.min.js has been split into multiple packages, just I hope not all 262 files in folder https://unpkg.com/browse/mermaid@10.0.2/dist/ are required.

All in all this folder contains 32MB, in contrast to ca 900KB  of former mermaid.min.js

As the JS files shall be  shipped with the  Rust-Library "aquamarine" the size of 32MB is a bit too large. 

Please tell me, If the following import statement would be used, which further files does it depend on? What is the JS file-set to be shipped as bundle?  Is there a npm-run command  to filter out these files as a bundle using an automated process? 
```
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
```

### Steps to reproduce

Check the content of ttps://unpkg.com/browse/mermaid@10.0.2/dist/ 
For me it not clear which files are required if importing https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs

### Setup

- Mermaid version:  10.0.2
- Browser and Version: rustdoc html build  process embedding mermaid diagrams via https://github.com/mersinvald/aquamarine

**Comment by ochowei** [comment]
Hi, 

according to the snippet
https://github.com/mermaid-js/mermaid/blob/8b37ceffe1a4c182f3e0bbf06c6b35622a0fccb1/.vite/build.ts#L120
I noticed that in the build process, mermaid build 3 different configs. so the folder size growth to 32MB. This could cause some issues with storage and deployment.

Maybe we can put the result in different subfolder or different prefix in the dist folder?

**Comment by sidharthv96** [comment]
The majority of the size is `.map` files.

**Comment by sidharthv96** [comment]
@ochowei it's done with https://cdn.jsdelivr.net/npm/mermaid@11.0.0-alpha.3/dist/

@frehberg you'll be able to ship [mermaid.tiny.min.js](https://cdn.jsdelivr.net/npm/mermaid@11.0.0-alpha.3/dist/mermaid.tiny.min.js) which is only 1.07MB, compared to 3.3MB of [mermaid.min.js](https://cdn.jsdelivr.net/npm/mermaid@11.0.0-alpha.3/dist/mermaid.min.js)

And all the required chunks of [mermaid.esm.min.mjs](https://cdn.jsdelivr.net/npm/mermaid@11.0.0-alpha.3/dist/mermaid.esm.min.mjs) is now safely inside [chunks/mermaid.esm.min/](https://cdn.jsdelivr.net/npm/mermaid@11.0.0-alpha.3/dist/chunks/mermaid.esm.min/)

**Comment by jgreywolf** [comment]
Is this still an open issue?

**Comment by jgreywolf** [comment]
Closing due to no response
