### ISSUE TITLE
Actor Menus on Sequence Diagrams do not popup.

### ISSUE THREAD

**Issue by timjstewart1024** [mermaid-js/mermaid#4212]
### Description

When I add links to an actor on a sequence diagram, the actor popup menu does not appear.  I'd greatly appreciate any help with this issue!

### Steps to reproduce

To reproduce the issue:

1. Copy the example mermaid text from [the Actor Menu documentation](https://mermaid.js.org/syntax/sequenceDiagram.html):

```
sequenceDiagram
    participant Alice
    participant John
    link Alice: Dashboard @ https://dashboard.contoso.com/alice
    link Alice: Wiki @ https://wiki.contoso.com/alice
    link John: Dashboard @ https://dashboard.contoso.com/john
    link John: Wiki @ https://wiki.contoso.com/john
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
```

2. Paste it into the code panel of https://mermaid.live/ 
3. Hover over the Alice and John actors and any other parts of the diagram.
4. I would expect a popup menu to appear but one does not.

I have tried adjusting the securityLevel in the config to "loose" but that does not help.
I have tried the forceMenu option which causes the popup menu to display all the time.

### Code Sample

```text
https://mermaid.live/edit#pako:eNqVUsFOwzAM_ZXgG1LXtWvXtTkMkCaBEJw4IKFeQuvRsDQpacoo0_6drBnaJiQQuTh-ee_Zkb2BQpUIFFp861AWuODsRbM6l8SehmnDC94waciV4AX-hG9VJR0quFw5FiUL1lbPiumSXJLKmKal43H5jfmFkka1ysZ6zA62xwaPfMWPtGub_irbtfGfsq-nbTv5X0UPoqHL0XzudDcohBo8PFKpNWEaSa-6C8fd4SPL3f_sWiMzZ8c2587lAQcVEcygtgTwoEZdM17a8Wx2ghxMhTXmQO21xCXrhMnBc08tFp3mpr_DdxSOIpRqLTuXW-vFOqMeelkANbpDD7qmtIX24wa6ZKK1qJ3pk1InOdANfACdhZEfBEmUTrNplkVJ5kEPdBROQj9OkkkYxEGYJmm69eBzcAj9aTxLkzDIskkchUnsAZbcKH3vNm5YvO0X7iXQLA
```

### Setup

- Mermaid version: Live editor version as of March 10, 2023
- Browser and Version: Chrome 111.0.5563.64

**Comment by jontreynes** [comment]
I'm experiencing the same as @timjstewart1024 

Actually on Azure DevOps wiki and on the  Vscode extension Markdown Preview Mermaid v1.20.0 by Matt Bierner
