### ISSUE TITLE
Mindmaps are not rendering

### ISSUE THREAD

**Issue by bittib010** [mermaid-js/mermaid#4214]
### Description

Also happens in your repo docs on mindmaps.

### Steps to reproduce

https://github.com/mermaid-js/mermaid/blob/6b251de227d999af7371e4928445193fe3a6de54/packages/mermaid/src/docs/syntax/mindmap.md

Read this. Currently Im running windows 10, chrome browser

### Setup

Windows10
Chrome
fully updated

**Comment by tomperr** [comment]
I don't have any problem on my laptop, mindmaps render correctly.

@bittib010 Do you still have the issue?

**Comment by bittib010** [comment]
Funny thing.. nope, not an issue now. I tried different browsers and mobile (android) when trying out this feature - everyone failed in loading the mindmap, and now it has magically returned as functioning again. weird..
