### ISSUE TITLE
Unable to use name starting with a digit for ER diagram attributes

### ISSUE THREAD

**Issue by kdrvn** [mermaid-js/mermaid#4222]
### Description

I want to be able to use names starting with a digit in my ER diagrams.

### Steps to reproduce

Use the code sample below.

### Screenshots

![image](https://user-images.githubusercontent.com/4067874/225268429-afe1ffe2-3e2e-4032-8692-acea74c905f0.png)

### Code Sample

```text
erDiagram
  ExampleEntity {
    integer id PK
    boolean 2fa_enabled
  }
```

### Setup

- Mermaid version: 9.4.0
- Browser and Version: Edge

**Comment by jgreywolf** [comment]
Closing as we are going to keep with standard definitions for naming conventions, which do not allow attributes to being with a number
