### ISSUE TITLE
User Journey Diagram section label not spanning full section.

### ISSUE THREAD

**Issue by edmund-leibert** [mermaid-js/mermaid#4224]
### Description

<details open>
  <summary><h1>Preface</h1></summary>

Afternoon, I hope all is well. 

Mermaid currently does _**not**_ correctly make the section label of the User Journey Diagram. 
</details>

<details open>
  <summary><h1>Intended Outcome</h1></summary>

As the documentation shows, the section label is supposed to have width that spans/covers all tasks in it. For better visualization, refer to the correctly rendered **User Journey Diagram** as rendered on the [Mermaid Documentation](https://mermaid.js.org/syntax/userJourney.html)...

![image](https://user-images.githubusercontent.com/43337293/225541869-a9a8c314-a8ec-44fe-9fa8-46e60a5cbdce.png)
</details>

<details open>
  <summary><h1>Current Outcome</h1></summary>
As can seen in the [Mermaid Live Editor](https://mermaid.live/) the section label does **not** span all tasks.

![image](https://user-images.githubusercontent.com/43337293/225548914-929e7edb-dd4d-47d1-9010-a2045eafaade.png)

</details>

### Steps to reproduce

1. Go to the [Mermaid Live Website](https://mermaid.live/)
2. Using Mermaid Live, test the following code _below_ to render a simple User Journey.
```
journey
    title My working day
    section Go to work
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Go home
      Go downstairs: 5: Me
      Sit down: 5: Me
```
4. Notice the difference between the diagram rendered in the official [Mermaid Documentation](https://mermaid.js.org/syntax/userJourney.html) and the one rendered in Mermaid Live

### Code Sample

```text
https://mermaid.live/edit#pako:eNplj70KwzAMhF9FaM5SShevLXTKlDWLiEXitraCIxNCyLvXzQ-0VJP47nSSZmzEMhp8SIqBpzpALnX6YignGCU-XWjB0q4M3KiTAHcBlVXeOEBJTwZlMnAxUPKBszH1g5KLg4Hzt3Lb5g2cPrSAK-nfjk78d5KVMRxZP1sqp6u4YyzQc_TkbP5s_phq1I5zFprcWspnYx2W7KOkUk2hQaMxcYGpt6R8c9RG8htc3r_RWxA
```

### Setup

- Mermaid version: v9.4.0 - v10.0.0
- Browser and Version: [Chrome, Edge, Firefox]

### Additional Context

- Interestingly enough, the User Journey is correctly rendered in Markdown in GitHub, but **not** on the following editors...
- VS Code (Using the Markdown Preview Mermaid extension which uses Mermaid v9.4.0)
- Mermaid Live (As of Mermaid v10.0.0)

**Comment by edmund-leibert** [comment]
Feel free to let me know if there is any further information you require of me. I will try to track down where else this bug happens. Look forward to hearing any feedback, corrections, etc. :)

**Comment by ochowei** [comment]
The current version of the live editor is 10.0.0. I downloaded and launched 10.0.1 from [mermaid-live-editor](https://github.com/mermaid-js/mermaid-live-editor) and found that this issue has already been resolved. It seems that once 10.0.1 is deployed online, this problem will be resolved.

**Comment by edmund-leibert** [comment]
> The current version of the live editor is 10.0.0. I downloaded and launched 10.0.1 from [mermaid-live-editor](https://github.com/mermaid-js/mermaid-live-editor) and found that this issue has already been resolved. It seems that once 10.0.1 is deployed online, this problem will be resolved.

@ochowei Alright, perfect! Thanks for the heads up.
