### ISSUE TITLE
Setting a callback as the documentation says raises a TypeError

### ISSUE THREAD

**Issue by Andromelus** [mermaid-js/mermaid#4262]
### Description

Using this [piece of documentation](https://mermaid.js.org/syntax/flowchart.html#interaction) (the last code block containing the full example), I get a TypeError:

```
utils.ts:265 
        
       Uncaught TypeError: s[r] is not a function
    at Object.Eo [as runFunc] (utils.ts:265:13)
    at SVGGElement.<anonymous> (flowDb.js:312:19)
Eo @ utils.ts:265
(anonymes) @ flowDb.js:312
```

### Steps to reproduce

- Copy the code provided in an html file.
- Open it into edge or chrome
- Open the developer console
- Click on the "A" node

### Code Sample

```text
<!DOCTYPE html>
<html lang="en">
  <body>
    <pre class="mermaid">

      flowchart LR
      A-->B
      B-->C
      C-->D
      click A callback "Tooltip"

</pre>

    <script type="module">
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
      
          const callback = function () {
      alert('A callback was triggered');
    };
    const config = {
      startOnLoad: true,
      flowchart: { useMaxWidth: true, htmlLabels: true, curve: 'cardinal' },
      securityLevel: 'loose',
    };
    mermaid.initialize(config);
    </script>
  </body>
</html>
```

### Setup

- Mermaid version: 10
- Browser and Version:
  - Chrome 111.0.5563.147
  - Edge 107.0.1418.42

**Comment by glops** [comment]
I have the same problem.
It works with the old javascript import: 
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.8/mermaid.min.js"></script>
</head>
<body>
    <div class="mermaid">
        graph LR;
        A-->B-->C;
        B-->D;
        click A exampleCallback "Tooltip for a callback"
        click B "http://www.github.com" "This is a tooltip for a link"
    </div>
    <script>
        mermaid.initialize({
            startOnLoad: true,
            securityLevel: 'loose'
        });
        var exampleCallback = function () {
            alert('A callback was triggered');
        }
    </script>
</body>
</html>
```

But is it still possible with the last version (10) ?

**Comment by vesper8** [comment]
I can't get anything to do with custom callbacks or tooltips to work with v10

**Comment by Ogglas** [comment]
Any update on this?

JSFiddle with the error: https://jsfiddle.net/Ogglas/2o73vdez/7

Uses Mermaid 10.4 https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.4.0/mermaid.min.js

Error on click:

> mermaid.min.js:10 Uncaught TypeError: m[v] is not a function
>     at Object.DCe [as runFunc] (mermaid.min.js:10:469)
>     at SVGGElement.<anonymous> (mermaid.min.js:101:15571)

**Comment by GRASBOCK** [comment]
Most likely related: 
https://github.com/mermaid-js/mermaid/issues/5510

**Comment by sidharthv96** [comment]
Fixed in https://github.com/mermaid-js/mermaid/pull/5517
