### ISSUE TITLE
flowchart's arrow is too small with mermaid v9.4.3

### ISSUE THREAD

**Issue by dantezhu** [mermaid-js/mermaid#4266]
### Description

flowchart's arrow is too small with mermaid v9.4.3, but in v9.0.0, it is all right.

v9.4.3: 
![image](https://user-images.githubusercontent.com/1105212/229174937-7c488745-0a1e-401e-b753-ff9e8db2682d.png)

v9.0.0: 
![image](https://user-images.githubusercontent.com/1105212/229175152-73c02b69-2e0e-414e-951c-89bb7832eb4b.png)

### Steps to reproduce

1. code like this:
    ```
    flowchart TD
        A[Christmas] -->|Get money| B(Go shopping)
        B --> C{Let me think}
        C ==>|One| D[Laptop]
        C ==>|Two| E[iPhone]
        C ==>|Three| F[fa:fa-car Car]
    ```

    will show like this:

    ```mermaid
    flowchart TD
        A[Christmas] -->|Get money| B(Go shopping)
        B --> C{Let me think}
        C ==>|One| D[Laptop]
        C ==>|Two| E[iPhone]
        C ==>|Three| F[fa:fa-car Car]
    ```

    ![image](https://user-images.githubusercontent.com/1105212/229174937-7c488745-0a1e-401e-b753-ff9e8db2682d.png)

2. but the old version(v9.0.0)'s arrow is big and clear.   
    ![image](https://user-images.githubusercontent.com/1105212/229175152-73c02b69-2e0e-414e-951c-89bb7832eb4b.png)

### Screenshots

v9.4.3: 
![image](https://user-images.githubusercontent.com/1105212/229174937-7c488745-0a1e-401e-b753-ff9e8db2682d.png)

v9.0.0: 
![image](https://user-images.githubusercontent.com/1105212/229175152-73c02b69-2e0e-414e-951c-89bb7832eb4b.png)

### Setup

- Mermaid version: v9.4.3
- Browser and Version: Chrome

**Comment by legonigel** [comment]
Should be already fixed with #4286
