### ISSUE TITLE
Diagram proposal: 2 x 2 matrix

### ISSUE THREAD

**Issue by tobie** [mermaid-js/mermaid#4282]
### Proposal

2 x 2 matrices are commonly used to break down complex problems along two key variables.

They can be used to position different options precisely in this matrix, e.g.: Gartner Magic Quadrants come to mind.

![Example of a Gartner Magic Quadrant](https://cdn.sisense.com/wp-content/uploads/Gartner-2022-Grid.png)

```
matrix2x2
    title Gartner Magic Quadrant
    x-axis Completeness of Vision ->
    y-axis Ability to Execute ->
    quadrant I Leaders
    quadrant II Challengers
    quadrant III Niche
    quadrant IV Visionaries
    Microsoft: [0.75, 0.75]
    Salesforce: [0.55, 0.60]
    IBM: [0.51, 0.40]
    Incorta: [0.20, 0.30]
```

Or they can be more abstract and expose just four concepts covered by those two variables, the Eisenhower Matrix comes to mind:

![Example of the Eisenhower Matrix](https://www.norberthires.blog/content/images/2022/01/the-eisenhower-matrix.png)

```
matrix2x2
    title Eisenhower Matrix
    x-axis Urgent -> Not Urgent
    y-axis Not Important -> Important
    quadrant I Plan
        Some additional text here.
    quadrant II Do
    quadrant III Delegate
    quadrant IV Delete
```

**Comment by sidharthv96** [comment]
Notes to implementors.

If there are no Points to mark in the chart, the labels of quadrants should come to the center. 
I have some doubts on the format for x,y axis labels. `start --> end` or  `[start, end]`


```
---
title: Title of chart, will be handled automatically
---

quadrantChart
    x-axis start --> optional end
    y-axis "start with unicode ❤" --> "optional end with unicode ❤"
    quadrant-1 "Label with unicode ❤"
    quadrant-2 Text label
    quadrant-3 Text label
    quadrant-4 Text label

%% section below is optional
    "Point with unicode ❤": [x, y]
    "Point with : colon": [x, y]
    Text point: [x, y]
```

- `0 <= (x,y) <= 1`
- x & y axis is optional
- Axis label ends are optional

We might also need some config values for where to place the axis labels. Sides (top/bottom, left/right) or start&end


Referred some examples at https://psychology.stackexchange.com/questions/22038/what-is-this-type-of-graph-called.

**Comment by amsubhash** [comment]
Hi @sidharthv96 I want to take this task can you please assign it to me?

**Comment by sidharthv96** [comment]
@amsubhash everyone is free to work on issues without open PRs no need to ask for assignment 😄

**Comment by amsubhash** [comment]
Ok got it thanks, will raise a PR as soon as possible

**Comment by amsubhash** [comment]
@sidharthv96 @knsv I have implemented the chart, I am thinking first please check the UI and the configuration and finalize them then I can write the docs and the unit/e2e test cases. please let me know how I can proceed.

**Comment by amsubhash** [comment]
@sidharthv96 I Have pushed the changes you suggested along with test cases and documentation, also I have removed it from the draft state.

**Comment by sidharthv96** [comment]
Quadrant chart is available in live editor now!
