### ISSUE TITLE
`@khanacademy/simple-markdown` imposes peer dependency on an old version of react

### ISSUE THREAD

**Issue by segevfiner** [mermaid-js/mermaid#4302]
### Description

When using `pnpm`:
```
 WARN  Issues with peer dependencies found
packages/swmd
└─┬ mermaid 10.1.0
  └─┬ @khanacademy/simple-markdown 0.8.6
    ├── ✕ missing peer react@16.14.0
    └── ✕ missing peer react-dom@16.14.0
Peer dependencies that should be installed:
  react-dom@16.14.0  react@16.14.0  
```

This is annoying, it forces projects to bring in react, and it forces them to an ancient version.

### Steps to reproduce

1. Install mermaid using `pnpm <=7`: `pnpm i mermaid`.

### Setup

- Mermaid version: 10.1.0
- Browser and Version: Chrome 112.0.5615.49

**Comment by sidharthv96** [comment]
@knsv

**Comment by knsv** [comment]
@segevfiner Thanks of reporting, we are not using react so we don't need to have it in the dependencies!

**Comment by sidharthv96** [comment]
React seems to be a critical dependency for the package. We'll have to figure out alternatives.

**Comment by remcohaszing** [comment]
I recommend to have a look at the [unified](https://unifiedjs.com) ecosystem. I haven’t really looked at how `@khanacademy/simple-markdown` is used, but my guess is Mermaid needs something like:

- [`mdast-util-from-markdown`](https://github.com/syntax-tree/mdast-util-from-markdown): parse markdown to mdast (markdown AST)
- [`mdast-util-to-hast`](https://github.com/syntax-tree/mdast-util-to-hast): convert mdast to hast (HTML AST)
- [`hast-util-to-dom`](https://github.com/syntax-tree/hast-util-to-dom): convert hast to DOM nodes

**Comment by sidharthv96** [comment]
@knsv we're already using mdast in docs.mts. Works very well.

**Comment by nathanlesage** [comment]
I can chime in that this issue prevents Zettlr from upgrading to Mermaid v10.x.

Additionally, I have just had a look at the repo, and noticed two issues:

1. It hasn't been updated in >2 years
2. It even has a _deprecation notice_, indicating that it should no longer be used by developers

I can also recommend unified's `remark`. Depending on how it is being used, however, it is important to have a look here: https://github.com/micromark/micromark-extension-frontmatter/issues/5

YAML frontmatter syntax can currently cause errors in properly building the Markdown AST for unified.

**Comment by jgreywolf** [comment]
Is this still an open issue?  I see one PR was merged to address SimpleMarkdown

**Comment by jgreywolf** [comment]
Closing due to no response
