### ISSUE TITLE
mmdc encoding issue 

### ISSUE THREAD

**Issue by borchersj** [mermaid-js/mermaid#4319]
### Description

I want to make a md-mermaid diagramm as a png in my html documentation. I use Sphinx as documentation tool. 
Everthing works fine, except the portrayal of the german "Umlaute" (Ä,,Ö,Ü, ä,ü,ö). 

### Steps to reproduce

My mermaid-diagram look like this: 

```{mermaid}
  flowchart TB
    id0[homabs_kennwerte_final] -- "Eingangstabelle<br>erstellen" --> id1[eingangstabelle_base]
    id1 -- "filtern p_gesamt_valids<br>größer 50 Prozent,<br>Tabelle anpassen für dtims" --> id2[eingangstabelle_final]
    
    style analysedaten stroke-width:2px, stroke-dasharray: 5 5
    subgraph analysedaten
      direction TB
      id0
    end
    subgraph dtims
      direction TB
      id1
      id2
    end
```

### Screenshots

![mermaid-d8c7a941a9d5f7b481b01f15b217f0825384ea0d](https://user-images.githubusercontent.com/130153474/233071019-a70b89ef-8c22-453e-9ba4-a6d33720d979.png)
The Output-Diagram looks like i expected, except the "Umlaute". 

### Code Sample

```text
Parts of my Sphinx conf.py

extensions = [
'myst_parser',
'sphinxcontrib.mermaid', 
'sphinx.ext.imgconverter']

mermaid_cmd = "../mmdc.cmd"
mermaid_output_format = "png"
mermaid_params = ['--theme', 'forest', '--width', '1850','--backgroundColor', 'transparent']
```

### Setup

- Sphinx version: 5.0.2
- mmdc version: 10.1.0
- Browser and Version: [Chrome, Edge, Firefox] --all

**Comment by sidharthv96** [comment]
Seems to be a problem with local machine/fonts. 
Renders properly in GitHub for me.

```mermaid
  flowchart TB
    id0[homabs_kennwerte_final] -- "Eingangstabelle<br>erstellen" --> id1[eingangstabelle_base]
    id1 -- "filtern p_gesamt_valids<br>größer 50 Prozent,<br>Tabelle anpassen für dtims" --> id2[eingangstabelle_final]
    
    style analysedaten stroke-width:2px, stroke-dasharray: 5 5
    subgraph analysedaten
      direction TB
      id0
    end
    subgraph dtims
      direction TB
      id1
      id2
    end
```

<img width="309" alt="image" src="https://user-images.githubusercontent.com/10703445/233254293-2f90f6e9-b3ad-4f75-bea2-b0c2c2b5b05a.png">

**Comment by sidharthv96** [comment]
Also working in live editor: https://mermaid.live/edit#pako:eNp9ks9u2zAMxl9F0NlpYmdJW2PoYViPAwasp9WFQVu0LVR_DIlu5gV5lr3FTrvlxSZFTYZuwHQQiE_k7yMo7nlrBfKSM9Ypu2sHcMQePlSGhSPF6nGwGhpfP6MxO3SEdScNqCe2WLCK30vTg-k9QYNK4fvG3aHzFGNT8ZBzFxj5I75Nqxvw-HS2yBOqk4rQGTbWPXrQVL-AksJHZO-OP48_0LHNin129jsayqL-kHAMzAjeo2Hd8ZdjgqT2F_PiH_PUf3JPt6f5RAE1exRAgeTJ2Wdc7KSgoSzGb9lZEeDDiBzMJduwzWv91PQOxuENIj0xJqTDlqQ1l6me5ppCNOIvROr-v7X5n7C4YHjGNToNUoS_3Ee54jSgxoqXIRTYwaSo4pU5hNRpjD3eC0nW8bID5THjMJH9MpuWl-QmPCd9lBA602dxBPPVWn0pwhPjU9qh0yplXFkQGLh7TvMY9V56CnprTSf7qE9OBXkgGn25XMbnq17SMDVXrdVLL0Vcw-HldrvcFtsbKNa4vV7DZr0WbZPf3nTFu7wT16u8AH44HH4DQELt9w

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/10703445/233254426-d1eca9a4-5699-45b7-93b1-bbecec94460b.png">
