### ISSUE TITLE
add a "<--" symbol pointing from the right to the left 

### ISSUE THREAD

**Issue by yangeos** [mermaid-js/mermaid#4336]
### Proposal

How about adding a 
<-- arrow to make the right to left pointing ??

### Example

a <-- b
will be rendered like
[a]<--[b]

**Comment by sidharthv96** [comment]
```mermaid
flowchart LR
  a --> b
  b --> a
```

Currently, left pointing arrows are possible by switching the nodes. 

Can you share a scenario where `<--` would be useful?

**Comment by tomperr** [comment]
Duplicate of #3208

**Comment by jgreywolf** [comment]
Closing as duplicate
