### ISSUE TITLE
currentConfig is incorrectly bundled over multiple files

### ISSUE THREAD

**Issue by luttje** [mermaid-js/mermaid#4345]
### Description

I'm noticing that currentConfig (in config.ts) is incorrectly split by Vite/RollUp over multiple files. This causes some scripts to not get the same currentConfig as others.

### Steps to reproduce

I am trying to add a `curve` configuration option to the ER diagram. That is where I ran into this issue. The only relevant code needed to reproduce this issue:

1. Add `curve?: string;` to `interface ErDiagramConfig` in `packages/mermaid/src/config.type.ts`
2. Add `curve: 'basis',` to `config.er` in `packages/mermaid/src/defaultConfig.ts`
3. Add `er: { curve: 'step' },` to the config object in `mermaid.initialize` in `demos/er.html`
4. For debugging add: `console.trace(conf.curve)` at the top of `drawRelationshipFromLayout` in `packages/mermaid/src/diagrams/er/erRenderer.js`
5. `pnpm run dev`

It should be expected that the console.log logs 'step', but instead it logs 'basis'. If you inspect in the browser which files exist, you will see two files containing `let currentConfig` and an exported `getConfig` function. This means some code uses a different config than others.

### Screenshots

![image](https://user-images.githubusercontent.com/2738114/234269012-5ee1ebc4-ce13-45de-81aa-237a8ea9434a.png)
![image](https://user-images.githubusercontent.com/2738114/234268994-865cc04d-1f53-4fc3-95a6-304ec03127b1.png)

### Code Sample

[fork](https://github.com/mermaid-js/mermaid/compare/develop...luttje:mermaid:feature/diagrams_curve_shape)

### Setup

- Mermaid version: 10.1.0
- Browser and Version: All (since it's a bundler issue), but tested on:
  - Chrome: Version 112.0.5615.138 (Official Build) (64-bit)
  - FireFox: Version 112.0.1 (64-bit)

### Additional Context

I've tried messing with these options inside `.vite/build.ts`, but to no avail (my knowledge of Vite and Rollup is insufficient atm):
- https://rollupjs.org/configuration-options/#output-manualchunks
- https://rollupjs.org/configuration-options/#output-inlinedynamicimports
- https://rollupjs.org/configuration-options/#output-preservemodules

Thanks for the great project, loving it!

Hope this bug report helps, let me know if you need more info 😊

**Comment by mootari** [comment]
Unfortunately this is happening again when loading mermaid-js via JSDelivr / esm.run.
