### ISSUE TITLE
[Docs Suggestion] - sequence diagram participant aliasing - line breaks

### ISSUE THREAD

**Issue by dazinator** [mermaid-js/mermaid#4351]
I am new to mermaid.js and using the live editor to create a sequence diagram and reading the docs, it took me a long time to work out how to make the name of the actor | particpant span multiple lines.

I eventually worked it out that you must do this:

```
  participant MySuperLongName as My Super<br>Long Name
```

It would be really nice to update the docs to include something about this. Aliasing is mentioned, but it wasn't clear that this is the only mechanism to introduce new lines into actor names.

**Comment by abitrolly** [comment]
@dazinator thanks for the pointer!

Here is the page to be fixed https://mermaid.js.org/syntax/sequenceDiagram.html#aliases
