### ISSUE TITLE
drawExcludeDays() in gannt chart renderer can loop infinitely 

### ISSUE THREAD

**Issue by toolness** [mermaid-js/mermaid#4353]
### Description

Creating certain kinds of gannt charts will cause the Mermaid renderer to hang.  Looking at the debugger, it appears to be stuck infinitely iterating over this loop:

https://github.com/mermaid-js/mermaid/blob/32d553a28fda9130417591403d2531cb56fa8626/packages/mermaid/src/diagrams/gantt/ganttRenderer.js#L497-L514

### Steps to reproduce

Try rendering the attached Mermaid code in the live editor, it will hang.

(Note that while you can paste this into the Mermaid live editor, you'll probably want to reset its site data after experiencing the hang, as the live editor appears to always load its previous input on page load.)

### Code Sample

```text
gantt
    title PlanA release schedule
    dateFormat YYYYMMDD
    axisFormat  %m/%d
		tickInterval 2day
		todayMarker off

				foo: blarg, 20230320, 20230513
        bar: milestone, prodthingy, 20230417, 0d

    section staging　release
				Auth build : active, BOOP, 20230301, 20230420
				Auth stg release: crit, BOOPstg, after BOOP, 1d
				BONK set up : BLOP, 202304, 20d
				BONK stg release: crit, BLOPstg, after BLOP, 1d
    section test
				Auth test: BOOPtest, after BOOPstg, 7d
				BONK test: BLOPtest, after BLOPstg, 20230511

    section product release
        prod release: crit, release, 20230512, 1d
```

### Setup

- Mermaid version: 10.1.0
- Browser and Version: Tested on Chrome 112.0.5615.137 and Safari 16.3.

- Note that **this bug does not occur on Firefox 112**, which throws a `Invalid date:202304` error.  Perhaps this suggests that Chrome and Safari may be parsing dates in a way that leads to some kind of infinite loop?

**Comment by toolness** [comment]
Update: I just discovered that this bug _doesn't_ occur on Firefox.  Added the following to the issue description

> - Note that **this bug does not occur on Firefox 112**, which throws a `Invalid date:202304` error.  Perhaps this suggests that Chrome and Safari may be parsing dates in a way that leads to some kind of infinite loop?

**Comment by toolness** [comment]
Hmm, maybe I should just fix this myself?  @sidharthv96 if i want to try fixing it myself, should I just go ahead and do it, or does the issue need to be assigned to me first?

**Comment by sidharthv96** [comment]
@toolness that'd be great. 

You don't have to be assigned to start working on issues. All open issues without PRs are for everyone to take a shot at.

**Comment by toolness** [comment]
@sidharthv96 also, I'd like to make another documentation PR which I describe here, let me know if you think it's a good idea: https://github.com/mermaid-js/mermaid/issues/866#issuecomment-1531658882
