### ISSUE TITLE
Days of the week not matching date on Gantt charts in labels

### ISSUE THREAD

**Issue by caffo** [mermaid-js/mermaid#4355]
**Describe the bug**

Days of the week on Gantt chart labels are not matching dates entered on the chart

**To Reproduce**
Link to Live Editor: 

https://mermaid.live/edit#pako:eNptkdtKAzEQhl8ljBQUsmWz5-ZSiujF3qggyt4Mm1TDdpMlm54sfXfHtuIB5ybhz__NTGb20DqlQcIr2hAayxQGfeN8j4GxZ4qorqP5nB4oRt0G4yy7xrZjt67XJ_nRm4H9Dtl6EzhdlB4TzpJYpFGcRUJwJtSJql3PjGX3xn1TSPnX-n8uPXNPWnd_qylniSJG_GBiqrVpLG7NeP7Q5Dma9NFEscsJXjU2mLa7s0H7NS6pLdyR5Oio0XfaszF41-loY1R4kywftvykyIt4EXM3YGvCTsbTvLHAoddUwiia5P6zzwbCm6YBgaSr0gtcLUMDjT2QFVfBPexsCzL4leawGj6HPjf46rEHucDlSOqA9sW5_suklQnO16dlHXd2tIDcwxZkUUyTskrFLElEWWVFyWEHMk3SaT6rZmkq8qwQVZofOLwfkybTsppVWV7GeUy2rCoOH-Qelyg

Check labels on the chart: 2013-04-10 should be monday, but at least for me, it's showing as wed:

<img width="287" alt="CleanShot 2023-04-10 at 13 06 08@2x" src="https://user-images.githubusercontent.com/456/230942433-769861d0-5995-415c-9dbe-7bd726235d65.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Arc Browser
- Version 0.96
- Also tested on chrome

**Comment by sashadev-sky** [comment]
It sounds like you meant to put 2023-04-10. 2013-04-10 is on a Wednesday

**Comment by DarshanDixit05** [comment]
I want to work on this issue , can you please assign it to me ?

**Comment by egomezbpedro** [comment]
Hi,

I'm with @sashadev-sky on this one as checking with Google Cal the date for April 10th, 2013 was indeed Wednesday.

2013-04-10
![Captura de Pantalla 2023-05-07 a las 19 27 15](https://user-images.githubusercontent.com/57415533/236693076-1dd23442-fdff-4573-8f34-4a1fb9c5b96e.png)

And April 10th, 2023 was Monday 

2023-04-10
![Captura de Pantalla 2023-05-07 a las 19 27 34](https://user-images.githubusercontent.com/57415533/236693107-f1305312-4791-463d-a00b-e9a05407035b.png)

Hi @caffo, could you confirm if your intended date was 2023-04-10?

**Comment by caffo** [comment]
You are totally right, I missed the *decade* ugh :(

Sorry about wasting your time. It's working as expected. I'm going to close this and hide in shame. Thanks!
