### ISSUE TITLE
eslint failed with out of memory error

### ISSUE THREAD

**Issue by ksilverwall** [mermaid-js/mermaid#4363]
### Description

eslint failed with out of memory error after e2e test executed.

### Steps to reproduce

1. clone this repo
2. init `node_modules` with `npx pnpm install`
3. execute `pnpm run dev` and `pnpm exec cypress open` for e2e test
4. execute some e2e tests on any browser
5. execute eslint

### Screenshots

Error Log
```
% git commit -m "namespace rect is not filled"

> mermaid-monorepo@10.1.0 pre-commit /Users/kazuki_tsunemi/work/mermaid-package/mermaid
> lint-staged

✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ packages/mermaid/.lintstagedrc.mjs — 1 file
    ❯ !(docs/**/*)*.{ts,js,json,html,md,mts} — 1 file
      ✖ eslint --cache --cache-strategy content --fix [SIGABRT]
      ◼ prettier --write
    ↓ cSpell.json — no files [SKIPPED]
    ↓ **/*.jison — no files [SKIPPED]
    ↓ src/docs/** — no files [SKIPPED]
    ↓ src/docs.mts — no files [SKIPPED]
    ↓ src/(defaultConfig|config|mermaidAPI).ts — no files [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ eslint --cache --cache-strategy content --fix:

<--- Last few GCs --->

[71148:0x7fca40040000]    31620 ms: Scavenge 4046.3 (4120.6) -> 4045.8 (4130.6) MB, 10.2 / 0.0 ms  (average mu = 0.799, current mu = 0.653) allocation failure; 
[71148:0x7fca40040000]    31650 ms: Scavenge 4052.4 (4130.6) -> 4051.2 (4131.9) MB, 9.5 / 0.0 ms  (average mu = 0.799, current mu = 0.653) allocation failure; 
[71148:0x7fca40040000]    32567 ms: Scavenge 4053.5 (4131.9) -> 4052.5 (4152.4) MB, 909.0 / 0.0 ms  (average mu = 0.799, current mu = 0.653) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10a5dbeb5 node::Abort() (.cold.1) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 2: 0x109051a69 node::Abort() [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 3: 0x109051c4e node::OOMErrorHandler(char const*, bool) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 4: 0x1091dd653 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 5: 0x1093a6305 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 6: 0x1093a4ce2 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 7: 0x10939701a v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 8: 0x109397995 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 9: 0x109379e0e v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
10: 0x1097afc6c v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
11: 0x109ba57f9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/kazuki_tsunemi/.volta/tools/image/node/18.16.0/bin/node]
 ELIFECYCLE  Command failed with exit code 1.
husky - pre-commit hook exited with code 1 (error)
```

### Setup

- Mermaid version: develop (56ec1ab52ce15ca7dbe76a3acbe1cb68acb13b2d)
- Browser and Version: no browser

### Additional Context

eslint may check the `node_modules`.
When I refresh `node_modules` then error is distinct temporally.

**Comment by Yokozuna59** [comment]
I think this is the issue we're facing: https://github.com/typescript-eslint/typescript-eslint/issues/1192

In case if you don't want to read the thread then here are some solutions:

1. https://github.com/typescript-eslint/typescript-eslint/issues/1192#issuecomment-553259601
2. https://github.com/typescript-eslint/typescript-eslint/issues/1192#issuecomment-565775211
3. https://github.com/typescript-eslint/typescript-eslint/issues/1192#issuecomment-1668264341
4. https://github.com/typescript-eslint/typescript-eslint/issues/1192#issuecomment-1685039178

I think 3rd is more similar use case to us.

**Comment by guypursey** [comment]
I've also had this error. It was preventing me from contributing as the pre-commit hook would run `eslint` and produce this memory issue before I could commit.

I tried the 4 solutions above but didn't have any luck with them (but they might work for others).

I've found that running `pnpm build` before doing anything that starts eslint has helped -- eslint seems to run without hitting the memory issue then.

(I've also found that increasing the memory available to Node through `export NODE_OPTIONS="_max_old_space_size=4096"` can help but your memory situation may vary. This was on my laptop with 8GB RAM.)

**Comment by ilyes-ced** [comment]
i had this problem as well my solution was 
- delete `node_modules` and rerun `npx pnpm install`

you might want to  clear eslint cache as well in `.eslintcache`
and maybe `prettier` too `rm ./node_modules/.cache/prettier/.prettier-cache`

**Comment by ksilverwall** [comment]
Is it necessary to run lint to `node_modules` ?
ignore this dir

**Comment by ilyes-ced** [comment]
> Is it necessary to run lint to `node_modules` ?
> ignore this dir

i don't think the linter lints `node_modules`
for me deleting it and reinstalling worked just fine and this error stopped

maybe it has to do with cache or something

**Comment by sidharthv96** [comment]
Fixed after update to eslint v9
