### ISSUE TITLE
Composite states with multiline title overlaps with starting point

### ISSUE THREAD

**Issue by aryzing** [mermaid-js/mermaid#4402]
### Description

Having a multiline title on a composite state will overlap with the starting point

### Steps to reproduce

```
stateDiagram-v2
    show: First line\nSecond line
    state show {
        [*] --> a
    }
```

### Screenshots

![repro-mermaid](https://github.com/mermaid-js/mermaid/assets/4924405/66e1147c-aed2-43fc-8ae1-ed87c24c25d3)

### Setup

- Mermaid version: v10.1.0
- Browser and Version: Brave v1.51.114

**Comment by knsv** [comment]
This has been fixed in version 11 of Mermaid. Thanks for reporting.
