### ISSUE TITLE
Displaying a chart in markdown from a link in an .mmd file

### ISSUE THREAD

**Issue by PackRuble** [mermaid-js/mermaid#4403]
The question is how can we display the chart in a markdown file if the chart is stored in a .mmd file. 

This is the same behavior as
```md
// file readme.md
![](res/image.png)
```

The picture itself is stored along the path `res/image.png` and thus we can see it immediately in the readme file.

The fact is that the diagrams can be too large, which causes inconvenience when editing the markdown file. Is it possible to specify only a link to the .mmd file so that the diagram appears in the view mode, and not the code itself?

I tried like this:
```md
// file readme.md

<img src="res/chart.mmd" alt=""/>

![](res/chart.mmd)
```
but none of these ways render the chart from file.

**Comment by sidharthv96** [comment]
This is out of scope for mermaid project. 
It would require support of an external service, like mermaid.ink (which supports encoded diagrams, not links to mmd files) to generate an image from a link. The linked mmd file should also be accessible to the server, so it should be publicly accessible.
