### ISSUE TITLE
Mindmap with a node over a certain length causes an infinite loop

### ISSUE THREAD

**Issue by jeffreykwan** [mermaid-js/mermaid#4408]
### Description

When I create a `mindmap` with a node that's over a certain length it causes the browser to crash. I believe it's a infinite loop. I was able to reproduce this using a node with `abcdefghijklmnopqrstuvwxy` or in japanese `プロダクトマネジメントプロ`

Chrome profile (had to zip to upload to Github)
[mermaid infinite loop Profile-20230516T134824.json.zip](https://github.com/mermaid-js/mermaid/files/11491927/mermaid.infinite.loop.Profile-20230516T134824.json.zip)

### Steps to reproduce

[Live Preview link](https://mermaid.live/edit#pako:eNoljDEOgkAQRa9CpoKEE1DrCWin2bAjbmQXss4WhpAYprGxpjPxAMbCxvvMRUTtXt77-SM0vSWowLtgvRkwIMe-5zzfhtYFopjVB9d1x6L4JmSVReWhctb5qXJRualcdX6r3FVeP7NACZ6iN86uxyOGLEPgPXlCqFa0tDOpYwQM0zo1ifv6FBqoOCYqIQ3WMG2caaPxfzl9AK2eRcE)
1. Create a mindmap
2. Add a node named `abcdefghijklmnopqrstuvwxy`
3. Browser crashes

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/1021118/a1e55286-d524-4b81-8b72-3a78887d7276)

### Code Sample

```text
https://mermaid.live/edit#pako:eNoljDEOgkAQRa9CpoKEE1DrCWin2bAjbmQXss4WhpAYprGxpjPxAMbCxvvMRUTtXt77-SM0vSWowLtgvRkwIMe-5zzfhtYFopjVB9d1x6L4JmSVReWhctb5qXJRualcdX6r3FVeP7NACZ6iN86uxyOGLEPgPXlCqFa0tDOpYwQM0zo1ifv6FBqoOCYqIQ3WMG2caaPxfzl9AK2eRcE

or

https://mermaid.live/edit#pako:eNoljEEOgzAMBL8S-QQSL-DcvoCrLy5xISV2aHBoK8Tfm6q31c7OHjAmz9CDBPVCKypaTsma5qpTUObshiXEuLXtD6HRbfR8n-bwWKJoWp95s7K_3tCBcBYKvp4dqM4h2MzCCH2N1aESDQH1rFMqloaPjtBbLtxBWT0ZXwJNmeRfnl8c3jfW

mindmap
	root((Engineer Skills))
		プロダクトマネジメントプロ

mindmap
	root((Engineer Skills))
		abcdefghijklmnopqrstuvwxy
```

### Setup

- Mermaid version: Latest (the version mermaid.live uses)
- Browser and Version: Chrome Version 113.0.5672.92 (Official Build) (arm64)

**Comment by AmalChandru** [comment]
@sidharthv96 Can I try this?

**Comment by sidharthv96** [comment]
Ofcourse. All issues without any PRs are open for everyone to try. :)
