### ISSUE TITLE
Pastebin automatically removes pastes containing mermaid.live and mermaid.ink links 

### ISSUE THREAD

**Issue by GECORegulatory** [mermaid-js/mermaid#4409]
### Description

Greetings,

I am encountering an issue when trying to share mermaid.live or mermaid.ink links via Pastebin. These links are often too long to share directly in many places, so I resort to using Pastebin. However, when I paste the link into Pastebin, it is automatically removed and replaced with the message "This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff." This doesn't seem to be affected by browser, IP address, or account. I also have no other problems using pastebin.

### Steps to reproduce

1. Generate a mermaid.live or mermaid.ink link
2. Share it via pastebin
3. Wait 5-60 seconds and refresh
4. Observe the message: "This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff." 

### Screenshots

https://gyazo.com/0f8f86d0e633ca9802df893905fd4f17

### Setup

- Mermaid version: 10.1.0 
- Browser and Version: Tested on Brave v1.51.114 /Chromium to 113.0.5672.9 (Desktop, Snap Package, Pop_OS), Firefox v1.51.114, and Brave Mobile (Android 12)

### Additional Context

The solution will probably involve contacting the moderators of Pastebin. This issue is Low Priority.

**Comment by sidharthv96** [comment]
Have sent a mail to pastebin admins.

**Comment by jgreywolf** [comment]
@sidharthv96 Have you heard back from pastebin? Im debating closing this issue as not something that can be solved within mermaid itself
