### ISSUE TITLE
404 error when fetching user avatars

### ISSUE THREAD

**Issue by tomperr** [mermaid-js/mermaid#4427]
### Description

On the website, the user avatars of the team members and contributors can't be loaded.

### Steps to reproduce

1. Go on the mermaid website
2. Look at "Meet the Team" and "Contributors" sections
3. Open "Network tab" in your web browser

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/11899139/bd350969-fde7-42f3-aa70-0bca179056e7)
![image](https://github.com/mermaid-js/mermaid/assets/11899139/cf5c29d4-c878-4cf5-a1e0-2b4e654e6fa0)
![image](https://github.com/mermaid-js/mermaid/assets/11899139/cbccca27-cc8b-462d-9abe-4163c16aba50)

### Setup

- Mermaid version: 10.2.0
- Browser and Version: Firefox 113.0.1

**Comment by sidharthv96** [comment]
Fixed in https://github.com/mermaid-js/mermaid/commit/0cec854f3b39f48b65a14a64bc0b2b20fe299d6d
Thanks for reporting @tomperr and @jiashengguo!

<img width="1359" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/d8a2274e-a10a-4d25-9878-81003ab9d1e4">
