### ISSUE TITLE
Nested subgraphs: The first child subgraph breaks if it contains anything

### ISSUE THREAD

**Issue by stefanlasiewski** [mermaid-js/mermaid#4428]
### Description

I was trying to use flowchart and subgraphs to represent a Kubernetes cluster and some nodes in the subgraphs.

I have a subgraph with two or more child subgraphs. The first child subgraph will break if I put anything in to it.

### Steps to reproduce

1. Write the following diagram on https://mermaid.live/ . This will compile, and render a diagram that is included in screenshot1

```
flowchart

  subgraph subgraph1
  end

  subgraph subgraph2
    subgraph subgraph201
    end
    subgraph subgraph202
       box2
    end
  end

  subgraph subgraph3
  end

  subgraph1 --> subgraph2
  subgraph201 --> subgraph3
  subgraph202 --> subgraph3
```

However, if I add text to the  subgraph201, the editor fails with a javascript error at the bottom of the screen that says 👍 

```
Syntax error in text
mermaid version 10.1.0
```

Here's the code to trigger that error. All I did was add the word `box1` to `subgraph201`.

```
flowchart

  subgraph subgraph1
  end

  subgraph subgraph2
    subgraph subgraph201
       box1
    end
    subgraph subgraph202
       box2
    end
  end

  subgraph subgraph3
  end

  subgraph1 --> subgraph2
  subgraph201 --> subgraph3
  subgraph202 --> subgraph3
```

### Screenshots

Screenshot1: ![image](https://github.com/mermaid-js/mermaid/assets/142752/c5b359c4-f31c-4285-9e43-664d9f54b603)

Screensho2:  ![image](https://github.com/mermaid-js/mermaid/assets/142752/90b5095a-1366-4f9d-9ea5-d67f611aae3c)

### Code Sample

```text
flowchart

  subgraph subgraph1
  end

  subgraph subgraph2
    subgraph subgraph201
      %%box1
    end
    subgraph subgraph202
       box2
    end
  end

  subgraph subgraph3
  end

  subgraph1 --> subgraph2
  subgraph201 --> subgraph3
  subgraph202 --> subgraph3
```

### Setup

- Mermaid version: [Mermaidv10.1.0 Live Editor](https://mermaid.live/)
- Browser and Version: Chrome Version 113.0.5672.126 (Official Build) (x86_64)

**Comment by stefanlasiewski** [comment]
Aha, I noticed that I can actually workaround this by adding something before the first subgraph, like so:

```
flowchart

  subgraph subgraph1
  end

  subgraph subgraph2
    this-is-a-workarond
    subgraph subgraph201
       box1
    end
    subgraph subgraph202
       box2
    end
  end

  subgraph subgraph3
  end

  subgraph1 --> subgraph2
  subgraph201 --> subgraph3
  subgraph202 --> subgraph3
```

That renders the following graph:

![image](https://github.com/mermaid-js/mermaid/assets/142752/8b72af02-e5b4-4b91-9d03-9d5fdd123d2b)

**Comment by ioggstream** [comment]
Possibly related issues:

- https://github.com/mermaid-js/mermaid/issues/4508 
- https://github.com/mermaid-js/mermaid/issues/2829
- https://github.com/mermaid-js/mermaid/issues/2429 <- this issue proposes the same `this-is-a-workaround` solution

**Comment by nirname** [comment]
Closing this in favor of https://github.com/mermaid-js/mermaid/issues/4644, please refer to the new issue. It is a error that comes across different issues.
