### ISSUE TITLE
Unable build Next.js app after 10.2.0 update `SyntaxError: Cannot use import statement outside a module` goes from `dayjs`

### ISSUE THREAD

**Issue by B2o5T** [mermaid-js/mermaid#4438]
### Description

we are unable to build our Next.js docs after the 10.2.0 update
[ardatan/feTS/actions/runs/5113409462/jobs/9192576118?pr=194](https://github.com/ardatan/feTS/actions/runs/5113409462/jobs/9192576118?pr=194)
rollback to 10.1.0 fixes issue

I guess this PR caused issue https://github.com/mermaid-js/mermaid/pull/4285

### Steps to reproduce

https://github.com/ardatan/feTS/tree/7aa27d39e369e4e9c2ac51d43bf5051bfb7d814d

```sh
yarn
yarn workspace website build
```

### Setup

- Mermaid version: 10.2.0
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
Issue in present in live editor too. https://github.com/mermaid-js/mermaid-live-editor/actions/runs/5088034742/jobs/9143981898?pr=1231

**Comment by amsubhash** [comment]
@sidharthv96 I think reverting the changes in #4285 and upgrading to dayjs version 2.* would fix the issue also we will be using esm. I have checked with dayjs `2.0.0-alpha.4` it's working fine.

**Comment by knsv** [comment]
@amsubhash Trying this path, reverting the changes from #4285 together with the dayjs version `2.0.0-alpha.4` but mermaid does not build then. Will revert to the #4285 and return to the previous version of dayjs until we find a better solution.

**Comment by sidharthv96** [comment]
Fixed in 10.2.1
