### ISSUE TITLE
Our graph is not working anymore since 10.2.0

### ISSUE THREAD

**Issue by pierrickouw** [mermaid-js/mermaid#4439]
### Description

Hello!
First, thanks for the great lib!

Our mermaid graph seems to be broken after we upgraded mermaid to 10.2.0.
**Before**
<img width="866" alt="Screenshot 2023-05-30 at 13 55 27" src="https://github.com/mermaid-js/mermaid/assets/1119578/d543e02f-74ba-4325-9766-52ee82b80dbf">
**After**
<img width="729" alt="Screenshot 2023-05-30 at 13 54 34" src="https://github.com/mermaid-js/mermaid/assets/1119578/433a9470-9f7b-4fc7-8e6b-1ffb97003ddc">

It looks like the svg doesn't have the viewbox anymore:
<img width="987" alt="image" src="https://github.com/mermaid-js/mermaid/assets/1119578/611a2309-ec7a-4def-89b6-dc848d0d4280">

We have this config: 

```
{
  "maxTextSize": 800000,
  "startOnLoad": false,
  "securityLevel": "loose",
  "flowchart": {
    "useMaxWidth": true,
    "htmlLabels": true,
    "curve": "cardinal"
  },
  "theme": "dark"
}
```

Do you have any idea?

### Steps to reproduce

See above

### Code Sample

```text
(example here, but the live editor is not up to date with the latest version)

https://mermaid.live/edit#pako:eNrFVH9r2zAU_CpvGiVQYlzo0hiTpDR18lfKBi0MlpSgWM-1NtvyJDk_GvLdJ9nKsjSlgzKYDTK6O92TfPbbklgwJCF5krRM4SGaFQAa13r6YIZHO1tUWotiOqwfNcK4yrlSc8dEzRT-UJQ81pXE6ZfmWWNKbzJ0bpDwLAs_jsdRNLw6kMfGTjS6Hd2OxweR83ZsdDkeBcGBtXt31PBqfGEX2hvM1elOZ6SHOXDWbymNpdfptppl_VYiCu2tkD-lOoSFyFhrcD4UxXdRyXMIV3SJIYyU9mKEnxXCUlQKDPgMnyDnRaVRQWm0UFKZoQSGxliieSvXPR_zQW8hfTeYWSJrMIR_VWJvjIUzbhAKqcSk3_IpMw5-nFK9EHoeGxeFyr98gcztS1F-p-sj47o1GJmx59MBePBOqwJX168QZ51hKXHJzQnr-ZwzddaJDGzGvkllcMMYWMaWn5HHJsBmtEGC5w2gE-yT3YdviJfR1_rgJPjgreBvlhhDmVGuuIQPb-XXa77UkxUOfi0XxxxL3hlU8J-DCv4SlEslOPrdSZvkKHPKmWk7WyudkZyubb-55884IyEEF_ZqN5zSVOrPxURQZrmEZgr3FMaV5HozwSVmlpyRTAhlPJwgycTKHEtqS27d5kil8I6uv3KmU4trWTWGlkt1nk3oAjN1QplaS2yqxFQyXlBT05I7V02nmDsBo_KHJXfmtLTS4n5TxCRs9k6qklGNEaem6ea_URulkHdNO667cpuUtPgmhNHYjex-AVeT53U
```

### Setup

- Mermaid version: 10.2
- Browser and Version: Chrome

### Additional Context

Happy to help debug if needed

**Comment by knsv** [comment]
Thanks for reporting @pierrickouw!

I am having problems reproducing the issue though. It works for me, both in a stand-alone html file as well as in an updated lived editor. Could it be some sort of conflict in your project?

It seems like the rendering stops in the middle, do you have any errors logs that could give some hints?

**Comment by pierrickouw** [comment]
Hello, 

I have managed to isolate the node which make it fail in the live editor, and the subpart in the html part: it's the `img` tag. (I changed the `url` in it)

Doesn't work on the new live editor (you have to scroll to see it)
https://mermaid.live/edit#pako:eNptkV1rwyAUhv-KnF30pmXtBiULWy9S4_VgvYtluGhbmSbBD1gp_e_TaEkHuzlfz-vrQS_Q9lxACUfDhhPaYdoh5MSPa3Yh7GP35Z3ru6Ya0zjh0mpp7WcmOLXoTjHI1nkjmveUx5l1ZyWyGzpIpcoHQjCu1hP8a5xF9bbeEjKJsnem-JnURTHRuHtG1Zos48EIEVoVL8uGwqvUR2RN-zbzRs3Q44bCPglSTEK0WGxisfpv-HSzvN05wvt1YA5aGM0kDy97iWIK7iS0oFCGkjPzTYF216Bj3vUf566F0hkv5uAHzpzAkoUP0VAemLLi-gu0C4bu

Still work on Github (they probably didn't update yet)
```mermaid
graph TD
  text[Text]
  button[Button]
  dismiss_button[Dismiss Button]
  picture[Picture]
  style button fill:#FFDDB6
  style dismiss_button fill:#ECECFF
  style picture fill:#D3FE88
  style text fill:#B6F0FF

    1890["<img src='url' />"]
    
      1890 --> 1891
      1890 --> 1892

      style 1890 fill:#D3FE88
```

**Comment by pierrickouw** [comment]
Just did a bisect, and it was introduced by this commit: 9bb0cef82bba4f31878852c9bf8075964652b93f

**Comment by medliii** [comment]
> Edit: I think it's because we have some image that don't load (and it's fine for us). Just added a PR: #4496

I have the same problem: graph broken if image was not loaded (broken link)
