### ISSUE TITLE
Render function does not work properly in latest release 10.2.0 

### ISSUE THREAD

**Issue by fangpinsern** [mermaid-js/mermaid#4442]
### Description

When loading up the latest release of mermaid in my html script, it throws a `Cannot read properties of undefined` error. This cause the render function to throw an error

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElementNS')
```

When reverted to version 9.3.4, the issue goes away.

### Steps to reproduce

1. Load up the latest mermaid script from the CDN.
2. In the following script tag, use the `.render` function to load your diagram
3. Console will show the error with your diagram not loaded

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/52379442/eb320a74-399f-48bb-80ab-c5855ed920a1)

### Code Sample

```text
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mermaid@10.2.0/dist/mermaid.min.js"> </script>
<script type="text/javascript">(function () {
    mermaid.initialize({ startOnLoad: false });
    const elements = document.getElementsByClassName("mermaid");
	console.log(elements)
    let id = 0;
    Array.from(elements).forEach(elem => {
        const insertSvg = function(svgCode){
            elem.innerHTML = svgCode;
        };

		console.log(atob(elem.innerText));

        mermaid.render(`graphDiv-${id++}`, atob(elem.innerText), insertSvg);
    })
})()
</script>
```

### Setup

- Mermaid version: 10.2.0
- Browser and Version: Chrome, Brave

**Comment by knsv** [comment]
There were breaking changes when we moved to version 10. In your case they are easily remedied though. In your file, change:
```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mermaid@10.2.0/dist/mermaid.min.js"> </script>
<script type="text/javascript">(function () {
```

To:
```
<script type="module">
    import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10.2.0/dist/mermaid.min.js";
   (function () {
```

Good luck!

**Comment by fangpinsern** [comment]
Thanks for assisting. I tried it out and they said the request module is not exported. Is this expected? 

![image](https://github.com/mermaid-js/mermaid/assets/52379442/ddb7322c-a594-49b7-b6df-4ffd1f8eb980)

**Comment by sidharthv96** [comment]
@fangpinsern can you try v10.2.2 ?

**Comment by fangpinsern** [comment]
same issue as using v10.2.0
Just want to check the cdn link is the same right?
https://cdn.jsdelivr.net/npm/mermaid@10.2.2/dist/mermaid.min.js

**Comment by sidharthv96** [comment]
We cannot diagnose the issue without getting the diagram code being rendered then. 
If it's not possible to share here, can you create a repro and share it with me or @knsv in Slack?

**Comment by sidharthv96** [comment]
I just noticed the URL is different. Can you try this one?

```html
<body>
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true });
  </script>
</body>
```

**Comment by szmurlor** [comment]
I had the same issue when I used the callback for inserting svg passed to `mermaid.render(...)` method.

I think your code should follow the new syntax (according changelog: https://github.com/mermaid-js/mermaid/blob/develop/CHANGELOG.md):

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mermaid@10.2.0/dist/mermaid.min.js"> </script>
<script type="text/javascript">(function () {
    mermaid.initialize({ startOnLoad: false });
    const elements = document.getElementsByClassName("mermaid");
	console.log(elements)
    let id = 0;
    Array.from(elements).forEach(elem => {
        /* not needed bacause mermaid.render is async/await
            const insertSvg = function(svgCode){
            elem.innerHTML = svgCode;
        }; */

          console.log(atob(elem.innerText));

         const {svg, bindFunctions} = await mermaid.render(`graphDiv-${id++}`, atob(elem.innerText));
         elem.innerHTML = svgCode;
    })
})()
</script>
```

**Comment by fangpinsern** [comment]
Hmmm yep! I missed that part of the change log. Changing it to an async await implementation with the new import link update worked!

Thanks!
