### ISSUE TITLE
chore: add more labels to issues

### ISSUE THREAD

**Issue by Yokozuna59** [mermaid-js/mermaid#4444]
Currently, it's hard to search for issues based on their labels. And from #4227:
 
> The second is: please make sure you do a good search through the issues here before creating a new one!
>
> So we might have duplicate issues since users could find what they were looking for.

So by adding more labels, users and developers would be able to filter issues and contribute to stuff they're interested in or related to each other.
 
You could add more labels for better visibility. For example:
 
- `Parser`: issues related to the parsing and syntax of diagrams. It would be helpful since I'm working on it here, #4401.

> **Note**: most issues have general labels, e.g., `Status: Triage`, that came from the GitHub issue templates. it doesn't help much for searching for issues which means duplicate issues.

**Comment by sidharthv96** [comment]
I think triage was a label for maintainers to filter issues that needed to be categorized. 

`Status: Triage` -> Needs to be verified, categorized, etc

**Comment by aloisklink** [comment]
> I think triage was a label for maintainers to filter issues that needed to be categorized.

It would be nice to have a triaging guide too :)

I don't really have the time to look at every issue/PR, but when I do, I can't really triage since I don't know what many of the labels mean.

Just as an example, when do we use a **feature** or **Type: Enhancement** label? I swear that only **Type: Enhancement** PRs automatically go into the draft release notes (see https://github.com/mermaid-js/mermaid/blob/develop/.github/release-drafter.yml), but PRs are auto-labelled with **feature** if they come from a branch called `feature/xxxxxx` so :shrug:

I'm sure there other people with triage permissions in the mermaid repo that don't triage since they don't know how to. And having a guide would make it easier to onboard new community members if they want to help with triaging.

**Comment by Yokozuna59** [comment]
Looking at `Type: Enhancement` Description, it really state that it's a feature:

![84665682-F137-448F-A6F6-0A2A08ECA55B](https://github.com/mermaid-js/mermaid/assets/87622592/bcfb3733-4feb-456b-b5ae-7f17c607cc1a)

I upvote triaging guide! Or at least adding description to each label, adopting new ones, removing duplicates.

I'm more than happy to contribute if you're willing.

---

I would also suggest adopting the new `github flow` instead of the `git flow`.

As stated [here](https://nvie.com/posts/a-successful-git-branching-model) from the author of `git flow`:

> This is not the class of software that I had in mind when I wrote the blog post 10 years ago. If your team is doing continuous delivery of software, I would suggest to adopt a much simpler workflow (like [GitHub flow](https://docs.github.com/en/get-started/quickstart/github-flow)) instead of trying to shoehorn git-flow into your team.

And by doing so it would be simpler and close to the current develop lifecycle to the contributors. Which results in cleaner labels, organized flow, less complexity, and much more!

**Comment by sidharthv96** [comment]
Totally agree. I've also felt that we have too many labels and no guidelines on how to use them. 

@knsv @ashishjain0512 @jgreywolf @mermaid-js/atlantians can anyone give us an idea of what the plans were for the labels?

**Comment by jgreywolf** [comment]
I have been trying to clean up the labels here and there. Removing some, adding others, etc. I dont think there is an official plan in place, and we just need to come up with one.

As opposed to randomly making changes as I had been doing.

In general, I am a fan of like things being with like things.  This means categorizing labels together (as we have no with some of them)

- overall status
- current workflow state
- type: bug, request, chore...
- component: parser, renderer...
- diagram type

I think the that "topic" ones we have now should go away. 
-
