### ISSUE TITLE
Vertical branches in Gitgraph

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#4451]
### Discussed in https://github.com/orgs/mermaid-js/discussions/3772

<div type='discussions-op-text'>

<sup>Originally posted by **DamienCassou** November  8, 2022</sup>
Currently, Gitgraph always represents branches horizontally:
![Screenshot 2022-11-07 at 21-05-52 Gitgraph (Git) Diagram 🔥](https://user-images.githubusercontent.com/217543/200404409-7ef13c18-5645-4258-bddb-21eee81168bd.png)

It would be nice to be able to render them vertically as well such as in this mockup:
![Screenshot 2022-11-07 at 21-00-30 Gitgraph (Git) Diagram 🔥](https://user-images.githubusercontent.com/217543/200404397-32f5373a-03f2-4fda-a74f-fd8334279f0b.png)

</div>

**Comment by harshlancer** [comment]
Can I work on this?

**Comment by Yokozuna59** [comment]
@harshlancer Please feel free to work on any open issues without linked PRs. There is no need to ask first.

**Comment by nirname** [comment]
This is a duplication of that one #2585, so I am closing it to keep history of the previous
