### ISSUE TITLE
need help flowchart

### ISSUE THREAD

**Issue by doctordragon666** [mermaid-js/mermaid#4454]
### Proposal

How to add a triangle node in a flowchart

**Comment by sidharthv96** [comment]
These are the possible shapes in flowchart: https://mermaid.js.org/syntax/flowchart.html#node-shapes

Are there any examples of triangle nodes? What do they represent?
If it's a standard shape, someone could add it in as a PR.

**Comment by doctordragon666** [comment]
There is really no triangle in the flowchart, I just want to use triangles when drawing.
Thank you.
