### ISSUE TITLE
`@mermaid-js/mermaid-zenuml` not on NPM?

### ISSUE THREAD

**Issue by armanbilge** [mermaid-js/mermaid#4477]
According to the release notes `@mermaid-js/mermaid-zenuml` was added in v10.2.3 🎉 

https://github.com/mermaid-js/mermaid/releases/tag/v10.2.3

However, I can't find it at NPM.

https://www.npmjs.com/package/@mermaid-js/mermaid-zenuml

Also, the `jsdelivr` URL in the docs does not work.

https://mermaid.js.org/syntax/zenuml.html#integrating-with-your-library-website

Thanks!

**Comment by ReeceHumphreys** [comment]
Currently having the same issue, is there any update on this?

**Comment by MrCoder** [comment]
It is at  https://www.npmjs.com/package/@zenuml/core.

**Comment by MrCoder** [comment]
@ReeceHumphreys is this what you are looking for? https://www.npmjs.com/package/@mermaid-js/mermaid-zenuml

**Comment by armanbilge** [comment]
Thanks for publishing it!

**Comment by ReeceHumphreys** [comment]
> @ReeceHumphreys is this what you are looking for? https://www.npmjs.com/package/@mermaid-js/mermaid-zenuml

Yes thanks!
