### ISSUE TITLE
`namespace` specifier not working on markdown interpreters

### ISSUE THREAD

**Issue by Ed-1T** [mermaid-js/mermaid#4481]
### Description

Previews containing the `namespace` keyword, including the one present in the README.md, result in an error when rendered through markdown (github, gists, vscode).
The issue does not occur on the mermaid documentation website, nor in the live editor

### Steps to reproduce

1. Create a markdown file on any text editor that supports mermaid (github, gists, vscode)
2. Paste any class diagram containing a namespace, such as the one found in the documentation

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/63556948/09ff57fd-3ac9-49a6-bd40-41dba978c19d)

### Code Sample

```text
classDiagram
namespace BaseShapes {
    class Triangle
    class Rectangle {
      double width
      double height
    }
}
```

### Setup

- Mermaid version: Latest? Whatever version Github uses.
- Browser and Version: Not available.

**Comment by sidharthv96** [comment]
namespace support was only added in [v10.2.0](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.0)

You can see the version github is using by using the `info` diagram. Currently it's 10.0.2. Once they upgrade to 10.2.0 or above, namespace will be supported. 

```mermaid
info
```
