### ISSUE TITLE
Documentation for classDiagram examples: "attribute type" order is backwards compared to UML

### ISSUE THREAD

**Issue by chrisfcarroll** [mermaid-js/mermaid#4489]
The documentation text suggests that the class diagram can show correct UML output — which it can! — **but** in the examples "attributeName type" is the wrong way round (UML has name then type, not type then name) and omits the colons, so that's confusing.

**Comment by jgreywolf** [comment]
See comment in PR

The way it works right now is that either method will be accepted.  Basically, for backwards compatibility, we display these specific values as typed. As previously we supported type only, attribute name only, etc.
