### ISSUE TITLE
Sankey diagrams

### ISSUE THREAD

**Issue by nirname** [mermaid-js/mermaid#4492]
### Proposal

I found Sankey flow diagrams descriptive and informative. Was looking for an easy tool do do that. Currently, all of them requires sort of programming to do that. I had my own ideas about that, but it's probably better to join existing project.

There was [a short discussion](https://github.com/orgs/mermaid-js/discussions/4474) about it.

There is [a PR](https://github.com/mermaid-js/mermaid/pull/4502), which is under development.

### Use Cases

A sankey diagram is a visualization used to depict a flow from one set of values to another. That was the Internet says :-)
Here are [some examples](https://observablehq.com/@d3/brexit-voting?collection=@d3/d3-sankey) of what d3 comes with. They are quite self-explanatory, so I picked those images as a screenshots samples.

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/2842432/9677efc1-53a5-41ac-871d-1b74c5145bf1)
![image](https://github.com/mermaid-js/mermaid/assets/2842432/b69b8a5c-a519-4ec9-9fef-fd14dbade44a)
![image](https://github.com/mermaid-js/mermaid/assets/2842432/8ed0e0a6-b988-4ec6-8f8c-8072c106d61f)

### Syntax

There are [some ideas](https://github.com/mermaid-js/mermaid/pull/4502/files#diff-801c0534c507def9f55d3e817082d2712459ed9631e51b8784eaa5952a73a0fa) about possible syntax.

There are some restrictions though:
* **Circular graphs are not supported by d3. There are some alternatives for that.**
* **Dropped flows are not supported by d3**
![image](https://github.com/mermaid-js/mermaid/assets/2842432/4054ae81-337b-41bb-8ace-ee68955041ad)

Keeping this is mind that is what I've come up with, inspired mainly by `dot`

Graph is a list of flows (or links).
Flow is a sequence `node -> value -> node -> value...`
```
a -> 30 -> b
a -> 40 -> b
```

2 separate streams between 2 nodes they can be grouped as well:
```
a -> {
    30
    40
} -> b
```

All outflows from the node can be grouped:
```
a -> {
    30 -> b
    40 -> c
}
```

All inflows to the node can be grouped too:
```
{
    a -> 30
    b -> 40
} -> c
```

Chaining example:
```
a -> {
    30
    40
} -> b -> {
    20 -> d
    50 -> e
}
```

### Implementation

I will try and implement it myself.

**Comment by nirname** [comment]
There are some current syntax examples

```
sankey
a -> 30 -> b -> 12 -> e
c -> 30 -> d -> 12 -> e
c -> 40 -> e -> 12 -> q
```

```
sankey
node[]
node[attr=1]
a -> 30 -> b
node[attrWithoutValue]
node[attr = 3]
node[attr1 = 23413 attr2=1234]
node[x1dfqowie attr1 = 23413 attr2]
```

**Comment by nirname** [comment]
As I mentioned earlier, there are 2 great features, that are not supported natively by D3

**Dropped flows**

Like this one, that depicts some loss

![image](https://github.com/mermaid-js/mermaid/assets/2842432/5bd693bc-1b0d-40d8-84c7-135e55205c90)

Nevertheless, it can be done, simply by creating an empty node for that. The only thing, that this won't beautifully flow sideways.

**Loops**

Loops are not supported either, but some forks of D3 have it

**Comment by nirname** [comment]
[There are a beautiful example](https://observablehq.com/@tomshanley/vertical-sankey-with-elegant-links-to-entry-and-exit-nodes) of vertical diagram with entry and exit nodes.
We also need smth like fadeouts
![image](https://github.com/mermaid-js/mermaid/assets/2842432/86e29467-a8eb-48d3-aa57-ea0e498f7b88)
This and the previous sample have to be a separate issue

**Comment by sidharthv96** [comment]
Yes, we can support the core features in the first release and work on the ones without d3 support later.

**Comment by nirname** [comment]
# These are some early ideas

## What is used now

**Circular graphs are not supported by d3. There are some alternatives for that.**
**Dropped flows are not supported by d3**

This is example of data for Sakey diagrams from d3 author (simple csv):

```csv
Berlin,Job Applications,102
Barcelona,Job Applications,39
Madrid,Job Applications,35
Amsterdam,Job Applications,15
Paris,Job Applications,14
London,Job Applications,6
Munich,Job Applications,5
Brussels,Job Applications,4
Dubai,Job Applications,3
Dublin,Job Applications,3
Other Cities,Job Applications,12
Job Applications,No Response,189
Job Applications,Responded,49,orange
Responded,Rejected,38
Responded,Interviewed,11,orange
Interviewed,No Offer,8
Interviewed,Declined Offer,2
Interviewed,Accepted Offer,1,orange
```

GoJS uses similar approach:

```json
{
"nodeDataArray": [
{"key":"Coal reserves", "text":"Coal reserves", "color":"#9d75c2"},
{"key":"Coal imports", "text":"Coal imports", "color":"#9d75c2"},
{"key":"Oil reserves", "text":"Oil\nreserves", "color":"#9d75c2"},
{"key":"Oil imports", "text":"Oil imports", "color":"#9d75c2"}
],
"linkDataArray": [
{"from":"Coal reserves", "to":"Coal", "width":31},
{"from":"Coal imports", "to":"Coal", "width":86},
{"from":"Oil reserves", "to":"Oil", "width":244}
}
```

## What do we need

Mainly we need:

- collection of nodes
- collection of links

We also need graph and node attributes like this:

- link sort
- node sort
- coloring strategy for links (source, target, transition)
- graph alignment (left, right, width)
- node color
- node title
- node width
- node padding
- graph margin

## Desired syntax

Graph is a list of flows (or links).
Flow is a sequence `node -> value -> node -> value...`

```
a -> 30 -> b
a -> 40 -> b
```

2 separate streams between 2 nodes they can be grouped as well:

```
a -> {
    30
    40
} -> b
```

All outflows from the node can be grouped:

```
a -> {
    30 -> b
    40 -> c
}
```

All inflows to the node can be grouped too:

```
{
    a -> 30
    b -> 40
} -> c
```

Chaining example:

```
a -> {
    30
    40
} -> b -> {
    20 -> d -> 11
    50 -> e -> 11
} -> f -> 30
```

**Probably ambiguous!**

Does the sample below mean that total outflow from "a" is 60?

```
a -> 30 -> {
    b
    c
}
```

Or does this one mean that total outflow must be 140 (70 to "b" and "c" respectively)?

```
a -> {
    30
    40
} -> {
    b
    c
}
```

**Overcomplicated**

Nested:

```
{
    {
        a -> 30
        b -> 40
    } -> c -> 12
    {
        d -> 10
        e -> 20
    } -> f -> 43
} -> g
```
