### ISSUE TITLE
 combine `cypress` and `vitest` coverage reports

### ISSUE THREAD

**Issue by Yokozuna59** [mermaid-js/mermaid#4494]
Currently, Mermaid uses only `vitest` to report coverage, and `vitest` doesn't run `renderer`, `svgDraw`, etc. files, which shows the wrong results (57%):

[![Coverage Status](https://coveralls.io/repos/github/mermaid-js/mermaid/badge.svg?branch=master)](https://coveralls.io/github/mermaid-js/mermaid?branch=master)
 
The main purpose of coverage is to know what have been test and highlight possible edge cases, but with these misleading reports, it would be hard.
 
Suggest solutions:
 
1. Create a script that takes reports from `vitest` and `cypress` coverages and then combines them.
 
Here is an [example](https://rafaelalmeidatk.com/blog/merging-coverage-reports-from-jest-and-cypress) for someone who combines `jest` and `cypress` coverage reports.
 
2. Make `vitest` handle both headless and unit testing; that will show better coverage, and from [vitest.dev](https://vitest.dev/guide/comparisons.html#cypress):
 
    > We suggest using Vitest for all headless logic in your application and Cypress for all browser-based logic.

    And:

    > We believe that Cypress isn't a good option for unit testing headless code, but that using Cypress (for E2E and component testing) and Vitest (for unit tests) would cover your app's testing needs.

3. Migrate to a new tool for both types of testing.
 
4. Migrate to the new visual testing tool for faster reports.

What do you think? Do you have something else in mind?
 
IMO, the first solution is good, but it will take more time to report, so the second looks like a better solution.

**Comment by sidharthv96** [comment]
> Create a script that takes reports from vitest and cypress coverages and then combines them.
> 
> Here is an [example](https://rafaelalmeidatk.com/blog/merging-coverage-reports-from-jest-and-cypress) for someone who combines jest and cypress coverage reports.

That blogpost has everything we need to combine our coverage reports. So we should be doing that ASAP. 

---

> We suggest using Vitest for all headless logic in your application and Cypress for all browser-based logic.

This is what we're doing now. We cannot use vitest to test rendering as jsdom doesn't have the things we need. 
We need a browser to test rendering. 

---

> 3. Migrate to a new tool for both types of testing.

I'm not aware of any tools that does this, any recommendations?

---

> 4. Migrate to the new visual testing tool for faster reports.

We have a LOT of image tests. Any migration would require 

1. Change of code. Doable, but a lot of grunt work. There's like 200+ places where `cy.` is used. 
2. Migration of approved data in Applitools. If we can ensure the rendering tests works, we could have an easier time here, but still a manual review would be required. 
3. Cypress has a hosted service (free), which allows us to verify tests easisly. The next best contestant in the space (playwright), lacks this. We'll have to download a trace file and run a command to view what happened. 


---


I think we should really be doing #1 ASAP.

**Comment by sidharthv96** [comment]
Coverage support added to E2E tests https://github.com/mermaid-js/mermaid/pull/4498 as our build process is not that straight-forward.

Accepting PRs for merging the coverage results.

**Comment by sidharthv96** [comment]
The coverage actually revealed many old functions that could possibly be removed.

**Comment by sidharthv96** [comment]
I think you can generate the other kinds of reports from the combined json.
