### ISSUE TITLE
Multi-line Comments

### ISSUE THREAD

**Issue by nirname** [mermaid-js/mermaid#4518]
### Proposal

We need to support multi-line comments, currently they are not supported.

I suggest a syntax like this `%{ }%`, which has to be discussed.

Escape character for titles and captions with special characters has yet to be discussed too. Perhaps double percent `%%` can be replaced with `%` in resulting diagram.

### Example

A complete example is:

```
myGraph
%% one line comment
Bob -> Hello -> Alice %% trailing comment
%{
multi-line
comment
}%
Pete -> Hello %{ comment in the middle }% -> Alice
Steve -> Hello %{
multi-line
comment
in the middle
}% -> Alice
```

It should be possible to have it inserted in the middle of the string:
```
a -> b %{ comment }% -> c
```

It can start on any line and end on any line too:
```
a-> b %{
long
comment
}% -> c
```
the result should be:
```
a -> b  -> c
```
Note, there are 2 spaces between b and following arrow, they are representing the idea that after comment is deleted everything else stays intact.

One line comment should be treated as trailing comment, so everything that start with `%%` till the end of the line is a comment.

The `%%`, `%{` and `%}` symbols are treated as parts of the comments too.

Comments should be removed before graph parsing.

Taking that in consideration, no graphs should have these symbols in their's grammars. If someone needs to include a line containing any of those inside a caption, label or a title he must precede it with escape character. The most common techniques about that is
* duplicating the character, so escape symbol could also be `%`; `%%` will be converted to `%`
* using another escape character, so `\` is one of the most ubiquitous, it can escape itself: `\%` will be converted to `%` and `\\` will be convert to `\`

**Comment by nirname** [comment]
I have not found a separate bug for it, but trailing comments are not working right now

**Comment by Yokozuna59** [comment]
I'm voting to that syntax, I've already implemented here but the parser is not done

https://github.com/mermaid-js/mermaid/blob/058b08d9b62b06d34f6fcdedb29c8a72fa21521f/packages/parser/src/language/grammars/common.langium#L12

**Comment by nirname** [comment]
I think i have to close this issue, because it is a duplicate of [this one](https://github.com/mermaid-js/mermaid/issues/1249)

**Comment by nirname** [comment]
I think i have to close this issue, because it is a duplicate of [this one](https://github.com/mermaid-js/mermaid/issues/1249)
