### ISSUE TITLE
namespaced classes lose members if relation statement comes after namespace

### ISSUE THREAD

**Issue by sduveen-pivot** [mermaid-js/mermaid#4519]
### Description

When a relation is declared after a namespace, the members disappear.

The following diagram will not include the `+Id: Guid` in either class
```
    classDiagram
      namespace A {
        class A1 {
          +Id : Guid
        }
      }
      namespace B {
        class B1 {
          +Id: Guid
        }
      }
      A1 --> B1
```
while 
```
    classDiagram
      A1 --> B1
      namespace A {
        class A1 {
          +Id : Guid
        }
      }
      namespace B {
        class B1 {
          +Id: Guid
        }
      }
```
will display the `+Id: Guid` because the relationships are before the namespace declaration.

### Steps to reproduce

See Description and code sample

### Screenshots

![mermaid_bug1](https://github.com/mermaid-js/mermaid/assets/117479580/a8fd253a-dbf1-4708-a2f2-27c10ed25385)

### Code Sample

```text
classDiagram
      namespace A {
        class A1 {
          +Id : Guid
        }
      }
      namespace B {
        class B1 {
          +Id: Guid
        }
      }
      A1 --> B1
```

### Setup

- Mermaid version: 3662869ce14be1a64a73fa4e6602f368b6204865 (on `develop` branch)
- Browser and Version: [Chrome, Firefox]

### Additional Context

This is a bug in the parser/classDb file.
Namespaces depend on successfully deleting the class from the base `classes` variable:
https://github.com/mermaid-js/mermaid/blob/3d117815425cbd05105ec0f0192adc0be91931f2/packages/mermaid/src/diagrams/class/classDb.ts#L452

However, when relations are added, they call addClass() (again)
https://github.com/mermaid-js/mermaid/blob/3d117815425cbd05105ec0f0192adc0be91931f2/packages/mermaid/src/diagrams/class/classDb.ts#L132-L136
and so the class is re-instantiated w/o the members that were 'known" from adding to namespaces

**Comment by duaneking** [comment]
This is not fixed and even the live mermaid renderer does not seem to work as expected in my tests.
