### ISSUE TITLE
Recent commit to develop causes demo charts to render without styles

### ISSUE THREAD

**Issue by NicolasNewman** [mermaid-js/mermaid#4527]
### Description

I recently noticed on the latest version of develop that the styles for charts on the demo page aren't loading properly. I've traced the issue back to the commit `0c449bb: handle optional .styles` which is where the behavior first appears.

#### Reproduce
1. Clone the latest version of develop
2. `pnpm i && pnpm dev`
3. Navigate to the demo page
4. Load the sequence or flowchart demo
5. Charts aren't rendering properly

#### Rollback
1. Revert to the commit before `0c449bb`
2. Restart the dev server
3. Refresh the page
4. The issue is resolved

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/16135852/c7435cd3-385a-47eb-859d-c48c906c8a31)
![image](https://github.com/mermaid-js/mermaid/assets/16135852/2d831461-4e04-4c14-ad88-64d35f2233b2)

### Setup

- Mermaid version: develop
- Browser and Version: [Chrome, Firefox]

**Comment by NicolasNewman** [comment]
[Commit](https://github.com/mermaid-js/mermaid/commit/0c449bbd27db43ee217a20ee028b569b53cca975) in question

**Comment by Yokozuna59** [comment]
> 1. Revert to the commit before `0c449bb`

We can't just `revert` the commit; some diagrams would fail because they don't have that field since it's optional. I'm going to look into it shortly, when I've time.

**Comment by NicolasNewman** [comment]
I apologize if my wording was confusing. I was just describing how to identify the commit where the issue started to appear and didn't mean to imply that as the solution. 

I have the lines in question commented out on my local environment so there's no immediate need on my end for having it resolved.

**Comment by Yokozuna59** [comment]
It should be resolved with this PR #4528.
