### ISSUE TITLE
can't work with more than one generic in UML diagram

### ISSUE THREAD

**Issue by abhashksingh** [mermaid-js/mermaid#4565]
### Description

I asked this question on stack-overflow [here](https://stackoverflow.com/questions/76573467/how-to-represent-map-in-mermaid/). 
I want to represent
```
map<int,std::string> pMap;
```
on a UML diagram.
I tried 
```
std::map~int,string~ pMap;
```
this results in crash of Mermaid.

### Steps to reproduce

Copy paste the below code to the mermaid editor

```
classDiagram

class Args{
    std::map ~int,string~ pMap;
}
```

### Code Sample

```text
classDiagram

class Args{
    std::map ~int,string~ pMap;
}
```

### Setup

- Mermaid version: 10.2.3
- Browser and Version: [Chrome, Edge, Firefox,Brave]

### Additional Context

I am ok with a workaround as well.

**Comment by Yokozuna59** [comment]
duplicate of #4431, #4555, and #3287. It should be resolved in #4534.

**Comment by GitSparTV** [comment]
It doesn't affect commas only. I caught infinite loop on such example:

```
classDiagram
    class A {
        -a~b::c~ d
    }
```

**Comment by jgreywolf** [comment]
I just added test case specifically for this, and yes it will be resolved with #4534

**Comment by jgreywolf** [comment]
Please confirm if this has been resolved with 10.5.0

**Comment by abhashksingh** [comment]
Mermaid Live Editor doesn't support 10.5.0 yet. Hence unable to do it.
Please tell me how to use 10.5.0.

**Comment by Yokozuna59** [comment]
@abhashksingh You may use this link: https://deploy-preview-4900--mermaid-js.netlify.app/

It's a preview for the live editor from one of the latest PRs.

**Comment by abhashksingh** [comment]
yeah it works on 10.5.0. Thanks @Yokozuna59 for the link.
