### ISSUE TITLE
BLAZOR - Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElementNS') In Blazor C#

### ISSUE THREAD

**Issue by Thoybur-Rohman** [mermaid-js/mermaid#4569]
### Description

I have moved from version 9 to 10 but I am still gettering errors in blazor , I have no clue what changes I require everything that I have tried has failed HERE IS MY ORIGINAL CODE  , PLEASE COULD I GET ASSITANCE . 

i want to change to version 20 with the correct imports.

i know theres already #4442 i tried to follow it but i failed and nothing worked   

### Steps to reproduce

1 - copy blazor code 
2 - add js code 

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/73062879/59df56e6-6b82-44fc-a57c-3ac358be3bab)

### Code Sample

```text
Blazor.cs File :

@page "/
@inject IJSRuntime JSRuntime

<div>
    <label for="input">Input:</label>
    <textarea id="input" @bind="@InputText" @oninput="RenderDiagram"></textarea>
</div>
<div>
    <label for="output">Output:</label>
    <div id="output">@OutputText</div>
</div>

@code {
    private string InputText = "";

    private string OutputText = "";

    private async Task RenderDiagram()
    {
        await JSRuntime.InvokeVoidAsync("renderMermaidDiagram");
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JSRuntime.InvokeVoidAsync("mermaid.initialize", new { startOnLoad = true });
            await JSRuntime.InvokeVoidAsync("renderMermaidDiagram");
        }
    }
}

Script : 
  <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>

  <script>
        window.renderMermaidDiagram = () => {
        var output = document.getElementById("output");
        var input = document.getElementById("input").value;

        if (input != "") {
            try {
                mermaid.mermaidAPI.parse(input); // Syntax validation
                mermaid.mermaidAPI.render('theGraph', input, function (svgCode) {
                    output.innerHTML = svgCode;
                });
            } catch (error) {
                output.innerHTML = "Invalid syntax"; // Display error message
            }
        }
    }
```

### Setup

- Mermaid version: 9 to 10
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

please help me refactor to version 10 ( I have read the docs still does not work )

### Additional Context

I already tried to follow #4442 but nobody else has a  blazor example.... please can i get some help refactoring this

**Comment by Thoybur-Rohman** [comment]
Please can i get some assistance on changing this

**Comment by sidharthv96** [comment]
@Thoybur-Rohman mermaid's render and parse is now async after v10, and the function signature is also different.

Please refer to these links on how to migrate. 

https://mermaid.js.org/config/usage.html#api-usage
https://github.com/mermaid-js/mermaid/releases/tag/v10.0.0
https://github.com/mermaid-js/mermaid/blob/master/CHANGELOG.md#1000

**Comment by Thoybur-Rohman** [comment]
> @Thoybur-Rohman mermaid's render and parse is now async after v10, and the function signature is also different.
> 
> Please refer to these links on how to migrate.
> 
> https://mermaid.js.org/config/usage.html#api-usage https://github.com/mermaid-js/mermaid/releases/tag/v10.0.0 https://github.com/mermaid-js/mermaid/blob/master/CHANGELOG.md#1000

but ill have to use  acdn how do I do this without it giving me an error

**Comment by sidharthv96** [comment]
```html
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
  mermaid.initialize({ startOnLoad: true });
</script>
```

**Comment by Thoybur-Rohman** [comment]
> ```
> <script type="module">
>   import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
>   mermaid.initialize({ startOnLoad: true });
> </script>
> ```

if you look above i am using blazor i tried to refactor the code to adapt to my blazor I just get uncaught promise do you have any ideas ?

**Comment by Thoybur-Rohman** [comment]
![image](https://github.com/mermaid-js/mermaid/assets/73062879/38f612c9-a89c-48a1-aff9-5665cfaa2d69)

**Comment by sidharthv96** [comment]
I'm not familiar with Blazor, and I think you'll get more support from the Blazor community as the issue here is not related to mermaid. 

Closing this as it's out of scope.

**Comment by sidharthv96** [comment]
Well, actually, you can modify just the renderer call to get it working. 

Instead of 
```ts
                mermaid.mermaidAPI.render('theGraph', input, function (svgCode) {
                    output.innerHTML = svgCode;
                });
```

use 

```ts
    const graphDefinition = 'graph TB\na-->b';
    const { svg } = await mermaid.render('theGraph', graphDefinition);
    output.innerHTML = svg;
```

**Comment by Thoybur-Rohman** [comment]
hi @sidharthv96 so iv been doing a bit of tinkering and I have tried the following : 
```
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
  mermaid.initialize({ startOnLoad: true });
</script>```

```
    <script>
    window.renderMermaidDiagram = () => {
        var element = document.getElementById("output");
        var input = document.getElementById("input").value;
            console.log(input)
        let id = 0;
        if (input != "") {
            try {
                    const { svg, bindFunctions } = await mermaid.render( id, input);
                    element.innerHTML = svg;
                    bindFunctions?.(element);
            } catch (error) {
                    element.innerHTML = "Invalid syntax"; // Display error message
            }
        }
    }
</script>
```
blazor code 
```
@inject IJSRuntime JSRuntime
 
<div>
<label for="input">Input:</label>
<textarea id="input" @bind="@InputText" @oninput="RenderDiagram"></textarea>
</div>
<div>
<label for="output">Output:</label>
<div id="output">@OutputText</div>
</div>
 
@code {
    private string InputText = "graph TD;"
                               + "\nA-->B";
 
    private string OutputText = "";
 
    private async Task RenderDiagram()
    {
        await JSRuntime.InvokeVoidAsync("renderMermaidDiagram");
    }
 
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JSRuntime.InvokeVoidAsync("renderMermaidDiagram");
        }
    }
}
```

and I get the following error 
![image](https://github.com/mermaid-js/mermaid/assets/73062879/80e6f1a1-5a51-4b6c-874b-3e01f568fa25)

**Comment by Thoybur-Rohman** [comment]
@sidharthv96 its when i chnage to the new v10 I get the errors

**Comment by Thoybur-Rohman** [comment]
@sidharthv96 i have found a solution :
```
<script type = "module" >
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
    mermaid.initialize({
    startOnLoad: true
});
window.renderMermaidDiagram = async () => {
        var element = document.getElementById("output");
        var input = document.getElementById("input").value;
        console.log(input);
        if (input != "") {
            try {
                const { svg  } = await mermaid.render("theGraph", input);
                element.innerHTML = svg;
            } catch (error) {
                element.innerHTML = "Invalid syntax"; // Display error message
            }
        }
    } < /script>

**Comment by adamhathcock** [comment]
worked for me too, thanks @Thoybur-Rohman !
