### ISSUE TITLE
ER diagram: ATTRIBUTE_WORD doesn't allow beginning with number

### ISSUE THREAD

**Issue by zagkleishman** [mermaid-js/mermaid#4571]
### Description

Trying to create a er Diagram using the [mermaid.live](https://mermaid.live) get an error " Expecting 'ATTRIBUTE_WORD', got 'error' " found it is because the line column starts with a number.  I think the issue is at the following [erDiagram.jison](https://github.com/mermaid-js/mermaid/blob/598addf50613a7194c24549dfcb0549ed61d077d/packages/mermaid/src/diagrams/er/parser/erDiagram.jison#L33C11-L33C11) I'm not sure why numbers were not allowed at the beginning and didn't find a way to quote the Attribute name.  Adding double quotes caused it to error about expecting "ATTRIBUTE_WORD , got COMMENT".

### Steps to reproduce

Create er diagram with the code from the code sample and it will error on the line ```set 2fa_provider```

### Code Sample

```text
erDiagram
    settings {
        varchar passwordPolicy
        set 2fa_provider
        varchar 2fa_name
        int 2fa_length
        tinyint 2fa_userchange
        tinyint enableCustomers
        tinyint enableRouting
    }
```

### Setup

- Mermaid version: 10.2.3
- Browser and Version: Vivaldi
- Mermaid.live

### Suggested Solutions

- Add option to also quote the Attribute name.
- Allow Numbers at the beginning of the Attribute name.

**Comment by ibrahimWassouf** [comment]
My guess is that this was set like so because it is assuming that the creator of the diagram is using regular identifiers instead of delimited ones for column names. If going by SQL conventions, regular identifiers cannot start with digits. @knsv and @sidharthv96, do you think the ER diagram should follow this assumption or allow the user to place these constraints themselves whenever needed?

**Comment by ibrahimWassouf** [comment]
If we wanted to allow for attribute names to start with digits, then this can easily be added with #4588

**Comment by sidharthv96** [comment]
I don't think we should deviate from standards. So unless there's a specific need for it, I'd say keep it simple.

**Comment by wanand** [comment]
Im interested in this feature as well. Would it be possible to have columns starting with numbers?

**Comment by jgreywolf** [comment]
Closing based on comments above - in keeping with standards for naming conventions
