### ISSUE TITLE
Unable to set notes for namespaces

### ISSUE THREAD

**Issue by GitSparTV** [mermaid-js/mermaid#4589]
### Description

When you define a note for namespace it doesn't draw a dashed line between them

### Steps to reproduce

1. Use code example.
2. Expect the issue

### Screenshots

<img width="422" alt="image" src="https://github.com/mermaid-js/mermaid/assets/5685050/d19cb24b-206e-4753-877a-759690242ec2">

### Code Sample

```text
classDiagram
    note for Class1 "My note"
    note for ns "My note"
    
    class Class1 {
        -field : Type
    }

    namespace ns {
        class Class2 {
            -field : Type
        }
    }
```

### Setup

- Mermaid version: 10.2.4
- Browser and Version: Safari 16.6

**Comment by jgreywolf** [comment]
Duplicate issue. Closing this in favor of #4706 due to the additional detail
