### ISSUE TITLE
Note "note" throws an error

### ISSUE THREAD

**Issue by GitSparTV** [mermaid-js/mermaid#4590]
### Description

If you create a note with text "note", it will show a syntax error

### Steps to reproduce

1. Use code example
2. Get parser error

### Screenshots

<img width="497" alt="image" src="https://github.com/mermaid-js/mermaid/assets/5685050/9b1add3e-95ac-441d-988a-b3e15676595c">

### Code Sample

```text
classDiagram
    note for Class "note"
    
    class Class {
        -field : Type
    }
```

### Setup

- Mermaid version: 10.2.4
- Browser and Version: Safari 16.6

**Comment by ibrahimWassouf** [comment]
Have been playing around and figured out why this happens. The lexer can return a `NOTE` token at any state, even after entering the `STR` from reading `"`. Therefore, this bug also occurs for the `NOTE FOR` token. I believe the easiest solution is to set the state to `INITIAL` in for the `NOTE` and `NOTE FOR` token rules. I can submit a pull request tomorrow if everything checks out.
