### ISSUE TITLE
newline(s) in classDiagram class name causes all members to each have same newline(s)

### ISSUE THREAD

**Issue by diablodale** [mermaid-js/mermaid#4592]
### Description

When I put `\n` in a class diagram class name, this adds the same newlines to all class members below.
Easy example with mermaid from https://github.com/mermaid-js/mermaid/issues/3958#issuecomment-1474173500

### Result

The layout of the `Du\nck` class is doublespaced in the class header and throughout the class members. Resulting in the members being rendered outside the class box. And when a class has many members, it results in unreadable layout where members are over/under other class boxes.

### Expected

Class members spacing to be unrelated to the spacing/height of the class name. They are always inside their own class box.

### Steps to reproduce

1. Use example mermaid from https://github.com/mermaid-js/mermaid/issues/3958#issuecomment-1474173500
2. Paste it into https://mermaid.live/

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/679350/7a06126e-cf24-4db8-b053-c8e17626424d)

### Code Sample

```text
https://mermaid.live/edit#pako:eNpVksFunDAQhl8FzanVsiwYYgPqpWoSqYeccouQkgEbsBbsrW2abrb77rVpts2ePP78z3j-sU_QaS6ghm5Ca28lDgbnRn1VcsYp-vJ7u41ebpemUd3-5RrfSztekyfRGvyH6mgjlYtwEB_RozNSDdEgFBfmchCk9gFnH376_AHO6EQAa2__-4hOjboUagXuv-lJ-1ob-yrnIN_8WLDbh-h8yQ3N-qxt6MjKN_Fd3QvhPOhQ3aG70q42whWt1lMk7fOrnLjfmkWtOohhFmZGyf3YvC6KGnCjmEUDtQ-56HGZXAN_pbg4_XhUHdTOLCKG5cC9q_dBX8M7Lp02UPc4WQ8njX5GUJ_AHQ_hiQZpna_YadXLIfDFTB6Pzh1svduF42SQblzapNPzzko-onHjz4ruKKElklxQluNNnvOuzaqyJ0XWc5ZmBOF8juGAKlT9BXVWZEnBaFWRlGW0KKsihiPUhNCEUJpWOUtZwcqM-Kw3rb2PNGEVK2mVpyzPqoykNzGI1c_D-_8Ky3rH05qwmjz_AZ7P0sw
```

### Setup

- Mermaid version: 10.2.3
- Browser and Version: Chrome Version 114.0.5735.199 (Official Build) (64-bit)

also reproduces in VSCode with https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid

### Suggested Solutions

None known. One has to remove all `\n` from class names.

### Additional Context

Errant behavior occurs when using immediate `Du\nck` or the label method `["Du\nck"]`.
If the class has no members, then the errant behavior is silently not seen.

**Comment by sidharthv96** [comment]
Note: Fix PR will need tests to verify the error cases.

**Comment by tomperr** [comment]
I took a look last night, I think the error comes from the `class_box` function

https://github.com/mermaid-js/mermaid/blob/aaec16ed6c743ab8a787f2cbc942c9a84044f823/packages/mermaid/src/dagre-wrapper/nodes.js#L737

Line and text position calculations may be wrong. I am not used to SVG so I am not really confident about looking at it, but I might give it a try if nobody solves the problem in the next few days.

**Comment by diablodale** [comment]
...and if that's the right code area, then perhaps here is where the positioning of the ?labels? is based on the calculated boundingbox height of the class title instead of another calc that is based on the attribute or method itself

https://github.com/mermaid-js/mermaid/blob/aaec16ed6c743ab8a787f2cbc942c9a84044f823/packages/mermaid/src/dagre-wrapper/nodes.js#L920

https://github.com/mermaid-js/mermaid/blob/aaec16ed6c743ab8a787f2cbc942c9a84044f823/packages/mermaid/src/dagre-wrapper/nodes.js#L938

**Comment by ibrahimWassouf** [comment]
Thank you @tomperr  and @diablodale, with your help and hints towards the general location of the bug, I believe it is an easy fix. I'm just wrapping up here and should create a PR if that's ok with you both?
