### ISSUE TITLE
Class Diagram: Nested namespace cause Parse error.

### ISSUE THREAD

**Issue by smeghead** [mermaid-js/mermaid#4618]
### Description

When you define a namespace inside namespace in class diagram, you will cause Parse error.

### Steps to reproduce

1. Use code example.
2. This will cause Parse error.

```
Error: Parse error on line 9:
...r } namespace Sub2 {
---------------------^
Expecting 'STRUCT_STOP', 'CLASS', got 'ALPHA'
```

### Code Sample

```text
classDiagram
    class Animal {
        +String beakColor
    }
    namespace Sub {
        class Duck{
            +String beakColor
        }
        namespace Sub2 {
            class Fish{
                -int sizeInFeet
            }
        }
    }
    Animal <|-- Duck
    Animal <|-- Fish
```

### Setup

 * Mermaid version: 10.2.4
 * Browser and Version: Google Chrome version: 114.0.5735.133

**Comment by ibrahimWassouf** [comment]
Currently, a namespace can only contain classes. It makes sense though to want to add nested namespaces or notes inside a namespace. Perhaps this can be an added feature, if it makes sense to do so @sidharthv96. I'm not really sure if there is a "correct" way to use class diagrams and if there is a limit to the type of features we would want to add to them.

**Comment by jgreywolf** [comment]
I will approve it as a feature request, though I am not sure where it will land on a priority timeline

**Comment by jgreywolf** [comment]
@smeghead At this time we are not going to add nested namespaces into class diagrams. This may be something that we will look at in the future, but now now.

**Comment by bioinformatist** [comment]
@ibrahimWassouf @jgreywolf It's indeed a very practical feature, as it can properly limit the freedom during implementation, which is beneficial for teamwork.

**Comment by ShiromMakkad** [comment]
@jgreywolf @ibrahimWassouf Is there any other way to draw a box within a box? I want to draw a box to represent a crate and draw subboxes to represent folders within that crate. The goal of the diagram I'm making is to show my team how often we're crossing these lines and make the case for a refactor. It's very hard to do that without some way to draw nested boxes. 

Seems like there's lots of options for other diagrams: https://stackoverflow.com/questions/60805200/add-boxes-containers-in-mermaid-sequence-diagram. Is there another diagram type more suited to this? I still want to model code in classes (or I guess traits/structs in rust).

**Comment by IceflowRE** [comment]
> @jgreywolf @ibrahimWassouf Is there any other way to draw a box within a box? I want to draw a box to represent a crate and draw subboxes to represent folders within that crate. The goal of the diagram I'm making is to show my team how often we're crossing these lines and make the case for a refactor. It's very hard to do that without some way to draw nested boxes.
> 
> Seems like there's lots of options for other diagrams: https://stackoverflow.com/questions/60805200/add-boxes-containers-in-mermaid-sequence-diagram. Is there another diagram type more suited to this? I still want to model code in classes (or I guess traits/structs in rust).

As long as nested namespace are not implement i still use the flowchart with subgraph feature. You will lose the feature to display methods but you can go with Node = Class and subgraph = namespace/package

**Comment by IceflowRE** [comment]
> @smeghead At this time we are not going to add nested namespaces into class diagrams. This may be something that we will look at in the future, but now now.

Is it suitable to open an issue to cover the nested namespace/packages in class diagrams?

**Comment by jgreywolf** [comment]
@IceflowRE Take a look first.  I dont have access to my links right now, but Im mostly sure there is already an issue to cover what you have said

**Comment by frozenfrank** [comment]
It seems this request has resurface as https://github.com/mermaid-js/mermaid/issues/5487.
