### ISSUE TITLE
Empty namespace in classdiagram

### ISSUE THREAD

**Issue by kostkams** [mermaid-js/mermaid#4625]
### Description

It's not possible to create an empty namespace without any class.

### Steps to reproduce

1. Create only namespace without content

### Code Sample

```text
classDiagram
namespace Test
```

### Setup

- Mermaid version: 10.2.4
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by Yokozuna59** [comment]
In mermaid, namespaces are rectangles with a title wraps classes, does it make since to create an empty one with height and width?

**Comment by kostkams** [comment]
How could I create a rectangle? I haven't found something in the docu.
That would solve my need.

**Comment by kostkams** [comment]
Ah sry, we use mermaid as an uml data model design tool. The user can create emtpy classnames and add the class later.
Right now, we add a dummy class with "hidden"-class. But that is just a workaround

**Comment by jgreywolf** [comment]
> Ah sry, we use mermaid as an uml data model design tool. The user can create emtpy classnames and add the class later. Right now, we add a dummy class with "hidden"-class. But that is just a workaround

My suggestion would be to create a class within the namespace, just the name of the class itself.  That should give you your box.  Otherwise, the namespace will not draw

**Comment by jgreywolf** [comment]
Closing as this is not something, and there is a workaround available
