### ISSUE TITLE
linkStyle should really be supported in other diagram types

### ISSUE THREAD

**Issue by morgen-peschke** [mermaid-js/mermaid#4636]
### Proposal

Ideally, this would act the same as the existing syntax for `linkStyle` for `flowchart` diagrams. 

The use-case I would have liked to have this capability was for some sequence diagrams, particularly as a way to track/display relevant changes across different versions of a diagram. Looking over the various diagram types, I didn't see any diagram type with links that wouldn't benefit from being able to highlight individual links.

**Comment by jgreywolf** [comment]
Closing as duplicate of #4284
