### ISSUE TITLE
Flowchart / Graph node containing keywords causes syntax error

### ISSUE THREAD

**Issue by nirname** [mermaid-js/mermaid#4645]
# Description

This issue is combination of:

- #1876
- #2135
- #2495
- #3077
- #4079
- #4245

Any node ending with any LINK_TARGET

- `_self`
- `_blank`
- `_parent`
- `_top`

Or containing keywords such as
- `call`
- `graph`

in its name will cause syntax error

# Examples

## Sample 1

```
graph
    my_child --> my_parent
```

## Sample 2

```
graph TD
  test[this is a call thing]
```

## Sample 3

```
graph
    app_load["App Load"] --> any_api_call["Any API Call"];
    any_api_call --> any_api_call
```

## Sample 4

```
graph
    A-node
    A-graph
```

**Comment by nirname** [comment]
@ibrahimWassouf please refer to this one, I decided to combine all of the in one

**Comment by ibrahimWassouf** [comment]
Thanks @nirname, I've worked on allowing keywords in id strings. Next up is to allow keywords in vertices and edges as simple text.
