### ISSUE TITLE
README not rendering class diagram

### ISSUE THREAD

**Issue by tomperr** [mermaid-js/mermaid#4647]
### Description

When I read the README on the mermaid repo, the class diagram does not render

### Steps to reproduce

Go to [the homepage of the repo](https://github.com/mermaid-js/mermaid) and look at the README
Also, directly taking a look at [the README.md file](https://github.com/mermaid-js/mermaid/blob/develop/README.md) triggers the error

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/11899139/0100def3-4051-4edb-9e06-73f7576479d7)

### Setup

- Mermaid version: The one used by Github
- Browser and Version: Firefox 115.0.2

### Additional Context

The diagram renders correctly on the mermaid live editor.
I could not check right not, but might it be a mermaid version error? If the class diagram requires mermaid 10.2.0 version or later and Github uses mermaid 10.1.0 (I took random version numbers for this example), an error would be triggered

**Comment by sidharthv96** [comment]
GitHub uses 
```mermaid
info
```
