### ISSUE TITLE
set new `weekends` when `weekday` is set

### ISSUE THREAD

**Issue by Yokozuna59** [mermaid-js/mermaid#4661]
The changes in #4634 gave the ability to start the week with another day other than default (sunday), but now the default `excludes weekends` might have unexpected behavior, that why we need to set new weekends according to the start day.

**Comment by leinelissen** [comment]
From what I can see the excludes function currently uses Saturday and Sunday when determining weekend days: https://github.com/mermaid-js/mermaid/blob/a3c645c3ebbe3017854b558ffc5a647fabaea587/packages/mermaid/src/diagrams/gantt/ganttDb.js#L175.
The weekend is Saturday and Sunday irrespective of what day the week starts on right?

**Comment by Ronid1** [comment]
Traditionally in some countries/cultures the weekend starts on Friday, so I think there is value in the option to configure the start day to either Friday or Saturday.  I've added a PR for this configuration.
