### ISSUE TITLE
too much data expands the box , does not go inline maybe hover to work ?!

### ISSUE THREAD

**Issue by Thoybur-Rohman** [mermaid-js/mermaid#4671]
### Description
i want my digram to do this 
![image](https://github.com/mermaid-js/mermaid/assets/73062879/b86faa8d-f3ed-4ab1-a230-828e7ebbe00f)

i noticed in the mermaid editor it auto adds a br how do i do this in mine ? 
![image](https://github.com/mermaid-js/mermaid/assets/73062879/fb1f8809-c920-4aa5-a55c-f77c4b3ba423)

i want it to go downwards : https://mermaid-js.github.io/docs/mermaid-live-editor-beta/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG5cbjEoXCJERVBBUlRNRU5UIFRFU1RcIiktLS1kZTllZTExZS04MmVmLTRmNjQtODgxZC1mMGU1MWE4YjlhMWZcbmRlOWVlMTFlLTgyZWYtNGY2NC04ODFkLWYwZTUxYThiOWExZihcIjAzMyBDbGFzc25hbWVcbjAyMSBDbGFzc1xuMDkwIE5hbWVcbjA4OCBJcmluYVxuMDk5IE90aGVyIE5hbWVcbjAxMCBCYWtpbmdcbjAwMSBOdXRzXG4wMzEgUG9wQ29yblxuMDIwIERvZyBGb29kXG4wMjMgQ2F0IEZvb2RcbjkwMSBHaWZ0IENhcmRzXG4wMTUgQXJvbWFUaGVyYXB5XG4wMTcgQm9keSBDYXJlXG4wMTkgR2FtZXNcbjAyMiBHaWZ0IFNldHNcIiktLT58WWVzfEFjdGlvbjEoXCJBY3Rpb24gMVwiKVxuZGU5ZWUxMWUtODJlZi00ZjY0LTg4MWQtZjBlNTFhOGI5YTFmKFwiMDMzIENsYXNzbmFtZVxuMDIxIENsYXNzXG4wOTAgTmFtZVxuMDg4IElyaW5hXG4wOTkgT3RoZXIgTmFtZVxuMDEwIEJha2luZ1xuMDAxIE51dHNcbjAzMSBQb3BDb3JuXG4wMjAgRG9nIEZvb2RcbjAyMyBDYXQgRm9vZFxuOTAxIEdpZnQgQ2FyZHNcbjAxNSBBcm9tYVRoZXJhcHlcbjAxNyBCb2R5IENhcmVcbjAxOSBHYW1lc1xuMDIyIEdpZnQgU2V0c1wiKS0tPnxOb3xBY3Rpb24yKFwiQWN0aW9uIDJcIikiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ

graph TD;

1("DEPARTMENT TEST")---de9ee11e-82ef-4f64-881d-f0e51a8b9a1f
de9ee11e-82ef-4f64-881d-f0e51a8b9a1f("033 Classname
021 Class
090 Name
088 Irina
099 Other Name
010 Baking
001 Nuts
031 PopCorn
020 Dog Food
023 Cat Food
901 Gift Cards
015 AromaTherapy
017 Body Care
019 Games
022 Gift Sets")-->|Yes|Action1("Action 1")
de9ee11e-82ef-4f64-881d-f0e51a8b9a1f("033 Classname
021 Class
090 Name
088 Irina
099 Other Name
010 Baking
001 Nuts
031 PopCorn
020 Dog Food
023 Cat Food
901 Gift Cards
015 AromaTherapy
017 Body Care
019 Games
022 Gift Sets")-->|No|Action2("Action 2")

i get this syntax error , if i add it into 1 line i get 

![image](https://github.com/mermaid-js/mermaid/assets/73062879/fa267667-9fe7-409b-ac43-7b8db56f7df6)

### Steps to reproduce

graph TD;

1("DEPARTMENT TEST")---de9ee11e-82ef-4f64-881d-f0e51a8b9a1f
de9ee11e-82ef-4f64-881d-f0e51a8b9a1f("033 Classname
021 Class
090 Name
088 Irina
099 Other Name
010 Baking
001 Nuts
031 PopCorn
020 Dog Food
023 Cat Food
901 Gift Cards
015 AromaTherapy
017 Body Care
019 Games
022 Gift Sets")-->|Yes|Action1("Action 1")
de9ee11e-82ef-4f64-881d-f0e51a8b9a1f("033 Classname
021 Class
090 Name
088 Irina
099 Other Name
010 Baking
001 Nuts
031 PopCorn
020 Dog Food
023 Cat Food
901 Gift Cards
015 AromaTherapy
017 Body Care
019 Games
022 Gift Sets")-->|No|Action2("Action 2")

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/73062879/d291b806-930e-46ba-99f0-57d4bbf9596d)

### Code Sample

```text
graph TD;

1("DEPARTMENT TEST")---de9ee11e-82ef-4f64-881d-f0e51a8b9a1f
de9ee11e-82ef-4f64-881d-f0e51a8b9a1f("033 Classname
021 Class
090 Name
088 Irina
099 Other Name
010 Baking
001 Nuts
031 PopCorn
020 Dog Food
023 Cat Food
901 Gift Cards
015 AromaTherapy
017 Body Care
019 Games
022 Gift Sets")-->|Yes|Action1("Action 1")
de9ee11e-82ef-4f64-881d-f0e51a8b9a1f("033 Classname
021 Class
090 Name
088 Irina
099 Other Name
010 Baking
001 Nuts
031 PopCorn
020 Dog Food
023 Cat Food
901 Gift Cards
015 AromaTherapy
017 Body Care
019 Games
022 Gift Sets")-->|No|Action2("Action 2")
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
Provided code renders as required in GitHub too.
Please provide a reproduction of how you are trying to render.

Also, where did you get the live-editor-beta link from? I've seen that pop up in issues recently, it's an old editor which we replaced over a year back. Please use https://mermaid.live instead. 
If you can share from where you got the beta link, maybe that could be fixed. 
 
```mermaid
graph TD;

1("DEPARTMENT TEST")---de9ee11e-82ef-4f64-881d-f0e51a8b9a1f
de9ee11e-82ef-4f64-881d-f0e51a8b9a1f("033 Classname
021 Class
090 Name
088 Irina
099 Other Name
010 Baking
001 Nuts
031 PopCorn
020 Dog Food
023 Cat Food
901 Gift Cards
015 AromaTherapy
017 Body Care
019 Games
022 Gift Sets")-->|Yes|Action1("Action 1")
de9ee11e-82ef-4f64-881d-f0e51a8b9a1f("033 Classname
021 Class
090 Name
088 Irina
099 Other Name
010 Baking
001 Nuts
031 PopCorn
020 Dog Food
023 Cat Food
901 Gift Cards
015 AromaTherapy
017 Body Care
019 Games
022 Gift Sets")-->|No|Action2("Action 2")

```

**Comment by jgreywolf** [comment]
@Thoybur-Rohman Can you confirm if this issue is working as expected?

**Comment by jgreywolf** [comment]
Closing based on lack of response/activity
