### ISSUE TITLE
initialize of theme arguments works in version < 10, but not after

### ISSUE THREAD

**Issue by fralau** [mermaid-js/mermaid#4672]
### Description

In version 10, the following sequence does not alter the theme:

```html
<script type="module">import mermaid from "https://unpkg.com/mermaid@10.2.0/dist/mermaid.esm.min.mjs"</script>
<script>mermaidAPI.initialize({
    theme: "base",
    themeVariables: {
        primaryColor: "#BB2528",
        primaryTextColor: "#fff",
        primaryBorderColor: "#7C0000",
        lineColor: "#F8B229",
        secondaryColor: "#006100",
        tertiaryColor: "#fff"
    }
});</script>
``` 
(Does not work with `mermaid.initialize()` either).

But works in version 9 (colors are properly changed):

```html
<script src="[https://unpkg.com/mermaid@9.2.0/dist/mermaid.min.js](view-source:https://unpkg.com/mermaid@9.2.0/dist/mermaid.min.js)"></script><script>mermaid.initialize({
    theme: "base",
    themeVariables: {
        primaryColor: "#BB2528",
        primaryTextColor: "#fff",
        primaryBorderColor: "#7C0000",
        lineColor: "#F8B229",
        secondaryColor: "#006100",
        tertiaryColor: "#fff"
    }
});</script>
```

### Steps to reproduce

Try a diagram in version 9 and 10.

### Screenshots

Version 9:

![Capture d’écran 2023-07-26 à 16 07 20](https://github.com/mermaid-js/mermaid/assets/36767124/55b10981-9985-4019-8db8-4f11e6f2ca22)

Version 10:
![Capture d’écran 2023-07-26 à 16 07 58](https://github.com/mermaid-js/mermaid/assets/36767124/969349cc-1909-4e62-b1db-6e3f2eca927e)

### Code Sample

Use with e.g. this diagram:

    
     graph LR
        hello --> world
        world --> again
        again --> hello
    

```mermaid
graph LR
    hello --> world
    world --> again
    again --> hello
```

```html
<div class="mermaid">graph LR
    hello --&gt; world
    world --&gt; again
    again --&gt; hello
</div>
```

### Setup

- Mermaid version: 9.2.0 and 10.2.0
- Browser and Version: Firefox, Safari (Mac)

**Comment by sidharthv96** [comment]
Please use `mermaid.initialize`, not `mermiadAPI.initialize`.

```js
mermaid.initialize({
        theme: 'base',
        themeVariables: {
          primaryColor: '#BB2528',
          primaryTextColor: '#fff',
          primaryBorderColor: '#7C0000',
          lineColor: '#F8B229',
          secondaryColor: '#006100',
          tertiaryColor: '#fff',
        }
      });
```

<img width="132" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/3295e847-eb82-4972-8bec-b8d83753dc75">

**Comment by fralau** [comment]
As indicated, I did use `mermaid.initialize()` and it did not work.

**Comment by sidharthv96** [comment]
That was because you were using 2 separate script tags. 
```
<script type="module">import mermaid from "https://unpkg.com/mermaid@10.2.0/dist/mermaid.esm.min.mjs"</script>
<script>mermaidAPI.initialize({
```

Removing the second script tag fixes the issue.

![image](https://github.com/mermaid-js/mermaid/assets/10703445/81953a87-6623-49c7-bd3b-e81e03f85cfd)


```html
<div class="mermaid">
  graph LR
    hello --> world
    world --> again
    again --> hello
</div>

<script type="module">
import mermaid from "https://unpkg.com/mermaid@10.2.0/dist/mermaid.esm.min.mjs";
mermaid.initialize({
    theme: "base",
    themeVariables: {
        primaryColor: "#BB2528",
        primaryTextColor: "#fff",
        primaryBorderColor: "#7C0000",
        lineColor: "#F8B229",
        secondaryColor: "#006100",
        tertiaryColor: "#fff"
    }
});
</script>
```

**Comment by sidharthv96** [comment]
Please close this if it was resolved.

**Comment by fralau** [comment]
Interesting! Let me check.

**Comment by fralau** [comment]
This worked, thanks! mkdocs-mermaid2 was fixed and it worked.

See https://github.com/fralau/mkdocs-mermaid2-plugin/issues/82

🚀
