### ISSUE TITLE
Sankey nodes doesn't show values

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#4674]
### Description

We should add a config to show the actual numbers. 

<img width="645" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/3c1593fc-9b6d-4374-831b-65088110d6dd">

---

Other examples
![image](https://github.com/mermaid-js/mermaid/assets/10703445/44bcc8b7-f8ab-49e4-b3ac-b62015b9c083)
<img width="960" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/47f47d00-9179-48b6-b826-38af01927434">
![image](https://github.com/mermaid-js/mermaid/assets/10703445/48c5af00-94cf-4747-8d82-c59795093821)

### Steps to reproduce

N/A

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by nirname** [comment]
I think we have to add some sort of function to render node title

**Comment by jacquesfu** [comment]
Plus one

**Comment by sidharthv96** [comment]
<img width="620" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/1e380c43-25e1-4f1a-8b40-65c1aadd3f13">

I'm able to render the values. But we need to decide how we should show the prefix and suffix. 
Currently, I've added prefix and suffix as config options, but I doubt that's the best approach. 

Either, we should support all config values in the frontmatter, which would be a big change. 
Or, we could add support for prefix and suffix into the grammar. (Which we can add/remove as sankey is still in `beta`).
