### ISSUE TITLE
Error 404 and Main content showing at the same time on webpage

### ISSUE THREAD

**Issue by BnJam** [mermaid-js/mermaid#4676]
### Description

Starting in this [GitHub Blog Article](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) Following this link for [Mermaids Syntax](https://mermaid-js.github.io/mermaid/#/n00b-syntaxReference?id=syntax-structure) causes the 404 Error element to appear on top of the main elements at Mermaids home webpage. 

This occurs in Opera One (version: 102.0.4871.0) (x86_64) - at least

### Steps to reproduce

1. Start at [GitHub Article](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/)
2. Following the link "...allow you to create graphs inline using [Mermaid syntax](https://mermaid-js.github.io/mermaid/#/n00b-syntaxReference?id=syntax-structure), for example:"
3. Observe issue

### Screenshots

<img width="792" alt="Screenshot 2023-07-27 at 4 45 42 PM" src="https://github.com/mermaid-js/mermaid/assets/16641658/8b47f939-69bc-485a-b9e3-b0b93ee69463">

### Code Sample

```text
NA
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by Yokozuna59** [comment]
The has been link changed:

https://mermaid.js.org/intro/n00b-syntaxReference.html#syntax-structure

```diff
- /n00b-syntaxReference?id=syntax-structure
+ /intro/n00b-syntaxReference.html#syntax-structure
```
