### ISSUE TITLE
Improve arrow positions on sequence diagrams

### ISSUE THREAD

**Issue by simonborje** [mermaid-js/mermaid#4691]
### Description

Compared to most other sequence diagrams I've seen generated by other software, arrow heads in mermaid sequence diagrams are positioned differently. I would not necessarily say that the mermaid way is "wrong", but at least to my eyes it does look a bit "off" compared to what I'm used to seeing.

The largest difference is that arrow heads extend into activation boxes rather than end at the border of the box.
Also, at larger scales, the tip of the arrow heads seem to slightly shoot past the line that they point to when no activation box exist.
I have added two screenshots to illustrate how it looks now and how it might look if it was drawn like most examples I could find.

### Steps to reproduce

Link to the example used for the screenshots: [mermaid.live](https://mermaid.live/edit#pako:eNpNz1FPwyAQAOC_wu5V2lRWysrDjEYT9dU30xdsb2tjgclotDb970K7JfJAuLvvLscEtW0QJJzxa0BT42Onjk7pypBw7vuuxmS_v3m1rZHkGfvekvimpLXfRDkkox3uVhzz0T7YD0nCRUmtTKyTFpUjGi8ulJLgksvMbrUvi15kaNn8GxntsogM6IDYk6ND5TdAQaPTqmvC-lNsqMC3qLECGZ6Ncp8VVGYObjg1yuNT03nrQHo3IAU1ePs2mvoar-byfZAH1Z9D9qTMu7X6ikIIcoIfkIzxlAt2K_JMMFbwglEYQYoyFUJkZVlk5VbwmcLv0p6lO1bkebHlbCcYz4v5D_YccyI)

### Screenshots

Current look:
![image](https://github.com/mermaid-js/mermaid/assets/3867784/dac406f8-d229-470a-b73f-51f7a63f0409)

Mock-up:
![image](https://github.com/mermaid-js/mermaid/assets/3867784/431cd0d6-0752-4204-be02-90f3661bb9f5)

### Setup

- Mermaid version: 10.3.0
- Browser and Version: Firefox 115.0.3

**Comment by sidharthv96** [comment]
This is not "just" a sequence diagram issue. Similar issue exists with flowcharts. 
If someone who is familiar with SVGs could pitch in, that would be wonderful!


<img width="836" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/d3d2106a-d62b-497d-a81e-398d8d4b8cfc">
<img width="214" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/824d4d8c-69bf-4f3b-857f-9d93458c6874">
<img width="499" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/5304701f-d4a3-4741-9c5b-dc7db84b8d2a">

**Comment by sidharthv96** [comment]
Related

- https://github.com/mermaid-js/mermaid/issues/2154

**Comment by mastersibin** [comment]
I solved the bug for sequence diagrams

**Comment by sidharthv96** [comment]
@mastersibin, Wonderful! Can you raise a PR? Thank you :)

**Comment by mastersibin** [comment]
@sidharthv96 done.

**Comment by simonborje** [comment]
Thank you for looking into the issue!
I realize that my original description was pretty vague, so for clarification I see two issues:
1. The arrow heads go too far into the lines/boxes
2. The right arrows point at the line rather than the start of the box, e.g.:
![image](https://github.com/mermaid-js/mermaid/assets/3867784/31ddcf0f-ef1a-4cdc-b7a8-98f56df38fc4)
vs
![image](https://github.com/mermaid-js/mermaid/assets/3867784/cfa5107f-7cc8-4835-bd10-1793facdf502)
I'm not sure if the PR addresses one or both of these issues.
