### ISSUE TITLE
Entity Relationship Diagrams Moveable tables

### ISSUE THREAD

**Issue by wanand** [mermaid-js/mermaid#4704]
### Proposal

The ability to move tables around will greatly improve the useability of the solution

**Comment by Yokozuna59** [comment]
I think this is out of scope for the mermaid project. We could have a different layout with the `-v2` prefix, but giving the ability to move elements in the rendered diagram is out of scope.

The svg layout has different `g` tags for each element depending on the diagram; you could take those tags and move them around if you want.
I'd recommend you using other tools, e.g., [draw.io](https://app.diagrams.net), and insert the the mermaid code then manipulate and move the layout. Here's how to insert mermaid code: https://drawio-app.com/blog/create-mermaid-diagrams-in-draw-io/.
