### ISSUE TITLE
Initialize of theme arguments works in version < 10, but not after

### ISSUE THREAD

**Issue by fralau** [mermaid-js/mermaid#4712]
As indicated, I did use `mermaid.initialize()` and it did not work.

_Originally posted by @fralau in https://github.com/mermaid-js/mermaid/issues/4672#issuecomment-1669502331_

**Comment by fralau** [comment]
Unfortunately, the issue was mistakenly closed and it is not possible to reopen it.

**Comment by sidharthv96** [comment]
Re-opening https://github.com/mermaid-js/mermaid/issues/4672
