### ISSUE TITLE
`Syntax error in text` appears under the body tag.

### ISSUE THREAD

**Issue by xiaozzzi** [mermaid-js/mermaid#4730]
### Description

I'm not sure if this is a bug, `Syntax error in text` appears under the `body` tag.

### Steps to reproduce

Link to Live Editor:
https://mermaid.live/edit#pako:eNpdUMtqwzAQ_BWxZxnskpTiW4nJzaeeWnRZpE0qqoeRVocQ8u-VLRxK5zQ7u8ywcwcdDcEIVwzMKogKg0znmDyyEJ8V3Tx306RC22bSbGMQ7ztr8in6xRGTEYz5R_zBaGIguRlTHqR46YdD1w9d_yqf9O2_-ylZthrd5pbb7ly4JGr-Ngi9nzgb6Bm2qjXkaECCp_qENfW7--qggL_Jk4KxUkMXLI4VqPCop1g4ftyChpFTIQllWVuYLF4T-l1cMHzFWMcLulxnMpZjmluBW4-PX8wKaLI

```
gantt
    dateFormat  YYYY-MM-DD

    section A section
    Completed task            :done,    des1, 2014-01-06,2014-01-08

    section Critical tasks
    Future task in critical line        :crit1, 5d
```
In the last line of the above code, I use `crit1` instead of `crit`

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/42293085/9712a1c9-fbfb-428d-ba9c-e7c377ec7d2f)

### Setup

- Mermaid version:
- Browser [edge 115.0.1901.200]

**Comment by sidharthv96** [comment]
Anyone having the same issue with their custom integration of mermaid can use the logic from https://github.com/mermaid-js/mermaid-live-editor/pull/1288 to fix it.

**Comment by JatinSainiOO7** [comment]
can i work on this issue

**Comment by Rishikesh63** [comment]
i wants to work on it

**Comment by shobrook** [comment]
Has any progress been made here? Is there a way to stop that "Syntax error in text" message from showing up?

**Comment by aakashsharma7** [comment]
@xiaozzzi @can i work on it?

**Comment by sidharthv96** [comment]
This was fixed in mermaid live editor.
