### ISSUE TITLE
 Image stop rendering after 9.1 (2º Issue)

### ISSUE THREAD

**Issue by emersonbottero** [mermaid-js/mermaid#4736]
### Description

When using only an img tag the img is not rendered
It used to work before. This is a second Issue about the same topic, see #4023

### Steps to reproduce

https://mermaid.live/edit#pako:eNpNUU1TpDAQ_StUX9QqYIYA4WNXLXfHoyc9KXvoIQGyQkIlYXbHKf67YcZRc-r0637vdfcBasU4lND06l_dobbe06aSnnu_Xn6KofWMrq8vOmtHU65WA9cDChb-NaHS7fkb9KpVodm1Fzee5oPa8WDgfz5YguDm90uDZYPBFqXXKL0VjHH5Dd9cnnAzCim5vvrxBd1f3nknsEanhoHmVitv5LrD0dxegQ8fJtwMh6WvAtvxgVdQupChfq2gkrOrm0aGlt8zYZUGx9gb7gNOVj3uZQ2l1RM_F20EthqHzyp-bHo4beq4MB9GlFAe4D-UNA5JmkQkoSnNSJbnPuyhJHEaFkVCSLGOoiglSTL78KaUY12HeU6SNKckIyQuaJ760CtkXC-Mdj8uMq0w1snUSjaiXfKT7l36fIkFDlthu2kb1mpYGcGW63W7gq4ooTmSmNMsxjSOWb2NirwhSdSwbB0RhHk--n8-ulkGn98BKuijPQ

### Screenshots

![image](https://user-images.githubusercontent.com/12377432/213905624-5953764e-30ae-491b-a677-e6b9bd0f0e56.png)

with some text together... 
![image](https://user-images.githubusercontent.com/12377432/213905634-b2c7600d-fee4-4706-8fd1-a01ea7cf6233.png)

this broke my vitepress plugin.. 
from mermaid.render
![image](https://user-images.githubusercontent.com/12377432/213905664-f9fb30e1-2013-46a6-913a-8f688fa5510e.png)
to mermaid.renderAsync
![image](https://user-images.githubusercontent.com/12377432/213905700-27d39da2-224e-43ba-803d-9e51bf21ae8d.png)

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by aravind-cod-101** [comment]
I would like to try this issue, Can someone assign me this issue?

**Comment by jgreywolf** [comment]
@aravind-cod-101 Is there any update on this issue?

**Comment by bonyuta0204** [comment]
@jgreywolf
Hello, I've implemented a solution for the issue and created Pull Request #5063 accordingly. 
Could you please take a moment to review the changes in this pull request? Thank you!
