### ISSUE TITLE
Subgraph direction not respected when nodes are connected outside subgraph

### ISSUE THREAD

**Issue by jason-curtis** [mermaid-js/mermaid#4738]
**Describe the bug**
 Subgraphs are supposed to have their own directionality when you use a `direction XY` directive. However, when nodes within that subgraph are connected with nodes outside of that subgraph, the subgraph directionality is ignored.

**To Reproduce**
[Link to Live Editor](https://mermaid.live/edit#pako:eNptj8EKwjAMhl-lBLytL7CDB_HoST320rXZWlzb0aWIjL277SZziP8hhOTLn2QCFTRCDW0fnsrISOx-Ep5ljanpohwMozDwJhAFtzaKtI2oyAa_4UWZZJwf2Z5Gr3_8emyJR9sZ-ud3uX6rhVwMd_Tmt8bD4bNt4coAVOAwOml1fmsqlAAy6FBAnVMt40OA8HPmZKJwe3kFNcWEFaRBS8KzlflQB3Ur-xHnN_y_WlE)

Open live editor and uncomment the last line.

everything is OK:
![image](https://github.com/mermaid-js/mermaid-live-editor/assets/3341011/22de8461-105c-4b2c-9919-5340b9585d02)

and then it's not
![image](https://github.com/mermaid-js/mermaid-live-editor/assets/3341011/a82c2861-da49-40e5-a6e9-93d2fd9d41d9)

**Expected behavior**
"left-right" subgraph should stay in left-right orientation

**Actual Behavior**
"left-right" subgraph is forced into top-down orientation

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 115.0.5790.171

**Comment by Yokozuna59** [comment]
deplucate of #2509
