### ISSUE TITLE
Sync render version

### ISSUE THREAD

**Issue by drw0if** [mermaid-js/mermaid#4741]
### Proposal

I'm trying to integrate mermaid js into an already existing micromark pipeline which only uses sync functions to traverse the markdown tree.
It would be useful to have a sync version of the render function which could fit this use case.

### Example

Something like:
```js
mermaid.init(...)
let { svg } = mermaid.syncRender(text)
```

**Comment by sidharthv96** [comment]
That would not be possible due to the underlying architecture. 
render was sync previously, but was made async as a breaking change.
