### ISSUE TITLE
The erDiagram. Entity starts with underscore ("_")

### ISSUE THREAD

**Issue by kurotych** [mermaid-js/mermaid#4775]
### Description

I've tried to represent my psql database as `erDiagram`.
But it didn't support entities whose names start with "\_".
But the PSQL allows table name that starts with "\_" 

### Steps to reproduce
Submit the Code Sample to [ `https://mermaid.live`](https://mermaid.live)

### Code Sample

```
erDiagram
_customer_order {
    bigint id PK
    bigint customer_id FK
    text shipping_address 
    text delivery_method 
    timestamp_with_time_zone ordered_at 
    numeric total_tax_amount 
    numeric total_price 
    text payment_method 
}
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
cc @tomperr who has added a new feature to ER recently.
