### ISSUE TITLE
Graph LR does not adhere to LR direction

### ISSUE THREAD

**Issue by Nixxen** [mermaid-js/mermaid#4790]
### Description

When writing a graph LR using the following syntax, I expect the subgraphs to follow the direction of the main graph (left to right).
However, as seen in the example, the Databases do not go to the right of services and instead get pushed down.
The same issue applies to the graph TD, where everything is TD, except the Databases, which end up to the right of services.

The expected result for graph LR is a graph with `System A` to the left, followed by `Other Internal` or `Databases`, then the remaining one (`Databases` or `Other Internal` - whichever was not picked first earlier). Since `Databases` has more connections, it would be cleaner to have that first. Finally, insert the `External` subgraph.

### Steps to reproduce

1. Make a graph with subgraphs
2. Have subgraph nodes pointing to nodes in other subgraphs.
3. Make enough subgraphs and internal nodes to skew the intended direction of the graph.

### Screenshots

graph LR
![image](https://github.com/mermaid-js/mermaid/assets/14964915/cad253e1-7f0c-4165-9072-f99d1704f8a3)

graph TD
![image](https://github.com/mermaid-js/mermaid/assets/14964915/86025f87-d1f0-480e-8cfb-c9d895074c2c)

### Code Sample

```text
graph LR
    subgraph SystemA["System A"]
        subgraph Services
            Service1
            Service2
            Service3
        end
        
        subgraph databases["Databases"]
            Database1
            Database2
            Database3
            Database4
        end

        subgraph Other["Other Internal"]
            Server1
        end

        Service1 -->|"Fetch data from"| Server1["Server 1"]
    end

    subgraph External
        Server1 -->|Reads selective data from| ExternalSystem
    end

    subgraph Service1["Service 1"]
        CacheData["Cache data from Server 1"]
        
    end

    subgraph Service2["Service 2"]
        ParseData["Parse data and create events"]
    end

    subgraph Service3["Service 3"]
        ParseEvents["Parse Events and create:
        - Operations
        - Suboperations
        - Components
        - Data"]
    end

    Service2 -->|Fetch cached data from| Service1
    Service2 -->|Store Events in| Database1["DB Events"]
    Service3 -->|Get Events from| Database1
    Service3 -->|Store Operations in| Database2["DB Operations"]
    Service3 -->|Store Suboperations in| Database3["DB Suboperations"]
    Service3 -->|Store Components in| Database4["DB Components"]
```

### Setup

- Mermaid version: [Mermaidv10.3.0 Live Editor](https://mermaid.live/)
- Browser and Version: Vivaldi 6.2.3105.43 (Stable channel) (64-bit)

**Comment by sidharthv96** [comment]
Duplicate https://github.com/mermaid-js/mermaid/issues/2509
