### ISSUE TITLE
Railroad syntax diagram

### ISSUE THREAD

**Issue by McCache** [mermaid-js/mermaid#4800]
### Proposal

Mermaid.js should add Railroad syntax diagram for there isn't one implemented yet for Mermaid.

SEE: https://en.wikipedia.org/wiki/Syntax_diagram
SEE: https://github.com/tabatkins/railroad-diagrams

### Use Cases

This will greatly enhance our GitHub README.md for projects related to some kind of domain language that has a syntax.

### Implementation

None

**Comment by Yokozuna59** [comment]
duplicate of #4252, and it's under development in #4608 by @nirname.
