### ISSUE TITLE
Elk Rendering for Flowcharts does not support Title and arrow styling

### ISSUE THREAD

**Issue by pascha00** [mermaid-js/mermaid#4813]
### Description

Elk Rendering for Flowcharts does not support title and arrow styling.

### Steps to reproduce

Use the sample code below. 

### Screenshots

**without Elk rendering :** 
![image](https://github.com/mermaid-js/mermaid/assets/144045584/443ea0d5-39b5-4253-ac47-ae31803c2801)

**with Elk rendering activated :** The Title disappears and the "Master Data" Arrow is plain instead of dotted.
![image](https://github.com/mermaid-js/mermaid/assets/144045584/2b595608-71ae-467f-81a1-9f75544f3eed)

### Code Sample

```text
---
title: Interfaces for B
---
%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart LR
A-->|"Guarantee"|B
C-->|"User attributes"|B
C-.->|"Master data"|B
C-->|"Exchange Rate"|B
C-->|"Profit Centers"|B
C-->|"Vendor Partners"|B
C-->|"Work Situation"|B
C-->|"Customer"|B
C-->|"Profit Centers"|B
B-->|"Guarantee"|C
```

### Setup

- Mermaid version: Live Editor 10.3.0
- Browser and Version: Chrome

**Comment by sidharthv96** [comment]
Elk also does not support line length currently.
We need to fix that also.

**Comment by itsalam** [comment]
Hi, currently taking a crack at this, and it's almost complete but I'm having issues running the precommit linting step as I'm running into memory leaks - just wondering if anyone here could chime in on how to work with that?

**Comment by sidharthv96** [comment]
@itsalam, you can use the `git commit -n` flag to skip eslint for now.

**Comment by itsalam** [comment]
@sidharthv96 cool, just checking if thats fine with you guys, I'll upload in a bit.

**Comment by bish0polis** [comment]
#4844 seems to address this issue perfectly.  Is this issue jammed?
