### ISSUE TITLE
It is not possible to use the comma "," as separator for generic type fields, parameters and return types 

### ISSUE THREAD

**Issue by sk0gen** [mermaid-js/mermaid#4836]
### Description

There is no possibility to use comma as separator inside Generic return type/parameter in methods but
it is possible to use `ClassDiagram` with generic types for example

```
classDiagram
	class ExampleClass~T1,T2~
	ExampleClass : +Document Document
	ExampleClass : +Collection Collection
```

and it's genereting the graph as expected
![image](https://github.com/mermaid-js/mermaid/assets/28295528/d63e9a82-07db-4834-8bd9-bb03ef6d656d)

Another working scenario:

```
classDiagram
	class ExampleClass~T1,T2~
	ExampleClass : +Document Document
	ExampleClass : +Collection Collection 
        ExampleClass : +ExampleMethod(List~T~ parameter)
```
![image](https://github.com/mermaid-js/mermaid/assets/28295528/caa185af-b5f8-423a-9114-e13a1aa293cb)

Unfortunately it is not possible to use comma (',') in similar scenario inside method declaration
```
classDiagram
	class ExampleClass~T1,T2~
	ExampleClass : +Document Document
	ExampleClass : +Collection Collection 
        ExampleClass : +ExampleMethod(List~T,T1~ parameter)
```

### Steps to reproduce

1. Open live editor
2. Use `Code Sample`
3. Diagram is not generated

### Code Sample

```text
classDiagram
	class ExampleClass~T1,T2~
	ExampleClass : +Document Document
	ExampleClass : +Collection Collection 
        ExampleClass : +ExampleMethod(List~T,T1~ parameter)
```

### Setup

- Mermaid version: [Mermaidv10.3.0 Live Editor](https://mermaid.live/)
- Browser and Version: [Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (64-bit)]

### Suggested Solutions

- It should be possible to use comma as separator of generics inside methods, fields etc.

**Comment by sidharthv96** [comment]
<img width="852" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/9bbea703-3a9e-4aec-b924-58d15e66d70d">

This is fixed in v10.5.0-rc.1

We will release 10.5.0 soon. 

You can use https://mermaid-js.netlify.app to run the latest unreleased code from the develop branch.
