### ISSUE TITLE
Is has_parent a reserved word in Mermaidv10.3.0 Live Editor

### ISSUE THREAD

**Issue by FatCash** [mermaid-js/mermaid#4840]
### Description

This simple flowchart creates an error. Actually any name ending with *_parent creates the error. Is it some kind of reserved keyword?

Error: Parse error on line 3:
...lowchart TD has_parent{Whats going
---------------------^
Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF', 'SQS', 'AMP', 'STYLE_SEPARATOR', 'DOUBLECIRCLESTART', 'PS', '(-', 'STADIUMSTART', 'SUBROUTINESTART', 'VERTEX_WITH_PROPS_START', 'ALPHA', 'COLON', 'CYLINDERSTART', 'DIAMOND_START', 'TAGEND', 'TRAPSTART', 'INVTRAPSTART', 'START_LINK', 'LINK', 'DOWN', 'DEFAULT', 'NUM', 'COMMA', 'MINUS', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'LINK_TARGET'

### Steps to reproduce

Create following flowchart in Mermaidv10.3.0 Live Editor

### Code Sample

```text
flowchart TD

    has_parent{Whats going on?}
```

### Setup

- Mermaid version: Mermaidv10.3.0 Live Editor
- Browser and Version: Chrome Version 116.0.5845.187 (Official Build) (arm64)

**Comment by sidharthv96** [comment]
This is fixed in 10.4.0

https://mermaid.live/edit#pako:eNoli0EKAyEMRa8iWc8J3HQzN2ihm0AJmqq0xiETKUXm7nXoXz0e7w8ILTJ4eL7bJ2RSc7cVxc1l2h8bKYuNeybbXWpFkmtyOWCBylqpxPkcZ45gmSsj-ImR9IWAcnbUrV2_EsCbdl6gb5GM10JJqf7l8QPT4C24
