### ISSUE TITLE
tickInterval option with the possibility to select "second" as unit

### ISSUE THREAD

**Issue by K-lone** [mermaid-js/mermaid#4843]
### Proposal

Hi ! I would like to use Gantt charts as an easy and flexible way to draw chronologies for historic and archaeologic purposes using markdown and mermaid language. For this, I needed to be able to include negative and large dates.

From what I red, the only way is to build gantt graph with a x-axis in second (%s). It works like a charm but I have a problem when dealing with the tick intervals. As mentionned by DarkNami in #1598 and #3729, supported units for the tick interval option are: minute, hour, day, week, month. I cannot fix the intervals and the output is quite ugly :( Is there any way to add second as unit for time interval ? Thanks !

PS: I had an example with real data ... but it seems that the compact display mode is not working on github. Anyway, it shows the tickInterval problem !

### Example

```mermaid
---
displayMode: compact
---
%%{init: { "theme": "neutral", "themeVariables": { 'fontFamily": "Times" } } }%%
gantt
    title Archaeological periods
    dateFormat X
    axisFormat %s  
    section Western Europe
        Mesolithic   : -8800, -4900
        Neolithic : -4900, -2000
        Bronze age: done, -2000, -800
        Iron age: done, -1100, -1
        Roman: -56, 400
        Early Middle Ages: done, 400, 800
        Early Middle Ages: done, 800, 1500
        Post-medieval period: 1500, 1800
        Modern: crit, 1800, 2023
```

**Comment by sidharthv96** [comment]
Fixed in https://github.com/mermaid-js/mermaid/pull/4778
Will be released soon. 

[Try here](https://beta.mermaid.live/edit#pako:eNo1Ts0KwjAMfpUQ8LaDc-ihZxl47rWX0EYt21JpM1HG3t0ONacv-f6yoE-B0eCNRNVJIOU-5YkUrLVONPrhIsr5SSOcCvskwQm9YvmpdrY4qXeNSaDPNLETqNMa2DfQHst3PRj4w85A2xVscOKaEEMtXzbGod652tFUGCgPDp2sVUezJvsWj0bzzA3Oj-3Lc6RbrUNzpbHw-gGfDkJK)
