### ISSUE TITLE
flowchart classDef font-size is rendered properly in LiveEditor, but not in Github renderer

### ISSUE THREAD

**Issue by injecteer** [mermaid-js/mermaid#4863]
### Description

In my flochart diagram I have the following classDef with `font-size:x-small`.

in LiveEditor it works like charm and looks as expected.

![grafik](https://github.com/mermaid-js/mermaid/assets/32952/7b5a6fa4-eed8-403c-94bf-4e421f05b397)

Although if I put the very same code into a README.md and view it on Github, the text inside boxes with `:::ext` is rendered small, but the boxes themselves are displayed in original size:

![grafik](https://github.com/mermaid-js/mermaid/assets/32952/c9f683ca-e13f-4580-8655-507757a69e95)

### Steps to reproduce

1. the working example it [here](https://mermaid.live/edit#pako:eNqNVctuEzEU_RXLbECKo2mbNNMRqtSqFQipAtGIBYSF43Eybj32yPakSavu2YNUCRb8Ays-i0_g2plkHqkKm9H43Ov7OD7XvsNMpxwneCb1Dcuoceh0PFETxyS19ozPEF86NNPKEStuebIkNqdS9hDTUpvkWRzH3psWBRFqpp9_muA_P398QeOMo5OikIJRJ7RChdELkXKLXo_H7whXaaGFchY5_XJqjhmERNpl3CAmS-u44Smy3CwEgy16wY334gsOZUxLO8GfXyRJApVVuUPWh18IfsHmwZTnmjBtOAGvYP72gOaGCmlJSh21ztvm2uQkE1NuFHV86JPMjdaLVf3nvXnphGxAV1arxnJFcwlp64rq5DucSDE11KxqPpwnqlzT8Ort-wt0cjlGY0OVnUFxa_LgD50rJ5zgnd63mUKOr9_RFtjwoHMqVJOEbN-nuqLsGroIXEyFSj0m9XxwRTzbxMrZ4KrCpuBKghwE85AttAcgh1-Bt1t2Vhm95ZIBxw2IU-kywjLOrmv0hk_bxK2r_TdrPh8y3OrSgEJ6m4j9JVjyQivutUVVitYRUSh_h7xg2zIXVhVteRCjzURH1h9Ckh7yJwXfcP7hxDzv7eh1iEqdEOA3qtEqkxM5J5XUnx4hYdGUWhiMtfje0AUNLW5JoYiVxkDr3uzjorWEnFDzzTSFYULnp-1am0VsZqmJVbXecOqr35bbUNX2PEEpAkpoHWt33__dFBRV-8LsL52hLDg82Ukn1aaZDlz1A9cFIn2CNrfXFiPHGzk0Zyz4tme7be_7fc2Lp1bZem8t76aluauB97dVkB1JhXAdkXY9Wk10DP6i3EVbR75r7pLYEU6oaUfOu16tujoxQ4zH5PKo75OR-rsVex5xD-ccpkKk8OjdTRRCEww-OWgigd-Uz2gpQb4TdQ-uFG7my5ViOHGm5D1cFv45OBMUnpIcJzMqLaA8FfCcXKwf0vCe9nBB1Uetax9Y4-QOL3Gyf9SPRwejYXywdxgNomjQwytAo2F_f7Q3iOIo3ouGg9F9D9-GAFH_CBDA4ngQg_vh8P4vLODWcg)
2. the Github README.md is [here](https://github.com/injecteer/vx-demo#readme)

### Screenshots

LiveEditor
![grafik](https://github.com/mermaid-js/mermaid/assets/32952/7b5a6fa4-eed8-403c-94bf-4e421f05b397)

Github
![grafik](https://github.com/mermaid-js/mermaid/assets/32952/c9f683ca-e13f-4580-8655-507757a69e95)

### Code Sample

```text
flowchart BT
	classDef ext font-size:x-small, color:#888
	domain-info(["🛈 The library provides core resources, vert.x components and domain classes"]):::ext
```
```


### Setup

- Mermaid version: 10.4.0
- Firefox 115.2.1esr (64-Bit)
- Chrome Version 117.0.5938.63 (64-Bit)

### Suggested Solutions

_No response_

### Additional Context

_No response_

**Comment by sidharthv96** [comment]
It _could_ be because GitHub is on an older version of mermaid, and I don't think we can do anything about it. 

👇 

```mermaid
info
```
