### ISSUE TITLE
Changing graph nodes text color

### ISSUE THREAD

**Issue by nfroidure** [mermaid-js/mermaid#487]
Hi! Thanks for this useful library.

I'd like to be able to change the text color in my graphs. I naively trie:
```
  classDef controller fill:#890620,color:#ebd4cb,stroke:#ebd4cb,stroke-width:1px;
```

But it doesn't work unfortunately.

I tried to look for similar issues but not sure there are. Those looks similar but no example were provided so i'm not sure it is the same need:
- https://github.com/knsv/mermaid/issues/381
- https://github.com/knsv/mermaid/issues/50

I really need this feature so i would PR the project if anyone point me out where I can change it since the codebase is huge and I did not found were the styling things takes place.

**Comment by marceloboeira** [comment]
Also doesn't work for me...

**Comment by tylerlong** [comment]
Please create a sample in https://mermaidjs.github.io/mermaid-live-editor/ to reproduce the bug. Thanks.

**Comment by DropkickSteve** [comment]
This is no bug I think, according to documentation there is no "color" setting for the text color of the node.
I think you have to fork the project and change the css on your own. You are looking for class .label where the default color is set to #333

**Comment by scribu** [comment]
I think Mermaid should allow changing the text color on a per-node basis.

If you set the fill color to something dark, you also need to change the text color to white, for it to not look horrible.

**Comment by mullinmax** [comment]
I too would really like to have this feature. I can't use dark colors for my nodes so the diversity of colors I can use is significantly reduced.

**Comment by jgahn-i4vine** [comment]
I used HTML tag for font color of node. For example, 
```
graph LR
MyApp --> DB(<font color=white>fa:fa-database MySQL)
style DB fill:#00758f
```

**Comment by marceloboeira** [comment]
It is still an issue...

**Comment by dazraf** [comment]
Please can we have something more powerful for inline styles? Similar to PlantUML. Stylesheets don't really cut it - specially for services like Gitlab!

**Comment by BobMilli** [comment]
Text color style would definitively be a great feature !

**Comment by eduo** [comment]
Why is the current functionality not enough?

I understand it's not as straightforward as defining in the diagram code itself, but some of the comments point to problems that today are already solved.

Styling of boxes, backgrounds, text and lines is possible using CSS. Also by extension things like hover, visited and animaction (marching ants, for example).

I'm currently using mermaid for a petri net workflow application and the style that will be applied to each step is defined by the type of step. So far the only thing that isn't easily stylable is the type of arrow (because such a thing doesn't exist in CSS). I'm attaching a few screenshots. The one with black dotted line is actually animated marching ants and the red one just outlines selection (clicking adds a class)
![Screen Shot 2019-07-24 at 13 56 55](https://user-images.githubusercontent.com/154630/61791684-f2f47300-ae1a-11e9-8b68-a3cfac42a4f9.png)

I might be missing what the specific miss is here, to be able to help.

**Comment by Logerfo** [comment]
At least for me, the problem is for websites that support mermaid within itself, like GitLab. Users cannot edit mermaid settings or apply any CSS.

**Comment by marceloboeira** [comment]
It also doesn’t work for the CLI, which is my main use of mermaid. It seems like a terrible idea to have a CLI for svg generation distributed in a interpreted language,
I’ve considered writing my own but I have no time these days.

**Comment by Logerfo** [comment]
I'm interested.

**Comment by knsv** [comment]
Hmm, the bots are rising. We have a rebellion on our hands.

**Comment by jpetro416** [comment]
I want this feature... I hate that there is such a lack of dynamic manipulation in this package. Compare this to Go.js and it's almost day and night. Not sure why we can't just reference a node like an array element `mermaid.changeNodeColor("ID", "CSS COLOR");  `

**Comment by tastevens** [comment]
This seems like a such a basic thing to have :/

**Comment by Dunning-Kruger** [comment]
@jpetro416 @tastevens We're always welcoming new contributors. If you'd like to help out, feel free to check our ["collaborators wanted"](https://github.com/mermaid-js/mermaid/issues/866) issue, read our [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/master/CONTRIBUTING.md), and [join us in slack](https://join.slack.com/t/mermaid-talk/shared_invite/enQtNzc4NDIyNzk4OTAyLWVhYjQxOTI2OTg4YmE1ZmJkY2Y4MTU3ODliYmIwOTY3NDJlYjA0YjIyZTdkMDMyZTUwOGI0NjEzYmEwODcwOTE)!

**Comment by etimau** [comment]
Sorry if I didn't understand the question but, for me, color in a classDef is working...
(with named color, #rrggbb or #rgb)
See [online editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblxuJSVjbGFzc0RlZlxuY2xhc3NEZWYgY2xhc3NBbGVydCBmaWxsOnJlZCxjb2xvcjp3aGl0ZSxzdHJva2Utd2lkdGg6MnB4LHN0cm9rZTpkYXJrUmVkO1xuY2xhc3NEZWYgY2xhc3NPayBmaWxsOmdyZWVuLGNvbG9yOiMwMEZGMDAsc3Ryb2tlLXdpZHRoOjJweCxzdHJva2U6ZGFya0dyZWVuO1xuY2xhc3NEZWYgY2xhc3NXYXJuIGZpbGw6b3JhbmdlLGNvbG9yOiNGRjAsc3Ryb2tlLXdpZHRoOjJweCxzdHJva2U6ZGFya09yYW5nZTtcblxuJSVmbG93Y2hhcnRcbkFbRGVmYXVsdCBzdHlsZV0gLS0-IEJbQWxlcnQgc3R5bGUhXVxuQSAtLT4gQ1tPSyBzdHlsZSFdXG5BIC0tPiBEW1dhcm5pbmcgc3R5bGUhXVxuXG4lJVN0eWxlXG5jbGFzcyBCIGNsYXNzQWxlcnQ7XG5jbGFzcyBDIGNsYXNzT2s7XG5jbGFzcyBEIGNsYXNzV2FybjsiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

**Comment by GDFaber** [comment]
I'm going to work on a PR for this as it can improve the visualisation when ```htmlLabels``` are disabled.

**Comment by sappjw** [comment]
It would be nice to have other CSS text attributes available too (i.e., `text-decoration`).

**Comment by GDFaber** [comment]
Hi @sappjw, I agree but would like to leave this issue to setting the text color only. Feel free to open another issue for the settings you consider most preferable.

**Comment by GDFaber** [comment]
The SVG attribute for text color is also ```fill``` which is already used to style the node itself. As ```color``` is already used as a workaround, I would like to keep it that way and use the ```color``` settings for disabled htmlLabels as well (it is then turned into ```fill``` for the ```text``` objects in the node). I'm going to submit a PR this weekend.
