### ISSUE TITLE
Images inside nodes seem to have stopped working

### ISSUE THREAD

**Issue by iconics-milan** [mermaid-js/mermaid#4878]
### Description

Using the current live editor (mermaid.live), existing samples that show how to embed images seem to have stopped working. For example the solution from #1133 renders just an empty node.

`graph TD
  DIR("<img src='https://iconscout.com/ms-icon-310x310.png'; width='30' />")`

renders just an empty node.

### Steps to reproduce

Paste the code sample into the live editor, it will render just an empty node. Both on Chrome and Firefox.

### Code Sample

```text
`graph TD
  DIR("<img src='https://iconscout.com/ms-icon-310x310.png'; width='30' />")`
```

### Setup

- Mermaid version: v10.4.0
- Browser and Version: Chrome 117.0.5938.92, Firefox 117.0.1

**Comment by itz-salemm** [comment]
Is this issue being worked on?
