### ISSUE TITLE
Export as PNG hangs

### ISSUE THREAD

**Issue by DavidCampbell-architect** [mermaid-js/mermaid#4901]
### Description

When I try to use the "Export as PNG" option, the document hangs indefinitely with the "Generating hi-res PNG" animation playing.

### Steps to reproduce

1. Open a diagram
2. Click the Export icon in the sidebar menu on the left
3. Click the "Export as PNG" option in the menu that pops up

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/138038670/59166269-6d86-41cd-94fd-38034496d443)

### Code Sample

```text
Not applicable. This happens regardless of the code.
```

### Setup

- Mermaid version: Whatever www.mermaidchart.com is set to on 10/03/2023
- Browser and Version: Brave Version 1.58.135 Chromium: 117.0.5938.140
- Also happens in Edge Version 117.0.2045.47 (Official build) (64-bit)

**Comment by Yokozuna59** [comment]
Hi @DavidCampbell-architect, thanks for reporting the issue, but mermaid doesn't have `export as png` functionality, it's part [mermaidchart](https://www.mermaidchart.com/).

Please report this issue in here https://github.com/Mermaid-Chart/issue-tracker.
