### ISSUE TITLE
C4 examples highlight is unreadable

### ISSUE THREAD

**Issue by italomaia-bk** [mermaid-js/mermaid#4905]
### Description

C4 examples use a highlight schema which leaves the text and background in tones in gray and that makes reading them very hard.

### Steps to reproduce

1. go to https://mermaid.js.org/syntax/c4.html#c4-container-diagram-c4container
2. check any of the examples

### Screenshots

![no-contrast](https://github.com/mermaid-js/mermaid/assets/44257361/3bde9b6a-5f66-4b79-9c05-2230b4e16205)

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

- either change highlight so text uses regular "black" color
- or add support for C4 highlight so proper constrast is used

**Comment by huynhicode** [comment]
@italomaia-bk Thanks for reporting!

This issue has been fixed in [PR-4924](https://github.com/mermaid-js/mermaid/pull/4924).

<img width="801" alt="Screenshot 2023-11-16 at 11 01 32 AM" src="https://github.com/mermaid-js/mermaid/assets/35910788/a8459c31-3425-44de-b6d2-d279d4b17745">
