### ISSUE TITLE
Export as PNG takes a long time or doesn't work

### ISSUE THREAD

**Issue by oryx-it** [mermaid-js/mermaid#4919]
### Description

Export as PNG takes a long time or doesn't work

### Steps to reproduce

Click on export and then on png

### Screenshots

<img width="699" alt="image" src="https://github.com/mermaid-js/mermaid/assets/111514654/21813269-f445-481d-b20f-42ba4bf0f1fc">

### Setup

- Mermaid version: Latest and greatest
- Browser and Version: Firefox 118.0.1

**Comment by RounakJoshi09** [comment]
Hey @oryx-it , I couldn't able to reproduce this issue. Can you give some more insights on how to catch this one. Thanks in Advance.

**Comment by Yokozuna59** [comment]
The issue should be filed in @mermaidchart, not here.

**Comment by huynhicode** [comment]
@oryx-it Sorry for any confusion or inconvenience.

Please log Mermaid Chart issues in our [Issue Tracker](https://github.com/Mermaid-Chart/issue-tracker/issues).  This will help the Mermaid Chart team prioritize bugs fixes and new features.
