### ISSUE TITLE
replace old twitter logo-enhancment

### ISSUE THREAD

**Issue by chaursiyasanjeet** [mermaid-js/mermaid#4921]
Hello there is an old logo of twitter in the documentation I can replace that

<img width="634" alt="image" src="https://github.com/mermaid-js/mermaid/assets/111435565/0451da5d-2d19-4d7a-b475-c26c847bf248">

Please assign me this issue I want to work in this.

**Comment by huynhicode** [comment]
Thanks for mentioning @chaursiyasanjeet .

Feel free to work on this issue as issues are not assigned.  Please review the [contributing docs](https://mermaid.js.org/community/development.html) and submit a PR when you are ready.

Thanks for your contributions!

**Comment by chaursiyasanjeet** [comment]
Hey @huynhicode thank you for giving the permission to work on the issue

I have raised the PR #4923 , please check it and merge it

Thank you

**Comment by Thanush19** [comment]
can i fix this??

**Comment by chaursiyasanjeet** [comment]
Hey @Thanush19  I have already raise the PR which fixing this problem, I will suggest fo find other issue.
