### ISSUE TITLE
MermaidAPI text overflow out of the node

### ISSUE THREAD

**Issue by zxzzxxzx** [mermaid-js/mermaid#494]
Hello,
when using mermaid.js all nodes with text inside were rendered correctly. But when I switched to MermaidAPI text in the node began to flow out of bounds. It is applied both for some longlonglong words with no spaces and for some longer texts which overflow down the node.
Any ideas how to fix that? Thank you 
![image](https://cloud.githubusercontent.com/assets/6254088/24138942/322e2c24-0e2b-11e7-9402-9cc48d227ca8.png)

**Comment by zxzzxxzx** [comment]
Found out that when set htmlLables to false in MermaidAPI, text does not overflow, but no html markup applied. When set to true, text overflows out of bounds. This issue does not show up in mermaid.js

**Comment by zxzzxxzx** [comment]
Actually is there a possibility to find out how the dimensions of rect are calculated and to override them? I guess it is done via getBBox() call but which styles are applied? Is it possible to state somewhere in config (or in code directly) something like font-size: 20px and make calculations of rect based on this values? I tried to do that in mermaid.forest.css, but it did not work.

**Comment by tylerlong** [comment]
Could you please reproduce the issue in https://mermaidjs.github.io/mermaid-live-editor/ and post a link back here?

**Comment by ggilmore** [comment]
Hello, I don't know if this is the same issue, but I see a similar problem here: 

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgYSBhcyBBXG4gICAgcGFydGljaXBhbnQgYiBhcyBCXG4gICAgYS0-YjogVGhpcyBpcyB2ZXJ5IGxvbmcgbGFiZWwgdGhhdCBzaG91bGQgc2hvdWxkIHN0cmV0Y2ggYWNyb3NzIGV2ZXJ5dGhpbmcgaW4gYSB3YXkgdGhhdCBpcyB1bnJlYWRhYmxlLlxuICAgIGItPmE6IHRlc3QgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

![screen shot 2018-06-19 at 3 31 40 pm](https://user-images.githubusercontent.com/9022011/41627628-e611b7cc-73d5-11e8-85ff-e510763b25d4.png)

**Comment by davidolrik** [comment]
I have the same issue with text in notes not staying in the box.

https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgYSBhcyBBXG4gICAgcGFydGljaXBhbnQgYiBhcyBCXG4gICAgYS0-YjogVGhpcyBpcyB2ZXJ5IGxvbmcgbGFiZWwgdGhhdCBzaG91bGQgc2hvdWxkIHN0cmV0Y2ggYWNyb3NzIGV2ZXJ5dGhpbmcgaW4gYSB3YXkgdGhhdCBpcyB1bnJlYWRhYmxlLlxuICAgIE5vdGUgb3ZlciBhOiBUaGlzIGlzIHZlcnkgbG9uZyBsYWJlbCB0aGF0IHNob3VsZCBzaG91bGQgc3RheSBpbiB0aGUgYm94IC5cbiAgICBiLT5hOiB0ZXN0ICIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

**Comment by rajasekaran2003** [comment]
The issue still exists in the latest version.

**Comment by rajasekaran2003** [comment]
@tylerlong the issue still exists in the latest editor

**Comment by rajasekaran2003** [comment]
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5wYXJ0aWNpcGFudCBBXG5wYXJ0aWNpcGFudCBCXG5Ob3RlIHJpZ2h0IG9mIEE6IHRleHQgb3ZlcmZsb3cgZm9yIG5vdGUgYm94ZXNcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

**Comment by rajasekaran2003** [comment]
https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5wYXJ0aWNpcGFudCBBXG5wYXJ0aWNpcGFudCBCXG5Ob3RlIHJpZ2h0IG9mIEE6IHRleHQgb3ZlcmZsb3cgZm9yIG5vdGUgYm94ZXNcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

**Comment by apavlyut** [comment]
Any updates fo fix?

I have the same issue on notes in sequences

**Comment by Tilix4** [comment]
Hi! Same issue for me...

**Comment by dany74q** [comment]
I've tackled similar overflow issues, namely:

- When the actor description is larger than the configured `conf.width`
- When there are notes with text that is larger than their hosting rectangle
- When there are participant messages with text that is larger than the configured actor margin

I propose fixes to the above in the following PR:
https://github.com/mermaid-js/mermaid/pull/1365
