### ISSUE TITLE
The order of svg is reversed for sequence diagram participant nodes

### ISSUE THREAD

**Issue by ad1992** [mermaid-js/mermaid#4946]
### Description

Hi team we are using this package to support mermaid in Excalidraw. To compute the position and dimensions I am using the SVG rendered by mermaid. 
However when updating from `10.2.3` to `10.3.0` (so I can get the Actor Creation and Destruction supported 10.3.0 onwards), the order participant nodes is reversed and its only reversed for actor type Participant which makes the migration tricky.

Eg let's consider this diagram
The **indexes** in the diagram resembles the **order** of nodes on the **DOM**  

![image](https://github.com/mermaid-js/mermaid/assets/11256141/f67a8c4f-7998-44ec-8931-603bd73a013d)

Further more the order when mixing actor symbols and participants is even more confusing

![image](https://github.com/mermaid-js/mermaid/assets/11256141/67c7bf5f-1f08-4f37-bc54-21eea637e20b)

Was there any specific reason for this change ?
Also I would like to know if the team is open to storing the dimensions and coordinates when using the API `mermaid.mermaidAPI.getDiagramFromText` ? That would help us in not being dependent on SVG for calculating positions / dimensions.

### Steps to reproduce

Try in different versions (10.2.3 vs 10.3.0)

### Screenshots

Shared above

### Setup

- Mermaid version: 3.0.0
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by Shivraj-Nakum** [comment]
I would like to contribute to this issue
plz assign it to me
