### ISSUE TITLE
Published Docs are Broken - Nav links are not clickable

### ISSUE THREAD

**Issue by NickBorgersOnLowSecurityNode** [mermaid-js/mermaid#4960]
### Description

The docs published here https://mermaid.js.org/intro/, [presumably generated from this content](https://github.com/mermaid-js/mermaid/tree/develop/docs), are broken at the moment. Specifically it is not possible to click on the links on the left nav. This makes it very difficult to navigate the published documentation.

NOTE: It works just fine if you visit the homepage first https://mermaid.js.org/ ! This broken behavior is only manifesting for me when I go directly to the docs!

I am running on MacOS and demonstrate this behavior with Mozilla Firefox and Google Chrome in the attached Gif. Many other links on the page work but the left Nav links do not.

### Steps to reproduce

1. Launch a Private Browsing or Incognito Window and go directly to https://mermaid.js.org/intro/
1. Click a nav link on the left side of the page like "State Diagram" under "Diagram Syntax"
1. Nothing happens; I should have been taken to the doc page on "State Diagram"

This procedure DOES WORK:
1. Launch a Private Browsing or Incognito Window and go directly to https://mermaid.js.org
1. Click the "Docs" button on top ribbon to be taken to https://mermaid.js.org/intro/
1. Click a nav link on the left side of the page like "State Diagram" under "Diagram Syntax"
1. The link works and I arrive at the page for "State Diagram" docs

### Screenshots

NOT WORKING, when you go direct to the docs:
![output_optimized](https://github.com/mermaid-js/mermaid/assets/73143201/078c3b82-dc4e-4e5f-a423-44b13b7c0664)

WORKING if you go through homepage:
![output_optimized](https://github.com/mermaid-js/mermaid/assets/73143201/97efd8a8-b2c9-4e8c-a9d9-6f0e122dbe20)

**Comment by itz-salemm** [comment]
Hi @NickBorgersOnLowSecurityNode This issue has been raised #4914 #4894

**Comment by huynhicode** [comment]
This seems to have been resolved with the latest update to Docs.

Closing issue - please reopen if needed.  Thanks!
