### ISSUE TITLE
Application Crash due to `(-->` Syntax

### ISSUE THREAD

**Issue by justkash** [mermaid-js/mermaid#4964]
### Description

Whenever I write the symbols: `(-->` (as you might while you're in the middle of creating a node), the application freezes and crashes.

I've only experienced this issue through the use of Mermaid within Notion and only while using `Graph`/`Flowchart`.

### Steps to reproduce

1. Create `Flowchart LR`/`Graph LR` diagram 
2. Write `node_a(-->node_b-->node_c`
3. Application Freeze/Crash

### Setup

- Mermaid version: Unknown (Notion 19-Oct-2023)
- Browser and Version: Safari 17.0

**Comment by vic-132** [comment]
Is there a way to recover my notion files? Or are they lost?
