### ISSUE TITLE
Examples Illegible in Docs Without Highlighting

### ISSUE THREAD

**Issue by mjmatthiesen** [mermaid-js/mermaid#4971]
### Description

When I look at diagram example code, it's grey on grey, completely illegible. I have to highlight to read.

### Steps to reproduce

1. Open Docs
2. Go to timeline example
3. Try to read (you cannot)

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/16603906/711bb711-3d3a-44dd-898e-5cfdc18c8eb3)

### Setup

- Mermaid version: Yes
- Browser and Version: Firefox 118.0.2

### Suggested Solutions

Make it legible. No reason the example text shouldn't be black.

### Additional Context

Using superior light theme.

**Comment by huynhicode** [comment]
@mjmatthiesen thanks for reporting!

This is being looked into.  We will update this issue when it has been resolved.

**Comment by marameref** [comment]
is this issue open, can i work on it?

**Comment by huynhicode** [comment]
@marameref Thanks for the interest in contributing!

I have submitted a [PR](https://github.com/mermaid-js/mermaid/pull/4998) for this issue.

Closing issue - please reopen if needed. Thanks!

**Comment by nirname** [comment]
Should not we keep this issue opened till request is merged?

**Comment by huynhicode** [comment]
@mjmatthiesen and all - this has been resolved with [PR-4924](https://github.com/mermaid-js/mermaid/pull/4924).
