### ISSUE TITLE
Website menu is not usable

### ISSUE THREAD

**Issue by Arthessia** [mermaid-js/mermaid#4982]
### Description

Hi,

are you aware of the fact the website https://mermaid.js.org/intro/getting-started.html is not usable?

I cannot click on any link from the menu (I tried all my browsers)

Thanks!

### Steps to reproduce

1. https://mermaid.js.org/intro/getting-started.html
2. click on any link on the menu (left menu)

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by cuevana8** [comment]
+1 ..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/mermaid-js/mermaid/issues/4982#issue-1958628586)

**Comment by AlansCodeLog** [comment]
Just ran into this. I don't think it's that the links are dead, but there seems to be some sort of padding getting applied to some element that's covering the links. I can get them working again by shrinking my window to the mobile layout then expanding it again (very weird). Am on chrome btw.

**Comment by NurRehman** [comment]
Assign it to me, I can handle that.

**Comment by huynhicode** [comment]
@Arthessia Thanks for reporting.

There are similar issues that have been logged:

https://github.com/mermaid-js/mermaid/issues/4969

https://github.com/mermaid-js/mermaid/issues/4960

https://github.com/mermaid-js/mermaid/issues/4902

https://github.com/mermaid-js/mermaid/issues/4894

@NurRehman Please feel free to work on this issue and raise a PR when ready. Thanks in advance for your contribution!

**Comment by vaibhav210603** [comment]
all links on the left are working just fine for me, please confirm

**Comment by Arthessia** [comment]
it looks better, but I'm not testing on the same PC, I'll confirm on next week

thanks!

**Comment by AlansCodeLog** [comment]
Seems to be working now (tested on desktop).

**Comment by huynhicode** [comment]
This seems to have been resolved with the latest update to Docs.

Closing issue - please reopen if needed.  Thanks!
