### ISSUE TITLE
getMessages API doesn't support Entity codes

### ISSUE THREAD

**Issue by ad1992** [mermaid-js/mermaid#4983]
### Description

If the messages contain entity codes, they are removed when using the `diagram.parser.yy.getMessages` API

### Steps to reproduce

copy the below mermaid syntax and use `diagram.parser.yy.getMessages` 

```
sequenceDiagram
    A->>B: I #9829; you!
    B->>A: I #9829; you #infin; times more!
```
when using ``diagram.parser.yy.getMessages`  👇🏻 

```
[
    {
        "from": "A",
        "to": "B",
        "message": "I",
        "wrap": false,
        "type": 0
    },
    {
        "from": "B",
        "to": "A",
        "message": "I",
        "wrap": false,
        "type": 0
    }
]
```

As you can see the `message `n attribute just contains the character `I`

### Setup

- Mermaid version: 10.2.3

**Comment by ad1992** [comment]
Was looking into this and this is what I got so far 👇🏻 

When [`apply`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/diagrams/sequence/sequenceDb.js#L463) is being triggered the message data already doesn't have entity codes so probably something wrong is going on with the jison parser, however I tried to parse explicitly with jison parser -https://bramp.github.io/js-sequence-diagrams/ and it works well.

I am not familiar with the jison grammar so would appreciate any further leads 🙏

**Comment by manojkumar20k3** [comment]
If this issue is still open ,I would love to contribute. Please assign it to me, So that i can start my first contribution.
