### ISSUE TITLE
Links to the documentation from mermail.live are broken

### ISSUE THREAD

**Issue by nirname** [mermaid-js/mermaid#4989]
### Description

When editing diagram in [mermaid.live](https://mermaid.live) docs button is supposed to lead me directly to the documentation for the graph type I am editing. Now it leads only to the main page. Seems that rerouting inside documentation is broken.

### Steps to reproduce

1. Open mermaid.live
2. Pick any of sample diagrams
3. Click "docs" button

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/2842432/d42bd3d4-839c-4913-8b12-5563b1c55323)

### Code Sample

These links are broken

```text
https://mermaid.js.org/#/sequenceDiagram
https://mermaid.js.org/#/flowchart
https://mermaid.js.org/#/classDiagram
```

etc...
did not have checked each and every

### Setup

- Mermaid version: 10.6.0 (on the documentation website)
- Browser and Version: Chrome

### Suggested Solutions

- Either fix links inside live editor (https://mermaid.live)
- Or fix redirects on the main documentation website (https://mermaid.js.org)

**Comment by LadegbayeStella** [comment]
Please, assign to me

**Comment by shubhusion** [comment]
kindly assign this to me

**Comment by nirname** [comment]
@shubhusion @LadegbayeStella no need to assign. Simply open PR and link it to this request. If you had already started but not have finished yet, you can mark this PR as a draft, and click ready for review when it's done.
When using [special Github keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) like resolves linking will be done automatically. And even if you give up implementing feature half-way every member of the community will see this PR and can take an inspiration from it.

**Comment by huynhicode** [comment]
@nirname Thanks for catching this!  Wonder if this issue should be cross-referenced in [Mermaid Live issues](https://github.com/mermaid-js/mermaid-live-editor/issues).

**Comment by sidharthv96** [comment]
For context:

1.  The redirect used to work properly. (Logic is in redirects.ts file)
2. Now, it works locally, but throws 404 in production. 

Possible issues: Version upgrade of vitepress ?

**Comment by sidharthv96** [comment]
> @nirname Thanks for catching this! Wonder if this issue should be cross-referenced in [Mermaid Live issues](https://github.com/mermaid-js/mermaid-live-editor/issues).

It's not technically a LE bug, as those old URLs should work here. 
But as you've fixed it in LE, we can avoid an unnecessary redirect now :)
