### ISSUE TITLE
The code is hard to read in light mode

### ISSUE THREAD

**Issue by nirname** [mermaid-js/mermaid#5001]
### Description

All the diagrams without syntax highlight in the light mode on the documentation pages are in grey color and hardly visible.

### Steps to reproduce

1. Go to https://mermaid.js.org/syntax/c4.html
2. Have a look at the code block

More examples

https://mermaid.js.org/syntax/c4.html
https://mermaid.js.org/syntax/mindmap.html
https://mermaid.js.org/syntax/timeline.html
https://mermaid.js.org/syntax/zenuml.html
https://mermaid.js.org/syntax/sankey.html
https://mermaid.js.org/syntax/xyChart.html

### Screenshots

![image (24)](https://github.com/mermaid-js/mermaid/assets/2842432/3bf42369-97d1-4bcf-aa23-e5dc5c61426a)

### Setup

- Mermaid version 10.6.0
- Browser and Version: Chrome

### Suggested Solutions

Styling is broken on the documentation website

**Comment by Yokozuna59** [comment]
It should be resolved in #4998.

**Comment by huynhicode** [comment]
Thanks for reporting @nirname and for referencing the open PR @Yokozuna59 .

A user had previously logged a similar issue [4971](https://github.com/mermaid-js/mermaid/issues/4971).

I am going to close this issue as it is a duplicate and there is a PR.  Please reopen if needed - thank you!
