### ISSUE TITLE
Support Pandoc Syntax

### ISSUE THREAD

**Issue by jorlando-tuik** [mermaid-js/mermaid#5004]
### Proposal

Mermaid is great! Thank you for all of the effort you have put into the diagram as code ecosystem.

I currently keep architecture diagrams in a github repo. I have a pandoc workflow that will generate the diagrams into png files, and then embed the diagrams into downstream documents as well. 

Since the code is already in GitHub, it would be nice if users could see rendered versions of the diagrams within the code view HTML. However, it seems that the pandoc version of markup is not recognized as a mermaid diagram. An example of the diagram syntax is below.

```
```{.mermaid #fig:start-stop}
%%| caption: "Start Stop"
%%| alt: "A flow chart representing the Start Stop workflow"
%%| name: "start-stop"
%%{init: {'theme': 'forest', "flowchart" : { "curve" : "basis" } } }%%

flowchart TD
    Start --> Stop
```

Would it be possible to support detecting pandoc style mermaid diagrams, and also ignore the pandoc comments (ie. `%%`)?

### Example

```
```{.mermaid #fig:start-stop}
%%| caption: "Start Stop"
%%| alt: "A flow chart representing the Start Stop workflow"
%%| name: "start-stop"
%%{init: {'theme': 'forest', "flowchart" : { "curve" : "basis" } } }%%

flowchart TD
    Start --> Stop
```

**Comment by sidharthv96** [comment]
Because the language tag is ` ```{.mermaid #fig:start-stop}`, GitHub will not detect it as a mermaid diagram. 
There is nothing we can do inside mermaid to fix that. 

The `%%` comments are already ignored by mermaid, so that shouldn't be an issue. 

````md
```mermaid
%%| caption: "Start Stop"
%%| alt: "A flow chart representing the Start Stop workflow"
%%| name: "start-stop"
%%{init: {'theme': 'forest', "flowchart" : { "curve" : "basis" } } }%%

flowchart TD
    Start --> Stop
```
````

becomes

```mermaid
%%| caption: "Start Stop"
%%| alt: "A flow chart representing the Start Stop workflow"
%%| name: "start-stop"
%%{init: {'theme': 'forest', "flowchart" : { "curve" : "basis" } } }%%

flowchart TD
    Start --> Stop
```

**Comment by jorlando-tuik** [comment]
Thank you for the feedback @sidharthv96 . I just filed a similar request to github https://github.com/orgs/community/discussions/73226.
