### ISSUE TITLE
Move ELK to external package

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#5043]
> It appears elkjs is being used from version 9.4.0 and up. However, since elkjs has an [Eclipse Public License 2.0](https://choosealicense.com/licenses/epl-2.0/) (which is a copyleft license), this forces us (and any commercial closed source users) to use an older version of mermaid-js.
>
> Is there no alternative?

_Originally posted by @hermanussen in https://github.com/mermaid-js/mermaid/issues/1969#issuecomment-1448209869_

**Comment by zszen** [comment]
Me too, I upgrade mermaid-js for Typora mardown. but it never support elk layout
