### ISSUE TITLE
Configure Class Diagram to Use Other Curves

### ISSUE THREAD

**Issue by LingkKang** [mermaid-js/mermaid#5056]
### Description

I found that flowchart can use `%%{ init: { 'flowchart': { 'curve': 'stepBefore' } } }%%` to easily configure the curve style, with various styles supproted. However, I did not found the way to do this in **Class Diagram**.

Specificly, I wonder is it possible to have right angles instead of curves, as what normal UML class diagrams usually have.

### Steps to reproduce

This is easy to reporduce, for example:

```
classDiagram
  class A
  class B
  class C
  A -- B
  C -- B
```

``` mermaid
classDiagram
  class A
  class B
  class C
  A -- B
  C -- B
```

### Setup

Using mermaid at [mermaid.live](mermaid.live). Currently, it is _v10.6.1_.

**Comment by LingkKang** [comment]
#2067 Found this issue

**Comment by jgreywolf** [comment]
Closing this as duplicate
