### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'x')

### ISSUE THREAD

**Issue by stefanstranger** [mermaid-js/mermaid#5064]
### Description

With Mermaid version 10.6.1. the following [Mermaid code](https://gist.github.com/stefanstranger/2ba6b101308c9a18087ad90440a5902e) shows the error "TypeError: Cannot read properties of undefined (reading 'x')"

That Mermaid code was working in version 10.4.0. See following screenshot.

![image](https://github.com/mermaid-js/mermaid/assets/2125385/e4b99a3d-7206-4444-a77b-6f95cfec34ba)

What has changed since version 10.4.0 that breaks the Mermaid diagram creation?

### Steps to reproduce

1. Download following [gist](https://gist.github.com/stefanstranger/2ba6b101308c9a18087ad90440a5902e)
2. Run Mermaid cli with latest version (e.g. via Docker) like this: docker run --rm -v c:/temp:/data minlag/mermaid-cli -i test.mmd
    This should give an error.
3. Run Mermaid cli with version 10.4.0 (e.g. via Docker) like this: docker run --rm -v c:/temp:/data minlag/mermaid-cli:10.4.0 -i test.mmd
 This should create an svg file.

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/2125385/585cce74-7858-450f-8c0d-0aac8073381d)

### Code Sample

```text
https://develop.git.mermaid.live/edit?gist=https://gist.github.com/stefanstranger/2ba6b101308c9a18087ad90440a5902e#pako:eNqdWFtv0zAU_itTnunDJvGyB6RR2BigMS2Fp0lHbuy2Fqkd2Q5QEP-dYztNmhFf0j11yfF3vnP3yZ-ikpQV18VWkWZ3sXr7LC7wb6X4dsuU_0e3a_92KQXlhksBC1juWPUd-AY2vGbANQhpgAsoK8Ubo2Eja8rUYqVa5lEoV6yyh3sl9q9kggIRwPaE1wDfruD0nYEfRHGyRg0L-xPe1nJ9iwofidlFBa3QA9mzqJBFGYSQScxeKQzhgim4F9oQUTEoDTEMVkztucBfNGnsO1YzPEGg6sG2SrbNIHGHJGu5RfcpuR8J8k7rtEEhC26lAkaqHVzFeM20M6ns1sXeZkOPFle_b6S2QXHmowptoG1qSSijsCT4yiZZgG9WHg5nP3ONT216wBqTSY9Ydsx1yMKyko3luSQGzVxAVyZrSQ9QIU-ByQRUMs-C_bK68i23yX3C5WqQeyQKpT6WXx460c7DNoFP5QIV02P6Y83JqbCNtxjsuj7E6Htfejfa0rWnvAMnYh_WtFKHPpAbzKEpr8ZojLwTPpzvIOfWyxDtr8Jgq1pgbe4bV8-YdCZd-cQaefkaNMOipnp497JGj32gUegeZThmk9yEmkZP70XYLhaLNxkFmVUNDmtWkWYKd8DnFXOknzvc0GSZr6-DyxhGCaEQ0HhYRQRCAONBFgu7Q5jRA-8F-orU_Dd7qfNm-XRDcSI8Eq1_SkUdsg23ewrHx1CySuFTN9A-sQN8I21tPPiH1erRRkExO2BKIxXZMripKtkK4_mVO6K82S-Eb8oUQRT56lKuA-5wp8GOxZf0XS7nDHZW2MkmCZKT8NwNxR9GDzQ1B50f0pSWUb3NJpNC792TqWJcigkHJvCWXW9PcbR9Q1uO2oeQ-BCKNOOez1C3eeYlcMe9JFN_BmYfiZywZWCOW1akTtq1dt0YO_Y9TYA-MS1bVTEX4gF9otoTQOHqDCCm8aZ6Ucp4PzJn51YkK1Ma__NgQlWIYXCUTY6N04skdlyzY6AkjmI_f-Fkes-5M_ppefaV_ZyTE1el6Vt9XMbB5Fz64zKxi0tkJzjb8MnVYepiOmtxyEmOkfr8fWJ2NmWuGkmxGZE5XUZCq0fgwnv0Orx3jx6k4RteEdtKPV7udS1Ed-6F4ThWHV58jxq2IiccWqAyFqXxKnQ1CX_WF5D0x5oj9chXn5ma-1t2zleikOb_wpmRXdkbaZfuqYE4GuvFq2KPJhJOi-vij8V5LrDOsZyKa_xJ2cYtDcWz-IuipDWyPIiquN6QWrNXRdtQ9M07TnBB33dP__4DE8J05g
```

### Setup

- Mermaid version: 10.6.1
- Browser and Version: Edge 119.0.2151.72

**Comment by sidharthv96** [comment]
Thanks for reporting this @stefanstranger.
I've found the newly added issue and patched it. 
But the root cause is how the arrows between a subgraph, and its child, is handled. 
Which would need a deeper inspection.
