### ISSUE TITLE
How to identify in the text where a node is

### ISSUE THREAD

**Issue by ted-marozzi** [mermaid-js/mermaid#5068]
### Description

Hi, I am the creator of an the ecosystem project Mermaid Flow.
Currently I am using the api getDiagramFromText to get information about the diagram, such as the current nodes and links ect. I wish to edit things about the nodes programatically, to do that I am using complex regexp matchers to find the node in the current text and modify it.

My question is, is there any internal api to, say from an node id, find the index of the diagram text where the node is written? Alternatively is there a way to programatically modify the diagram text such as changing node labels that will be reflected in the final diagram text?

Cheers. 

### Steps to reproduce

1. Call getDiagramFromText
2. Notice we can't manipulate the text the user has entered.

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
Currently, we don't have that support :( . 
Something like this could possibly be added once we have Langium parsers for all the diagrams. But it's gonna be a while to get the bigger diagrams converted.

**Comment by ted-marozzi** [comment]
Thanks, is Langium being rolled out to replace bison/jison? Can i track it somewhere?

**Comment by ted-marozzi** [comment]
Gonna close this because we don't have immediate plans to support
