### ISSUE TITLE
 Regarding the interaction of the flow chart, add a js callback function mechanism for clicking on the node, and report an error when clicking on the node.

### ISSUE THREAD

**Issue by life2022** [mermaid-js/mermaid#5074]
### Description

 Regarding the interaction of the flow chart, add a js callback function mechanism for clicking on the node, and report an error when clicking on the node.

### Steps to reproduce

Bug：[jsfiddle](https://jsfiddle.net/Ogglas/2o73vdez/7)

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/48848815/d34b0892-c3f2-4c3a-968b-b415f3b9248e)

### Setup

- Mermaid version:
- Browser and Version: Chrome

**Comment by sidharthv96** [comment]
Please add a `window.callback = callback;` at the end, to attach your function to the window.

**Comment by reckertz** [comment]
As a generic approach I use   $(document).on("click", ".nodeLabel", function (evt) { ... }); to capture a click on a node, $(this).text(); gives the node-information that is needed in the event - function. I use it for submodels starting with the clicked node. Mermaid is a great tool.
