### ISSUE TITLE
Annonations on classes from the mermaid example give syntax error in text

### ISSUE THREAD

**Issue by Jarivanbakel** [mermaid-js/mermaid#5089]
### Description

The following code gives a syntax errors in text.
Removing the line ```<<interface>> Shape``` makes it work.

Note: We've tested multiple versions of mermaid and they don't seem to work.
```html
---
title: Class diagram
---

<pre class="mermaid">
classDiagram
class Shape
<<interface>> Shape
Shape : noOfVertices
Shape : draw()
</pre>
<script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11.0.0-alpha.6/dist/mermaid.esm.min.mjs';
</script>
```

### Steps to reproduce

1. Copy the code and paste it to an .md file 
2. Try to show the diagram on the web.

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/55702583/2aaed298-ae55-4536-95c1-fabf1ac52ab3)

### Setup

- Mermaid version:10.6.1 & 11.0.0-alpha.6
- Browser and Version: Chrome Version 119.0.6045.161 (Official Build) (64-bit)

**Comment by Jarivanbakel** [comment]
```html
classDiagram
class Shape<Type>
Shape : noOfVertices
Shape : draw()
```
Also does not work.

**Comment by jgreywolf** [comment]
< and > are explicitly not supported.  Per the [documentation ](http://mermaid.js.org/syntax/classDiagram.html#generic-types)use ~ syntax to denote types

**Comment by jgreywolf** [comment]
Interesting.  I am seeing syntax error if I put this code into a webpage as you have shown here.  
But it does NOT fail on mermaid.live.  
![image](https://github.com/mermaid-js/mermaid/assets/300077/d2845d8f-c918-4998-9d0c-ef9cf60ab49c)

**Comment by Jarivanbakel** [comment]
Closed the issue, guess the script was not up to date.

**Comment by jayPare** [comment]
Seems to be still present with 11.12.1 if using _mermaid.min.js_.

**Comment by vasildakov** [comment]
I had the same issue on 11.12.2 — <<interface>> only works if the Mermaid source is rendered as plain text (not via innerHTML). For example:

```html
<pre class="mermaid">
classDiagram
class Shape &lt;&lt;interface&gt;&gt;
</pre>
```
