### ISSUE TITLE
Mermaid Class Diagram incorrect in the Docs

### ISSUE THREAD

**Issue by ad1992** [mermaid-js/mermaid#5092]
### Description

The class Diagram for [Cardianlity and Multiplicity](https://mermaid.js.org/syntax/classDiagram.html#cardinality-multiplicity-on-relations) seems to be wrong as it is different from the mermaid live editor.

![image](https://github.com/mermaid-js/mermaid/assets/11256141/7ec0279a-c634-4e3a-b5a8-067632d2e48b)

Additionally the height for the label `many` should slightly increase so its not cut off as well (Its cutting in both)

### Steps to reproduce

Mentioned Above

### Screenshots

Added Above

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by ad1992** [comment]
> > This probably might be related to mermaid version being old in docs ?
> 
> I don't think so. Docs use the latest version of mermaid, it's sometime the live editor that has older mermaid versions. I think there is an unreleased fix, so 10.6.2 might solve this.

Alright sounds good! Any ETA on the release date of 10.6.2 ? I am assuming all these [bug fixes ](https://github.com/mermaid-js/mermaid/pulls?q=is%3Apr+author%3Aad1992+is%3Aclosed) would also be pushed to the  10.6.2?

**Comment by sidharthv96** [comment]
<img width="768" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/da237ef7-bf63-4e6e-b3c0-e51f283e5736">

Yeah, seems like it's fixed in develop. 

No fixed ETA on 10.6.2, you can follow progress in https://github.com/mermaid-js/mermaid/milestone/11

**Comment by jgreywolf** [comment]
Closing as this issue is resolved
