### ISSUE TITLE
Different behavior of activation and its shortcut in sequence diagrams.

### ISSUE THREAD

**Issue by voroninp** [mermaid-js/mermaid#5105]
### Description

This does not work:
```
sequenceDiagram
    participant A
    participant B

    A ->>+ B: Do 1
    A ->>- B: Do 2
```
> Error: Trying to inactivate an inactive participant (A)

Yet this works:
```
sequenceDiagram
    participant A
    participant B

    A ->> B: Do 1
    activate B
    A ->> B: Do 2
    deactivate B
```

as well as this:
```
sequenceDiagram
    participant A
    participant B

    A ->> B: Do 1
    activate A
    A ->> B: Do 2
    deactivate A
```

### Steps to reproduce

See above.

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/9202028/244109c1-0a58-4932-a775-0bfb17f96f8b)

vs

![image](https://github.com/mermaid-js/mermaid/assets/9202028/3b3737c3-3057-48a2-8032-59cc336cbae9)

or

![image](https://github.com/mermaid-js/mermaid/assets/9202028/a85df9f2-e08f-4b9a-aad0-6b3cba164241)

### Setup

- Mermaid version: 10.6.1
- Browser and Version: Chrome Version 119.0.6045.200

### Suggested Solutions

Behavior should be equivalent.

**Comment by sidharthv96** [comment]
```
    A ->>- B: Do 2
```
Is trying to deactivate A, not B. 

So the equivalent code would be 

```
sequenceDiagram
    participant A
    participant B

    A ->> B: Do 1
    activate B
    A ->> B: Do 2
    deactivate A
```

which indeed throws an error. 

So, what you need is

```
sequenceDiagram
    participant A
    participant B

    A ->>+ B: Do 1
    B ->>- A: Do 2
```

**Comment by voroninp** [comment]
> Is trying to deactivate A, not B.

Is `A ->>+ B` activating A or B?

**Comment by sidharthv96** [comment]
Ahh, I see the confusion. 

`A ->>+ B` activates B, but `A ->>- B` tries to deactivate A.

I'm **_guessing_**, the logic is Activation message activates the recipient, while deactivation message deactivates the sender. 

If `A ->>- B` were to deactivate A, that would mean we'd have to reverse the flow when writing the diagrams, which is counter intuitive.

**Comment by voroninp** [comment]
Hm, indeed, after being activated, B must deactivate itself, so to say.

```
sequenceDiagram
    A ->>+ B: Activate
    B ->>- A: Deactivate
```
![image](https://github.com/mermaid-js/mermaid/assets/9202028/6f1fe996-9a19-4ac4-a6ce-c58b445c4a74)
