### ISSUE TITLE
CSS Class not applied in classDiagram when escaped class name begins with a number

### ISSUE THREAD

**Issue by jacbz** [mermaid-js/mermaid#5106]
### Description

When I attach a CSS class to a class where the name was escaped, and the name starts with a number, the CSS class is not applied.

### Steps to reproduce

Generate diagram for this:

```
classDiagram
class `2c`:::className {
    << Test >>
}
```

Expected: `2c` has CSS class "className".

Actual: `2c` does not have CSS class "className".

### Setup

- Mermaid version: 10.6.0
- Browser and Version: Chrome

**Comment by sidharthv96** [comment]
cc @jgreywolf

**Comment by jgreywolf** [comment]
I do not think there is anything specifically disallowing this to work.

However, looks like there is currently an issue with the ::: syntax - see #1649 

I will check the number question - otherwise will close this as duplicate

**Comment by aviram-shubeili** [comment]
> ### Description
> When I attach a CSS class to a class where the name was escaped, and the name starts with a number, the CSS class is not applied.
> 
> ### Steps to reproduce
> Generate diagram for this:
> 
> ```
> classDiagram
> class `2c`:::className {
>     << Test >>
> }
> ```
> 
> Expected: `2c` has CSS class "className".
> 
> Actual: `2c` does not have CSS class "className".
> 
> ### Setup
> * Mermaid version: 10.6.0
> * Browser and Version: Chrome

@jacbz  semi-related question - where are you defining the css Class?

**Comment by jacbz** [comment]
This is a minimal sandbox example what does not need the actual CSS definition.

**Comment by jgreywolf** [comment]
Closing in favor of https://github.com/mermaid-js/mermaid/issues/1649
