### ISSUE TITLE
--> on_call is not escaped?

### ISSUE THREAD

**Issue by mitinarseny** [mermaid-js/mermaid#5134]
### Description

Take a look at these two almost identical flowcharts. The first one uses `on_call1` node name and it works. While the second one uses `on_call` and it shows an error. Looks like something is not properly escaped...

```mermaid
flowchart LR
    a --> on_call1
```

```mermaid
flowchart LR
    a --> on_call
```

### Steps to reproduce

have a flowchart with a link to a node called `on_call`

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/10659110/057114ff-cda8-499b-bc3e-6ca3add69c11)

### Setup

- Mermaid version:
- Browser and Version: Safari

### Additional Context

Meanwhile, both `on_call` and `on_call1` work well in VS Code markdown preview extension. So the bug might be in GitHub's integration for mermaid

**Comment by sidharthv96** [comment]
GitHub has an old version, works well in mermaid.live
```mermaid
info
```
