### ISSUE TITLE
'&' not rendered as expected

### ISSUE THREAD

**Issue by cnglen** [mermaid-js/mermaid#5149]
### Description

& not rendered as expected

### Steps to reproduce

```
  flowchart LR;
  ref_mut["&&&&&&"];
```

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/4279208/aef4db73-7df8-4308-9f43-4f0afe273bd4)

### Code Sample

```text
flowchart LR;
  ref_mut["&&&&&&"];
```
```


### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

_No response_

### Additional Context

_No response_

**Comment by prateek1998** [comment]
Hi @cnglen, this is not a major error, it is because of the font family which they're using. For more clarification check the screenshot.

![image](https://github.com/mermaid-js/mermaid/assets/37973089/5d9beb0a-e6fc-43bc-ada6-29de87fa3f25)

**Comment by cnglen** [comment]
x

> Hi @cnglen, this is not a major error, it is because of the font family which they're using. For more clarification check the screenshot.
> 
> ![image](https://private-user-images.githubusercontent.com/37973089/293340663-5d9beb0a-e6fc-43bc-ada6-29de87fa3f25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDM4ODQsIm5iZiI6MTcwMzk0MzU4NCwicGF0aCI6Ii8zNzk3MzA4OS8yOTMzNDA2NjMtNWQ5YmViMGEtZTZmYy00M2JjLWFkYTYtMjlkZTg3ZmEzZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDEzMzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZWE5NTEyNzFhYWU1ZjJlYThiN2E3NWRkZTAzZDc0N2JjYmZhMDNmMTM1Njk1MTZiZDEzMDBjNTc4OThhYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vPW4oo2ntWqDiJfWLdTVhgldlr27jzcFFZ3A9cZ2CZs)

how to check and set the font-family which mermaid is using?

**Comment by prateek1998** [comment]
Hi @cnglen 
By default they are using font family value as **"default": "\"trebuchet ms\", verdana, arial, sans-serif;"**, If you want to switch this one then I have attached some screenshot, please have a look
![image](https://github.com/mermaid-js/mermaid/assets/37973089/82cd1a2f-85bf-4e78-b2a5-85ad5a5fc582)

![image](https://github.com/mermaid-js/mermaid/assets/37973089/c26f77c5-2db3-4979-aecd-8803e3d4d34b)
{
  "theme": "default",
  "fontFamily":"\"Open Sans\", sans-serif"
}

**Comment by stefnotch** [comment]
This can be closed, I believe

**Comment by prateek1998** [comment]
Yes @stefnotch, we can close this issue.

**Comment by FutzMonitor** [comment]
@sidharthv96 May you please close this issue?
