### ISSUE TITLE
Svg zoom in, zoom out in all four directions, is there a function switch?

### ISSUE THREAD

**Issue by Kilig947** [mermaid-js/mermaid#5226]
### Proposal

![image](https://github.com/mermaid-js/mermaid/assets/46100050/adc66f44-c2dd-4697-819f-5277de65f0e8)

Did GitHub implement these controls back and forth and zoom in themselves?

Does mermain support it?

**Comment by sidharthv96** [comment]
Github added it themselves. 
You can find another implementation found in our Live editor [here](https://github.com/mermaid-js/mermaid-live-editor/blob/develop/src/lib/components/View.svelte).

**Comment by rr210** [comment]
https://github.com/rr210/markdown-it-diagram
