### ISSUE TITLE
Dev setup broken

### ISSUE THREAD

**Issue by ad1992** [mermaid-js/mermaid#5234]
### Description

Looks like the dev setup was recently broken probably post https://github.com/mermaid-js/mermaid/commit/41a9ac953a3c2aa4378622d0ff556897c4c7fb6b

I am using **Mac** and tried with  below **node** versions.

I am getting the below errors with different versions of `node.js`

1. Using node **18.19.x -** 

```
Error [ERR_INTERNAL_ASSERTION]: Code: ERR_MODULE_NOT_FOUND; The provided arguments length (2) does not match the required ones (3).
This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues
```

2. Using node **20.x**
```
Error: Cannot find package '/mermaid/node_modules/.pnpm/vitest@0.34.0_@vitest+ui@0.34.0_jsdom@22.0.0/node_modules/vitest/node_modules/vite/package.json' imported from /mermaid/node_modules/.pnpm/vitest@0.34.0_@vitest+ui@0.34.0_jsdom@22.0.0/node_modules/vitest/dist/config.js
Did you mean to import vite@4.5.0_@types+node@18.17.5/node_modules/vite/index.cjs?
```

### Steps to reproduce

Mentioned above

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
@ad1992 Which command is throwing this error? I'm on node 18.19.0, no issues. 
But I had seen similar issue previously (few months back) when using tsx, which is why we didn't switch to it then.

I've been running develop and next branches multiple times without any issues.

**Comment by ad1992** [comment]
Sorry had been busy for last couple of weeks so couldn't reply.

@sidharthv96 the start server command throws the error 👇

```
tsx .vite/server.ts
```

**Comment by sidharthv96** [comment]
@ad1992 What's the error?

You have to run 

```bash
pnpm install
pnpm -w dev
```

**Comment by ad1992** [comment]
> @ad1992 What's the error?

The same error I have posted in the issue description, that is happening due `tsx .vite/server.ts` in `dev` script.

> 
> You have to run
> 
> ```shell
> pnpm install
> pnpm -w dev
> ```

Yes thats what I am doing as mentioned above,  `tsx .vite/server.ts` in `dev` script. throws error

**Comment by sidharthv96** [comment]
Try deleting your `node_modules` folder. This doesn't seem like an issue with mermaid, as our CI is working fine and other contributors aren't facing the issue.

**Comment by ad1992** [comment]
> Try deleting your `node_modules` folder. This doesn't seem like an issue with mermaid, as our CI is working fine and other contributors aren't facing the issue.

Yep, I already did that multiple times. Probably this is platform-specific and not related to mermaid. I will also try clearing all possible cache and do a clean install

**Comment by ad1992** [comment]
Alright, so something was wrong with my environment. Clearing node modules, pnpm cache resolved this so I am closing.

**Comment by ad1992** [comment]
Sadly its weird, whenever I pause and comeback to the project after few days, my dev setup breaks 😢
