### ISSUE TITLE
bottom-to-top oriented gitgraphs to mimic git logs

### ISSUE THREAD

**Issue by arkadianriver** [mermaid-js/mermaid#5239]
### Proposal

First, I love how beautiful Mermaid's git graphs are compared to others!

This proposal is to add `BT` orientation, because that's how we commonly see git graphs in the wild when viewing git log histories (with commits listed in reverse chronological order).

### Use Cases

This is particularly useful when working with folks and documenting situations that they might see in their git histories. It would be helpful to keep the orientation the same.

### Screenshots

Two such examples of this orientation are the git histories provided by the VS Code extensions Git Graph and GitLens:

- GitGraph: 
![20240125_111918-Git Graph - hqtodo - Visual Studio Code](https://github.com/mermaid-js/mermaid/assets/6054194/941e544d-be47-4167-9dc3-fab27d2efc96)

- GitLens:
![20240125_112446-hqtodo - Visual Studio Code](https://github.com/mermaid-js/mermaid/assets/6054194/4bcf8377-e46d-4aeb-a332-390565234fa5)

### Syntax

`BT` to go along with the existing `LR` and `TB`

### Implementation

This is a proposal which I'd love to see built into mermaid by the wonderful community.

**Comment by JingyuMarcelLee** [comment]
For now, I simply flipped the ```TB``` orientation. The syntax is exactly the same with the ```BT``` option except you added ```TB``` after ```gitgraph```.  Below are the same gitgraph, but with different orientations.

- ```TB```

![image](https://github.com/mermaid-js/mermaid/assets/46755208/503d7079-d60f-4b9a-86d2-a7b9878d3c60)

- ```BT```

![image](https://github.com/mermaid-js/mermaid/assets/46755208/8a830a44-c1fd-43f7-ab14-44e9c0dcb341)

Please let me know if there should be any additional changes.

**Comment by arkadianriver** [comment]
Nice, thanks for working on this Jingyu. 😎
