### ISSUE TITLE
Issue with Mermaid Diagrams Not Rendering in GitHub iOS App

### ISSUE THREAD

**Issue by Usokkie** [mermaid-js/mermaid#5246]
Hello Mermaid Team,

I am encountering an issue with Mermaid diagrams not rendering in the GitHub app for iOS. Instead of displaying the diagrams, the app shows only the raw Mermaid code. This issue can be reproduced by accessing the Mermaid repository through the GitHub iOS app.

Steps to Reproduce:
1. Open the GitHub app on an iOS device.
2. Navigate to the Mermaid repository.
3. Attempt to view a Markdown document with embedded Mermaid diagrams.

**Comment by sidharthv96** [comment]
This is also present in Android app, and is due to Github's app not having support. Not an issue with Mermaid. Please raise an issue with the Github team.
