### ISSUE TITLE
min output file is not minified

### ISSUE THREAD

**Issue by Mister-Hope** [mermaid-js/mermaid#5253]
### Description

The output chunk mermaid.esm.min.mjs is not minified, which is not friendly for CDN usage.

**Comment by Mister-Hope** [comment]
Sorry but I just remember I opened a issue eariler at https://github.com/mermaid-js/mermaid/issues/4093. However the related PR https://github.com/mermaid-js/mermaid/pull/4109 is closed.

**Comment by sidharthv96** [comment]
<img width="970" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/c5df44d4-d9c5-4975-b01c-b528926fc592">

It's minified in `next`. https://github.com/mermaid-js/mermaid/pull/5069
