### ISSUE TITLE
GANTT Chart failing to render once the second section is added

### ISSUE THREAD

**Issue by petruut** [mermaid-js/mermaid#5260]
### Description

When attempting the following configuration, the chart glitches once the second section is added.

gantt
    dateFormat MM-YY
    axisFormat %b %Y
    tickInterval 1month

section Project Gov

    Kick off: 06-23, 1m
    Governance: 18m
    Closure: 2m

section Deployment

    Activity 5: 06-23, 1m
    Activity 6: 08-23, 3m

### Steps to reproduce

1. Render the code as described:

When attempting the following configuration, the chart glitches once the second section is added.

gantt
    dateFormat MM-YY
    axisFormat %b %Y
    tickInterval 1month

section Project Gov

    Kick off: 06-23, 1m
    Governance: 18m
    Closure: 2m

section Deployment

    Activity 5: 06-23, 1m
    Activity 6: 08-23, 3m

2. The chart glitches (try to render just the first section to see)

### Screenshots

With the second section, it glitches:
![image](https://github.com/mermaid-js/mermaid/assets/15355480/3f383e1b-4c69-421f-8e4e-ca24f7b41b90)
Without the second section, it renders:
![image](https://github.com/mermaid-js/mermaid/assets/15355480/78b391ed-b0dd-4948-9c50-9b4cac301239)

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by petruut** [comment]
new update: the bug only seems to happen when i put the second section PLUS the durations of all activities in m (months). If i switch everything to d (days), the bug disappears.

i really need this to work with months (m), so hopefully will be able to fix this.

**Comment by NourS-d** [comment]
![image](https://github.com/mermaid-js/mermaid/assets/40243542/100b2019-cc4e-4162-acae-a13f6acb785d)
`gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Project Gov
    Kick off: 06-23, 1M
    Governance: 18M
    Closure: 2M
    section Deployment
    Activity 5: 06-23, 1M
    Activity 6: 08-23, 3M
`

Is this want you need? 
with months is should probably be "M". the small "m" is reserved for minutes.

**Comment by petruut** [comment]
I love you @NourS-d - I didn't immediately pick this up from the documentation, but it now makes sense!!
