### ISSUE TITLE
Unable to render a graph if the node contains the word `graph` in it.

### ISSUE THREAD

**Issue by bnzone** [mermaid-js/mermaid#5276]
### Description

I came across the situation where it won't be able to render the graph in certain situations if I have the word `graph` in it. 
Is that a reserved keyword? When I capitalize it, the graph renders fine.

I've provided an example below.

## The code snippets below will not throw an error:

✅
```
graph TD;
A-->B;
A-->C;
B-->D;
C-->graph1;
```

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C--> graph1;
```

✅
```
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C--> GRAPH;
```

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->GRAPH;
```

## The code below will throw an error:
❌
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->my-graph;
```

### Code Sample

```text
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->my-graph;
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by c032** [comment]
This sounds like the problem described in the PR <https://github.com/mermaid-js/mermaid/pull/4657>, released in [v10.3.1](https://github.com/mermaid-js/mermaid/releases/tag/v10.3.1).

**Comment by FutzMonitor** [comment]
I can confirm with the current live editor v.10.8.0 that this bug isn't present. So, it seems this issue can be closed unless it's occurring on another platform. 

![image](https://github.com/mermaid-js/mermaid/assets/31524934/a70a3521-96c0-454f-bf72-a7afc076726d)

**Comment by bnzone** [comment]
@FutzMonitor Thank you for taking the time to test it.
So, I guess, it seems that Github is using the older version in the editor which still contains this bug.

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->my-graph;
```
