### ISSUE TITLE
Unable to render rich display - Diagram error not found.

### ISSUE THREAD

**Issue by fagner-koho** [mermaid-js/mermaid#5310]
### Description

In Github markdown if I use this:

```mermaid
flowchart LR
    Test[Phase 1: To call method]
    Test2[Phase 2: Try logic]
    
    Test --> Test2
```

I get this error:
![image](https://github.com/mermaid-js/mermaid/assets/76964728/b934f80e-3f6e-4003-9d43-749d64ab0739)

The issue seems to be around the substring `: To call` but I'm not sure exactly what it is.

This works fine at mermaid.live.

### Steps to reproduce

1. Create a markdown file in Github.
2. Paste this:
```mermaid
flowchart LR
    Test[Phase 1: To call method]
    Test2[Phase 2: Try logic]
    
    Test --> Test2
```
3. Commit (or see a preview of the file in Github).
4. See the bug to render.

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/76964728/b934f80e-3f6e-4003-9d43-749d64ab0739)

### Code Sample

```text
flowchart LR
    Test[Phase 1: To call method]
    Test2[Phase 2: Try logic]
    
    Test --> Test2
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by nirname** [comment]
@fagner-koho At the moment it works just fine, closing. Do not hesitate to open a new issue if it is still a problem
