### ISSUE TITLE
Interactive documentation

### ISSUE THREAD

**Issue by nalgeon** [mermaid-js/mermaid#5311]
Hi folks! Thank you for this great project!

I think the Mermaid docs would be even better if the examples were interactive, so people could change the code and see it reflected in the diagram. Here is an example based on the Mermaid Intro: https://codapi.org/try/mermaid

If you're interested, I'll be happy to send you a PR to backport this into Mermaid Intro (and maybe Syntax docs as well).

**Comment by sidharthv96** [comment]
Yes, that would be wonderful. 
If we could avoid having to click on run, and auto render as people type (like mermaid.live), it might be smoother as well.

**Comment by nalgeon** [comment]
The maintainer [changed their mind](https://github.com/mermaid-js/mermaid/pull/5330#issuecomment-1987704420):

> I feel that codapi is adding a lot of complexity for what can be achieved by a custom vue component which calls mermaid.render on a button click.

Closing.

**Comment by sidharthv96** [comment]
I changed my mind based on the information presented. 
The feature was implemented in https://github.com/mermaid-js/mermaid/pull/5376

[Full explanation](https://github.com/mermaid-js/mermaid/pull/5330#issuecomment-1987994535)
