### ISSUE TITLE
when "self" in a node identifier, using GH mermaid: "Unable to render rich display: Diagram error not found"

### ISSUE THREAD

**Issue by ringerc** [mermaid-js/mermaid#5317]
### Description

Mermaid js as adopted by Github's Markdown renderer does not like the string `self` appearing in a label for a node.

See the two diagrams below.

### Steps to reproduce

```mermaid
flowchart TD;

  my_self["me"]
  other["thing"]
  my_self --> other
```

vs

```mermaid
flowchart TD;

  my_thing["me"]
  other["thing"]
  my_thing --> other
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

- Emit a useful error with the actual error from the renderer
- Don't special case string names

**Comment by nirname** [comment]
@ringerc it seems that at the moment both diagrams work just fine at mermaid.live and gh as well. Please, check it and confirm or add some more examples.

**Comment by ringerc** [comment]
They're rendering here now too. I presume the issue was fixed since when I reported it in Feb. Thanks for checking.
