### ISSUE TITLE
A diagram that works in mermaidchart.com fails in Notion

### ISSUE THREAD

**Issue by chris-braidwell** [mermaid-js/mermaid#5341]
### Description

When I paste the same Mermaid source into a `/mermaid` block in Notion, I get this error: `Syntax error in Mermaid diagram: TypeError: Cannot read properties of undefined (reading 'id')`.

### Steps to reproduce

I can share the source in a private message.

### Setup

Notion as of 29-Feb-2024

### Suggested Solutions

Could the Notion plugin for Mermaid be out of date? Should we expect differences in the two environments?

**Comment by Yokozuna59** [comment]
Most likely because they are using an older version.

The live editor uses `v10.8.0`, but notion uses `v10.6.1`:

![8CA99124-47F8-4C21-A4C3-EE4615A8A33F](https://github.com/mermaid-js/mermaid/assets/87622592/0d4a1a98-de95-4421-8699-22268ad884e4)

**Comment by chris-braidwell** [comment]
Thanks. Is there an official contact @ Notion to work this with? If not I'll just open a general ticket with them.

I didn't know about `info` -- that's handy.

**Comment by Yokozuna59** [comment]
I'm not really sure, but people open issues in this repo: https://github.com/makenotion/notion-sdk-js.
