### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by nitsanavni** [mermaid-js/mermaid#5342]
### Proposal

TODO lists and plans are very useful things to have in repositories.
If we could wrap them in
```
```mermaid
Type: Kanband
TODO
...
DOING
...
DONE
...
```\
```

It could make it a nicer UX.

### Use Cases

Per repository lightweight planning.

### Implementation

None

**Comment by sidharthv96** [comment]
Love the idea!

A gammar like this would scale better, and is similar to what we already have with other diagarms in mermaid. 

```
kanban-beta
Column1
  task1["Optional unicode string"]
  task2["IDs cannot have spaces"]
Column2
  task3
  task4["`Line1
    **Bold**
    Line 3`"]
Column3
...

style task1 color:red
style task1,task2 border:1px
```

**Comment by knsv** [comment]
I will base the grammar for this on Mindmaps
