### ISSUE TITLE
Bump Typescript-Eslint version To V7

### ISSUE THREAD

**Issue by NicolasCwy** [mermaid-js/mermaid#5404]
### Description

The current minor version of typescript 5.4.2 is not supported by typescript eslint, giving a warning

### Steps to reproduce

1. pnpm install
2. pnpm test

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/25302138/63681719-78f2-4a3f-aaa5-2f22d2fbaf70)

**Comment by sidharthv96** [comment]
Thanks, renovate bot was not configured properly, so it was waiting for approval to bump up major versions.  Have fixed it.  will update pending packages.
