### ISSUE TITLE
mermaid.ink server is down

### ISSUE THREAD

**Issue by jonathan-moreau-peaksys** [mermaid-js/mermaid#5473]
### Description

When I want to display the PNG image of my chart, the mermaid.ink url is in error 521 (server is down)

### Steps to reproduce

1. Go to [https://mermaid.ink/](https://mermaid.ink/)
2. ![image](https://github.com/mermaid-js/mermaid/assets/141261431/55669003-3bcb-4bb0-9743-80454eea0f35)

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/141261431/8be27270-fe1b-4dfe-bbe9-4e2645bb1b9d)

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
Seems to be working now. 
Also, the repo for mermaid.ink is https://github.com/jihchi/mermaid.ink/issues/.
