### ISSUE TITLE
Add support for nested namespaces

### ISSUE THREAD

**Issue by skillmaker-dev** [mermaid-js/mermaid#5487]
### Proposal

I think it would be a great feature to have, nested namespaces make it easier to represent packages or namespaces in which classes reside, and it should be possible either by creating a namespace inside another namespace or by separating namespaces with a dot like this `namespace example1.example2.example3 {}`

### Example

for example in PlantUML, nested packages or namespaces can be represented like this `package foo1.foo2.foo3 {
  class Object
}`

### Screenshots

The previous example will be represented in this way in plantUML: 
![image](https://github.com/mermaid-js/mermaid/assets/64654197/a2dd0072-ac77-41e2-aa27-1b70db7ad17c)

**Comment by Khar-Ma2** [comment]
Hi, I just encountered the same problem. I also think that this item should be documented.

However, I have found a solution, although this behavior is unpredictable and not obvious to me.

So, I created 2 namespaces at the same level, and then I put the "children" as a class in the "main" one. 
It looks something like this:

```mermaid
classDiagram

namespace presentation{
    class auth
    class main
}
namespace auth{
    class AuthScreen
    class AuthViewModel
}
namespace main{
    class MainScreen
    class MainViewModel
}
```

![nested namespaces](https://github.com/mermaid-js/mermaid/assets/169257792/7e6f0ae4-3aec-4ccf-8428-0a79674c2f72)

**Comment by skillmaker-dev** [comment]
> Hi, I just encountered the same problem. I also think that this item should be documented.
> 
> However, I have found a solution, although this behavior is unpredictable and not obvious to me.
> 
> So, I created 2 namespaces at the same level, and then I put the "children" as a class in the "main" one. It looks something like this:
> 
> ```
> classDiagram
> 
> namespace presentation{
>     class auth
>     class main
> }
> namespace auth{
>     class AuthScreen
>     class AuthViewModel
> }
> namespace main{
>     class MainScreen
>     class MainViewModel
> }
> ```
> 
> ```mermaid
> classDiagram
> 
> namespace presentation{
>     class auth
>     class main
> }
> namespace auth{
>     class AuthScreen
>     class AuthViewModel
> }
> namespace main{
>     class MainScreen
>     class MainViewModel
> }
> ```

That's a nice workaround, the namespace is behaving like a class and therefore it is being surrounded by the box and then you change it to be a namespace, I hope they create this feature, No one replied to this issue so far apart from you :(

**Comment by nirname** [comment]
Hello! Thanks for the suggestion. Is this workaround enough so we can close the issue, or you are still interested in something like
```
classDiagram

namespace presentation{
    namespace auth {
        class AuthScreen
        class AuthViewModel
    }
    namespace main{
        class MainScreen
        class MainViewModel
    }
}
```

**Comment by skillmaker-dev** [comment]
I think 
```
classDiagram

namespace presentation{
    namespace auth {
        class AuthScreen
        class AuthViewModel
    }
    namespace main{
        class MainScreen
        class MainViewModel
    }
}
```
or this are better than the workaround because it is somehow confusing when working with a large codebase.

```
namespace example1.example2.example3 
{
	class class1
}
```

**Comment by nirname** [comment]
@skillmaker-dev would you like to make a contribution?

**Comment by skillmaker-dev** [comment]
@nirname I will try my best after taking a look at the codebase.

**Comment by ReneLombard** [comment]
@nirname and @skillmaker-dev I've made an attempt to resolve this issue. Please see the following pull request:
https://github.com/mermaid-js/mermaid/pull/5849

**Comment by ReneLombard** [comment]
@nirname can I assign the pull request to you?

**Comment by nc-jeni** [comment]
Unfortunately, it does not work... 

```
classDiagram

namespace presentation{
    namespace auth {
        class AuthScreen
        class AuthViewModel
    }
    namespace main{
        class MainScreen
        class MainViewModel
    }
}
```

I returns the error

```
Error: On line 3
MermaidDetailedError: Parse error on line 4:
...e presentation{    namespace auth {   
----------------------^
Expecting 'CLASS', 'NOTE_FOR', 'NOTE', got 'ALPHA'
```

I am using the online editor https://mermaid.ai/

**Comment by ReneLombard** [comment]
@nc-jeni If you look at the pull requests mentioned it doesn't add nested namespaces but rather the . in the namespace:

so instead of doing this:

```code
classDiagram

namespace presentation{
    namespace auth {
        class AuthScreen
        class AuthViewModel
    }
    namespace main{
        class MainScreen
        class MainViewModel
    }
}
```

you could potentially do this:

```code
classDiagram

namespace presentation.auth {
    
        class AuthScreen
        class AuthViewModel
    }
    namespace presentation.main{
        class MainScreen
        class MainViewModel
    }

```

which results in 
```mermaid
classDiagram

namespace presentation.auth {
    
        class AuthScreen
        class AuthViewModel
    }
namespace presentation.main {

        class MainScreen
        class MainViewModel
    
}
```

For us the latter is working, but feel free to jump in and add some nested support :)

**Comment by nc-jeni** [comment]
> [@nc-jeni](https://github.com/nc-jeni) If you look at the pull requests mentioned it doesn't add nested namespaces 
> but rather the . in the namespace:
> 


 I actually did that as a work-around even that it is not semantically correct as sub packages should be listed inside the outer-package.

**Comment by ReneLombard** [comment]
@nc-jeni 

I think there is a use-case for both scenarios. The latter was the easiest for me that covered our requirements.

But please feel free to add a contribution, I think a lot of people will benefit from this change 🥇
