### ISSUE TITLE
The diagram renders only once.

### ISSUE THREAD

**Issue by PiotrFerenc** [mermaid-js/mermaid#5489]
### Description

Error during rendering of the subsequent diagram.

### Steps to reproduce

https://gist.github.com/PiotrFerenc/fdab1157627e628b1699da456a4d773d

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/30370747/159a6301-c637-409b-ac29-f05ffde11ad2)
![image](https://github.com/mermaid-js/mermaid/assets/30370747/97f45a8f-5da2-4b8c-9a62-df1fd0af57a1)

### Setup

- Mermaid version:
- Browser and Version: Chrome/ Ubuntu

**Comment by sidharthv96** [comment]
Please go through the documentation on how to use the API. 

https://mermaid.js.org/config/usage.html#api-usage
