### ISSUE TITLE
Mermaid Chart - Code Editor Constantly Reduces Upwards

### ISSUE THREAD

**Issue by chrisdunlopnz** [mermaid-js/mermaid#5505]
### Description

The code editor just reduces in size. This happens no matter what device I am on, nor what chart and makes my new mermaid chart subscription hard to use.

Attached video 

### Steps to reproduce

Open mermaidchart
Open a new diagram
The code editor will eventually be minimised by the upwards scrolling.

### Screenshots

https://github.com/mermaid-js/mermaid/assets/5751058/58cac60d-6f72-4ec4-9e56-0c54a745e66c

### Setup

Mermaid Chart
Google Chrome

**Comment by sidharthv96** [comment]
Thank you so much for reporting. I'm surprised to see this happening now, as was fixed about a year back.
I guess there are edge cases we missed. I'm unable to reproduce the issue locally, I'll loop @dav1tj to see if he can break it. 


Future reference: https://github.com/Mermaid-Chart/issue-tracker is the right place for reporting Mermaid Chart issues

**Comment by sidharthv96** [comment]
I'm unable to reproduce in `Chrome Version 124.0.6367.119 (Official Build) (arm64)` on `macOS Ventura 13.6.6 (22G630)` both in production and development.

https://github.com/mermaid-js/mermaid/assets/10703445/e211d042-7114-4f2e-93c7-2fc5e880f453

@chrisdunlopnz can you please help isolate the issue?

Here are some steps 

1. Try in incognito
2. Try in a different browser (Firefox/Safari/Brave).
3. Try after starting chrome without extensions. [Guide](https://www.majorgeeks.com/content/page/google_chrome_without_extensions.html)

**Comment by sidharthv96** [comment]
I have added some fixes which _might_ in theory help with the issue. 
We're also adding some extra debug statements so we can get additional information from your machine (will add info on how to send the info to us after release).

Both these should be included in today's release. Will update here once it's live.

**Comment by chrisdunlopnz** [comment]
Hi apologies for the late reply, but it has been fixed on all versions I have tested, thanks so much for the help
