### ISSUE TITLE
'Graph' keyword in mindmap diagram breaks if elk renderer set for flowchart

### ISSUE THREAD

**Issue by varon** [mermaid-js/mermaid#5507]
### Description

This error was really incomprehensible to diagnose.

Setting the elk renderer in the mermaid config for `flowchart` breaks mindmaps escaping somehow.

This works correctly:

```text
%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
 mindmap
   ("single item mindmap")
    ["Descendant node"]
```

This is broken (note this is ONLY set for flowchart):

```text
%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
 mindmap
   ("single item mindmap")
    ["Descendant node in graph"]
```

but this works:

```text
 mindmap
   ("single item mindmap")
    ["Descendant node in graph"]
```

How? why?

## Examples on GitHub of broken diagrams

This works - where we don't use the keyword `graph` inside the string label:

```mermaid
%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
 mindmap
   ("single item mindmap")
    ["Descendant node"]
```

This is broken:

```mermaid
%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
 mindmap
   ("single item mindmap")
    ["Descendant node in graph"]
```

### Setup

- Mermaid version: 10.9.0

**Comment by varon** [comment]
This is a glaring bug impacting us. Please address or explain what we need to do move forward here.

**Comment by nirname** [comment]
Thanks for reaching out & sorry for the long response, things are piling up.

Nothing too complex. Because of the wrong detector it thinks that you are trying to invoke flowchart-elk diagram.

But I understand how it looks from the outside.
Try removing the word "graph" from the node label and you'll be even more confused.

```mermaid
%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
 mindmap
   ("single item mindmap")
    ["Descendant node in my image"]
```

That's a bug for sure.
