### ISSUE TITLE
Flowchart edges not found: Diagram db `getEdges` returining edges which aren't drawn on DOM

### ISSUE THREAD

**Issue by ad1992** [mermaid-js/mermaid#5516]
### Description

Diagram db `getEdges` sometimes returns edges which aren't drawn or DOM for flowchart

### Steps to reproduce

Let's consider the 👇🏻 mermaid code

```
flowchart TB   
    subgraph conference
        frontend
        backend
        security
    end
    frontend --> |Dive into frontend frameworks| conference
    backend --> |Learn all about backend| conference
    security --> |securing web apps| conference
```

For the above this 👇🏻 is the mermaid output

<img width="193" alt="Screenshot 2024-05-13 at 12 49 47 PM" src="https://github.com/mermaid-js/mermaid/assets/11256141/ad49e25f-41c1-4ed9-ba74-c9cd319db9a0">

As its clear that none of the edges are drawn even though the diagram db `getEdges` returns 👇🏻 

```
[
    {
        "start": "frontend",
        "end": "conference",
        "type": "arrow_point",
        "text": "Dive into frontend frameworks",
        "labelType": "text",
        "stroke": "normal",
        "length": 1
    },
    {
        "start": "backend",
        "end": "conference",
        "type": "arrow_point",
        "text": "Learn all about backend",
        "labelType": "text",
        "stroke": "normal",
        "length": 1
    },
    {
        "start": "security",
        "end": "conference",
        "type": "arrow_point",
        "text": "securing web apps",
        "labelType": "text",
        "stroke": "normal",
        "length": 1
    }
]
```

So this should be fixed in the code so that the `getEdges` returns correct set of edges

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by nirname** [comment]
@ad1992 I am closing this issue because it seems that you had already fixed it, but merging PR did not closed the issue, because you had had to use magic comment like "resolves #issue_number"
