### ISSUE TITLE
Feature request: Gantt chart task with multiple dependencies

### ISSUE THREAD

**Issue by wigy-opensource-developer** [mermaid-js/mermaid#552]
There are cases in a project when multiple tasks has to be ready (apple *and* banana) in order to start with a given task (cherry).

```mermaid
gantt
  apple :a, 2017-07-20, 1w
  banana :crit, b, 2017-07-23, 1d
  cherry :active, c, after b, after a, 1d
```

It would be intuitive if I could just express these dependencies by adding multiple `after` properties to the task.

Is there a way I can workaround this missing feature at the moment? If either start time or duration changes on apple and banana, I need to remember to update cherry to depend on the one with the latest end time.

**Comment by shuodong** [comment]
I found mermaid today and trying to use it for my current project. Then found it can't support multiple predecessors, which is very useful for complicated projects.

**Comment by DougHughes** [comment]
totally, drawing a line from the end of task to the beginning of a dependent task when the start of the dependent task doesn't line up (because it has other dependencies) would also be useful. This is particularly important when the dependent task is in a different section (different parallel project). Having a line from the end of the task in Proj1 to the beginning of the task in Proj2 when there's a gap, would be illustrative. (dotted, whatever)

**Comment by CraigDamlo** [comment]
This may be a second feature request, but to build on the apple, banana, cherry example, sometimes I need a delay, like start apple 1 week after banana; both beginning and ending.

**Comment by fbartho** [comment]
I too also want this feature! 

Additionally, sometimes it might be convenient to have a `before taskId` statement.

**Comment by fbartho** [comment]
I think this is the interesting code for this feature: https://github.com/knsv/mermaid/blob/a4992963b3873ec7a566ba91b92596d2a360e3b9/src/diagrams/gantt/ganttDb.js#L66-L76

Are there any more things to look at?

**Comment by peetervois** [comment]
I also need this feature. And I also found the code by **fbartho**. It seems to me that a loop would be needed to look through every afterStatement[x] and return the task.endTime that is the latest. Would it work?

**Comment by wigy-opensource-developer** [comment]
ping for you, @github-actions

**Comment by peetervois** [comment]
Thank you for keeping it open. I am watching this issue. I am ready to set up premium for those who decides to solve it and make new release for https://www.dokuwiki.org/plugin:flowcharts .

**Comment by peetervois** [comment]
The change is going to be published soon. Stay tuned.

**Comment by Dunning-Kruger** [comment]
@itprdev If you'd like, leave a comment here so I can assign the issue to you so nobody else works on it and when we close it you'll permanently show up as the user that fixed it!
