### ISSUE TITLE
Add Title To the Graph

### ISSUE THREAD

**Issue by vikram-rawat** [mermaid-js/mermaid#556]
There should be a way to add title to the graph right from Flowchart diagram. I am really sorry if you have one that I didn't find anywhere.

**Comment by alexkli** [comment]
Here is a little workaround for adding a fake title to the top down flowchart (TD):

[View in Mermaid Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKCnRpdGxlWzx1Pk15IFRpdGxlPC91Pl0KdGl0bGUtLT5GaXJzdFN0ZXAKc3R5bGUgdGl0bGUgZmlsbDojRkZGLHN0cm9rZTojRkZGCmxpbmtTdHlsZSAwIHN0cm9rZTojRkZGLHN0cm9rZS13aWR0aDowOwoKRmlyc3RTdGVwLS0-Li4uCg)

```
graph TD

title[<u>My Title</u>]
title-->FirstStep
style title fill:#FFF,stroke:#FFF
linkStyle 0 stroke:#FFF,stroke-width:0;

FirstStep-->...
```

Add this to the top immediately after the `graph TD` definition.

This defines a box, styles its text with underscore (`<u>`, YMMV) and makes the box fill & stroke blank (`style title`) and links it to the real first step/box (`FirstStep`) so it appears on top, while making the link hidden using `linkStyle 0`.

**Comment by tylerlong** [comment]
@alexkli that is a brilliant idea! It could be used as a nice workaround before we add official support

**Comment by nqb** [comment]
Any update on that feature ?

**Comment by simonwatz** [comment]
Yes this isn't working for me either

**Comment by gakonst** [comment]
@alexkli does not work for Sequence Diagrams unfortunately.

**Comment by elin-y** [comment]
good idea but it also doesn't apply to the left-to-right graphs unfortunately.

**Comment by pothitos** [comment]
Until this issue is resolved, this is another workaround that applies to the left-to-right graphs too.

```
graph LR
  subgraph This is my caption
    A --> B
  end
```

which uses a `subgraph` to display something like

[![Graph with caption](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgc3ViZ3JhcGggVGhpcyBpcyBteSBjYXB0aW9uXG4gICAgQSAtLT4gQlxuICBlbmRcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgc3ViZ3JhcGggVGhpcyBpcyBteSBjYXB0aW9uXG4gICAgQSAtLT4gQlxuICBlbmRcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

**Comment by sommmen** [comment]
Any updates on this?

**Comment by GDFaber** [comment]
Not yet, but I've got it on my list.

**Comment by sommmen** [comment]
> Not yet, but I've got it on my list.

I see, Thanks for the.. update? i gues 'working on it' is still a status update in my book ;)

**Comment by GDFaber** [comment]
I'm closing this issue in favour of #1433, please refer to the new issue for future updates. This is still one of the tasks I want to work on once I get the time, so it does not change priorities to close this one :)
