### ISSUE TITLE
Please add Chinese support

### ISSUE THREAD

**Issue by zronal** [mermaid-js/mermaid#5597]
### Description

Currently, many subtitles and elements cannot be displayed if Chinese characters are entered. For example, checkout of Please add Chinese support.

### Steps to reproduce

    gitGraph
       commit id: "AAA"
       commit id: "BBB"
       branch 中文

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
You can use double quotes to allow all characters.

```mermaid
gitGraph
   commit id: "AAA"
   commit id: "BBB"
   branch "中文"
```

```
gitGraph
   commit id: "AAA"
   commit id: "BBB"
   branch "中文"
```
