### ISSUE TITLE
mermaid doesnt work with latest pip version

### ISSUE THREAD

**Issue by skultetymichal** [mermaid-js/mermaid#5616]
### Description

In my jenkins pipeline, I am updating pip to the latest version and installing mermaid plugin. I am geting and error that mermaid-0.3.2 has invalid metadata and that I should use pip<24.1. 

### Steps to reproduce

1. in jenkins pipeline: 
pip install --upgrade pip mermaid

2. resuting error:
20:13:55  Requested mermaid from https://files.pythonhosted.org/packages/a7/c4/d259de417b44785e37107399e21c4868244c9baae127346a70119ca5a3a9/-py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
20:13:55      torch (>=1.7torchvision)
20:13:55            ~~~~~~^
20:13:55  Please use pip<24.1 if you need to use this version.
20:13:55  ERROR: Could not find a version that satisfies the requirement mermaid (from versions: 0.3.2)
20:13:55  ERROR: No matching distribution found for mermaid

### Setup

- Mermaid version: 0.3.2
- pip-24.1.1

**Comment by sidharthv96** [comment]
https://pypi.org/project/mermaid/ is not related to us. 

Related: https://github.com/uncbiag/mermaid/issues/154
