### ISSUE TITLE
classDiagram 'direction RL' state is maintained when removed

### ISSUE THREAD

**Issue by Stemt** [mermaid-js/mermaid#5624]
### Description

By default the direction of a classDiagram is Top-Down until one uses the 'direction RL' directive to change this to Right-Left.
I've however found that after removing this directive the classDiagram orientation stays Right-Left even if I use 'direction TD' (this is not officially mentioned in the documentation but would be intuitive and is a feature in other diagrams) .
This goes for both the [mermaid live editor](https://mermaid.live/) and my sphinx documentation.
In the live editor the diagram fixes itself after a page reload but I haven't been able find a fix for my sphinx documentation.

### Steps to reproduce

1. Create A classDiagram e.g.
```
classDiagram
    test1 -- test2
```
This diagram should be in the Top-Down orientation.

2. Add 'direction RL' to the diagram
```
classDiagram
    direction RL
    test1 -- test2
```
The diagram should now be in the Right-Left orientation.

3. Remove 'direction RL' from the diagram
```
classDiagram
    test1 -- test2
```
The diagram should now once again be in Top-Down orientation, but is not.

4. Add 'direction TD' for good measure.
```
classDiagram
    direction TD
    test1 -- test2
```
It's now still in the Right-Left orientation.

### Screenshots

![Screenshot from 2024-07-05 11-57-33](https://github.com/mermaid-js/mermaid/assets/32430762/f8818fca-3136-4a89-b421-384b410efd86)
![Screenshot from 2024-07-05 11-57-47](https://github.com/mermaid-js/mermaid/assets/32430762/ff1532d7-6eda-47f9-84bf-ebe147766c13)
![Screenshot from 2024-07-05 11-58-00](https://github.com/mermaid-js/mermaid/assets/32430762/535fc847-85f7-450a-95e1-df5d47948e61)
![Screenshot from 2024-07-05 11-58-09](https://github.com/mermaid-js/mermaid/assets/32430762/022707bd-20b2-4c4b-bd4f-e67acfd2f8ba)

### Setup

- Mermaid version: v10.9.1 (live editor) & v10.9.0 (sphinx docs)
- Browser and Version: [Chromium: 126.0.6478.126]

### Suggested Solutions

- implement 'direction TD' to force direction instead of relying on it being the default direction.

**Comment by sidharthv96** [comment]
Thanks for raising the issue @Stemt!
The direction was not being cleared properly, so it's been fixed in #5625, and should be available in the next release.
