### ISSUE TITLE
Where is the prompt for the GPT bot ?

### ISSUE THREAD

**Issue by inverted-capital** [mermaid-js/mermaid#5626]
### Description

We are looking to generate mermaid diagrams using OpenAI's models, and were hoping to see inside of the GPT prompt that this project used to produce the mermaid gpt: https://chatgpt.com/g/g-1IRFKwq4G-mermaid-chart-diagrams-and-charts

If you want to keep that private we have no problem with that, if you have some commercial terms under which we could see the prompt that would be great too.

### Steps to reproduce

Sorry this is not a bug but I didn't know where to put this message.

Thank you for making the mermaid tools they are invaluable to us and we love plain text everything.

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
Please reach out to hello@mermaidchart.com, as [MermaidChart](https://www.mermaidchart.com/) is handling all the AI related stuff.
