### ISSUE TITLE
classDiagram Generic type adds HTML if name of HTML element Video, Section

### ISSUE THREAD

**Issue by elbakerino** [mermaid-js/mermaid#5634]
### Description

Section and Video as generic type in `classDiagram` adds HTML tags.

Some like `Img` don't cause this error, not further tested which others cause errors.

### Steps to reproduce

Add `Video` or `Section` as generic type.

### Screenshots

![grafik](https://github.com/mermaid-js/mermaid/assets/7737034/77ff625d-b4ca-42ca-859e-787d2ae7a91e)

### Code Sample

```text
classDiagram
    class Zebra{
      +List<Video> videos
    }
    class Tiger{
      +List<Section> section
    }
    class Lion{
      +List<Img> images
    }
```

### Setup

- Mermaid version: latest
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by Austin-Fulbright** [comment]
Currently working on this. I think I found the issue. Once I make sure all the test suites are passing, I will make a PR.

**Comment by Austin-Fulbright** [comment]
Hey I realized that instead of using <> to declare generics you should use the ~~ instead. so for your code example:

classDiagram
    class Zebra{
      +List<Video> videos
    }
    class Tiger{
      +List<Section> section
    }
    class Lion{
      +List<Img> images
    }
    
    The correct code for your desired output would be:
    classDiagram
    class Zebra{
      +List~Video~ videos
    }
    class Tiger{
      +List~Section~ section
    }
    class Lion{
      +List~Img~ images
    }

The problem is with the way that the code handles <> I can change it however I am not sure if the <> were ever meant to declare generics in the code. But I hope this helps for now.

**Comment by elbakerino** [comment]
Thanks, yes tilde works! I've only read the first code at [the docs](https://mermaid.js.org/syntax/classDiagram.html#generic-types):

> **Nested** type declarations such as `List<List<int>>` are supported, ....

But that demonstrated "how it is shown" and not "how it is written", maybe in general something hard to explain to users - and i think i'll run into that often without a mermaid linter ;)
