### ISSUE TITLE
IDE Plugin not working

### ISSUE THREAD

**Issue by technoplato** [mermaid-js/mermaid#5768]
### Description

When I sync my projects with my api key, they load but will not open in WebStorm or Visual Studio Code

https://youtu.be/3qt0S6KYiSc

### Steps to reproduce

Create Mermaid account
Download plugin
Create sample chart
Add key to plugin
Load my charts successfully 
🐛🚨 Click chart and nothing happens

### Screenshots

video is worth like 1,000 screenshots I've heard: https://youtu.be/3qt0S6KYiSc

### Code Sample

```text
asdf
```

### Setup

All just downloaded 8/24/2024

### Suggested Solutions

a

### Additional Context

a

**Comment by sidharthv96** [comment]
Moved to https://github.com/Mermaid-Chart/issue-tracker/issues/87. 
This repo is for the open source mermaid project. The plugins are from MermaidChart.com.
