### ISSUE TITLE
elk renderer dont work in mermaid 11.0.2 version 

### ISSUE THREAD

**Issue by zszen** [mermaid-js/mermaid#5782]
### Description

`%%{init: {'theme': 'neutral' ,'flowchart': {'defaultRenderer': 'elk' }}}%%`

elk renderer dont work in mermaid 11.0.2 version. But ok when back to 10.x

### Steps to reproduce

using elk renderer in 11.0.2

### Setup

- Mermaid version: 11.0.2
- Browser and Version: [Firefox]

**Comment by knsv** [comment]
@zszen Thanks for reporting. 

We have updated the syntax for selecting layout algorithms are select from the code. The new syntax would be like this:
```
---
  config:
    layout: elk
---
```
The old way should still work though, we will add a fix for this in the next mermaid release.

**Comment by zszen** [comment]
> @zszen Thanks for reporting.
> 
> We have updated the syntax for selecting layout algorithms are select from the code. The new syntax would be like this:
> 
> ```
> ---
>   config:
>     layout: elk
> ---
> ```
> 
> The old way should still work though, we will add a fix for this in the next mermaid release.

in v11 version mermaid not contain elk layout, and I can't easy find out the js...

**Comment by nbrugger-tgm** [comment]
ELK layout is still broken in 11.* versions

**Comment by TimJJTing** [comment]
For those who use 11.* versions and cannot use ELK layout, check if you have the engine loaded and registered since the engine is not included by default.

With bundlers
```js
import mermaid from 'mermaid';
import elkLayouts from '@mermaid-js/layout-elk';
// load and register the engine
mermaid.registerLayoutLoaders(elkLayouts);
// ...
// mermaid.initialize(config);
```

or with CDN

```html
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  import elkLayouts from 'https://cdn.jsdelivr.net/npm/@mermaid-js/layout-elk@0/dist/mermaid-layout-elk.esm.min.mjs';
  // load and register the engine
  mermaid.registerLayoutLoaders(elkLayouts);
  // ...
  // mermaid.initialize(config);
</script>
```

See https://www.jsdelivr.com/package/npm/@mermaid-js/layout-elk

**Comment by pbreheny** [comment]
@TimJJTing: Not only is it not well documented, the existing documentation is incorrect 🤦 : https://github.com/mermaid-js/mermaid/issues/6273
