### ISSUE TITLE
v11: some complex HTML content is rendered as an empty node in flowcharts with Firefox

### ISSUE THREAD

**Issue by djibe** [mermaid-js/mermaid#5851]
### Description

Complex labels with HTML are rendered as empty nodes in flowcharts since v11 in Firefox (v130 tested) even though "flowchart.htmlLabels" is true.

I couldn't find any doc for migrating from v10 to v11 to solve this.

### Steps to reproduce

[Diagram link](https://mermaid.live/edit#pako:eNplUsuO0zAU_ZUrI6GMaFXSB0KhqtTRsGAxCEHFhrBwnZvkThM78mNoNRqJLXs-gA2Lfkf-ZL4E25lIlVgkzrGP7znn5j4woQpkGas072rYXecSgMuKJH7bxgX6sz7Zuj-33KIzuN7rjXKXu2raucZy0Z_xO0ynG2gVSbNIcvayse9g4euZnF3Fo3vSvEm-hjdeBS1jTw0-K3qg1QGzF8t09bpcTZ7x9AcVts7S7hgujPZiuUW69MWTBfR_IF0GoUFmd_M58U8A8EkZslTG_e3u2tta7zdbaWlPKiTwwQnhDdwpp816tt-EhE8_f4dlW_hkmAFv1ZEENU0QTis4wnx2FwjvZcmlHQgwX0FbzQ4Xx698n-5JWFISlm-hRqcx9GIIAsFnsPixP1d89Bhb9F_SdNU1znjzT7_-enDZUyOUxuSWC_hgOBcx9MCb52xsx6gYyQMj_p2RElXZhLWoW06Fn4iHcCVntsYWc5b5z4LrQ85y-eh53Fn15SQFy6x2OGFauapmWckb45HrCj8tN8T9WLUjBQuySt8O8yaULKlij_8AJXTSSA)

1. Run the previous diagram with 10.x
2. Run the previous diagram with 11.x

### Screenshots

v10
![Capture d'écran 2024-09-09 220051](https://github.com/user-attachments/assets/d6a01339-56f6-49c1-849e-a732c8675b10)

v11: bottom node with HTML is rendered as empty node
![Capture d'écran 2024-09-09 220037](https://github.com/user-attachments/assets/7ca4aa67-edd5-46e9-95c0-70da20bfc505)

### Code Sample

[Link](https://mermaid.live/edit#pako:eNplUsuO0zAU_ZUrI6GMaFXSB0KhqtTRsGAxCEHFhrBwnZvkThM78mNoNRqJLXs-gA2Lfkf-ZL4E25lIlVgkzrGP7znn5j4woQpkGas072rYXecSgMuKJH7bxgX6sz7Zuj-33KIzuN7rjXKXu2raucZy0Z_xO0ynG2gVSbNIcvayse9g4euZnF3Fo3vSvEm-hjdeBS1jTw0-K3qg1QGzF8t09bpcTZ7x9AcVts7S7hgujPZiuUW69MWTBfR_IF0GoUFmd_M58U8A8EkZslTG_e3u2tta7zdbaWlPKiTwwQnhDdwpp816tt-EhE8_f4dlW_hkmAFv1ZEENU0QTis4wnx2FwjvZcmlHQgwX0FbzQ4Xx698n-5JWFISlm-hRqcx9GIIAsFnsPixP1d89Bhb9F_SdNU1znjzT7_-enDZUyOUxuSWC_hgOBcx9MCb52xsx6gYyQMj_p2RElXZhLWoW06Fn4iHcCVntsYWc5b5z4LrQ85y-eh53Fn15SQFy6x2OGFauapmWckb45HrCj8tN8T9WLUjBQuySt8O8yaULKlij_8AJXTSSA)

### Setup

- Mermaid version: 11.x
- Browser and Version: Firefox 130

### Suggested Solutions

- HTML labels are interpreted the same

**Comment by codekrolik2** [comment]
+1

```
mermaid
flowchart
    BEGIN([BEGIN])
    END([END])
    LOAD_CAMERAS_FROM_CONFIG[[LOAD_CAMERAS_FROM_CONFIG]]
    BEGIN([BEGIN]) --> LOAD_CAMERAS_FROM_CONFIG[[LOAD_CAMERAS_FROM_CONFIG]]
    LOAD_CAMERAS_FROM_CONFIG --> RUN_CHILD_FLOWS[[RUN_CHILD_FLOWS]]
    FINALIZE[[FINALIZE]]
    FINALIZE --> END([END])
    RUN_CHILD_FLOWS[[RUN_CHILD_FLOWS]]
    RUN_CHILD_FLOWS --> FINALIZE[[FINALIZE]]
    RUN_CHILD_FLOWS .-> Factory:CameraProcessRunnerFlow>Factory:CameraProcessRunnerFlow]
    RUN_CHILD_FLOWS .-> Factory:VideoChunkManagerFlow>Factory:VideoChunkManagerFlow]
```

**Comment by TTycho** [comment]
As Markdown Preview Enhanced recently updated Mermaid from 10.9.0 to 11.1.1 I noticed a similar issue. Since this update I get the text "Unsupported markdown: link" in the preview window in Mermaid nodes that contain a string starting with 'www.' or an email address. In the HTML exported version nothing appears in these blocks.

**Environment**
- OS: Linux
- VSCode: 1.92.2
- Markdown Preview Enhanced: 0.8.14
- Mermaid 11.1.1
- Node.js: 20.14.0

**To Reproduce**
Not sure what version Github is using but for me the boxes below A and B are empty:
```mermaid
flowchart
A -->mermaid("www.mermaidjs.org")
B -->me_example_com["me@example.com"]
```

**Expected behavior**

No links created

**Comment by pawel-bugalski** [comment]
I can confirm the problem.
Here is a small reproduction I've made:
https://mermaid.live/edit#pako:eNo9j7EOgzAMRH8l8tRKLO2YuWsn1iwuMQQpiSvjqFSIf28KAk_26Z1Pt0DHnsCCy33kTxdQ1GVT58Xz7eKg5UQmsxoNqCZyHozSrA6uJ3Y_MDSvcWdINmo3eaZpeyGUPclphQYSScLR1_zlrznQQIkc2Lp66rHEmuTyWlEsyu03d2BVCjUgXIYAtsc41au8PSo9RhwE04GQH5XluRfceq4_ZHRQQw

Note that this renders perfectly in Chrome 128.0.6613.120 but fails in Firefox 130.0

Firefox:
<img width="1386" alt="Screenshot 2024-09-10 at 11 20 17" src="https://github.com/user-attachments/assets/aea10ed1-f0e2-48c9-a7ec-fe9f04ae1482">
Chrome:
<img width="1180" alt="Screenshot 2024-09-10 at 11 33 19" src="https://github.com/user-attachments/assets/ee0fc62a-c04e-4c9b-975f-f48fc8e9d813">

**Comment by theletterf** [comment]
Related: https://github.com/mermaid-js/mermaid/issues/5824

**Comment by djibe** [comment]
Solved by <https://github.com/mermaid-js/mermaid/pull/5856>
