### ISSUE TITLE
Mermaid diagrams broken due to DOMPurify release v3.1.7 (empty `<foreignObject`)

### ISSUE THREAD

**Issue by slorber** [mermaid-js/mermaid#5904]
### Description

Upgrade transitive dependency DOMPurify from 3.1.6 to 3.1.7

See flowchart diagram labels being empty, because `<foreignObject>` tags are empty

### Steps to reproduce

Upgrade transitive dependency DOMPurify from 3.1.6 to 3.1.7

````
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
``` 
````

### Screenshots

![image](https://github.com/user-attachments/assets/9d9bbe33-1273-44d4-88e9-ab377f2b70c0)

### Setup

- Mermaid version: 10.x, 11.x
- Browser and Version: all

### Suggested Solutions

Convince DOMPurify to revert breaking change.

DOMPurify report here: https://github.com/cure53/DOMPurify/issues/1002

Workaround, force resolution to v3.1.6	

```js
 "resolutions": {
    "dompurify": "3.1.6"
  },
```

### Additional Context

I'm the maintainer of Docusaurus and this issue affects all our newly initialized sites. The problematic version was published 1 day ago and we already got 2 bug reports that Mermaid diagrams do not work well.

- https://github.com/facebook/docusaurus/issues/10526
- https://github.com/facebook/docusaurus/issues/10524

I'm opening this issue mostly to let you know of the problem. 

I don't really know how Mermaid uses that lib exactly, nor if it's possible for you to patch usage on your side to make Mermaid code compatible with v3.1.7+. You could also decide to pin the dependency.

Personally I consider it a breaking change and they should rather revert it, but it's their responsibility to decide.

**Comment by nijinekoyo** [comment]
Is this issue being fixed? Pinning dependency versions is not a good idea :)

**Comment by slorber** [comment]
The maintainer of DOMPurify doesn't plan to revert the behavior so in the meantime the best option is to pin the dependency in Mermaid.

In the next version (v3.1.8) they plan to add an option that allows Mermaid to restore the previous behavior.

See discussions here: https://github.com/cure53/DOMPurify/issues/1002#issuecomment-2381258197

So to me the plan for Mermaid should be:
- pin to `3.1.6` until `3.1.8` gets released with the new option
- then upgrade to `^3.1.8` and use the new option

**Comment by aloisklink** [comment]
> The maintainer of DOMPurify doesn't plan to revert the behavior so in the meantime the best option is to pin the dependency in Mermaid.

:rocket: Thanks for the help @slorber! I've made https://github.com/mermaid-js/mermaid/pull/5914 that will pin DOMPurify to:

https://github.com/mermaid-js/mermaid/blob/de2c05cd5463af68d19dd7b6b3f1303d69ddb2dd/packages/mermaid/package.json#L80

I'm guessing DOMPurify 3.1.8 will require some config/code changes, so we'd have to make a new Mermaid release that supports `^3.1.8` once it's out!

**Comment by slorber** [comment]
Thanks!

Not sure what's your plan but it may be useful for the community to backport these changes to v10.x patch as well. Although technically v11 was quite easy to adopt for us we only allow 11.x on upcoming Docusaurus v3.6+ and not v2.0-3.5.

**Comment by aloisklink** [comment]
Thanks for bringing that up @slorber!

We've made [v10.9.2](https://github.com/mermaid-js/mermaid/releases/tag/v10.9.2) that has this change!

**Comment by slorber** [comment]
Thanks 👍 Docusaurus users will thank you without knowing any of this ever happened 😄

**Comment by beanaroo** [comment]
Should `@types/dompurify` perhaps be pinned to `3.0.5`? I started encountering this error today:

```
error TS2688: Cannot find type definition file for 'dompurify'.
  The file is in the program because:
    Entry point for implicit type library 'dompurify'

Found 1 error.
```

```
$ npm ls @types/dompurify

@my-org/my-package@3.145.0 /Users/me/Projects/my-project
└─┬ @my-org/my-package-doc@3.145.0 -> ./doc
  └─┬ @docusaurus/theme-mermaid@3.6.3
    └─┬ mermaid@11.4.0
      ├─┬ @types/dompurify@3.2.0
      │ └── dompurify@3.1.6 deduped
      └── dompurify@3.1.6
```

https://www.npmjs.com/package/@types/dompurify/v/3.2.0 shows:

> This is a stub types definition. dompurify provides its own type definitions, so you do not need this installed. 

It seems `v3.0.5` was the latest version prior
