### ISSUE TITLE
Architecture Diagram grows very tall

### ISSUE THREAD

**Issue by Carus11** [mermaid-js/mermaid#5952]
### Description

I have an architecture diagram with two groups, and in one group a bunch of nodes/database objects which I want to link to a particular service. I have done this through junctions but notice that when I create an edge connecting the two groups I then can cause the diagram to grow to a very tall size. If I leave the two groups disconnected it seem reasonable.

![image](https://github.com/user-attachments/assets/b77d4911-a920-4ede-873c-6dadd90bd03e)

### Steps to reproduce

In the code sample try removing and adding the line:

```
edge:R -- L:firewall
```

### Code Sample

```text
https://develop.git.mermaid.live/edit#pako:eNqFlcGOgjAQhl-l6UkTPQjqgeNmNXvQbKJ7E7MpdMDuSmtKcWOM774FrIVQhUtp55_5_g6hveJYUMABJjI-MAWxKiSMI1Ak5Eg_qRTFCSVAQRIFdBAfRUGHu6VZQAt-ZlLwDLja1ynlk4M8sxiqEeRkUI_D3faSK8j2iHFbs5sFNIVHykJP0DuUgVd5mhJs0HiMVkGZHvKmf8G_TxIy4_6jiBxeEybhjxyPD_LyvtCk3ys926ndaDW6UwzI-K1zjONmURpNBpQoEpEchjs9e-2BRl5L7vXJ_Zbc75NPW_Jpn3zWks_65POWfN6W24SfgseKCY4yRp9WBBm8lc39CrTKmT1ZQaJE8qyIDZuvVBVyhO8c_XGcHO81x-twbGmn6oHznDj_Nc7v4DwHznfgfHcXNyw9qM9k_YTX3JeVNvpoFy1qauOuhvYgmyXNHl1oz4WedcGuJvdY8LoWfJcF32Vhjiy5lpbnmaljzo4ygkc4A5kRRvX5fS1XQqwOkEGIA_1KifwNcchvWkcKJbYXHuNAyQJGWJ-K6QEHCTnmelac9J8H74ykkmRGApQpIdf17VBdErd_TZnrJg
```

### Setup

- Mermaid version: Mermaidv11.3.0+f859772  (From live editor)
- Browser and Version:  Edge 129.0.2792.79 , Firefox v131

### Additional Context

If I re-arrange the whole thing in a right to left orientation it seems to work

**Comment by NicolasNewman** [comment]
Thanks for bringing this up! I've identified the cause and will hopefully have a fix out by the end of this coming week.
