### ISSUE TITLE
Error: email address in digram

### ISSUE THREAD

**Issue by QriDoki** [mermaid-js/mermaid#5986]
### Description

Error: email address in digram

### Steps to reproduce

graph
    WY(qriDoki@163.com)
    MOE(qri@qri.moe)
    MOE --> WY  

### Screenshots

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/db47b5cf-a84b-40e9-a435-56d24b507d3d">

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by patHyatt** [comment]
A solution without changes needed
- Wrap the email in an **a**nchortag and prefix href with `mailto:`

```
graph
WY[<a href='mailto:qriDoki@163.com'>qriDoki@163.com</a>]
MOE[<a href='mailto:qri@qri.moe'>qri@qri.moe</a>]
MOE --> WY
```
