### ISSUE TITLE
Link text in class diagram doesn't support character escaping 

### ISSUE THREAD

**Issue by AndreiShenets** [mermaid-js/mermaid#6021]
### Description

I have following class diagram

```text
classDiagram
direction BT
class Entity1 {
   text Id
}
class Entity2 {
   text Id
   text Entity1Id
}

Entity2  -->  Entity1 : "Entity1Id:Id"
```

Which fails to render with the error like below:

![image](https://github.com/user-attachments/assets/3cb51c36-a598-4842-86c0-28234c9309c2)

Both double quotes and escaping ':' with '\\' doesn't help. I was not able to find other ways of escaping so I think it is a bug.

Example:
```mermaid
classDiagram
direction BT
class Entity1 {
   text Id
}
class Entity2 {
   text Id
   text Entity1Id
}

Entity2  -->  Entity1 : "Entity1Id:Id"
```

### Steps to reproduce

Post the code from the example into the live editor

### Screenshots

![image](https://github.com/user-attachments/assets/7b62b8d7-1f1c-4038-abef-6c708ec5360b)

### Code Sample

```text
classDiagram
direction BT
class Entity1 {
   text Id
}
class Entity2 {
   text Id
   text Entity1Id
}

Entity2  -->  Entity1 : "Entity1Id:Id"
```

### Setup

- Mermaid version: latest in live editor
- Browser and Version: Chrome 130.0.6723.92, Edge 130.0.2849.68

**Comment by jgreywolf** [comment]
Closing this as a duplicate of #4488

**Comment by jgreywolf** [comment]
Closing this as a duplicate of #4488
