### ISSUE TITLE
Nested class diagram crashes diagram creation

### ISSUE THREAD

**Issue by D0kRay** [mermaid-js/mermaid#6085]
### Description

This function was mentioned in issue #5487 and should be possible with the following syntax.
If i paste the underlying snippet in the live editor (develop and normal) the creation of the diagram fails.
```
classDiagram
  
  namespace presentation{
      class auth
      class main
  }
  namespace auth{
      class AuthScreen
      class AuthViewModel
  }
  namespace main{
      class MainScreen
      class MainViewModel
  }
```

### Steps to reproduce

1. paste the snippet in the description in the live editor
2. live preview doesn't work

### Code Sample

```text
classDiagram
  
  namespace presentation{
      class auth
      class main
  }
  namespace auth{
      class AuthScreen
      class AuthViewModel
  }
  namespace main{
      class MainScreen
      class MainViewModel
  }
```

### Setup

- Mermaid version: 11.4
- Browser and Version: Chrome, Edge

**Comment by jgreywolf** [comment]
Closing this as this is not currently supported, and is covered in #6018
