### ISSUE TITLE
At some occations the intersection calculations for diamond shapes fail when using elk

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#6088]
### Description

...

### Steps to reproduce

-

### Screenshots

![image](https://github.com/user-attachments/assets/8a3257c0-40b3-41c7-8fee-cdb9a0904500)

### Code Sample

```text
..
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by ashishjain0512** [comment]
It was fixed in `0.1.7` mermaid layout-elk package
