### ISSUE TITLE
Discord invitation on mermaid.js.org is invalid

### ISSUE THREAD

**Issue by johnnydecimal** [mermaid-js/mermaid#6137]
### Description

The Discord invitation link, `https://discord.gg/AgrbSrBer3`, at the top-right of the project home page is invalid:

```text
Invite Invalid

This invite may be expired or you might not have permission to join.
```

### Steps to reproduce

1. Visit that URL.
2. Sadness.

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by huynhicode** [comment]
Hi @johnnydecimal thanks for reporting! A PR has been raised to fix the broken links. 

In the meantime, please use this link: https://discord.gg/sKeNQX4Wtj
