### ISSUE TITLE
Is there a way to use emoji?

### ISSUE THREAD

**Issue by edudesouza** [mermaid-js/mermaid#625]
Hi there, 

I have a flow chart, that is a chatbot conversation, and we have some emojis in our texts.
Is there a way to incorporate it?

Many thanks.

**Comment by tylerlong** [comment]
Currently nope, I am afraid.

**Comment by RangerMauve** [comment]
Heyo! This is still very important. :D

**Comment by wemod123** [comment]
Of course, emoji support will give this package much powerful visualization

**Comment by knsv** [comment]
We do support fontawesome ut emojis are emojis... 🌠

**Comment by RangerMauve** [comment]
Any opposition to including emoji in the unicode text range? Basing this off of [this GH issue](https://github.com/diasks2/pragmatic_tokenizer/issues/20#issuecomment-374352212) and looking at the code for parsing [UNICODE_TEXT](https://github.com/mermaid-js/mermaid/blob/51e902cd36430be1fb6ea0d15bfe789bc690ed7e/src/diagrams/flowchart/parser/flow.jison#L102) tokens.

**Comment by RangerMauve** [comment]
Started playing around with the idea here: https://github.com/RangerMauve/mermaid/tree/emoji

**Comment by Dunning-Kruger** [comment]
@RangerMauve Join us [in slack](https://join.slack.com/t/mermaid-talk/shared_invite/enQtNzc4NDIyNzk4OTAyLWVhYjQxOTI2OTg4YmE1ZmJkY2Y4MTU3ODliYmIwOTY3NDJlYjA0YjIyZTdkMDMyZTUwOGI0NjEzYmEwODcwOTE) if you need some help/feedback/answers and be sure to read the [contribution guide](https://github.com/mermaid-js/mermaid/blob/master/CONTRIBUTING.md)!

**Comment by Jmedders** [comment]
Just stumbled across this solution after addressing when an end-user puts in breaking characters like: `(` or `{` 
See: http://mermaid-js.github.io/mermaid/#/flowchart?id=special-characters-that-break-syntax. 

Basically just wrap in double quotes and pasting in emojis is not an issue.
```
graph TD
A-->B("hello 🥰")
```

<img width="132" alt="Screen Shot 2019-11-25 at 11 51 19 AM" src="https://user-images.githubusercontent.com/16631297/69569296-93e66c80-0f7a-11ea-97df-88de96d21a37.png">

**Comment by joe733** [comment]
> Just stumbled across this solution after addressing when an end-user puts in breaking characters like: `(` or `{`
> See: http://mermaid-js.github.io/mermaid/#/flowchart?id=special-characters-that-break-syntax.
> 
> Basically just wrap in double quotes and then you can paste in emojis
> 
> ```
> graph TD
> A-->B("hello 🥰")
> ```
> 
> <img alt="Screen Shot 2019-11-25 at 11 51 19 AM" width="132" src="https://user-images.githubusercontent.com/16631297/69569296-93e66c80-0f7a-11ea-97df-88de96d21a37.png">

Thanks! The same goes for Unicode characters like `●` `→` etc. Found it useful when I was building [`LR(0)`](https://en.wikipedia.org/wiki/LR_parser#Items) items:

![image](https://user-images.githubusercontent.com/38415384/84564078-e738d480-ad7d-11ea-8282-40af180beefd.png)

Just wondering if I can align the multiple lines to `left` instead of `centre` which appears to be default.

**Comment by SamuelMarks** [comment]
[an aside] @joe733 you coming from Tikz? - Would be handy to get your notes there! :)

**Comment by joe733** [comment]
> [an aside] @joe733 you coming from Tikz? - Would be handy to get your notes there! :)

[off-topic] @SamuelMarks, I've not used Tikz. As for the notes... it's an assignment by our compiler design teacher, thought it would be fun to give it a try with `.md` & mermaid :smile: and oh about the PDF I'm generating it using [Joplin](https://github.com/laurent22/joplin/).

**Comment by GDFaber** [comment]
Hi everyone, I'm not entirely sure but, according to the example listed above, it seems to me that using emoji is possible:
[Example in the Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkEtLT5CKFwiaGVsbG8g8J-lsFwiKSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0IiwiZmxvd2NoYXJ0Ijp7Imh0bWxMYWJlbHMiOmZhbHNlfX0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

If my assumtions are correct, can we close this issue?

**Comment by GDFaber** [comment]
This issue seems to be solved so we can close here.
