### ISSUE TITLE
Pointing to a subgraph

### ISSUE THREAD

**Issue by stckcrsh** [mermaid-js/mermaid#644]
It would be nice if we could have an arrow point to a subgraph

I am working on mapping some state charts and found that i could get close to mapping it completely using the flowcharts but the only missing thing was the ability to point to a subgraph.

As a workaround i am making nodes in the subgraphs called initial that all other places point to when they would normally point to the graph.

**Comment by internetrush1** [comment]
Agreed, was just going to open an issue for this.

+1

**Comment by Dieterbe** [comment]
+1

**Comment by RupalBarman-alation** [comment]
+1

**Comment by benelgiac** [comment]
+1 as well! Would be very useful

**Comment by tischi** [comment]
+1

**Comment by amittestkiwi** [comment]
+1

**Comment by Dieterbe** [comment]
> If you are still interested in it, and it is still relevant, you can comment or remove the label to revive it.

I am, it is.

**Comment by getconor** [comment]
I am also still interested in this and believe it is still relevant.

**Comment by Dunning-Kruger** [comment]
Note that right now the project has a lot more requests piled up than it can handle.
[We would be happy to accept new collaborators! ](https://github.com/knsv/mermaid/issues/866)

**Comment by knsv** [comment]
This is quite a big task, believe it or not, as dagre-d3 which is used for rendering does not support this. I am currently working State Diagrams which **will** support this feature (for state diagrams). There are several other features also beeing limited by dagre-d3 like multi directional arrows and more arrow types.

This is another incentive to move away from dagre-d3 and render in house instead.

I don't see this happening in the short term though.

**Comment by RobCoPKC** [comment]
+1 would make mermaid-js even more useful

**Comment by knsv** [comment]
There has been some progress here. There is a new rendering engine capable of doing this. It is still in beta but possible to use as of 8.5.1

https://mermaid-js.github.io/mermaid/#/flowchart?id=beta-flowcharts

Eventually both graph/flowchart will render the flowchart using this new way of rendering.

**Comment by giovap95** [comment]
Hi, 
what about arrows pointing _from_ a node _to_ a subgraph? It looks like that isn't supported right now.

**Comment by knsv** [comment]
Hi!

This should be possible now, see the attached example.

https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZmxvd2NoYXJ0IExSXG4gICAgQSAtLT4gQlxuICAgIFxuc3ViZ3JhcGggQlxuICAgQ1tJbiB0aGUgc3ViZ3JhcGdoXVxuZW5kIiwibWVybWFpZCI6e30sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

Will close this for now.
