### ISSUE TITLE
`classDef default` does not apply

### ISSUE THREAD

**Issue by kohenkatz** [mermaid-js/mermaid#684]
According to [the docs](https://mermaidjs.github.io/flowchart.html#default-class), I should be able to set the style of any otherwise-unstyled flowchart elements like this:

```
classDef default fill:#f9f,stroke:#333,stroke-width:4px;
```

However, it doesn't seem to actually work.

Here's an example [in the Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5cbmNsYXNzRGVmIHJlZCBmaWxsOiNmMDA7XG5jbGFzc0RlZiBkZWZhdWx0IGZpbGw6IzBmMDtcbmNsYXNzIEIgcmVkOyIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19) (based on the default sample):

![image](https://user-images.githubusercontent.com/88755/42521968-011c49f2-8438-11e8-984d-69d3613b72d2.png)

**Comment by sethbro** [comment]
Same issue here.

**Comment by pocc** [comment]
Same issue here, using Hugo, Learn theme. My solution in the [live editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5cbmNsYXNzRGVmIHJlZCBmaWxsOiNmMDA7XG5jbGFzc0RlZiBvdGhlcnMgZmlsbDojMGYwO1xuY2xhc3MgQiByZWQ7XG5jbGFzcyBBLEMsRCxFLEYgb3RoZXJzIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0) is to explicitly assign all other nodes to this class.

<img width="802" alt="Screen Shot 2019-05-06 at 1 14 21 AM" src="https://user-images.githubusercontent.com/10995145/57202382-64e7b980-6f9c-11e9-8df0-099fcc7f6031.png">

**Comment by pocc** [comment]
This is still an issue as the bug still exists.

**Comment by bhrutledge** [comment]
Maybe this could be worked around via the `node` and `edgePath` classes that are already applied:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;

classDef node stroke-width:2px,fill:none,stroke:red
classDef edgePath stroke-width:2px,stroke-dasharray: 5, 5
```
<img width="154" alt="Screen Shot 2019-07-06 at 7 03 27 AM" src="https://user-images.githubusercontent.com/1326704/60755331-339b6200-9fbc-11e9-908e-bbeda114a4f7.png">

See also #724.

**Comment by kohenkatz** [comment]
@bhrutledge That sounds good to me, but it still means the docs need to be updated.

**Comment by kohenkatz** [comment]
@bhrutledge The other issue is that you need to be much more careful when doing that: If you could use the `default` class described in the docs, then any node that is not specifically assigned a class will use the `default` style but any node that *is* assigned a specific class will not get those styles. If it is done your way, then you need to "undo" the `node` style for any other class you create.

For example, if you use `default`:

```
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[fa:fa-car Car]

classDef default fill:#0f0,stroke-width:4px;
classDef red fill:#f00;
class B red;
```

In this case, you don't need to reset `stroke-width` back to `1px` in `classDef red`.

However, if using `node`:

```
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[fa:fa-car Car]

classDef node fill:#0f0,stroke-width:4px;
classDef red fill:#f00,stroke-width:1px;
class B red;
```

If you do it this way, you need to reset the `stroke-width` back to the previous value.

Not a deal-breaker, but still a little annoying.

**Comment by kohenkatz** [comment]
This is still relevant:

- The docs [still say](https://mermaidjs.github.io/#/flowchart?id=default-class):

    > If a class is named default it will be assigned to all classes without specific class definitions.

- The online editor running the newest version [still doesn't respect a `default` class definition](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5cbmNsYXNzRGVmIHJlZCBmaWxsOiNmMDA7XG5jbGFzc0RlZiBkZWZhdWx0IGZpbGw6IzBmMDtcbmNsYXNzIEIgcmVkOyIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

**Comment by pocc** [comment]
Repeating my last comment:

> This is still an issue as the bug still exists.

**Comment by GDFaber** [comment]
Let's fix `classDef default` rather than update the docs. As @kohenkatz stated above, it is less error-prone than using 'classDef node` for this purpose. PR coming up this weekend if all goes well.

**Comment by GDFaber** [comment]
FYI: During my tests for this issue I realized that text colors are not properly applied if htmlLabels are disabled, but this will be tackled in a new issue entry as this one is about applying the default class definition.
