### ISSUE TITLE
Sequencediagram text with <br /> BR tag with space fails

### ISSUE THREAD

**Issue by gene1wood** [mermaid-js/mermaid#702]
This works 

[working example](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgSm9lXG4gICAgcGFydGljaXBhbnQgQWxpY2VcbiAgICBKb2UtPj5BbGljZTogRm9vXG4gICAgTm90ZSBvdmVyIEFsaWNlOiBCYXI8YnIvPkJhelxuICAgIE5vdGUgb3ZlciBKb2UsQWxpY2U6IFRoYXQgbm90ZSBhYm92ZSBzaG91bGQgaGF2ZSBoYWQgYSBjYXJyaWFnZSByZXR1cm4gYmV0d2VlbiBCYXIgYW5kIEJheiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

```
sequenceDiagram
    participant Joe
    participant Alice
    Joe->>Alice: Foo
    Note over Alice: Bar<br/>Baz
    Note over Joe,Alice: That note above should have had a carriage return between Bar and Baz
```
but this, with a space between the `r` and `/` fails by rendering the `<br />` as text not as a line break. One tricky thing is that if you look at it in the interactive view, and then type something on the line with the `<br />` it displays correctly, but the view link continues to display incorrectly.

[non working example](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgSm9lXG4gICAgcGFydGljaXBhbnQgQWxpY2VcbiAgICBKb2UtPj5BbGljZTogRm9vXG4gICAgTm90ZSBvdmVyIEFsaWNlOiBCYXI8YnIgLz5CYXpcbiAgICBOb3RlIG92ZXIgSm9lLEFsaWNlOiBUaGF0IG5vdGUgYWJvdmUgc2hvdWxkIGhhdmUgaGFkIGEgY2FycmlhZ2UgcmV0dXJuIGJldHdlZW4gQmFyIGFuZCBCYXoiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

```
sequenceDiagram
    participant Joe
    participant Alice
    Joe->>Alice: Foo
    Note over Alice: Bar<br />Baz
    Note over Joe,Alice: That note above should have had a carriage return between Bar and Baz
```

This may relate to some challenges people had in #384

**Comment by gene1wood** [comment]
@watsoncj You'd said that PR #764 fixes this bug, but when I go and test the [non working example](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgSm9lXG4gICAgcGFydGljaXBhbnQgQWxpY2VcbiAgICBKb2UtPj5BbGljZTogRm9vXG4gICAgTm90ZSBvdmVyIEFsaWNlOiBCYXI8YnIgLz5CYXpcbiAgICBOb3RlIG92ZXIgSm9lLEFsaWNlOiBUaGF0IG5vdGUgYWJvdmUgc2hvdWxkIGhhdmUgaGFkIGEgY2FycmlhZ2UgcmV0dXJuIGJldHdlZW4gQmFyIGFuZCBCYXoiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ) above, it still manifests this bug.

Is this because when @tylerlong merged your PR it hasn't yet been manifested in the code used on `mermaidjs.github.io`? I'm assuming that your code would be live now considering it was merged back in November 2018

**Comment by gene1wood** [comment]
@watsoncj You'd said that PR #764 fixes this bug, but when I go and test the [non working example](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgSm9lXG4gICAgcGFydGljaXBhbnQgQWxpY2VcbiAgICBKb2UtPj5BbGljZTogRm9vXG4gICAgTm90ZSBvdmVyIEFsaWNlOiBCYXI8YnIgLz5CYXpcbiAgICBOb3RlIG92ZXIgSm9lLEFsaWNlOiBUaGF0IG5vdGUgYWJvdmUgc2hvdWxkIGhhdmUgaGFkIGEgY2FycmlhZ2UgcmV0dXJuIGJldHdlZW4gQmFyIGFuZCBCYXoiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ) above, it still manifests this bug.

@tylerlong merged your PR into [`7.0.2`](https://github.com/knsv/mermaid/blob/master/CHANGELOG.md#702-2017-06-01) but the bug persists in the current version of `8.3.0`.

**Comment by GDFaber** [comment]
This seems to be similar to #1088. Looking at the commit mentioned above, the regex ```<br\/?>``` is used to determine the lines. This takes care of ```<br>``` and ```<br/>``` but does not find ```<br />```.

If noone is already working at this issue, I can take a look at it.

**Comment by GDFaber** [comment]
PR coming up for the weekend I suppose.
