### ISSUE TITLE
 Rounded corners shape should have completely round end-caps in mermaid flowchart.

### ISSUE THREAD

**Issue by dotancohen** [mermaid-js/mermaid#723]
Flowchart symbols convention specifies that flowchart Terminators (start and stop points) should have completely round end-caps. Mermaid should support such a shape.

I propose either modifying the `(foo)` shape to have a completely round end-cap (`stroke-linecap:round`) as there is no use for slightly-rounded corners in the Flowchart symbols convention, or perhaps to have a new shape `([foo])`, `(_foo_)`, or `[(foo)]` that has this feature.

Flowchart symbols reference:
https://www.rff.com/flowchart_shapes.php
https://www.smartdraw.com/flowchart/flowchart-symbols.htm
https://www.lucidchart.com/pages/flowchart-symbols-meaning-explained

**Comment by dotancohen** [comment]
A bit of activity for the stalebot.

**Comment by dotancohen** [comment]
A bit of activity for the stalebot.

**Comment by knsv** [comment]
I approve. This should not be too difficult and is good first issue. However, think thoughly about a intuitive syntax. The proposed syntax needs some work:
```
([foo]), (_foo_), or [(foo)]
```
In PlantUML state diagrams en markers are denote with [*]. Maybe `(* Text *)`?

**Comment by dotancohen** [comment]
> In PlantUML state diagrams en markers are denote with [*]. Maybe `(* Text *)`?

Sure, that looks fine.

**Comment by GDFaber** [comment]
Using ```(* Text *)``` would cause a minor change in behaviour though, because it can be used to produce the node text "* Text *" (which works in the live editor). Should stick to it anyway or rather use another syntax?

**Comment by dotancohen** [comment]
@GDFaber You are correct. I just checked the live editor and `([ Foo ])` does not have this problem. It also looks like the element produced, so is very fitting for Mermaid's intuitive behaviour.

Use `([ Foo ])` syntax.

**Comment by GDFaber** [comment]
This seems to be a good opportunity to shake hands with the mermaid flowcharts code, so I'd like to give this one a try.

**Comment by chris579** [comment]
Great, looking forward for your PR.

**Comment by knsv** [comment]
@GDFaber How are things going? Let me know if you are stuck. I would be glad to assist either by chat or call.

**Comment by GDFaber** [comment]
Hi @ksnv, I had no time to start with this until now, but I'll get to it tomorrow night and give it a try. I will let you know how it gets along. Thanks for offering, I will surely let you know via Slack if I run into problems.

**Comment by GDFaber** [comment]
That was fun :) I think it works properly, but I'll fill in the tests first and hand in my PR tomorrow night.

**Comment by GDFaber** [comment]
Done, my PR is at #1130.
