### ISSUE TITLE
gantt: syntax for multi-line section titles?

### ISSUE THREAD

**Issue by rhz** [mermaid-js/mermaid#743]
I'd like to have multi-line section titles. Is there a syntax for that?

**Comment by rhz** [comment]
I tried with `tspan` as suggested in [this SO answer](https://stackoverflow.com/a/31509120/3746788) but it doesn't work.

**Comment by rhz** [comment]
I tried all the suggestions in #384. None worked.

**Comment by rhz** [comment]
Replacing `.text` by `.html` in [line 274 of ganttRenderer.js](https://github.com/knsv/mermaid/blob/a4992963b3873ec7a566ba91b92596d2a360e3b9/src/diagrams/gantt/ganttRenderer.js#L274) and having a section title like
```
section <tspan x="10" dy="0em">Line 1</tspan><tspan x="10" dy="1.4em">Line 2</tspan>
```
does the trick. However, the position along the y axis of the section title isn't quite right anymore.

**Comment by rhz** [comment]
A bit off-topic: while tinkering with the code that computes the position along the y axis of the section title I found that the `for` loop in [line 280 of ganttRenderer.js](https://github.com/knsv/mermaid/blob/a4992963b3873ec7a566ba91b92596d2a360e3b9/src/diagrams/gantt/ganttRenderer.js#L280) seems to be unnecessary (its body should be kept though). `prevGap` is accumulated by iterating over `numOccurances` with `.data(numOccurances)`. Also, the `for` loop never gets to run its body more than once since it [returns immediately](https://github.com/knsv/mermaid/blob/a4992963b3873ec7a566ba91b92596d2a360e3b9/src/diagrams/gantt/ganttRenderer.js#L282).

**Comment by wgroeneveld** [comment]
Yes please, struggling with the same, also tried everything in #384 - no avail.

**Comment by rhz** [comment]
What will happen with this feature request? Will it be implemented?

**Comment by rhz** [comment]
Is this project still alive? Any contributor would like to chime in?

**Comment by Dunning-Kruger** [comment]
The project is still alive and well however there's more feature requests than pull requests so it might fall through the cracks....

**Comment by rhz** [comment]
Hi @Dunning-Kruger! It's good that the project is alive and well :)
Before a pull request can be made for this feature request, perhaps it would be would to talk about what the ideal solution would look like and what other solutions are acceptable.
For example, could [the little patch I commented above](https://github.com/knsv/mermaid/issues/743#issuecomment-428909404) be a good or acceptable solution?

**Comment by Dunning-Kruger** [comment]
@rhz I can't comment on the proposed solution. If it's a small effort, feel free to get a pull request up. If not, feel free to drop by [our slack community ](https://join.slack.com/t/mermaid-talk/shared_invite/enQtNzI4NDU5ODkzMTkxLTk3MDVmYmY5Y2ZjZThkZWQ2Y2ExMzVmOGQxZGEyZDFmZDI4OWE0NzZjOWJmOTVmNjkzMmM4YWI5ZjQzNmVhMzg)and talk with people who know more about the platform than I do! Thanks for the interest!

**Comment by rhz** [comment]
It is indeed a tiny patch, just one line change. However, doing a pull request would involve first learning how to do one (or maybe I could just do it on github's web interface directly?). Since I doubt it will be accepted, I don't think I'll be learning how to do a pull request at the moment. Regarding the link to join the slack community, it says "This invite link is no longer active" when I go through it.

**Comment by Dunning-Kruger** [comment]
@rhz Link was updated here: https://github.com/knsv/mermaid/issues/866

**Comment by rhz** [comment]
Thanks @Dunning-Kruger

**Comment by GDFaber** [comment]
I suggest splitting the lines up into ```tspan``` items and appending them to the ```text``` in one turn with its creation. As mentioned by @rhz, the y position should be updated as well for multiline texts. I'd like to take a look at it but it may take some time.

**Comment by GDFaber** [comment]
PR is ready
