### ISSUE TITLE
Support alternate arrow heads

### ISSUE THREAD

**Issue by elipriaulx** [mermaid-js/mermaid#780]
In order to use the [Flowchart](https://mermaidjs.github.io/flowchart.html) to draw simple object or class diagrams with a UML-esque feel, it would be great to be able to designate arrow heads accordingly. This is a semantic thing rather than a stylistic thing I suppose, and would make sense to be done where the line and arrow is expressed. 

I have had a quick look through the documentation and googled-around - maybe I am missing something but it doesn't look to be possible to specify this when the connections are expressed. I wouldn't go as far as advocating for complete support of UML class and object diagrams out of the box within the Flowchart mechanism, but a simple compromise such as supporting the arrow heads would go a long way.

Examples of arrow heads to support:

![arrowheads](https://user-images.githubusercontent.com/8568379/51060904-7c91df80-1645-11e9-8978-bf27fcd7318c.png)

- Filled Enclosed (already supported)
- Open
- Hallow Enclosed
- Hallow Diamond
- Filled Diamond

**Comment by robertscotthoward** [comment]
Even just the Open Arrowhead (for inheritance) would triple the value of this clever technology.

**Comment by C5H8NNaO4** [comment]
Is there any update on this issue? I'm trying to render neurological pathways like this ![ads](https://www.wikipathways.org//wpi/wpi.php?action=downloadFile&type=png&pwTitle=Pathway:WP3869&oldid=98007)

**Comment by azaroth42** [comment]
Would be very useful for our usage too (RDF graph diagrams)

**Comment by tomiaro** [comment]
If you want to use arrowhead for Inheritance in your GRAPH set:
  
mermaid.initialize({
       themeCSS: '#extensionEnd { fill: white; }',
  });

**Comment by chris579** [comment]
We now have [class diagrams](https://mermaid-js.github.io/mermaid/#/classDiagram?id=class-diagrams) which support most of this [relation types](https://mermaid-js.github.io/mermaid/#/classDiagram?id=defining-relationship). Flow diagrams are not supposed to be used for UML. This is the scope of class diagrams.

For dependency relations, this is tracked in #1146
