### ISSUE TITLE
Maintain the order of the nodes in Flowchart

### ISSUE THREAD

**Issue by vidur149** [mermaid-js/mermaid#815]
I have defined a graph as follows ->
```
graph TD
linkStyle default interpolate basis
subgraph 
A[gunung]-->B[NOUN]
C[Krakatau]--> D[NOUN]
E[Yang]-->F[PRON]
G[Pernah]-->H[ADV]
I[meletus] --> J[VERB]
K[mulai]-->L[VERB]
M[terbatuk-batuk] --> N[VERB]
end
subgraph 
  B --> O[FN]
  D --> O
  F --> O
  J --> O
  L --> P[FV]
  N --> P
end
subgraph 
  O --> Q[Subject]
  P --> R[Predicate]
end
subgraph 
 Q-->S[clause]
 R-->S
end
```
[Editor Link](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbmxpbmtTdHlsZSBkZWZhdWx0IGludGVycG9sYXRlIGJhc2lzXG5zdWJncmFwaCBcbkFbZ3VudW5nXS0tPkJbTk9VTl1cbkNbS3Jha2F0YXVdLS0-IERbTk9VTl1cbkVbWWFuZ10tLT5GW1BST05dXG5HW1Blcm5haF0tLT5IW0FEVl1cbklbbWVsZXR1c10gLS0-IEpbVkVSQl1cbktbbXVsYWldLS0-TFtWRVJCXVxuTVt0ZXJiYXR1ay1iYXR1a10gLS0-IE5bVkVSQl1cbmVuZFxuc3ViZ3JhcGggXG4gIEIgLS0-IE9bRk5dXG4gIEQgLS0-IE9cbiAgRiAtLT4gT1xuICBKIC0tPiBPXG4gIEwgLS0-IFBbRlZdXG4gIE4gLS0-IFBcbmVuZFxuc3ViZ3JhcGggXG4gIE8gLS0-IFFbU3ViamVjdF1cbiAgUCAtLT4gUltQcmVkaWNhdGVdXG5lbmRcbnN1YmdyYXBoIFxuIFEtLT5TW2NsYXVzZV1cbiBSLS0-U1xuZW5kXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)
I need to preserve the order of the nodes. I defined ```Pernah``` before ```Yang``` but it comes in the end. Please help, on how to maintain the order of the nodes. Thanks. It would really help me achieve everything I ever wanted :p.

**Comment by spex66** [comment]
not ideal, but adding a sub-subgraph around your terms from the FN clause, the order will be preserved
```
graph TD
linkStyle default interpolate basis
subgraph 

subgraph FN
A
C
E
G
I
end

A[gunung]-->B[NOUN]
C[Krakatau]--> D[NOUN]
E[Yang]-->F[PRON]
G[Pernah]-->H[ADV]
I[meletus] --> J[VERB]
K[mulai]-->L[VERB]
M[terbatuk-batuk] --> N[VERB]
end

subgraph 
  B --> O[FN]
  D --> O
  F --> O
  J --> O
  L --> P[FV]
  N --> P
end
subgraph 
  O --> Q[Subject]
  P --> R[Predicate]
end
subgraph 
 Q-->S[clause]
 R-->S
end
```

**Comment by knsv** [comment]
**Hi! Sorry for the slow response.**

The posisitioning of the nodes are done by a layout algorithm and sometimes that one is not perfect and worksarounds like the one is required. I am aware of this but is not easy to fix. I have half an idea of adding more layout algorithms and the possibility to pick the one thats best fits a particular use case.

The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866. I am closing this one for now, not out of disrespect but as a part of an effort to clean out stale issues that has been resolved but not closed. 

Is this still a problem? If so please reopen it.

**Comment by joe733** [comment]
Hi I'm having the same issue.

I need to preserve the order of the nodes else the _parse-tree_ (to parse a string like  `2 + 3 * 4` ) won't work.

```mermaid
graph TD
E(E)
E1(E)
E2(E)
T(T)
T1(T)
T2(T)
F(F)
F1(F)
F2(F)
_P(+)
_S(*)
_D(num)
_D2(num)
_D3(num)

E --> E1
E --> _S
E1 --> T
T --> F
F --> _D
E1 --> E2
E2 --> T2
T2 --> F2
F2 --> _D2
E1 --> _P
E --> T1
T1 --> F1
F1 --> _D3
```

> Btw is there a way to optimize (in every sense) the above mermaid graph to yield the following figure. 

Here `+` needs to be move to middle & it's siblings on either sides, with the longer one on the left.

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbkUoRSlcbkUxKEUpXG5FMihFKVxuVChUKVxuVDEoVClcblQyKFQpXG5GKEYpXG5GMShGKVxuRjIoRilcbl9QKCspXG5fUygqKVxuX0QobnVtKVxuX0QyKG51bSlcbl9EMyhudW0pXG5cbkUgLS0-IEUxXG5FIC0tPiBfU1xuRTEgLS0-IFRcblQgLS0-IEZcbkYgLS0-IF9EXG5cblxuRTEgLS0-IEUyXG5FMiAtLT4gVDJcblQyIC0tPiBGMlxuRjIgLS0-IF9EMlxuRTEgLS0-IF9QXG5FIC0tPiBUMVxuVDEgLS0-IEYxXG5GMSAtLT4gX0QzIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkUoRSlcbkUxKEUpXG5FMihFKVxuVChUKVxuVDEoVClcblQyKFQpXG5GKEYpXG5GMShGKVxuRjIoRilcbl9QKCspXG5fUygqKVxuX0QobnVtKVxuX0QyKG51bSlcbl9EMyhudW0pXG5cbkUgLS0-IEUxXG5FIC0tPiBfU1xuRTEgLS0-IFRcblQgLS0-IEZcbkYgLS0-IF9EXG5cblxuRTEgLS0-IEUyXG5FMiAtLT4gVDJcblQyIC0tPiBGMlxuRjIgLS0-IF9EMlxuRTEgLS0-IF9QXG5FIC0tPiBUMVxuVDEgLS0-IEYxXG5GMSAtLT4gX0QzIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

@spex66 sorry, I didn't get the idea of sub-graphs.

**Comment by danitrod** [comment]
I am having the same problem as @joe733. I wanted to do a parse-tree for a college class and I wanted to use mermaid, but I will have to switch to another software because of the messed up ordering.

**Comment by XertroV** [comment]
I have a similar issue to @joe733 and @danitrod 

note: I'm automatically converting whitespace indented s-expressions (though cheating because I strip out parens and just use whitespace)

Here's an example: 

![image](https://user-images.githubusercontent.com/1046448/86323985-2ffaf380-bc81-11ea-82f6-fd9144e1c9f5.png)

spamming subgroups does seem to work:

![image](https://user-images.githubusercontent.com/1046448/86325250-18246f00-bc83-11ea-884a-72d07a3be706.png)

but is ugly. Might try and patch mermaid.js to draw "invisible" boxes around subgroups with "#nbsp;" as their name. Oh and fix the phantom subgroups that show up.

source code (tree stuff is in docs/_layouts/default.html): https://github.com/xertrov/fi

**Comment by XertroV** [comment]
:tada: https://github.com/XertroV/mermaid/commit/aa670effa3aeb7ebc25462cc5dcee08279ee2c8a

Invisible subgroups to force ordering:

![image](https://user-images.githubusercontent.com/1046448/86331023-db10aa80-bc8b-11ea-96be-8b91d509c828.png)

**Comment by Polirecyliente** [comment]
I spent some time looking for a solution to this, and @XertroV answer served for me, so I'm going to write the search terms I used in hope that search engines show this Issue if someone searches for a solution, because search engines show a lot of sea mermaids and not a lot of diagram layout.

Mermaid layout nodes
Mermaid layout elements
Mermaidjs layout elements
Mermaid position elements
Mermaidjs position elements
Mermaid keep elements in position
Mermaid keep layout

**Comment by Polirecyliente** [comment]
You know what? On second thought I will share my case, it doesn't cost me anything.

First of all lets show the need for this solution. Normally, Mermaid nodes that are defined first are placed higher in the hierarchy. This can be overridden by Mermaid itself when there are subgraphs present, because for some reason subgraphs get higher levels in the hierarchy of nodes, even if they are defined after and should therefore come after in the hierarchy.

The basic black box process diagram shows a process as a "black box", in which the process receives inputs and produces outputs. Also, a "black box" process can feed itself by connecting its output to its input. The straightforward way to write a "black box" process diagram (that feeds itself) in Mermaid is:

``` mermaid
flowchart LR
  Input --> Process
  subgraph Process
    A --> B --> C --> A
  end
  Process --> Output
  Output --> Input
```
This produces the following image:
![o2](https://user-images.githubusercontent.com/52269801/115100967-27209900-9f06-11eb-9942-47f035556b2e.png)

As can be seen, the Input is not in to the left anymore, because its place in the hierarchy has been taken by the subgraph.

Giving credit to @XertroV the fixed Mermaid code is

``` mermaid
flowchart TB
  Input
  subgraph s1 [" "]
    Input --> Process
    subgraph s2 [" "]
      subgraph Process
        A --> B --> C --> A
      end
      Process --> Output
	end
  end
  Output --> Input
  
  classDef class1 fill: white, stroke: white
  class s1,s2 class1
  style Process fill: white, stroke: black
```

![o1](https://user-images.githubusercontent.com/52269801/115101004-72d34280-9f06-11eb-8674-014ab8af99f2.png)

This correctly shows the "black box" process between the inputs and the outputs.

**Comment by ferrieux** [comment]
@knsv 
> Is this still a problem? If so please reopen it.

Yes, it is a show stopper. I heavily invested on Mermaid for flowcharts, the idea is absolutely neat, but devil in details like this one end up killing the whole experience:
 - impossible to even *predict* (let alone *force*, as suggested here) node layout
 - same for arrows that randomly zigzag when crossing subnet boundaries
 - impossible to touch node padding (it is not a CSS attribute, it is hardcoded in SVG geometry)

I'd suggest replacing the complicated/unmaintainable algorithm with a simple, predictable and documented one: this way, granted, authors will need to work a bit more to reach their goals, but they'll end up with the job done instead of banging their heads until they drop Mermaid.

**Comment by wizlee** [comment]
Comment here as a show of hand. A suggestion is perhaps to include this inside directives as a configuration.

**Comment by DuncanHills** [comment]
Started using mermaid inside our org for docs and ran into this issue.

**Comment by bjohas** [comment]
Same here.

**Comment by benoit-dubreuil** [comment]
Same

**Comment by matthiasg** [comment]
Same here :)

**Comment by jtbandes** [comment]
I'm interested in the workarounds offered in this thread using subgraphs. However, I haven't found any combination of 

First I have these nodes in order:
```mermaid
flowchart LR
subgraph foo
    foo1
    foo2
    foo3
end
```

Now I'd like to add an arrow from foo3 back to foo1, without changing the position of any nodes. But when I add an edge, the nodes move around:

```
flowchart LR
subgraph foo
    foo1
    foo2
    foo3 --> foo1
end
```

```mermaid
flowchart LR
subgraph foo
    foo1
    foo2
    foo3 --> foo1
end
```

How would I apply the subgraph workaround in this situation? I've tried subgraphs around lots of different groups of nodes, but nothing seems to allow me to make the nodes line up in their original order.

**Comment by StupydHors** [comment]
If somebody encounters this thread searching for a way to re-order columns in a sequence diagram I have settled upon just adding a simple `Note over Actor1, Actor2: Title of the Sequence`

**Comment by jpl-jengelke** [comment]
Why is this closed? Node ordering remains **_very broken_**. 

Auto-closing tickets because they age doesn't make the problem go away. ...

**Comment by Warfront1** [comment]
The most insidious aspect of this issue, is you can work on a diagram for a few hours, and make one connection that changes the whole shape of your chart.

My specific use case was tracking the flow of multiple electrical connectors with a chart.
The chart and nodes modeled the electrical connector as you would see it in person (in a particular order)
Without proper ordering this chart is actually dangerous as it no longer resembles the real world object.
It actually becomes a liability.

**Comment by knsv** [comment]
> I'd suggest replacing the complicated/unmaintainable algorithm with a simple, predictable and documented one: this way, granted, authors will need to work a bit more to reach their goals, but they'll end up with the job done instead of banging their heads until they drop Mermaid.

I feel your pain! If I understand you correctly you are proposing a syntax for user controlled layout. Where you tell mermaid that A should positioned to the right of, or below of etc. That is interesting but would be new flowchart type.

I think there are possible paths here:
1. Improving tools like invisible lines, length of lines etc to help users modify the layout
2. A new diagram type for manual layout

**Comment by ferrieux** [comment]
Hello Knut,

First, I'm very glad to see your interest in this. Here is how I would tackle it:

To me, the very core of the beauty and appeal of Mermaid, beyond its being an non-wysiwyg, ASCII, greppabble and diff-friendly format,  is its **simplicity**. So, I'm rather reluctant to drop that by completely changing the format and inventing a new type; better to just add config options to convey constraints here and there.

Now what constraints exactly ?
  * your idea of line length is interesting; a variant could be "line strength", like a spring rigidity in physics, that would be easier to the human mind, and more scalable than lengths (when dozens of nodes are added to an existing graph)
  * invisible lines, on the other hand, would only be prorogating the existing *mysterious* effect of adding an edge, without making it any more predictable.
  * one very simple primitive I find myself wanting, is just "node A should be above / at the same Y position as node B (for a vertical layout)"; it might even be sufficient in 99.9% of cases. Bring in the same for X (still in a vertical layout) and you pretty much reach 100% ;)
  * maybe I'm missing a few corner cases ; I'm open to refining the mechanism when they show up.

What do you think ?

**Comment by knsv** [comment]
That makes sense, I also like this option better. The trick is what you can and can not do with dagre. The first steps is deep dive there to find proper solutions. Meanwhile collecting and simplifying workarounds should also be done.

Collecting as in a troubleshooting guide in the docs etc.

**Comment by sidharthv96** [comment]
Related: #3357

**Comment by knsv** [comment]
Som action in this one now as the lazy loading is in place which opens up for more layout algorithms. I am comparing cytoscape and elk as additional layout algorithms. Elk seems very promising even though the library is huge.

For small diagrams all is well but with bigger ones elks is superior to the dagre algorithm currently in use. 

Activation of this would something like `flowchart elk LR` or `flowchart-elk LR`.

**Comment by artk42** [comment]
@knsv that's awesome! how to give a test? i'm a bit new to the mermaid's dev process

**Comment by Delfana** [comment]
I found a less complicated way to fix this particular example.

> The basic black box process diagram shows a process as a "black box", in which the process receives inputs and produces outputs. Also, a "black box" process can feed itself by connecting its output to its input. The straightforward way to write a "black box" process diagram (that feeds itself) in Mermaid is:
> 
> 
> This produces the following image: ![o2](https://user-images.githubusercontent.com/52269801/115100967-27209900-9f06-11eb-9942-47f035556b2e.png)
> 
> As can be seen, the Input is not in to the left anymore, because its place in the hierarchy has been taken by the subgraph.
> 

I put the nodes in separate subgraphs and made the connections in the main graph.
It doesn't matter if the connections or the subgraphs are defined first. But the order of the subgraphs matters. I haven't figured out what the rules are though...

``` mermaid
flowchart LR
    Input --> Process
    Process --> Output
    Output --> Input

    subgraph Process
      A --> B --> C --> A
    end
    subgraph sgOutput [" "]
      %% It works without this subgraph in this example. Not sure why.
      Output
    end
    subgraph sgInput [" "]
      Input
    end

  style Process fill: white, stroke: black
  classDef class1 fill: white, stroke: white
  class sgOutput,sgInput class1
```

**Comment by Delfana** [comment]
Here's an ugly fix for https://github.com/mermaid-js/mermaid/issues/815#issuecomment-1048975586. 

> First I have these nodes in order:
> ``` mermaid
> flowchart LR
> subgraph foo
>     foo1
>     foo2
>     foo3
> end
> ```
> 
> Now I'd like to add an arrow from foo3 back to foo1, without changing the position of any nodes. But when I add an edge, the nodes move around:
> ``` mermaid
> flowchart LR
> subgraph foo
>     foo1
>     foo2
>     foo3 --> foo1
> end
> ```
> 
> 
> How would I apply the subgraph workaround in this situation? I've tried subgraphs around lots of different groups of nodes, but nothing seems to allow me to make the nodes line up in their original order.

I used the w/o in https://github.com/mermaid-js/mermaid/issues/815#issuecomment-1200069093 and added invisible connections between all the nodes to keep them in the correct order. I wasn't able to get them on a crisp line though.
The direction needs to be defined in the subgraph. It doesn't matter what the direction in the main graph is set to in this example.

``` mermaid
flowchart 

subgraph foo
    direction LR
    foo1 ---
    foo2 ---
    foo3 ---> foo1
end

linkStyle 0 stroke-width:0px
linkStyle 1 stroke-width:0px
```

``` 
flowchart 

subgraph foo
    direction LR
    foo1 ---
    foo2 ---
    foo3 ---> foo1
end

linkStyle 0 stroke-width:0px
linkStyle 1 stroke-width:0px
```

**Comment by felixsanz** [comment]
Why is this closed?

**Comment by sidharthv96** [comment]
```mermaid
info
```

Github is on v9.3.0. So I guess it'll be a while till it's released.

**Comment by aScHEABL** [comment]
> **Hi! Sorry for the slow response.**
> 
> The posisitioning of the nodes are done by a layout algorithm and sometimes that one is not perfect and worksarounds like the one is required. I am aware of this but is not easy to fix. I have half an idea of adding more layout algorithms and the possibility to pick the one thats best fits a particular use case.
> 
> The project has got good traction but it also means that it is very hard to manage all issues on your spare time. I am trying to get a bigger team together for faster development and better support #866. I am closing this one for now, not out of disrespect but as a part of an effort to clean out stale issues that has been resolved but not closed.
> 
> Is this still a problem? If so please reopen it.

Why did you close this issue when it's not resolved? The solutions provided above is still broken and not inconvenient at all.
And need a better documentation.

**Comment by duaneking** [comment]
FYI, This is the biggest bug that I encounter in mermaid daily.

**Comment by dimavs** [comment]
> No single engine can solve the layout correctly, making all job for creation any complex diagram useless UNPREDICTABLY.

It doesn't even have to be complex, you can't put just four simple squares properly:
```
C4Context

Boundary(foo, "foo (on top of bar)", "") {
  Deployment_Node(foo_l, "FOO L", "") {
    Container(foo_lc, "CONT L", "", "")
  }  
  Deployment_Node(foo_r, "FOO R", "") {  
    Container(foo_rc, "CONT R", "", "")
  }
}

Boundary(bar, "bar (under foo)", "") {
  Deployment_Node(bar_node, "BAR NODE", "") {  
    Container(bar_l, "CONT L", "", "")
    Container(bar_r, "CONT R", "", "")
  } 
}

UpdateLayoutConfig($c4ShapeInRow="4", $c4BoundaryInRow="1")
```

**Comment by Ryan-Millard** [comment]
> 🎉 [XertroV@aa670ef](https://github.com/XertroV/mermaid/commit/aa670effa3aeb7ebc25462cc5dcee08279ee2c8a)
> 
> Invisible subgroups to force ordering:
> 
> ![image](https://user-images.githubusercontent.com/1046448/86331023-db10aa80-bc8b-11ea-96be-8b91d509c828.png)
> 
> It does stretch out the graph a bit, but works for my purposes
> 
> a side effect is that sub-trees will now not overlap vertically, which might or might not be good:
> 
> (in this example I'd put those two labeled subgraphs in to force this so it was easier to read)
> 
> ![image](https://user-images.githubusercontent.com/1046448/86331748-da2c4880-bc8c-11ea-9efc-d873471a8662.png)
> 
> rendering example from @joe733 above
> 
> ![image](https://user-images.githubusercontent.com/1046448/86332266-a30a6700-bc8d-11ea-8543-312a24e042db.png)
> 
> with generated code:

To add more onto this, a CSS class can also be used to make it look like the subgraph isn't even there.

### Original
```mermaid
graph TD
r["e "]
subgraph sg.r ["#nbsp;"]
r --- r.0["E "]
subgraph sg.r.0 ["#nbsp;"]
r.0 --- r.0.0["E "]
subgraph sg.r.0.0 ["#nbsp;"]
r.0.0 --- r.0.0.0["T "]
subgraph sg.r.0.0.0 ["#nbsp;"]
r.0.0.0 --- r.0.0.0.0["F "]
subgraph sg.r.0.0.0.0 ["#nbsp;"]
r.0.0.0.0 --- r.0.0.0.0.0["num"]

end
end
end
r.0 --- r.0.1["+"]

r.0 --- r.0.2["T"]
subgraph sg.r.0.2 ["#nbsp;"]
r.0.2 --- r.0.2.0["F"]
subgraph sg.r.0.2.0 ["#nbsp;"]
r.0.2.0 --- r.0.2.0.0["num"]

end
end
end
r --- r.1["*"]

r --- r.2["T"]
subgraph sg.r.2 ["#nbsp;"]
r.2 --- r.2.0["F"]
subgraph sg.r.2.0 ["#nbsp;"]
r.2.0 --- r.2.0.0["num"]

end
end
end

```

### With CSS
```mermaid
graph TD
r["e "]
subgraph sg.r ["#nbsp;"]
r --- r.0["E "]
subgraph sg.r.0 ["#nbsp;"]
r.0 --- r.0.0["E "]
subgraph sg.r.0.0 ["#nbsp;"]
r.0.0 --- r.0.0.0["T "]
subgraph sg.r.0.0.0 ["#nbsp;"]
r.0.0.0 --- r.0.0.0.0["F "]
subgraph sg.r.0.0.0.0 ["#nbsp;"]
r.0.0.0.0 --- r.0.0.0.0.0["num"]

end
end
end
r.0 --- r.0.1["+"]

r.0 --- r.0.2["T"]
subgraph sg.r.0.2 ["#nbsp;"]
r.0.2 --- r.0.2.0["F"]
subgraph sg.r.0.2.0 ["#nbsp;"]
r.0.2.0 --- r.0.2.0.0["num"]

end
end
end
r --- r.1["*"]

r --- r.2["T"]
subgraph sg.r.2 ["#nbsp;"]
r.2 --- r.2.0["F"]
subgraph sg.r.2.0 ["#nbsp;"]
r.2.0 --- r.2.0.0["num"]

end
end
end

style sg.r fill:none,stroke:none
style sg.r.0 fill:none,stroke:none
style sg.r.0.0 fill:none,stroke:none
style sg.r.0.0.0 fill:none,stroke:none
style sg.r.0.0.0.0 fill:none,stroke:none
style sg.r.0.2 fill:none,stroke:none
style sg.r.0.2.0 fill:none,stroke:none
style sg.r.2 fill:none,stroke:none
style sg.r.2.0 fill:none,stroke:none
```
Above, only a small amount of CSS has been added (see below). 
```
style sg.r fill:none,stroke:none
style sg.r.0 fill:none,stroke:none
style sg.r.0.0 fill:none,stroke:none
style sg.r.0.0.0 fill:none,stroke:none
style sg.r.0.0.0.0 fill:none,stroke:none
style sg.r.0.2 fill:none,stroke:none
style sg.r.0.2.0 fill:none,stroke:none
style sg.r.2 fill:none,stroke:none
style sg.r.2.0 fill:none,stroke:none
```

This can also be replaced with classes, but that's a separate concern.

**Comment by orrymr** [comment]
Mermaid is such a great project and I'd love to use it. But this issue is a show stopper for me. 
Would it be possible to reopen this issue? I cannot get the subgraph workaround to do what I want; it still bungles the ordering.
