### ISSUE TITLE
"During rendering these classes are extracted from the..." 

### ISSUE THREAD

**Issue by thef1stofhername** [mermaid-js/mermaid#893]
**Describe the bug**
The documentation is unfinished

**To Reproduce**
1. Go to https://mermaidjs.github.io/#/sequenceDiagram?id=styling
2. See error

**Expected behavior**
How to use css to style your lovely sequence diagrams

**Screenshots**
![Screenshot_2019-07-25 Sequence diagram - mermaid - Markdownish syntax for generating flowcharts, sequence diagrams, class d](https://user-images.githubusercontent.com/36307579/61908666-2eb43900-aefe-11e9-80a1-0c1c0e74ff74.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 68.0.

**Comment by antoniomolram** [comment]
I visited also this section and I was not able to figure out how to apply styles to a sequenceDiagram.@knsv, any idea? Thank you!!

**Comment by vikyaiyer** [comment]
#974

**Comment by GDFaber** [comment]
This issue has already been solved by #974 which was merged in October 2019, so  we can close here.
