### ISSUE TITLE
Flowchart: wrong escaping in non-html mode

### ISSUE THREAD

**Issue by bennybenami** [mermaid-js/mermaid#903]
**Describe the bug**
In a flowchart diagram, when working in a non-html mode, =,<,> symbols are translated into their html form (e.g. &equals)

**To Reproduce**
The following simple diagram:
graph TD
A["a=b"] 

with this configuration:
{
  "theme": "default",
  "flowchart": {
    "htmlLabels": false
  }
}

results with a square containing the following text:
a & equals; b

**Expected behavior**
 a square with the label a=b

**Screenshots**
https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcbkFbYT1iXSAiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCIsImZsb3djaGFydCI6eyJodG1sTGFiZWxzIjpmYWxzZX19fQ

**Comment by spbert29** [comment]
If you add securityLevel: loose to your config, it works.
I dont think that this should work and I would classify this as a Bug:

Working:
![image](https://user-images.githubusercontent.com/42182294/64408431-0be17c80-d087-11e9-8da0-ae08111d9ddb.png)

Not Working:
![image](https://user-images.githubusercontent.com/42182294/64408467-2156a680-d087-11e9-9ef5-c5e89bc55497.png)
