### ISSUE TITLE
Individual linkStyle behaves differently than default linkStyle

### ISSUE THREAD

**Issue by ppqn** [mermaid-js/mermaid#910]
**Describe the bug**

When using linkStyle default, the link label is doesn't change; but when using linkstyle [number], the link label loses its background and doesn't hover over the link.

**To Reproduce**
1. Go to https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFI7XG4gIEFGe0FGfVxuICBVW1VdXG4gIFUtLVdJLS0-QUY7XG4gIFUtLU5MUC0tPkFGO1xuICBsaW5rU3R5bGUgZGVmYXVsdCBmaWxsOm5vbmUsc3Ryb2tlOmdyZWVuLHN0cm9rZS13aWR0aDoxcHg7XG4gIGxpbmtTdHlsZSAxIGZpbGw6bm9uZSxzdHJva2U6cmVkLHN0cm9rZS13aWR0aDoxcHg7IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

2. See the difference between WI and NLP

Code:
```mermaid
graph LR;
  AF{AF}
  U[U]
  U--WI-->AF;
  U--NLP-->AF;
  linkStyle default fill:none,stroke:green,stroke-width:1px;
  linkStyle 1 fill:none,stroke:red,stroke-width:1px;
```

**Expected behavior**
NLP should look like WI

**Screenshots**

|||
|-|-|
|Expected|![Annotation 2019-08-22 114050](https://user-images.githubusercontent.com/29017154/63529504-be83dd80-c4d2-11e9-90ca-1497cb631297.png)|
|Actual|![Annotation 2019-08-22 113927](https://user-images.githubusercontent.com/29017154/63528766-8af48380-c4d1-11e9-8bef-20d28479a6c7.png)|

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 8.2.3

**Comment by GDFaber** [comment]
I've stumbled across this while working on #1088 today and got it basically fixed, but need to do more testing to make sure it's working properly with different settings.

**Comment by chris579** [comment]
I will assign you in the meanwhile. If you verified that you fixed it, make sure to mention both issues in your pr. Thanks!

**Comment by GDFaber** [comment]
Thanks, will do.

**Comment by GDFaber** [comment]
My PR is at #1132.
