### ISSUE TITLE
Help for a forum and Color lines and online tools

### ISSUE THREAD

**Issue by Dylantje** [mermaid-js/mermaid#911]
Dear all.
Sorry for this wrong place..
Only where can i find a forum or something?
I found Mermaid Live Editor online

And create:
[Link](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbnN0eWxlIEEgZmlsbDojZjlmLHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDo0cHhcbkFbUGFuYXNvbmljPGJyPkxldmVsIzJdID09PXxBYW52b2VyfCBCdCBcbkEoUGFuYXNvbmljKSA9PT18UmV0b3VyfCBCdFxuc3R5bGUgQyBmaWxsOmN5YWFuLHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDo0cHhcbnN0eWxlIEJ0IGZpbGw6I2YwZixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4XG5CdChcIiBcIilcbkJ0IC0tPnxBYW52b2VyfCBDKEdhcmFnZSlcbkJ0IC0tPiB8UmV0b3VyfCBDKEdhcmFnZSlcbnN0eWxlIER0IGZpbGw6cmVkLHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHhcbkR0KFwiIFwiKVxuQnQgPT09IHxBYW52b2VyfCBEdFxuQnQgPT09fFJldG91cnwgRHRcbnN0eWxlIEV0IGZpbGw6Ymx1ZSxzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4XG5FdChcIiBcIilcbkR0ID09PXxBYW52b2VyfEV0XG5EdCA9PT18UmV0b3VyfEV0XG5EdCAtLT4gfEFhbnZvZXJ8RihCaWpLZXVrZW4pXG5EdC0tPnxSZXRvdXJ8RihCaWprZXVrZW4pXG5zdHlsZSBGIGZpbGw6eWVsbG93LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHhcbnN0eWxlIEd0IGZpbGw6Z3JlZW4sc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjJweFxuR3QoXCIgXCIpXG5FdCA9PT18QWFudm9lcnxHdFxuRXQgPT09fFJldG91cnxHdFxuc3R5bGUgSCBmaWxsOmxpZ2h0Z3JlZW4sc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjJweFxuRXQtLT4gfEFhbnZvZXJ8SChLZXVrZW4pXG5FdCAtLT4gfFJldG91cnxIKEtldWtlbilcbnN0eWxlIEl0IGZpbGw6eWVsbG93LHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHhcbkl0KFwiIFwiKVxuR3QgID09PXxBYW52b2VyfEl0XG5HdCA9PT18UmV0b3VyfEl0XG5zdHlsZSBKIGZpbGw6bGlnaHRwdXJwbGUsc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjJweFxuR3QtLT4gfEFhbnZvZXJ8SihBY2h0ZXJrYW50KVxuR3QgLS0-fFJldG91cnxKKEFjaHRlcmthbnQpXG5zdHlsZSBLIGZpbGw6I2NjZixzdHJva2U6I2Y2NixzdHJva2Utd2lkdGg6MnB4LHN0cm9rZS1kYXNoYXJyYXk6IDUsIDVcbkl0LS0-IHxBYW52b2VyfEsoVlYga2V1a2VuKVxuSXQtLT4gfFJldG91cnxLKFZWIEtldWtlbiApXG5zdHlsZSBMdCBmaWxsOiNjY2Ysc3Ryb2tlOiNmNjYsc3Ryb2tlLXdpZHRoOjJweCxzdHJva2UtZGFzaGFycmF5OiAxLCA1XG5cbkx0KFwiIFwiKVxuSXQgID09PXxBYW52b2VyfEx0XG5JdCA9PT18UmV0b3VyfEx0XG5zdHlsZSBNIGZpbGw6bGlnaHRncmVlbixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4XG5zdHlsZSBNTSBmaWxsOm9yYW5nZSxzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4XG5MdCA9PT0gfEFhbnZvZXJ8TShTdGFuZGxlaWRpbmcpXG5MdCA9PT0gfFJldG91cnxNKFN0YW5kbGVpZGluZylcbk0oU3RhbmRsZWlkaW5nKSA9PT0gTU1NW1ZlcmRlbGVyXVxuTShTdGFuZGxlaWRpbmcpLS0tTU1bQm92ZW52ZXJkaWVwaW5nXVxuTShTdGFuZGxlaWRpbmcpID09PSBNTU1bVmVyZGVsZXJdXG5cblxuTU1NW1ZlcmRlbGVyXSAgPT09IFoxKFpvbGRlcilcbk1NTVtWZXJkZWxlcl0gID09PSBaMShab2xkZXIpXG5aMShab2xkZXIpLS0tWlooWm9sZGVydmVyZGllcGluZylcbloxKFpvbGRlcikgLS0tWjIoIFZvb3JrYW50KVxuWjEoWm9sZGVyKSAtLS0gWjMoIEFjaHRlcmthbnQpXG5NTU1bVmVyZGVsZXJdIC0tLSBNTU1NKChTbGFhcGthbWVyIDEpKVxuTU1NW1ZlcmRlbGVyXSAtLS0gTU1NTSgoU2xhYXBrYW1lciAxKSlcbk1NTVtWZXJkZWxlcl0gLS0tIE1NTTEoKEJhZGthbWVyKSlcbk1NTVtWZXJkZWxlcl0gLS0tIE1NTTEoKEJhZGthbWVyKSlcbk1NTVtWZXJkZWxlcl0gLS0tIE1NTTIoKEpvbmdlbnMgMSkpXG5NTU0yKChKb25nZW5zIDEpKSAtLS0gTU1NMygoSm9uZ2VucyAyKSlcbk1NTTMoKEpvbmdlbnMgMikpIC0tLSBNTU1bVmVyZGVsZXJdIFxuXG5QdChcIiBcIilcbk50IC0tLXxSZXRvdXJ8IFB0XG5OdCAtLS0gfEFhbnZvZXJ8UHRcblxuXG5cbk50KFwiIFwiKVxuTHQgPT09IE50XG5MdCA9PT0gTnRcbnN0eWxlIE50IGZpbGw6bGlnaHRncmVlbixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4XG5zdHlsZSBPIGZpbGw6bGlnaHRncmVlbixzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4XG5zdHlsZSBPTyBmaWxsOmxpZ2h0Z3JlZW4sc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjJweFxuc3R5bGUgUHQgZmlsbDpsaWdodGdyZWVuLHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHhcbnN0eWxlIFEgZmlsbDp5ZWxsb3csc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjJweFxuc3R5bGUgWCBmaWxsOnllbGxvdyxzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4XG5cblB0IC0tPiB8QWFudm9lcnxRKFZvb3JrYW50IEtsZWluKVxuUHQgLS0-IHxSZXRvdXJ8UShWb29ya2FudCBLbGVpbilcblB0IC0tPiB8QWFudm9lcnxYKFZvb3JrYW50IEdyb290KVxuUHQgLS0-IHxSZXRvdXJ8WChWb29ya2FudEdyb290KVxuTnQgLS0tIHxSZXRvdXJ8IE8oR2FuZylcbk8oR2FuZykgLS0tIE9PKFdjKVxuT08oV2MpIC0tLSB8QWFudm9lcnwgTnQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

Only is mis some things...
How to color some lines?
How to strecht lines so the are stragt

And perhaps better and other online tools..

Or a forum..

Hope some...

Thanks

**Comment by knsv** [comment]
Hi!

This is possible but a bit crude perhaps. It is described in the documentation, https://mermaidjs.github.io/#/flowchart?id=styling-and-classes

Hope this helps.

# Styling links
It is possible to style links. For instance you might want to style a link that is going backwards in the flow. As links have no ids in the same way as nodes, some other way of deciding what style the links should be attached to, is required. Instead of ids, the order number of when the link was defined in the graph is used. In the example below the style defined in the linkStyle statement will belong to the fourth link in the graph:

linkStyle 3 stroke:#ff3,stroke-width:4px;

**Comment by Dylantje** [comment]
Dear..
Thanks...
Only this working in the live editor.
Only when i try this lokal, no color to see

I run on the last version

**Comment by mshirey** [comment]
I agree this is a bit crude as I'm having a hell of a time trying to style the links.  Even trying to color them by index doesn't see to work reliably as the results appear rather random.  I'm guessing the order you're drawing the links is not identical to the order they are defined.
A related question though, I've tried to apply a default style to all of the links, but it only affects the normal links, the thicker links are not affected.  

Is there a different comment/selector for the thicker links?  Also related... is there a styling reference for all of the selectors and properties?

Thank you!

**Comment by jgreywolf** [comment]
@Dylantje @mshirey  Is this still an issue for you with the current version of Mermaid? [Live Editor](https://mermaid-js.github.io/mermaid-live-editor)
