### ISSUE TITLE
Chaining of vertices for flowcharts

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#916]
The syntax would be more concise if it was possible to allow multiple vertice statements on one row.

An example:
**Before**
```
graph TB
  a-->b
  b-->c
  c-->d
```
**With chaining**
```
graph TB
  a-->b-->c-->d
```

**Comment by GDFaber** [comment]
Cool, this takes care of #836 and #751 (perhaps #670 but I'm not entirely sure about that one).

**Comment by Dunning-Kruger** [comment]
Hey @jgreywolf. I would love to leave this issue assigned to you before closed so it permanently displays that you developed it. Could you leave a comment or something so I can assign you this story?
