### ISSUE TITLE
Callback with Parameters

### ISSUE THREAD

**Issue by spbert29** [mermaid-js/mermaid#921]
**Is your feature request related to a problem? Please describe.**
When I try to add some Parameters for a function the rendering fails cause of parsing - I dont know if it is related, i didnt found a solution/question about it here. If there is a Solution feel free to close this issue.

**Describe the solution you'd like**
It would be nice if it is possible to add some Parameters something like this:
` graph TD
            A-->B
            B-->C
            click A callback(www.google.at) "Open URL"`
`<script>
    function callback(url){
        console.log(url);
    }
</script>`

**Describe alternatives you've considered**
The alternative is to generate the JS Functions automated and for every parameter once when loading the Flowchart, but this should only be a workaround:
` graph TD
            A-->B
            B-->C
            click A callback_google "Open URL"
            click B callback_nhl "Open URL"`

`<script>
    function callback_google(){
        console.log(www.google.at);
    }
    function callback_nhl(){
        console.log(www.nhl.com);
    }
</script>`

**Additional context**
![image](https://user-images.githubusercontent.com/42182294/64096817-e8ef5980-cd62-11e9-8a71-d8b8f794f036.png)

**Comment by knsv** [comment]
This is not planned but I approve of the idea!

**Comment by Dunning-Kruger** [comment]
To add to the suggestion, I would pass the node name as parameter instead of having a customizable parameter. That would have 0 impact in the syntax and allow the same (and more) uses.

**Comment by Dunning-Kruger** [comment]
@keenanjt33 If you'd like, please leave a comment so I can assign you the issue.
