### ISSUE TITLE
How can I style the text of a specific node rather than the whole text of a flowchart?

### ISSUE THREAD

**Issue by georgelichen** [mermaid-js/mermaid#923]
How can I style the text of a specific node rather than the whole text of a flowchart?  Thank you in advance.

**Comment by spbert29** [comment]
You can add a class like this:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5jbGFzc0RlZiB0ZXN0IGZpbGw6bGlnaHRibHVlLGNvbG9yOmdyZWVuLHN0cm9rZTojRkY5RTJDXG5jbGFzcyBBIHRlc3QiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

[Here ](https://mermaidjs.github.io/#/flowchart?id=styling-and-classes)you can find the man

**Comment by georgelichen** [comment]
> You can add a class like this:
> 
> https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5jbGFzc0RlZiB0ZXN0IGZpbGw6bGlnaHRibHVlLGNvbG9yOmdyZWVuLHN0cm9rZTojRkY5RTJDXG5jbGFzcyBBIHRlc3QiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ
> 
> [Here ](https://mermaidjs.github.io/#/flowchart?id=styling-and-classes)you can find the man

Thank you for the reply.  But your sample shows how to style a specific node rather than the text of that node, such as the text font or text size.  I'd like to find a way to style the text of a node specially which will have different font, text size, text color from the text from other nodes.

**Comment by jgreywolf** [comment]
All you have to do is to set the style for text as already shown above.  See here:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG5cbmNsYXNzRGVmIHRlc3QgY29sb3I6Z3JlZW4sZm9udC1mYW1pbHk6YXJpYWwsZm9udC1zaXplOjEwcHhcbmNsYXNzIEEgdGVzdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

**Comment by georgelichen** [comment]
Thank you jgreywolf for you reply！
