### ISSUE TITLE
How To Load mermaid from AMD or Require.js?

### ISSUE THREAD

**Issue by radiantone** [mermaid-js/mermaid#925]
Hi,
  I would like to load mermaid using Require.js but it seems the way it is set up, this cannot work.

**Comment by jgreywolf** [comment]
Is this still an issue/request?
@radiantone

**Comment by colombod** [comment]
any update?

**Comment by sidharthv96** [comment]
We will be switching to ESM only in v10 (#4108)
You could try something like https://www.npmjs.com/package/requirejs-esm

There are no plans in our roadmap to support non ESM right now.
