### ISSUE TITLE
callback is not called when provided for graphs that does not support interactivity

### ISSUE THREAD

**Issue by xiaoxiao426** [mermaid-js/mermaid#930]
**Describe the bug**
I found that you change the code about "src/mermaidAPI.js" on August 11, 2019, the changed code as follwing:
```
if (typeof cb !== 'undefined') {
   - cb(svgCode, flowDb.bindFunctions)
   - cb(svgCode, ganttDb.bindFunctions)
   + case 'flowchart':
   +    cb(svgCode, flowDb.bindFunctions)
   +   break;
   + case 'gantt':
   +     cb(svgCode, ganttDb.bindFunctions)
   +    break;
   +    default:
   + }
   + } else {
    - logger.warn('CB = undefined!')
    +  logger.debug('CB = undefined!')
    + }
```
these new code leads to my problem. before changed, my code operate normally。
**To Reproduce**
1. when draw the grapg of "sequenceDiagram"
2. execute this following code will console error info: "bindFunctions is not a function": ```mermaid.render(eleId, definition, (svgCode, bindFunctions) => {'}```
3. and the display of graph is abnormal

**Screenshots**
![image](https://user-images.githubusercontent.com/30727788/65105186-b00fdf80-da06-11e9-8655-653fa45f3202.png)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [76.0.3809.100（正式版本） （64 位）]

**Additional context**

**Comment by xiaoxiao426** [comment]
Supplementary explanation：
in my opinion， the reason is that: the default case lackof  the params: bindFunctions
![image](https://user-images.githubusercontent.com/30727788/64749551-95da8b00-d548-11e9-8169-651b970d0ade.png)

**Comment by knsv** [comment]
Hi! Thansk for the report. The underlying issue is that sequence diagrams currently does not support interaction.

What happens is that the callback is not called at all for such graphs. This will be addressed

**Comment by jgreywolf** [comment]
Closing based on previous comments that the previous handling reported was a bug that has been fixed, and how to handle
