### ISSUE TITLE
Flowchart: Not able to set style for dotted/Thick links through themes or themeCSS

### ISSUE THREAD

**Issue by sulabh-msft** [mermaid-js/mermaid#935]
**Describe the bug**
FlowChart: Not able to set style the styles for dotted/think links through themes or by specifying styles though `themeCSS` initialize option

Mermaid version 8.2.3

Dotted link
-----
```
graph LR;
   A-.->B;
```
![image](https://user-images.githubusercontent.com/13728069/65026030-569ba800-d955-11e9-9425-4e3dae4b5666.png)

Thick link
----
```
graph LR
   A ==> B
```
![image](https://user-images.githubusercontent.com/13728069/65026497-4a641a80-d956-11e9-9a1b-4240f1fad9dc.png)

**To Reproduce**
1. Go to the Mermaid editor
Code: 

```
graph TD;
A[Christmas] -.->|Get money| B(Go shopping)
```
Theme: default
or Go to the [Mermaid Editor default theme](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG5BW0NocmlzdG1hc10gLS4tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpXG5cblxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)

![image](https://user-images.githubusercontent.com/13728069/65026976-30770780-d957-11e9-8a07-840fb21f6acc.png)

Now change the theme to `dark`
Theme: dark

[Mermaid editor dark theme](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG5BW0NocmlzdG1hc10gLS4tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpXG5cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkYXJrIn19)

Observe the color of dotted link. It is not changing across themes. This is resulting in issue where back-ground is also dark ( dark theme)

![image](https://user-images.githubusercontent.com/13728069/65027157-79c75700-d957-11e9-8d0c-cd51bc5b30d1.png)

**Expected behavior**
The style for dotted/thick links IMO we should have different style for these links in dark theme We should also have it exposed as a separate css class name to that it is customizable through `themeCSS` option.

**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [chrome]
 - Version  76.0.3809.132 

**Additional context**
Looks like the styles are hard coded for dotted/thick links.

Snippet
/// https://github.com/knsv/mermaid/blob/master/src/diagrams/flowchart/flowRenderer.js (line: 193)
```js
    if (typeof edge.style !== 'undefined') {
      edge.style.forEach(function(s) {
        style = style + s + ';';
      });
    } else {
      switch (edge.stroke) {
        case 'normal':
          style = 'fill:none';
          if (typeof defaultStyle !== 'undefined') {
            style = defaultStyle;
          }
          break;
        case 'dotted':
         // ISSUE:  HARD CODED STYLE for dottted
          style = 'stroke: #333; fill:none;stroke-width:2px;stroke-dasharray:3;';  
          break;
        case 'thick':
         // ISSUE:  HARD CODED STYLE for thick
          style = 'stroke: #333; stroke-width: 3.5px;fill:none';   
          break;
      }
    }
```

**Comment by knsv** [comment]
@sulabh-msft Thanks for your the issues you have reported on mermaid. They are all good ideas, valid and excellently reported. I have been looking at UML diagrams during autumn but will give flowcharts more focus now.
