### ISSUE TITLE
when I want zoom in the font ，it will disappear

### ISSUE THREAD

**Issue by Soanguy** [mermaid-js/mermaid#959]
**Desktop (please complete the following information):**
 - OS: [windows 7]
 - Browser [chrome]
 - Version [77.0.3865.90]

![image](https://user-images.githubusercontent.com/24608949/65782683-ccd3b200-e180-11e9-8712-2faf91ae60c3.png)
there is something wrong ， when I try to zoom in ，the characters will be disappeared。
I use this on hexo ，and theme is next。
I dont know which one cause this problem。

**Comment by Dunning-Kruger** [comment]
I could not reproduce this in the [live editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ).

**Comment by simpltek** [comment]
Just a thought, but with certain graphs and fonts, zooming in and out seems like it might require a re-render if the font scaling doesn't match up with the SVG element scaling, no?
