### ISSUE TITLE
How to style the text on the line?

### ISSUE THREAD

**Issue by georgelichen** [mermaid-js/mermaid#962]
It seems the LINKSTYLE is only able to style the line, but not able to style the arrow and the text associated with it.  How to style the text and arrow of a line?

**Comment by ex-nerd** [comment]
Not only that, but the box styling of the link is lost if you add styling to a specific link (though strangely not if you add a `linkStyle default ...`).

**Comment by GDFaber** [comment]
I'll give this one a try next.

**Comment by GDFaber** [comment]
My PR adds the possibility to set the text color of line labels by `color` setting in the link style. I'll create new issues for the other topics mentioned here.

**Comment by GDFaber** [comment]
Hi @georgelichen, please refer to #1236 for arrow heads styling.

**Comment by GDFaber** [comment]
This is not ready yet, I'll move the `styleFromStyleArr` function to utils.js and modify it to return style and labelStyle in one go so it doesn't need to go through all settings twice.
