### ISSUE TITLE
Migrate from node-sass to dart-sass

### ISSUE THREAD

**Issue by Bjego** [mermaid-js/mermaid#986]
You should port your sass library to dart-sass, because node-sass is a legacy implementation and has been replaced by dart-sass.

> Dart Sass is the primary implementation of Sass, which means it gets new features before any other implementation. It's fast, easy to install, and it compiles to pure JavaScript which makes it easy to integrate into modern web development workflows. Find out more or help out with its development on GitHub.
> https://sass-lang.com/dart-sass

And node-sass is based on the C-Based library "Lib-Sass"

> Node-sass is a library that provides binding for Node.js to LibSass, the C version of the popular stylesheet preprocessor, Sass.
> https://github.com/sass/node-sass

**Comment by knsv** [comment]
I will close this issue. Please let me know if there is any outstanding issues.
