### ISSUE TITLE
Simplify font-settings

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#989]
One of the most persistant problems users have when integrating mermaid into their sites is setting the font properly, specifically so that bound are set correctly.

The root cause for this is related to font-settings. If the hidden rendering of the diagram has different font-settings then the final font settings the sizing of the boxes etc will differ.

It would be great if it was possieble to set the font in the configuration. Then the integrator only would need to provide a font-family to the page and set the option font-family in the mermaid options for the rendering to be correct.

This could potentially be set using css variables. So that the variables are being set from configuration at initialize.

**Comment by nothingismagick** [comment]
Right, that explains my font rendering problems and some words getting
cropped. A word of warning though, CSS variables will not work on IE 11

**Comment by knsv** [comment]
thanks for the heads up. Will set a default value then for IE to be overridden by a css variable so IE11 will get the default.
