### ISSUE TITLE
Upstream Peer Dependency dagre

### ISSUE THREAD

**Issue by nothingismagick** [mermaid-js/mermaid#990]
I was just updating my deps, and noticed this. I thought I would mention it, because it seems that the d3 version is out of date ...

```
warning "mermaid > dagre-d3-renderer@0.5.8" has incorrect peer dependency "d3@^4.13.0".
```

Isn't modern d3 `"d3@^5.12.0"`?

(Yes, I know technically that the line here in this project's package.json is:
```json
    "d3": "^5.7.0",
```
So it will properly install 5.12 and any other minor / patch increase. Just wondering if outreach to the dagre repo is warranted.

**Comment by christopherkade** [comment]
Hi @nothingismagick,

Is there really something we can do about it? 

`dagre-d3-renderer` has the following peer dep:

```
"peerDependencies": {
  "d3": "^4.13.0"
},
```

Which conflicts with our own `^5.7.0` version.

**Comment by nothingismagick** [comment]
Let's see where https://github.com/dagrejs/dagre-d3/issues/375 takes us.

**Comment by gordonwoodhull** [comment]
I tested and submitted PRs dagrejs/dagre#376 and tylingsoft/dagre-d3-renderer#11 - take your pick.

**Comment by pravi** [comment]
dagre-d3 merged the pr. @gordonwoodhull thanks! @christopherkade would it be possible to switch to dagre-d3 (dagre-d3-renderer is a fork and I don't know why this was chosen in the first place), which seems more active any way. Also can we use the master branch directly till they make a new release?

**Comment by gordonwoodhull** [comment]
agree, dagre and dagre-d3 were officially unmaintained for a while and got forked then. a new maintainer stepped in and the original repo was reactivated (under a new org).

**Comment by pravi** [comment]
@gordonwoodhull @christopherkade @nothingismagick I have switched to dagre-d3, dagre and graphlib in #1018. Build and test passed. Please review.

**Comment by knsv** [comment]
Part of release 8.4.1

**Comment by knsv** [comment]
Part of release 8.4.1
